### ISSUE TITLE
Crashed when ref to mscorlib, Version=65535.65535.65535.65535, Culture=neutral, PublicKeyToken=b77a5c561934e089

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1004]
![err](https://user-images.githubusercontent.com/2529999/33491338-dc4d6e44-d6f4-11e7-95a1-07aff9d79b57.jpg)

**Comment by siegfriedpammer** [comment]
That's a strange exception. Could you tell me, which assembly you tried to open in ILSpy? Thanks!

**Comment by CreateAndInject** [comment]
I usually meet these assemblies, but now I can find only one, and it's no error in ILSpy2

[Test.zip](https://github.com/icsharpcode/ILSpy/files/1523617/Test.zip)
