### ISSUE TITLE
Boolean operators not decompiled correctly

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1005]
Test case compiled in Release, does not occur in Debug:
```cs
bool Test()
{
    return GetValue() && GetValue();
}

bool Test2()
{
    return GetValue() || GetValue();
}

bool GetValue() => false;
```
Output:
```cs
private bool Test()
{
    if (this.GetValue())
    {
        return this.GetValue();
    }
    return false;
}

private bool Test2()
{
    if (!this.GetValue())
    {
        return this.GetValue();
    }
    return true;
}

private bool GetValue()
{
    return false;
}
```

**Comment by KrisVandermotten** [comment]
What exactly do you mean when you say "not decompiled correctly"? That output looks correct to me.

**Comment by siegfriedpammer** [comment]
It will be impossible for a decompiler to decompile the code exactly as it was written, depending on how it was compiled. So, as long as it's semantically correct and looks somewhat pretty, I'd say it's not a bug.

**Comment by mmusu3** [comment]
I figured this one might be more difficult. I made this issue however because these did decompile back into boolean operators in ilspy v2. If you think this is never going to happen in v3, you can close the issue.

**Comment by dgrunwald** [comment]
The C# compiler emits multiple `ret` instructions for these. We've decided to keep the control flow from IL and not attempt to simplify these into short-circuiting operators.
ILSpy 5 actually has a transform that can do this (`CombineExitsTransform`), but it's only enabled within lambda expressions.
