### ISSUE TITLE
Why is ILSpy no response with this?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1006]
```
[ExportContextMenuEntryAttribute(Header = "Test")]
public class Tester : IContextMenuEntry
{
    public bool IsVisible(TextViewContext context) => context.SelectedTreeNodes.All(n => n is AssemblyTreeNode);
    public bool IsEnabled(TextViewContext context) => true;
    public void Execute(TextViewContext context)
    {
        foreach (AssemblyTreeNode node in context.SelectedTreeNodes)
        {
            var module = node.LoadedAssembly.GetModuleDefinitionAsync().Result;
            foreach (var tr in module.GetTypeReferences())
                tr.Resolve();
        }
    }
}
```
Run ILSpy, select any one assembly, execute command "Test", ILSpy will be no response in "tr.Resolve()"
But there's no problem if I load assembly like this: AssemblyDefinition.ReadAssembly(...)
![er](https://user-images.githubusercontent.com/2529999/33556859-54122094-d940-11e7-9dd5-b50e5bd5fd2e.jpg)

**Comment by CreateAndInject** [comment]
Can you reproduce？

**Comment by siegfriedpammer** [comment]
No, I could not reproduce this. Seems like this is a threading issue. Will be difficult to reproduce, I think.

**Comment by CreateAndInject** [comment]
There are ModuleDefinition & AssemblyDefinition some days ago, but now they are GetModuleDefinitionAsync & GetAssemblyDefinitionAsync, and my code doesk run correctly, can you help me?

**Comment by siegfriedpammer** [comment]
This is a threading issue, currently ILSpy loads references on the UI thread and your command runs on the UI thread as well, when trying to resolve the type, an assembly reference must be loaded -> UI thread dead-loc. Solution: Execute your command on a different thread using Task.Run.

**Comment by CreateAndInject** [comment]
Why it works before the commit 12dc70e05a1362f34af5491faccb2acc97d06704 (2017-11-27)?
ModuleDefinition=GetModuleDefinitionAsyc().Result

**Comment by siegfriedpammer** [comment]
Because before that the assembly resolver did not use a background thread and ILSpy was hanging during startup.

**Comment by siegfriedpammer** [comment]
I am planning to fix this as soon as the AssemblyList/LoadedAssembly API is truly thread-safe.

**Comment by CreateAndInject** [comment]
If I new a new thread, it's hard to use, such:
MainWindow.Instance.SelectedNodes will orrcur : System.InvalidOperationException

**Comment by siegfriedpammer** [comment]
It's not hard at all:

			public void Execute(TextViewContext context)
			{
				var nodes = context.SelectedTreeNodes.OfType<AssemblyTreeNode>().ToArray();
				Task.Run(() => Do(nodes));
			}

			void Do(AssemblyTreeNode[] nodes)
			{ 
				foreach (AssemblyTreeNode node in nodes) {
					var module = node.LoadedAssembly.GetModuleDefinitionAsync().Result;
					foreach (var tr in module.GetTypeReferences())
						tr.Resolve();
				}
			}

**Comment by CreateAndInject** [comment]
So, only Resolve can not run in the UI thread?

**Comment by siegfriedpammer** [comment]
Everything that potentially needs to load an assembly cannot run on the UI as it would dead-lock.

**Comment by CreateAndInject** [comment]
Why this one will be no response:
```
public void Execute(TextViewContext context)
    {
        Form frm = new Form();
        frm.Click += delegate
          {
              foreach (AssemblyTreeNode node in context.SelectedTreeNodes)
              {
                  var module = node.LoadedAssembly.GetModuleDefinitionAsync().Result;
                  Task.Run(() =>
                  {
                      foreach (var tr in module.GetTypeReferences())
                          tr.Resolve();
                      System.Windows.Forms.MessageBox.Show("111");
                  }).Wait();
                  System.Windows.Forms.MessageBox.Show("222");
              }
          };
        frm.Show();
    }
```

and this one will work:
```
public void Execute(TextViewContext context)
    {
        Form frm = new Form();
        frm.Click +=async delegate
          {
              foreach (AssemblyTreeNode node in context.SelectedTreeNodes)
              {
                  var module = node.LoadedAssembly.GetModuleDefinitionAsync().Result;
                  await Task.Run(() =>
                  {
                      foreach (var tr in module.GetTypeReferences())
                          tr.Resolve();
                      System.Windows.Forms.MessageBox.Show("111");
                  });
                  System.Windows.Forms.MessageBox.Show("222");
              }
          };
        frm.Show();
    }
```

**Comment by dgrunwald** [comment]
To be clear: this is a bug in ILSpy; the assembly resolver should not dead-lock with the UI thread.

The bug has been dormant for many years and only now resurfaced because we fixed another bug that prevented loading assemblies in the background.
