### ISSUE TITLE
ILSpy.AddIn sometimes loads binary from obj folder when "opening output in ILSpy"

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1009]

**Comment by christophwille** [comment]
Sample from frontends.sln (right click on Console project, Open output in ILSpy):

// D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\obj\Debug\netcoreapp2.0\ilspycmd.dll

which has no deps file in obj (and thus fails to load assemblies), whereas in 

// D:\GitWorkspace\ILSpy\ICSharpCode.Decompiler.Console\bin\Debug\netcoreapp2.0\ilspycmd.dll

it works as expected
