### ISSUE TITLE
Assembly Decompil Class (Lib) .Unknown result type (might be due to invalid IL)

### ISSUE THREAD

**Issue by StreamXL** [icsharpcode/ILSpy#1011]
Error while viewing de Lib Class

![1](https://user-images.githubusercontent.com/31142317/34066384-03617470-e20e-11e7-82ed-32fb8174b2cb.png)
![2](https://user-images.githubusercontent.com/31142317/34066385-0383412c-e20e-11e7-9d7d-1acb61257492.png)
![3](https://user-images.githubusercontent.com/31142317/34066386-03a20382-e20e-11e7-9748-712642b8e552.png)

[lib.dll.zip](https://github.com/icsharpcode/ILSpy/files/1564440/lib.dll.zip)

**Comment by siegfriedpammer** [comment]
Please note that it is not possible to fully decompile an assembly if a reference is missing. I think this is something we might not be able to fix. So this is not a bug, but expected behavior because we are missing information about some types.

**Comment by siegfriedpammer** [comment]
I cannot analyze the zip file you attached because it only contains a file with the extension ".compressed" which doesn't look like any standard compression format. Can you please use some standard format? zip, 7z, rar?

**Comment by StreamXL** [comment]
Hello siegfriedpammer,
When opening the target assembly with ILSpy, I can see the referenced assemblies as embedded resources

Unfortunately, I do not know what compression the file uses

![1](https://user-images.githubusercontent.com/31142317/34070788-6a476984-e26c-11e7-891e-2346d67f6d70.png)

**Comment by siegfriedpammer** [comment]
You could try to find where the embedded references are unpacked and do the unpacking yourself. Then load the unpacked files in ILSpy and it should be able to decompile everything correctly.

**Comment by StreamXL** [comment]
![2](https://user-images.githubusercontent.com/31142317/34070942-631c319c-e26e-11e7-832a-dc11b4347f20.png)

**Comment by siegfriedpammer** [comment]
Yes, just write some small helper program to do the same. Then load the decompressed files in ILSpy.

**Comment by StreamXL** [comment]
Thank you very much I will do, is there a possibility for her to donate?

then save memorystream to .dll

![2](https://user-images.githubusercontent.com/31142317/34070975-16b60412-e26f-11e7-9008-8d8c80995512.png)

![3](https://user-images.githubusercontent.com/31142317/34070985-475237a8-e26f-11e7-9d32-8bdbcc31d58f.png)

**Comment by siegfriedpammer** [comment]
using System;
    using System.IO;
    using System.IO.Compression;

    class Program
    {
        static void Main(string[] args)
        {
            Decompress(@"C:\temp\lib.dll\costura.lockboxlib.dll.compressed", @"C:\temp\lib.dll\costura.lockboxlib.dll");
        }

        static void Decompress(string compressedFileName, string uncompressedFileName)
        {
            using (var compressedStream = new DeflateStream(new FileStream(compressedFileName, FileMode.Open), CompressionMode.Decompress))
            using (var targetStream = new FileStream(uncompressedFileName, FileMode.CreateNew))
            {
                compressedStream.CopyTo(targetStream);
            }
        }
    }

**Comment by StreamXL** [comment]
Thank you very much maybe you could install such a function directly in ILSpy

**Comment by siegfriedpammer** [comment]
See https://github.com/takeshixx/ILSpy-CosturaPlugin
