### ISSUE TITLE
Program crashes on search sometimes

### ISSUE THREAD

**Issue by greenjaed** [icsharpcode/ILSpy#1014]
When using the search functionality, the program will crash sometimes.  I haven't exactly nailed down the exact cause of the crashes yet.  I've attached the error that appears.  I'm using the latest version of ILSpy (3.0.0.3447)

![ilspy crash](https://user-images.githubusercontent.com/5624793/34171574-a3a1bcdc-e4a3-11e7-83af-88521106adaa.png)

**Comment by siegfriedpammer** [comment]
This is because you have an assembly in the list/tree that does not exist. Try removing the tree nodes with a yellow exclamation mark icon.

**Comment by greenjaed** [comment]
Okay, that fixed the issue, but is that the desired behavior?  I can run version 2.4 and this doesn't happen.

**Comment by siegfriedpammer** [comment]
I was offering a workaround. It will be fixed as soon as I get home.
