### ISSUE TITLE
Feature Request: IL to Emit

### ISSUE THREAD

**Issue by dornfussenegger** [icsharpcode/ILSpy#1015]
It would be very nice if the IL Spy could help writing Emit ILCodes to CS.
For ex: IL_0001: ldarg.0 should result in emitter.Emit(OpCode.ldarg0) - with the same nice output like the "IL with C#" where the code is enriched with comments of the emitted code that is written.
Of course it is not easy - espacally writing method-calls. But it would be a very helpfull tool for people that write a lot of emitted codes.
thank you!

**Comment by conwid** [comment]
Hi everyone,

I though I'd give it a try and created a plugin here:
https://github.com/conwid/ILGenerationLanguage

It's still a very early alpha version, but I'm hoping that some of you might find it useful and even contribute.

**Comment by AceHack** [comment]
I am very interested in this feature

**Comment by dgrunwald** [comment]
I'm not sure if this is something we want in ILSpy itself; seems like a pretty niche use case.
A plugin seems like the better choice.

**Comment by siegfriedpammer** [comment]
Closing this, because this was implemented as a plugin.
