### ISSUE TITLE
Starting ILSpy.exe throws a Windows Protected your PC BSOD on Windows 1709

### ISSUE THREAD

**Issue by muqeet-khan** [icsharpcode/ILSpy#1016]
I am new to ILSpy, but, assumed this was not standard, so reporting it here. 

1. Downloaded from https://github.com/icsharpcode/ILSpy/releases/tag/v3.0.1
2. Extracted on disk. 
3. Ran ILSpy.exe
 
![image](https://user-images.githubusercontent.com/6345044/34309397-6d3b6492-e717-11e7-90cf-6c27881c3fbb.png)

OS: Windows 10 Pro
Version: 1709
Build Number: 16299.125

**Comment by siegfriedpammer** [comment]
This is not a blue screen. It's just that the download link is not yet very popular and thus not recognized by Windows Defender. You can just select "More info" and then select "Run anyway". ILSpy does not contain any malware, spyware or adware. It is completely clean and safe to use.
