### ISSUE TITLE
VS Extension not working (VS2015)

### ISSUE THREAD

**Issue by ljvankuiken** [icsharpcode/ILSpy#1017]
VS2015 There is no ILSpy menu item either in Tools or Solution Explorer context menus.

**Comment by MSeal** [comment]
Having the same issue with v3.0.1 :/

**Comment by M3LiNdRu** [comment]
Same issue for me as well with v1.7.2.0

**Comment by christophwille** [comment]
If someone with VS2015 could actually look into the issue this would be great, because we are short of VS2015 installations.

**Comment by M3LiNdRu** [comment]
Lads,

Installing extension from Visual Studio marketplace worked for me: https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy

However, In vs201,  If I browse a project reference and then I press right click button over it I cannot see the option Open with ILSpy

Cheers

**Comment by siegfriedpammer** [comment]
Support for VS 2015 was removed in 75c45a3 / f227f36d
