### ISSUE TITLE
Can't to decompile big class.

### ISSUE THREAD

**Issue by jclitwin** [icsharpcode/ILSpy#1018]
Yo,

ILSpy gave me error when I to try decompile some big classes.  Someone can to help?

**Comment by christophwille** [comment]
Do you have any samples you can share? (ie reproducible with OSS NuGet packages)

**Comment by jclitwin** [comment]
Yeah, download this DLL and go to **PlayZone.cs** and search _function_: **ProcessNetCommand**.

**Link**: https://drive.google.com/file/d/1WH2dt-P-No47RY9Cu7EpHqv2y_k9sKMz/view?usp=sharing

**Comment by jclitwin** [comment]
I tried with lastest version of the ILSpy, now can to decompile, but function has many "Unknown reuslt type", like:

`//IL_01b6: Unknown result type (might be due to invalid IL or missing references)
//IL_16ea: Unknown result type (might be due to invalid IL or missing references)
//IL_1728: Unknown result type (might be due to invalid IL or missing references)
//IL_272e: Unknown result type (might be due to invalid IL or missing references)
//IL_2743: Unknown result type (might be due to invalid IL or missing references)
//IL_2746: Unknown result type (might be due to invalid IL or missing references)
//IL_2749: Invalid comparison between Unknown and O`
