### ISSUE TITLE
ILSpy.BamlDecompiler.Plugin.dll marked as Trojan by Windows Defender in Windows 10

### ISSUE THREAD

**Issue by hyspace** [icsharpcode/ILSpy#1020]
Today I noticed that Windows Defender reported
`ILSpy_binaries_Net46_Win_3.0.1.3459\ILSpy.BamlDecompiler.Plugin.dll` as Trojan.

Detailed information:
![image](https://user-images.githubusercontent.com/679641/34579323-5a231424-f13d-11e7-8fdd-dadd0a6860df.png)

I wonder if it is a false report.

**Comment by christophwille** [comment]
Please submit the file to virustotal.com to verify

**Comment by hyspace** [comment]
virustotal.com said it is safe. Do you have any idea why it was marked as Trojan?

**Comment by christophwille** [comment]
No, absolutely no idea why Defender would think it is a Trojan... especially because on virustotal.com, it says ok for the MS av engine.

**Comment by christophwille** [comment]
@hyspace could you provide your Defender definition version?

**Comment by sharwell** [comment]
@hyspace It sounds (from emails I sent a bit ago) like the issue may be resolved now. Are you still able to reproduce this?

**Comment by hyspace** [comment]
Sure.
```
Antivirus definition: 1.259.1155.0
Antispyware definition: 1.259.1155.0
```
Let's see if others also meet this problem.

**Comment by sharwell** [comment]
I was not able to reproduce this with 1.259.1153.0. When I checked for updates, it brought me to 1.259.1184.0 where I am also not able to reproduce it.

**Comment by hyspace** [comment]
@sharwell @christophwille I can not reproduce it as well. I restore the dll and manually scan the ILSpy folder and this time it shows nothing. Thanks guys.
