### ISSUE TITLE
Suggestion: Show decompiled .NET libraries during Debug in VS

### ISSUE THREAD

**Issue by XspeedPL** [icsharpcode/ILSpy#1022]
When you are browsing through the call stack at a breakpoint in VS2017 all of the native libraries (ie. mscorlib.dll) show a "Source Not Found" window.
Could the VS extension of ILSpy show the decompiled version instead?
Ideally with the exact line from the call stack highlighted.

Cheers!

**Comment by christophwille** [comment]
Native libraries are not managed code, so this is by definition impossible.

**Comment by XspeedPL** [comment]
Ah, sorry for the confusion.
I meant the .NET libraries 'native' as in 'from GAC', like mscorlib.dll, System.dll, etc..
Those are viewable with ILSpy, but having the view directly in VS debugger would be a huge help.

**Comment by siegfriedpammer** [comment]
This is now built into Visual Studio 16.5: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#decompilation-extraction
