### ISSUE TITLE
C# 7.1: Async Main

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1023]
Specification: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.1/async-main.md
Difficulty: Easy
Time needed: 2-3 hrs

1. Add [unit tests](https://github.com/icsharpcode/ILSpy/wiki/Unit-Tests): In this case only pretty tests make sense.
2. Extend the code in `CSharpDecompiler.MemberIsHidden` to hide the generated `<Main>` method in the decompiled code, if `settings.AsyncAwait` is set.

**Comment by MikeFH** [comment]
Is it OK if I take a look at this ?

**Comment by siegfriedpammer** [comment]
Yes, you are very welcome to submit a pull request for this feature. Please base your pull request on the master branch and follow the guidelines for unit tests.

If you have any questions, feel free to ask!
Thank you for your interest in contributing to this project!
