### ISSUE TITLE
There is no "Analyze" option on right-click pop-up menu

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1027]
It was one of the features I used most in previous ILSpy versions. But in the version 3.0, I didn't see the right click pop-up menu feature. It was removed ? I think it's a very important feature.

![vvv](https://user-images.githubusercontent.com/16493751/34844026-2e8c7d8e-f721-11e7-8ce4-0bca9fd8065b.png)

**Comment by MaxAkbar** [comment]
Try right-clicking on the TreeView pane instead of the code window.

**Comment by Dentrax** [comment]
@MaxAkbar I know that trick, but it's not always useful. It was very useful in pop-up way.

**Comment by Dentrax** [comment]
Would you add this feature to the next-new version? Otherwise it's hard find on the TreeView panel. -,- @siegfriedpammer
