### ISSUE TITLE
DecompilerTypeSystem: need a way to GetCecil() for unresolved entity

### ISSUE THREAD

**Issue by KirillOsenkov** [icsharpcode/ILSpy#1028]
MonoDevelop's AssemblyBrowser deals with IUnresolvedEntities a lot. We need a way to get back to a Cecil object from an IUnresolvedEntity.

Unfortunately the GetCecil() overload that we need is internal:
https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/TypeSystem/DecompilerTypeSystem.cs#L94

Since all the public GetCecil() methods do is retrieve the unresolved entity and call the internal overload, I think it would make sense to make it public so it can be called directly to map from unresolved type system objects to Cecil objects.

**Comment by siegfriedpammer** [comment]
Would you need this change in the nuget release or would a simple patch on the 3.0.x branch suffice? @dgrunwald any objections?

**Comment by KirillOsenkov** [comment]
I’d need this in Roslyn, since we’re using whatever Roslyn is using. If you just batch this with whatever other updates planned, that’d be great. For now we’ve worked around by using Reflection, but it’d be nice to move to real API in the future. It’s not urgent. Thanks!

**Comment by siegfriedpammer** [comment]
@sharwell has made a PR to update the decompiler to 3.0.0.3447 (https://github.com/dotnet/roslyn/pull/24189). Would it be possible to wait for the changes MonoDevelop needs?

@KirillOsenkov are there any other things you would need to get started with MonoDevelop? I would like to include all the necessary changes in the next nuget release.

**Comment by KirillOsenkov** [comment]
I’ll let you know if I find anything next week, but so far this is it! Thanks!

**Comment by sharwell** [comment]
> @sharwell has made a PR to update the decompiler to 3.0.0.3447 (dotnet/roslyn#24189). Would it be possible to wait for the changes MonoDevelop needs?

Probably yes.

**Comment by siegfriedpammer** [comment]
@KirillOsenkov I have made the requested changes, please tell me if there's anything else you would need.

**Comment by KirillOsenkov** [comment]
This is awesome! Thank you! 👍

**Comment by christophwille** [comment]
@sharwell I have uploaded 3.0.1.3460 that includes the requested fix (currently validating).
