### ISSUE TITLE
ILSpy crash when searching

### ISSUE THREAD

**Issue by EFLFE** [icsharpcode/ILSpy#1031]
ILSpy (3.0.1.3459) crash while searching for any word:
![img](https://i.imgur.com/54LDOAX.png)

Found the reason: Library, after obfuscation
![img](https://i.imgur.com/o0sr78N.png)

Do I attach a file? How critical is this bug? Maybe it's my problem that I'm trying to appear a protected library?

**Comment by KirillOsenkov** [comment]
cc @jbevain - what is your stance on hardening Cecil against obfuscated assemblies?

**Comment by jbevain** [comment]
If I get a hand on the assembly, I try to make Cecil not crash.

**Comment by KirillOsenkov** [comment]
@ELFLE - would you please file a new issue over at https://github.com/jbevain/cecil/issues/new and attach the assembly in question?

**Comment by EFLFE** [comment]
I used the ConfuserEx with one rule: "invalid metadata" (This protection adds invalid metadata to modules to prevent disassembler/decompiler from opening them)

**Comment by EFLFE** [comment]
@KirillOsenkov https://github.com/jbevain/cecil/issues/482

**Comment by KirillOsenkov** [comment]
OK so it looks like the assembly is specifically crafted to make Cecil crash :) In that case I think this bug needs a try/catch in AbstractSearchStrategy.Search wrapping the Cecil TypeDefinition.get_Methods() call.
