### ISSUE TITLE
Decompiling types without method bodies?

### ISSUE THREAD

**Issue by KirillOsenkov** [icsharpcode/ILSpy#1032]
Is there support for decompiling whole types without method bodies?

I'd imagine there should be a check here somewhere:
https://github.com/icsharpcode/ILSpy/blob/97efc7b7f5807c47c0316bd7ec51ebb661c4a4a4/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs#L727

Ideally `DecompileType()` should get an optional bool parameter "decompileMethodBodies" (default to true ) that should turn off bodies for methods, properties, events, indexers, constructors, destructors and operators.

This is not really blocking but nice to have so that we can preserve MonoDevelop's "Summary" mode. MonoDevelop currently has AstBuilder.DecompileMethodBodies flag: http://source.monodevelop.com/#MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomMethodNodeBuilder.cs,9ba778e1a1490f5b

**Comment by siegfriedpammer** [comment]
I have thought about this and I think there are some points to discuss:

* (optional) parameter vs. property?
I think adding a bool property would be easier to implement, as there are many different overloads that could result in the syntax tree/string containing a type definition. On the other hand: an instance of `CSharpDecompiler` can be used to generate multiple syntax trees and therefore should be stateless, so I think adding options as properties is not a good idea, but maybe I am overthinking this. 😄 

* I am not quite happy with the name `decompileMethodBodies` as the setting affects property getters/setters and custom events as well.

* Looking at `DecompileBody`: https://github.com/icsharpcode/ILSpy/blob/66d806b2d9a0a21407074d3867a81c846c900217/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs#L780-L793
Without extra logic, it seems that we would not be able to remove some compiler generated attributes and add the `async` modifier, if we're not analyzing the method bodies at all.
Not sure, whether one would expect to not see these attributes and/or the async modifier, when just browsing definitions.

**Comment by KirillOsenkov** [comment]
Here's how I currently achieve this:
https://github.com/mono/monodevelop/pull/3682/commits/55e62ff10d6a796d7504773b2f740452dc860d38

**Comment by siegfriedpammer** [comment]
Yes, removing the method bodies after decompilation is a possibility, albeit a bad one performance-wise. I would like to avoid generating and transforming code that is thrown away right after generation.

**Comment by siegfriedpammer** [comment]
@KirillOsenkov any thoughts on the points I mentioned?

**Comment by siegfriedpammer** [comment]
@KirillOsenkov the PR is merged, can you tell me if there is something else to change for MonoDevelop?
@christophwille Can we publish a new nuget?

**Comment by christophwille** [comment]
@siegfriedpammer please set the version to 3.0.2. Also, should we merge something from master?

**Comment by siegfriedpammer** [comment]
@christophwille changes on master are mainly new features, the only changes that would make sense for a new nuget are: 1e14c8f and (possibly) 97efc7b. Do you think any of these should be cherry-picked?

**Comment by christophwille** [comment]
Yes, I was thinking about the TFM for net45.

**Comment by siegfriedpammer** [comment]
Done, version is `3.0.2.3465`

**Comment by KirillOsenkov** [comment]
Thanks a lot for this work! From reviewing it looks great as far as I can see. We'll pick up the new version with the next Roslyn update, and there's no rush since we have a workaround for now.

Nothing else comes to mind for now, but I'll be sure to open new issues if I discover anything else.

**Comment by christophwille** [comment]
Please see https://github.com/icsharpcode/ILSpy/releases/tag/3.0.2
