### ISSUE TITLE
Option to show code unfolded (expanded) by default

### ISSUE THREAD

**Issue by zvirja** [icsharpcode/ILSpy#1034]
First of all my congratulations with v3 release! 🎉 

Currently all the code is collapsed by default when you open e.g. a class:
![image](https://user-images.githubusercontent.com/1074182/35048888-0d987bd4-fba7-11e7-99f5-39a89dfd9c8b.png)

It's actually very annoying to expand it for each time when you quickly switch across the classes to briefly review their implementations.

Could you please advice whether there is an option to make code expanded by default? I've checked the configuration, but was unable to find the corresponding tweak.

Thanks a lot!

**Comment by bprg** [comment]
Duplicate : https://github.com/icsharpcode/ILSpy/issues/1013
