### ISSUE TITLE
System.AggregateException: 发生一个或多个错误

### ISSUE THREAD

**Issue by wtujvk** [icsharpcode/ILSpy#1035]
System.AggregateException: 发生一个或多个错误。 ---> System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 System.Threading.Tasks.Task`1.get_Result()
   在 ICSharpCode.ILSpy.AboutPage.<>c__DisplayClass7.<AddUpdateCheckButton>b__6(Task`1 task)
---> (内部异常 #0) System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   在 System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)<---

**Comment by siegfriedpammer** [comment]
I cannot reproduce this... the update server is reachable. Maybe it was just a temporary hiccup?
