### ISSUE TITLE
Visual Studio Addin Errors when Opening Nuget Reference

### ISSUE THREAD

**Issue by spottedmahn** [icsharpcode/ILSpy#1037]
I right clicked a Nuget package, Microsoft.AspNetCore (1.1.2), and said open w/ ILSpy.  I then got about 20 popup error messages.  Here are a few:

![image](https://user-images.githubusercontent.com/14079228/35104171-0c82bbb2-fc36-11e7-835c-36b2ce7884e5.png)

![image](https://user-images.githubusercontent.com/14079228/35104173-0de49a2a-fc36-11e7-8ae7-d6948548aacf.png)

![image](https://user-images.githubusercontent.com/14079228/35104181-100ccebc-fc36-11e7-89cf-a1172907044e.png)

**Comment by siegfriedpammer** [comment]
Did the reference to the Nuget Package have a yellow triangle next to it? If that was the case, then there was some error and even VS was not able to fully resolve the package. After restarting VS the error went away on my machine... I was only able to reproduce it once.

**Comment by Rpinski** [comment]
We have applied some fixes in add-in and I haven't seen such errors in latest devevelopment drop. Could you please give it a try? Here is the link to latest one on our build server:

https://ci.appveyor.com/api/buildjobs/502aqb2i7rn8s2pc/artifacts/ILSpy.AddIn%2Fbin%2FRelease%2Fnet46%2FILSpy.AddIn.vsix

If still something strange is happening, please feel free to open a new issue or reopen this one.

**Comment by spottedmahn** [comment]
awesome, thanks @Rpinski!
