### ISSUE TITLE
Unit Tests: add configurations for mcs to all tests

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1043]
I think it would be a good idea to run all tests with mcs as well, currently we're not able to detect some basic patterns employed by mcs (#1038 and #1036). Also, would be nice to run these tests on the build server. Any way to get that going on AppVeyor?

Note: Creating IL-Pretty tests for all existing tests would mean a lot of additional work. Therefore I would like to just invoke mcs directly as additional configuration in the existing tests.

**Comment by dgrunwald** [comment]
This is not going to happen; fully supporting mcs-generated code pattern is too much work for us.
It was already a lot of work to support the new Roslyn code patterns; and mcs seems to have significantly more differences from the MS compilers.

**Comment by siegfriedpammer** [comment]
We now have a `CompilerOptions.UseMcs` in the Tester infrastructure. We can now add tests for mcs patterns as we see fit.
