### ISSUE TITLE
Generics array-construction decompilation bug

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1048]
```
struct foo
{
	public static foo[,] Create1(int dx, int dy) { return new foo[dx,dy]; }
	public static T[,] Create2<T>(int dx, int dy) { return new T[dx,dy]; }
}
```
`Create1` decompiles properly. `Create2` decompiles into the following:
```
public static T[,] Create2<T>(int dx, int dy)
{
	return (T[,])new !!0[dx, dy];
}
```
There are at least two errors in the output.
1. The cast, though that might be due to the constructed type is wrong?
2. Well, I think this one is obvious. :-)

**Comment by dgrunwald** [comment]
Thanks for repoting this issue.

This turned out to be a problem with type substitution in the "magic array methods" (e.g. `instance void !!T[0...,0...]::.ctor(int32, int32)`). Fixed now.
