### ISSUE TITLE
ternary operator, failure to lookup enumeratee

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1055]
csc input
```
using System;
public class A
{
	void M(bool b1) {
		bool b2 = string.Equals("", "", b1 ? StringComparison.Ordinal : StringComparison.OrdinalIgnoreCase);
		bool b3 = string.Equals("", "", StringComparison.Ordinal);
	}
}
```
ILSpy output:
```
private void M(bool b1)
{
	bool flag = string.Equals("", "", (StringComparison)(b1 ? 4 : 5));
	bool flag2 = string.Equals("", "", StringComparison.Ordinal);
}
```
Expected: Lookup enumeratee symbols for values 4 and 5, followed by recognition they are both of 1) same and 2) expected type so the explicit cast can be dropped.

**Comment by dgrunwald** [comment]
`TypeHint` was meant for cases like this. We haven't really been using it much because the conversion infrastructure can already handle most stuff.
But once the expected type needs to be passed into sub-expressions, that's definitely a case for `TypeHint`.

**Comment by tamlin-mike** [comment]
@dgrunwald That's really good news - I'll have to look into `TypeHint`!

As a follow-up on the report, I have now also experienced numerous occasions where an enumeration being compared to enumeratee with value 0 (zero) is decompiled to literal zero and then cast to enum type.

orig:
` enum E { first } class C { enum E e; void bar() { if (e == E.first) { ... } }`
frequently (always?) gets decompiled into roughly
`if (e == (E)0) { ... }`

I haven't dug into the source yet to see where this is happening, but just maybe it could be related to the original issue.

**Comment by dgrunwald** [comment]
I've fixed the handling of enum constants within the ternary operator.

I can't reproduce the problem with enum comparisions -- `ExpressionBuilder.TranslateCeq` is calling `AdjustConstantExpressionToType` precisely to handle this case.
