### ISSUE TITLE
Enter/Exit V2 variation failing to convert to lock()

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1060]
I have encountered what seems to be an unexpected variation of what `LockTransform.TransformLockV2` should recognize.

```
{stloc V_0(ldobj System.Object(ldflda lockObjFld(ldloc this))) }
{call Enter(ldloc V_0) }
{.try BlockContainer {
...
finally BlockContainer {
	Block (incoming: 1) {
		call Exit(ldloc V_0)
		leave ...
	}
}
```

The V2 matcher expects
```
stloc lockObj(ldloc tempVar)
call Enter(ldloc tempVar)
...
finally { call Exit(ldloc lockObj) }
```
i.e. the `lockObj` (`V_0`) is expected to be initialized by `ldloc`, but for the failing code it's getting initialized by `ldobj`.
The failing code is also using `lockObj` for the `Enter` call, while it seems the match is to only accept `tempVar` (i.e. not the same var as used for the `Exit` call).

One solution could be to combine the `MatchLdLoc` call with more load-type checks, but that feels kinda... hackish.

I think a more generic solution could be better, something like adding a new `MatchVariableLoad` (provided such a thing isn't already existing and I'm just ignorant about it), allowing anything but constants, but not knowing the ILSpy code intimately enough I don't know if this could mess up something unexpected.

Another option could be to perform a rudamentary alias analysis, and make it even more generic.

Comments?

**Comment by dgrunwald** [comment]
The `lock` pattern changed for a reason in newer C# compiler versions -- this one might leave the lock locked on a ThreadAbortException (causing deadlocks later).

I don't think we should decompile it to the proper `lock` statement when it has different semantics.

**Comment by tamlin-mike** [comment]
@dgrunwald 
> I don't think we should decompile it to the proper lock statement when it has different semantics.

I beg to differ. For the compiler at the time that code was compiled, it was "correct". Only later was it realized "Dang, this can screw up big time!".

IFF ILSpy is intended to properly decompile _only_ binaries produced by the very latest version(s) of compilers, that position would have merit, but I had hoped the idea was to be able to decompile any version of MSIL generated by a compiler (no matter the version).

I'd prefer emitting the lock() pattern the original code most likely used, but amend the decompiled src with a comment re. the problem.


But this leads to a related issue - is ILSpy only to be able to emit one single version of C# (the latest), or are there plans to allow it to emit older versions of the language too (a user setting)?

I'm thinking about scenarios where f.ex. only an older compiler is available (to compile decompiled src), or where you have a decompiled src for, say, C#5, and want to diff it textually against a decompilation of a newer binary, where the decompilation is provided by a more recent ILSpy.

To take a more recent example, let's refer to this very issue. :-) With language-level "latest" that ugly generated code could be preferred, but if language-level was lowered it could emit the most likely src it was produced from (i.e. `lock(...)`).

I realize it would add some complexity to ILSpy, but I also think the idea has merit.
