### ISSUE TITLE
Different control flow in decompiled code

### ISSUE THREAD

**Issue by OndrejPetrzilka** [icsharpcode/ILSpy#1061]
See code below, decompiled code results in different control flow. For/while is not the issue, the actual result of such code is different. In second case it could cause NullReferenceException due to this issue.

Original code:
```
private static IEnumerable<ElementInfo> _GetLineBreakElementInfos(CreoleToken start, CreoleToken end)
{
    var token = start;
    while (token != end)
    {
        if (token.Code == CreoleTokenCode.BackSlash && token.Next?.Code == CreoleTokenCode.BackSlash)
        {
            var lineBreakElementInfo = new ElementInfo(RichTextElementType.LineBreak)
            {
                Start = token,
                End = token.Next
            };

            yield return lineBreakElementInfo;
            token = token.Next.Next;
        }
        else
        {
            token = token.Next;
        }
    }
}
```

Decompiled code:
```
private static IEnumerable<ElementInfo> _GetLineBreakElementInfos(CreoleToken start, CreoleToken end)
{
	for (CreoleToken token = start; token != end; token = token.Next)
	{
		if (token.Code == CreoleTokenCode.BackSlash)
		{
			CreoleToken next = token.Next;
			if (next != null && next.Code == CreoleTokenCode.BackSlash)
			{
				ElementInfo elementInfo = new ElementInfo(RichTextElementType.LineBreak)
				{
					Start = token,
					End = token.Next
				};
				yield return elementInfo;
				token = token.Next.Next;
				continue;
			}
		}
	}
}
```

**Comment by siegfriedpammer** [comment]
Seems like `PatternStatementTransform` is causing this.

@dgrunwald Seems we need to move all loop transforms to the ILAst... what do you think?

**Comment by siegfriedpammer** [comment]
Note: the above code is compiled in release mode. The debug version looks completely different.

**Comment by dgrunwald** [comment]
You can't introduce `for`-loops in the `PatternStatementTransform` if there are `continue;` statements in the loop body, since that changes the target of the `continue;`.
All `for`-loops with `continue;` are already handled in the `StatementBuilder` (if incrementBlock.IncomingEdgeCount > 1), the PST loop transform is only there to clean up the remaining "simple" loops.
