### ISSUE TITLE
Analysis function fails to find references on assemblies targeting framework 4.0 or later.

### ISSUE THREAD

**Issue by ActivistInvestor** [icsharpcode/ILSpy#1070]
I have not been able to get the Analyze function to produce any results outside of the class containing a member for which Analyze is invoked on, when used with a set of assemblies that target .NET 4.0 or later. 

Using an almost-identical set of assemblies that target an older framework version, Analyze will correctly find all references to a member.

It seems that ILSpy has fallen into a state of disrepair.

**Comment by siegfriedpammer** [comment]
I have used the analyzers successfully in the latest released version. Could you provide a specific example that is failing?

**Comment by siegfriedpammer** [comment]
I have just pushed a fix that improves assembly discovery in the "Used by" analyzers. Would be nice, if you could check whether the situation improved with this fix. Thank you very much! This specific fix is in https://ci.appveyor.com/project/icsharpcode/ilspy/build/3.1.1.3670 or later, if you need a nightly build for testing.

**Comment by siegfriedpammer** [comment]
Closing because there was no feedback.
