### ISSUE TITLE
Sometimes uses Enumarator instead of Foreach

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1071]
Sometimes decompiler uses Enumarator instead of Foreach every place in a Unity Mono Librray, not one place. Sometimes it doesn't use any Enumarator for for-loops. I tested it with Dnspy works correctly. 

I left a test case here: (Left: dnSpy v4.5.2, Right: ILSpy v3.0.1.3459)

![Image](https://user-images.githubusercontent.com/16493751/36599881-d0658dd2-18c1-11e8-9217-516eba05692a.png)

If not visible: https://i.hizliresim.com/vj6XjD.png

**Comment by Dentrax** [comment]
The ILCode of the given HasCompletedLevel void: https://paste.ee/p/p4yKD

**Comment by dgrunwald** [comment]
Looks like the enumerator is getting boxed for the Dispose call? That's not what happens in a normal foreach loop, so ILSpy isn't decompiling the code to a foreach loop.
