### ISSUE TITLE
About dynamic

### ISSUE THREAD

**Issue by escms** [icsharpcode/ILSpy#1073]
MVC Source Code:
base.ViewBag.Url = url;
because
base.ViewBag is dynamic type,
so ,expect
((dynamic) base.ViewBag).Url = url;

ilspy:

if (UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7 == null) { UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7 = CallSite<Func<CallSite, object, string, object>>.Create(Binder.SetMember(CSharpBinderFlags.None, "Url", typeof(UserCenterController), new CSharpArgumentInfo[] { CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null), CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, null) })); } UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7.Target(UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7, base.ViewBag, arg);

 JustDecompile is support the decompile dynamic Type code ,This is very common in the MVC project. Do you have any plans

**Comment by siegfriedpammer** [comment]
See #829 and #154...

Unless it is contributed by someone, it will not be added to ILSpy due to limited resources. JetBrains is a big company, we are three developers. Contributions are very welcome!
