### ISSUE TITLE
Advanced Option Request: Use Sealed Keyword Everywhere If Possible

### ISSUE THREAD

**Issue by Dentrax** [icsharpcode/ILSpy#1074]
We don't understand that some classes are final or not / can be sealed or not. 

Theory:
-If the class/function has never been made inheranced/overridden anywhere, add sealed keyword. (if possible) (public sealed override void, public sealed class, etc.)

I didn't see this setting in the lastest 'master' branch build. I think it might be really useful.

@siegfriedpammer

**Comment by siegfriedpammer** [comment]
I don't see the advantage/use of such an option... seems a bit out of scope for a decompiler...

**Comment by christophwille** [comment]
Wouldn't that be more like a custom tool than ran on top of source code? (using Roslyn)

**Comment by siegfriedpammer** [comment]
The decompiler should not add any information to the output that was not there in the binary. This is a thing you can do after decompiling and exporting the source code.
