### ISSUE TITLE
Fixed block over array generates incorrect code

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1078]
Input:
```cs
unsafe static void Test(int[] array)
{
    fixed (int* ptr = array)
    {
        NoOp(ptr);
    }
}

unsafe static void NoOp(int* ptr) { }
```
Output:
```cs
private unsafe static void Test(int[] array)
{
	fixed (int[] array2 = array)
	{
		int* ptr = (int*)(long)((array != null && array2.Length != 0) ? ((IntPtr)(&array2[0])) : ((IntPtr)(void*)null));
		PointerToArray.NoOp(ptr);
	}
}

private unsafe static void NoOp(int* ptr)
{
}
```
Errors:
 `CS0209 The type of a local declared in a fixed statement must be a pointer type`
 `CS0212 You can only take the address of an unfixed expression inside of a fixed statement initializer`

**Comment by dgrunwald** [comment]
Looks like a Roslyn compiler update at some point changed the code pattern generated for fixed statements.
Regenerating the `.il` files for our `UnsafeCode` test case causes them to fail with exactly this kind of error. 

Fortunately it seems that the differences between old roslyn and new roslyn have little to no overlap with the differences between the legacy csc (pre-roslyn) and old roslyn, so it seems that it's sufficient to generate the roslyn `.il` files and we still end up testing all the code patterns.
