### ISSUE TITLE
Decompiling constants of the target type

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#1084]
Originally reported by @davkean in dotnet/roslyn#25006:

> The following:
>
> ``` C#
>         internal int ActualMaxDegreeOfParallelism
>         {
>             get { return (_maxDegreeOfParallelism == Unbounded) ? int.MaxValue : _maxDegreeOfParallelism; }
>         }
> ```
>
> gets decompiled to:
> 
> ``` C#
> 		internal int ActualMaxDegreeOfParallelism
> 		{
> 			get
> 			{
> 				if (this.m_maxDegreeOfParallelism != -1)
> 				{
> 					return this.m_maxDegreeOfParallelism;
> 				}
> 				return 2147483647;
> 			}
> 		}
> ```
>
> Similar to other decompilers, we should be smarter around replacing magic "literals" with their appropriate constants.

I suggest implementing the feature mentioned by @CyrusNajmabadi in https://github.com/dotnet/roslyn/issues/25006#issuecomment-367962429:

> ... looks in the Type for that value for any constants matching the value. If it finds any, it will use them. As such, it will replace constants with things like int.MaxValue, double.Infinity, ...

:link: This is related to #517, but is much more narrowly-scoped and (I believe) much easier to implement as an interim solution covering majority cases.

**Comment by siegfriedpammer** [comment]
@sharwell @davkean Would you expect the decompiler to replace literals with constants everywhere? Even in constant / enum declarations?

Which one do you prefer? `enum E { A = 0x7F }` or `enum E { A = sbyte.MaxValue }`

(Of course definitions of `public const double NaN` in `System.Double` and others would not use `double.NaN` in the definition.)
