### ISSUE TITLE
"Open in ILSpy" from references not present in VS 2017 15.6.1 Enterprise

### ISSUE THREAD

**Issue by johanstenberg92** [icsharpcode/ILSpy#1086]
Hi, this feature is not available in VS 2017 15.6.1 Enterprise, I use version 1.7.2.0 of the extension.

Thanks,

Johan

**Comment by siegfriedpammer** [comment]
We've recently published an update to the extension, can you confirm whether that fixes this bug? Thank you!

**Comment by johanstenberg92** [comment]
Works now. Thanks!
