### ISSUE TITLE
Nested Type node text should not include enclosing type name.

### ISSUE THREAD

**Issue by EdHarvey** [icsharpcode/ILSpy#109]
The text on a nested type node contains both the enclosing and nested type name. The enclosing type name is superfluous.

for example, see mscorlib, System.ActivationContext. This contains an enumeration ApplicationState which is shown as ActivationContext.ApplicationState.

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
