### ISSUE TITLE
Feature Request: Search by abbreviated qualified name

### ISSUE THREAD

**Issue by carlreinke** [icsharpcode/ILSpy#1090]
[apisof.net](https://apisof.net/) has a neat feature where you can omit much of the name being searched for and still filter effectively.  It would be handy if ILSpy implemented something like this.

Probably the easiest way to see how it works is to go play with it.

A few examples for finding `System.Xml.XmlReaderSettings`:
* xreadset
* xrs
* x.xr
* x.xrs
* s.x.xr

If we ask nicely, maybe @terrajobst can provide the actual algorithm used on apisof.net.

**Comment by siegfriedpammer** [comment]
Currently we do not have any plans to extend the search feature. It would be nice if somebody could contribute it. If anybody wants to give it a go, take a look at `AbstractSearchStrategy.MatchName` in `SearchStrategies.cs`. I think it would be best to add an option for this (for now default: false).

If you have any questions, please ask!
