### ISSUE TITLE
Option to decompile using fully qualified names

### ISSUE THREAD

**Issue by ststeiger** [icsharpcode/ILSpy#1103]
Instead of "using clauses", could we have an option to decompile to fully qualified names ? 

So that recompilation works if we have a/multiple assembly with a class/struct/enum/whatever with a same-name-object in two namespaces. 

For example instead of 

```
using a;
using b;    


namespace abc
{
void foo()
{  
    MethodOrClassInAwithSameNameInB(); 
   x.ExtensionMethod();
}
}
```

I woud like to get code like 

```  
namespace abc
{
void foo()
{  
    a.MethodOrClassInAwithSameNameInB(); 
    staticExtensionClass.ExtensionMethod(x);
}
}
```

so that a correctly decompiled project actually recompiles after decompilation.

**Comment by siegfriedpammer** [comment]
I think you can achieve that by unchecking "Insert using declarations":

![grafik](https://user-images.githubusercontent.com/344204/37900716-52fde3f8-30ef-11e8-87ed-3ed60b550cb5.png)

**Comment by dgrunwald** [comment]
ILSpy already checks whether disambiguation is necessary, and should produce fully qualified names if the short name does not resolve as expected.
If you have a case where this fails, please post a full example.

**Comment by ststeiger** [comment]
Ah, didn't see that. 
Yes, this is what I wanted. 
But, it's still omiting fully qualified namespaces where the code or a reference is inside the parent namespace.
