### ISSUE TITLE
.dll files are corrupted after edited successfully by Ilspy and reflexil

### ISSUE THREAD

**Issue by abouhaa** [icsharpcode/ILSpy#1112]
.dll files are corrupted after edited successfully by Ilspy and reflexil

I am trying to edit a .dll file; I can read the code using ILSpy which is great, edit it using Reflexil plugin, update the object and save it as on my desktop.

When I try to add the new modified .dll to visual studio project, it would load into references but can't really use the functions inside the .dll that I was able to do.
The change I made was on one integer in the library that has nothing to do with any other function.

I have also noticed that the new .dll size has dropped significantly from 240Kb to 210Kb; I don't think changing an integer's initial value from 4 to 9 should change the file size.

Even more strange, I reloaded the original .dll into ILspy and never did any change on it.. I directly saved it as on my desktop. The size still dropped the same amount it dropped before and I couldn't read the .dll from visual studio.

Moreover, I tried to load the .dlls into a resource editor, the original loaded properly but every other .dll that was opened by Ilspy and whether was modified or not couldn't even be seen on the browse window of the resource editor.

Any ideas? IS the .dll file corrupted after ILspy? Am I missing some step??

Thanks.

**Comment by christophwille** [comment]
As ILSpy itself only reads from a DLL, it is most likely Reflexil - you might want to ask in the Reflexil repo https://github.com/sailro/Reflexil/issues

**Comment by abouhaa** [comment]
Makes sense. I will try.
Thank you.
