### ISSUE TITLE
How to upgrade an old API to the new one?

### ISSUE THREAD

**Issue by na2axl** [icsharpcode/ILSpy#1115]
I was using an old version of ICSharpCode.Decompiler for a while, but recently I've upgraded to the latest version from Nuget. There was several changes with the upgrade and I think I've fixed them but now I'm facing another one, how to create a method body?
The code I'm trying to upgrade is: ([full code source](https://github.com/AlienEngine/AlienEngine/blob/features/rendering/AlienEngine/Shaders/ASL/ASLShaderCompiler.cs))
```csharp
internal static KeyValuePair<MethodDefinition, KeyValuePair<string, string>> CreateMethodString(TypeDefinition s, MethodDefinition m)
{
    if (s == null)
        throw new ArgumentNullException("s");

    if (m == null)
        throw new ArgumentNullException("m");

    var ctx = new DecompilerContext(s.Module)
    {
        CurrentType = s,
        CurrentMethod = m,
        CancellationToken = CancellationToken.None
    };

    var d = AstMethodBodyBuilder.CreateMethodBody(m, ctx);

    var glsl = new ASLShader.GLSLVisitor(d, ctx);

    var sig = ASLShader.GLSLVisitor.GetSignature(m);
    var code = glsl.Result;
    var desc = new KeyValuePair<MethodDefinition, KeyValuePair<string, string>>(
        m,
        new KeyValuePair<string, string>(m.Name, sig + code)
    );

    return desc;
}
```

**Comment by siegfriedpammer** [comment]
What issues are you having with the `CSharpDecompiler.Decompile(IMemberDefinition)` API? You should be able to get access to the `BlockStatement`. Can you post an attempt of yours at using the new API?

**Comment by na2axl** [comment]
Thanks @siegfriedpammer for the reply, I will try this and give a feedback :-)

**Comment by na2axl** [comment]
I've used the `CSharpDecompiler` API and I was able to get the `BlockStatement` of the method body. But I don't know how to get or create a `TransformContext`. I have also issue when trying to apply a custom `IAstTransform` to the statement, the exception **Node is already used in another tree.** is thrown. I've tried to use the `Clone()` method but nothing...

The new code is:
```cs
internal static KeyValuePair<MethodDefinition, KeyValuePair<string, string>> CreateMethodString(TypeDefinition s, MethodDefinition m)
{
    if (s == null)
        throw new ArgumentNullException(nameof(s));

    if (m == null)
        throw new ArgumentNullException(nameof(m));

    var settings = new DecompilerSettings();
    var typeSys = new DecompilerTypeSystem(m.Module);

    var decompiler = new CSharpDecompiler(typeSys, settings)
    {
        CancellationToken = CancellationToken.None
    };
    
    var tree = decompiler.Decompile(m);

    BlockStatement methodBody = BlockStatement.Null;
    
    foreach (AstNode node in tree.Members)
    {
        if (node is MethodDeclaration method)
        {
            methodBody = method.Body;
            break;
        }
    }
    
    if (methodBody == BlockStatement.Null)
        throw new Exception("Unable to find a method declaration in the syntax tree.");
    
    // I don't know how to get a TransformContext, so null is passed instead...
    var glsl = new ASLShader.GLSLVisitor(methodBody, null);

    var sig = ASLShader.GLSLVisitor.GetSignature(m);
    var code = glsl.Result;
    var desc = new KeyValuePair<MethodDefinition, KeyValuePair<string, string>>(
        m,
        new KeyValuePair<string, string>(m.Name, sig + code)
    );

    return desc;
}
``` 

The `GLSLVisitor` constructor:
```cs
public GLSLVisitor(BlockStatement block, TransformContext ctx)
{
    var trans1 = new ReplaceMethodCallsWithOperators();
    var trans2 = new RenameLocals();
    ((IAstTransform)trans1).Run(block, ctx);
    trans2.Run(block, ctx);

    Result = block.AcceptVisitor(this, 0).ToString();
    Result += Environment.NewLine;
}
```

And the custom `IAstTransform`:
```cs
    internal sealed class RenameLocals : IAstTransform
    {
        private int _ctr;

        private readonly Dictionary<string, string> _locals = new Dictionary<string, string>();

        public void Run(AstNode node, TransformContext context)
        {
            if (node == null)
                throw new ArgumentNullException(nameof(node));

            if (node is VariableInitializer initializer)
            {
                var newName = $"_loc{_ctr++}";
                _locals[initializer.Name] = newName;
                initializer.ReplaceWith(new VariableInitializer(newName, initializer.Initializer));
            }
            else
            {
                if (node is IdentifierExpression identifier)
                {
                    string newName;
                    if (_locals.TryGetValue(identifier.Identifier, out newName))
                        identifier.ReplaceWith(new IdentifierExpression(newName));
                }
            }

            foreach (var c in node.Children)
                Run(c, context);
        }
    }
```

The exception was thrown when calling `initializer.ReplaceWith()`.

**Comment by siegfriedpammer** [comment]
Why are you using the `IAstTransform` interface at all? It is only useful when you are implementing a transform that is added to the decompiler pipeline, but there is no need for you to do this.

As for
```
 initializer.ReplaceWith(new VariableInitializer(newName, initializer.Initializer));
```
maybe using .Detach()
```
 initializer.ReplaceWith(new VariableInitializer(newName, initializer.Initializer.Detach()));
```
solves your problem?

**Comment by na2axl** [comment]
I've removed the `IAstTransform` interface.
But it seems that `Detach()` doesn't exist in the type `Exression`...
![image](https://user-images.githubusercontent.com/14062034/38471580-0bb28a54-3b6b-11e8-8c53-e24328dc26cb.png)

**Comment by siegfriedpammer** [comment]
Oh I am sorry, forgot that `Detach` is an internal extension method...

you can do the same:

		public static T Detach<T>(this T node) where T : AstNode
		{
			node.Remove();
			return node;
		}

**Comment by na2axl** [comment]
@siegfriedpammer thanks it work. But... aigain... I'm facing other issues when calling `Expression.Annotation<T>()`. It always return `null` when `T` is a type from `Mono.Cecil` (`MethodDefinition`, `MethodReference`, `TypeReference`, etc...).

Maybe those types are not expression annotations in the new API?

Trying for fix...

**Comment by siegfriedpammer** [comment]
We no longer provide `Mono.Cecil` objects as annotations. You can use the `GetSymbol` extension method to get the symbol that is referenced by a node. To get the Cecil object you have to use `DecompilerTypeSystem.GetCecil`. Hope this helps!

**Comment by na2axl** [comment]
Yes thanks, the use of `GetSymbol` have fixed the problem. I've fixed some other issues and the new API works like a charm 😄

**Comment by na2axl** [comment]
Thanks again for the **GOOD** support! 👍
