### ISSUE TITLE
Search results presentation

### ISSUE THREAD

**Issue by MikeFH** [icsharpcode/ILSpy#1118]
Currently, search results are presented this way :
![search](https://user-images.githubusercontent.com/17053707/38770328-a119f320-4011-11e8-9633-d82f5040e71b.png)

Would it be possible/a good idea to present them this way :
![search_table](https://user-images.githubusercontent.com/17053707/38770333-ac072ea6-4011-11e8-9b80-c0a7f121d1c3.png)

The location information on the right seems far more readable if left aligned. 

I would submit a PR myself but I am no WPF expert. In the example picture I set a constant width for the first column, but I'm sure there are better solutions.

**Comment by siegfriedpammer** [comment]
The ListBox was replaced with a ListView in 1ba2c0537a2946d08345623c14c0ee05e2f9ff36.

**Comment by MikeFH** [comment]
Nice. Thank you.
