### ISSUE TITLE
Resolve WinRT/UWP language projection rules

### ISSUE THREAD

**Issue by weltkante** [icsharpcode/ILSpy#1127]
In WinRT/UWP context there appears to be a set of types which exist in multiple assemblies but are assumed to be identical. Currently ILSpy assumes types to be singletons and performs no such (reverse) mapping. The result is that ILSpy gets confused and cannot properly resolve e.g. property accessors.

For example, consider a property in a C# project `static Rect Bounds { get => Window.Current.Bounds; }` then ILSpy can resolve `Current` but not `Bounds` and will instead output `get_Bounds()`.

The problem is that the C# compiler used language projection and the C# assembly refers to `Rect` in `System.Runtime.WindowsRuntime.dll` but the `Window` class uses a `Bounds` property with `Rect` from `Windows.winmd` on win8/winrt or `Windows.Foundation.FoundationContract.winmd` on win10/uwp.

The bug manifests itself in `DecompilerTypeSystem.FindNonGenericMethod` where at the end it iterates over the available methods but cannot match any because `CompareTypes` returns false due to non matching return type (at one side it has a Rect from the projection, at the other side it has a Rect from the runtime, which do not compare as equal). This results in creating a fake method which will not be linked to a property accessor.

[edit] CoreCLR appears to have source code for those mappings in form of a macro table, may be useful as reference: https://github.com/dotnet/coreclr/blob/master/src/inc/winrtprojectedtypes.h

**Comment by siegfriedpammer** [comment]
Closing, because SRM has this enabled by default.
