### ISSUE TITLE
XamlParseException on startup

### ISSUE THREAD

**Issue by FuSoftware** [icsharpcode/ILSpy#1137]
Config :
- ILSpy 3.1
- .NET 4.0 (4.5 looking at the registry)
- Windows7 (Not SP1)

So far, the config file states that .NET 4.0 should be enough to run the software

```
<startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0,Profile=Client" />
</startup>
```

The program returns an XamlParseException when started with the above configuration. Since there's no proper log, I join you a screenshot of the error message :

![capture3](https://user-images.githubusercontent.com/11671860/40045053-93a6283c-5829-11e8-94fb-8877d3e4af98.PNG)

**Comment by siegfriedpammer** [comment]
Ever since we added support for .NET Standard in the decompiler, we require .NET 4.6 for the ILSpy UI. This was an oversight, which is now fixed.
