### ISSUE TITLE
Array-index out of bounds crash in TransformArrayInitializers.HandleSimpleArrayInitializer

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1138]
https://github.com/icsharpcode/ILSpy/blob/b6dce5c27accb1a1e12fabd8aad49baeb6b48806/ICSharpCode.Decompiler/IL/Transforms/TransformArrayInitializers.cs#L175-L177
https://github.com/icsharpcode/ILSpy/blob/b6dce5c27accb1a1e12fabd8aad49baeb6b48806/ICSharpCode.Decompiler/IL/Transforms/TransformArrayInitializers.cs#L181-L183

At the start of the loop the index is properly checked (and loop aborted if OOB) but `MatchLdcI4` can (and in my case do) give it a new value that is not checked.

Locally I avoided the crash by replicating the bounds-check (appending `|| index >= length` to the multi-term ìf`), but I haven't dug deeper into it to see if that's the correct fix.

The (now decompiled, with my workaround) becomes:
```
char[] obj = new char[1];
obj[1] = '$';
```
which clearly is a bug in the original program, but ILSpy shouldn't be fooled into crashing conditions by buggy binaries. :-)

Edit: Got another crash, this time with a negative index, so the added conditions to line 181 now have to be ` || index >= length || index < 0`.

**Comment by dgrunwald** [comment]
Looking at the code, we're also missing a check that an index isn't used multiple times.
Otherwise we could end up removing an instruction which might have side effects.
