### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by nike022812** [icsharpcode/ILSpy#1139]
![image](https://user-images.githubusercontent.com/3353304/40091251-20bff8b4-58e9-11e8-8e63-778cee3fe271.png)

**Comment by FuSoftware** [comment]
Most likely duplicate of https://github.com/icsharpcode/ILSpy/issues/1137

You lack the .NET 4.6 required to run the software. There was an oversight where the config file "allowed" .NET 4.0+ to run the executable, while the program isn't compatible. This will be fixed in the next release.

**Comment by siegfriedpammer** [comment]
Duplicate of #1137
