### ISSUE TITLE
Assertion Failed dialog on decompilation

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1140]
I've got this dialog twice while navigating .net assembly
After pressing "Throw" button have got this error text:

`
Error decompiling System.Void xxxxx.App::.cctor()
 ---> ICSharpCode.ILSpy.AssertionFailedException: 
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage) in offset 380
   at ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message) in offset 9
   at System.Diagnostics.TraceInternal.Fail(String message) in offset 55
   at System.Diagnostics.Debug.Assert(Boolean condition) in offset 6
   at ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase) in offset 44
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in offset 126
   at ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase) in offset 8
   at ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase) in offset 126
   at ICSharpCode.Decompiler.IL.ILFunction.CheckInvariant(ILPhase phase) in offset 88
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 373
-- continuing with outer exception (ICSharpCode.Decompiler.DecompilerException) --
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 914
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(MethodDefinition methodDefinition, IMethod method, DecompileRun decompileRun, ITypeResolveContext decompilationContext) in offset 126
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IList`1 definitions) in offset 383
   at ICSharpCode.ILSpy.CSharpLanguage.DecompileField(FieldDefinition field, ITextOutput output, DecompilationOptions options) in offset 162
   at ICSharpCode.ILSpy.TreeNodes.FieldTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options) in offset 15
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput) in offset 69
   at ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass33_0.<DecompileAsync>b__0() in offset 38

`

I"m using latest build from appveyor service (
Help -> About said this: ILSpy version 3.2.0.3696-alpha
)
![il_assertion](https://user-images.githubusercontent.com/765343/40267426-b700554e-5b64-11e8-8de3-3aea7cbddae4.png)

**Comment by greenozon** [comment]
Note: this is some very basic assert, as it throws even on such a simple thing like:

public static readonly int _init = 8;

(valided it from other decompiler)

PS
I've checked using latest release - ILSpy version 3.1.0.3652
it works OK

**Comment by siegfriedpammer** [comment]
When you select a field definition in the tree view, we have to decompile the ctors as well, to be able to display field initializers.

The assertion is thrown while decompiling the static ctor of the type. Could you please either post the assembly you tried to decompile or provide the IL code (if it's a simple method that can be easily reassembled)?

Thank you very much for your help!

**Comment by greenozon** [comment]
Here are some hints that might help...

full IL and some pics from ILSpy, hope it helps to deduce and make corrections!

ILAst:
(@cctor, after "Throw" button pressed)

![ilast](https://user-images.githubusercontent.com/765343/40268177-a7872d06-5b71-11e8-914c-8589f29e0730.png)


`
.method private hidebysig specialname rtspecialname static 
	void .cctor () cil managed 
{
	// Method begins at RVA 0x447c8
	// Code size 242 (0xf2)
	.maxstack 2
	.locals init (
		[0] class [mscorlib]System.Threading.Thread,
		[1] class [mscorlib]System.Threading.ThreadStart,
		[2] class App.App/'<>c__DisplayClass2'
	)

	IL_0000: ldc.i4.8
	IL_0001: stsfld int32 App.App::_init
	IL_0006: call bool [mscorlib]System.Diagnostics.Debugger::get_IsAttached()
	IL_000b: brtrue.s IL_0014

	IL_000d: call bool App.App::IsDebuggerPresent()
	IL_0012: brfalse.s IL_0028

	IL_0014: call string [mscorlib]System.Environment::get_CommandLine()
	IL_0019: ldstr "/Debug"
	IL_001e: callvirt instance bool [mscorlib]System.String::Contains(string)
	IL_0023: ldc.i4.0
	IL_0024: ceq
	IL_0026: br.s IL_0029

	IL_0028: ldc.i4.0

	IL_0029: stsfld bool App.App::DebuggerIsPresent
	IL_002e: call bool [mscorlib]System.Diagnostics.Debugger::get_IsAttached()
	IL_0033: brtrue.s IL_003c

	IL_0035: call bool App.App::IsDebuggerPresent()
	IL_003a: brfalse.s IL_006a

	IL_003c: call string [mscorlib]System.Environment::get_CommandLine()
	IL_0041: ldstr "AllContainers"
	IL_0046: callvirt instance bool [mscorlib]System.String::Contains(string)
	IL_004b: brtrue.s IL_006a
	.try
	{
		.try
		{
			IL_004d: call class [System]System.Diagnostics.Process [System]System.Diagnostics.Process::GetCurrentProcess()
			IL_0052: callvirt instance void [System]System.Diagnostics.Process::Kill()
			IL_0057: leave.s IL_0062
		} // end .try
		catch [mscorlib]System.Exception
		{
			IL_0059: pop
			IL_005a: ldc.i4.0
			IL_005b: call void [mscorlib]System.Environment::Exit(int32)
			IL_0060: leave.s IL_0062
		} // end handler

		IL_0062: leave.s IL_006a
	} // end .try
	finally
	{
		IL_0064: newobj instance void [System]System.ComponentModel.InvalidAsynchronousStateException::.ctor()
		IL_0069: throw
	} // end handler
	.try
	{
		IL_006a: ldnull
		IL_006b: stloc.1
		IL_006c: newobj instance void App.App/'<>c__DisplayClass2'::.ctor()
		IL_0071: stloc.2
		IL_0072: ldloc.2
		IL_0073: call int32 App.App::CheckEn()
		IL_0078: stfld int32 App.App/'<>c__DisplayClass2'::'ret'
		IL_007d: ldloc.2
		IL_007e: ldfld int32 App.App/'<>c__DisplayClass2'::'ret'
		IL_0083: ldc.i4.0
		IL_0084: ble.s IL_00a9

		IL_0086: ldloc.1
		IL_0087: brtrue.s IL_0096

		IL_0089: ldloc.2
		IL_008a: ldftn instance void App.App/'<>c__DisplayClass2'::'<.cctor>b__0'()
		IL_0090: newobj instance void [mscorlib]System.Threading.ThreadStart::.ctor(object, native int)
		IL_0095: stloc.1

		IL_0096: ldloc.1
		IL_0097: newobj instance void [mscorlib]System.Threading.Thread::.ctor(class [mscorlib]System.Threading.ThreadStart)
		IL_009c: stloc.0
		IL_009d: ldloc.0
		IL_009e: callvirt instance void [mscorlib]System.Threading.Thread::Start()
		IL_00a3: ldloc.0
		IL_00a4: callvirt instance void [mscorlib]System.Threading.Thread::Join()

		IL_00a9: leave.s IL_00ae
	} // end .try
	catch [mscorlib]System.Exception
	{
		IL_00ab: pop
		IL_00ac: leave.s IL_00ae
	} // end handler
	.try
	{
		IL_00ae: call uint32 App.DLC::getID()
		IL_00b3: dup
		IL_00b4: stsfld uint32 App.Programm::_id
		IL_00b9: brtrue.s IL_00d8

		IL_00bb: ldsfld bool App.DLC::CommandLineMode
		IL_00c0: brtrue.s IL_00d2

		IL_00c2: ldstr "Please exit and try again."
		IL_00c7: ldstr "A problem"
		IL_00cc: call valuetype [PresentationFramework]System.Windows.MessageBoxResult [DConfig]DConfig.EMessageBox::Show(string, string)
		IL_00d1: pop

		IL_00d2: ldc.i4.m1
		IL_00d3: call void [mscorlib]System.Environment::Exit(int32)

		IL_00d8: leave.s IL_00e7
	} // end .try
	catch [mscorlib]System.Exception
	{
		IL_00da: pop
		IL_00db: ldc.i4 -3423
		IL_00e0: call void [mscorlib]System.Environment::Exit(int32)
		IL_00e5: leave.s IL_00e7
	} // end handler

	IL_00e7: ldstr "App.Static"
	IL_00ec: call void App.App::BenchmarkAppStartupStep(string)
	IL_00f1: ret
} // end of method App::.cctor

`


let me know if you need more hints

**Comment by siegfriedpammer** [comment]
The IL of the inner class `<>c__DisplayClass2` and any other inner classes would be needed to create a full repro... Thank you very much!

**Comment by greenozon** [comment]
There is just one inner class you've mentioned there,
here it is:

`
.class nested private auto ansi sealed beforefieldinit '<>c__DisplayClass2'
	extends [mscorlib]System.Object
{
	.custom instance void [mscorlib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = (
		01 00 00 00
	)
	// Fields
	.field public int32 'ret'

	// Methods
	.method public hidebysig specialname rtspecialname 
		instance void .ctor () cil managed 
	{
		// Method begins at RVA 0x4478a
		// Code size 7 (0x7)
		.maxstack 8

		IL_0000: ldarg.0
		IL_0001: call instance void [mscorlib]System.Object::.ctor()
		IL_0006: ret
	} // end of method '<>c__DisplayClass2'::.ctor

	.method public hidebysig 
		instance void '<.cctor>b__0' () cil managed 
	{
		// Method begins at RVA 0x44794
		// Code size 37 (0x25)
		.maxstack 2
		.locals init (
			[0] int32
		)

		IL_0000: ldarg.0
		IL_0001: ldfld int32 App.App/'<>c__DisplayClass2'::'ret'
		IL_0006: stloc.0
		IL_0007: ldstr "Error: Please report."
		IL_000c: ldloc.0
		IL_000d: box [mscorlib]System.Int32
		IL_0012: call string [mscorlib]System.String::Concat(object, object)
		IL_0017: call valuetype [PresentationFramework]System.Windows.MessageBoxResult [DConfig]DConfig.EMessageBox::Show(string)
		IL_001c: pop
		IL_001d: ldc.i4.s -2
		IL_001f: call void [mscorlib]System.Environment::Exit(int32)
		IL_0024: ret
	} // end of method '<>c__DisplayClass2'::'<.cctor>b__0'

} // end of class <>c__DisplayClass2

`

**Comment by siegfriedpammer** [comment]
A minimal example that triggers the assertion:

```
using System;

namespace ThrowInFinally
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
            }
            finally
            {
                throw new Exception();
            }
       }
    }
}
```

**Comment by greenozon** [comment]
Fantastic deduction and mind analysis
you must be the ancestor of Sherlock H! :)

**Comment by siegfriedpammer** [comment]
No, I just reassembled the IL and copied the suspicious parts into a separate project and reduced it further... :) But thanks ;-)...

**Comment by greenozon** [comment]
are there any plans to add a fix for this issue?
thx

**Comment by dgrunwald** [comment]
Interesting. In C#, it's clear that it's impossible to leave the try{}finally{} construct without an exception, because any attempt at leaving the try block will enter the finally block.
However in IL, there's only instruction for jumping out of a try-block is `leave`, which requires a target to jump to, and said target must not be inside the try-finally construct. The compiler needs to put some code in this unreachable target block to make the IL valid, so it generates an infinite loop.

ILSpy now tries to eliminate the jump and use normal control flow out of the try block to reach the infinite loop -- but then notices that it just put code in an unreachable spot, and asserts.
Instead of attempting to move the jump instruction out of the try, we need to special case this and delete the jump instruction (and its unreachable target block) altogether.
