### ISSUE TITLE
AddIn opens reference assembly when trying to open symbol in ILSpy

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1164]
Steps to reproduce:

1. create .NET core console app
2. Compile the project
3. Right-click on `Console.WriteLine` and select "Open code in ILSpy"
4. Wait for ILSpy to open and load the assembly and navigate to the symbol. 

Expected behavior:
ILSpy decompiles the actual IL of `System.Console.WriteLine`.

Actual behavior:
A reference assembly without any IL in the method bodies is loaded.

**Comment by Rpinski** [comment]
This will be fixed in final 3.2 release (and in latest devdrops, of course).
