### ISSUE TITLE
Improve visibility of Visual Studio extension

### ISSUE THREAD

**Issue by cremor** [icsharpcode/ILSpy#1171]
Although I'm a long time user of the standalone ILSpy, I just recently learned that there is an Visual Studio extension for it. If I take a detailed look at the GitHub readme, I can find the "VS Extension" button that brings me to the VS marketplace. But the text of the readme, more specifically the "Decompiler Frontends" section, only mentions the VS Code extension. I suggest to also mention the VS extension there.

Although you might want to wait with this change until #1125 (and maybe #1164) is fixed and published to the markedplace, otherwise new users might run into those problems and quickly abandon the extension again.

**Comment by christophwille** [comment]
Yes, this will have to wait until 3.2 is released as final version.

**Comment by dgrunwald** [comment]
The addin in 3.2 beta is broken again; in a normal (desktop) C# console application, I can't even navigate to the `Console.WriteLine` in a hello world app.
