### ISSUE TITLE
ILSpy crash on save: Illegal characters in path

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1187]
CTLR+S
crashing -  Illegal characters in path
![il_crash](https://user-images.githubusercontent.com/765343/42106048-4dd3195c-7bdb-11e8-92d9-6a2b59282d2e.png)

![il_crash2](https://user-images.githubusercontent.com/765343/42106060-5524fb76-7bdb-11e8-9e2b-c6fe6bf63ac2.png)

target - https://www.sendspace.com/file/6vet0u

**Comment by dgrunwald** [comment]
I doubt think saving obfuscated assemblies to disk will ever work well -- we replace invalid characters in paths with `-`, so in obfuscated assemblies several classes/resources will get written to the same file.

**Comment by greenozon** [comment]
agree, replacing invalid chars looks like a good strategy.
but the question was that ILSpy shall not crash.

**Comment by siegfriedpammer** [comment]
Yes, the crash should be fixed now. We were passing an invalid filename to `Path.ChangeExtension` which is now fixed.
