### ISSUE TITLE
Performance issues with deeply nested if-structures

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1193]
ILSpy version 3.2.0.3851-rc
CTRL+S
waiting 3 minutes (using Core i7)
process of decompilation not finished, looks like it get stucked.
a guess would be that it stucked (or doing long hardwork) inside Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1

target: https://www.sendspace.com/file/orprcy

**Comment by dgrunwald** [comment]
With a release build, decompilation finishes within 90 seconds for me. Debug builds are significantly slower due to all the assertion checking (usually 2 or 3 times slower).

But the profile looks weird; I think there's a performance bug in `TryConvertExpressionTree`.

**Comment by dgrunwald** [comment]
I fixed some places where highly nested block structures caused us to unnecessarily take quadratic time.
This brings the runtime down to 22s (release build).
Debug builds can be significantly slower as they perform additional recursive tree walks when verifying the ILAst invariants -- I wouldn't be surprised if this is a case where release builds take O(N²) and debug builds need O(N³).
