### ISSUE TITLE
Strange if statements with goto

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1194]
ILSpy version 3.2.0.3851-rc

Seen this strange decompiled code:

```
...
	if (!o.FixLeftSpecified)
	{
		goto IL_0437;
	}
	goto IL_0437;
	IL_0437:
	if (!o.FixRightSpecified)
	{
		goto IL_0448;
	}
	goto IL_0448;
	IL_0459:
...
```
no obfuscation used, plain code,
method Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriter1.Write50_BarProfileStandard
from #1193

**Comment by AustinWise** [comment]
While there might not be any obfuscation, this assembly was not compiled from C#. It was generated by the [sgen.exe](https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-serializer-generator-tool-sgen-exe) tool. The code patterns generated by that tool don't match those used by csc.exe, which explains why the decompiled code looks strange.
