### ISSUE TITLE
Assembly-csharp not detect

### ISSUE THREAD

**Issue by FrenchModZ** [icsharpcode/ILSpy#1197]
Hello,

when I open Dnspy and I select my assembly-csharp of the apk I want to edit, I have this problems:

https://drive.google.com/file/d/1FBwhHvI1vGObPk37lfsF-Ne40uNxZkNW/view?usp=sharing

But, on my folder its the good adress, all other dll of the app work but not the assembly-csharp.dll
Please, help me and sorry for my bad english

Thanks you

**Comment by siegfriedpammer** [comment]
This is the ILSpy repository, please report the issue at the dnSpy repository (https://github.com/0xd4d/dnSpy).
