### ISSUE TITLE
Performance: HasAttribute/GetAttribute

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/ILSpy#1204]
Currently, every `HasAttribute` / `GetAttribute` call ends up decoding all attributes applied to the target entity. While custom attributes are relatively cheap (their argument values are only decoded at a later point); security declarations are expensive as they require full decoding of the permission blob.

But most of the known attributes cannot occur within security declarations, so a `HasAttribute` / `GetAttribute` check for them performs lots of redundant work.

This is especially relevant for `AddDefinesForConditionalAttributes`, which currently ends up calling `GetAttributes()` for the target of every call.

**Comment by siegfriedpammer** [comment]
Fixed by #2765
