### ISSUE TITLE
Resource files not decompiled correctly

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1225]
Using ILSpy 4 from source.

Steps:
1. Create a new C# library project
2. Add a new resource file with a new icon
3. Compile the project and open the output in ILSpy
4. Save assembly code to a directory

WholeProjectDecompiler tries to save embedded resources files relative to the decompiler exe rather than the target directory.

**Comment by dgrunwald** [comment]
I think I found the problematic code path in `WholeProjectDecompiler`, though I'm not sure if it was reachable in ILSpy, because ILSpy was overriding that code path in a derived class.
Can you check if the problem is solved now?

**Comment by mmusu3** [comment]
Sorry, the instructions may have been faulty as I have been using the decompiler as a library. The issue seems to be mostly resolved however there is still a problem with resx renaming. Resources with long names are not having their file extension changed correctly due to the 64 character limit set in `WholeProjectDecompiler.CleanUpFileName`. Thank you for looking into this.

**Comment by dgrunwald** [comment]
Hmm, I'm not sure what we could do on too-long file names... but I guess the 64 char limit is a bit too aggressive. I'll increase it to 200 chars. Decompiling into a directory with a name longer than 59 chars may now fail if [long path support](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/) isn't enabled.

**Comment by greenozon** [comment]
Pardon putting my 5 cents, but why 200 chars? :)
usual value is MAX_PATH which is 256 AFAIK.

Regards long path support - its disabled by default + has other limitations (eg I bet it won't work on FAT like FS)

**Comment by dgrunwald** [comment]
The limit here is on a file name (for some callers, on the file name without extension).
The Windows MAX_PATH=260 limit is for the whole absolute path. So using 200 still leaves a bit of room for the directory path and file extension.
200 is already a rather high limit and may require long path support... if you say we shouldn't rely on that, I'll just keep the limit at 64.

**Comment by mmusu3** [comment]
Maybe it would be better it CleanUpFileName excluded the extension when trimming the path

**Comment by dgrunwald** [comment]
I'd like to avoid a bunch of extra logic in a security-critical function.
Also, not every caller of `CleanUpFileName` uses it for a filename in the way the resource code does; it can also be a directory name or file name without extension.
