### ISSUE TITLE
SequencePointBuilder: No sequence points generated for nested ILFunctions (i.e., lambdas)

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1229]
Test case:

    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(args.Length);
            Test((a, b) => a + b);
        }

        static void Test(Func<int, int, int> f)
        {
            f(1, 2);
        }
    }

Note that this makes the `PortablePdbWriter` generate an invalid pdb file. We'll need fixes in both areas.

**Comment by dgrunwald** [comment]
Cannot reproduce; stepping into lambdas works fine.
