### ISSUE TITLE
Executable not found after downloading files

### ISSUE THREAD

**Issue by absoluteAquarian** [icsharpcode/ILSpy#1238]
I followed the directions on the main page on how to download and run ILSpy.
However, when I ran the solution through the file explorer, it just opened it in Visual Studio 2017.

The image below is the content of the main directory the files were installed to.
All folders that are supposed to be present are present.
![ilspy why](https://user-images.githubusercontent.com/30454621/43239396-ae6e5e4e-9057-11e8-856f-6378098c9382.JPG)

**Comment by christophwille** [comment]
You downloaded the source, not the precompiled binaries. You are looking for eg https://github.com/icsharpcode/ILSpy/releases/download/v4.0-alpha1/ILSpy_binaries_4.0.0.4226-alpha1.zip
