### ISSUE TITLE
ILSpy 3.2 fails StrongName validation

### ISSUE THREAD

**Issue by Shlomibo** [icsharpcode/ILSpy#1239]
The binaries provided as version 3.2 of ILSpy fail validation, as if their signature is invalid.

Versions 3.1 and 3.0 are valid.

**Comment by dgrunwald** [comment]
In 3.2 we started patching the compiled ILSpy.exe to increase the default stack size. I completely forgot we were strong-naming our executable.
I guess we'll have to re-sign in the post-build-action... and for 4.0 we should consider getting rid of the strong name, if possible. (unfortunately strong names interact with versioning for ILSpy plugins...)
