### ISSUE TITLE
Unnecessary and wrong convertion int nullable type

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1252]
[Web.zip](https://github.com/icsharpcode/ILSpy/files/2274164/Web.zip)

Web.Areas.Admin.Controllers.AgencyController.Delete
```
		public ActionResult Delete(string IDS)
		{
			string[] arr = IDS.Split(',');
			int AID = base.Session["AdminID"].ParseInt();
			int s = (from a in db.Agency
			where arr.Contains(a.ID.ToString()) && (object?)a.AdminID == (object?)(int?)AID
			select a).Update((Agency a) => new Agency
			{
				IsDel = (int?)1
			});
			return Json(new Result(s));
		}
```
ILSpy try to convert something to (object?), but 'object' isn't value type, so it's an error, and convert to (int?) is unnecessary
The correct code is :
where arr.Contains(a.ID.ToString()) && a.AdminID == AID

**Comment by dgrunwald** [comment]
That commit on Aug 10 just hides the bug: the comparison is supposed to be a lifted value comparison, not a reference comparison. The ILAst is already wrong, as it indicates a lifted reference comparison (which explains trying to cast to `object?`). Hiding the `?` made the code compile, but it's still the wrong type of comparison.
