### ISSUE TITLE
Invalid decompilation of interface property implementation

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1266]
ILSpy is producing an invalid explicit method implementation for a property getter.
`Error CS0683 'TestClass.get_transform()' explicit method implementation cannot implement 'ICanvasElement.transform.get' because it is an accessor`
```cs
Transform ICanvasElement.get_transform()
{
    return base.transform;
}
```
I have attached a project which reproduces this error. It is referencing Unity engine dlls however I have encountered this issue in non unity projects, though I have not been able to recreate a standalone test with these after many attempts to do so. The attached sample is the best I can get.
[ILSpyInterfaceTest.zip](https://github.com/icsharpcode/ILSpy/files/2304946/ILSpyInterfaceTest.zip)

**Comment by siegfriedpammer** [comment]
To me it seems this is a bug in the compiler, because there is no metadata for the property (i.e. no rows in the `Property` or `PropertyMap` table of `TestProject.dll`. I don't think that this is fixable.

**Comment by mmusu3** [comment]
Is it a bug in the compiler that compiled the Unity dlls or the TestProject? I compiled TestProject using the most recent release version of Visual Studio at the time. I have experienced this issue both in a Unity assembly and a non unity assembly. I would expect them to have been compiled with different compilers. I had been trying to isolate a small reproduction from a non Unity project since ILSpy v2 but had never manged to create one, so when I eventually got this one I gave up and sent it with the Unity dlls as is. The test project was not compiled with unity, it only references the dlls from elsewhere.

**Comment by siegfriedpammer** [comment]
I tried a bunch of other decompilers to see what they're producing. All of them treat this method similar to what ILSpy generates.

**Comment by mmusu3** [comment]
It sounds like there's not much you can do. Can the erroneous methods be removed since they have reserved names that cause compiler errors or are they required i some way for the program to function correctly? I know my test isn't a great example of such behavior but you'd know better than me if that is the case. If there is nothing you can do I'll just have to manually deal with the few cases that appear. Thanks for looking into this!

**Comment by siegfriedpammer** [comment]
I doubt that we will be able to fix this. Omitting the method from the output seems to be a bad idea, because it might be needed, or might be of interest to an ILSpy user. This is unfortunate, but please deal with such cases manually. Sorry for the inconvenience!
