### ISSUE TITLE
Bad decompilation of yields

### ISSUE THREAD

**Issue by tellowkrinkle** [icsharpcode/ILSpy#1269]
When decompiling [the Assembly-CSharp.dll for Higurashi Vol. 6](https://github.com/icsharpcode/ILSpy/files/2317615/Assembly-CSharp.dll.zip), a large number of files including `Assets.Scripts.UI.Prompt/PromptController.cs `, `Assets.Scripts.UI.SaveLoad/SaveLoadManager.cs`, and `Assets.Scripts.UI/MainUIController.cs` are left with lines like `/*Error: Unable to find new state assignment for yield return*/;` after yield statements, with the rest of the code missing.

**Comment by dimamatik** [comment]
Hello! I have a same issue with .dll, compiled by Mono from Unity Engine. For example, this code:
`while (oneObject.itsfield == false)
{
yield return null;
}
`
decomiled as:
`if (oneObject.itsfield == false)
{
yield return null;
/*Error: Unable to find new state assignment for yield return*/;
}
`
while circle was changed to if!!!
the latest release (4.0.0.4358-beta2) does not fix this problem
you can contact me by email (dimamatik[at]yandex[dot]ru) for more information and testing

**Comment by dimamatik** [comment]
@siegfriedpammer 
Hello! I have a same problem on 4.0.0.4358-beta2. Code, generated with Unity3d, like:
`while (myObject.itsField == false) { yield return null; }`
was decompiled as:
`if (myObject.itsField == false) { yield return null; /*Error: Unable to find new state assignment for yield return*/;}`

Please, fix!
You can contact me by email dimamatik[at]yandex[dot]ru for more info.

**Comment by dimamatik** [comment]
@vizv @siegfriedpammer
Hello! I download and build your fix (fix-yield-return-generated-from-mono) for "Unable to find new state assignment for yield return" problem. It's works! But I have a problem with simillar code:

I am using Unity 2018 with Mono compiler integrated into this engine
This class:
`using System.Collections;`
`using System.Collections.Generic;`
`using UnityEngine;`

`public class Test : MonoBehaviour `
`{`
`	List<Test> children = new List<Test>();`
`	public IEnumerable<Test> Children`
`	{`
`		get`
`		{`
`			foreach( Test item in children)`
`			{`
`				yield return item;`
`			}`
`			yield break;`
`		}`
`	}`
`}`

was decompiled with error after yield break line:
`IL_00bd:`
`/*Error near IL_00be: Unexpected return in MoveNext()*/;`
(all over code decompiled right)
Please, fix it too

**Comment by vizv** [comment]
@siegfriedpammer Could you attach a copy of pre-compiled `Assembly-CSharp.dll`

**Comment by dimamatik** [comment]
[Test.zip](https://github.com/icsharpcode/ILSpy/files/2530725/Test.zip)

Here is .zip with compiled .dll and script file. Used Unity 2018.2.11f1

**Comment by vizv** [comment]
@dimamatik That's a different issue, switch analysis doesn't clean up orphan blocks correctly.

**Comment by siegfriedpammer** [comment]
@dimamatik Yes, please do create a new issue. We want to keep things clean.

**Comment by dimamatik** [comment]
@vizv Ok, created https://github.com/icsharpcode/ILSpy/issues/1307
