### ISSUE TITLE
Cannot resolve base member

### ISSUE THREAD

**Issue by gatodevelop** [icsharpcode/ILSpy#1272]
If the Identifier is a base member, Identifier.GetResolveResult () returns ErrorResolveResult.
If it is a base method, IdentifierExpression.GetResolveResult () returns ErrorResolveResult, too.

**Comment by siegfriedpammer** [comment]
No, because there can be multiple methods with the same name. Of course we could provide a MethodGroupResolveResult there, but that is not implemented currently.

**Comment by gatodevelop** [comment]
I see. Thank you.
