### ISSUE TITLE
Decompilation generates code that only works on framework 4.7.2

### ISSUE THREAD

**Issue by ststeiger** [icsharpcode/ILSpy#1273]
If code contains a function such as 
`public static void foo(string arg1, bool canWrite, string arg3)`
which is then called as 
`foo("arg1", true, "arg3");`
The decompilation yields 
`foo("arg1", canWrite: true, "arg3");`
But this only compiles on framwork 4.7.2. 

Correct would be 
`foo("arg1", true, "arg3");`

**Comment by siegfriedpammer** [comment]
This feature is part of C# 7.3 and not connected to the .NET Framework version used in any way. You can simply select a lower language version from the version dropdown and the decompiler will not generate code using features from that version.

However, keep in mind that among other things, the decompiler cannot remove generic types from the code when selecting C# 1.0. This is impossible.

**Comment by ststeiger** [comment]
Ah, didn't notice this dropdown before. 
Apparently there since 3.1. 
Sorry to bother you - my fault.
