### ISSUE TITLE
CSharpDecompiler should implement IDisposable to deterministically release file locks

### ISSUE THREAD

**Issue by z1c0** [icsharpcode/ILSpy#1275]
I have a scenario, where I need to delete assemblies again immediately after decompilation. This does not work currently, because a `PEFile` in `MetadataModule` instance keeps a lock on the file.

A solution would be to make `CSharpDecompiler` and `MetadataModule` `IDisposable` to have a deterministic way of releasing the file lock (since `PEFile` already implements `IDisposable`)

```csharp
static string Decompile(string filePath)
{
	string code = "";
	using (var decompiler = GetDecompiler(filePath)) {
		code = decompiler.DecompileWholeModuleAsString();
	}
	File.Delete(filePath); // now works, since CSharpDecompiler and MetadataModule are disposable
	return code;
}

static CSharpDecompiler GetDecompiler(string assemblyFileName)
{
	return new CSharpDecompiler(assemblyFileName, new DecompilerSettings() {  ThrowOnAssemblyResolveErrors = false });
}
```

**Comment by siegfriedpammer** [comment]
@dgrunwald what's your opinion on this issue? Thanks!

**Comment by dgrunwald** [comment]
The decompiler shouldn't implement IDisposable. It usually doesn't own the PEFile and thus shouldn't destroy it.
In ILSpy 3.x the CSharpDecompiler(string) constructor was just loading the assembly into memory without locking the file; we should do the same in 4.0.

**Comment by z1c0** [comment]
Thank you @siegfriedpammer that solves my problem.
Sorry that I missed that setting.
