### ISSUE TITLE
RemoveDeadCode option messes up array initialization

### ISSUE THREAD

**Issue by gatodev** [icsharpcode/ILSpy#1280]
Source:

    class Test {
        public Test() {
            int[] a = { 1 };
            int[] b = { 1, 2 };
            int[] c = { 1, 2, 3 };
            int[] d = { 1, 2, 3, 4 };
            int[,] e = { { 1 } };
        }
    }

Output:

    internal class Test
    {
        public Test()
        {
            (new int[1])[0] = 1;
            int[] obj = new int[2]
            {
                1,
                2
            };
            RuntimeHelpers.InitializeArray(new int[3], (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
            RuntimeHelpers.InitializeArray(new int[4], (RuntimeFieldHandle)/*OpCode not supported: LdMemberToken*/);
            (new int[1, 1])[0, 0] = 1;
        }
    }

**Comment by siegfriedpammer** [comment]
The "remove dead code" option is not intended for normal C# code. It was added for F# and some special cases. Do not use it for standard unobfuscated C# code.

**Comment by gatodevelop** [comment]
I see. Thank you.

**Comment by siegfriedpammer** [comment]
I will keep this open and take a look at the problem anyway.
