### ISSUE TITLE
Decompiling types in non-main modules

### ISSUE THREAD

**Issue by gatodevelop** [icsharpcode/ILSpy#1282]
The types at the same rows in the main module are decompiled.
If this cannot be done, an exception should be thrown.

**Comment by siegfriedpammer** [comment]
Can you please provide an example? Thank you very much!

**Comment by gatodevelop** [comment]
Source:

    using System;
    using System.Linq;
    using System.Reflection;
    using ICSharpCode.Decompiler;
    using ICSharpCode.Decompiler.CSharp;

    static class MainClass {
        static void Main() {
            var decompiler = new CSharpDecompiler(
                Assembly.GetExecutingAssembly().Location, new DecompilerSettings());
            var module = decompiler.TypeSystem.Modules[1];
            var typeDefinition = module.TypeDefinitions.ElementAt(1);
            var fullTypeName = typeDefinition.FullTypeName; // Interop
            var syntaxTree = decompiler.DecompileType(fullTypeName);
            Console.WriteLine(syntaxTree);
        }
    }

Output:

    using ICSharpCode.Decompiler;
    using ICSharpCode.Decompiler.CSharp;
    using ICSharpCode.Decompiler.CSharp.Syntax;
    using ICSharpCode.Decompiler.TypeSystem;
    using System;
    using System.Linq;
    using System.Reflection;

    internal static class MainClass
    {
        private static void Main ()
        {
            CSharpDecompiler cSharpDecompiler = new CSharpDecompiler (Assembly.GetExecutingAssembly ().Location, new DecompilerSettings ());
            IModule module = cSharpDecompiler.TypeSystem.Modules [1];
            ITypeDefinition typeDefinition = module.TypeDefinitions.ElementAt (1);
            FullTypeName fullTypeName = typeDefinition.FullTypeName;
            SyntaxTree value = cSharpDecompiler.DecompileType (fullTypeName);
            Console.WriteLine (value);
        }
    }

**Comment by siegfriedpammer** [comment]
Now I understand, thank you!

@dgrunwald Do you think we should support decompiling code from any loaded module or clarify APIs, documentation and implementations (i.e. explicit module checks and throwing exceptions) that this is not supported? AFAIK we only load metadata for modules other than the main module, so fixing this by explicitly stating that it's not possible, seems to be the best idea. I don't want to change the decompiler engine too much.

**Comment by dgrunwald** [comment]
The assembly being decompiled must be the main assembly of the type system; anything else would cause the type system to misbehave.
Yes, we should throw an exception in this case. (I thought we already did so -- did this get lost in the SRM port?)
