### ISSUE TITLE
Dump IL

### ISSUE THREAD

**Issue by 3asm** [icsharpcode/ILSpy#1284]
Does ILSpy offer a command line utility to dump IL, similar to what ICSharpCode.Decompiler.Console does, but only for IL?

**Comment by siegfriedpammer** [comment]
This feature is currently not on our list. However, it can be easily added using `ICSharpCode.Decompiler.Disassembler.ReflectionDisassembler`. Contributions are welcome! If you want to help out and have questions, please feel free to ask!

**Comment by kmatyaszek** [comment]
@3asm please check my commit [f45dcf0](https://github.com/kmatyaszek/ILSpy/commit/f45dcf0e62cb430e7508a3001448b55a91c0caf2), I think that it resolve your problem.

**Comment by 3asm** [comment]
Super, that's very helpful. Thanks @kmatyaszek.
