### ISSUE TITLE
Crashes ever time I start it.

### ISSUE THREAD

**Issue by Heimerdawg** [icsharpcode/ILSpy#1288]
ILSpy crashes every time I start it.

Error:
https://gyazo.com/0412c1244ed94a45d8e35196e411ae39

**Comment by dgrunwald** [comment]
ILSpy 4.0 is not compatible with ILSpy 3.x plugins.

**Comment by Heimerdawg** [comment]
> ILSpy 4.0 is not compatible with ILSpy 3.x plugins.

Okay, sorry, I did not notice the version difference. Thank you, it is working now.

**Comment by sailro** [comment]
I made a Refexil PR for properly supporting ILSpy v4: https://github.com/sailro/Reflexil/pull/142
