### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kingshreyash** [icsharpcode/ILSpy#1291]
Installed Successfully, but on starting of any .sln gives this error:

LegacySitePackage failed for package [ILSpyAddInPackage]Source: 'ILSpy.AddIn' Description: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. 
File name: 'Microsoft.VisualStudio.LanguageServices, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'   at ICSharpCode.ILSpy.AddIn.ILSpyAddInPackage.Initialize()   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by christophwille** [comment]
What exact version of Visual Studio are you using?

**Comment by kingshreyash** [comment]
I upgraded VS2017 to latest update, and this resolved the issue.
It works like a charm. If I anything I can do in retrun of favor, please let me know. Cheers
