### ISSUE TITLE
Decompilation yields invalid code (4.0b2)

### ISSUE THREAD

**Issue by IanKemp** [icsharpcode/ILSpy#1298]
1. https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/Extensions.cs#L190-L194

ILSpy generates the following for that `if`-block, which of course does not compile as there is no direct cast from `JToken` to `JValue`:

```csharp
					if (item is JValue)
					{
						yield return ((JValue)item).Convert<JValue, U>();
					}
```

2. https://github.com/yunfeifei/QRCodeTools/blob/master/ThoughtWorks.QRCode/reader/QRCodeDataBlockReader.cs#L23

ILSpy generates code that references a label that is out of scope.

**Comment by siegfriedpammer** [comment]
ad 1) I cannot reproduce this using ILSpy latest master and Newtonsoft.Json v11.0.0.0.
The code mentioned always uses as + null check as the original code did (version from 2018-10-14: https://github.com/JamesNK/Newtonsoft.Json/blob/3154a6de68f12c5c3e1576ccdba5f1177827cd9f/Src/Newtonsoft.Json/Linq/Extensions.cs#L190-L194)

ad 2) could you please provide the binary you used? There is no official download available from the link you provided.

Thank you very much for your help!

**Comment by siegfriedpammer** [comment]
No feedback -> close
