### ISSUE TITLE
Please add assembly load path for VS NuGet cache

### ISSUE THREAD

**Issue by miaodadao** [icsharpcode/ILSpy#1300]
New NuGet will use a default package cache path at `C:\Users\${USER}\.nuget\packages`, please add it into the default assembly load path or users can setting for it.
This is important for browser dlls of dotnet core, otherwise you have to find the right path manual.
Thank you.

**Comment by kant2002** [comment]
Also if you will be loading that, please consider using `NUGET_PACKAGES` (IIRC) environment variable as override for standard Nuget packages location.

**Comment by siegfriedpammer** [comment]
ILSpy should already handle the `.nuget\packages\` path correctly. Do you have an example binary where it fails?

**Comment by carlreinke** [comment]
This doesn't work for me either.

Seems like it's looking for a JSON attribute that doesn't exist because of the `"/"` here:
https://github.com/icsharpcode/ILSpy/blob/09524224eeb00e5f3edaccf33e89cfb019ab03ad/ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs#L105
whereas my .deps.json file looks like
```json
  "targets": {
    ".NETCoreApp,Version=v2.1": {
```

**Comment by siegfriedpammer** [comment]
@carlreinke Thank you for providing an example, that demonstrates the problem.

I consider this fixed, If there are further problems, please feel free to open a new issue.

**Comment by nvmkpk** [comment]
I would like ILSpy to resolve references from nuget cache path. I will create another issue for that.

**Comment by carlreinke** [comment]
The latest CI build is loading assemblies from the NuGet cache for me.  Did you try it?

**Comment by nvmkpk** [comment]
No, I have the version that is released in marketplace and it does not load from the nuget cache path.
