### ISSUE TITLE
NullReference Exception in search area

### ISSUE THREAD

**Issue by Sedighzade** [icsharpcode/ILSpy#1306]
How to reproduce the bug:
1- Click the 'Search' icon
2- The search box appears.
3- Click on the either of the listview columns ( 'Name' or 'Location' ).
4 - A messagebox appeares with 'NullReferenceException' exception.

My version is  3.2.0.3856.

**Comment by siegfriedpammer** [comment]
This was fixed in v4.0-beta1 (see 38247fed2d229cec9e6af9e77f094f28374f67d8).
