### ISSUE TITLE
Methods in .winmd files compiled from C# don't show up in individual method view in ILSpy 4

### ISSUE THREAD

**Issue by TautvydasZilys** [icsharpcode/ILSpy#1311]
To reproduce this, open this file in ILSpy 4:

[RuntimeComponent1.zip](https://github.com/icsharpcode/ILSpy/files/2578260/RuntimeComponent1.zip)

You'll see this: 

![image](https://user-images.githubusercontent.com/1092489/48444972-466dd780-e74a-11e8-954d-9df570927346.png)

However, if you go to the declaring class, you can see the method body, but it's incorrect:

![image](https://user-images.githubusercontent.com/1092489/48445005-5be30180-e74a-11e8-82de-7f91e6335f33.png)

This does not happen in older ILSpy versions (screenshot from 2.4):

![image](https://user-images.githubusercontent.com/1092489/48445030-6c937780-e74a-11e8-8c05-eff005d5518d.png)

**Comment by siegfriedpammer** [comment]
This one is funny: CFF Explorer shows a RVA value greater than 0 for method 1.

![grafik](https://user-images.githubusercontent.com/344204/48867898-0a84e300-edd8-11e8-8807-d326a89470a5.png)

How come System.Reflection.Metadata does not return the same value?

![grafik](https://user-images.githubusercontent.com/344204/48867981-5a63aa00-edd8-11e8-85c2-f86c806980a6.png)

@sharwell @tmat Would you be able to take a look at this one? Thank you very much!

**Comment by TautvydasZilys** [comment]
> WinMDs are tricky since they can be viewed in two modes - raw and projected. The mode is specified via an option when creating the reader.

That is true for cecil too (https://github.com/jbevain/cecil/blob/eea822cad4b6f320c9e1da642fcbc0c129b00a6e/Mono.Cecil/ModuleDefinition.cs#L103). TBH I think that should be an option in ILSpy, similar to how "decompile await constructs" is.

Do you believe this is a bug in the metadata reader, or rather how it is used?

**Comment by tmat** [comment]
Not a bug. You are looking at the wrong class: `<WinRT>Class1`. Is the method body in `Class1`?

**Comment by TautvydasZilys** [comment]
It's not.

![image](https://user-images.githubusercontent.com/1092489/48889386-91db5200-edea-11e8-8f00-a4ff8f51430c.png)

**Comment by siegfriedpammer** [comment]
So, when I disable the application of WinRT projections, the RVA will be reported correctly. Then the method body is displayed in `<WinRT>Class1`. However, as applying WinRT projections is the default, I would have expected the method body to be visible from `Class1` when applying the projections.

@tmat Thank you very much for the hint!
@dgrunwald Do we actually ever need WinRT projections to be applied? #1127 comes to mind. I think the best way would be to add an option, so the user can decide whether they want projections applied or not.
