### ISSUE TITLE
Provide precompiled Linux binaries

### ISSUE THREAD

**Issue by aaronfranke** [icsharpcode/ILSpy#1312]
https://github.com/icsharpcode/ILSpy/releases

I tried downloading the binaries ZIP file. The EXE does not run in the Mono runtime and does not run in Wine either (though that's beside the point). Please provide precompiled Linux binaries.

**Comment by dgrunwald** [comment]
The ILSpy UI uses WPF, which is Windows-only. Only the decompiler engine itself is cross-platform.
We have a cross-platform UI over at https://github.com/icsharpcode/AvaloniaILSpy but it's a work-in-progress. You'll find Linux binaries there.

**Comment by christophwille** [comment]
Also https://github.com/icsharpcode/ILSpy/tree/master/ICSharpCode.Decompiler.Console is xplat.
