### ISSUE TITLE
var names from .pdb file

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1313]
is it possible to read out variable names from generated .pdb file (by VisualStudio)
for the moment I see auto-generated var names

I see that ILSpy could generate .pdb files, but could it consume already present ones?

**Comment by siegfriedpammer** [comment]
Actually, ILSpy should support this already. Could you possibly have disabled the feature in the options dialog?

![grafik](https://user-images.githubusercontent.com/344204/48515886-4eb93600-e862-11e8-8bc2-307fb27908b1.png)

If it's not working, please provide an example binary + PDB. Thank you very much!

**Comment by greenozon** [comment]
Just checked - that checkbox is ON (I did not even know about it :) ) - 

http://prntscr.com/ligy8v

pdb is here (as well as my full simple project!)

https://www.sendspace.com/file/rku5yx

used latest VS2017 for this.
