### ISSUE TITLE
Goto Entrypoint feature

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1315]
Is it possible to add "Goto Entrypoint" right click menu item over assembly in the left treeview pane?
would be very handy I guess
gray this menu out if there is no EP defined (eg: dll)

**Comment by siegfriedpammer** [comment]
There should be a hyperlink on the method name on the line `// Entry point: ConsoleApp9.Program.Main`, in the decompiler view after selecting the assembly node.

Is that sufficient? If not, please explain. Thanks!

**Comment by greenozon** [comment]
wow, YES!
very cool
pardon me, but that's non-obvious! (clickable item)

consider making it like hyperlink (eg blue colored)

wow again :)
