### ISSUE TITLE
Export to VS2010 format fails

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1318]
When exporting to VS2010 sources, there is an issue reported by the compiler:

Error	5	Invalid option '4' for /langversion; must be ISO-1, ISO-2, 3 or Default	...

VisualStudio 2010  version 10.0.40219.1 SP1Rel

PS
used  ILSpy version 4.0.0.4382-beta2

**Comment by greenozon** [comment]
Looks like a VS2010 limitation
possible solution here -

https://social.msdn.microsoft.com/Forums/vstudio/en-US/5757472f-8b17-42c9-afa6-6d0c5eeb9e1c/cant-set-language-version-to-c-40-in-visual-studio-2010?forum=visualstudiogeneral



2) here is an Advanced project options from VS2010  - it does not have value "4"... strange!?

http://prntscr.com/ljsmhi

**Comment by siegfriedpammer** [comment]
This is strange. When adding the language versions dropdown we took inspiration from [this](https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md#c-4-vs-2010) list, which explicitly mentions that VS 2010 equals C# version 4.

To me this looks like a limitation in Visual Studio 2010 and I don't think we have the resources to add special code to support this, unfortunately.
