### ISSUE TITLE
How to build ILSpy 3.2.0.3856?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1320]
I builded ILSpy 3.2.0.3856 a few days ago.
But now, I forgot how did I do it, I can only build ILSpy 3.2.0.0-no-branch.(commit 60726e97, Fix BamlDecompiler.Tests)
Which commit shoud I choose to build 3.2.0.3856?

**Comment by Rpinski** [comment]
You're building the correct commit. If the resulting build version confuses you: Have you deleted the `.git` directory or have you just downloaded the source code without cloning it from GitHub? The build needs a Git repo to generate version information properly.

**Comment by siegfriedpammer** [comment]
What's the status of this? Is this resolved?
