### ISSUE TITLE
ILSpy developer meeting in Stuttgart 2019-02-14 to 2019-02-17

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/ILSpy#1321]
In the past, we had a yearly "SharpDevelop developer days" meeting in Bad Ischl, Austria.
In the last years, this was effectively an ILSpy meeting, since our other projects are inactive.

So this time around, we're making it official and announcing it here: the next meeting will be in Stuttgart, Germany on Feb Thu 14th - Sun 17th 2019.

If you are interested in coming and contributing to ILSpy, please let me know.

Currently planning to come: @dgrunwald @siegfriedpammer @christophwille
Pinging some contributors who might be interested: @jeffreye @vizv @agametov @Chicken-Bones @Viridovics @CreateAndInject @sharwell @tmat

**Comment by Chicken-Bones** [comment]
That'd be awesome, if only I didn't live in Australia, and wasn't going on holidays at the time. I'd be interested in reading a summary of the meeting, and donating further contributions in the future.

**Comment by vizv** [comment]
Thanks for the invitation, however I couldn't join the meeting.
I use ILSpy for Unity game modding, and I might continue contribute the project if I have time.

**Comment by maxtoroq** [comment]
I'm sure this is not the best place for this, but I just wanted to express my gratitude for making this tool that increases my happiness. THANK YOU!

**Comment by christophwille** [comment]
I'll keep updating this comment with "What have we been doing" at our dev meeting:

* https://github.com/icsharpcode/ILSpy/issues/1416 We dropped support for all TFMs except netstandard2.0
