### ISSUE TITLE
Mis-decompilation of (strange) bool ToString(), becoming int ToString()

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1333]
Arg '1' is obviously a string.

For the following somewhat strange IL, ILSpy mis-decompiles this as turning `int` into a string (`0`/`1`), instead of `bool` (`false`/`true`).
```
ldarg.1
ldc.i4.0
stloc.1
ldloca.s 1
constrained. [mscorlib]System.Boolean
callvirt instance string [mscorlib]System.Object::ToString()
stind.ref
ldc.i4.1
ret
```
and
```
ldarg.1
ldc.i4.1
stloc.1
ldloca.s 1
constrained. [mscorlib]System.Boolean
callvirt instance string [mscorlib]System.Object::ToString()
stind.ref
ldc.i4.1
ret
```

**Comment by dgrunwald** [comment]
I'm assuming the variable used by `ldloca.s 1` is of type `int` and not `bool`?

The IL is indeed strange.
If the bool.ToString() implementation modified `this`, the new value would be visible in the original variable of type `int`!
The correct decompilation is not a cast to `bool`, but rather a reference cast to `ref bool`. C# doesn't have reference casts, so the closest thing we can emit is a pointer cast: `((bool*)&num)->ToString()`

**Comment by dgrunwald** [comment]
Oh, the bug also occurs if the local variable has the type `bool`, because inlining removes the variable so the original type doesn't really matter (though we check that the value stored fits into the type of the variable).
