### ISSUE TITLE
Extension for Visual Studio 2019

### ISSUE THREAD

**Issue by maratbakirov** [icsharpcode/ILSpy#1335]
Could it be possible to adapt the extension
https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy

to support visual studio 2019?

it would be very helpfull...

**Comment by christophwille** [comment]
I have added support for VS2019 by following Mads' guidelines and on first testing, it works as expected. Please note that this checkin in post-Beta3, therefore you'd have to build yourself atm.

![install_vs2019](https://user-images.githubusercontent.com/344208/50053577-e5199980-0137-11e9-844f-ab8445429e4e.png)

**Comment by christophwille** [comment]
You can give these build artefacts a try https://ci.appveyor.com/project/icsharpcode/ilspy/builds/21043323/job/n20o4qatmbmwlcr6/artifacts
