### ISSUE TITLE
CSharpDecompiler support loading from Stream

### ISSUE THREAD

**Issue by daningalla** [icsharpcode/ILSpy#1337]
Please add a constructor overload to CSharpDecompiler that will accept an input stream in addition to file names and the other options.

Or, am I missing something in the API that facilitates this already?

**Comment by siegfriedpammer** [comment]
> Or, am I missing something in the API that facilitates this already?

Which version of the decompiler did you try to use? In 4.x you can use `PEFile` to achieve this.

**Comment by daningalla** [comment]
Excellent - I see you are referring to the betas. Will check it out, thank you kindly.

**Comment by siegfriedpammer** [comment]
I think this is resolved. If you have any further questions, please open a new issue. Thanks!
