### ISSUE TITLE
Obfuscated names question

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1359]
ILSpy version 4.0.0.4472-beta3

question: are there any plans to translate (make visible) obfuscated namespaces/classes/methods/types/etc inside the tool?

to be more specific, the question is all about just to properly visualize, not do any real conversions/renames/etc

as for the moment there are two parts:
in the left tree these are not visible at all
in the right pane some symbols grayed out are being printed out

example:

![screenshot_31](https://user-images.githubusercontent.com/765343/50419703-dc614b80-083a-11e9-926f-c925f95ac52b.png)

Expected behavior: consider some scheme of translating (just for visual perception of end-user) of invisible names

Example of possible solution (translating invisible (unicode) chars into \u1234 - it takes more display footprint, but at least one might work with it/analyze/navigate/etc

![screenshot_34](https://user-images.githubusercontent.com/765343/50419807-775a2580-083b-11e9-8068-17f48d5b584f.png)

**Comment by greenozon** [comment]
Thank you for you interest and response
From end-user perspective - any option would be fine :)
as the goal is read-ablity as well as click-ability and navigation

**Comment by lextm** [comment]
Usually you can run de4dot before opening the assembly in ILSpy, https://github.com/0xd4d/de4dot IMHO ILSpy shouldn't attempt to do anything special for obfuscated assemblies.

**Comment by greenozon** [comment]
Of course, de4dot to the rescue, but it does not cover 100% of use cases.
Very often you need to peek into input assembly to understand some tidbits
and you can't
see my pics above why
