### ISSUE TITLE
nameof usage instead of plain text

### ISSUE THREAD

**Issue by sungam3r** [icsharpcode/ILSpy#1362]
In the code there are constructions like

```
	public bool ShowInternalApi {
			get { return ShowApiLevel == ApiVisibility.PublicAndInternal; }
			set {
				if (ShowApiLevel == ApiVisibility.PublicAndInternal) {
					ShowApiLevel = ApiVisibility.PublicOnly;
				} else {
					ShowApiLevel = ApiVisibility.PublicAndInternal;
				}
				OnPropertyChanged("ShowInternalApi");
				OnPropertyChanged("ShowAllApi");
			}
		}
```
with literal strings mainly for OnPropertyChanged

For safe use and to simplify the search consider to change it everywhere to nameof:

```public bool ShowInternalApi {
			get { return ShowApiLevel == ApiVisibility.PublicAndInternal; }
			set {
				if (ShowApiLevel == ApiVisibility.PublicAndInternal) {
					ShowApiLevel = ApiVisibility.PublicOnly;
				} else {
					ShowApiLevel = ApiVisibility.PublicAndInternal;
				}
				OnPropertyChanged(nameof(ShowInternalApi));
				OnPropertyChanged(nameof(ShowAllApi));
			}
		}
```

**Comment by siegfriedpammer** [comment]
Currently, there are no plans to introduce `nameof` expressions in the decompiled output, because things can get quite complicated. For more information on which language features we are focusing on currently, see #829.

**Comment by sungam3r** [comment]
I talk about  ILSpy codebase itself, not decompiled output.
For example:
 https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/FilterSettings.cs#L67
or
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/FilterSettings.cs#L92

**Comment by siegfriedpammer** [comment]
@sungam3r Oh sorry, I misunderstood. Normally people ask about decompilation quality, that's why I jumped conclusions.

@siriak Thank you for providing a pull request.
