### ISSUE TITLE
Build error [HEAD + VS 15.9.4]

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1370]
I don't even know if this is a Microsoft error or ILSpy error, and since even trying to understand that MSBuild gibbersih makes an explorative root canal with a blunt spoon seem preferred, I defer it to people with greater patience.

_The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd' has invalid child element 'license' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'. List of possible elements expected: 'packageTypes, repository, releaseNotes, iconUrl, tags, language, developmentDependency, description, serviceable, licenseUrl, summary, dependencies, contentFiles, requireLicenseAcceptance, copyright, projectUrl, references, frameworkAssemblies' in namespace 'http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd'. This validation error occurred in a 'license' element.	ICSharpCode.Decompiler	C:\Program Files\dotnet\sdk\2.0.2\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	204_

**Comment by christophwille** [comment]
This is related to https://github.com/icsharpcode/ILSpy/commit/0905cf74ac68bb2aecfea1412eebc67cafbc7d61 - on publishing Beta 3, I got the deprecation notice and fixed the nuspec. 

Note that you need a vCurrent of NuGet. Potentially the easiest way is to install .NET Core 2.2 SDK.

**Comment by tamlin-mike** [comment]
@christophwille Thanks. Manually installing .NET Core 2.2 SDK made the build work again.

So Microsoft made a breaking change, where if you don't update/modify the XML tag it displays a deprecation warning, and if you do update the tag it completely fails to build using the mainstream tool (read: included in VS, even the latest non-testing version)?

_*rolleyes*_ Only in Redmond...

I'm leaving this issue open for now; In case someone else encounters the error (seems likely) it's easier found. Once it's included in a VS "stable" release it should be closed.

**Comment by christophwille** [comment]
As soon as the test cases for C# 8.0 nullable reference types is checked in, VS 2019 will be required for building the solution - and it comes with the correct latest tooling.
