### ISSUE TITLE
Fields marked 'specialname' are excluded from the type system

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1394]
There's a field 'staticLocalInitFlag_0' in the class 'frmPlot', but ILSpy doesn't show it, Reflector can.
I have already show all types and members
![image](https://user-images.githubusercontent.com/2529999/51073936-bd740d80-16b2-11e9-8b98-fd0ee6ada0f0.png)

[1.zip](https://github.com/icsharpcode/ILSpy/files/2752045/1.zip)

By the way, what is the difference between: `Show internal types and members` and `Show all types and members`

**Comment by siegfriedpammer** [comment]
> By the way, what is the difference between: Show internal types and members and Show all types and members

Show all types and members does not hide compiler-generated types and members from the tree view. Also, property and event nodes have child nodes for their accessors.
