### ISSUE TITLE
In application "ILSpy 4.0.0.4521" namespace "Chapter01.Page0051" is missing.

### ISSUE THREAD

**Issue by platonov-eugene** [icsharpcode/ILSpy#1398]
In application "**JetBrains dotPeek 2018.3.1**" namespace "**Chapter01.Page0051**" is displayed.

![dotpeek](https://user-images.githubusercontent.com/4559983/51370000-967c6800-1b06-11e9-9a9a-30246f119ef5.PNG)

In application "**ILSpy 4.0.0.4521**" namespace "**Chapter01.Page0051**" is missing.

![ilspy](https://user-images.githubusercontent.com/4559983/51370009-a005d000-1b06-11e9-893e-dbdfc5981efa.PNG)

Used assembly "**Chapter01.dll**" is attached as "**Chapter01.pdf**".
[Chapter01.pdf](https://github.com/icsharpcode/ILSpy/files/2771847/Chapter01.pdf)

**Comment by greenozon** [comment]
How about this checkbox? is it ON or OFF?
used version ILSpy version 4.0.0.4521 and
I could see your ns/classes:

![screenshot_35](https://user-images.githubusercontent.com/765343/51370676-91b4b580-1b00-11e9-82ec-951b153b03ae.png)

**Comment by siegfriedpammer** [comment]
Reactivation of "show internal types and members" should suffice in this case. Yes, this is a breaking change, because the setting went from bool to tri-state.
