### ISSUE TITLE
Setting always lose

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1399]
Open the lastest ILSpy4, checked `Show internal types and members`
Close ILSpy4, and open ILSpy 3.2, then close ILSpy 3.2, open the lastest ILSpy4
`Show internal types and members` is unchecked.

I think this is why some people say something is missing.

**Comment by siegfriedpammer** [comment]
Yes, this is a breaking change, because the setting went from bool to tri-state (enum).

I didn't want to introduce extra code to migrate the setting, because it would only be executed once.

**Comment by siegfriedpammer** [comment]
>

**Comment by CreateAndInject** [comment]
There're thousands of errors, for example:
CSharpDecompiler.DecompileTypes now doesn't support the paramter type : IEnumerable<TypeDefinition>

So, I must convert cecil to SRM, and sometimes I need to get a cecil object, so I must convert SRM to cecil.

It's so many work, I give up, thanks.
