### ISSUE TITLE
assembly resource file content can not be read inside ilspy

### ISSUE THREAD

**Issue by DaneSpiritGOD** [icsharpcode/ILSpy#1400]
assembly resource file can not be read inside ilspy

// MaterialDesignThemes.Wpf, Version=2.5.0.1205, Culture=neutral, PublicKeyToken=null
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: v4.0.30319
// Hash algorithm: SHA1
// Debug info: Loaded from PDB file: C:\Users\Administrator\.nuget\packages\materialdesignthemes\2.5.0.1205\lib\net45\MaterialDesignThemes.Wpf.pdb

the assembly above can be downloaded from nuget `materialdesignthemes`.

![image](https://user-images.githubusercontent.com/4377454/51375618-4ff82f00-1b41-11e9-9b9b-7bb5a259ba05.png)

I can read the resource files's content inside ilspy before.

**Comment by siegfriedpammer** [comment]
I cannot reprodue this.

**Comment by siegfriedpammer** [comment]
Can you check whether the BAML decompiler plugin is loaded by ILSpy? Maybe the plugin gets blocked?

**Comment by DaneSpiritGOD** [comment]
what does `BAML decompiler plugin` mean? 

![image](https://user-images.githubusercontent.com/4377454/51421984-63a7a200-1be2-11e9-8832-ec05c9626eb9.png)

I download the ilspy with vs extension.

**Comment by DaneSpiritGOD** [comment]
oh,I found the where the problem is.
ilspy vs  extension doesn't contain the `BAML decompiler plugin` while the release zip contains the file.
