### ISSUE TITLE
Option to not remember previous libraries

### ISSUE THREAD

**Issue by veccsolutions** [icsharpcode/ILSpy#1401]
It would be really nice if there was an option to not remember assemblies from the last time it was running so it wouldn't load any of those or any of the default ones. Or is this already an option and I'm missing it?

**Comment by siegfriedpammer** [comment]
Currently, there is no such option. You can only achieve this by creating a custom assembly list and manually clearing that before exiting ILSpy.

What is your use-case for this?

**Comment by veccsolutions** [comment]
Primarily when I have opened libraries across a network share it takes a long time to re-open ilspy unless I cleared out the list before closing it. Another is it's just clutter. I made my own custom build that did this as an option defaulting to current behavior. I could do a pull request with it if you would like.

**Comment by siegfriedpammer** [comment]
Yes please, pull requests are very welcome!

**Comment by veccsolutions** [comment]
Done

**Comment by siegfriedpammer** [comment]
Thank you very much!
