### ISSUE TITLE
File->Open locks the application

### ISSUE THREAD

**Issue by veccsolutions** [icsharpcode/ILSpy#1402]
When clicking the file menu, then clicking open ILSpy hangs. I've tried the most recent release (4.0.0.4521), an older release (3.2), and built from source with the current master branch and got the same results every time.

It is hanging on the `if (dlg.ShowDialog() == true) {` line in the OpenCommandExecuted method in MainWindow.xaml.cs.

I was able to get it to work by changing that method from

```csharp
void OpenCommandExecuted(object sender, ExecutedRoutedEventArgs e)
{
	e.Handled = true;
	OpenFileDialog dlg = new OpenFileDialog();
	dlg.Filter = ".NET assemblies|*.dll;*.exe;*.winmd|Nuget Packages (*.nupkg)|*.nupkg|All files|*.*";
	dlg.Multiselect = true;
	dlg.RestoreDirectory = true;
	if (dlg.ShowDialog() == true) {
		OpenFiles(dlg.FileNames);
	}
}
```

to
```csharp
void OpenCommandExecuted(object sender, ExecutedRoutedEventArgs e)
{
	e.Handled = true;
	var dlg = new System.Windows.Forms.OpenFileDialog();
	dlg.Filter = ".NET assemblies|*.dll;*.exe;*.winmd|Nuget Packages (*.nupkg)|*.nupkg|All files|*.*";
	dlg.Multiselect = true;
	dlg.RestoreDirectory = true;
	dlg.ShowHelp = true;

	if (dlg.ShowDialog() ==  System.Windows.Forms.DialogResult.OK) {
		OpenFiles(dlg.FileNames);
	}
}
```

Looking around online it looks like it may have something to do with threading.

One oddity, `dlg.ShowHelp = true;` is needed for it to work.

**Comment by siegfriedpammer** [comment]
I am unable to reproduce this. Could you please provide some more information? Thank you!

**Comment by veccsolutions** [comment]
I'm on Windows 10, 17134.523. The steps to reproduce, fresh download of ILSpy version 4.0.1.4530, extract it, open ilspy.exe, file->open->locked up. Running from source in VS, it hangs on the line I mentioned above, particularly when `dlg.ShowDialog()` is called.

**Comment by christophwille** [comment]
Same here with unable to repro - and given that File/Open is such a basic (and often used) command I don't think it is ILSpy that is acting up. Much more likely that it is that specific machine.
