### ISSUE TITLE
How to migrate this old code to the latest?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1403]
```
       public static HashSet<string> GetAssemblyReferencesEx(this ModuleDefinition module)
        {
            HashSet<string> hs = new HashSet<string>();
            foreach (AssemblyNameReference r in module.AssemblyReferences)
                hs.Add(r.Name);
            foreach (var type in module.GetTypeReferences())
            {
                var t = type;
                while (true)
                {
                    if (t.Scope is AssemblyNameReference)
                        hs.Add(t.Scope.Name);
                    var td = t.Resolve();
                    if (td == null || td.BaseType == null)
                        break;
                    if (t == type)
                        foreach (var i in td.Interfaces)
                            if (i.InterfaceType.Scope is AssemblyNameReference)
                                hs.Add(i.InterfaceType.Scope.Name);
                    t = td.BaseType;
                }
            }
            return hs;
        }
```

I don't know how to get an ITypeDefinition from TypeReferenceHandle, and how to get a type's scope.

By the way, why there're so many way to get base type:
DirectBaseTypes
GetAllBaseTypeDefinitions
GetAllBaseTypes
GetNonInterfaceBaseTypes

What is  the meaning of 'Direct'?
There's only one base type in .net ,why GetNonInterfaceBaseTypes return a collection?

**Comment by siegfriedpammer** [comment]
Sorry, but in the code you posted, what is the purpose of iterating over all type references?

The AssemblyRef table should return all assembly references used in the module. There can be no assembly reference used in the TypeRef table, that is not listed in the AssemblyRef table. This means that the first loop should suffice. At least that's how Microsoft specified the format in ECMA-335.

> What is the meaning of 'Direct'?

This means that the property returns the immediate parent types of the type. For

A : I1, I2
B : A, I3, I4
C : B, I5, I6

and invoked on C this would return B, I5 and I6.

> By the way, why there're so many way to get base type:
DirectBaseTypes
GetAllBaseTypeDefinitions
GetAllBaseTypes
GetNonInterfaceBaseTypes

Because they're useful extension methods:
- GetAllBaseTypes: Traverses the inheritance hierarchy and returns all base types. For the previous example (invoked on C), this would return System.Object, A, I1, I2, B, I3, I4.
- GetAllBaseTypeDefinitions: Same as GetAllBaseTypes, but returns ITypeDefinition instead of IType, that means, it invokes IType.GetDefinition() on all base types.
- GetNonInterfaceBaseTypes: Same as GetAllBaseTypes, but returns base classes only. This means for the previous example it would return System.Object, A and B.

I hope this clears things up a bit!

**Comment by CreateAndInject** [comment]
Is the order determined?
Is 'B' allways the first one invoked on C in these 4 methods?

**Comment by CreateAndInject** [comment]
> Sorry, but in the code you posted, what is the purpose of iterating over all type references?
> 
> The AssemblyRef table should return all assembly references used in the module. There can be no assembly reference used in the TypeRef table, that is not listed in the AssemblyRef table. This means that the first loop should suffice. At least that's how Microsoft specified the format in ECMA-335.
> 
> EDIT: Sorry, I misunderstood your code. You are trying to get all transitive references used by the "main" assembly. I will soon provide an example.


Say this example:
```
    class Program
    {
        static void Main(string[] args)
        {
            DataTable dt = new DataTable();
            Console.WriteLine(dt);
        }
    }
```

Compile it, and view the output in ILSpy, there're only 2 references:
mscorlib, System.Data

But you must add reference 'System.Xml' to compile this code in Viusal Studio

My 'GetAssemblyReferencesEx' can get all references, but I don't know how to migrate to apply the latest ILSpy.

**Comment by CreateAndInject** [comment]
I'm sorry, VS2017 can compile it without 'System.Xml', but VS2010 can not.
What I mean is just you say: get all transitive references used by the "main" assembly

**Comment by siegfriedpammer** [comment]
I came up with a solution to your problem, which does not work exactly the same, but should yield similar enough results. The main problem with emulating your approach is that our type system does not provide the "parent module" for unknown types. @dgrunwald is there a sensible approach to including more metadata for unknown types in the TS?

You could of course duplicate a lot of resolver logic from MetadataModule, but that would be error-prone.

An alternative solution would be using the CreateCecilObjectModel extension method. 

The following code returns all transitive references of an assembly:

```csharp
public void Execute(TextViewContext context)
{
	if (context.SelectedTreeNodes == null)
		return;
	AssemblyTreeNode node = (AssemblyTreeNode)context.SelectedTreeNodes[0];
	var asm = node.LoadedAssembly.GetPEFileOrNull();
	if (asm != null) {
		var compilation = new DecompilerTypeSystem(asm, node.LoadedAssembly.GetAssemblyResolver());
		string output = string.Join(Environment.NewLine,
			compilation.ReferencedModules
				.Select(m => m.AssemblyName)
				.Distinct(StringComparer.OrdinalIgnoreCase)
		);
		MessageBox.Show(output);
	}
}
```

The downside is that it includes references of B, that are not "required" by assembly A.

**Comment by CreateAndInject** [comment]
```
class MyForm : System.Windows.Forms.Form
{
}
```
td.GetAllBaseTypes() (td is MyForm) return 2 types:
MyForm
Form

1. Why contains itself?
2. Why doesn't contain ContainerControl, Control, Component, Object....?

**Comment by CreateAndInject** [comment]
> The following code returns all transitive references of an assembly:
> 
> ```cs
> public void Execute(TextViewContext context)
> {
> 	if (context.SelectedTreeNodes == null)
> 		return;
> 	AssemblyTreeNode node = (AssemblyTreeNode)context.SelectedTreeNodes[0];
> 	var asm = node.LoadedAssembly.GetPEFileOrNull();
> 	if (asm != null) {
> 		var compilation = new DecompilerTypeSystem(asm, node.LoadedAssembly.GetAssemblyResolver());
> 		string output = string.Join(Environment.NewLine,
> 			compilation.ReferencedModules
> 				.Select(m => m.AssemblyName)
> 				.Distinct(StringComparer.OrdinalIgnoreCase)
> 		);
> 		MessageBox.Show(output);
> 	}
> }
> ```
> 
> The downside is that it includes references of B, that are not "required" by assembly A.

your code is just module.AssemblyReferences, not My GetAssemblyReferencesEx

for example:
```
    class Program
    {
        static void Main(string[] args)
        {
            DataTable dt = new DataTable();
            Console.WriteLine(dt);
        }
    }
```
Compile it, and test the build assembly:

your code = module.AssemblyReferences:
mscorlib, System.Data

My GetAssemblyReferencesEx:
mscorlib, System.Data, System, System.Xml

Because 'IListSource' is defined in System.dll, and 'IXmlSerializable' is defined in System.Xml.dll, these 2 are DataTable's base interfaces.

> is there a sensible approach to including more metadata for unknown types in the TS?
This time, assume ILSpy load all needed assemblies.

**Comment by siegfriedpammer** [comment]
This will do what you are looking for. Note that it traverses the whole graph of references and it might return more assemblies than you might expect it to.

```csharp
static HashSet<string> GetTransitiveReferences(LoadedAssembly assembly)
{
	HashSet<string> refs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
	HashSet<string> processedReferences = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
	Queue<PEFile> files = new Queue<PEFile>();
	var resolver = assembly.GetAssemblyResolver();
	files.Enqueue(assembly.GetPEFileOrNull());
	while (files.Count > 0) {
		var file = files.Dequeue();
		if (!processedReferences.Add(file.Name))
			continue;
		foreach (var r in file.AssemblyReferences) {
			refs.Add(r.Name);
			PEFile reference = resolver.Resolve(r);
			if (reference != null)
				files.Enqueue(reference);
		}
	}
	return refs;
}
```

**Comment by CreateAndInject** [comment]
Do you test it? Your code will get 11 assebmlies in my example:
```
    class Program
    {
        static void Main(string[] args)
        {
            DataTable dt = new DataTable();
            Console.WriteLine(dt);
        }
    }
```
But my GetAssemblyReferencesEx: just 4:
mscorlib, System.Data, System, System.Xml

What I need is just how to get all type references of one assembly, and how to resolve type reference to type definition in order to know which assembly defined these types.

**Comment by siegfriedpammer** [comment]
> Do you test it? Your code will get 11 assebmlies in my example:

Yes, I mentioned that in my previous reply.

> What I need is just how to get all type references of one assembly, and how to resolve type reference to type definition in order to know which assembly defined these types.

Then use this:

However: as previously explained, this will not work with references that cannot be found!

```csharp
static HashSet<string> GetTransitiveReferences(LoadedAssembly assembly)
{
	HashSet<string> refs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

	var genericContext = new ICSharpCode.Decompiler.TypeSystem.GenericContext();
	ICompilation c = new SimpleCompilation(assembly.GetPEFileOrNull(), CollectReferencedAssemblies(assembly));

	foreach (var typeRefHandle in c.MainModule.PEFile.Metadata.TypeReferences) {
		var type = ((MetadataModule)c.MainModule).ResolveType(typeRefHandle, genericContext);

		foreach (var baseType in type.GetAllBaseTypeDefinitions()) {
			refs.Add(baseType.ParentModule.AssemblyName);
		}
	}

	return refs;
}

static IEnumerable<PEFile> CollectReferencedAssemblies(LoadedAssembly assembly)
{
	HashSet<string> processedReferences = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
	Queue<PEFile> files = new Queue<PEFile>();
	var resolver = assembly.GetAssemblyResolver();
	files.Enqueue(assembly.GetPEFileOrNull());
	while (files.Count > 0) {
		var file = files.Dequeue();
		if (!processedReferences.Add(file.Name))
			continue;
		foreach (var r in file.AssemblyReferences) {
			PEFile reference = resolver.Resolve(r);
			if (reference != null) {
				files.Enqueue(reference);
				yield return reference;
			}
		}
	}
}
```

**Comment by CreateAndInject** [comment]
It doesn't work also.

call GetAllBaseType on DataTable contains 'IListSource', but it's UnknownType, so GetAllBaseTypeDefinitions doesn't contain it.

IListSource is defined in System.dll, and ILSpy can find this dll, why is 'IListSource' UnknownType?

```
        public static HashSet<string> GetAssemblyReferencesEx(this DecompilerTypeSystem ts)
        {
            var context = new GenericContext();
            var hs = new HashSet<string>();
            foreach (var r in ts.MainModule.PEFile.AssemblyReferences)
                hs.Add(r.Name);
            foreach (var type in ts.MainModule.PEFile.Metadata.TypeReferences)
            {
                var iType = ts.MainModule.ResolveType(type, context);
                foreach (var baseType in iType.GetAllBaseTypeDefinitions())
                    hs.Add(baseType.ParentModule.AssemblyName);
            }
            return hs;
        }
```

**Comment by siegfriedpammer** [comment]
> It doesn't work also.
> call GetAllBaseType on DataTable contains 'IListSource', but it's UnknownType, so GetAllBaseTypeDefinitions doesn't contain it.
> IListSource is defined in System.dll, and ILSpy can find this dll, why is 'IListSource' UnknownType?

The DecompilerTypeSystem does not contain transitive references, that's why you have to use:

```csharp
ICompilation c = new SimpleCompilation(assembly.GetPEFileOrNull(), CollectReferencedAssemblies(assembly));
```

as posted above.

**Comment by CreateAndInject** [comment]
> Note: there are different options to configure the type system. The ILSpy UI is using it essentially in "single-assembly-mode", so it can't resolve across assembly boundaries. You can create a full type system via new DecompilerTypeSystem(...).

I find this in wiki, it says DecompilerTypeSystem is more powerful than SimpleCompilation, so why DecompilerTypeSystem can not do what SimpleCompilation can?

**Comment by siegfriedpammer** [comment]
The DecompilerTypeSystem is used for decompilation and only contains information necessary for the decompiler. DecompilerTypeSystem is a specialized version of SimpleCompilation: if you need "different" special behavior, you should use SimpleCompilation.

For example: the "single-assembly-mode" is achieved by using

```csharp
new SimpleCompilation(
	module.WithOptions(TypeSystemOptions.Default | TypeSystemOptions.Uncached | TypeSystemOptions.KeepModifiers),
	MinimalCorlib.Instance) // pass minimal corlib instead of references
```

> it says DecompilerTypeSystem is more powerful than SimpleCompilation

the wiki does not say that DecompilerTypeSystem is more powerful - DecompilerTypeSystem is more specialized and does resolve references at creation. Resolving the references at creation is indeed the only thing it does "extra". It is a small extension of SimpleCompilation.

**Comment by CreateAndInject** [comment]
When call CollectReferencedAssemblies, ILSpy may load 30+ dlls(even if my program only ref to mscorlib and System.Data)

So I decide to use CreateCecilObjectModel.

By the way, why the results of GetAllBaseTypes contains itself?

**Comment by siegfriedpammer** [comment]
> When call CollectReferencedAssemblies, ILSpy may load 30+ dlls(even if my program only ref to mscorlib and System.Data)

You could use UniversalAssemblyResolver instead of GetAssemblyResolver() so the resolver is no longer connected to the ILSpy UI (the assemblies no longer appear in the assembly list).

> By the way, why the results of GetAllBaseTypes contains itself?

I don't know the reason for this, maybe @dgrunwald remembers the reason.

**Comment by CreateAndInject** [comment]
Thanks!
