### ISSUE TITLE
Sample code to decompile a member is not working

### ISSUE THREAD

**Issue by torman119** [icsharpcode/ILSpy#1411]
The sample code to decompile a single member from the getting started page is not working (https://github.com/icsharpcode/ILSpy/wiki/Getting-Started-With-ICSharpCode.Decompiler)

The proposed code fails:
"ITypeDefinition typeInfo = decompiler.TypeSystem.Compilation.FindType(name).GetDefinition();
                IMemberDefinition cecilProperty = decompiler.TypeSystem.GetCecil(typeInfo.Properties.First()).Resolve();"

My error messages:
decompiler.TypeSystem.Compilation does not exists
decompiler.TypeSystem.GetCecil() does not exists

Is there a different way to decompile a member?

**Comment by siegfriedpammer** [comment]
Sorry! The wiki page did not get updated for the final release of ILSpy 4.0.

It is updated now. If you have further questions, feel free to ask!
