### ISSUE TITLE
Complex from/where contains compiler generated names

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1424]
ILSpy version 4.1.0.4599-alpha1

Please analyze and figure out why ILSpy does not collapse internal compiler constructions like
<>h__xxx

example:
method
private static IEnumerable<ElectronicsFamily> FromDevice()

```
		IEnumerable<ElectronicsFamily> families = from <>h__TransparentIdentifier1 in (from split in splitFamily
				let isOptional = split.EndsWith("*", StringComparison.Ordinal)
				select new
				{
					<>h__TransparentIdentifier0 = <>h__TransparentIdentifier0,
					actualName = (isOptional ? split.Substring(0, split.Length - 1) : split)
				}).Where(<>h__TransparentIdentifier1 =>
			{
				if (criticalOnly)
				{
					if (criticalOnly)
					{
						return !<>h__TransparentIdentifier1.<>h__TransparentIdentifier0.isOptional;
					}
					return false;
				}
				return true;
			})
```

target: https://www.sendspace.com/file/m5uvpw

**Comment by dgrunwald** [comment]
This is an issue with the where condition; it needs to be collapsed into a single expression in order to use a query expression.
The "transparent identifier" is compiler-generated for `let` in query expressions.
