### ISSUE TITLE
No debug symbol

### ISSUE THREAD

**Issue by DSGMBot115** [icsharpcode/ILSpy#1426]
ILSpy version 4.0.0.4518-rc1
Save C# project no debug symbol

**Comment by christophwille** [comment]
You mean when you save an assembly as C# project? Well, all we create is C# files, you'd have to compile that to get a PDB (or use the Generate PDB feature instead).

**Comment by DSGMBot115** [comment]
> You mean when you save an assembly as C# project? Well, all we create is C# files, you'd have to compile that to get a PDB (or use the Generate PDB feature instead).

I save a class as C# files, it has debug symbol

**Comment by christophwille** [comment]
Sorry I don't follow.

**Comment by DSGMBot115** [comment]
> Sorry I don't follow.

when i save an assembly as C# project, method GetDebugInfoOrNull did not use

**Comment by siegfriedpammer** [comment]
See https://github.com/icsharpcode/ILSpy/issues/1328#issuecomment-447651862

**Comment by dgrunwald** [comment]
ILSpy has two features:
 * Decompile + save code as .csproj. You can then recompile this project to generate a new DLL with new debug symbols.
 * Generate .pdb file (with embedded sources) matching the existing DLL.

These are unrelated features; what exactly do you think should ILSpy do differently?
Please be specific about what you are doing and what kind of output you expect. Currently we have no idea which ILSpy feature you are talking about.
