### ISSUE TITLE
Linux Support Status

### ISSUE THREAD

**Issue by Ristovski** [icsharpcode/ILSpy#1431]
What is the status of building ILSpy under Linux? (Not talking about the UI.)

It appears to be using `<LangVersion>7.2</LangVersion>` while Mono supports only `7.1`.

I wanted to update the project https://github.com/andreif/ILSpyMono (which adds the ability to add dll references/dependencies, something that - to my knowledge at least - `ilspycmd` lacks) to the latest version of ILSpy, but this seems to be next to impossible.

There are numerous errors ranging from CRLF encoding issues (which are easy to fix with `dos2unix`) - to presumably missing `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` in the `<Project>` tags across projects. Not to mention how `nuget` seems to lose it's mind every time you change something and requires all the `obj/` directories to be wiped which miraculously fixes the odd errors (it seems to dislike parts using `netstandard2.0` while others use `net462`, no idea why it only happens randomly and the wipe makes it work almost every time.)

Is something similar to the aforementioned project possible under Linux with the latest version of ILSpy?

Will `ilspycmd` ever get the option for specifying references/dependencies (as to be able to fully decompile projects with external deps)?

**Comment by siegfriedpammer** [comment]
I've tried downgrading the decompiler codebase from 7.2 to 7.1, but we're using too many new language features in too many places. Sorry, this is not going to happen.

**Comment by Ristovski** [comment]
@siegfriedpammer How about introducing the ability to specify external references with `ilspycmd`?

**Comment by siegfriedpammer** [comment]
Yes, this is definitely the way to go. Could you explain what this feature should look like? Thank you!

**Comment by Ristovski** [comment]
`ilspycmd` should provide an option for setting the search path for `dlls` to be used as references without decompiling them.

This would help in cases where `ilspycmd` produces `Unknown result type (might be due to invalid IL or missing references)`
