### ISSUE TITLE
How to use your API

### ISSUE THREAD

**Issue by GoddessLuBoYan** [icsharpcode/ILSpy#1434]
I want to use your dlls (such as ICSharpCode.Decompiler.dll)
I create a new VS2013 project, and import the dlls.
There is no compile errors.
However, when I debug, I get an error:
![1](https://user-images.githubusercontent.com/38455509/53564850-e3863c00-3b92-11e9-930d-dae498d60465.png)
namespace "ICSharpCode" not exist class or namespace "Decompiler"

Why? I have imported them, and copy them to my debug folder

![2](https://user-images.githubusercontent.com/38455509/53565095-71fabd80-3b93-11e9-8cca-c479d16b486d.png)

Thanks very much!

**Comment by GoddessLuBoYan** [comment]
Because of some reasons, I can't use VS2017

**Comment by greenozon** [comment]
Thats your main show stopper
2013 can't support latest .net editions which ILSpy requires...

**Comment by GoddessLuBoYan** [comment]
> Thats your main show stopper
> 2013 can't support latest .net editions which ILSpy requires...

oh, that's bad.
Is there any console version?

**Comment by GoddessLuBoYan** [comment]
> > Thats your main show stopper
> > 2013 can't support latest .net editions which ILSpy requires...
> 
> oh, that's bad.
> Is there any console version?

I mean ILspy console exe, I can use exe too.

**Comment by greenozon** [comment]
maybe this could treat the issue?

https://support.microsoft.com/en-us/help/3045566/microsoft-net-framework-4-6-targeting-pack-and-language-packs-for-wind

**Comment by GoddessLuBoYan** [comment]
> maybe this could treat the issue?
> 
> https://support.microsoft.com/en-us/help/3045566/microsoft-net-framework-4-6-targeting-pack-and-language-packs-for-wind

thanks, I'll have a try

**Comment by GoddessLuBoYan** [comment]
> maybe this could treat the issue?
> 
> https://support.microsoft.com/en-us/help/3045566/microsoft-net-framework-4-6-targeting-pack-and-language-packs-for-wind

wow, it works
however, there is an exception:
![3](https://user-images.githubusercontent.com/38455509/53566585-8fca2180-3b97-11e9-90a5-9563ced2b64a.PNG)
can't load "System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f711d50a3a" or one of this uses.  not match.

I have used .NET4.6

**Comment by GoddessLuBoYan** [comment]
May I need .NET4.7?

**Comment by GoddessLuBoYan** [comment]
Oh, I have fount the console exe "ilspycmd". I will close this issue when I install it. Thank you very much

**Comment by GoddessLuBoYan** [comment]
![final](https://user-images.githubusercontent.com/38455509/53567336-ea647d00-3b99-11e9-9f98-2950b135d1cd.PNG)
OHHHHH! I GET IT!!!

**Comment by lextm** [comment]
The project file only targets .NET Standard 2.0,
```
<TargetFramework>netstandard2.0</TargetFramework>
```
so that .NET Framework 4.5.x/4.6.0 projects cannot consume it. Ideally it should target more platforms like,
```
<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
```

**Comment by dgrunwald** [comment]
We just recently moved away from targeting multiple frameworks.
This allowed us to get rid of a whole bunch of workarounds for various MSBuild bugs with multi-targeting.

You need to use at least .NET 4.6.2 to consume the current decompiler versions (ILSpy >=5).
Use the older versions (<=4) of ICSharpCode.Decompiler on NuGet if you need to support .NET 4.5. The NuGet had separate builds of the .dll for the various framework versions; copying the .dll from an ILSpy installation won't give you the .NET 4.5 variant!

**Comment by lextm** [comment]
@dgrunwald Such is acceptable (as most guys should be on 4.6.1 and above), but I could not see any note from ILSpy release notes https://github.com/icsharpcode/ILSpy/releases Maybe the NuGet package should have a separate release notes to highlight such changes.

**Comment by siegfriedpammer** [comment]
> but I could not see any note from ILSpy release notes https://github.com/icsharpcode/ILSpy/releases Maybe the NuGet package should have a separate release notes to highlight such changes.

There is nothing written in the release notes, because ILSpy 5.x is not yet released. I don't know which version of ILSpy @GoddessLuBoYan used to copy the libraries from, but it seems to be a nightly build.
