### ISSUE TITLE
Lambda expressions are not decompiled correctly for C# 2

### ISSUE THREAD

**Issue by adrium** [icsharpcode/ILSpy#1439]
I am using the decompiler to convert code from C# 7.0 to C# 2. Everything went fine except the following:

Given the code:

```cs
using System.Collections.Generic;
namespace Test
{
	public class Searcher
	{
		public string Do(List<string> list)
		{ return list.Find(x => x.Equals("OK")); }
	}
}
```

The decompiler generates the lambda expression as:

```cs
(string x) => x.Equals("OK")
```

However, the resulting code is still a lambda expression which is a feature not available in C# 2. Hence, it can not be compiled as is. The resulting error is:

```
AnonDelegate.dec.cs(16,32): error CS8023: Feature 'lambda expression' is not available in C# 2. Please use language version 3 or greater.
```

The expression needs to be replaced by the following:

```cs
delegate(string x) { return x.Equals("OK"); }
```

**Comment by siegfriedpammer** [comment]
I have added the missing option for this. Please note, however, that lambda syntax will always be used if anonymous types are used. You will have to manually convert anonymous types to named types.
