### ISSUE TITLE
Improve enums

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1441]
Original
```
        private void Form1_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyData == (Keys.Control | Keys.R))
            {
                MessageBox.Show("OK");
            }
        }
```

ILSpy
```
private void Form1_KeyDown(object sender, KeyEventArgs e)
{
	if (e.KeyData == (Keys)131154)
	{
		MessageBox.Show("OK");
	}
}
```

**Comment by dgrunwald** [comment]
We already do this for enums marked as `[Flags]`.
It's more difficult for something like `Keys`, because we don't want to decompose `Keys.R` into individual bits.

**Comment by CreateAndInject** [comment]
There's no problem in Reflector.

**Comment by tamlin-mike** [comment]
@dgrunwald According to documentation the `Keys` enum is marked with `[System.Flags]`.
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys

One could argue this is nuts, since ORing f.ex. `S` and `T` is nonsensical, but it is what it is.

**Comment by siegfriedpammer** [comment]
The Flags-enum transformation does not work in this case because the individual members of the enumeration are overlapping.
