### ISSUE TITLE
languageVersionComboBox.Width is a little small.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1444]
![image](https://user-images.githubusercontent.com/2529999/54016420-cc140800-41bd-11e9-9f24-d5161789dc1c.png)

**Comment by siegfriedpammer** [comment]
This is no longer the case in latest master (5.0.0.4683-preview1).

**Comment by CreateAndInject** [comment]
It's still that when I update to the lastest (2019-4-6)
