### ISSUE TITLE
Assertion on "++" for 64-bit value.

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1447]
https://github.com/icsharpcode/ILSpy/blob/76e641f9606cce27e7c64aa8426eb7ca0f496f69/ICSharpCode.Decompiler/CSharp/ExpressionBuilder.cs#L1336

This will trigger on input
'numeric.compound.add.old(ldobj System.UInt64(ldsflda whatever), ldc.i8 1)'

The fix should be simple enough for me to not need to fork and add a PR. :-)

**Comment by dgrunwald** [comment]
Interesting. The Microsoft compilers generate
```
        [load address]
	IL_0008: dup
	IL_0009: ldobj [mscorlib]System.UInt64 /* 01000012 */
	IL_000e: dup
	IL_000f: stloc.1
	IL_0010: ldc.i4.1
	IL_0011: conv.i8
	IL_0012: add
	IL_0013: stobj [mscorlib]System.UInt64
	IL_0018: ldloc.1
```
for a compound assignment, which doesn't trigger this assertion.

**Comment by tamlin-mike** [comment]
No one has ever accused the Microsoft C# compiler of producing optimized code. :-)

_Sidenote: It's actually stated as a fact by someone high up in the C#/Roslyn toolchain they just don't care about IL quality. They defer it to the JIT and let that handle it. Seems to have become a common pattern: let someone else deal with it._
