### ISSUE TITLE
 (DE) Obfuscation Problems Question

### ISSUE THREAD

**Issue by StreamXL** [icsharpcode/ILSpy#1448]
Is there any other way to clean up the processes and to look at it in the ILSpy?

It looks like another string encryption is active

![1](https://user-images.githubusercontent.com/31142317/54397264-2f1e0700-46b6-11e9-94c8-deae573724cb.png)

Doing clean also does not work weird, get no error message. Everything okay

After cleaning, the file is not usable

de4dot cleaned
Cleaning C:\Test.exe
Renaming all obfuscated symbols
Saving C:\Test-cleaned.exe
![2](https://user-images.githubusercontent.com/31142317/54397539-1f52f280-46b7-11e9-8afa-47d06bcb057d.png)

**Comment by siegfriedpammer** [comment]
I suggest that you report this problem in the de4dot repository. ILSpy intentionally does not support de-obfuscation.
