### ISSUE TITLE
Enumerator count debugging helper problem

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1451]
https://github.com/icsharpcode/ILSpy/blob/d9fba190ce465d8deb9a3c743bf23dff75e2d5f8/ICSharpCode.Decompiler/IL/Instructions/ILInstruction.cs#L366

While debugging I have intermittently been hitting this assert. I'm not 100% sure, but I think it's been a result of hitting a breakpoint inside some code I've been testing, inspecting the result(s) of multiple Child collections, and then continuing.

Last time it happened the count was (IIRC) 4.

Could this be a result of a race, where multiple threads at once try to modify the count, or might it "just" be that the VS debugger hangs on to instances of enumerators even after the quick-watching is done?

Just to make sure ILSpy code is OK, perhaps make that inc/dec atomic?

**Comment by siegfriedpammer** [comment]
> or might it "just" be that the VS debugger hangs on to instances of enumerators even after the quick-watching is done?

From my experience it's exactly that, I think it's nothing to worry about.

The only known bug which triggers this assertion without the debugger being attached is #1391.

**Comment by dgrunwald** [comment]
The decompiler engine is single-threaded, so there's no need for atomics/locking. (decompiling a whole project uses multiple instances of the engine in parallel)

I guess this is a problem with the VS debugger if it doesn't call `enumerator.Dispose()`. I don't think there's anything we can do here without giving up this assertion completely, and it's far too valuable for that.

**Comment by tamlin-mike** [comment]
> (decompiling a whole project uses multiple instances of the engine in parallel)

Aha, that explain why decompilation keeps running even when e.g. an assert has triggered!

> I don't think there's anything we can do here without giving up this assertion completely, and it's far too valuable for that.

Agreed.
