### ISSUE TITLE
resx for IlSpy Eng-Fre (Declaration of intention)

### ISSUE THREAD

**Issue by glachancecmaisonneuve** [icsharpcode/ILSpy#1461]
Would you welcome/accept resx files for IlSpy if it was offered?  I am currently teaching a class and part of the curriculum is on localization/internationalization.  

I don't believe there is much if anything in IlSpy that needs internationalization but with 17 students, we could probably make short work of refactoring the strings currently hard coded into a proper resource file, and then also deliver a French localized version of that resource file.

If it was offered, would you use it?  The students will find it gratifying if it's used, but it wouldn't be a great first dive into participating in an open source project if it's not.

**Comment by dgrunwald** [comment]
We haven't quite decided whether we want internationalization.
There's already PR #1299 for Chinese (which already moves the existing string to a resource file).
I guess a second translation would be a point in favor of merging that.

**Comment by siegfriedpammer** [comment]
#1299 was just merged to master. If you are still interested in providing a french translation, please go ahead.
