### ISSUE TITLE
No FullName from SimpleType in VariableDeclarationStatement

### ISSUE THREAD

**Issue by jtillman** [icsharpcode/ILSpy#1463]
Disclaimer: I'm a little new to ILSpy

Issue: There is no way to get the FullName of the type used in a VariableDeclarationStatement. The SimpleType just contains the Identifier for the Type that is used but there is no set way to know which namespace that this Type Identifier belongs.

My assumption is that this information is already known but probably lost when constructing the SyntaxTree.

**Comment by siegfriedpammer** [comment]
The AST does not contain semantic information, however it is annotated with additional information: Each part of the AST is annotated with `ResolveResult` objects and of course `ILInstruction` objects, (which are a higher level abstraction of the IL). For example a `VariableDeclarationStatement` should have a `ILVariableResolveResult` annotation.

You can use the `GetResolveResult` extension to get the `ResolveResult` instance or in your case `GetILVariable` would look for the `ILVariableResolveResult` and return the `ILVariable` instance, which should provide all the information you need. If something is missing, please feel free to ask!

**Comment by jtillman** [comment]
Got it!... I was focusing on the VariableDeclarationStatement and ignoring the VariableInitializer statement methods. I've verified that using `GetILVariable()` worked perfectly in my case.

@siegfriedpammer Thank you for such a quick and detailed response. Really saved me some time from being stuck!
