### ISSUE TITLE
Defensive copy of readonly structs are not shown

### ISSUE THREAD

**Issue by sonnemaf** [icsharpcode/ILSpy#1465]
Hi,

I'm paying with the following code in which I have a static readonly field of the type PointStruct (which is a struct). If I decompile this code using ILSpy (version 4.0.1.4530) you don't see the defensive copy of the struct in the Main() method.

```
using System;

namespace ConsoleApp1 {
    
    class Program {

        static readonly PointStruct _p = new PointStruct(3, 4);

        static void Main(string[] args) {

            Console.WriteLine(_p.ToString());

            // Allowed but doesn’t do anything, it is executed on an defensive copy !!!
            _p.Swap();

            Console.WriteLine(_p.ToString());
        }
    }

    struct PointStruct {
        public long X;
        public long Y;

        public PointStruct(long x, long y) {
            this.X = x;
            this.Y = y;
        }

        public void Swap() {
            //var oldX = this.X; this.X = this.Y;  this.Y = oldX;
            this = new PointStruct(this.Y, this.X);
        }

        public override string ToString() {
            return $"({X.ToString()},{Y.ToString()})";
        }
    }

}
```

The output of ILSpy is

```
private static void Main(string[] args)
{
	Console.WriteLine(_p.ToString());
	Console.WriteLine(_d.ToString());
	_p.Swap();
	Console.WriteLine(_p.ToString());
}
```

If I try the same in [SharpLab.io](https://sharplab.io/#v2:EYLgHgbALAPgAgBgARwIwG4CwAoHA7AQwFsBTAZwAcCBjEpAYQHs8zGAbEgQQotSQG8cSYUiEi4AJhSoA7AJxiR41BCQAnEgQAmzNgE8kABUYBLPABcAyubUBXauaQB9CkgC8SPCQDuR0xes7BwAKAGYAGiQoAEosXGwlJTRVOCgkAFkCM2C0BABtAF0kAjUAczJo+XjEmukATmCXADoAFUZAs1Lg6NiFBNqlAHpBpE42NkZvEi0kYFtHHXI8QEwCBcZivD1zAAtOyJNHEzIkEjASannppGYNpC0SADMSFhMANzpqRgoDAEI/xQGzgoTUs3gIFG6cQBAzQDWabQ6eC6PTiAwAvgCMdURGQbPZHMYzFY8Q4qjDQkgJkikAANVG1OAUqmlJAATSh/RqjL8RMC+OCzKQYEigr0lUEnMBOyOTRp7iF9MBSGlZCarPlekViSx0PEFNSSFB4O6ZKVSGGrxK1zYWjlHhVsvQyt2qrtzpl7OEDvVHnYtq1AxV8q8vkJARJ5mC3siDppvUlSh1Cb113eajUJnu0mQCJsnRNErNKDkABIAETBfg01rtPNI7po8L8Vk1xHItHRMsBkRYxN9LFAA) I see a defensive copy for each member call.

```
private static void Main(string[] args)
{
    PointStruct p = _p;
    Console.WriteLine(p.ToString());
    p = _p;
    p.Swap();
    p = _p;
    Console.WriteLine(p.ToString());
}
```

When I run this console app you can see that the defensive copy is executed because the Swap() method doesn't swap the X and Y values.

I think this is a bug.

Regards,

Fons Sonnemans

**Comment by dgrunwald** [comment]
The ILSpy output seems to be the same as the original source code.
Why would this be a bug?

**Comment by sonnemaf** [comment]
You are right, it is not a bug. But it is inconsistent with the use of 'in struct parameters' and 'readonly ref locals'.

The Foo() method in the following code takes a DateTime (struct) as an 'in' parameter.

```
using System;

namespace ConsoleApp115 {
    class Program {
        static void Main(string[] args) {
            Foo(DateTime.Today);
        }

        private static void Foo(in DateTime d) {
            Console.WriteLine(d.ToString());
            Console.WriteLine(d.Day);
            Console.WriteLine(d.Year);
        }
    }
}
```

ILSpy generates the following code which includes the 'defensive copy' (dateTime = d)

```
private static void Foo(in DateTime d)
{
	DateTime dateTime = d;
	Console.WriteLine(dateTime.ToString());
	dateTime = d;
	Console.WriteLine(dateTime.Day);
	dateTime = d;
	Console.WriteLine(dateTime.Year);
}
```

The following code has a 'ref readonly local'. 

```
using System;

namespace ConsoleApp115 {
    class Program {
        static void Main(string[] args) {
            var today = DateTime.Today;
            ref readonly DateTime d = ref today;

            Console.WriteLine(d.ToString());
            Console.WriteLine(d.Day);
            Console.WriteLine(d.Year);
        }
    }
}
```

ILSpy generates the following code which includes the 'defensive copy' (dateTime = today)

```
private static void Main(string[] args)
{
	DateTime today = DateTime.Today;
	DateTime dateTime = today;
	Console.WriteLine(dateTime.ToString());
	dateTime = today;
	Console.WriteLine(dateTime.Day);
	dateTime = today;
	Console.WriteLine(dateTime.Year);
}
```

If you show the 'defensive copy' for 'in parameters' and 'ref readonly locals' why not show it for 'readonly struct fields' (like SharpLab.io does).

Regards,

Fons

**Comment by dgrunwald** [comment]
An explicit "defensive copy" is ugly. Also, being unable to use a single statement may hurt some higher-level transforms; for example expression lambdas may turn to statement lambdas, thus making it impossible to apply the query expression transform.
SharpLab.io is intentionally emitting lower-level C# to show "what the IL code actually does"; ILSpy has the goal of getting as close to the original code as possible with reasonable effort.
So we have some logic that detects where C# would introduce implicit defensive copies, and remove the corresponding explicit copies where possible. It looks like this logic wasn't updated for the new C# 7.* features.

**Comment by sonnemaf** [comment]
I understand your decision to remove the defensive copies. I would love an extra option in the Options dialog to get them shown if set.

**Comment by dgrunwald** [comment]
I've fixed the interaction of defensive copies with `in` parameters and/or `readonly struct` in 416425b68112246daab677f862ae661aaee6d56f.
The `ref readonly` case is more tricky; the IL code doesn't store whether a ref-local was `readonly`. While we could infer that in some cases (that would otherwise fail to compile); in your example there's no way to do so.
