### ISSUE TITLE
Commandline option for ILSpy

### ISSUE THREAD

**Issue by brijeshagrawal** [icsharpcode/ILSpy#1469]
I just have to check if the binaries/dlls are obfuscated or not.  I don't want to run ILSpy UI. I want a command line option which on runs generate a report to say if the dll/binary is obfuscated or not.

**Comment by GoddessLuBoYan** [comment]
What you want is in the function main() of the file:
/ICSharpCode.Decompiler.Console/Program.cs

And you can compile it, there is a compile doc in github

**Comment by siegfriedpammer** [comment]
ICSharpCode.Decompiler.Console can be installed as `dotnet tool` using `dotnet tool install -g ilspycmd`. There is no need to compile it yourself.

**Comment by siegfriedpammer** [comment]
This functionality is already provided by `de4dot`, we have no plans to add this to ILSpy.
