### ISSUE TITLE
Tooltip can not find mscorlib.xml doc for zh-CN ENV.

### ISSUE THREAD

**Issue by treert** [icsharpcode/ILSpy#1477]
The doc for zh-CN is in zh-hans，not zh directory.

System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName is not accurate for .net doc directory.

只有中文才有这种问题吧，虽然只要装上英文的文档就好了。

**Comment by maikebing** [comment]
#1510

**Comment by siegfriedpammer** [comment]
@maikebing Is this fixed in the latest version? We cannot test and/or fix this, because we have no Chinese environment and do not understand Chinese.

**Comment by maikebing** [comment]
Yes, it's fixed.  @siegfriedpammer

**Comment by christophwille** [comment]
Thanks for confirming, closing the issue.
