### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by xDShot** [icsharpcode/ILSpy#1478]
I've built it on Linux (I think so...). Now, how do I actually start it???

**Comment by xDShot** [comment]
```
[xdshot@lenovo-pc ILSpy]$ dotnet run
Couldn't find a project to run. Ensure a project exists in /home/xdshot/ILSpy, or pass the path to the project using --project.
```
wtf is this???

**Comment by christophwille** [comment]
You can run https://github.com/icsharpcode/ILSpy/tree/master/ICSharpCode.Decompiler.Console, the main solution won't work on Linux. Alternatively, check out https://github.com/icsharpcode/AvaloniaILSpy/
