### ISSUE TITLE
Exception filtering Instead of 'when (true)' decompile to 'when (1 != 0)'

### ISSUE THREAD

**Issue by bprg** [icsharpcode/ILSpy#1484]
**Code**
```csharp
private static void Main(string[] args)
{
	try
	{
		throw new Exception("Error");
	}
	catch (Exception e) when (true)
	{
		Console.WriteLine(e);
	}
}
```

**Decompile**
```csharp
private static void Main(string[] args)
{
	try
	{
		throw new Exception("Error");
	}
	catch (Exception e) when (1 != 0)
	{
		Console.WriteLine(e);
	}
}
```

**Comment by meirumeiru** [comment]
I can confirm this one... but I also have this one in a "if(true)" ... this compiles to "if(1 == 0)" also now... (this has been inserted by an obfuscator... that's why it's a strange command)...

**Comment by siegfriedpammer** [comment]
See also #811. Usually we want to make the generated C# look similar to the underlying IL. I am not sure, if it's a good idea to aggressively optimize the generated code.

**Comment by siegfriedpammer** [comment]
This is out of the scope of ILSpy, as explained in my previous comment.
