### ISSUE TITLE
Indentation problem when "LINQ Expression Syntax" disabled

### ISSUE THREAD

**Issue by carlreinke** [icsharpcode/ILSpy#1485]
Indentation gets stuck one level too deep sometimes.

![image](https://user-images.githubusercontent.com/11667451/56105537-06c63a00-5efa-11e9-9923-1caedf9f086e.png)

LINQ expression syntax disabled:
![image](https://user-images.githubusercontent.com/11667451/56105768-31fd5900-5efb-11e9-925c-e87f8d01cca1.png)

LINQ expression syntax enabled:
![image](https://user-images.githubusercontent.com/11667451/56105784-4ccfcd80-5efb-11e9-951a-f236f38a4cad.png)

I can provide the .dll if that would help, or you can find the source [here](https://github.com/carlreinke/Hypersonic/blob/c90fb94081f0f5948bdcdec363e00abb566cc661/Hypersonic/Program.cs#L685-L691).

Version: 5.0.0.4730-preview1

**Comment by dgrunwald** [comment]
Indentation is still wrong as of master commit 906f69fd455b83a; for example in `CSharpConversions.GetApplicableConversionOperators()` in the decompiler roundtrip test.

**Comment by siegfriedpammer** [comment]
Fixed in d6144af26d5e862f4099a4c9648b0996e30293a2
