### ISSUE TITLE
"Read By" empty for enum element

### ISSUE THREAD

**Issue by carlreinke** [icsharpcode/ILSpy#1492]
Code view shows a usage of the enum element, but Analyzer doesn't find it.
![image](https://user-images.githubusercontent.com/11667451/56248097-35602400-6064-11e9-9e1b-a05986ea00d0.png)

Version: version 5.0.0.4688-preview1

**Comment by siegfriedpammer** [comment]
IL of the method:

```
.method /* 0600527C */ public hidebysig static 
	class Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SkippedTokensTriviaSyntax SkippedTokensTrivia (
		valuetype [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList`1<class Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken> tokens
	) cil managed 
{
	// Method begins at RVA 0x12cca2
	// Code size 18 (0x12)
	.maxstack 8

	IL_0000: ldc.i4 8563 // <-- this is the enum value
	IL_0005: ldarga.s tokens
	IL_0007: call instance class [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.GreenNode valuetype [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxList`1<class Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken>::get_Node() /* 0A00166D */
	IL_000c: newobj instance void Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SkippedTokensTriviaSyntax::.ctor(valuetype Microsoft.CodeAnalysis.CSharp.SyntaxKind, class [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.GreenNode) /* 06004B7C */
	IL_0011: ret
} // end of method SyntaxFactory::SkippedTokensTrivia
```

The analyzers work on IL level and the `FieldAccessAnalyzer` only looks at `ldfld`, `ldsfld`, `stfld`, `stsfld`, `ldflda` and `ldsflda` instructions. On the IL level there is no reference to the enum.

I doubt we will ever be able to handle this on the IL level as there is no type information.

**Comment by dgrunwald** [comment]
We shouldn't show the `Read By` analyzer for constants/enumerators, as it can never find any usages for those.

**Comment by carlreinke** [comment]
Maybe even disable the "Analyze" menu item for elements that Analyzer can't possibly provide usages of.
