### ISSUE TITLE
"Trim" method could not on new line, in string interpolation

### ISSUE THREAD

**Issue by ahdung** [icsharpcode/ILSpy#1497]
version: 4.0.1.4530

![ID截图20190422114537](https://user-images.githubusercontent.com/12094247/56481945-2eb62e80-64f4-11e9-8453-fb1860bb1346.png)

**Comment by ahdung** [comment]
@siegfriedpammer any comment?

**Comment by siegfriedpammer** [comment]
Thank you for reporting, this is fixed in the [latest CI build (master)](https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy_binaries.zip?branch=master&job=Configuration%3A+Release).

**Comment by ahdung** [comment]
@siegfriedpammer Thank you very much.
