### ISSUE TITLE
NullReferenceException: Open from GAC

### ISSUE THREAD

**Issue by paradoxlost** [icsharpcode/ILSpy#1498]
Receive the following error attempting to open from gac. Does not occur if run as admin. Happens with 4.0 and 4.0.1.
```
---------------------------
Sorry, we crashed
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at ICSharpCode.ILSpy.GacInterop.<GetGacAssemblyFullNames>d__0.MoveNext()

   at System.Linq.Enumerable.<TakeWhileIterator>d__27`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at ICSharpCode.ILSpy.OpenFromGacDialog.FetchGacContents()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()
---------------------------
OK   
---------------------------
```
Fairly fresh Windows 10-64 bit build with Visual Studio 2015 installed.

**Comment by siegfriedpammer** [comment]
This is the same as #1267.

I am not sure how we could debug this. Would you be able to compile ILSpy on your machine and then try to reproduce the problem? Thank you!

**Comment by paradoxlost** [comment]
I was able to debug this a bit, and can confirm the error occurs in the fusion api itself. The following block returns (in my case) 0x80070005 and the assemblyEnum object is also null.

```cs
Fusion.CreateAssemblyEnum(out assemblyEnum, null, null, 2, 0);
```

No binding/loading errors are logged by fusion. I have not been able to identify any particular permissions issue. Changing the code to something similar to this would a least give a more robust response to the issue:

```cs
int err = Fusion.CreateAssemblyEnum(out assemblyEnum, null, null, 2, 0);
if (err != 0) throw new System.Runtime.InteropServices.COMException("Failed to enumerate GAC", err);
// choose your preferred exception types.
```

I will continue to investigate. Maybe I can get more insight into fusion somehow.

**Comment by siegfriedpammer** [comment]
Any progress on finding a solution? Did you try the latest 5.0 preview? Thanks!

**Comment by siegfriedpammer** [comment]
I was able to reproduce this today. Running ILSpy.exe in elevated mode seems to fix the problem. No idea why GAC enumeration suddenly requires administrator privileges.

**Comment by siegfriedpammer** [comment]
The only way around this seems to be implementing GAC enumeration without using the Fusion API. I checked what other decompilers use, it seems they manually enumerate the GAC directories in the file system.

**Comment by paradoxlost** [comment]
In my case it appears to be a weird Office PIA deployment. The actual
files are limited to System & Administrators only.

High Resolution Date & Time:    8/7/2019 12:13:38.1633871 PM
Event Class:    File System
Operation:    CreateFile
Result:    ACCESS DENIED
Path:   
C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Access\15.0.0.0__71E9BCE111E9429C\Microsoft.Office.Interop.Access.dll
TID:    4080
Duration:    0.0000280
Desired Access:    Read Attributes
Disposition:    Open
Options:    Open Reparse Point
Attributes:    n/a
ShareMode:    Read, Write, Delete
AllocationSize:    n/a

**Comment by siegfriedpammer** [comment]
I am no longer able to reproduce this, but I think we should consider switching from the Fusion API to something else. But I don't think this will fix the problem for you, as direct access to the files is prohibited.

**Comment by siegfriedpammer** [comment]
I have just pushed a change that removes the Fusion API usage. We directly enumerate the GAC directories ourselves. For this, we only need LIST permission, which should be available in any case. If there are any other issues, please open a new issue.
