### ISSUE TITLE
LINQ decompilation, missing required cast

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1501]
ILSpy: 5.0.0.0-no-branch-preview1 (663ba0c5)
Output selected: C# 5.0
Compiler used: csc 4.7.3190.0 (chances are any compiler would do)

I stripped the repro down. The original is at
 https://github.com/aaubry/YamlDotNet.git ,

specifically

 https://github.com/aaubry/YamlDotNet/blob/026d707f1cc1f320aa9a3d408b7f9aee17ce9ac6/YamlDotNet/RepresentationModel/YamlNode.cs#L239-L242

```C#
// stripped down repro
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

public abstract class YamlNode
{
    public static implicit operator YamlNode(string value) { return null; }
    public static implicit operator YamlNode(string[] sequence)
    {
        return new YamlSequenceNode(sequence.Select(i => (YamlNode)i));
    }
}

public sealed class YamlSequenceNode : YamlNode, IEnumerable<YamlNode>
{
    public YamlSequenceNode(IEnumerable<YamlNode> children) {}
    public IEnumerator<YamlNode> GetEnumerator() { return null; }
    IEnumerator IEnumerable.GetEnumerator() { return null; }
}
```

The problem is in `op YamlNode(string[])`.

Decompiled this displays
```
public static implicit operator YamlNode(string[] sequence)
{
    return new YamlSequenceNode(from i in (IEnumerable<string>)sequence
            select (i));
}
```

Disregarding the SQL-ish vs. C# syntax (which is impossible to differentiate from IL), the problem is the missing cast for the argument to `YamlSequenceNode` ctor.

There were two more related (possibly the same) problems when trying to decompile + recompile YamlDotNet, which should be obvious to spot I believe.

**Comment by siegfriedpammer** [comment]
```csharp
// YamlNode
using System;
using System.Collections.Generic;
using System.Linq;

public abstract class YamlNode
{
	public static implicit operator YamlNode(string value)
	{
		return null;
	}

	public static implicit operator YamlNode(string[] sequence)
	{
		return new YamlSequenceNode(((IEnumerable<string>)sequence).Select((Func<string, YamlNode>)((string i) => i)));
	}
}

```

is the output with LINQ expressions disabled. I think we would have to extend ExpressionBuilder so that it moves casts from outside the lambda into the lambda. Another idea: do not transform extension methods to LINQ if there are casts around the lambda, however I think we have some code that explicitly removes casts in the IntroduceQueryExpressions transform. This might cause some regressions.

**Comment by siegfriedpammer** [comment]
I just tried something: see https://github.com/icsharpcode/ILSpy/blob/bf72999f365e30f0581c83098deecc9321bc82fc/ICSharpCode.Decompiler/CSharp/CallBuilder.cs#L876-L894

If I remove the check for anonymous types (line 879), the output looks quite nice:

```csharp
// YamlNode
using System.Collections.Generic;
using System.Linq;

public static implicit operator YamlNode(string[] sequence)
{
	return new YamlSequenceNode(((IEnumerable<string>)sequence).Select((string i) => (YamlNode)i));
}
```

With LINQ enabled:

```csharp
// YamlNode
using System.Collections.Generic;
using System.Linq;

public static implicit operator YamlNode(string[] sequence)
{
	return new YamlSequenceNode(from i in (IEnumerable<string>)sequence
		select (YamlNode)i);
}
```

So in addition to fixing the LINQ expressions transform to not transform expressions that have casts tacked to them (for correctness), we could improve the call builder.

Another nice improvement would be to make the LINQ expressions transform less aggressive: we should not introduce LINQ expressions for simple `Select` or `Where` calls.
