### ISSUE TITLE
ILSpy 5.0 Preview 2 Crashing

### ISSUE THREAD

**Issue by furqansafdar** [icsharpcode/ILSpy#1516]
After installing ILSpy 5.0 Preview 2 on Visual Studio 2019 Enterprise, getting below error with title "Sorry we crashed!" when trying to disassembly .net standard 2.0 library.

> Error(s) loading plugin: ILSpy.BamlDecompiler.Plugin
> 
> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 
> File name: 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
> 
> File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
> 
> WRN: Assembly binding logging is turned OFF.
> 
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> 
> Note: There is some performance penalty associated with assembly bind failure logging.
> 
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
>    at Microsoft.VisualStudio.Composition.PartDiscovery.<CreatePartsAsync>d__10.MoveNext()
> 
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
> 
>    at Microsoft.VisualStudio.Composition.PartDiscovery.CreatePartsAsync(IEnumerable`1 assemblies, IProgress`1 progress, CancellationToken cancellationToken)
> 
>    at Microsoft.VisualStudio.Composition.PartDiscovery.CreatePartsAsync(Assembly assembly, CancellationToken cancellationToken)
> 
>    at ICSharpCode.ILSpy.App..ctor()
>

**Comment by trivalik** [comment]
To clarify this, it happens when you enter the menu "Tools" --> "ILSpy".

```
---------------------------
Sorry we crashed!
---------------------------
Error(s) loading plugin: ILSpy.BamlDecompiler.Plugin

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'



WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



   at Microsoft.VisualStudio.Composition.PartDiscovery.<CreatePartsAsync>d__10.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.VisualStudio.Composition.PartDiscovery.CreatePartsAsync(IEnumerable`1 assemblies, IProgress`1 progress, CancellationToken cancellationToken)

   at Microsoft.VisualStudio.Composition.PartDiscovery.CreatePartsAsync(Assembly assembly, CancellationToken cancellationToken)

   at ICSharpCode.ILSpy.App..ctor()





-------------------------------------------------

Error(s) loading plugin: 

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'



WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



   at Microsoft.VisualStudio.Composition.PartDiscovery.<CreatePartsAsync>d__10.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.VisualStudio.Composition.PartDiscovery.CreatePartsAsync(IEnumerable`1 assemblies, IProgress`1 progress, CancellationToken cancellationToken)

   at Microsoft.VisualStudio.Composition.PartDiscovery.CreatePartsAsync(Assembly assembly, CancellationToken cancellationToken)

   at ICSharpCode.ILSpy.App..ctor()
```

**Comment by MrClyfar** [comment]
I am experiencing the same crash message when I select `Tools->ILSpy`

However, if I have ILSpy.exe open in the background, then clicking `Tools->ILSpy` in Visual Studio switches ILSpy.exe into view. I do not see the crash message in this case.

But in Visual Studio, the right-click command `Open Code in ILSpy` does not work for me still. It does nothing at all.

**Comment by christophwille** [comment]
Please give the vsix from here a try: https://ci.appveyor.com/project/icsharpcode/ilspy/build/job/sc4xkqets7ka0y70/artifacts (yes, intentionally the Debug version)

**Comment by infraviolet** [comment]
I have the same issue. I can't launch the exe either, getting the same error message.

**Comment by christophwille** [comment]
@infraviolet @MrClyfar @trivalik @furqansafdar Anyone tried a recent CI build as I pointed out?

**Comment by MrClyfar** [comment]
I downloaded ILSpy 5.0.0.4852-preview2 from the artifacts of the latest build on AppVeyor, and the ILSpy vsix file from the same build (v5.0.0.4852).

When selecting the ILSpy menu item from the Tools menu in Visual Studio, I get the following error...

![image](https://user-images.githubusercontent.com/700064/60762142-2c726380-a051-11e9-9045-a28124324907.png)

I think I'm being a bit silly here, but am I supposed to start ILSpy.exe first before using the Visual Studio addin? There does not look to be a way to configure the addin to know where to look for the .exe file, so it's no wonder it is not working. Apologies if I'm being a bit dumb here lol.

**Comment by christophwille** [comment]
See https://github.com/icsharpcode/ILSpy/pull/1522/files#diff-969eddb6d4efef25c08c59535991b8cdR55 - this PR added a new dependency that is not included in the VSIX build yet.

**Comment by christophwille** [comment]
Verified in VS2019 with latest CI build that the missing DLL issue is solved (again).

**Comment by MrClyfar** [comment]
I installed the latest DEBUG build of the ILSpy addin (v5.0.0.4854) into Visual Stufio 2019, and can confirm that when I now click the ILSpy menu option, the ILSpy application now comes up without a hitch.

That's great :) thanks for fixing this.
