### ISSUE TITLE
file does not contain any managed metadata

### ISSUE THREAD

**Issue by Natt3** [icsharpcode/ILSpy#1521]
Hi,

I am trying to decompile a project that was made in VB and I keep getting an error like this

// PE file does not contain any managed metadata.

Exception Details:
`
ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task``1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
`

any information would be appreciated thanks

**Comment by sgkoishi** [comment]
You can check if following is true:
 * The file is *protected* by a packer
 * The program is in `Visual Basic`, not `Visual Basic .NET`

If so, you cannot decompile it using ILSpy directly.

**Comment by Natt3** [comment]
I believe it is packed but not 100% sure. Using PEiD it shows that there is "Nothing found *" as the packer, also I am pretty sure that this is in VB .Net

**Comment by siegfriedpammer** [comment]
Closing, because it appears to be resolved.

**Comment by Venus24kk** [comment]
Hi siegfriedpammer,

Nice to meet you. I'm going to use ILSply, but I have the same issue as this one. This issue is closed by you, but there is no solution or reference link. Could you please tell me where it is resolved?

Regards,

venus24kk

**Comment by siegfriedpammer** [comment]
There is no general solution to this problem. It always depends on the file/assembly you are trying to open. If you are trying to open an assembly that is not a managed (i.e. .NET) assembly, then there is nothing we can do. ILSpy does not support assemblies that do not contain managed metadata.

**Comment by Venus24kk** [comment]
Could you please check this file if it works on your side? After installing .NET 4.6.2 on Windows 10, I tested it using ILSpy_binaries_5.0.2.5153. However, it shows the same as this one. Could you please check if it works on your side?

[TC.zip](https://github.com/icsharpcode/ILSpy/files/4168705/TC.zip)

**Comment by sgkoishi** [comment]
> 
> 
> Could you please check this file if it works on your side? After installing .NET 4.6.2 on Windows 10, I tested it using ILSpy_binaries_5.0.2.5153. However, it shows the same as this one. Could you please check if it works on your side?
> 
> [TC.zip](https://github.com/icsharpcode/ILSpy/files/4168705/TC.zip)

The program is written in Delphi, which is not .NET and not supported.

**Comment by Venus24kk** [comment]
Thank you.

Someone says I can get dll files from that exe. After that, I can get source using those dll files. Do you think it’s possible?

Regards,

Sent from Mail for Windows 10
