### ISSUE TITLE
How to find some method in mixed mode assembly

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1532]
The question might sound a bit stupid, but are there any ways to do it?

eg - I'm decompiling lots of assemblies, 
at some moment
I've got an assertion and it shows me the fail point

for example
<Module>.std._String_iterator<std::_String_val<std::_Simple_types<char> > >.+=

I really would like to locate that failing assemlby, but search shows me 0 results.
so is it possible to find these kind of methods or for the moment only manual (long lasting) search is possible?

thanks

PS if search is complicated to implement, how about adding failing assembly name/path as a 2nd line in error pane?

![image](https://user-images.githubusercontent.com/765343/59157755-08a31880-8ab9-11e9-9e29-1d1a023e848c.png)

**Comment by dgrunwald** [comment]
For this issue there's an easier solution than changing the search to support unusual member names: we can include the metadata token in the error message.

**Comment by greenozon** [comment]
Great solution!
accepting :)
