### ISSUE TITLE
MSIX: CI Builds Drop Location

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1539]
ToDo from https://github.com/icsharpcode/ILSpy/pull/1522

Needs a location for CI distribution
Needs code signing for CI package

Might tie in to https://github.com/icsharpcode/ILSpy/issues/1525

**Comment by christophwille** [comment]
Out build pipeline is online at https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=1

**Comment by MatthewSteeples** [comment]
Not sure whether this is intentional, but users that are not a member of the organisation can't download build artifacts (can only see build results). This may be a limitation of the platform rather than something that can be configured

**Comment by christophwille** [comment]
The issue exists to first sign the MSIX as part of the CI (without signing it wouldn't install in the first place), and then drop it a standard location so auto-update can work its magic (that wouldn't if we use standard drop location of Azure Pipelines).

**Comment by christophwille** [comment]
The MSIX is "history" as of ILSpy 8. Closing.
