### ISSUE TITLE
MSIX: Store

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1540]
ToDo from https://github.com/icsharpcode/ILSpy/pull/1522

Store needs entry created

Oren suggested automating via Pipelines, but that would require org store account w AAD.

**Comment by onovotny** [comment]
The .NET Foundation has an AAD-backed store account that could be an option for you to use. Open Live Writer is currently published there and I'll likely move NuGet Package Explorer from my account over to it as well.

**Comment by christophwille** [comment]
Then let's link the dotnetfdn issue here too https://github.com/icsharpcode/ILSpy/issues/1525

**Comment by christophwille** [comment]
Name squatting - wanted to reserve "ILSpy" to our newly created store account, but it tells me that the name is not available

**Comment by christophwille** [comment]
The ILSpy app is now registered to us. With 5.0 RC1 we will start submitting the app store version of ILSpy.

**Comment by christophwille** [comment]
First submission has been submitted, closing.

**Comment by MatthewSteeples** [comment]
For those of us too impatient for it to appear in the search results, any chance you can share the direct link?

**Comment by christophwille** [comment]
First, we need to get through certification. Turns out there are a few things that need fixing.

**Comment by MatthewSteeples** [comment]
Ah yes, been there. It's not a fun (nor a quick) process

**Comment by christophwille** [comment]
You can give https://www.microsoft.com/store/apps/9MXFBKFVSQ13 a try.

**Comment by MatthewSteeples** [comment]
Works great. Even picked up my settings from my ad-hoc ILSpy instance. Great job 👍
