### ISSUE TITLE
Error CS0518 - Predefined type 'System.<Boolean|String|Object|..etc>' is not defined or imported

### ISSUE THREAD

**Issue by SharkFourSix** [icsharpcode/ILSpy#1543]
Error CS0518 - Predefined type 'System.<Boolean|String|Object|..etc>' is not defined or imported

I get the above message when I hit recompile after editing a class.

I did some research and it seems it would have to do with the misconfiguration of the runtime assembly reference. I tried adding the relevant mscorlib from all the .NET installations I could find on my machine but I couldn't get the errors to disappear.

Is there somewhere that I could edit the compilation command line and arguments?

--

.NET 4.7.2 / Core 3.0
VS installed 2010 (I think this is unrelated)
OS: Windows 10 Home, Creators Update 1803

**Comment by sgkoishi** [comment]
Try remove following folders and restart your IDE
```
bin
obj
.vs
```

**Comment by siegfriedpammer** [comment]
This issue is not directly related to the decompiler engine, if you have a concrete example were ILSpy generates wrong code or a wrong project file, please open a new issue.
