### ISSUE TITLE
Analyze no longer find some reference like `Dictionary<TKey, TValue>` in another assemblies

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1553]
Tested with 5.0.0.4793-preview2

When open both `mscorlib` and `System.Core` from GAC, and call `analyze` for `System.Collections.Generic.Dictionary<TKey,TValue>`(mscorlib), the result no longer show `System.Linq.Enumerable.ToDictionary()`(System.Core) in `Used By` as it does in 3.x.

It used to be work for ILSpy 3.2, but not for 4 and 5.

**Comment by siegfriedpammer** [comment]
Fixed in fe80e1b767b8cb466afdfdcafbb38dd5a6447a1d
