### ISSUE TITLE
mono struct return temporary variable not inlined

### ISSUE THREAD

**Issue by arbruijn** [icsharpcode/ILSpy#1555]
Mono mcs seems to create a temporary variable when accessing fields in structs returned from calls (e.g. `getStruct().x`). This temporary variable is not inlined with recent ILSpy versions. It used to be inlined with ILSpy 2, but the current `IsGeneratedValueTypeTemporary` check prevents this.

The variable is inlined when I add the following code at the top of `IsGeneratedValueTypeTemporary`, I don't know if that's a proper fix:
```cs
if (loadInst.Parent.OpCode == OpCode.LdFlda)
	return true;
```
For example for the following the class:
```cs
class Structret {
    struct S { public int x; }
    static S getS() { return new S(); }
    void Do(int x) { Do(getS().x); }
}
```
The `Do` method is compiled with mono to:
```
IL_0000: ldarg.0
IL_0001: call valuetype testvar/S testvar::getS()
IL_0006: stloc.0
IL_0007: ldloca.s 0
IL_0009: ldfld int32 testvar/S::x
IL_000e: call instance void testvar::Do(int32)
```
And this is currently decompiled to:
```cs
private void Do(int x)
{
	S s = getS();
	Do(s.x);
}
```

[monostructret.zip](https://github.com/icsharpcode/ILSpy/files/3342874/monostructret.zip)

**Comment by tamlin-mike** [comment]
While that fixes the current scenario, I it could produce incorrect decompilation if the data in slot 0 is used (read) again later in scope.

Probably DFA - even if trivially simple - needs to be used, together with some heuristics to not generate excessively long expressions (in case access would be something like `getS().foo.bar.longname.baz.x`).
I believe this example could be a good starting point, to only inline 1st level of such chains.
