### ISSUE TITLE
System.ArgumentException: given Block is invalid

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1562]
[1.zip](https://github.com/icsharpcode/ILSpy/files/3330670/1.zip)

BaiduCrawerDemo.FrmCheck.method_0

**Comment by CreateAndInject** [comment]
And there's an `assert` in Hudianbao.FrmChargeRecord.method_2

![image](https://user-images.githubusercontent.com/2529999/60770634-c3055a00-a10f-11e9-96e1-0937eea0aefd.png)

**Comment by greenozon** [comment]
set_Kind is very old issue and IMHO critical one

ref: (one of):
https://github.com/icsharpcode/ILSpy/issues/1456
