### ISSUE TITLE
`Unexpected return in MoveNext()` when mixed `using` and more than one `yield break`

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1563]
Tested with 5.0.0.4861-preview3
1. It happened with the below code `Program.M(int)`(compile with roslyn)
```csharp
    class Program : IDisposable
    {
        public static IEnumerable<int> M(int i)
        {
            using (var a = new Program())
            {
                if (i == 2)
                    yield break;

                while (i < 40)
                {
                    if ((i % 2) == 0)
                        yield break;
                    i++;

                    yield return i;
                }
            }
            Console.WriteLine("normal exit");
        }
        void IDisposable.Dispose()
        {
            Console.WriteLine("Dispose");
        }
        public static void Main(string[] args)
        {
            try
            {
                foreach (var cur in M(1))
                {
                    Console.WriteLine(cur);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
}
```
Decode as the below code, which not skip the `normal exit`
```csharp
public static IEnumerable<int> M(int i)
{
	using (new Program())
	{
		if (i != 2)
		{
			while (i < 40)
			{
				if (i % 2 != 0)
				{
					i++;
					yield return i;
					continue;
				}
				goto end_IL_002a;
			}
			goto IL_0083;
		}
		end_IL_002a:;
	}
	/*Error near IL_00b0: Unexpected return in MoveNext()*/;
	IL_0083:
	Console.WriteLine("normal exit");
}
```

-----

2. And by the way, there is another issue. When you looking the raw(CompilerGenerated) method `MoveNext()`, you can see something like the below, and it should be display as `((IDisposable)this).Dispose()` instead
```cs
	} // end .try
	fault
	{
		// System.IDisposable.Dispose();
		IL_00a8: ldarg.0
		IL_00a9: call instance void ConsoleApp7.Program/'<M>d__0'::System.IDisposable.Dispose()
		// }
		IL_00ae: endfinally
	} // end handler
```

**Comment by dgrunwald** [comment]
`((IDisposable)this).Dispose()` isn't correct either; we're dealing with a direct non-virtual call to the method implementing the interface.
If a derived class re-implements the interface, the code variant with the cast would incorrectly call the derived method. Though I guess in this restricted case the class is sealed, so we can use this syntax.

The yield-break error seems to occur whenever there's multiple `yield break` inside a `try-finally` block -- roslyn seems to store the return value `false` in a local variable and then re-uses a single control-flow-block for both yield breaks:
```
		IL_008b:
		<>m__Finally1();
		return result;
```
The decompiler fails to understand that `result` must be `false` here, so it doesn't detect that this is a `yield break`.
