### ISSUE TITLE
wpf applications never build after decompilation

### ISSUE THREAD

**Issue by MostafaNanticock** [icsharpcode/ILSpy#1564]
whenever I have any WPF application decompiled i can never build the result, simply because it contains tons of invalid code inside the XAML files, almost because the namespaces used are not available, i don't know why does this happen, i've tried to write a simple WPF application then decompile it and it did succeed. but whenever i try to decompile a real world WPF application i can never get it to be built.
i think this is why till now ILSpy is unable to Decompile itself & get Built correctly

**Comment by christophwille** [comment]
Quick note on "ILSpy decompiling itself" - that line means "decompiling and then recompiling the decompiler engine" (ICS.Decompiler.dll - atm missing local functions support stops us from achieving that). The WPF frontend is not part of this goal.

**Comment by MostafaNanticock** [comment]
so does this mean that there is no intention to Fix whatever causes the Decompiler to produce errors in it's decompilaton results for WPF Applications?

**Comment by christophwille** [comment]
I did not comment on part at all.

**Comment by MostafaNanticock** [comment]
thank you for your attention, & sorry for the misunderstanding.

**Comment by siegfriedpammer** [comment]
Could you please provide an example binary? Thank you very much!

**Comment by christophwille** [comment]
No feedback, closing. Please open a new issue (with requested details) if you later feel this still to be an issue.
