### ISSUE TITLE
Failed get underlyingType of Enum and stackoverflow in `CSharp.TranslatedExpression.ConvertTo(TypeSystem.IType, CSharp.ExpressionBuilder, bool, bool)` when `__value` is not the first member of Enum

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1569]
The dll is edited with dnspy. Tested with ILSpy 5.0.0.4861-preview3.

Also tested it's ok to compile and run codes with the dll, so the format of the dll should be ok.

Seems it should loop to find first non-static field here.
https://github.com/icsharpcode/ILSpy/blob/v5.0-preview3/ICSharpCode.Decompiler/SRMExtensions.cs#L72

stackoverflow when use C# mode to decode the method
[ClassLibrary1.dll.gz](https://github.com/icsharpcode/ILSpy/files/3379786/ClassLibrary1.dll.gz)

**Comment by siegfriedpammer** [comment]
I cannot reproduce the problem using the provided assembly. Which method should I try to decompile?

**Comment by yyjdelete** [comment]
ClassLibrary1.TestIL.Test()

**Comment by siegfriedpammer** [comment]
Oh, sorry, my bad, was looking at the wrong assembly. Thank you!
