### ISSUE TITLE
decompilation to > null with assignment to field as expression

### ISSUE THREAD

**Issue by arbruijn** [icsharpcode/ILSpy#1571]
ILSpy master 2019-06-19

The following code (where hasBool.Bool is a property)
```cs
return hasBool.Bool = x != null;
```

when compiled with .NET Core 2.2, decompiles to:

```cs
return hasBool.Bool = (x > null);
```

The decompilation generates a `Block` inside an expression and apparently the `> null` to `!= null` transform is not run inside this block.

This seems to be caused by the empty `VisitBlock` method in `ExpressionTransforms`. I've changed this method to `VisitBlockContainer` so children of blocks are still visited. This seems to work, it still passes all tests and the example now decompiles to `(x != null)`.

Source:
```cs
class HasBool {
    public bool Bool { get; set; }
}
class C {
    HasBool hasBool;
    bool CheckNull(object x) {
        return hasBool.Bool = x != null;
    }
}
```

IL code of CheckNull method:
```
IL_0000: nop
IL_0001: ldarg.0
IL_0002: ldfld class HasBool C::hasBool
IL_0007: ldarg.1
IL_0008: ldnull
IL_0009: cgt.un
IL_000b: dup
IL_000c: stloc.0
IL_000d: callvirt instance void HasBool::set_Bool(bool)
IL_0012: nop
IL_0013: ldloc.0
IL_0014: stloc.1
IL_0015: br.s IL_0017
IL_0017: ldloc.1
IL_0018: ret
```

ILAst after inlining, before ExpressionTransformation:
```
leave IL_0000 (Block IL_0013 (CallInlineAssign) {
				callvirt set_B(ldfld bc(ldloc this), stloc I_0(comp.o(ldloc x > ldnull)))
				final: ldloc I_0
			})
```
[testnonnull.zip](https://github.com/icsharpcode/ILSpy/files/3388816/testnonnull.zip)

**Comment by dgrunwald** [comment]
Thank you for the detailed bug report!
