### ISSUE TITLE
Wiki Page listing internal features of DEBUG builds

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1577]
A combination of short description and screenshot per feature that is in a DEBUG build compared to a standard release build.

**Comment by dgrunwald** [comment]
Stuff that needs explanation:
 * ILAst view
    * Show steps
       * Context menu on steps
    * Show CFG (context menu on BlockContainer)
* Debug commands in File menu

**Comment by siegfriedpammer** [comment]
Talking about debug features... should we remove the "Typed IL" view? It's been a long time since I used it the last time. Is it still useful?

**Comment by dgrunwald** [comment]
It's still useful to debug the `ILReader` itself.

**Comment by siegfriedpammer** [comment]
I started describing the features here: https://github.com/icsharpcode/ILSpy/wiki/Additional-Features-in-DEBUG-Builds

**Comment by siegfriedpammer** [comment]
Can this be closed? If not, what is missing?

**Comment by christophwille** [comment]
If nothing's missing definitely close it. But I don't know all DEBUG tricks anyways, so I am a bad judge.
