### ISSUE TITLE
Question on assembly attributes rendering styles

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1578]
I"m curious what is the meaning (if any) of the rendering style used to print type names in below picture
what I noticed:
text:
- regular (1)
- bold  (2)
- red
- bold red  (3)

![image](https://user-images.githubusercontent.com/765343/61183854-094a4400-a64f-11e9-95c1-aa10f4d18b98.png)

**Comment by siegfriedpammer** [comment]
All type keywords (bool, byte, char, string, etc.) are colored red. All other types are colored blue, if the decompiler was able to resolve them.

Bold formatting means, it's a value type, normal means its a reference type/interface or Delegate.

**Comment by greenozon** [comment]
This is good info,
proposing to add it into some kind of help (or tool wiki)


closing.
