### ISSUE TITLE
Question on assembly TypeForwardTo types printing

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1579]
Why some of the types are printed in short form (OK form my point of view)
and some are using full type names?

eg:
short: (OK?!)
[assembly: TypeForwardedTo(typeof(ADVF))]

long - same namespace as above one - 
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.ComTypes.BINDPTR))]

![image](https://user-images.githubusercontent.com/765343/61183894-a4431e00-a64f-11e9-8951-a7992699ebb4.png)

also there is a using above all these attributes:

using System.Runtime.InteropServices.ComTypes;

**Comment by siegfriedpammer** [comment]
The name `BINDPTR` exists in two namespaces `System.Runtime.InteropServices` and `System.Runtime.InteropServices.ComTypes`, since both are imported at the top, we have to use fully-qualified names to reference the correct type.

**Comment by greenozon** [comment]
yeah, cool
by bad, all is clear & legal then. :)
