### ISSUE TITLE
Superflous local ref (invalid code) generated when using indexer

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1580]
```
struct V3 { public int this[int idx] { get { return 0; } set {} } }
class Foo { V3 m_v = new V3(); void Bar (int i) { m_v[i] *= 2; } }
```
Generates
```
private void Bar(int i)
{
  ref V3 v = ref m_v;
  v[i] *= 2;
}
```
1. This is the exact code generated no matter what language level is selected. That is in itself an error.

2. Probably a pattern matching needs to be added to see that `var get/OP val/set` => `var OP= val;`.

That transform could hopefully also fix the problems with collection indexing where ilspy currently can generate something like:
```
List<int> l1; int i; // actual collection and index
int index;
List<int> l2 = l1;
l1[index = i] = l2[index] * 2;
```
where the actual intended code would be `l1[i] *= 2;`
(could be that the collection actually needs to be e.g. Dictionary, and/or contain more complex types, such as `V3` from the sample above, and a field of that type needs to be modified).

**Comment by siegfriedpammer** [comment]
Ad 1. see https://github.com/icsharpcode/ILSpy/issues/1292#issuecomment-477383331:

> We can't magically make ref locals disappear, just like we can't magically erase generics just because you might select C# 1.0.
