### ISSUE TITLE
ArgumentException "Value does not fall within the expected range" when Searching in ILSpy

### ISSUE THREAD

**Issue by alexand312z** [icsharpcode/ILSpy#1581]
I face the following exception while searching in ILSpy.
![image](https://user-images.githubusercontent.com/25646575/61198091-e3827500-a70a-11e9-89b4-eb90f94e500b.png)

Could anyone please let me know how if this is something a user can fix? or if ILSpy developer has fixed this already?

I am using ILSpy version 2.4.0.1963.

Thanks & regards,
Alex

**Comment by siegfriedpammer** [comment]
Please grab a newer release from here: https://github.com/icsharpcode/ILSpy/releases

Version 2.4 was released more than 3 years ago and is no longer supported.
