### ISSUE TITLE
Is IL decompiled code easier to read than source code? Now VS2017 comes with the anti-compiler is it better to see decompiling better than source code?

### ISSUE THREAD

**Issue by gallop1** [icsharpcode/ILSpy#1591]
请问IL反编译的代码比源代码更容易阅读吗？现在VS2017自带了反编译器是否看反编译比源代码更好？
Is IL decompiled code easier to read than source code? Now VS2017 comes with the anti-compiler is it better to see decompiling better than source code?

**Comment by christophwille** [comment]
Could you please post in English? Otherwise we'll have to close this issue.

**Comment by maikebing** [comment]
@gallop1  VS2017 只是调试的时候可以看到源码， 如果源码服务器或者能找到的话 。  至于是否容易阅读， 只要对方不混淆， 还是非常容易阅读的， ILSpy 非常棒。

**Comment by maikebing** [comment]
@gallop1  我认为你只需要反编译一个你自己写的源码对比一下就知道是否更容易阅读了。 这要看情况。

**Comment by yinyue200** [comment]
I think it's better to close this issue, this is a very subjective question, not a real "issue" 😂

**Comment by gallop1** [comment]
Is IL decompiled code easier to read than source code? Now VS2017 comes with the anti-compiler is it better to see decompiling better than source code?@maikebing You are wrong, now VS2017 according to F12 can decompile the source code, instead of debugging time can see the source code, I do not know how you debugging time can see the source code, VS will just go to the source server download will not see.

**Comment by siegfriedpammer** [comment]
As @yinyue200 already pointed out, this seems to be largely opinion-based. There is no concrete problem or area for improvement provided, so I am closing this.
