### ISSUE TITLE
switch statement issue

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1602]
ILSpy version 5.0.0.4970-preview3

method:  GetAnnotationDrawingForKeyScanCode

it is not properly decompiled to swtich-case but is using PrivateImplementationDetails ...

```
	string description = keyScanCode.Description;
	if (description != null)
	{
		switch (<PrivateImplementationDetails>.ComputeStringHash(description))
		{
		case 1789179269u:
..............
```

target from #1601

**Comment by siegfriedpammer** [comment]
The `SwitchOnStringTransform` fails probably because `SwitchDetection` moves too much code into the switch:

```csharp
case 2166136261u:
	if (description != null && description.Length == 0 && !gamepadAnnotationMode)
	{
		drawing = ((!(keyScanCode.FriendlyName == "Do not inherit"))
			? (Application.Current.TryFindResource("UriKeyScanCodeEmpty") as Drawing)
			: (Application.Current.TryFindResource("UriKeyScanCodeDoNotInherit") as Drawing));
	}
	break;
```

Does not match the usual C# switch on string pattern.

**Comment by greenozon** [comment]
I've check other decompilers...
looks like only JetBrains dotPeek managed the best this puzzle - 

![image](https://user-images.githubusercontent.com/765343/63223231-24165800-c1bb-11e9-925c-453485498173.png)


the rest are either showin as ILSPy or just if/else/if...

**Comment by dgrunwald** [comment]
The usual C# switch on string has an `if (string.op_Equality(switchVar, "StringLiteral"))` call to guard against hash collisions.
It looks like for empty strings, the C# compiler emits `description != null && description.Length == 0` instead of the equality check.
