### ISSUE TITLE
async related issue

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1604]
Something is not OK with async decompilation (this is from file saved to disk!)
the decompiled text in ILSpy is different, showing < & > symbols, but internal var still present.

please ref to the method

```
		[AsyncStateMachine(typeof(_003CFillSingleConfig_003Ed__72))]
		public Task FillSingleConfig(string configSourcePath)
		{
			AsyncTaskMethodBuilder asyncTaskMethodBuilder = AsyncTaskMethodBuilder.Create();
			int num = -1;
			AsyncTaskMethodBuilder asyncTaskMethodBuilder2 = asyncTaskMethodBuilder;
			_003CFillSingleConfig_003Ed__72 stateMachine = default(_003CFillSingleConfig_003Ed__72);
			asyncTaskMethodBuilder2.Start(ref stateMachine);
			return asyncTaskMethodBuilder.Task;
		}
```
from  #1601 

There is 2nd very similar case in the same assembly in another method
use "_003C" to locate through decompiled items

**Comment by dgrunwald** [comment]
Looks like these are `async` methods without any `await`.
The C# compiler seems to have optimized out the `state` field accesses since the state machine is trivial (just a single state), which confuses the AsyncAwaitDecompiler, which expects a normal state machine.

**Comment by greenozon** [comment]
OK
taking into account that this specific trivial compiler case is analyzed and understood, any ideas how to improve current code... :)
