### ISSUE TITLE
RFC: Switch to Pre-Release Builds of AvalonEdit 6

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1606]
See  https://github.com/icsharpcode/ILSpy/commit/98406c64de16935e32691bf5c884b6d5a7bcd532

ILSpy should be a consumer of AE builds to verify that it still meets our needs / API compat. v6 is only cleanup, so this not only should be safe but also is sort of a precondition for releasing AE6.

@dgrunwald @siegfriedpammer

**Comment by siegfriedpammer** [comment]
I don't see any problems with this.
