### ISSUE TITLE
Azure Pipelines: Build Artefacts Download Not Possible

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1613]
Eg https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=100 - clicking on the blue "Artifacts" button forces a login (best to test in Incognito tab). Contrasting with https://dev.azure.com/FirebirdClient/CI/_build/results?buildId=1047, there a download is possible. Q: what's the difference?

**Comment by christophwille** [comment]
@onovotny Do you happen to have a quick insight into this one?

**Comment by onovotny** [comment]
That looks like a bug...I'll raise it with the Pipelines team.

**Comment by owenhuynMSFT** [comment]
We just fixed it and we're in the process of rolling it out.

**Comment by christophwille** [comment]
It seems to have propagated to our environment - downloads for eg https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build/results?buildId=140 are working now. Thanks!

**Comment by owenhuynMSFT** [comment]
Thanks for closing @christophwille 😊
