### ISSUE TITLE
Missing cast when target type not resolved

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#1614]
[test.zip](https://github.com/icsharpcode/ILSpy/files/3468876/test.zip)

Result
```csharp
private C1 Foo()
{
    //IL_0006: Unknown result type (might be due to invalid IL or missing references)
    //IL_000c: Expected O, but got Unknown
    return new object();
}
```

Expected: `return (C1) new object();`

**Comment by siegfriedpammer** [comment]
leave IL_0000 (conv unknown->none <invalid>(castclass C1(newobj Object..ctor())))

looks like the `castclass` get's removed in the ExpressionBuilder.

**Comment by siegfriedpammer** [comment]
https://github.com/icsharpcode/ILSpy/blob/84aaaeb84e9324aceec30325162ab6d7bdeab343/ICSharpCode.Decompiler/CSharp/TranslatedExpression.cs#L226-L228

This seems to be the problem...

**Comment by dgrunwald** [comment]
That was meant to handle all the casts from the implicit `ConvertTo()` calls -- there were a bunch of redundant and invalid casts without it.

An explicit `castclass` should maybe use a different code path, since it's something different than an implicit IL conversion.
