### ISSUE TITLE
Resources not decompiled.

### ISSUE THREAD

**Issue by CyberFoxHax** [icsharpcode/ILSpy#1626]
This is probably not a bug in ILSpy but perhaps the application i'm tinkering with.

When i opened the resources tab 2 files without an extension named
{5afba4e7-4cbd-48f4-ae87-5cb4a100aac0}
{22a11d39-8946-4a47-958b-a3b1fb426f2d}

Some of the binary for one:
![image](https://user-images.githubusercontent.com/7734690/62765362-90f66780-bac2-11e9-82d3-12d66a30d112.png)

Note: both files starts with:
`7B 7A 7D 02 "{z}."`

Any idea what's going on?

**Comment by siegfriedpammer** [comment]
It is perfectly valid to store arbitrary binary streams as resources in executable files. It is up to the code loading/using the resource to interpret the data. I doubt, we will be able to help you with this.

In any case, if you want us to take a look, once we have time, please always provide the binary. Thank you!

**Comment by CyberFoxHax** [comment]
The exe is not under any license. The author has disappeared along with the source.
ILSpy gives has restored the majority of the C# with the exception of all the resources and XAML.

[PCSX2Bonus.zip](https://github.com/icsharpcode/ILSpy/files/3489914/PCSX2Bonus.zip)

**Comment by siegfriedpammer** [comment]
This assembly was obfuscated with SmartAssembly. You could easily decode the resources, if you take a look at the `SmartAssembly` namespaces. ILSpy can't and won't do this automatically, because we do not provide deobfuscation support.

Closing this, because we do not provide any special support for obfuscated code. Sorry.

**Comment by CyberFoxHax** [comment]
You did plenty already. Thank you!
