### ISSUE TITLE
Assembly could not be loaded

### ISSUE THREAD

**Issue by giggioman00** [icsharpcode/ILSpy#1637]
```
// C:\***\***.exe
// PE file does not contain any managed metadata.

ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
   in ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
   in ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   in System.Threading.Tasks.Task`1.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()
```

what can I do? I get the warning in the title, and the premius quote is the detailed errors

**Comment by siegfriedpammer** [comment]
Seems like this assembly was not created using a compiler for managed programming languages (C#, F#, VB.NET, etc.) ILSpy cannot read unmanaged binaries. You will have to use a decompiler/diassembler for native code instead.

Idea: we could display more information from the PE Header(s) to make it easier to differentiate corrupted managed assemblies from pure native binaries.

**Comment by Techbrunch** [comment]
I ran into a similar issue today when trying to decompile a Xamarin app and someone actually solved it.

You can run a smally [python script](https://github.com/x41sec/tools/blob/master/Mobile/Xamarin/Xamarin_XALZ_decompress.py) to decompress the DLL.

Source: [Decompressing Xamarin DLLs](https://www.x41-dsec.de/security/news/working/research/2020/09/22/xamarin-dll-decompression/)

**Comment by AgentSamad** [comment]
i have extracted apk but do not find assembly files , only meta data file but when i drag and drop that meta deta into llspy it throws this error 
![image](https://user-images.githubusercontent.com/73158987/178674571-f46199df-919c-4674-ba4f-2c6b243aa3ad.png)
