### ISSUE TITLE
Mockup: Ribbon UI (User Feedback Requested!)

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1639]
This is a mockup. This is not planned to be built. This is intended only to gather feedback. Really.

**Motivation** Most decompiler UIs are some sort of derivative of the original Reflector. Ours hasn't changed in a long time, and the menu + toolbar are mostly duplicating access to features. This mockup intends to show "What if ILSpy looked like WinDbg" - using a ribbon instead of menus/toolbars.

**Feedback I'd like to gather** Mostly two things - do developers think that ribbons in "their" applications are sort of "demeaning" (ie devs feels that ribbons are only for office workers? even if they themselves use Windows Explorer?) Secondly, and most importantly, would it take away too much screen real estate compared to the status quo?

In order to help guessing at the second question here is a comparative screenshot of how much we'd loose (red line showing where we'd end up in lines lost in a text editor):

![screencomparison_dotpeek_windbg](https://user-images.githubusercontent.com/344208/63003450-716f8e00-be78-11e9-8dfb-8ff46f0f2af1.png)

**Mockup** A couple of notes beforehand - it shows only the ribbon part, not the window chrome (and thus not backstage nor quick access toolbar), and only for Home. It is a mix of existing menu & toolbar plus a few options from Settings in easier access than before. Navigation (back/forward) isn't fleshed out, could be solved entirely differently (I had a few variants).

Without further ado, here is the mockup:

![ilspy_ribbon_mockup](https://user-images.githubusercontent.com/344208/63003787-40dc2400-be79-11e9-8618-e5d17f84296e.png)

Please add your comments, and yes, "If you build this, I'll never again use ILSpy" **is** a perfectly valid feedback item. After all, it is a quick and dirty mockup intended to generate feedback.

Also very welcome is feedback along the línes "Instead of wasting time on that contraption, do X instead". No feelings will be hurt.

**Comment by MihaMarkic** [comment]
Nah, you don't have that much menu items and it'd be a waste of vertical space.

**Comment by Mrks83** [comment]
I agree with @MihaMarkic, there aren't that many items and you barely need one of the options. But that's exactly why I find a more descriptive ribbon bar useful. Right now, as a occasional user, I have to hover all the icons to understand their meanings. A collapsible/pin-able ribbon bar would be more expressive and does not take away vertical space (in fact we could save some).

**Comment by greenozon** [comment]
I like the new design
if that would be a real office-like toolbar, it should have then a nice small "collapser" - for those who fight for each sq. pixel :)

eg:

![image](https://user-images.githubusercontent.com/765343/63050878-c6e18480-bee4-11e9-8927-ae56a4cfd879.png)

**Comment by christophwille** [comment]
Yes, definitely a collpaser. And by putting Back, Forward, Open and Search in the top Quick Access Bar the most-used commands would be immediately accessible anyways.

**Comment by jogibear9988** [comment]
I think a better feature would be to Open multiple CodeWindows, maybe by using AvalonDock

**Comment by siegfriedpammer** [comment]
@jogibear9988 That's something we're evaluating as well, but not in the scope of this issue.

**Comment by christophwille** [comment]
Feedback gathered, closing.
