### ISSUE TITLE
Catch-when block fails to decompile when catching a type parameter

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1643]
Tested with 5.0.0.5049-preview4

https://www.nuget.org/packages/System.Reactive/4.1.6
Try with `System.Reactive.Concurrency.CatchScheduler<TException>.Wrap<>(...)`
or
`System.Reactive.Concurrency.CatchScheduler<TException>.CatchSchedulerLongRunning.ScheduleLongRunning<>(...)`
https://github.com/dotnet/reactive/blob/rxnet-v4.1.6/Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs#L87

**Comment by siegfriedpammer** [comment]
In both cases it seems like aggressive inlining fails:

```
.try BlockContainer {
	Block IL_0000 (incoming: 1) {
		callvirt Invoke(ldfld Item2(ldloca tuple), ldfld Item3(ldloca tuple), ldloc cancel)
		leave IL_0000 (nop)
	}

} catch val : 2A0004B7 Index=0 Owner=020001B4 System.Reactive.Concurrency.CatchScheduler`1 when (BlockContainer {
	Block IL_0014 (incoming: 1) {
		stloc arg(unbox.any `0(ldloc val)) // <---  not inlined
		leave IL_0014 (comp.i4.unsigned(callvirt Invoke(ldfld _handler(ldfld Item1(ldloca tuple)), ldloc arg) != ldc.i4 0))
	}

}) BlockContainer {
	Block IL_003c (incoming: 1) {
		leave IL_003c (nop)
	}

}
```

**Comment by dgrunwald** [comment]
Inlining isn't possible there; the `unbox.any` and the `ldfld` might both throw exceptions, so we can't reorder them.
But I think the `unbox.any` here might be part of the `catch (T)`, not of the `when` expression.
There's a transform that eliminates the `isinst` typecheck in `when` blocks, I guess that transform does not correctly handle generic exceptions?

**Comment by siegfriedpammer** [comment]
This is the pattern we currently match:

```
catch ex : TException when (...) BlockContainer {
	Block entryPoint (incoming: 1) {
		stloc v(ldloc ex)
		...
	}
}
=>
catch v : TException when (...) BlockContainer {
	Block entryPoint (incoming: 1) {
		...
	}
}
```

It essentially moves the variable that is used in the first store instruction to the exception handler. This is possible, if the variable has a local slot.

Now there are two problems with the method reported:

1) We do not yet support the following pattern:

```
catch ex : TException when (...) BlockContainer {
	Block entryPoint (incoming: 1) {
		stloc v(unbox.any TException(ldloc ex))
		...
	}
}
=>
catch v : TException when (...) BlockContainer {
	Block entryPoint (incoming: 1) {
		...
	}
}
```

This is easily fixed by unwrapping the `unbox.any` and checking if the types match.

2) In the following case (and the method reported), however, optimized Roslyn decides to use a stack slot instead of the local slot and the code cannot be transformed, because we cannot turn a stack slot into an exception local:

```csharp
public void GenericException<TException>(int input) where TException : Exception
{
	try {
		Console.WriteLine(input);
	} catch (TException val) {
		Console.WriteLine(val.Message);
		throw;
	}
}
```

Note: It is not necessary to create a special case for `catch-when`: It uses the same patterns.

**Comment by dgrunwald** [comment]
I'm pretty sure we detect more complex patterns than that for the `when` clause.
I thought the type-check was using an explicit `isinst` instruction if a `when` clause is present?

**Comment by siegfriedpammer** [comment]
Yes, the `when` clause starts with an `isinst` followed by a branch. But regardless whether there is a `when` clause present, if the exception type is a generic parameter, accessing the exception variable for first time emits an `unbox.any T` instruction.

Example without a `when` clause:
```csharp
public void GenericException<TException>(int input) where TException : Exception
{
	try {
		Console.WriteLine(input);
	} catch (TException val) {
		Console.WriteLine(val.Message);
		throw;
	}
}
```

ILAst before the `when` clause transform:

```
.try BlockContainer {
	Block IL_0001 (incoming: 1) {
		call WriteLine(ldloc input)
		leave IL_0000 (nop)
	}

} catch E_12 : 2A000001 Index=0 Owner=06000007 ICSharpCode.Decompiler.Tests.TestCases.Pretty.ExceptionHandling.GenericException when (ldc.i4 1) BlockContainer {
	Block IL_000c (incoming: 1) {
		stloc V_0(unbox.any ``0(ldloc E_12))
		call WriteLine(constrained[``0].callvirt get_Message(ldloca V_0))
		rethrow
	}

}
```

Example with a `when` clause:
```csharp
public void GenericExceptionWithCondition<TException>(int input) where TException : Exception
{
	try {
		Console.WriteLine(input);
	} catch (TException val) when (val.Message.Contains("Test")) {
		Console.WriteLine(val.Message);
		throw;
	}
}
```

ILAst before the `when` clause transform:

```

.try BlockContainer {
	Block IL_0001 (incoming: 1) {
		call WriteLine(ldloc input)
		leave IL_0000 (nop)
	}

} catch E_58 : 0200003D System.Object when (BlockContainer {
	Block IL_000c (incoming: 1) {
		stloc S_1(isinst ``0(ldloc E_58))
		if (comp.o(ldloc S_1 != ldnull)) br IL_0018
		br IL_0014
	}

	Block IL_0014 (incoming: 1) {
		stloc S_3(ldc.i4 0)
		br IL_0038
	}

	Block IL_0018 (incoming: 1) {
		stloc V_0(unbox.any ``0(ldloc S_1))
		stloc S_3(comp.i4.unsigned(callvirt Contains(callvirt get_Message(box ``0(ldloc V_0)), ldstr "Test") > ldc.i4 0))
		br IL_0038
	}

	Block IL_0038 (incoming: 2) {
		leave IL_000c (ldloc S_3)
	}

}) BlockContainer {
	Block IL_003a (incoming: 1) {
		call WriteLine(callvirt get_Message(box ``0(ldloc V_0)))
		rethrow
	}

}
```

So, you can see, this has nothing to do with the `when ` clause. It's the same pattern, if there is no `when` clause.
