### ISSUE TITLE
Wrong Decompilation of Protected Event Access

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/ILSpy#1645]
I've this Code ILSpy creates:

     internal class InstanceSimpleXxx : Xxx
     {
          	public sealed override event EventHandler<EventArgs> XxxxChanged
		{
			add
			{
				BlaBla.Changed += ((Xxx)this).OnXxxGroupChanged;
			}
		}
		protected sealed override void OnXxxGroupChanged(object sender, EventArgs e)
		{
		}
     }

problem is the cast to Xxx of this, cause the Method is in the derived class itself.

So during compile you get an error: 

Auf den geschützten Member "Xxx.OnXxxGroupChanged(object, EventArgs)" kann nicht über einen Qualifizierer vom Typ "Xxx" zugegriffen werden. Der Qualifizierer muss vom Typ "InstanceSimpleXxx" (oder von ihm abgeleitet) sein.

**Comment by jogibear9988** [comment]
The cast could removed completely

**Comment by siegfriedpammer** [comment]
Can you provide either a stripped down example of this problem, or the assembly? Thank you very much!

**Comment by jogibear9988** [comment]
I can provide the Assembly, but not in public here.

**Comment by jogibear9988** [comment]
@siegfriedpammer you got it per mail

**Comment by jogibear9988** [comment]
I could not deliver the dll to your email account, gets rejected. even if the dll is zipped

**Comment by siegfriedpammer** [comment]
Please rename the zip to docx, then it should work. (At least I hope. Haven't emailed binaries in a long time using gmail.)

**Comment by jogibear9988** [comment]
done

**Comment by jogibear9988** [comment]
does not work

**Comment by siegfriedpammer** [comment]
Do you still use Skype?

**Comment by siegfriedpammer** [comment]
Closing, because this is already fixed in the latest nightly build for master.
