### ISSUE TITLE
Copying text from the code-area seems to be always done twice

### ISSUE THREAD

**Issue by donid** [icsharpcode/ILSpy#1650]
I am using a clipboard monitor that can compare the latest two text clips from the clipboard and when I use it to compare text that I have copied from the (yellow) code/text area in ILSpy, the texts are always the same. So, I did further investigations and found that ILSpy seems to put the same content in the clipboard twice (within fractions of a second) when copying code. I am using the lastest commit from master-branch.

**Comment by siegfriedpammer** [comment]
I cannot reproduce this. Could you tell us, which tool you used? I used the Windows 10 built-in Clipboard History and an open-source tool called "Clipboard Monitor". Both of them did not show this behavior.

@dgrunwald should we move this to the AvalonEdit repository?

**Comment by donid** [comment]
Windows Clipboard History cannot be used to test this, since it filters duplicates (I did a quick test).
My clipboard tool is homegrown and rather large, but I could reproduce the problem with this code:
https://stackoverflow.com/a/11901709
Just create an empty WinForms project (.NetFX 4.7.2) and modify it like this and add the code from SO:

	ClipboardNotification _cn = new ClipboardNotification();
	public Form1()
	{
		InitializeComponent();
		ClipboardNotification.ClipboardUpdate += ClipboardNotification_ClipboardUpdate;
	}
	private void ClipboardNotification_ClipboardUpdate(object sender, EventArgs e)
	{
		Trace.WriteLine(DateTime.Now);
	}


BTW: The problem also happens, when you execute "Copy FQ Name" in the tree!

**Comment by donid** [comment]
Oops, sorry I accidentally clicked the "Close" button on this issue...

**Comment by christophwille** [comment]
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/TreeNodes/CopyFullyQualifiedNameContextMenuEntry.cs#L24

This is bog-standard in-framework Clipboard. And the Execute method is called only once (for good measure I just tried it with a breakpoint). There is nothing strange happening on our end.

**Comment by siegfriedpammer** [comment]
Have you tried your homegrown clipboard history app with a simple WPF App that copies something to the clipboard?

**Comment by donid** [comment]
@siegfriedpammer  a few minutes ago I had the idea with the simple WPF App: Same Problem
Then I tried a simple WinForms App: Same Problem
(I am testing with the monitoring code provided above, not my homegrown code)
Now I had the Idea that it might be related to .Net FX 4.8 (recently I had another strange problem which was caused by 4.8)
I will post back when I have more test results.

**Comment by donid** [comment]
Final findings:
The problem is not .NetFX 4.8 related, it happens in older Frameworks, too.
But it does not occur, when you copy text from a non-.Net application!
I am pretty sure that Clipboard.SetText did not always produce two events for
AddClipboardFormatListener, but I have no idea when/why that changed.

Anyway, since this is not directy related to ILSpy I'll close this issue.

**Comment by siegfriedpammer** [comment]
if a simple WPF app and/or WinForms app show the same behavior, I think this is by design. You could try raising the issue with Microsoft at https://github.com/dotnet/wpf or https://github.com/dotnet/winforms.

I doubt, we will be able to change this behavior from within ILSpy, also I don't think it is much of a problem, because setting the clipboard doesn't usually take too long, so doing it twice in a row is not an issue...
