### ISSUE TITLE
Post decrement problem

### ISSUE THREAD

**Issue by lambertlb** [icsharpcode/ILSpy#1656]
I found this issue when running the tests from my translated unit test. This was a very large method so i stripped it down to just contain the failure. The point of the test is to test double operators on every valid .Net primitive type.

Original code:
```c#
		private	void	DoubleOperators()
		{
			double	primary = 'B';
			CxAssert((++primary) == 'C');
			CxAssert((--primary) == 'B');
			CxAssert((primary++) == 'B');
			CxAssert((primary--) == 'C');
		}
```

Translated code:
```c#
		private void DoubleOperators()
		{
			double num = 66.0;
			CxAssert((num += 1.0) == 67.0);
			CxAssert((num -= 1.0) == 66.0);
			num += 1.0;
			CxAssert(num == 66.0);
			num -= 1.0;
			CxAssert(num == 67.0);
		}
```

In case you are interested following is how my C++ translator translated it.

```c++
Void	CABlock_NS::DoubleTest::DoubleOperators()
{
	struct Locals
	{
		Double	LC000;
		Double	dup4;
		Double	dup5;
		Double	dup6;
		Double	dup7;

		Locals()
		{
			LC000 = 0;
		};
	};
	SysBase::CheckStack();
	Locals	 locals;

	locals.dup4 = CabMath::AddDouble(((Double)locals.LC000),((Double)(((CXChar)locals.LC001).GetAsDouble())));
	locals.LC000 = ((Double)locals.dup4);
	CxAssert(((Boolean)CabMath::EqualsDouble(((Double)locals.dup4),((Double)67.0))));
	locals.dup5 = CabMath::SubtractDouble(((Double)locals.LC000),((Double)(((CXChar)locals.LC001).GetAsDouble())));
	locals.LC000 = ((Double)locals.dup5);
	CxAssert(((Boolean)CabMath::EqualsDouble(((Double)locals.dup5),((Double)66.0))));
	locals.dup6 = CabMath::AddDouble(((Double)locals.LC000),((Double)(((CXInt32)locals.LC002).GetAsDouble())));
	locals.LC000 = ((Double)locals.dup6);
	CxAssert(((Boolean)CabMath::EqualsDouble(((Double)locals.dup6),((Double)67.0))));
	locals.dup7 = CabMath::SubtractDouble(((Double)locals.LC000),((Double)(((CXInt32)locals.LC002).GetAsDouble())));
	locals.LC000 = ((Double)locals.dup7);
	CxAssert(((Boolean)CabMath::EqualsDouble(((Double)locals.dup7),((Double)66.0))));
}
```

**Comment by dgrunwald** [comment]
Looks like a weird interaction between variable splitting+recombining and copy propagation.
Before copy propagation:
```
			call WriteLine(ldstr "IncDecDouble:")
			stloc V_0(ldc.f8 66)
			call WriteLine(stloc V_0(binary.add.f8(ldloc V_0, ldc.f8 1)))
			call WriteLine(stloc V_0(binary.sub.f8(ldloc V_0, ldc.f8 1)))
			stloc S_10(ldloc V_0)
			stloc V_0(binary.add.f8(ldloc S_10, ldc.f8 1))
			call WriteLine(ldloc S_10)
			stloc S_14(ldloc V_0)
			stloc V_0(binary.sub.f8(ldloc S_14, ldc.f8 1))
			call WriteLine(ldloc S_14)
			call WriteLine(ldloc V_0)
```
after:
```
			call WriteLine(ldstr "IncDecDouble:")
			stloc V_0(ldc.f8 66)
			call WriteLine(stloc V_0(binary.add.f8(ldloc V_0, ldc.f8 1)))
			call WriteLine(stloc V_0(binary.sub.f8(ldloc V_0, ldc.f8 1)))
			stloc V_0(binary.add.f8(ldloc V_0, ldc.f8 1))
			call WriteLine(ldloc V_0)
			stloc V_0(binary.sub.f8(ldloc V_0, ldc.f8 1))
			call WriteLine(ldloc V_0)
			call WriteLine(ldloc V_0)
			leave IL_0000 (nop)
```
Note that there are different instances of `V_0` here, so the code after the copy propagation transform would still be correct if we had a unique name for each part of `V_0`. It's the recombination into a single variable that ends up changing the semantics.

So really the problem is that variable recombination relies on something that we haven't documented/validated as an invariant yet: different parts of a split variable have non-overlapping lifetimes.
This is initially guaranteed by construction when splitting variables, but transforms might end up violating this. I don't know if copy propagation is the only transform that causes problems here.

**Comment by dgrunwald** [comment]
We recently moved copy propagation to a late phase in the decompiler, so it would be possible to recombine the split variables on the ILAst side before running copy propagation (currently recombination happens implicitly during the translation to C# simply because the variable name is reused).

That would fix this case, but what about other transforms? There aren't many that do non-local code movement, so it could be possible that there aren't any additional problems.

But on the other hand, I don't think it's realistic to expect our transforms to uphold a non-local invariant like "different parts of a split variable have non-overlapping live ranges".
So the solution might be to write a data flow analysis that detects such overlapping live ranges and assigns unique names to the different parts of the variable?

**Comment by lambertlb** [comment]
Sorry for this long post but i need to include a lot of details. A de-compiler is basically a pattern recognition process. Both problems i submitted almost had identical patterns with the cases that succeed. It therefore seems to me that at its core there is probably too much type bias that needs to be made more generic. I took the two issues I submitted and created a new test dll to illustrate. I also added two successful cases that just use different types. Below I will show three outputs for each case.
1)	Original ccode.
2)	ILSpy decompiled code.
3)	ILDasm output for the code.
This will illustrate that there is almost no difference between the IL code that passes vs the ones that fails. The variation is mainly the type. A generic pattern recognizer should generate basically the same syntax tree. Since it doesn’t it seems to me that there must be too much type dependency in the recognizer. This has gotten me interested so I will check out the project and look into this.

Original code:
public void	Uint64ToStringTest()
{
	TestAssert(UInt64.MinValue.ToString() == "0");
}
public void UIn32ToStringTest()
{
	TestAssert(UInt32.MinValue.ToString() == "0");
}
public void DoublePostIncrementTest()
{
	double num = 1;
	TestAssert((num++) == 1);
}
public void Int32PostIncrementTest()
{
	Int32 num = 1;
	TestAssert((num++) == 1);
}

ILSpy translated code:
    public unsafe void Uint64ToStringTest()
    {
        TestAssert(((ulong*)(&0))->ToString() == "0");
    }

    public void UIn32ToStringTest()
    {
        TestAssert(0u.ToString() == "0");
    }

    public void DoublePostIncrementTest()
    {
        double num2 = 1.0;
        num2 += 1.0;
        TestAssert(num2 == 1.0);
    }

    public void Int32PostIncrementTest()
    {
        int num = 1;
        TestAssert(num++ == 1);
    }

ILDasm Code:
  .method public hidebysig instance void 
          Uint64ToStringTest() cil managed
  {
    // Code size       29 (0x1d)
    .maxstack  3
    .locals init ([0] uint64 V_0)
    IL_0000:  nop
    IL_0001:  ldarg.0
    IL_0002:  ldc.i4.0
    IL_0003:  conv.i8
    IL_0004:  stloc.0
    IL_0005:  ldloca.s   V_0
    IL_0007:  call       instance string [mscorlib]System.UInt64::ToString()
    IL_000c:  ldstr      "0"
    IL_0011:  call       bool [mscorlib]System.String::op_Equality(string,
                                                                   string)
    IL_0016:  call       instance void TestLibrary.TestClass::TestAssert(bool)
    IL_001b:  nop
    IL_001c:  ret
  } // end of method TestClass::Uint64ToStringTest

  .method public hidebysig instance void 
          UIn32ToStringTest() cil managed
  {
    // Code size       28 (0x1c)
    .maxstack  3
    .locals init ([0] uint32 V_0)
    IL_0000:  nop
    IL_0001:  ldarg.0
    IL_0002:  ldc.i4.0
    IL_0003:  stloc.0
    IL_0004:  ldloca.s   V_0
    IL_0006:  call       instance string [mscorlib]System.UInt32::ToString()
    IL_000b:  ldstr      "0"
    IL_0010:  call       bool [mscorlib]System.String::op_Equality(string,
                                                                   string)
    IL_0015:  call       instance void TestLibrary.TestClass::TestAssert(bool)
    IL_001a:  nop
    IL_001b:  ret
  } // end of method TestClass::UIn32ToStringTest

  .method public hidebysig instance void 
          DoublePostIncrementTest() cil managed
  {
    // Code size       43 (0x2b)
    .maxstack  4
    .locals init ([0] float64 num)
    IL_0000:  nop
    IL_0001:  ldc.r8     1.
    IL_000a:  stloc.0
    IL_000b:  ldarg.0
    IL_000c:  ldloc.0
    IL_000d:  dup
    IL_000e:  ldc.r8     1.
    IL_0017:  add
    IL_0018:  stloc.0
    IL_0019:  ldc.r8     1.
    IL_0022:  ceq
    IL_0024:  call       instance void TestLibrary.TestClass::TestAssert(bool)
    IL_0029:  nop
    IL_002a:  ret
  } // end of method TestClass::DoublePostIncrementTest

  .method public hidebysig instance void 
          Int32PostIncrementTest() cil managed
  {
    // Code size       19 (0x13)
    .maxstack  4
    .locals init ([0] int32 num)
    IL_0000:  nop
    IL_0001:  ldc.i4.1
    IL_0002:  stloc.0
    IL_0003:  ldarg.0
    IL_0004:  ldloc.0
    IL_0005:  dup
    IL_0006:  ldc.i4.1
    IL_0007:  add
    IL_0008:  stloc.0
    IL_0009:  ldc.i4.1
    IL_000a:  ceq
    IL_000c:  call       instance void TestLibrary.TestClass::TestAssert(bool)
    IL_0011:  nop
    IL_0012:  ret
  } // end of method TestClass::Int32PostIncrementTest
