### ISSUE TITLE
Failed to identify an special lambda

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1660]
Tested with ILSpy 5.0.0.5087-preview4

### Code
```cs
    public class D
    {
        protected virtual void BaseCall<T>(object x, object state, Func<T> action)
        {
        }
    }
    public class C : D
    {
        public Action<object> M(object state)
        {
            return (x) => {
                base.BaseCall(x, state, () => default(object));
            };
        }
    }
```

### Actual
```cs
public class C : D
{
/*
[Serializable]
[CompilerGenerated]
private sealed class <>c
{
	public static readonly <>c <>9 = new <>c();

	public static Func<object> <>9__0_1;

	internal object <M>b__0_1()
	{
		return null;
	}
}

[CompilerGenerated]
private sealed class <>c__DisplayClass0_0
{
	public C <>4__this;

	public object state;

	internal void <M>b__0(object x)
	{
		<>4__this.<>n__0(x, state, (Func<object>)(() => null));
	}
}

[CompilerGenerated]
[DebuggerHidden]
private void <>n__0<T>(object x, object state, Func<T> action)
{
	base.BaseCall(x, state, action);
}
*/
	public Action<object> M(object state)
	{
		return delegate(object x)
		{
			<>n__0(x, state, (Func<object>)(() => null));
		};
	}
}
```

**Comment by dgrunwald** [comment]
Looks like a problem with the `ProxyCallReplacer` transform that is supposed to replace `<>n__0` with `base.BaseCall`.
The C# compiler introduces such a private helper method because it's illegal to call `base.ProtectedMethod` from a nested class.
Looks like we currently expect the helper method to have the same type parameters as the caller `M`, when in fact it has the same type parameters as the callee `BaseCall`.

**Comment by siegfriedpammer** [comment]
https://github.com/icsharpcode/ILSpy/blob/3c2a26325ef8f5a11765cde96db4c48750719ec0/ICSharpCode.Decompiler/IL/Transforms/ProxyCallReplacer.cs#L33

genericContext is null

**Comment by dgrunwald** [comment]
`DelegateConstruction.GenericContextFromTypeArguments` expects the type arguments to be the caller's type parameters. This works for yield/async/lambda helper methods, as those inherit type parameters from the method containing them.
But proxy call helpers seem to inherit type parameters from the target method, not from the containing method. So `GenericContextFromTypeArguments` ends up being the wrong tool.
