### ISSUE TITLE
strange castings for ctor

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1661]
ILSpy version 5.0.0.5093-preview4

seen this today, it was OK before ...

![image](https://user-images.githubusercontent.com/765343/63633665-ad62da00-c654-11e9-8c34-e42bc3e8ae4c.png)

**Comment by siegfriedpammer** [comment]
Could you provide a more complete sample? Thank you!

**Comment by greenozon** [comment]
from #1601

**Comment by siegfriedpammer** [comment]
Looks like a bug introduced by 8c4066d471db3a04e672b262b72542284d9f9fb4...
