### ISSUE TITLE
Variable is not defined

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1668]
[test.zip](https://github.com/icsharpcode/ILSpy/files/3540853/test.zip)

test.dll : Class0.method_6
```
ilist_0 = SGLinq.ToList(SGLinq.Where(ilist_0, (EntityRelation relation) => !SGLinq.Any(relationList, (EnVCEntityRelation vcRelation) => vcRelation.Kind == relation.Kind && vcRelation.From == relation.From && vcRelation.To == relation.To)));
foreach (EntityRelation item in ilist_0)
{
	relation = item;
	IEnumerable<EnVCEntityRelation> enumerable = relationList;
```
`relation` is defined in lambda, can't be used in `foreach`

![image](https://user-images.githubusercontent.com/2529999/63687004-f2923200-c835-11e9-84ba-4e68475c15b3.png)

**Comment by siegfriedpammer** [comment]
Seems this was fixed by the TDCU rewrite.
