### ISSUE TITLE
Post decrement problem revisited

### ISSUE THREAD

**Issue by lambertlb** [icsharpcode/ILSpy#1669]
I have done some investigating and I am opening this issue again. To recap there is a problem with post increment on a double variable.

Original code:
public void DoublePostIncrementTest()
{
    double num = 1;
    TestAssert((num++) == 1);
}

Translated code:
public void DoublePostIncrementTest()
{
	double num2 = 1.0;
	num2 += 1.0;
	TestAssert(num2 == 1.0);
}

After doing a deep dive into the code it seems to me the issue is in file TransformAssignment.cs at line 720.
if (!binary.Left.MatchLdLoc(tmpVar) || !binary.Right.MatchLdcI(1))
    return false;
binary.Right.MatchLdcI(1) this portion of the expression assumes there is an integer constant of 1 but in fact it can also be a double constant of one so the method exists with a false. Once that is fixed there might be later code that needs to be tweaked. If i have time i might take a shot at it. I would expect you guys could do it a lot faster though since you are familiar with the code.

Not sure how come the original issue i posted was closed since this in fact a bug and needs to be fixed to ensure the translated code runs accurately. The main requirement for my translator was the code runs identical to the original and having the code be aesthetically pleasing was a secondary requirement. Not sure what your requirements are so they maybe different.

**Comment by dgrunwald** [comment]
Your original issue for the double decrement is #1656 and is still open (was never closed).
You're correct that it would be an easy fix to detect post-increment on doubles.
However there's another bug that causes the statements to be output in the wrong order; that will need to also be solved since it could also be triggered by other code constructs.

**Comment by lambertlb** [comment]
technically i don't think it is out of order. Following is the IL code.
    IL_0000:  nop
    IL_0001:  ldc.r8     1.
    IL_000a:  stloc.0
    IL_000b:  ldarg.0
    IL_000c:  ldloc.0
    IL_000d:  dup
    IL_000e:  ldc.r8     1.
    IL_0017:  add
    IL_0018:  stloc.0
    IL_0019:  ldc.r8     1.
    IL_0022:  ceq
    IL_0024:  call       instance void TestLibrary.TestClass::TestAssert(bool)
    IL_0029:  nop
    IL_002a:  ret

The part that is missing for correctness is duplicating the starting value and doing the test on the duplication. That part is missing. The addition and store to local value is correct. My translator just created a local variable called dup and added to and tested that. I did not do the extra transforms to use post decrement because it wasn't required for my project.

**Comment by lambertlb** [comment]
I thought I would elaborate in case it is useful to you. In my translator when i encountered a DUP instruction i would create a new local variable with the name of Dup plus a a duplicate item counter  appended to the end. I would treat the dup as a store local. During my analysis phase if a transformation was able to consume the dup i would just mark the variable as unused so it was optimized out later. This way if no transform did anything with it the output would just contain an extra local variable with an assignment.  And subsequent statements would use that variable name.  Hope that helps

**Comment by dgrunwald** [comment]
ILSpy already does something like that. But it also has a bunch of transforms that try to get rid of such generated variables to make the code nicer to read; and a combination of those introduces this bug. (I've described the details in #1656)

**Comment by lambertlb** [comment]
Post decrement and increment also have issues on pointer types. This seems to be an issue on all scalar types except Byte and SByte which pass all the tests. Following is an example of one of the types failing.
```
/// <summary>
/// Test structure
/// </summary>
public struct TestStruct
{
    /// <summary>
    /// Variable for test
    /// </summary>
    public Int16 X;
}

/// <summary>
/// Pointer related operators tests as defined in https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators
/// </summary>
private void Int16PointerOperationsTests()
{
    unsafe
    {
        Int16 number = 27;
        Int16* pointerToNumber = &number;
        Program.LocalAssert(*pointerToNumber == 27);
        *pointerToNumber = 8;
        Program.LocalAssert(*pointerToNumber == 8);
        TestStruct test1;
        test1.X = 2;
        TestStruct* basePtr = &test1;
        Program.LocalAssert(basePtr->X == 2);
        Int16* stackArray = stackalloc Int16[3];
        stackArray[0] = 1;
        stackArray[1] = 2;
        stackArray[2] = 3;
        Program.LocalAssert(stackArray[1] == 2);
        Program.LocalAssert(*(stackArray + 2) == 3);
        Program.LocalAssert(*(&stackArray[1] - 1) == 1);
        pointerToNumber = stackArray;
        Program.LocalAssert(*(++pointerToNumber) == 2);
        Program.LocalAssert(*(--pointerToNumber) == 1);

// Following has the error
        Program.LocalAssert(*pointerToNumber++ == 1);
        Program.LocalAssert(*pointerToNumber == 2);
        Program.LocalAssert(*(pointerToNumber--) == 2);
        Program.LocalAssert(*pointerToNumber == 1);
    }
}

results in the following:
pointerToNumber6++;
Program.LocalAssert(*pointerToNumber6 == 1);

```

**Comment by siegfriedpammer** [comment]
See #947 as well.

**Comment by dgrunwald** [comment]
The code reordering problem is fixed now, so ILSpy should now produce correct code in these cases (using a temporary variable to hold the old value prior to the increment).
I think post-increment on double is not common enough to bother supporting the pretty syntax.
Post-increment on pointers has #947.
