### ISSUE TITLE
Strong Naming Yes/No?

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1670]
A "For the record" issue - do we still need strong naming on ics.d? Reason is that I tried adding a NuGet to ILSpy.csproj, and that package was not strong named (like most NuGet packages), and obviously ILSpy wouldn't start. 

What is the reason we still sn ics.id? @dgrunwald I remember a discussion, but not really any of the points.

**Comment by dgrunwald** [comment]
To my knowledge most NuGet packages are strong named.
After all, a package without strong name cannot be used by other packages/programs that are strong named; but a package with a strong name can be used everywhere.

Also, AFAIK adding/remove a strong name is a massive breaking change that forces all ILSpy plugins to recompile. I think currently we are still mostly ABI-compatible with ILSpy 4.0, so we shouldn't change anything right now.

**Comment by christophwille** [comment]
Given my initial problem, would the following work (or how could we make it work, it at all): the main thrust is that I want non-sn'd NuGets in ILSpy.exe (my sample was https://github.com/MahApps/MahApps.Metro), so: could we keep the sn on ics.d, but get rid of it on ILSpy.exe? I understand that InternalsVisibleTo is the issue here (togethere with the sn), is there any way that our API surface could be made so that we no longer need to work with InternalsVisibleTo?

Yes, having the sn on the NuGet is good, but on ILSpy.exe can be a problem (assuming that eg we introduce that in vNext).

**Comment by christophwille** [comment]
Will keep sn on ilspy.exe (that might need to be revisited for netcore where .exe is a shim for dll main assembly)
