### ISSUE TITLE
"Save Code" in ILSpy results in different source compared to the code shown in UI

### ISSUE THREAD

**Issue by an-dr-eas-k** [icsharpcode/ILSpy#1674]
ILSpy allows configuration of `DecompilerSettings` in the options dialog and this settings are applied in the UI text editor.

When calling the "Save Code" function from the menu bar, or the assembly context menu, different code is generated. Here the ILSpy `DecompilerSettings` are not respected, neither do the variable names follow those from the debug symbols in pdb files. Here new instances of `ICS.Decompiler` are created with hard coded `DecompilerSettings` and lost  `DebugInfoProvider`.

Also the pwsh cmdlets have no possibility to specify `DecompilerSettings`. Again, the debug symbols are not respected when generating cs code.

This issue was already brought up in #1328 and #1426 where it was vaguely described and thus rejected.

Especially the feature to preserve the `DebugInfoProvider` is painful as it means making the `PortableDebugInfoProvider` and `MonoCecilDebugInfoProvider` available for `ICS.Decompiler`.

In my opinion, these two providers are no _UI features_, but technically required for proper csharp code, thus the transfer to `ICS.Decompiler` is consistent. Talking about the referenced Mono.Cecil: The final compile output contain this libraries anyhow.

**Comment by christophwille** [comment]
For this discussion there is one important distinction to make: between the ICS.Decompiler NuGet package and the ILSpy frontend. ICS.D was specifically re-architected in v4 to move from Cecil to System.Reflection.Metadata. Frontends like ILSpy on the other hand can take those dependencies, that is why there is a PDB Provider interface that does take a Cecil dependency.

**Comment by siegfriedpammer** [comment]
I guess there are a few misunderstandings here:

One part of this issue discusses the debug info:

* `IDebugInfoProvider` and its implementations are meant to be independent from the UI and the other decompiler frontends and of course the decompiler itself, as there are multiple PDB formats.
* `IDebugInfoProvider` is not connected to the decompiler settings in any way: be887d0 adds the relevant setting to the `WholeProjectDecompiler`.

The other part is about the missing option to allow passing decompiler settings to the powershell and cmdline frontends.

**Comment by an-dr-eas-k** [comment]
Yes. That is a valid point. Actually I really was afraid of this changes in project references. 

Perhaps the provider are again refactored to a new assembly that is subsequently available to the powershell frontend and ILSpy. I somehow liked the idea of this `LoadSymbols` method in PEFile and was relying on this.

Currently my solution fits my needs but I confess, I was not digging in the project history.

**Comment by siegfriedpammer** [comment]
> Talking about the referenced Mono.Cecil: The final compile output contain this libraries anyhow.

No, the Nuget distribution of [`ICSharpCode.Decompiler`](https://www.nuget.org/packages/ICSharpCode.Decompiler/) does NOT contain Mono.Cecil. The nuget is used by Roslyn and many other users. We want to keep the nuget distribution as small as possible.

**Comment by siegfriedpammer** [comment]
be887d0 fixes one problem mentioned in this issue. I have created #1676 and #1677 for the missing features.
