### ISSUE TITLE
Add an option to support custom DecompilerOptions to powershell and command-line frontends

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1677]
The powershell and command-line frontends of the decompiler engine do not allow customizing the output of the decompiler or which language version/transformations it should apply.

Implement either an option that accepts a file containing the selected options (similar to ILSpy.xml, but without all the options that do not apply to the decompiler) or a switch for every single option.

I am not sure which of these is better: using a file would require us to define some format; using switches, is a lot of work and will become complicated.

**Comment by dgrunwald** [comment]
Do we need all the individual options? It's probably sufficient to have a single switch for the C# version?

**Comment by siegfriedpammer** [comment]
Good point. Maybe @an-dr-eas-k could chime in and describe their requirements? From my point of view language version would be sufficient.

**Comment by an-dr-eas-k** [comment]
See my new pull request #1679 where I rely on the currently existing settings file. No new format needs definition.

**Comment by siegfriedpammer** [comment]
I am not a fan of reusing the ILSpy.xml settings file because it contains a lot more than is actually usable by the commandline. It contains not only the settings, but also the assembly list configuration, which has no value for the commandline.

**Comment by an-dr-eas-k** [comment]
The only elements read and used from ilspy.xml are ILSpy.DecompilerSettings. In my opinion, this subtree is sufficient for the new settings file. Which makes the ilspy.xml file compatible for a new file if you like.

**Comment by christophwille** [comment]
Going back to Daniel's comment - what do you customize *aside* from the lanuage version? If so, why?

**Comment by an-dr-eas-k** [comment]
In the end you are right, setting the language version is a good start. 

There were two reasons why my code differed between UI and powershell/"save Code" calls: 
- missing debug symbols and 
- the switches RemoveDeadCode RemoveDeadStores which I liked and which are not covered from the language version.

So, I came up with the idea to just use the original ilspy.xml with all detailed stuff.

Cheers.
