### ISSUE TITLE
Show enum value setting

### ISSUE THREAD

**Issue by Symbai** [icsharpcode/ILSpy#1685]
Using ICSharpCode.Decompiler nuget packed in version 4.0.0.4521. What's the decompiler setting that enables showing the enum values?

Expected:
```
public enum Blabla
{
 none = 0,
 whatever = 123
}
```

While this code:

```
var decompiler = new CSharpDecompiler(typ.ParentModule.PEFile.FileName,
	new DecompilerSettings() {
		ThrowOnAssemblyResolveErrors = false
	});
return decompiler.DecompileTypeAsString(typ.Type.FullTypeName);
```

returns:
```
public enum Blabla
{
 none,
 whatever
}
```

**Comment by siegfriedpammer** [comment]
There is no setting to disable this. The returned code is wrong... however, I am unable to reproduce the problem in ILSpy.

**Comment by Symbai** [comment]
First of all the issue is about  ICSharpCode.Decompiler nuget packed in version 4.0.0.4521  and not ILSpy. However it can also be produced with ILSpy.

![image](https://user-images.githubusercontent.com/14368203/64179602-fb48c080-ce52-11e9-9f7d-10c163d646cd.png)
![image](https://user-images.githubusercontent.com/14368203/64179626-07cd1900-ce53-11e9-83a2-6dbb518ff330.png)
![image](https://user-images.githubusercontent.com/14368203/64179619-03086500-ce53-11e9-9ac2-36cd2a0c0f56.png)

The first image should show:
```
public enum Bla
{
	none = 0,
	whatever = 1
}
```

And the reason why it does not is because in source the enum is written as:
![image](https://user-images.githubusercontent.com/14368203/64179732-2fbc7c80-ce53-11e9-97ef-9921bb690ce0.png)
but instead when it's written in source as:
![image](https://user-images.githubusercontent.com/14368203/64179881-62667500-ce53-11e9-856c-bf7be08667a0.png)
ILSpy shows:
![image](https://user-images.githubusercontent.com/14368203/64179908-6d210a00-ce53-11e9-8954-0368c1579aeb.png)

Conclusion: If an enum does not straighly counts up and misses a number the decompiler shows the values but on default it does not, although it knows the integer values (none = 0, whatever = 1). So the request would be to show the values at all times.
