### ISSUE TITLE
New code pattern for string concatenation

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/ILSpy#1691]
This is currently causing test failures (due to the Roslyn NuGet update):
https://github.com/dotnet/roslyn/pull/35006

This gets tricky because there is a change in evaluation order and possibly also with regards to mutable value types, see https://github.com/dotnet/roslyn/issues/522#issuecomment-482494176
So supporting both patterns would result in two programs with different behaviors decompiling to the same code, which then has one of the behaviors depending on which compiler version is used when recompiling :(

**Comment by christophwille** [comment]
Test errors: https://ci.appveyor.com/project/icsharpcode/ilspy/build/job/cb9c5utkc4jiqbdu/tests 
Code change: https://github.com/icsharpcode/ILSpy/commit/61ef67f854fb1a904b835c508041f635a4cfe0bb#diff-37a82c6ae3b55ce5d833adbd171c918eL45

**Comment by dgrunwald** [comment]
Given that the meaning of `operator+(object, string)` is now different between VS2019.3 and earlier versions; and that it may change again in the future (dotnet/roslyn#38641), I think ILSpy should keep calls to `string.Concat(object, object)` as-is.
Exception: we could detect special cases where we know the evaluation order according to both compiler versions is identical to the language spec, and keep the pretty `"A" + num` for those.
This would involve a hard-coded list of special types (e.g. `int`) that are known to have a side-effect-free `ToString()` implementation.
