### ISSUE TITLE
VSIX: Cannot find type

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1701]
Sample project attached. 

Repro: right-click on .Add (line 32 in MainWindow.xaml.cs) and choose "Open code in ILSpy". Resulting error in ILSpy: Cannot find 'M:System.Net.Http.Headers.HttpHeaders.Add(System.String,System.String)' in command line specified assemblies.

[WpfHttpClientRepro.zip](https://github.com/icsharpcode/ILSpy/files/3623203/WpfHttpClientRepro.zip)

HttpClient seems to be "special" because that's the only one I could come with that showed this error message.

**Comment by christophwille** [comment]
Related old issue https://github.com/icsharpcode/ILSpy/issues/1164

**Comment by Rpinski** [comment]
After some improvements in resolution of reference assemblies in c729922961a915ae73ec807760c818b3791d8f08 this issue has been fixed, too.
