### ISSUE TITLE
NullPropagationTransform.IsGetter not work for getter on generic types

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1709]
>The issue is updated to make it more clear

Tested with 6.0.0.5171-alpha1.

Seems the below code need to be changed to `method.AccessorOwner is IProperty p && method.Equals(p.Getter);`?
https://github.com/icsharpcode/ILSpy/blob/57b725df7981cc3688037ee358a9c2a109303a64/ICSharpCode.Decompiler/IL/Transforms/NullPropagationTransform.cs#L273-L276

### Code
```cs
using System.Collections;
using System.Collections.Generic;

    public class TestClass
    {
        public int? Method(object obj)
        {
            return (obj as ICollection)?.Count + (obj as ICollection<int>)?.Count
        }
    }
```

### Actual
You can see it works for `ICollection` but not for `ICollection<int>`
```cs
using System.Collections;
using System.Collections.Generic;

    public class TestClass
    {
	public int? Method(object obj)
	{
		int? num = (obj as ICollection)?.Count;
		ICollection<int> obj2 = obj as ICollection<int>;
		return num + ((obj2 != null) ? new int?(obj2.Count) : null);
	}
    }
```

**Comment by dgrunwald** [comment]
Thanks for debugging this!

We introduced `IMethod.AccessorKind` during the migration to System.Reflection.Metadata, so that can be used to simplify this check.
