### ISSUE TITLE
Add support for attributes defined for return values ([return: ...])

### ISSUE THREAD

**Issue by michael-damatov** [icsharpcode/ILSpy#1715]
Decompiling the `Enumerable.FirstOrDefault` looks like this:
```cs
public static TSource FirstOrDefault<TSource>(this IEnumerable<TSource> source)
{
    bool found;
    return source.TryGetFirst(out found);
}
```

The Source Browser (https://source.dot.net/System.Linq/R/8087366974af11d2.html) shows the `MaybeNull` attribute that annotates the return value:
```cs
[return: MaybeNull]
public static TSource FirstOrDefault<TSource>(this IEnumerable<TSource> source) =>
    source.TryGetFirst(out bool _);
```

Using ILSpy version 5.0.0.5124 with .NET Core 3.0.

**Comment by siegfriedpammer** [comment]
`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Linq.dll` does not contain this attribute on my machine either... ILSpy can't display something that's not there in the IL.

```
.method /* 0600006E */ public hidebysig static 
	!!TSource FirstOrDefault<TSource> (
		class [System.Runtime]System.Collections.Generic.IEnumerable`1<!!TSource> source
	) cil managed 
{
	.custom instance void [System.Runtime]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = (
		01 00 00 00
	)
	// Method begins at RVA 0xb1dc
	// Code size 9 (0x9)
	.maxstack 2
	.locals /* 11000036 */ (
		[0] bool
	)

	IL_0000: ldarg.0
	IL_0001: ldloca.s 0
	IL_0003: call !!0 System.Linq.Enumerable::TryGetFirst<!!TSource>(class [System.Runtime]System.Collections.Generic.IEnumerable`1<!!0>, bool&) /* 2B00000D */
	IL_0008: ret
} // end of method Enumerable::FirstOrDefault
```

**Comment by dgrunwald** [comment]
Maybe these attributes only exist on the reference assemblies?

**Comment by michael-damatov** [comment]
Decompiling the `List<T>.Find` method works correctly:

```cs
[return: MaybeNull]
public T Find(Predicate<T> match)
{
  ...
}
```

**Comment by yyjdelete** [comment]
@michael-damatov 
Seems it's only include as a part of master(5.0) of corefx, but not in 3.0.
https://github.com/dotnet/corefx/commit/fe969a5893b845c0ba4550d828894c49745f456f

https://github.com/dotnet/corefx/blob/release/3.0/src/System.Linq/src/System/Linq/First.cs#L33-L37
