### ISSUE TITLE
Generic type parameters cannot be applied to basic types 

### ISSUE THREAD

**Issue by kornos** [icsharpcode/ILSpy#1718]
- What version did you use? : ILSpy version 6.0.0.5182-alpha1

- Write down all steps needed to reproduce this issue. Also attach any needed files.

1.Open the attached assembly.dll
2. Browse to NetFtpLibrary.FTP class

private bool <<IgnoreDirectoriesWithNoPermission>>k__BackingField;
private string <<ReconnectRetryTestCommand>>k__BackingField;

[assembly.zip](https://github.com/icsharpcode/ILSpy/files/3663077/assembly.zip)

**Comment by siegfriedpammer** [comment]
These are backing fields of automatic properties. Usually automatic properties have `CompilerGeneratedAttribute`s attached to the backing fields and the `get`/`set` accessors. Looks like this assembly was modified with some tool.
