### ISSUE TITLE
Initial Checkout Visual Studio Build Failure

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1731]
When executing Build/Build in VS 16.3 (and earlier) on a fresh git clone checkout in a blank directory, build fails:

```1>------ Build started: Project: ICSharpCode.TreeView, Configuration: Debug Any CPU ------
2>------ Build started: Project: ICSharpCode.Decompiler, Configuration: Debug Any CPU ------
2>ILSpyUpdateAssemblyInfo225442377
1>ICSharpCode.TreeView -> D:\Demos\ILSpy-blankcheckout1\SharpTreeView\bin\Debug\net472\ICSharpCode.TreeView.dll
2>ICSharpCode.Decompiler -> D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler\bin\Debug\netstandard2.0\ICSharpCode.Decompiler.dll
2>Successfully created package 'D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler\bin\Debug\ICSharpCode.Decompiler.6.0.0.5240-alpha1-debug.nupkg'.
2>Done building project "ICSharpCode.Decompiler.csproj".
3>------ Build started: Project: ICSharpCode.Decompiler.Tests, Configuration: Debug Any CPU ------
4>------ Build started: Project: ICSharpCode.Decompiler.PdbProvider.Cecil, Configuration: Debug Any CPU ------
5>------ Build started: Project: ILSpy.BamlDecompiler, Configuration: Debug Any CPU ------
6>------ Build started: Project: TestPlugin, Configuration: Debug Any CPU ------
3>ICSharpCode.Decompiler.Tests -> D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler.Tests\bin\Debug\net472\ICSharpCode.Decompiler.Tests.exe
7>------ Build started: Project: ILSpy.Tests, Configuration: Debug Any CPU ------
4>ICSharpCode.Decompiler.PdbProvider.Cecil -> D:\Demos\ILSpy-blankcheckout1\ICSharpCode.Decompiler.PdbProvider.Cecil\bin\Debug\netstandard2.0\ICSharpCode.Decompiler.PdbProvider.Cecil.dll
7>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
7>Done building project "ILSpy.Tests.csproj" -- FAILED.
5>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
5>Done building project "ILSpy.BamlDecompiler.csproj" -- FAILED.
8>------ Build started: Project: ILSpy.BamlDecompiler.Tests, Configuration: Debug Any CPU ------
9>------ Build started: Project: ILSpy.AddIn, Configuration: Debug Any CPU ------
6>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
6>Done building project "TestPlugin.csproj" -- FAILED.
9>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
9>Done building project "ILSpy.AddIn.csproj" -- FAILED.
8>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.BamlDecompiler.Plugin.dll' could not be found
8>CSC : error CS0006: Metadata file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\bin\Debug\net472\ILSpy.exe' could not be found
8>Done building project "ILSpy.BamlDecompiler.Tests_2qz4kodo_wpftmp.csproj" -- FAILED.
========== Build: 4 succeeded, 5 failed, 1 up-to-date, 0 skipped ==========
```

Sometimes, the following error shows up in the log too:
```
Error	MSB4018	The "WriteAppConfigWithSupportedRuntime" task failed unexpectedly. System.IO.FileNotFoundException: Could not find file 'D:\Demos\ILSpy-blankcheckout1\ILSpy\app.config'.
```
An immediately following Build/Rebuild works as expected. It seems that VS doesn't respect project dependencies on the initial Build/Build. 

If I copy ILSpy\app.config from a previous checkout (where ILSpyUpdateAssemblyInfo already had run) to a new blank checkout, initial Build/Build works. It seems that the missing app.config - which is generated from a template via ILSpyUpdateAssemblyInfo task - messes up Visual Studio's build ordering because neither AppVeyor nor Azure Pipelines has this "on initial checkout" build problem.

**Comment by christophwille** [comment]
Instead of hoping that MS fixes that issue in VS I propose the following:

* Check in a version of ILSpy\app.config
* Add ILSpy\app.config to .gitignore

With the file in place, Build runs correctly (in-order) *even* overwriting the file before build takes place. @dgrunwald acceptable workaround solution?

**Comment by dasMulli** [comment]
The problem seems to be that the csproj contains a reference to a file that does not exist and the task that finds the app.config file for processing doesn't really check...

I was able to work around this with
```diff
diff --git a/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj b/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csprojindex cd5bc932..3fa2a69f 100644
--- a/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
+++ b/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj
@@ -619,7 +619,7 @@
     <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
   </ItemGroup>

-  <Target Name="ILSpyUpdateAssemblyInfo" BeforeTargets="BeforeBuild">
+  <Target Name="ILSpyUpdateAssemblyInfo" BeforeTargets="PrepareForBuild">
     <PropertyGroup>
       <UpdateAssemblyInfo>powershell -NoProfile -ExecutionPolicy Bypass -File BuildTools/update-assemblyinfo.ps1 $(Configuration)</UpdateAssemblyInfo>
     </PropertyGroup>
```

**Comment by christophwille** [comment]
I'll give that a try - but do you have any idea why only VS chokes on that and the build servers using msbuild work just fine?

**Comment by dasMulli** [comment]
Some design time builds are still failing though because the Nuget restore fails b/c it is sometimes restored before the other project. Since the PS script to generate the app.config is triggered from a different project than the one being restored with

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/6129250/66129222-c49bcc80-e5ef-11e9-9216-75fca0bafeb1.png">

**Comment by christophwille** [comment]
Interesting - using PrepareForBuild seems to lead to multiple invocations of ILSpyUpdateAssemblyInfo, but yes, Build/Build on a blank checkout works.

**Comment by dasMulli** [comment]
Bottom line, MSBuild looks during `PrepareForBuild` if there is an app.config referenced by the solution and sets up all the items and properties that further processing tasks rely on..

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/6129250/66129697-b8643f00-e5f0-11e9-9e54-bf69e035cfd2.png">

**Comment by dasMulli** [comment]
PrepareForBuild is called quite often for all sorts of targets like design time builds..
So you may wants to call it before PrepareForBuild only if necessary..

```xml
  <Target Name="ILSpyUpdateAssemblyInfoOnPrepareForBuildIfNecessary"
          DependsOnTargets="ILSpyUpdateAssemblyInfo"
          Condition="!Exists('..\ILSpy\app.config')" />
```

**Comment by christophwille** [comment]
The "only if necessary" bit could get interesting - and that got us into that bind in the first place... we insert the git revision number (calculated via this PS) into the version number, thus we need the binding redirects to that very version (we use MEF).

**Comment by siegfriedpammer** [comment]
We could use @dasMulli's solution in addition to our current configuration. This would ensure that app.config is generated before the first build, but is still updated on every build.

**Comment by dasMulli** [comment]
> do you have any idea why only VS chokes on that and the build servers using msbuild work just fine

Crystal ball tells me that VS just does project build ordering a little differently when design time builds and up-to-date build system gets into that project.
Even Restore works differently with pure msbuild-based restore works a little different.
Collecting a binlog during CI runs could help.. 

The "only if necessary" part as meaning to call it *additionally* before prepareforbuild and leave the Before="BeforeBuild" in there as well. But now thinking about it, this is probably a super bad idea anyway because the tasks that fail basically copy+edit the file to an intermediate location and set up the further build variables to use that file instead.

**Comment by dasMulli** [comment]
maybe.. use the current git head pointer file as an MSBuild input to make the target incremental 🙃

**Comment by christophwille** [comment]
Maybe one way could be to write a VERSION file in the PS that 'persists' the old version that was used to generate the files from the templates. On each run, check "if file exists and revision == current" short circuit out of the PS.
