### ISSUE TITLE
Optimized "inline" property get/set method stored in a Func/Action decompiled incorrectly

### ISSUE THREAD

**Issue by lbmaian** [icsharpcode/ILSpy#1741]
There apparently exists a C# compiler out there that can optimize the following:
```cs
... Foo(...)
{
    Func<bool> func = () => obj.Prop
    ...
}
```
into (pseudo-decompiled):
```cs
... Foo(...)
{
    Func<bool> func = new Func<bool>(obj.get_Prop);
    ...
}
```
That is, it optimizes away the need for an internal method for the lambda, effectively "inlining" the property get method access into `new Func<bool>(obj.get_Prop)` (which of course isn't valid C#, but results in valid CIL). The same can happen for property set, e.g. `new Action<bool>(obj.set_Prop)`

Contrast that with the typical compilation result (pseudo-decompiled):
```cs
[CompilerGenerated]
bool <Foo>m__0()
{
    return Prop;
}

... Foo(...)
{
    Func<bool> func = new Func<bool>(<Foo>m__0);
    ...
}
```

I'm not sure which C# compiler does this (some older mcs version I think), but I've manually constructed an example dll that features this optimization: [MyClass.zip](https://github.com/icsharpcode/ILSpy/files/3693229/MyClass.zip)

In the dll, the `Foo` method is compiled the regular the way, while the `Bar` method is compiled the "inline" way.

Ideally, `Bar` should be decompiled to have the same body as `Foo`.

**Comment by dgrunwald** [comment]
For any C# compiler other than that old mcs version, there's a big difference between a lambda and a direct delegate.
E.g.
```
MyEvent += new Func<bool>(obj.Method);
MyEvent -= new Func<bool>(obj.Method);
```
works as expected as the delegates compare equal, but once you use two lambdas:
```
MyEvent += obj => obj.Method();
MyEvent -= obj => obj.Method();
```
the delegates no longer compare equal and the event deregistration fails.

The mcs transform may be a valid optimization since the equality of lambdas is left open by the language spec; but the reverse of that transform is definitely invalid!

**Comment by lbmaian** [comment]
The latest build still doesn't fix the issue. I still see the following in decompiled example dll:
```cs
	private Func<bool> Bar()
	{
		return base.get_Active;
	}
```

In the dll that I emailed to you, it also results in the following confusing decompiled code:
```cs
isActive = new Func<bool>(this, __ldftn(CompGatherSpot.get_Active))
```

It now has a `__ldftn` which isn't defined anywhere, and still tries to directly refer to the property get method.

-------------

@dgrunwald

Hmm, that may be true, but there still needs to be a way to refer to a delegate of a property getter (or setter) - and without reflection.

The following decompiled code is still invalid:
`new Func<bool>(obj.get_Prop)`

And it's evident that reflection is not being used in the compiled code, or else we'd see the compiled version of something like `Delegate.CreateDelegate*typeof(Func<bool>, obj.GetType().GetProperty("Prop").GetGetMethod())`.

**Comment by siegfriedpammer** [comment]
> It now has a __ldftn which isn't defined anywhere, and still tries to directly refer to the property get method.

Yes, that is expected. You will have to do manual post-processing on these cases, as we cannot directly represent the semantics in C#. We favor compile errors over runtime errors/wrong semantics, if a 100% valid translation is not possible or too difficult/error-prone.

**Comment by siegfriedpammer** [comment]
> Hmm, that may be true, but there still needs to be a way to refer to a delegate of a property getter (or setter) - and without reflection.

No, this is currently not possible in C#.

**Comment by lbmaian** [comment]
Ugh, this is what I get for manually editing a Linqpad-generated dll with reflexil and forgetting to fix a method reference.

Attached a fixed version of the dll: [query_mkzcgs.zip](https://github.com/icsharpcode/ILSpy/files/3711666/query_mkzcgs.zip)

And I confirm it does decompile into the "correct" code:
```cs
private Func<bool> Bar()
{
	return new Func<bool>(this, __ldftn(MyClass.get_Active));
}
```

I do wish there was an option for controlling how this gets decompiled in the future though, for those like me dealing with whatever dubious ahead-of-time optimizations mcs is doing.

**Comment by dgrunwald** [comment]
It looks like a future C# version will be able to express the `ldftn` opcode: [Function Pointers](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md)

**Comment by siegfriedpammer** [comment]
> I do wish there was an option for controlling how this gets decompiled in the future though, for those like me dealing with whatever dubious ahead-of-time optimizations mcs is doing.

The decompiler pipeline is extensible and contributions are always welcome. :) You could add an `IAstTransform` to the C# AST transforms pipeline that detects the `new Func<T>(arg, __ldftn(...))` pattern and transforms it to what you think might be appropriate. I will gladly answer any questions about the transformation pipeline.

The core members are busy enough with keeping up with the new language features Microsoft is putting out every few months.

**Comment by lbmaian** [comment]
> 
> 
> It looks like a future C# version will be able to express the `ldftn` opcode: [Function Pointers](https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md)

Fascinating, although it doesn't look like it would handle this particular use case: creating a delegate from a non-static property getter. The proposed address-of-function `&` syntax only works on static methods, results in a function pointer rather than a delegate (unless I'm missing some way to convert function pointers to delegates there), and function pointers, besides being the wrong type, are called with the calli instruction rather than call/callvirt instruction.

> The decompiler pipeline is extensible and contributions are always welcome. :) You could add an `IAstTransform` to the C# AST transforms pipeline that detects the `new Func<T>(arg, __ldftn(...))` pattern and transforms it to what you think might be appropriate. I will gladly answer any questions about the transformation pipeline.
> 
> The core members are busy enough with keeping up with the new language features Microsoft is putting out every few months.

Thanks, I may consider doing so in the future!
