### ISSUE TITLE
StackOverflow in TranslatedExpression.ConvertTo

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1747]
It's something new in `5.0.1.5145` and not happen with `5.0.0.5124`.

See `ClassLibrary1.C.Method()` attached below, when `ClassLibrary2` is not found, the cast from `bool` to `Nullable<bool>` lead to an StackOverflow in 5.0.1
[issue1747.zip](https://github.com/icsharpcode/ILSpy/files/3707594/issue1747.zip)

Add an simpler case, and decompile `C.Method(bool)`
```cs
    public class C
    {
        public static void Method(bool a) => Method((bool?)a);
        public static void Method(bool? a) { }
    }
```

**Comment by siegfriedpammer** [comment]
@dgrunwald could you please take a look at this? I suspect, this is a side-effect of the recent changes in 1d95eb60a276754511a68e39a5bd0368b51401ba
