### ISSUE TITLE
ILSpy context menu opens in VS for C# projects, how can I enable it for our projects

### ISSUE THREAD

**Issue by RobertvanderHulst** [icsharpcode/ILSpy#1753]
I have installed the ILSpy addin. It works nicely for C# projects. What do I need to do to make the addin work with our project type ?

**Comment by christophwille** [comment]
What do you mean by "our project type"?

**Comment by RobertvanderHulst** [comment]
Christoph, We have developed our own .Net development language with a compiler and VS integration. Our project files have the ".xsproj" extension.
See www.xsharp.info, if you register there you can download a free version.
The source for the project system is at https://github.com/X-Sharp/XSharpPublic/tree/master/VisualStudio

**Comment by RobertvanderHulst** [comment]
Any news ?

**Comment by christophwille** [comment]
eg for open output in ILSpy, this gets called: https://github.com/icsharpcode/ILSpy/blob/e104f4ce6e924fde9a800d336a8542df4324dd2f/ILSpy.AddIn/Commands/ProjectItemForILSpy.cs#L29

Unless it is Roslyn, it won't work.

**Comment by RobertvanderHulst** [comment]
Ok, Thanks for the info.
