### ISSUE TITLE
Input var name conflicting with framework class name

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1758]
ILSpy version 6.0.0.5288-alpha1

Example:

```
	internal void SetColor(SchemeColorValues **Color**, decimal Tint, decimal Transparency)
		{
			IsRgbColorModelHex = false;
			SchemeColor = Color;
			int num = 1;
			switch (Color)
			{
			case SchemeColorValues.Text1:
			case SchemeColorValues.Dark1:
				num = 1;
				break;
			case SchemeColorValues.Background1:
			case SchemeColorValues.Light1:
				num = 0;
				break;
			case SchemeColorValues.Text2:
			case SchemeColorValues.Dark2:
				num = 3;
				break;
			case SchemeColorValues.Background2:
			case SchemeColorValues.Light2:
				num = 2;
				break;
			case SchemeColorValues.PhColor:
				num = 4;
				break;
			case SchemeColorValues.Accent1:
				num = 4;
				break;
			case SchemeColorValues.Accent2:
				num = 5;
				break;
			case SchemeColorValues.Accent3:
				num = 6;
				break;
			case SchemeColorValues.Accent4:
				num = 7;
				break;
			case SchemeColorValues.Accent5:
				num = 8;
				break;
			case SchemeColorValues.Accent6:
				num = 9;
				break;
			case SchemeColorValues.Hyperlink:
				num = 10;
				break;
			case SchemeColorValues.FollowedHyperlink:
				num = 11;
				break;
			}
			this.Tint = Tint;
			this.Transparency = Transparency;
			int num2 = num;
			if (num2 >= 0 && num2 < listThemeColors.Count)
			{
				clrDisplayColor = **Color.FromArgb**(255, listThemeColors[num2]);
				if (this.Tint != 0m)
				{
					clrDisplayColor = SLTool.ToColor(clrDisplayColor, (double)Tint);
				}
			}
		}
```

issue:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SchemeColorValues' does not contain a definition for 'FromArgb' and no accessible extension method 'FromArgb' accepting a first argument of type 'SchemeColorValues' could be found (are you missing a using directive or an assembly reference?)	
C:\Temp\---ColorTransform.cs	212	Active

Expectation:  resolve such conflicts by adding full framework class name path
or  
option 2
rename input arg into smth else

**Comment by siegfriedpammer** [comment]
@dgrunwald we might have to feed the names of local variables into the resolver used by `FullyQualifyAmbiguousTypeNamesVisitor`. Currently the resolver does not receive this information. `ExpressionBuilder` uses some sort of hack with `bool HidesVariableWithName(string)` to work around other conflicts in overload resolution.

**Comment by dgrunwald** [comment]
For parameters, `LookupSimpleNameOrTypeName()` already looks at `(CurrentMember as IParameterizedMember)?.Parameters`, so we'd just need to use a resolver with the appropriate context.

For local variables, the visitor would have to call `CSharpResolver.AddVariable()`.

**Comment by siegfriedpammer** [comment]
Looking at the code, the context should already be the correct one, however I haven't debugged it yet.
