### ISSUE TITLE
Poor decompilation of compound assignments on floats

### ISSUE THREAD

**Issue by Chicken-Bones** [icsharpcode/ILSpy#1764]
The following pretty print test case fails similarly on all configurations (None/Optimize/UseRoslyn)
```cs
public void InlineArrayPostIndexer()
{
	float[] array = new float[1];
	Console.WriteLine(array[0]++);
}
```
Sample output:
```cs
public void InlineArrayPostIndexer()
{
	float[] array = new float[1];
	ref float reference = ref array[0];
	float value;
	reference = (value = reference) + 1f;
	Console.WriteLine(value);
}
```

Going to investigate and attempt PR. Any advice appreciated

**Comment by Chicken-Bones** [comment]
So I see, noted, I just assumed compound assignment as they're in the same test class. Do you have a Slack/Discord?

**Comment by siegfriedpammer** [comment]
> Do you have a Slack/Discord?

Would our gitter be sufficient?
