### ISSUE TITLE
DisplayClass shoud be kept if there is reference left

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1768]
Tested with master/5.0.0.4793-preview2

1. Decompile the below code with C#1.0(both lambda and local function is disabled), and expected init and assign to the DisplayClass should be kept, and this used to work for `version <= 5.0.0.4793-preview2`.
2. But there is another question, what's the expected behavior when decompile the below code with C#6.0(lambda enabled but local function disabled, or manually change options with lambda disabled but local function enabled). It never used to work. Should there is an seperated option to disable it.

#### Code:
```cs
	public void M(object x)
	{
		if (x == null)
		{
			Console.WriteLine(x);
			return;
		}
		Action z = () => { Console.WriteLine("z: " + x); };
		z.Invoke();
		z.Invoke();
		void ZZ()
		{
			Console.WriteLine("ZZ: " + x);
		}
		ZZ();
	}
```
#### Excepted:
```cs
	public void M(object x)
	{
		<>c__DisplayClass0_0 <>c__DisplayClass0_ = new <>c__DisplayClass0_0();
		<>c__DisplayClass0_.x = x;
		if (<>c__DisplayClass0_.x == null)
		{
			Console.WriteLine(<>c__DisplayClass0_.x);
			return;
		}
		Action action = new Action(<>c__DisplayClass0_.<M>b__0);
		action();
		action();
		<>c__DisplayClass0_.<M>g__ZZ|1();
	}
```

#### Actual
```cs
	public void M(object x)
	{
		if (x == null)
		{
			Console.WriteLine(x);
			return;
		}
		<>c__DisplayClass0_0 <>c__DisplayClass0_;//<--never inited.
		Action action = new Action(<>c__DisplayClass0_.<M>b__0);
		action();
		action();
		<>c__DisplayClass0_.<M>g__ZZ|1();
	}
```

**Comment by siegfriedpammer** [comment]
This should be fixed on the 5.0.x branch. Will soon be merged to master.
