### ISSUE TITLE
Problem with GetSymbol on node of array type

### ISSUE THREAD

**Issue by lambertlb** [icsharpcode/ILSpy#1771]
On AstNodes GetSymbol seems to have a problem with arrays. Following is and example with a field declaration.
```
class Program
{
    bool[] boolArray;
    bool testBool;
    public static int Main(String[] args)
    {
        return (0);
    }
}
```

Following is the code where I detect the issue.
```
public void VisitFieldDeclaration(FieldDeclaration fieldDeclaration)
{
    var sym = fieldDeclaration.ReturnType.GetSymbol();
    Debug.Assert(sym != null);
}
```

sym doesn't appear to be null for any other types I have tried, just arrays. Is this a bug? If not is there another way that i can get information about the type of variable? I am doing some analysis and want to get information about Class Fields, method Parameters and Method local variables so want to get at more in-depth information while using the visitor pattern. GetSymbol seems to do that for everything but arrays.

**Comment by siegfriedpammer** [comment]
The reason is that `ArrayType` is an `IType` but not an `ISymbol`. You will have to work with `GetResolveResult().Type`.

> GetSymbol seems to do that for everything but arrays.

Generic types, pointer types and a few others should behave the same.

Hope this helps!
