### ISSUE TITLE
CheckVariant likely combinatorial explosion problem

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1775]
I've just encountered a problem with a debug build, where runtime seems to be `O(n^m)`. It has so far spent 45 _minutes_ checking invariants, for an assembly that otherwise decompiles in seconds.
(I'll see if I can produce a repro once this part is done)

The problem is, I believe, a combinatorial explosion. I am currently watching a _recursive_ call stack at least 100 levels deep for IL.Transforms.BlockILTransform.VisitBlock.

I think I have an idea for a solution to this (very real) problem.

We wouldn't want to modify any existing classes, especially for a debug-only check. But what about adding a set, only used for `[Conditional("DEBUG")]`, to place already visited and verified blocks in. That way this `O(n^m)` could be reduced to something like `O(n*log(m))` (or even smaller) I believe.

Does it sound sane?

**Comment by dgrunwald** [comment]
> I am currently watching a recursive call stack at least 100 levels deep for IL.Transforms.BlockILTransform.VisitBlock.

That's normal, this is recursion over the dominator tree which can be deeply nested for large methods with lots of linear control flow. But that's not a performance problem.

Caching `CheckInvariant` is problematic since some invariants are non-local; it would be difficult to ensure that invalid states are discovered in the same transform that introduced them.
However, I'm not aware of any case with exponential time.
AFAIK the worst-case decompiler run time is O(n³) in both debug and release builds (though the invariant checking in debug builds makes it more likely to actually hit the worst case).

What's the top-level `CheckInvariant` call? The one in StatementTransform.cs?

**Comment by tamlin-mike** [comment]
I was running ILSpy under a debugger for the 45+ minutes runtime (total time ended up over 80 minutes). Not debugging it I have been unable to repro that long runtime. Under sampling profiler it now took "just" over 10 minutes.

Problematic assembly is a generated XmlSerializer with approx. 170 small types, and a total of 1400 fields in the reader. Problematic case seems to be the generated XmlSerializationReader. While the writer .cs is over 4MB and took over a minute to produce while running under debugger, the reader is... over 12MB!

Well that surely explains a thing or two.

A top-level `CheckInvariant` I got when breaking to the debugger was in `IL.Block`, not in StatementTransform.cs. It contains one single instruction (in `Instructions`), an `if`. The Block itself was only 7 bytes. Following parent chain there's a lot of nested `if`'s.

Instead of guessing, or trying to find the problematic spot in the debugger, I'll run a profiling pass, and look at the generated reader decompiled code.

[some time passes...]

Oh my sweet lord! That generated XmlSerializationReader is... is... horrible! I don't think I could create a code-generator that bad even if I tried! The amount of repetetive methods, both in the reader and writer, only differing in what field (singular) they access is... excessive.

One of the methods I stumbled across in the reader is over 1k LOC, decompiled, and contains nested if's from here to sunday. ILSpy thankfully sorts them out into same-level "else if" construct, but semantically they surely are nested so deep it's absurd.

No wonder ILSpy is struggling.

Having seen what I have now seen (and can unfortunately never un-see), I'm not only starting to question the hope for humanity, but also if this issue shouldn't simply be closed with something like "User error. Hit user to continue".

Some profiling data, for completeness, in order of CPU time consumed by method alone, skipping methods not displaying notable difference between self and self+children:

| self% | +children% | name | note |
| --- | --- | --- | --- |
| 7 | 9 | IL.ILInstruction::IsDescendantOf | most CPU time of any single method |
| 5 | 55 | IL.ILInstruction::CheckInvariant | expected |
| 3.72 | 15 | IL.ILInstruction+<get_Descendants>d__112::MoveNext | might be something to look into |
| 3.3 | 10.6 | IL.ILInstruction+ChildrenEnumerator::get_Current |  ditto |
| 2 | 6.3 | IL.ILInstruction+ChildrenEnumerator::.ctor | could # of enumerators be reduced? |
| 1.6 | 21 | IL.CallInstruction::CheckInvariant | possible/likely part of the run time observed |
| 0.87 | 12.31 | IL.LdLoc::CheckInvariant | this seems interesting |
| 0.81 | 13.24 | System.Linq.Enumerable+<OfTypeIterator>d__95`1[System.__Canon].MoveNext() ||


Apologies for the noise.
