### ISSUE TITLE
Crashing at startup

### ISSUE THREAD

**Issue by SamueleLorefice** [icsharpcode/ILSpy#1778]
Whener I open it, just crashes after a few seconds with no log/information about the error whatsoever.

**Comment by christophwille** [comment]
Which version of ILSpy is this, where did you obtain it from?

**Comment by dgrunwald** [comment]
"just crashes" meaning what exactly? (Windows Error Reporting?)
Can you start ILSpy in a debugger to get a stack trace? (e.g. Visual Studio: `File > Open > Project`, select ILSpy.exe, then start in debugger)

**Comment by christophwille** [comment]
Also, you might be able to find an Application Error (Source) event log entry (in Event Viewer / Windows Logs / Application)

**Comment by SamueleLorefice** [comment]
> "just crashes" meaning what exactly? (Windows Error Reporting?)

The application basically closes itself few moments after opening it.
> Can you start ILSpy in a debugger to get a stack trace? (e.g. Visual Studio: `File > Open > Project`, select ILSpy.exe, then start in debugger)

Well, unfortunately attaching visual studio to the application doesn't make any error show up. (just like running it normally). The output log only has 1 line about the error:

`The program '[12556] ILSpy.exe' ended with the code -1073741795 (0xc000001d) 'Illegal Instruction'.
The program '[12556] ILSpy.exe: Program trace' ended with the code 0 (0x0).`

All the other lines are the dlls being loaded. Nothing else.

> Which version of ILSpy is this, where did you obtain it from?

Latest release and previus release from the github releases.

If you need any other info, I'm here.

**Comment by SamueleLorefice** [comment]
Googling around for that error I see it's related to SSE instructions and AMD processors. However my machine is running over an i7 6700HQ and Windows 10 Home.

**Comment by tamlin-mike** [comment]
Overclocked? Bad RAM? Malware? Bad antivirus? File corruption of some .NET runtime file?

If you start it using `devenv /debugexe ilspy.exe`, do you still only get that short info, or do you get a more usable stacktrace?

**Comment by SamueleLorefice** [comment]
Not overclocked. RAM is fine, never had a malware since 10 years and I do not use any antivirus (apart from common sense). Starting from command line gives the same error and no stack trace.

**Comment by tamlin-mike** [comment]
Baffling. If you load it for debugging in VS, but force VS to treat it as a "native" before running it, you should be able to get a stack trace.

**Comment by SamueleLorefice** [comment]
Maybe I'm missing some options in my visual studio configuration. I already disabled just my code. Any other thing I should enable/disable?
[This](https://streamable.com/cj6ik) is what happens when I run ILSpy in visual studio.

**Comment by tamlin-mike** [comment]
In the solution view, right click ILSpy, select Properties. Change Debugger Type from Auto to Native.

**Comment by SamueleLorefice** [comment]
Strangely enough, ilspy doesn't crash anymore.
