### ISSUE TITLE
TransformDisplayClassUsage: Support methods without .locals init

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1781]
Tested with master(6.0.0.5337-alpha1)

I don't have an minimum reproduce with C# code, but can be tested with Assemblies from netcoreapp3.0. Seems need an method without `.locals init`, and `variable.HasInitialValue` is false here.
https://github.com/icsharpcode/ILSpy/blob/9bb2ea872cf8731ff92227c98cf6e4b7886b549c/ICSharpCode.Decompiler/IL/Transforms/TransformDisplayClassUsage.cs#L125

`[System.Linq]System.Collections.Generic.LargeArrayBuilder<T>.CopyTo(CopyPosition position, T[] array, int arrayIndex, int count)`(netcoreapp3.0)
and
`[System.Text.Json]System.Text.Json.JsonNode.Parse(...)`(***netcoreapp5.0 ONLY***)

**Comment by siegfriedpammer** [comment]
Seems like in .NET 5.0 C# will no longer emit `.locals init` by default.
