### ISSUE TITLE
async not detected on .NET Core 3

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1788]
https://gist.github.com/jaredpar/de522f659963bf50e0fd9f24d3b00768

compile as netcoreapp3.0

**Comment by dgrunwald** [comment]
The problem here is that `builder` is a reference type; the async transform currently expects it to the TaskBuilder to be value type.

**Comment by dgrunwald** [comment]
Also, `awaiter` being a reference type means there's an unexpected `castclass` instruction on the code path that resumes after an `await`.
