### ISSUE TITLE
How to determine if member access is static

### ISSUE THREAD

**Issue by lambertlb** [icsharpcode/ILSpy#1793]
When visiting a Member reference expression how do I tell if the member is static or not? Both the IType and the symbol come back null on the member name. I see no other properties that would have useful information.
```
public void VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression)
{
    IType type = memberReferenceExpression.MemberNameToken.GetResolveResult().Type;
    var sym = memberReferenceExpression.MemberNameToken.GetSymbol() as IEntity;
}
```

**Comment by dgrunwald** [comment]
The annotation is usually set on the expression node itself, not on the individual tokens.
Try `(memberReferenceExpression.GetSymbol() as IMember)?.IsStatic`.

**Comment by lambertlb** [comment]
Both return null.
```
public void VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression)
{
    IType type = memberReferenceExpression.GetResolveResult().Type;
    var sym = memberReferenceExpression.GetSymbol() as IMember;
}
```
In this particular instance my code is analyzing the following expression.
```
Program.LocalAssert (!flag)
```
There is a call to a static LocalAssert method on a class called Program. My program is trying to use data about the memberReferenceExpression to analyze this and figure out if LocalAssert is a static method or instance. If instance it will need to further figure out if is virtual or not. If there was a way to get at the raw ILInstruction and therefor the raw Type I could use that data to figure things out.

**Comment by dgrunwald** [comment]
For calls the concrete symbol isn't really known until a particular overload is chosen, so you'll find the symbol on the `InvocationExpression`.

**Comment by lambertlb** [comment]
It seems to be working when i do the following although it is a bit klunky. Parent is the InvocationExpression.
```
public void VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression)
{
    IType type = memberReferenceExpression.GetResolveResult().Type;
    if (type.Kind == TypeKind.Unknown)
    {
        type = memberReferenceExpression.Parent.GetResolveResult().Type;
    }
    var sym = memberReferenceExpression.GetSymbol() as IEntity;
    if (sym == null)
    {
        sym = memberReferenceExpression.Parent.GetSymbol() as IEntity;
    }
}
```

**Comment by siegfriedpammer** [comment]
Would it be possible for you to upload your current implementation somewhere so one of us can take a look and provide better suggestions? Thank you!

**Comment by siegfriedpammer** [comment]
Closing due to no feedback for three months.
