### ISSUE TITLE
Extra incorrect cast to double for uint -> float promotion

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1794]
ver: 9bb2ea87

compilable repro
```
class C {
public static void fn1(uint val, int div) { float f = val / (float)div; }
public static void fn2(uint val, int div) { float f = (float)val / div; }
public static void fn3(uint val, int div) { float f = (float)(double)val / (float)div; }
public static void fn4(uint val, int div) { float f = (float)(double)val / div; }
}
```

1&2 produces same IL. 3&4 ditto (duh).

Decompiled, however, 1&2 becomes exactly the same as 3&4,

`float num = (float)(double)val / (float)div;`

This is not only redundant, it can probably produce observable difference.

It seems the bug could be simple - a missing check if one of the terms is `r4` as opposed to `r8`, or simply a missing u32 -> float path. Fingers crossed it's that simple.

**Comment by dgrunwald** [comment]
> This is not only redundant, it can probably produce observable difference.

While double-rounding can do that in general, the conversion `uint`->`double` is always lossless so there should be no observable difference possible in your case. But `ulong`->`float` may be problematic. Would be interesting to figure out a test case that shows the difference.

**Comment by tamlin-mike** [comment]
I was more worried r8->r4 could employ some rounding rule different from u32->r4, depending on runtime, platform and even CPU.

However, as the following example displays (checking IL first to make sure it really is different), that seems to not be the case for Microsoft, Windows and neither x86 nor "x64" (AMD64). The JIT could however also play a role in this.
```
#define DEBUG
class C /* runtime test for u32->r8->r4 always producing same result as u32->r4 */ {
  static void Main()
  {
    for (uint i = 1<<23; i !=0; ++i) { // IEEE-754 `float`, a.k.a. r4, have 23 bits mantissa
      float f = (float)i;
      double d = (double)i;
      System.Diagnostics.Debug.Assert(f == (float)d);
    }
  }
}
```
This could be an indication u64->r4 could also produce same result as u64->r8->r4, but I wouldn't want to be the one putting it to the test with code like this. :-)

I still claim the decompiled output is wrong for cases 1&2 though, as there is no u32->r8 in that code, yet ILSpy introduces that extra cast.

**Comment by dgrunwald** [comment]
A test program like yours starting at (1L<<53) doesn't take long to find the first counter-example: 
`i=9007199791611905; (float)i=9.0072E+15; (double)i=9007199791611904; (float)(double)i=9.007199E+15`

**Comment by tamlin-mike** [comment]
Sweet! Maybe my specific case wasn't something to worry about, but it was sure neat to get confirmation there are indeed dragons in these waters.

**Comment by dgrunwald** [comment]
Test case:
```
		static void Issue1794()
		{
			Console.WriteLine("CastToFloat:");
			Console.WriteLine(CastToFloat(9007199791611905).ToString("r"));
		}

		static float CastToFloat(ulong val)
		{
			return (float)val;
		}
```
Test Results (without the fix):
![image](https://user-images.githubusercontent.com/243140/68509212-b422e580-0270-11ea-8cc7-5772e61c4e70.png)

The test fails when the original code (compiled with the given settings) produces a different result than the decompiled+recompiled code (again using the same compiler).
ILSpy produces the wrong `(float)(double)val` cast in all cases, but only some combinations of compiler+runtime actually allow observing the difference. I'm lucky that my test project happened to be the Roslyn (not optimized)+32 bits.

**Comment by dgrunwald** [comment]
On 64-bit runtimes, even the direct cast produces the wrong result!
In fact, on 64-bit runtimes, there is a difference between converting `ulong->float` and `long->float`:
```
> (float)9007199791611905 == (float)9007199791611905U
false
> ulong original_integer = 9007199791611905;
> float directly_converted_to_float_64_bit_runtime = (float)original_integer;
> float directly_converted_to_float_32_bit_runtime = 9.0072E+15f;
> directly_converted_to_float_32_bit_runtime == directly_converted_to_float_64_bit_runtime
false
> // convert back to integer to accurately measure the conversion error:
> (long)directly_converted_to_float_64_bit_runtime - (long)original_integer
-536870913
> (long)directly_converted_to_float_32_bit_runtime - (long)original_integer
536870911
// directly_converted_to_float_32_bit_runtime was more accurate!
```

It turns out that the IL code for a direct conversion *always* rounds twice (with all compilers):
```
    IL_0000: ldarg.0
    IL_0001: conv.r.un
    IL_0002: conv.r4
    IL_0003: ret
```
On the x86 .NET runtime, this rounds `ulong`->`float80`->`float`
On 64-bit runtimes, this rounds `ulong`->`double`->`float`

This is because IL lacks a `conv.r4.un` opcode: the opcodes with specific float sizes always interpret the input as signed.
So yeah, even though float rounding is well-specified in IEEE 754, programming languages always manage to mess this up in practice.

ILSpy currently interpret the `conv.r.un` as a conversion to `double`, hence the `(float)(double)val` cast. This is what actually happens on 64-bit machines! The x86 runtime manages to always round correctly, as an 80-bit float has 63 bits of mantissa, which is just enough to accurately represent every `ulong`.

ILSpy's stack analysis currently uses two floating-point types (`F4` and `F8`), it looks like we'd need a third floating-point type to accurately model the `conv.r.un` result on x86.

**Comment by tamlin-mike** [comment]
Amazing how such a seemingly small issue can lead to such large results - very interesting results.

> ILSpy currently interpret the `conv.r.un` as a conversion to `double`

Eureka! That explains it! It also verifies my suspicion that it could be even CPU-dependent. It's still probably also runtime and JIT dependent. You can turn down FPU internal precision from 80 to 64 bits, and isn't SSE strictly 32/64 bits internally?

> it looks like we'd need a third floating-point type

As r4 and r8 are the concrete types, but realization has now struck that `r` is really a third, internal representation, it looks like it. As a bonus, that would "automagically" take care of the redundant cast to double starting this issue. :-)
