### ISSUE TITLE
Saved resx kept open

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1799]
Explicitly saving a resource as resx, ILSpy seems to keep it open, preventing e.g. renaming the file. Need to exit ILSpy to get control over the file.

Could be it's an unhandled case (that could still be made to work with a properly placed `using` for the file), since the resource is empy. Don't ask. :-)

**Comment by siegfriedpammer** [comment]
I just tried this with System.dll. Saved `System.resources` by selecting the tree node and then using the Save button and could not reproduce this behavior.

Can you reproduce this problem using `System.dll`? If so, please post the exact steps. Thank you!

If this only happens in one specific case, please provide the assembly. (If necessary, you can use a private channel.)

Thank you very much!

**Comment by tamlin-mike** [comment]
My System.dll's `System.resources` contains a bunch (many, many screenful) of strings. I discovered the problem with a resource that was empty. I don't know how it got into the assembly in that state, but it's at least not obfuscated. The resx is not generated by ILSpy during production of a full project, this state can only be reached by explicitly selecting the node and use its "Save" button.

Saved as `.resources` it's 180 bytes,
```
000000: ce ca ef be 01 00 00 00 91 00 00 00 6c 53 79 73 ............lSys
000010: 74 65 6d 2e 52 65 73 6f 75 72 63 65 73 2e 52 65 tem.Resources.Re
000020: 73 6f 75 72 63 65 52 65 61 64 65 72 2c 20 6d 73 sourceReader, ms
000030: 63 6f 72 6c 69 62 2c 20 56 65 72 73 69 6f 6e 3d corlib, Version=
000040: 34 2e 30 2e 30 2e 30 2c 20 43 75 6c 74 75 72 65 4.0.0.0, Culture
000050: 3d 6e 65 75 74 72 61 6c 2c 20 50 75 62 6c 69 63 =neutral, Public
000060: 4b 65 79 54 6f 6b 65 6e 3d 62 37 37 61 35 63 35 KeyToken=b77a5c5
000070: 36 31 39 33 34 65 30 38 39 23 53 79 73 74 65 6d 61934e089#System
000080: 2e 52 65 73 6f 75 72 63 65 73 2e 52 75 6e 74 69 .Resources.Runti
000090: 6d 65 52 65 73 6f 75 72 63 65 53 65 74 02 00 00 meResourceSet...
0000a0: 00 00 00 00 00 00 00 00 00 50 41 44 50 41 44 50 .........PADPADP
[stray bytes]
```
Saving it as ".resources" did not exhibit the problem. Switching `Save as type` to `.resx`, followed by saving it, the generated resx remains impossible to rename until ILSpy is shut down.

If this turns out to not be enough info to repro, just holler and you'll get a copy of the dll.

**Comment by siegfriedpammer** [comment]
I selected `.resx` as file type... if you could send me a copy of the dll, that would be very nice! Thanks!
