### ISSUE TITLE
Problem with polymorphism

### ISSUE THREAD

**Issue by pepri** [icsharpcode/ILSpy#180]
Original code:

``` cs
class Class
{
  public Class(object a) { }
  public Class(params object[] a) : this((object)a) { }
}
```

Disassembled code (note the missing explicit conversion, which results in an error: Constructor cannot call itself):

``` cs
using System;
internal class Class
{
  public Class(object a) { }
  public Class(params object[] a) : this(a) { }
}
```

.NET Reflector has this issue too.

ILSpy version: 1.0.0.822

**Comment by dgrunwald** [comment]
The newdecompiler branch fixes this issue.
