### ISSUE TITLE
Modernize Assembly Lists

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1800]
Goal: Make the assembly lists feature a first-class citizen in the UI.

Proposal:

 Add a new group to the toolbar, in between Reload & Show Internal types. Add a dropdown to easily switch between assembly lists, and add a button (Edit/Manage style icon) that opens a (redesigned) Open Assembly List dialog.

 Redesign the Open Assembly List dialog to Manage Assembly List dialog (File menu item would need to reflect textual change too). Proposed redesign:

![manageasmlists](https://user-images.githubusercontent.com/344208/69006320-d500d000-092d-11ea-99f6-84fd18dcbd1b.png)

 A simple listbox will do compared to ListView as used today. Create -> New, Clone is a new command (clones an existing list with ability to set new name). OK/Cancel -> Close. Selecting a list is no longer intended in this dialog, that's what the dropdown in the toolbar is for.

Additionally: Should we update the in-built asm lists? Those are quite old... 

Alternative approach: put this in the Options dialog as a separate tab? Maybe the best option.

**Comment by donid** [comment]
Just a few days ago I thought: it would be really nice to be able to switch the currently active list from the toolbar. I sometimes need the huge list of all Visual Studio assemblies for plugin development, but when I don't need them they clutter up the tree and I am too lazy to go to the menu.
So, big thumbs up from me!

**Comment by siegfriedpammer** [comment]
While we're at it, we could probably add a few features, that implement #611 and #770. Something like an `AssemblyGroupNode` might be useful, however, a few open questions:

1. Should such an "assembly group" impact assembly resolution? (or should it just be a UI thing?)
I would say, yes. This would make it visually clear, which assemblies are used in a decompilation process.
2. Should it be possible to have an assembly in multiple groups? If 1 is implemented, this is necessary.
3. Do we want "nested groups"? - I would say, no, this is too complex.

@christophwille what do you think? Should I move these ideas to #770?

**Comment by christophwille** [comment]
My preference would be to keep it simple - one list active at any one time. Because groups and their resolution behavior might confuse casual users (point in case: which group is an assembly added to that you d&d or pass via the cmd line).

**Comment by tamlin-mike** [comment]
> nested groups

This indeed seems like too complex, and possibly also of questionable utility. But while on the subject, something I'd like to see is the ability to tuck away resolved (or even explicitly loaded, whether by cmd-line or UI) assemblies inside one or more grouping nodes in the UI.

Having to scroll through page up and page down of Microsoft.This and System.That (or UnityEngine.ManyManyMany for the game-decompilation crowd) is getting tedious very fast, and really hurts overview.

To stay away from nested grouping (but allow it one level deep), it could probably be good to be able to select a group of such assemblies, in the current node list, and get an option to "Place in Existing Group", or "Create new Group".

One important use I can see for such a feature is to have different versions of an assembly (where assemby version has been left at default 1.0.0.0 for all version) and get a more immediate view of what assembly you are actually looking at.

I'm also in favor of such lists affecting assembly resolution - they should take precedence. Other resolved assemblies would probably best be displayed as it behaves today, to give a clear indication of what was not already included.

I'd also expect groups (and their content) to be persistent, and in a text format so you can f.ex. mass-edit filesystem paths.

> (point in case: which group is an assembly added to that you d&d or pass via the cmd line).

IMHO none. They would be added top-level, like they are today. Automagically placing such assemblies in groups would indeed be confusing.
