### ISSUE TITLE
How to tell when accessing property

### ISSUE THREAD

**Issue by lambertlb** [icsharpcode/ILSpy#1807]
How can i tell when VisitMemberReferenceExpression is accessing a property as Follows?
```
public void VisitMemberReferenceExpression(MemberReferenceExpression memberReferenceExpression)
{
}

The memberReferenceExpression is "{dateTime1dArray.Length}"
```
The reference expression is accessing the Length property on an array. I have tried getting the Symbol and the IType on various parts of the expression like the Target and the Parent but can't seem to find anything to identify the MemberNameToken as a property. Can you please tell me how to figure out if the MemberNameToken is a Property?

**Comment by dgrunwald** [comment]
In IL, getting the length of an array has its own opcode: `ldlen`
So there's no metadata token referring to a field or property.

**Comment by siegfriedpammer** [comment]
I have added a MemberResolveResult referring to `System.Array.Length` / `System.Array.LongLength`, if the `System.Array` type is available. `memberReferenceExpression.GetSymbol()` should now return the correct info.

Thank you for reporting this!
