### ISSUE TITLE
Recursive decompile through command line

### ISSUE THREAD

**Issue by Pl0414141** [icsharpcode/ILSpy#1808]
Hi,

Is there a way to decompile files using the command line recursively?

Thank you

**Comment by christophwille** [comment]
What are you trying to achieve?

**Comment by Pl0414141** [comment]
@christophwille i would like automate the process of decompilation when i need decompile multiple .dll and .exe files.

At the moment, i can use ilspy with reflexil one by one binary to decompile but do not exists an option to decompile multiple files via command or option

**Comment by christophwille** [comment]
Did you try https://www.nuget.org/packages/ilspycmd/ (docs at https://github.com/icsharpcode/ILSpy/tree/master/ICSharpCode.Decompiler.Console)

**Comment by Pl0414141** [comment]
Thanks! it is just as i need!
