### ISSUE TITLE
Docking: Should switching the tab also change selection in tree view?

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1814]
Referencing the screen recording from #1812 - when opening a new tab for Cmdlet, it doesn't navigate the tree view. Also on switching tabs back and forth it doesn't.

When navigating inside a document (clicking a hyperlink) we do reflect the change in the tree view. It should also be reflected on tab change I think.

**Comment by siegfriedpammer** [comment]
Yes, I think it should.
