### ISSUE TITLE
Tooltips: use Segoe for summary text (as in tree)

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1819]
Switch away from serif'd font.

**Comment by siegfriedpammer** [comment]
Trying different fonts:

**Original (WPF default = Georgia):**
![image](https://user-images.githubusercontent.com/344204/69647120-39780980-1069-11ea-8560-d7fee2dde1c0.png)

**Serifless (Segoe UI):**
![image](https://user-images.githubusercontent.com/344204/69646933-e900ac00-1068-11ea-9336-1ca4aaeabe06.png)

**Monospace (Consolas):**
![image](https://user-images.githubusercontent.com/344204/69647269-747a3d00-1069-11ea-96f1-881a352eb91a.png)

**Comment by christophwille** [comment]
My preference is Segoe, and can I please see one screenshot without justification? I think that hampers readability quite a bit.

**Comment by siegfriedpammer** [comment]
**Segoe UI with TextAlignment.Left:**
![image](https://user-images.githubusercontent.com/344204/69647842-80b2ca00-106a-11ea-90d9-71d5b4404fae.png)
