### ISSUE TITLE
Interactive decompilation helper

### ISSUE THREAD

**Issue by pvasilek** [icsharpcode/ILSpy#1821]
Hello,

want add an option to rename entities (field, methods etc). Like "int a;" to "int totalCost;"
The simplest way would be wrap
	internal readonly MetadataReader metadata;
with own MetadataReader and override
	public string GetString(StringHandle handle);
Then store aliases in the companion project file withing the main module directory.

But the proposed implementation would break ILSpy architecture. Could you please advise the better way?

**Comment by siegfriedpammer** [comment]
See #209 and #731. We have decided in the past that this is out of for ILSpy. Also it would not work with  PDB generation and other features, so it is of limited use.
