### ISSUE TITLE
Wrap PDB reading in try/catch

### ISSUE THREAD

**Issue by pvasilek** [icsharpcode/ILSpy#1823]
If we have
Sample.dll
Sample.exe
Sample.pdb (for Sample.exe)

The IL decompilation for methods of Sample.dll will fail at debugInfo.GetSequencePoints() of PortableDebugInfoProvider.

The proposed solution is to add some verifier in ctor to raise an exception if wrong PDB which will be ignored. Or wrap methods in try/catch and return an empty list, for example.

**Comment by siegfriedpammer** [comment]
Can you please provide an example that demonstrates the issue? I am unable to create an example that crashes. At the moment ILSpy ignores any errors while reading symbols. Is this not what you want? Please be more specific, thank you!

**Comment by pvasilek** [comment]
Did not store the sample and can not reproduce the issue anymore.
