### ISSUE TITLE
ILSpy update error

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1831]
Step 1

![image](https://user-images.githubusercontent.com/765343/69899691-da6d0a00-1372-11ea-8b5d-d68ee9f41121.png)

Step 2:

![image](https://user-images.githubusercontent.com/765343/69899697-e35ddb80-1372-11ea-875b-9bce043f34e0.png)

Host OS: WIn7 SP1 x64

**Comment by siegfriedpammer** [comment]
I cannot reproduce this.

**Comment by christophwille** [comment]
The update URL that is being checked is https://ilspy.net/updates.xml - the only other thing in the code path is the (possible) system Web proxy that might interfere.

**Comment by greenozon** [comment]
I tried to understand the issue using network sniffer from MS, 
I saw some alert sent by server:

![image](https://user-images.githubusercontent.com/765343/69916092-24cbb500-145f-11ea-85c6-c22361fe424f.png)

this page has nice description of TLS as well as Alert protocol

http://blog.fourthbit.com/2014/12/23/traffic-analysis-of-an-ssl-slash-tls-session/

**Comment by greenozon** [comment]
TLS Alert bytes:
02, 46:
FATAL                          2    0x02
PROTOCOL_VERSION              70    0x46

**Comment by greenozon** [comment]
I"m not using any system proxy

**Comment by christophwille** [comment]
Our http code is as simple as it can get in .NET - and we cannot reproduce your problem on our machines.

**Comment by greenozon** [comment]
OK, I"ll find the update code in C# and try to debug it in a test proj
then feedback

**Comment by greenozon** [comment]
Found updater code
created small test proj

Found interesting detail!
![image](https://user-images.githubusercontent.com/765343/69920966-88250980-1496-11ea-9d81-8ac2672965c4.png)

.net 4.8 - error
.net 4.7.2 - error
.net 4.6.2 and lower - OK!

**Comment by greenozon** [comment]
Finally found the explanation - Win7 is becoming old and very old OS...

https://github.com/dotnet/docs/issues/4675


this code works when added before WebClient

 ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;

but.. thats a big big holywar and looks like noone from MS/.NET is going to fix it,  but letting it die gracefully.

**Comment by christophwille** [comment]
Well, unless MS changes their mind, Win7 will be out of (mainstream) support by mid-January, see https://support.microsoft.com/en-us/help/4057281/windows-7-support-will-end-on-january-14-2020

"Enforcing" TLS 1.2 with ServicePointManager - what would be the problem of that workaround?

**Comment by greenozon** [comment]
The problem is that by putting exact  Tls12 version you are automatically limiting the new releases (eg upcoming Tls13 or even newer...
I'm not pushing for any actions, this is expected graceful (happy) end of W7 OS :)
Also there are other options to enable Tls12 (eg from OS registry, etc)
but it requires manual  work... etc

Hope that someone else will grep in issues and will find this info useful
Closing it for hte moment.
