### ISSUE TITLE
CSharpDecompiler.DecompileWholeModuleAsSingleFile() name confusing

### ISSUE THREAD

**Issue by Piedone** [icsharpcode/ILSpy#1833]
I'd suggest renaming `CSharpDecompiler.DecompileWholeModuleAsSingleFile()` to `DecompileWholeModuleAsSingleSyntaxTree()` as in my understanding it's not really doing anything with a single file. The documentation on the method reinforces this: "Decompiles the whole module into a single syntax tree.".

Am I missing something?

**Comment by dgrunwald** [comment]
Well if you think about the compiler's input, each syntax tree is a file.
Roslyn went with `SyntaxTrees` in the compilation; but ILSpy is based on NRefactory which used `Files` for the same thing.

**Comment by Piedone** [comment]
Hmm OK, I see, so "AsSingleFile" refers to the input, not the output. Knowing the context now makes it clear and my `DecompileWholeModuleAsSingleSyntaxTree` suggestion is wrong.

I'm not a native English speaker but for me, this wording is still strange and initially, I dismissed this method since I didn't want to receive a file. However, I don't really have a better suggestion, so if you'd like then please close this issue.
