### ISSUE TITLE
Maybe some verify is needed for KnownType?

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1839]
It's an special edge case found when do some test for #1835, and maybe never happen in real world.
Sence `void` and `System.Void` is different in both IL and C#, it's possible to define an type with the same name without broken program. 

1. The type system of ILSpy become dirty when `enum System.Void` is defined.
https://sharplab.io/#v2:CYLg1APgAgTAjAWAFADsCGBbApgZwA5oDGWABFIkgN7Im1kDMJWKArhiQGoD2AlsJQF9kQpFEawSAYRLUkdBiQAqATzykALnBIBeEutVYuAMwAUUACwBKANw06YpQb0wdeg8ZPc+Nu7V8KLEgBZE0sZfxF5By9gYJhQnQA+EmAsIzQWABt1WyQBIA===
```cs
using System;
namespace System
{
    public enum Void{}
}
public class C {
    public Type t1 = typeof(Void);
    public Type t2 = typeof(void);
    public void M() {
    }
    internal Void M1() => default;
}
```
> Maybe need to reset `KnownTypeCode` if typeKind not match in MetadataTypeDefinition.ctor(and only change `TypeKind.Struct` to `TypeKind.Void` if match), and check `KnownTypeCode` in KnownTypeCache.SearchType;
>I don't think it's possible to show the difference between them when they have the same TypeKind(userdefined struct System.Void{})

2. And stackoverflow if `enum System.Int32 : int` is defined.
```cs
namespace System
{
public enum Int32 : int{}
}
```
> Don't know how to make an fix for that. The stackoverflow happen before everything is return. The enum have the same name as its underlying type.

loop between:
https://github.com/icsharpcode/ILSpy/blob/b75c2521939aea391acda7b660707fe98ce676be/ICSharpCode.Decompiler/TypeSystem/Implementation/MetadataTypeDefinition.cs#L103
```cs
ICSharpCode.Decompiler.TypeSystem.Implementation.MetadataTypeDefinition.MetadataTypeDefinition
ICSharpCode.Decompiler.TypeSystem.MetadataModule.GetDefinition
ICSharpCode.Decompiler.TypeSystem.MetadataModule.GetTypeDefinition
ICSharpCode.Decompiler.TypeSystem.Implementation.KnownTypeCache.SearchType
ICSharpCode.Decompiler.TypeSystem.Implementation.KnownTypeCache.FindType
ICSharpCode.Decompiler.TypeSystem.Implementation.SimpleCompilation.FindType

```

**Comment by siegfriedpammer** [comment]
Not sure how we want to deal with this. Looking at the warning emitted by the compiler, I think we could fix this by using the assembly qualified name for types that have keywords.

```
warning CS0436: The type 'Void' in '_' conflicts with the imported type 'void' in 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Using the type defined in '_'.
```

**Comment by dgrunwald** [comment]
> I think we could fix this by using the assembly qualified name for types that have keywords.

What assembly qualified name? There's no standard for name of the corlib, every run-time can have its own.
I don't know what the C# compiler does, I guess it prefers types in referenced assemblies over the builtin ones? It's certainly possible to define your own `Int32` that gets used for `int` by the C# compiler if you don't reference mscorlib.

**Comment by dgrunwald** [comment]
Unless someone has a real-world use-case for this, I think this should be closed as Won't Fix.

**Comment by yyjdelete** [comment]
Feel free to close this.
