### ISSUE TITLE
YieldReturnDecompiler doesn't set MoveNextMethod

### ISSUE THREAD

**Issue by shimonmagal** [icsharpcode/ILSpy#1844]
Regarding YieldReturnDecompiler .cs:
https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/IL/ControlFlow/YieldReturnDecompiler.cs#L134

**MoveNextMethod prop is never set for ILFunction function.**

Details:
Even though there is a moveNextFunction calculated, the ILFunction (function)'s MoveNextMethod prop is never set.

I temporarily patched it. I opened a pr for it:
https://github.com/icsharpcode/ILSpy/pull/1843
But I don't think it is necessarily the best solution for the issue.
I'd be very appreciative if you could fix it correctly / merge the pr if you think it is ok.

Either way, I need the MoveNextMethod property to be set since currently,  this line doesn't work for method with yield-return (since MoveNextMethod is null):
https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/DebugInfo/DebugInfoGenerator.cs#L158

**Comment by siegfriedpammer** [comment]
Fixed in #1843
