### ISSUE TITLE
NullReferenceException in SequencePointBuilder.AddToSequencePoint for stackalloc

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1851]
Tested with master.

Choose `IL with C#` or save pdb for assembly with the below code
`inst.Parent` is null

```cs
    public unsafe void M(void* p) { }
    public unsafe void ZZZ()
    {
        int* p = stackalloc int[1];
        M(p);
    }
```

**Comment by siegfriedpammer** [comment]
Triage: The reason for this exception is: `PointerArithmeticOffset.Detect` which sometimes creates new ILAst instructions representing the detected values. These are not part of any tree, thus `Parent == null`. I think the generated C# AST should still contain the instructions that match the original code.
