### ISSUE TITLE
Move Project NuGet Feed for Master Branch Builds?

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1856]
Currently, we have a project feed (https://ci.appveyor.com/nuget/ilspy-masterfeed) that pushes ICSharpCode.Decompiler.nupkg on master builds:

https://github.com/icsharpcode/ILSpy/blob/master/appveyor.yml#L13

This means it is tied to AppVeyor builds - we could move that to Azure DevOps or even GitHub Packages.

However, we do not have statistics on usage - is anyone actually using this on a regular basis? (automated builds that use non-nuget.org packages) Because moving something that nobody needs/uses is pointless.

**Comment by christophwille** [comment]
Azure DevOps: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml

**Comment by Piedone** [comment]
I actually use the nightly now to get some pre-release configs. This doesn't mean much but a nightly feed is useful in general, please don't remove it :).

**Comment by siegfriedpammer** [comment]
@christophwille how do we resolve this? Can it be closed?

**Comment by christophwille** [comment]
I haven't looked into Azure DevOps feeds yet. As soon as we drop AppVeyor the feed would be gone.

**Comment by christophwille** [comment]
Instead of tacking it onto Azure DevOps we should look into moving the build over to GH Actions (and use the Packages feature there).

**Comment by christophwille** [comment]
We are now publishing to https://github.com/icsharpcode/ILSpy/packages/547741 but seems to my knowledge that GH package repo at least atm still requires AuthN (no anon access)

**Comment by christophwille** [comment]
https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#about-scopes-and-permissions-for-package-registries

We will keep using this "as is" (provided by GitHub) - maybe at some point anon access will be possible. Closing.
