### ISSUE TITLE
DisplayClass not removed

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#1858]
ILSpy version 6.0.0.5450-preview1

goto method DirectoryCopy()
you'll see something like

```
<>c__DisplayClass2_2 CS$<>8__locals0 = default(<>c__DisplayClass2_2);
....
```

https://www.sendspace.com/file/ol1dwq

**Comment by greenozon** [comment]
also method
private async void Check()

**Comment by dgrunwald** [comment]
Method DirectoryCopy is broken; there are code paths (e.g. `sourceDirName.Length > 260`) where the compiler-generated display class variable is accessed without ever being initialized --> compiler-generated code throws `NullReferenceException`.
That should never happen for compiler-generated display class variables. ILSpy needs to emit code that preserves the potential `NullReferenceException`, which means it needs to keep the display class around.
Possible a bug in whichever compiler was used to build this assembly?

`Check()` looks like something that we could fix in our transform.
