### ISSUE TITLE
Drag & Drop to Assembly tree does not work in certain cases

### ISSUE THREAD

**Issue by donid** [icsharpcode/ILSpy#1860]
When I drop a .dll-file from windows explorer in ILSpy it works fine, but when I try the same from the result list of File Locator 6.2, the cursor turns into a stop-sign and ILSpy shows a line as preview for the insertion point. When I release the mouse button, nothing happens...

I have done some debugging and found that in the failing scenario ILSPy sets _e.Effects = DragDropEffects.Move_ in _AssemblyListTreeNode.CanDrop_ (_e.AllowedEffects_ is _Copy | Link_) because _DataFormats.FileDrop_ is present. So I changed the line to _e.Effects = DragDropEffects.Link_ and it worked. This might not be the real solution, but since it is probably hard for you to reproduce this issue, this information hopefully helps you to determine what is going wrong here.

**Comment by siegfriedpammer** [comment]
Thank you for debugging and reporting this issue. I have added `Link` and `Copy` to the list of effects. However, note that all of these are handled the same by ILSpy.
