### ISSUE TITLE
string.Concat was not replaced into operators

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#1868]
ILSpy version: `ILSpy version 6.0.0.5462-preview1`
File: [CheatSheet.zip](https://github.com/icsharpcode/ILSpy/files/3982448/CheatSheet.zip)
Method: `CheatSheet.Menus.RecipeBrowserWindow.Update`
Source: https://github.com/JavidPack/CheatSheet/blob/master/Menus/RecipeBrowser.cs#L284-L303
Decompiled result:
```
if (selectedRecipe.anyIronBar && selectedRecipe.requiredItem[i].type == 22)
{
	Main.HoverItem.SetNameOverride(string.Concat(Lang.misc[37], " ", Lang.GetItemNameValue(22)));
}
else if (selectedRecipe.anyWood && selectedRecipe.requiredItem[i].type == 9)
{
	Main.HoverItem.SetNameOverride(string.Concat(Lang.misc[37], " ", Lang.GetItemNameValue(9)));
}
else if (selectedRecipe.anySand && selectedRecipe.requiredItem[i].type == 169)
{
	Main.HoverItem.SetNameOverride(string.Concat(Lang.misc[37], " ", Lang.GetItemNameValue(169)));
}
else if (selectedRecipe.anyFragment && selectedRecipe.requiredItem[i].type == 3458)
{
	Main.HoverItem.SetNameOverride(string.Concat(Lang.misc[37], " ", Lang.misc[51]));
}
else if (selectedRecipe.anyPressurePlate && selectedRecipe.requiredItem[i].type == 542)
{
	Main.HoverItem.SetNameOverride(string.Concat(Lang.misc[37], " ", Lang.misc[38]));
}
```

**Comment by dgrunwald** [comment]
What's the type of `Lang.misc`?
If it's a type that might have a custom `ToString()` method, then this is intentional: different versions of the C# compiler use a different evaluation order for string concatenation, and none of them correspond to the language spec: dotnet/roslyn#38641

To ensure ILSpy doesn't subtly change the semantics of the code during decompilation, we are restricted to only using `operator +` for string concatenation when all three different variants:
 * old C# compiler behavior (<VS2019.3)
 * new C# compiler behavior (>=VS2019.3)
 * and the language specification
agree on the evaluation order.

**Comment by sgkoishi** [comment]
The `Lang.misc` is `LocalizedText[]`, which implement both `explicit operator string` and `override string ToString()`.

In this case, no `ToString()` was called in that method. All items were converted to objects (`[mscorlib]System.String::Concat(object, object, object)`), and `Concat` call `ToString()` on each of them in order. 
I guess this is the old compiler behavior? The only way I can find on SharpLab to use `Concat(object, object, object)` is to manually call it.

**Comment by dgrunwald** [comment]
Yes, in this case the old compiler behavior was:
 * evaluate `Lang.misc[37]`
 * evaluate `Lang.misc[51]`
 * call `string.Concat(object, object, object)`, which calls `LocalizedString.ToString()` on the arguments from left to right
The new compiler behavior would be:
 * evaluate `Lang.misc[37]`
 * call `LocalizedString.ToString()` on that
 * evaluate `Lang.misc[51]`
 * call `LocalizedString.ToString()` on that
 * call `string.Concat(string, string, string)`

So if `LocalizedString.ToString()` has side-effects (e.g. a `Console.WriteLine`) and `Lang.misc[51]` also has an effect (e.g. throwing `IndexOutOfRangeException`), the overall program behavior might differ depending on the compiler version used. So ILSpy can't rely on `operator+` replicating the behavior o the input IL, and has to keep the explicit `string.Concat()` call around.
