### ISSUE TITLE
Why doesn't ILSpy support the ability to debug source code in the VS plug-in

### ISSUE THREAD

**Issue by gallop1** [icsharpcode/ILSpy#1876]
A long time ago I read on the Internet that it had this feature

**Comment by gallop1** [comment]
@siegfriedpammer
siegfriedpammer can you answer this question?thanks.

**Comment by christophwille** [comment]
ILSpy long ago had a debugger which was a sorts-of-clone of the SharpDevelop debugger. We removed it in favor of being able to "step into" decompiled inside SharpDevelop (and other issues). And it never came back to ILSpy (it would be cool to have a step into decompiled code in Visual Studio though...)
