### ISSUE TITLE
How to switch display language?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1878]
It seems ILSpy always show local language, when someone want to report some issue, he don't know the exact English words, and if he take a screenshot, others can't understand his language.

**Comment by siegfriedpammer** [comment]
Currently there are only two languages available: English (default) and Chinese, which was only added recently. ILSpy does not yet have an UI for changing the UI language.

**Comment by siegfriedpammer** [comment]
A possible workaround is to simply rename/remove the `zh-Hans/ILSpy.resources.dll` whenever you want to take a screenshot.
