### ISSUE TITLE
Provide a setting to desugar X? into Nullable<X> for value types

### ISSUE THREAD

**Issue by ashmind** [icsharpcode/ILSpy#1882]
For SharpLab purposes, I would like to present `int?` as `Nullable<int>`, e.g here:
https://sharplab.io/#v2:CYLg1APgAgTABAYTgbzgSwHYBcD8cBmA3HAL5A==

This is to teach people difference between nullable value and reference types.

Having some setting for it in `DecompilerSettings` would be great, and this could be a good default for `LanguageVersion.CSharp1` (though C# 1 didn't support generics either).

**Comment by siegfriedpammer** [comment]
@dgrunwald do you think this should be a separate option? Should I just wire it up to `DecompilerSettings.UseLiftedOperatorsForNullables`?
