### ISSUE TITLE
Main ILSpy GitHub page points to defunct web site

### ISSUE THREAD

**Issue by Zastai** [icsharpcode/ILSpy#1902]
At the top of [the main ILSpy GitHub page](https://github.com/icsharpcode/ILSpy), you have:
".NET Decompiler http://www.ilspy.net/".

However, that host name no longer functions; it should probably be https://ilspy.net instead (or given that that just redirects here, it could be dropped).

**Comment by christophwille** [comment]
Ah yes, TLS. I have removed the link because all information from the Web site was migrated to Wiki and other locations (for the moment).
