### ISSUE TITLE
SharpTreeView: Last First-Party Component Being Non-MIT

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1904]
As stated in https://github.com/icsharpcode/ILSpy/blob/master/doc/ILSpyAboutPage.txt SharpTreeView is the only remaining first-party component inside the repo that is not MIT licensed. 

History: Together with other parts (eg AvalonEdit) it was copied verbatim from SharpDevelop at the time ILSpy was started. AvalonEdit source code was later swapped for AvalonEdit NuGet, which was re-licensed to MIT (please see https://web.archive.org/web/20160718043001/http://community.sharpdevelop.net/blogs/christophwille/archive/2014/01/26/license-change-for-sharpdevelop-5.aspx for the relicensing of SharpDevelop to MIT). 

Options

* leave it is as is
* take the latest MIT-licensed code from the SharpDevelop repository and replace our LGPL copy with the new MIT-licensed copy. However, we have fixed stuff in our repo that never happened in SharpDevelop (new project format, bug fixes, et cetera).
* re-license our LGPL copy to MIT. See the history https://github.com/icsharpcode/ILSpy/commits/master/SharpTreeView - changes have been contributed by developers w/out JCA to the copied code. We'd need to get their ok.

**Comment by christophwille** [comment]
Regarding re-licensing (last bullet point): we could do something similar to https://github.com/icsharpcode/SharpZipLib/issues/103#issuecomment-206696820

**Comment by tamlin-mike** [comment]
> we have fixed stuff in our repo that never happened in SharpDevelop ( ... _bug fixes_ ...

Provided it's feasible, perhaps it could be beneficial to PR them upstream?

**Comment by siegfriedpammer** [comment]
At some point Daniel tried to merge the changes back to ILSpy, but I think it didn't really work out because there were too many differences. (I can no longer find the branch for this... was deleted some time ago, iirc)

**Comment by christophwille** [comment]
Yes the branch was deleted. For me, the question is mostly - do we want everything to be consistently one single license, or will we continue to be fine having one that is different (I personally don't think it creates too much friction, I only see accidential copying happening).

**Comment by christophwille** [comment]
We decided to cherry-pick from SharpDevelop and drop the sharptreeview branch (full merge). We will try to get in touch with all ILSpy SharpTreeView contributors to complete a re-license to MIT.

**Comment by christophwille** [comment]
As stated above, we have decided to try to re-license the SharpTreeView code to MIT (from LGPL) as-is in this repository. How does this work?

All contributors of SharpDevelop had JCAs (please see https://github.com/icsharpcode/SharpDevelop/wiki/Joining-the-Team) - and that's where SharpTreeView's original code came from. So @dgrunwald, @siegfriedpammer and @christophwille contributions in this repository are qualified for automatic relicensing (JCA).

Everyone else's contributions are listed at https://github.com/icsharpcode/ILSpy/commits/master/SharpTreeView. The aforementioned Wiki page had the patch clause (less than eight lines), but we want to be very conscious even though the main part of ILSpy always was MIT-licensed (maybe some contributors didn't even realize that SharpTreeView was different; additionally, the contributors listed here also contributed to the MIT part of ILSpy)

* @EdHarvey patch contributions https://github.com/icsharpcode/ILSpy/commit/1dfef669122aab402b5360bfdcd4124535a04e39#diff-b28f0beb21e22a328a92da15b3f2a51a, https://github.com/icsharpcode/ILSpy/commit/197a00d63661751671ffc875e055f62f40d0dda1#diff-b28f0beb21e22a328a92da15b3f2a51a and https://github.com/icsharpcode/ILSpy/commit/359d04b3b62346961bbb207983bbc25cef41afa3#diff-b28f0beb21e22a328a92da15b3f2a51a
* @sharwell various project file changes https://github.com/icsharpcode/ILSpy/commit/4908b129f82c58adb3662683c1067d32ead60bca#diff-b28f0beb21e22a328a92da15b3f2a51a, https://github.com/icsharpcode/ILSpy/commit/996e04075ea65c38e28898eefd922cf121c19502#diff-b28f0beb21e22a328a92da15b3f2a51a and https://github.com/icsharpcode/ILSpy/commit/ea930e025c047094fa68954ba52decf39264fc25#diff-b28f0beb21e22a328a92da15b3f2a51a
* @clairernovotny minor project file changes https://github.com/icsharpcode/ILSpy/commit/b88d8b047fdc92a3e2ad771de85d15d2e76ac323#diff-b28f0beb21e22a328a92da15b3f2a51a and https://github.com/icsharpcode/ILSpy/commit/8a31bf30bce4c9757b845c3b788a0dbca0e366dc#diff-b28f0beb21e22a328a92da15b3f2a51a

Yes, csproj-"only" changes are listed, but in a DevOps world build code counts too.

In the spirit of https://github.com/icsharpcode/SharpZipLib/issues/103#issuecomment-206696820 (SharpZipLib relicensing) I'd like to ask

@EdHarvey @sharwell @clairernovotny

to reply in this thread with 

I certify that I own, and have sufficient rights to contribute, all source code and related material for my contributions to SharpTreeView intended to be compiled or integrated with the source code for the ILSpy open source product (the "Contribution"). My Contribution is licensed under the MIT License.

Once those are on file, we can relicense - and I will lock this thread so no entries can be modified later on. 

Thanks.

**Comment by sharwell** [comment]
I do not agree with the idea that the changes listed above (commits 4908b12, 996e040, ea930e0) would result in me having a copyright claim to the project. My changes were volunteered without any strings (i.e. public domain).

**Comment by christophwille** [comment]
I never thought of wording it that way, but yes, if someone else wants to OK the license change that way - definitely. I really only copied the SharpZipLib paragraph because it was what I already had.

**Comment by clairernovotny** [comment]
certify that I own, and have sufficient rights to contribute, all source code and related material for my contributions to SharpTreeView intended to be compiled or integrated with the source code for the ILSpy open source product (the "Contribution"). My Contribution is licensed under the MIT License.

**Comment by clairernovotny** [comment]
@sharwell IANAL but unless it's otherwise stated and explicilty disclaimed, every author has copyright to their contributions automatically. That's why CLA bots are so important.

**Comment by EdHarvey** [comment]
I certify that I own, and have sufficient rights to contribute, all source code and related material for my contributions to SharpTreeView intended to be compiled or integrated with the source code for the ILSpy open source product (the "Contribution"). My Contribution is licensed under the MIT License.

**Comment by christophwille** [comment]
Thanks everyone, we can now switch SharpTreeView to MIT. See the additional issue for further action. I am now closing & locking this issue as previously announced.
