### ISSUE TITLE
Check parameter name when generating variable.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1907]
The ctor of Invoice(last line, from referenced dll) contains invalid parameter names, so ILSpy generate invalid variable names
The assembly I want to decompile doesn't contain invalid parameter names, only referenced dll which I don't want to decompile contain invalid parameter names
```
private Fpxx BlankWasteTaxCardZuoFei(object[] param)
{
	string   = param[0].ToString();
	string  2 = param[1].ToString();
	string  3 = param[2].ToString();
	string text = param[3].ToString();
	string  4 = param[4].ToString();
	string  5 = param[5].ToString();
	byte[] typeByte = Invoice.TypeByte;
	byte[] array = new byte[32];
	Array.Copy(typeByte, 0, array, 0, 32);
	byte[] array2 = new byte[16];
	Array.Copy(typeByte, 32, array2, 0, 16);
	byte[]  6 = AES_Crypt.Encrypt(Encoding.Unicode.GetBytes("KP" + DateTime.Now.ToString("F")), array, array2);
	Invoice.IsGfSqdFp_Static = false;
	Invoice invoice = new Invoice(Invoice.ParseFPLX( ),  2,  3, text,  4,  5,  6, "NEW76mmX177mm");
....................
```

**Comment by siegfriedpammer** [comment]
Thank you for reporting this issue. I have implemented a bugfix, but I would like to verify before pushing. Could you please provide an example DLL? Please send it to siegfried.pammer@gmail.com. Thank you!

**Comment by CreateAndInject** [comment]
[CheckParameter.zip](https://github.com/icsharpcode/ILSpy/files/4073336/CheckParameter.zip)

**Comment by siegfriedpammer** [comment]
Thank you very much!
