### ISSUE TITLE
.net core 3.1 self-contained Mode not working

### ISSUE THREAD

**Issue by cctvbnm1111** [icsharpcode/ILSpy#1909]
ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
 ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
System.Threading.Tasks.Task`1.InnerInvoke()
System.Threading.Tasks.Task.Execute()

**Comment by siegfriedpammer** [comment]
This is by design - there are two files: `<ProgramName>.exe` and `<ProgramName>.dll`. The `exe` file only contains an unmanaged setup code, which then calls into the managed `dll` file.

Hope this helps!
