### ISSUE TITLE
Linux build instructions, lack information

### ISSUE THREAD

**Issue by beef331** [icsharpcode/ILSpy#1917]
The linux build instructions lack saying you also need powershell core installed. So following them makes one think there is an issue with the .Csproj on linux.

**Comment by vvuk** [comment]
`/Users/vladv/proj/ilspy/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj(630,5): error MSB3073: The command "powershell -NoProfile -ExecutionPolicy Bypass -File BuildTools/update-assemblyinfo.ps1 Debug" exited with code 127.`

Note that the build tries to invoke `powershell`, but depending on how it's installed, on OSX/Linux it may be `pwsh` (e.g. going the `dotnet tool install --global PowerShell` route, you end up with `pwsh`.  Making an extra `powershell` symlink works, but should be unnecessary.)

**Comment by christophwille** [comment]
Could you please try PR #1941? We are considering moving to PS "Core" even on Windows (although it means one additional install step, at least atm)
