### ISSUE TITLE
Missing Sequence Points (In comparison with original PDB)

### ISSUE THREAD

**Issue by NitzanEgozy** [icsharpcode/ILSpy#1919]
This might relate to https://github.com/icsharpcode/ILSpy/issues/1245. In contrast to what was discussed at #1245 (for debug builds using NOP which is useless for release), I'm talking about Sequence Points that exist in the original PDB but are not generated by ILSpy. These points definitely have a meaning (in the example I'm attaching this is the catch block). They exist on Release builds as well.
In the example I'm attaching (a simple, small executable), we have this class
```
6 public class ClassA
7 {
8 	public void func1()
9 	{
10 		try
11 		{
12 			throw new Exception();
13 		}
14 		catch (Exception)
15 		{
16 		}
17 	}
18 }
```
```
.method public hidebysig instance void  func1() cil managed
{
  // Code size       10 (0xa)
  .maxstack  1
  .try
  {
    IL_0000:  newobj     instance void [System.Runtime]System.Exception::.ctor()
    IL_0005:  throw
  }  // end .try
  catch [System.Runtime]System.Exception 
  {
    IL_0006:  pop
    IL_0007:  leave.s    IL_0009
  }  // end handler
  IL_0009:  ret
} // end of method ClassA::func1
```
I'm using JetBrains dotPeek to parse portable PDBs (this happens with legacy PDBs as well). Parsing the relevant method's Sequence Points gives the following output:
The PDB from Visual Studio: `11000000 SP(IL_0000 1:12,5-12,27) SP(IL_0006 1:14,4-14,21) SP(IL_0007 1:16,4-16,5) SP(IL_0009 1:17,3-17,4) `
The PDB from ILSpy: `11000000 SP(IL_0000 1:12,5-12,27) HiddenSP(IL_0005) SP(IL_0007 1:17,3-17,4) `
Side by side we can see that ILSpy misses the sequence points for line 14.
This happens both when running ILSpy.exe and using the cmd endpoint.

The following project was used to simulate that:
https://github.com/NitzanEgozy/dotnet/tree/master/testers/ILSpy_MissingSequencePoints
The output directory contains the relevant outputs (MissingSequencePoints.dll, MissingSequencePoints.orig.pdb, MissingSequencePoints.ilspy.pdb).

I did a small research and found that SequencePointBuilder doesn't do anything with try-catch blocks, but I couldn't get it to properly discard the previous Sequence Point (which is hidden, so it conflicts if we just add another Sequence Point).
This might just be the pop that's missing the sequence point.

**Comment by siegfriedpammer** [comment]
My analysis shows that we will have to map the first instruction after the catch-block (at least) to the catch-block variable declaration. Not yet sure how exception filters interact with this.
