### ISSUE TITLE
PowerShell cmdlets: Progress reporting

### ISSUE THREAD

**Issue by jhoek** [icsharpcode/ILSpy#1923]
When decompiling a large project, it would be nice (and Powershell-like) to have some form of progress reporting. I guess for this to work, the code that does the actual decompilation should report its progress to the PowerShell cmdlets, which would then call WriteProgress to inform the user? Thanks for considering my suggestion!

**Comment by christophwille** [comment]
That would need progress reporting in the engine, and that isn't available @siegfriedpammer right? (eg IProgress<T>)

**Comment by siegfriedpammer** [comment]
No, we currently have no means of progress indication implemented in the engine.

I could imagine this only for `WholeProjectDecompiler`, which could report progress on the number of classes/files that need to be decompiled. Integrating fine-grained progress reporting in the decompiler pipeline would be a lot of work and I don't think that it would make sense for single entities.

**Comment by jhoek** [comment]
@siegfriedpammer OK, understood. Perhaps I'd be more interested in the current file path being written (when decompiling an entire project) than in the remaining number of files to decompile, but I'm not sure if that would make a difference? It's not too fine-grained, but it gives users a rough indication of progress and current activity.
