### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#1927]
[TestVB.zip](https://github.com/icsharpcode/ILSpy/files/4194672/TestVB.zip)

Create a VB.NET WinForm project `TestVB` by VS2010, view `TestVB.My.MyProject.MyForms.Create__Instance__`

**Comment by CreateAndInject** [comment]
Is this right?
ILSpy lastest:
```
private static T Create__Instance__<T>(T Instance) where T : Form, new()
{
	//Discarded unreachable code: IL_0094, IL_00ea, IL_0108, IL_0110
	if ((Instance == null || Instance.IsDisposed) ? true : false)
	{
		if (m_FormBeingCreated != null)
		{
			if (m_FormBeingCreated.ContainsKey(typeof(T)))
			{
				throw new InvalidOperationException(Utils.GetResourceString("WinForms_RecursiveFormCreate"));
			}
		}
		else
		{
			m_FormBeingCreated = new Hashtable();
		}
		m_FormBeingCreated.Add(typeof(T), null);
		TargetInvocationException ex;
		try
		{
			return new T();
		}
		catch (TargetInvocationException ex2) when (((Func<bool>)delegate
		{
			// Could not convert BlockContainer to single expression
			ProjectData.SetProjectError(ex = ex2);
			return ex.InnerException != null;
		}).Invoke())
		{
			string BetterMessage = Utils.GetResourceString("WinForms_SeeInnerException", ex.InnerException.Message);
			throw new InvalidOperationException(BetterMessage, ex.InnerException);
		}
		finally
		{
			m_FormBeingCreated.Remove(typeof(T));
		}
	}
	return Instance;
}
```

dnSpy:
```
private static T Create__Instance__<T>(T Instance) where T : Form, new()
{
	bool flag = Instance == null || Instance.IsDisposed;
	if (flag)
	{
		bool flag2 = MyProject.MyForms.m_FormBeingCreated != null;
		if (flag2)
		{
			bool flag3 = MyProject.MyForms.m_FormBeingCreated.ContainsKey(typeof(T));
			if (flag3)
			{
				throw new InvalidOperationException(Utils.GetResourceString("WinForms_RecursiveFormCreate", new string[0]));
			}
		}
		else
		{
			MyProject.MyForms.m_FormBeingCreated = new Hashtable();
		}
		MyProject.MyForms.m_FormBeingCreated.Add(typeof(T), null);
		try
		{
			return Activator.CreateInstance<T>();
		}
		catch (TargetInvocationException ex) when (ex.InnerException != null)
		{
			string BetterMessage = Utils.GetResourceString("WinForms_SeeInnerException", new string[]
			{
				ex.InnerException.Message
			});
			throw new InvalidOperationException(BetterMessage, ex.InnerException);
		}
		finally
		{
			MyProject.MyForms.m_FormBeingCreated.Remove(typeof(T));
		}
	}
	return Instance;
}
```

**Comment by siegfriedpammer** [comment]
Yes, this is correct. ILSpy shows the literal translation of Visual Basic .NET exception handling to C#.

dnSpy uses some extra transform, which removes certain pieces of code generated by the VB compiler. (See https://github.com/0xd4d/ILSpy/blob/ilspyv2/ICSharpCode.Decompiler/ILAst/ILAstOptimizer.cs#L951)

**Comment by siegfriedpammer** [comment]
@dgrunwald Do you think we should start removing calls to `ProjectData.SetProjectError`?

**Comment by siegfriedpammer** [comment]
see also #1092

**Comment by dgrunwald** [comment]
`ProjectData.SetProjectError` has observable side-effects; simply deleting the call like dnSpy does is incorrect and may cause the decompiled program to have different behavior than the original.
The ILSpy decompilation result is as close as you can get in C#.

**Comment by CreateAndInject** [comment]
There're at least 2 problems:
1. Use of unassigned local variable 'ex'
 `TargetInvocationException ex;` => `TargetInvocationException ex=null;`
2. Func<T> doesn't exist on .Net 2.0

By the way, why does my plugin export source like :
```
TargetInvocationException ex2;
					try
					{
						return new T();
					}
					catch (TargetInvocationException ex) when (((Func<bool>)delegate
```

The order of `ex2` and `ex` is different

**Comment by dgrunwald** [comment]
Hmm that unassigned local variable is a problem due to our approach of using a lambda to embed additional statements where C# expects an expression. Without the lambda, the C# compiler would realize that `ex2` is being initialized in the when-clause before the catch block can run.

How do you suppose we represent that code without using `Func<T>`?
The `when`-block has a call to a method returning `void`, but there's no good way of representing that in C# syntax. But simply ignoring the method call like dnSpy does also is not an option -- with a compiler error users can at least see that something weird is going on, and adjust the code if necessary.

**Comment by CreateAndInject** [comment]
I viewed mscorlib.dll (.net 2.0), there's no appropriate delegate `bool ()`, so ILSpy have to use `Func<T>`.

By the way, why does my plugin export source like :
```TargetInvocationException ex2; //ex ???
try
{
	return new T();
}
catch (TargetInvocationException ex) when (((Func<bool>)delegate
```
The order of ex2 and ex is different

**Comment by dgrunwald** [comment]
The order in which the names are assigned is based on the order in which the variables are used; not the order of declarations.
ILSpy puts the declaration as close to the first use as possible, so usually both orders end up matching; but here it's syntactically not possible to declare `ex2` after `ex`.

**Comment by CreateAndInject** [comment]
I get it : My plugin doesn't apply DebugInfoProvider
Thanks!
