### ISSUE TITLE
Unknown result type(might be due to invalid IL or missing references)

### ISSUE THREAD

**Issue by xiangxingxing** [icsharpcode/ILSpy#1931]
Hi! When using ILSpy to decompile my file , I've met the unexpected codes in the output shown like this 
//IL_0130: Unknown result type (might be due to invalid IL or missing references)
//IL_0136: Expected O, but got Unknown
//IL_0178: Unknown result type (might be due to invalid IL or missing references)
//IL_017e: Expected O, but got Unknown
//IL_01d8: Unknown result type (might be due to invalid IL or missing references)
//IL_01de: Expected O, but got Unknown
//IL_01de: Unknown result type (might be due to invalid IL or missing references)
//IL_01e8: Expected O, but got Unknown.
**Example file**
[AElf.Contracts.Configuration.dll.zip](https://github.com/icsharpcode/ILSpy/files/4218296/AElf.Contracts.Configuration.dll.zip)
Maybe you will see the unexpected codes in file named Acs1Reflection included in the folder Acs1.
 **Command I use**
"ilspycmd.exe -p AElf.Contracts.Configuration.dll -o output/" in windows.

I will appreciate it if you can help me!

**Comment by siegfriedpammer** [comment]
Yes, these comments are expected, in case there are references missing. You need to add all assemblies directly referenced by `AElf.Contracts.Configuration.dll` to ILSpy. If ILSpy is unable to automatically resolve the references, you can also add them manually to the assembly list.

Hope this helps, if you have further questions, please feel free to ask!

**Comment by xiangxingxing** [comment]
@siegfriedpammer The comments are gone when I add the assemblies as you suggested here. Many thanks!
