### ISSUE TITLE
6.x breaking changes for plugins

### ISSUE THREAD

**Issue by sailro** [icsharpcode/ILSpy#1932]
Investigating https://github.com/sailro/Reflexil/issues/145

Seems from 5.x to 6.x, all Top/Bottom Pane management methods were removed:
MainWindow : public void ShowInBottomPane(string title, object content)

What is the expected way to work with Plugins with 6.x ?

**Comment by siegfriedpammer** [comment]
What are your requirements? Currently the new docking solution added to ILSpy is not extensible, that is: you cannot add custom pads. I will have to add some extension points. However, the distinction between top and bottom panes will be difficult.

Currently the default positions for panes are kind of hard-coded see https://github.com/icsharpcode/ILSpy/blob/e2b10adc72260538ed52badc4233d95197cae1e7/ILSpy/Docking/DockLayoutSettings.cs#L31-L60

Programmatically initializing a docking layout is somewhat tricky and all the approaches I have seen so far broke ILSpy in one or another way.

Would be nice to work with you to create an extension API for this. Thank you!

**Comment by sailro** [comment]
Don't you think we can re-introduce this ShowInBottomPane(string title, object content), so it's super simple for migrating plugins, and do all the magic on the ILSpy side ?  :)

**Comment by sailro** [comment]
In my case it's super simple, I'm just using this legacy method here:

https://github.com/sailro/Reflexil/blob/ef5cc8c6fc3f2f8f441c9fbe2767adcc2a4b4bac/Plugins/Reflexil.ILSpy/Plugins/ILSpyPackage.cs#L176
