### ISSUE TITLE
Find actual method from reflection name of overloads

### ISSUE THREAD

**Issue by nmallick1** [icsharpcode/ILSpy#1938]
I have a few overload methods in the code that I am trying to decompile. The appear in the stack trace shows as follows
DecompilerTest.SampleLibrary.+<OverLoadFunc>d__5

I am using the following code to locate the typename 

string functionName = "DecompilerTest.SampleLibrary.+<OverLoadFunc>d__5";
var name = new FullTypeName(functionName);
ITypeDefinition typeInfo = decompiler.TypeSystem.MainModule.Compilation.FindType(name).GetDefinition();

typeInfo.Methods returns me a list of methods. One of which is what I am looking for as represented by reflection name DecompilerTest.SampleLibrary.+<OverLoadFunc>d__5

typeInfo.DeclaringTypeDefinition.Methods returns me a list of method names as was written in code i.e.. more than one occurrence of the method public void DecompilerTest.SampleLibrary.OverLoadFunc(parameterList) as there are overloads of this method.

Can I map the method represented by the reflection name to the actual method overload that it represents ? Basically I am trying to backtrack and identify what method was translated into what runtime code by the compiler.

**Comment by dgrunwald** [comment]
What exactly do you mean by "reflection name"?
For types there's `System.Type.FullName`. `ICSharpCode.Decompiler.TypeSystem.ReflectionHelper.ParseReflectionName()` can handle those.

But I'm not aware of any reflection equivalent for methods. If you have a `System.Reflection.MethodInfo` you can use it's `MetadataToken` to find the same member in the decompiler's type system.
Stack traces seem to have their own syntax. The syntax used by stack traces seems insufficient to always recover the overload:
```
namespace A { class C { }}
namespace B { class C { } }
class Program
{
    static void Overloaded(A.C c) { Console.WriteLine(Environment.StackTrace); }
    static void Overloaded(B.C c) { Console.WriteLine(Environment.StackTrace); }

    static void Main(string[] args)
    {
        Overloaded((A.C)null);
        Overloaded((B.C)null);
    }
}
```
Both stacks use `Program.Overloaded(C c)` despite referring to different overloads.

**Comment by nmallick1** [comment]
Thank you @dgrunwald. This helps.
