### ISSUE TITLE
Failure to extract embedded source code after decompilation due to PRN file system

### ISSUE THREAD

**Issue by jacdavis** [icsharpcode/ILSpy#1942]
A customer reported a failure to decompile to Visual Studio. Details of the investigation can be found here: https://developercommunity.visualstudio.com/content/problem/935023/decompile-while-debugging-unable-to-decompile-the.html.

Root cause is windows refusing to create a filename that was generated from a type name during decompilation. This filename ends in PRN.cs. Windows is not allowing a file of this name (regardless of extension or path) due to the printer file system. I suspect windows blocking this file name is actually a bug and I can repro the issue with both C# and C++ with filenames where the file is PRN regardless of extension or path. 

That said, the generation of source filenames from types may need to special case this and other paths (such as COM.cs).

**Comment by siegfriedpammer** [comment]
Thank you for reporting this!

> That said, the generation of source filenames from types may need to special case this and other paths (such as COM.cs).

Are there any special names we'd need to take care of other than the ones listed at https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?

**Comment by siegfriedpammer** [comment]
@jacdavis I have pushed a fix for this.

**Comment by siegfriedpammer** [comment]
I think this can be closed.

**Comment by jacdavis** [comment]
Your fix sounds good. For some reason, I didn't get any notification about your questions. Sorry about I didn't answer.

**Comment by siegfriedpammer** [comment]
Thank you for letting me know, no worries!
