### ISSUE TITLE
ref readonly Properties not decompiled correctly

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#1943]
Properties that return a ref readonly are displaying an IsReadOnlyAttribute instead of the readonly keyword.

Source:
```cs
class RefReadonlyPropertyTest
{
    int value;
    ref readonly int RefProperty => ref value;
}
```

Output:
```cs
class RefReadonlyPropertyTest
{
	[IsReadOnly]
	private ref int RefProperty => ref value;

	private int value;
}
```

**Comment by dgrunwald** [comment]
Wow, the `IsReadOnly` attribute is confusing.
For methods, `[IsReadOnly]` means the `this` pointer is read-only; and `[return:IsReadOnly]` means the ref-return is read-only.
For property, `[IsReadOnly]` means the ref-return is read-only; the status of the `this` pointer is only marked on the accessor methods.
