### ISSUE TITLE
Logic for return after finally blocks is changed.

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1946]
Tested with master.
Build the below code with Roslyn+Release(It doesn't happen when compiled with Debug)

### Orig Code
```cs
        public string Method2()
        {
            string obj = "1";
            try
            {
                obj = "2";
            }
            catch
            {
                obj = "3";
            }
            finally
            {
                obj = "4";
            }
            return obj;
        }
```

### Actual
NOTE: the return value changed from "4" to "2" now;
```cs
public string Method2()
{
	string obj2 = "1";
	try
	{
		return "2";
	}
	catch
	{
		return "3";
	}
	finally
	{
		obj2 = "4";
	}
}
```

**Comment by siegfriedpammer** [comment]
Analysis: The "Copy return block into try block" step inlines the return statement in release mode. We obviously should not do this in case there is a finally block accessing that same variable.
