### ISSUE TITLE
Open ILSpy by double click on DLL in File Explorer?

### ISSUE THREAD

**Issue by abatishchev** [icsharpcode/ILSpy#1952]
I'm having this option in dotPeek but I'd like to switch to ILSpy and don't see such option there. Is it available, feasible? How can I integrate it with File Explorer easier?

**Comment by abatishchev** [comment]
Wonderful, thanks much! When do you plan to publish Preview 3?

**Comment by abatishchev** [comment]
@siegfriedpammer The [release notes](https://github.com/icsharpcode/ILSpy/releases/tag/v6.0-preview3) mentioned this feature:

>Add "Open with ILSpy" entry to the Windows Explorer context menu on exe and dll files (via Options/Misc)

But I don't see this item in the options:

![image](https://user-images.githubusercontent.com/351644/81335835-1791a280-905d-11ea-85ba-d5254d87c285.png)

**Comment by siegfriedpammer** [comment]
Sorry, I realise that the wording of the release notes is a bit indirect. The option is hidden behind the button:

![image](https://user-images.githubusercontent.com/344204/81336097-fb1b5780-90a8-11ea-81da-44b55a8871b2.png)

Hope this helps!

**Comment by abatishchev** [comment]
Oh, right. I was looking at it and didn't see :) Thanks!
