### ISSUE TITLE
local functions with too low language level selected behaviour

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#1954]
If a local function is identified, it would be nice to get a warning (in interactive mode quite prominently, with a dialog box) if selected language level is too low, instead of generating invalid decompiled code.

Example:

```
// input
class C { int M() { int Mfn() { return 1; } return Mfn() + 1; } }

// output as C# 7.0 (OK)
internal class C
{
	private int M()
	{
		return Mfn() + 1;
		int Mfn()
		{
			return 1;
		}
	}
}

// output as C# 6.0 (uh-oh)
internal class C
{
	private int M()
	{
		return <M>g__Mfn|0_0() + 1;
	}

	[CompilerGenerated]
	internal static int <M>g__Mfn|0_0()
	{
		return 1;
	}
}
```

**Comment by siegfriedpammer** [comment]
I don't see how we could implement such a feature properly... it seems it would require us to try to decompile a given piece of code multiple times using different settings and comparing the output.

I think it is impossible to guess the language version as the decompiler pipeline is complex and there are many dependencies between each one of the stages in the pipeline.

Do you have a concrete suggestion on how such a feature could be implemented?

**Comment by dgrunwald** [comment]
Also, the code isn't invalid; it just uses names that are not valid in C#.
If you decompile to disk, we escape those identifiers to be valid C#; it's just in the UI that we show the original method names.

Maybe what you actually want is an option to turn on the name escaping in the UI?

**Comment by siegfriedpammer** [comment]
@tamlin-mike any comment?

**Comment by siegfriedpammer** [comment]
Closing... no feedback and there isn't really anything we could do to fix this.
