### ISSUE TITLE
Missing Project Type GUID property in .csproj after decompilation with -p flag

### ISSUE THREAD

**Issue by Techbrunch** [icsharpcode/ILSpy#1958]
I'm using ILSpy to decompile a DLL from a Xamarin App.

This is the command I'm running:
```
ilspycmd -p -o decompiled ***.dll -r .
```

The output generates a `.csproj` (`-p` flag) but I could not open it with Visual Studio 2019 for Mac.

I'm getting an error:

<img width="601" alt="Screenshot 2020-03-22 at 16 55 05" src="https://user-images.githubusercontent.com/1835765/77253902-ec462600-6c5d-11ea-988c-7e80b9c41b48.png">

```
Load operation failed.
Project does not support framework '.NETPortable,Version=v4.5,Profile=Profile111'
```

The problem appears to be that the `.csproj` XML is missing the Project Type GUID property:

```xml
<ProjectTypeGuids>{786C830F-07A1-408B-BD7F-6EE04809D6DB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
```
This one correspond to the "Portable Class Library" project type ([List of Visual Studio Project Type GUIDs](https://www.codeproject.com/Reference/720512/List-of-Visual-Studio-Project-Type-GUIDs))

Adding this property resolves the problem and the project can be openned.

Note that TargetFrameworkIdentifier, TargetFrameworkVersion and TargetFrameworkProfile are correctly specified in the `.csproj`:

```xml
    <TargetFrameworkIdentifier>.NETPortable</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile111</TargetFrameworkProfile>
```

**Comment by dgrunwald** [comment]
Thanks for the detailed bug report. This should be fixed now on master.
