### ISSUE TITLE
Ambiguous decompiled operator overload / type argument list

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#1959]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/pattern-matching#changes-to-syntactic-disambiguation
The generic type arguments may be ambiguous.
[Demo on SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZRwBsmALOgGIAUARgPbMA26jANJ6x4zACUhYgSTF0AXxFE01dAFl6g9DPxqJASwB2AF3TaArgFt0AXnQAGANwbiO/UeMxzV2+InEAIumCujbGzunsQA9KEMTugAPAYmMDx+AHzo9H4A/Om+goLBIXT09FGxTkKJ6Clp6JnZuWrSSA1yWF7IYhLNFLzs6MwADgCmAE4AhrrMQxX0PmwDAGa6PD5DmgDmABa6wh5E7fm660PMAO4GA6cAcsy6AJLGfbPGA3oDwACiAB4AxgN9uprMbTKPJEBodUhdFg9frDMYTGLTdCzBZLdArDZbNR7EIHI6nbTndBXW73R7PXSvT4/P4AoF1HZSZCSIA==)
```
        int num = 0;
        int num2 = 0;
        D d = null;
        F((num < num2), d > (d ?? d));
```
The last line was decompiled to `F(num < num2, d > (d ?? d));`(bracket missing), which `num2, d` will be considered as generic type arguments of `num`, and `d ?? d` as parameter.

**Comment by siegfriedpammer** [comment]
Should we always add extra parentheses around simple binary operator expressions in call argument lists (and tuple expressions?) with operator `<` and left operand identifier expression?

**Comment by dgrunwald** [comment]
Hmm this is tricky. It's also possible to construct cases where the `<` operator isn't directly contained in the argument list, e.g. `F(b ? true : num < num2, d > (d ?? d))`
This is really more of a lexical issue. We could detect the ambiguity in the token stream, but at that point it's too late to insert the opening parenthesis.
