### ISSUE TITLE
Search constant can not handle modes begins with number

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#1962]
Tested with `6.0.0.5614-preview2`(master)

Try search `0_NOT_EXISTS` or `"0_NOT_EXISTS"` with `Constant`, and found it actual get all reference to `0`(int).

After some try, I finally found `c:"0_NOT_EXISTS"`(without space after `:`) works, but there still no found an way to get use regex like `/0_NOT_EXISTS/`(also get int `0`).

**Comment by siegfriedpammer** [comment]
I think there's a misunderstanding here: The `LiteralSearchStrategy` parses the search text according to the C# lexing rules. It is meant to be used to search for magic values/constants used in method bodies or other members.

For example:
![image](https://user-images.githubusercontent.com/344204/78172202-f209eb80-7455-11ea-9ef8-0665633a0a77.png)

So, when parsing "0_NOT_EXISTS" the C# compiler/lexer reports CS1013 "Invalid number". Identifiers in C# may not start with a digit, hence the lexer interprets it as `0_` ('0' followed by a digit separator) which equals the literal value `0`of type `int` and then gives up with an error (which is ignored by ILSpy). It then continues to search for methods/members that use the literal value `0`, as you observed.

Note that the C# lexer used by ILSpy does not yet support digit separators and binary literals, these were added in C# 7, The lexer we use still works with the rules of C# 5.

Hope this helps!
