### ISSUE TITLE
[Question] Release ILSpy 6 Preview 3 sooner

### ISSUE THREAD

**Issue by MatanGreeny** [icsharpcode/ILSpy#1964]
Hi,

Any chance you will consider releasing v6 preview 3 as it currently stands and delay the remaining tasks to the next release? We are working on a project that will benefit from the fixes you introduced since the last release (notably #1937) and we're trying to stick with nuget gallery as the package repository for our nuget dependencies.

I will really appreciate your consideration,
Thanks.

**Comment by christophwille** [comment]
The release of preview3 is scheduled for post-April 14th (it will be really close to that date though).

**Comment by MatanGreeny** [comment]
Alright, Thanks! 😄
