### ISSUE TITLE
async state-machine struct fields not populated when decompiling to C# 7.0 or later (ILSpy 6.0.0.5559-preview2)

### ISSUE THREAD

**Issue by Jehoel** [icsharpcode/ILSpy#1970]
(I searched existing issues for "async" and "state machine" and didn't find anything relevant).

I'm disassembling a .NET Framework 4.x assembly (I don't have the C# source code) that is disassembled like this when using ILSpy 4.x or when using ILSpy `6.0.0.5559-preview2` (provided "**C# 6.0 / VS 2015**" is selected in the toolbar):

```
[AsyncStateMachine(typeof(<FoobarAsync>d__7<>))]
public static Task<T> FoobarAsync<T>( string x, int y, Baz z = null )
{
    <FoobarAsync>d__7<T> stateMachine = default(<FoobarAsync>d__7<T>);
    stateMachine.x = x;
    stateMachine.y = y;
    stateMachine.z = z;
    stateMachine.<>t__builder = AsyncTaskMethodBuilder<T>.Create();
    stateMachine.<>1__state = -1;
    AsyncTaskMethodBuilder<T> <>t__builder = stateMachine.<>t__builder;
    <>t__builder.Start(ref stateMachine);
    return stateMachine.<>t__builder.Task;
}
```

However when decompiled in ILSpy `6.0.0.5559-preview2` with C# 7.0 or later (7.0, 7.1, 7.2, 7.3, and 8.0) selected, the struct population is omitted entirely and replaced with `num = -1`, giving only this:

```
[AsyncStateMachine(typeof(<FoobarAsync>d__7<>))]
public static Task<T> FoobarAsync<T>( string x, int y, Baz z = null )
{
    AsyncTaskMethodBuilder<T> asyncTaskMethodBuilder = AsyncTaskMethodBuilder<T>.Create();
    int num = -1;
    AsyncTaskMethodBuilder<T> asyncTaskMethodBuilder2 = asyncTaskMethodBuilder;
    <FoobarAsync>d__7<T> stateMachine = default(<FoobarAsync>d__7<T>);
    asyncTaskMethodBuilder2.Start(ref stateMachine);
    return asyncTaskMethodBuilder.Task;
}
```

I have some non-default settings, though I don't think they're relevant:

* View > [x] "Show all types and members"
* View > Options > Decompiler > [x] "Always show enum member values"
* View > Options > Misc > [x] "Allow multiple instances"

**Comment by siegfriedpammer** [comment]
Could you please provide the assembly for me to look at? To me this looks like the async state machine transform does not recognize this pattern and the display-class usages transform destroys the state-machine assignments afterwards.

**Comment by Jehoel** [comment]
Sure - do you have an e-mail address or other way to securely send the file to you?

**Comment by siegfriedpammer** [comment]
please use siegfried.pammer@gmail.com

**Comment by Jehoel** [comment]
Got it - you can delete your reply now.

**Comment by Jehoel** [comment]
@siegfriedpammer Sorry for the delay, I'm having problems with GMail's attachment file scanner - I'll send you a OneDrive link.

**Comment by siegfriedpammer** [comment]
That's fine, no stress...

**Comment by Jehoel** [comment]
Email sent! Please let me know as soon as you've downloaded the file, thanks!
