### ISSUE TITLE
How to debug aspnetcore 3.1 with ilspy？

### ISSUE THREAD

**Issue by jackletter** [icsharpcode/ILSpy#1983]
Pdb file generated by ilspy cannot be loaded in vs2019, prompt: PDB does not match image error
![image](https://user-images.githubusercontent.com/15626065/79289229-510e3c80-7efb-11ea-958a-8553435d0a6e.png)

**Comment by christophwille** [comment]
@jacdavis any ideas?

**Comment by jackletter** [comment]
dnSpy
