### ISSUE TITLE
BamlDecompiler.Tests License Header Mess

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#1985]
Although this is "non-production" piece of ILSpy it is also the messiest re: license headers. See https://github.com/icsharpcode/ILSpy/pull/1984#issuecomment-615840060 for a history of the BAML decompiler.

We have a mix of no license headers, LGPL (most likely a template mistake by @siegfriedpammer), as well as (correctly) MIT (exactly one: Stub.cs)

Code exclusively from @siegfriedpammer:

Mocks/AvalonDock.cs: LGPL header
Cases/AttachedEvent.xaml
Cases/AttachedEvent.xaml.cs: LGPL header
AvalonDockBrushes.xaml
AvalonDockCommon.xaml
Dictionary1.xaml
EscapeSequence.xaml
Issue445.xaml, Issue775.xaml, Issue1435.xaml, Issue1546.xaml, Issue1547.xaml
Issue1547.xaml.cs: no license header
MyControl.xaml
MyControl.xaml.cs: LGPL license header
Resources.xaml
Resources.xaml.cs: LGPL license header
Simple.xaml
Simple.xaml.cs: LGPL license header
SimpleDictionary.xaml
SimpleNames.xaml
SimpleNames.xaml.cs: LGPL license header

Mixed authorship

BamlTestRunner.cs: LGPL header; @siegfriedpammer, @dgrunwald, plus test hookups from @vwoodzell
Cases/CustomControl.cs: no license header; @vwoodzell, one line by @SLaks (text constant)
Cases/MarkupExtension.xaml: @vwoodzell
Cases/NamespacePrefix.xaml: @vwoodzell
Cases/SimplePropertyElement.xaml: @vwoodzell

We at least should fix @siegfriedpammer files, when it comes to mixed authorship, we'd need to ask @vwoodzell for his OK to officially treat his contributions as MIT. In close semblance to https://github.com/icsharpcode/ILSpy/issues/1904#issuecomment-609363841 I'd like to ask @vwoodzell to reply in this thread with

I certify that I own, and have sufficient rights to contribute, all source code and related material for my contributions to BAML Decompiler Tests intended to be compiled or integrated with the source code for the ILSpy open source product (the "Contribution"). My Contribution is licensed under the MIT License.

Once that is on file, we can relicense - and I will lock this thread so no entries can be modified later on.

Thanks.

**Comment by vwoodzell** [comment]
Oh, absolutely.

I certify that I own, and have sufficient rights to contribute, all source code and related material for my contributions to BAML Decompiler Tests intended to be compiled or integrated with the source code for the ILSpy open source product (the "Contribution"). My Contribution is licensed under the MIT License.

**Comment by christophwille** [comment]
Thanks. Now we can relicense the whole thing (as usual @siegfriedpammer & @dgrunwald code is covered by the JCA)
