### ISSUE TITLE
Analyzer fails to find usages of a type when it is used as a type argument 

### ISSUE THREAD

**Issue by nvmkpk** [icsharpcode/ILSpy#1992]
I tried finding usages of `Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware`. It is used as a type argument in `Microsoft.AspNetCore.Builder.HostFilteringBuilderExtensions.UseHostFiltering` which is in the same assembly but analyzer finds none.

**Comment by nvmkpk** [comment]
When can I expect this fix to be available on VS extension marketplace?

**Comment by christophwille** [comment]
The VS Marketplace only receives stable releases. In the meantime you'd need to grab CI builds or releases from GH (this is going to be part of preview4, so CI builds atm)

**Comment by nvmkpk** [comment]
Yes, I understand that. I wanted to know if you have an estimated date for the stable release.
