### ISSUE TITLE
Question - UniversalAssemblyResolver magic?

### ISSUE THREAD

**Issue by daningalla** [icsharpcode/ILSpy#1997]
I copied a small test assembly to an isolated directory in my profile (win10). This assembly has a reference to a third party assembly which is not in any of the mscore/dotnet assembly folders or the GAC (.netcore, so I don't think this is applicable anyway). 
I then create PEFile and build a type system using the UniversalAssemblyResolver. When I drill into the type system for the small test assembly, I see the metadata loader has discovered, in its entirety, all of the types in the referenced assembly.

I can understand it finding mscorlib or BCL assemblies and discovering all of that metadata, but a third party assembly that only sits in my local .nuget package folder?

Thank you

**Comment by daningalla** [comment]
It would probably resolves any types available in the current AppDomain yes? If so, that's it.

**Comment by dgrunwald** [comment]
No, it doesn't look at the current AppDomain.
Check `typeSystem.ReferencedModules.Select(m => m.PEFile?.FileName)` to see where the assembly was found.

**Comment by daningalla** [comment]
Thank you
