### ISSUE TITLE
Compiler generated variables with weird names

### ISSUE THREAD

**Issue by GreenNBlacko** [icsharpcode/ILSpy#1999]
I'm trying to port unity visual novels to android and I've been getting issues with some scripts.. There's these weirdly named variable which have an compiler generated tag
![image](https://user-images.githubusercontent.com/45263750/80826907-b21c5c80-8beb-11ea-9d2f-48653533d013.png)
these names are throwing errors and I'm not completely sure if they will cause problems for the game itself

the assembly file:
[Assembly-CSharp.zip](https://github.com/icsharpcode/ILSpy/files/4565798/Assembly-CSharp.zip)
the faulty script is FileIOManagerBase

**Comment by dgrunwald** [comment]
ILSpy shows the original name from the metadata for these fields in the UI.
But if you save the assembly to disk, it should escape these names to avoid compiler errors.

**Comment by GreenNBlacko** [comment]
So I should just rename these variables and test if the code is still functional? Or is it supposed to rename them automatically?

**Comment by dgrunwald** [comment]
ILSpy should automatically rename these if you use File > Save.

**Comment by GreenNBlacko** [comment]
![image](https://user-images.githubusercontent.com/45263750/80834811-2231df00-8bfa-11ea-8da9-de3535b77799.png)
the variable names are still the same even after the method trying to save using `File > Save.`
I'll try renaming the variables manually and test the code for issues

**Comment by christophwille** [comment]
I can confirm that this behavior reproduces with 5712.

**Comment by siegfriedpammer** [comment]
I just tried this. These fields are used as backing fields for cached delegate initialization. The decompiler successfully manages to remove their uses (these are only used in the static constructor of the class), but they are not removed from the ILSpy tree view and the decompiled code for the reasons described in #1926.

@christophwille I cannot reproduce the escaping behavior:
![image](https://user-images.githubusercontent.com/344204/81107527-a72d3900-8f17-11ea-93e2-b70f6f1010bc.png)

Did you use the "Save code"-feature with csproj?

**Comment by christophwille** [comment]
I used the context menu in the tree view.
