### ISSUE TITLE
extension/package.json not found inside zip

### ISSUE THREAD

**Issue by TheGroundZero** [icsharpcode/ILSpy#2004]
I downloaded [ILSpy.AddIn_6.0.0.5671-preview3.vsix](https://github.com/icsharpcode/ILSpy/releases/download/v6.0-preview3/ILSpy.AddIn_6.0.0.5671-preview3.vsix) from the [Releases](https://github.com/icsharpcode/ILSpy/releases) page and tried to install it in VSCode using *Install from VSIX...*

However, I'm getting the error that extension.json or package.json is missing from the bundle.  
Opening the vsix file/archive in 7zip I indeed cannot find either file.

In the Marketplace, I can find ILSpy (icsharpcode.ilspy-vscode), but it's version 0.7.11 and marked as Preview.

What am I missing here?

![Install from VSIX](https://user-images.githubusercontent.com/2406013/81556433-90a93680-938a-11ea-86ae-27b45f8c45aa.png)

![error](https://user-images.githubusercontent.com/2406013/81556271-56d83000-938a-11ea-945a-b2c871394cd6.png)

![Marketplace](https://user-images.githubusercontent.com/2406013/81556648-f72e5480-938a-11ea-8943-64fdbe2f22db.png)

**Comment by siegfriedpammer** [comment]
The VSIX package cannot be used with vscode. It is for Visual Studio only. The vscode plugin is located  
[here](https://github.com/icsharpcode/ilspy-vscode/).

Hope this helps!
