### ISSUE TITLE
Some Debug Steps are not visible on UI due to its size

### ISSUE THREAD

**Issue by abatishchev** [icsharpcode/ILSpy#2006]
Version: ILSpy_binaries_6.0.0.5671-preview3

Expected behavior:

The items are auto-arranged into multiple rows based on the size of the menu

Actual behavior:

The items are rendered as-is and getting hidden or half-visible

Screenshots to illustrate the issue:

![image](https://user-images.githubusercontent.com/351644/81960443-d271f100-95c5-11ea-9d65-d7816a9a0b23.png)

![image](https://user-images.githubusercontent.com/351644/81960399-c25a1180-95c5-11ea-960f-3d9dfd34ae67.png)

![image](https://user-images.githubusercontent.com/351644/81960421-cbe37980-95c5-11ea-83a5-a9f41a94433a.png)

**Comment by dgrunwald** [comment]
This is internal debugging UI -> won't fix.
The ILAst view needs a big window size anyway to read the code without tons of horizontal scrolling.
