### ISSUE TITLE
Help -> About stopped working in Prview 3

### ISSUE THREAD

**Issue by abatishchev** [icsharpcode/ILSpy#2007]
Version: ILSpy_binaries_6.0.0.5671-preview3

Clicking at Help -> About in the top menu does nothing. Meanwhile other menus work fine though.

**Comment by siegfriedpammer** [comment]
Cannot reproduce this. Could you provide a screen gif of the bug?

**Comment by christophwille** [comment]
Additionally, can you still reproduce with the latest builds from the build server?

https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy_binaries.zip?branch=master&job=Configuration%3A+Release

**Comment by abatishchev** [comment]
Sorry, please please disregard, it's not ILSpy is bogus, it's me.
