### ISSUE TITLE
Can not run in offline mode

### ISSUE THREAD

**Issue by JinZhuXing** [icsharpcode/ILSpy#2009]
I can't run ILSpy in offline mode.
If I execute program, FileNotFound Exception occur.

Tested Version : 5.0.2.5153, 6.0.0.5671-Preview3

**Comment by siegfriedpammer** [comment]
Can you please check the properties of ILSpy.exe and other DLLs in the download: They might be blocked by Windows Defender after downloading. Can you check the "General" tab of the file properties, whether there is a button named "Unblock" at the bottom?

It would be very helpful for me to diagnose the issue, if you could post the file that was not found by ILSpy. Thank you very much!

**Comment by JinZhuXing** [comment]
![image](https://user-images.githubusercontent.com/15034343/82052741-bae25780-96ee-11ea-85ca-44dbf67ac69a.png)

**Comment by JinZhuXing** [comment]
Windows Defender is not running in the background.

**Comment by christophwille** [comment]
Could you please translate for us what is in the first line of the exception text after "System.IO.FileNotfoundException: ". Thanks.

**Comment by JinZhuXing** [comment]
无法找到指定文件 - Can not find appoint(selected) file.

**Comment by siegfriedpammer** [comment]
From the stack trace it looks like your system is missing a font file. However I have no idea, which one or why that would be the case, because I have never used a Chinese edition of Windows or WPF.

**Comment by christophwille** [comment]
You'd need to attach a debugger to ILSpy starting to see the full information on what font file might be missing. 

@maikebing could you please help us out if a Chinese-Chinese communication could get quicker results? Thanks. (maybe you even have an idea what is causing this)

**Comment by JinZhuXing** [comment]
OK, I'll check it.
If I find the missed font, I'll send you.
Thank you.

**Comment by christophwille** [comment]
@JinZhuXing did you get a chance to try to find out which font is missing for you?

**Comment by JinZhuXing** [comment]
I think this problem occurs only in Windows SandBox.
I am now finding the reason.

**Comment by siegfriedpammer** [comment]
@JinZhuXing were you able resolve the problem?

Can this be closed?

**Comment by JinZhuXing** [comment]
OK.
Thank you.
