### ISSUE TITLE
Create winget Package

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2012]
https://github.com/microsoft/winget-pkgs/tree/master/manifests

ICSharpCode/ILSpy should be the location. 

Edit: looks like this won't be doable atm because winget only supports installers. (maybe waiting it out for winget 3rd party repos support like choco is easier anyways because https://chocolatey.org/packages/ilspy)

Note: redirecting to the Windows store MSIX is not intended. We want to keep the local, no-installer experience (easy to drop addins).

**Comment by christophwille** [comment]
See https://github.com/microsoft/winget-cli/issues/140

**Comment by christophwille** [comment]
Well, winget is adding additional stores (such as the Microsoft Store): https://github.com/microsoft/winget-cli/releases/tag/v.0.2.2521-preview This might be a good-enough story to not repackage ILSpy yet again.

**Comment by weitzhandler** [comment]
Thank you for making all this research and your updates!
