### ISSUE TITLE
Add MMB shortcut to "Open in new tab" for tree view and links

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2019]
Any thoughts?

**Comment by riQQ** [comment]
Could you also add a binding for Middle Mouse Button for the same funnction. Users are already used to this, because browsers have been using this for a long time.

**Comment by siegfriedpammer** [comment]
So I just was reminded that `Shift+Click` means `extend selection`. I think we should go with: middle mouse button in the tree view and with Shift+Click + MMB on the links in the text view.
