### ISSUE TITLE
CSharpDecompiler fails on Xamarin dll

### ISSUE THREAD

**Issue by Doraku** [icsharpcode/ILSpy#2021]
Hello, I am using the ICSharpCode.Decompiler nuget package to read full types information from a target library in order to produce an api documentation, mixing it with the xml comment, and this has work flawlessly on my projects but it has recently come to my attention that the decompiler fails for Xamarin projects.
I have created a simple Android App (Xamarin), added a reference to the Xamarin.Forms nuget package and a dummy class:
```csharp
    /// <summary>
    /// dummy
    /// </summary>
    public class Dummy
    {
        /// <summary>
        /// dummy
        /// </summary>
        public Xamarin.Forms.Xaml.IMarkupExtension Extension;
    }
```
Creating the decompiler as such `new CSharpDecompiler(assemblyFilePath, new DecompilerSettings())` fails with this exception
>ICSharpCode.Decompiler.Metadata.AssemblyResolutionException: 'Failed to resolve assembly: 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

The Xamarin dependencies are not present in the output folder next to the library which I believe might be the problem but I am not sure if this is something that can be resolved by tinkering with the project configuration or a `IAssemblyResolver`.

Visual Studio 2019 Version 16.5.5
ICSharpCode.Decompiler Version 5.0.2.5153

**Comment by dgrunwald** [comment]
You don't need to implement `IAssemblyResolver` yourself -- if you create a `UniversalAssemblyResolver` instance, you can use `AddSearchDirectory` to register additional directories for the Xamarin dependencies.

Alternatively, you can also use `new DecompilerSettings { ThrowOnAssemblyResolveErrors = false }`, but that may cause code to be decompiled incorrectly if it's using types from the missing dependencies.

**Comment by Doraku** [comment]
>Alternatively, you can also use new DecompilerSettings { ThrowOnAssemblyResolveErrors = false }, but that may cause code to be decompiled incorrectly if it's using types from the missing dependencies.

Thanks I knew there was something like this but for some reason I didn't saw it when I looked at all the flags of DecompilerSettings. As I only need the name of the externe types this shouldn't cause any problem but I will keep in mind the UniversalAssemblyResolver solution if something else occurs 👍
