### ISSUE TITLE
'fixed' statements/pinning

### ISSUE THREAD

**Issue by LADSoft** [icsharpcode/ILSpy#2023]
ILSPY doesn't support fixed statements/pinning.  Dot peek figures out that if you store an address in a pinned local variable it is a candidate for a fixed statement, and also figures out the unpin statement that ends the sequence.   ILSPY finds these statements but doesn't recognize that a fixed statement is required there.

 Another issue is that DotPeek is able to figure out where an array is used (based on a multiply with the result of a compatable MSIL sizeof instruction.

Here is the IL file which you can compile to see the problems.   I think I got all the dependencies and also threw in a slightly modified version of the DotPeek output. 

[szip.zip](https://github.com/icsharpcode/ILSpy/files/4698766/szip.zip)

**Comment by dgrunwald** [comment]
I looked at `aa.bb.main` and ILSpy produces similar `fixed statements to those in `q.cs`.

Problems I can see:
 * ILSpy inserts casts in the style `fixed (sbyte* a_ = (sbyte*)(&L_64_66c1428b))` when the type of the pinned variable does not match the type of whatever is being pinned. This is not legal C#. DotPeek seems to work-around this problem by ignoring the type of the pinned variable and using the type of the initializer instead, we could do something similar. Or maybe we should use 
 * In some methods (e.g. `M_activatenext_66c1428b`), the detection of the pinned region fails. This results in the use of undeclared variables called `reference`. I haven't looked into why the pinned region detection fails yet.
 * I think the indexed pointer accesses have subtly different semantics from normal C# pointer accesses: the multiplication happens in 32-bits and thus has weird overflow behavior when indexing >4 GB arrays on a 64-bit .NET runtime. Normal C# pointer accesses don't have that overflow bug (they perform the `conv.i` before multiplying, not after). If the IL code doesn't have exactly the same behavior, we can't perform the transformation to `ptr[i]` syntax.

**Comment by dgrunwald** [comment]
Here's the control-flow graph for `M_activatenext_66c1428b`:
![Uploading M_activatenext_66c1428b.png…]()
Black edges are control-flow; green edges are dominance.

The pinned variable V_2 (pinning &mod.lastseen) is initialized in block IL_0000 and reset to 0 in block IL_00f7.
But that makes it possible to reach block IL_00f8 in both the pinned and unpinned states. Block IL_00f8 (the return instruction) would have to be both inside and outside the `fixed` statement. This is impossible, so ILSpy refuses to create a pinned region.
Looks like DotPeek solves this by duplicating the affected block.

**Comment by dgrunwald** [comment]
I think it makes sense to emit `fixed (__anontype_b76acefe_0002* ptr5 = &Unsafe.As<uint32_12, __anontype_b76acefe_0002>(ref mod.whatmod))` -- this would fit well with using `Unsafe.As` for arbitrary ref-conversions, instead of the current "use a pointer cast" approach (`ref *(newtype)&old_ref`) which 90% of the time results in a compiler-error.

Of course OCCIL should use a more appropriate type for the pinned locals to avoid these ugly casts.

**Comment by dgrunwald** [comment]
Fixed with 1f2d1660c8a5e and 35c405b9730378d94. Your assembly now decompiles+recompiled successfully, at least with the help of `System.Runtime.CompilerServices.Unsafe.dll`.
