### ISSUE TITLE
Invalid expression term 'ref' - bad code generated that was generated fine before

### ISSUE THREAD

**Issue by hansmbakker** [icsharpcode/ILSpy#2026]
I decompiled a program twice with probably different versions of ILSpy. Previously it decompiled fine, but the versions I tried today generate erroneous code (version 5 from the MS Store and version 6 preview 3 from github).

The application I am trying to decompile is located in [this archive](https://github.com/icsharpcode/ILSpy/files/4704383/software.v2.2.zip) - it is an application for a winforms laser engraver application that I am trying to modernize. The issue is with the exe - I am not interested in the dependencies (they contain unmanaged code and I will stay away from that).

Previously generated code - compiles fine:
```csharp
private static PointF bezier_interpolation_func2(float t, PointF[] points, int count)
		{
			PointF result = default(PointF);
			float num = 0f;
			float num2 = 0f;
			for (int i = 0; i < count; i++)
			{
				int num3 = count - 1;
				ulong num4 = calc_combination_number(num3, i);
				num += (float)((double)((float)(double)num4 * points[i].X) * Math.Pow(1f - t, num3 - i) * Math.Pow(t, i));
				num2 += (float)((double)((float)(double)num4 * points[i].Y) * Math.Pow(1f - t, num3 - i) * Math.Pow(t, i));
			}
			result.X = num;
			result.Y = num2;
			return result;
		}
```

Code generated today - does not compile:
```csharp
private static PointF bezier_interpolation_func2(float t, PointF[] points, int count)
		{
			//IL_0002: Unknown result type (might be due to invalid IL or missing references)
			//IL_00a5: Unknown result type (might be due to invalid IL or missing references)
			PointF result = default(PointF);
			float num = 0f;
			float num2 = 0f;
			for (int i = 0; i < count; i++)
			{
				int num3 = count - 1;
				ulong num4 = calc_combination_number(num3, i);
				num += (float)((double)((float)num4 * ((PointF)(ref points[i])).get_X()) * Math.Pow(1f - t, num3 - i) * Math.Pow(t, i));
				num2 += (float)((double)((float)num4 * ((PointF)(ref points[i])).get_Y()) * Math.Pow(1f - t, num3 - i) * Math.Pow(t, i));
			}
			((PointF)(ref result)).set_X(num);
			((PointF)(ref result)).set_Y(num2);
			return result;
		}
```

**Comment by dgrunwald** [comment]
Looks like ILSpy found the definition of `PointF` in your previous decompilation (otherwise it wouldn't have recognized that `set_X` belongs to a property `X`), but your current decompilation did not find `PointF`.
For unknown types the decompiler logic assumes the type is a reference type, uses of unresolved structs can lead to weird code such as this.

**Comment by hansmbakker** [comment]
`PointF` is a builtin type (it is from `System.Drawing` - part of .Net Framework 4.0). I did not follow a different procedure in ILSpy.
I just loaded the exe into ILSpy, right clicked on it in the tree and selected "save code".

Is there something I need to do different or can it be a regression in ILSpy?

**Comment by hansmbakker** [comment]
Odd thing:
Today I decided to try with a clean slate: I selected all items from the tree in ILSpy, right clicked and clicked "Unload".

Then I loaded the exe again, right clicked and clicked "Load dependencies" just to be sure.

After that, saving the code worked as expected. I'll close it now, since I cannot reliably reproduce it.
