### ISSUE TITLE
ILSPY doesn't find any assembly from GAC_64

### ISSUE THREAD

**Issue by senglory** [icsharpcode/ILSpy#2034]
![ILSPY](https://user-images.githubusercontent.com/1064066/84564438-50aee800-ad6a-11ea-8489-7152acd35021.jpg)
For example, in "Open From GAC" I type System.Fabric and see nothing, whereas this assembly has been already placed in GAC_64 (see the [screenshot](https://1drv.ms/u/s!ArGxIywiws8MhQ6AWhs99_HvfWY8?e=iAdetM)). OS - Win2012R2 x64 Standard

**Comment by christophwille** [comment]
Could you please try a latest from the build server? It enumerates the GAC differently.

**Comment by christophwille** [comment]
@senglory did you get a chance to test with the now-released preview4?

**Comment by senglory** [comment]
Yes, the version "6.0.0.5801-preview4" shows both GAC and GAC_64 content. Thanks! Waiting for a release version.

**Comment by christophwille** [comment]
Closing the issue because underlying issue is resolved. Note: v6 should release this summer.
