### ISSUE TITLE
for loop array access not detecting i < array.Length - 1

### ISSUE THREAD

**Issue by devilsclaw** [icsharpcode/ILSpy#2041]
ILSpy will show for C#:

Just an example:
int[] array = new int[201];
for (int i = 0; i < 200; i++) {
  array[i] = -1;
}

I am not sure if this is something easy to detect and automate

**Comment by dgrunwald** [comment]
Most likely the code was originally written with a hardcoded `200`, and ILSpy is showing you exactly that.

I'm not aware of any compiler that replaces `array.Length` with a constant in this situation, so I'm not sure why you think ILSpy should do the reverse transformation.

**Comment by devilsclaw** [comment]
Thanks for the reply, Yeah after looking over it more, It looks like your assumption is most likely correct.
