### ISSUE TITLE
How to modify output?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2049]
```
foreach (var en in syntaxTree.Descendants.OfType<EntityDeclaration>()) {
	if (en is TypeDeclaration) {
		en.InsertChildBefore(en.FirstChild, new TextNode("abc"), Roles.Text);
		if (en.ToString().StartsWith("abc"))
			Console.WriteLine("yes");
                 else
                        Console.WriteLine("no"); // why here?
	}
}
```

**Comment by dgrunwald** [comment]
`TextNode` isn't supported for output; it's a left-over from the `NRefactory` AST. I'll delete it.

Try a `Comment` node with `Roles.Comment` instead, that should work.
The ILSpy AST can only generate C# code, not arbitrary text.

**Comment by CreateAndInject** [comment]
I don't need `//`
In fact, I want to add `partial`.
``public (partial) class xxx```

**Comment by siegfriedpammer** [comment]
You can use `ed.Modifiers |= Modifiers.Partial;` to achieve this.

**Comment by CreateAndInject** [comment]
Thanks, it works!
