### ISSUE TITLE
Lost xmlns

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2052]
Original:
`<Grid x:XmlAttributeProperties.XmlSpace="preserve"/>`

ILSpy:
`<Grid XmlAttributeProperties.XmlSpace="preserve"/>`

VS can't build it without `x:`

**Comment by CreateAndInject** [comment]
By the way, how can I decompile .baml to a string/Stream/Document?
I find `BamlResourceFileHandler`, but it save to a file.

**Comment by CreateAndInject** [comment]
Another ILSpy output:
`<GroupBox Grid.Row="1" xmlns="clr-namespace:DevExpress.Xpf.LayoutControl;assembly=DevExpress.Xpf.LayoutControl.v19.1">`

dnSpy is right:
```
<Window .... xmlns:lay="http://schemas.devexpress.com/winfx/2008/xaml/layoutcontrol">
<lay:GroupBox Grid.Row="1">
```

Here, `GroupBox` defined in `DevExpress.Xpf.LayoutControl.v19.1`, `Grid` defined in `PresentationFramework`, ILSpy doesn't add a prefix for `GroupBox`, VS think both `GroupBox` and `Grid` defined in `DevExpress.Xpf.LayoutControl.v19.1`, so build failed.

**Comment by siegfriedpammer** [comment]
> By the way, how can I decompile .baml to a string/Stream/Document?
> I find `BamlResourceFileHandler`, but it save to a file.

Currently there are no plans to add the BAML decompiler to tools other than ILSpy. How would such an API look like?

**Comment by CreateAndInject** [comment]
@siegfriedpammer  Minimum change: make `LoadIntoDocument` as public, and add an optional parameter `assemblyReferences`

Others, make more types/members as public, such as: `BamlDocument` `BamlReader` `XamlDecompiler`......

**Comment by CreateAndInject** [comment]
Can you expose `assemblyReferences`?

**Comment by CreateAndInject** [comment]
@siegfriedpammer Can you expose assemblyReferences? So when we export to project, we can know which assemblies should be referenced.

**Comment by siegfriedpammer** [comment]
I am not sure, what you are referring to. When exporting an assembly as project, ILSpy already generates a project file, which should contain all required references. Are you talking about single file XAML export?

**Comment by CreateAndInject** [comment]
My plugin need it. What you do is:
```C#
		internal static XDocument LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver,
			Stream stream, CancellationToken cancellationToken)
		{
			cancellationToken.ThrowIfCancellationRequested();
			var document = BamlReader.ReadDocument(stream, cancellationToken);
			var xaml = new XamlDecompiler().Decompile(new BamlDecompilerTypeSystem(module, assemblyResolver), document, cancellationToken, new BamlDecompilerOptions(), null);
			return xaml;
		}
```

=>

```C#
		public static XDocument LoadIntoDocument(PEFile module, IAssemblyResolver assemblyResolver,
			Stream stream, CancellationToken cancellationToken, List<string> assemblyReferences = null)
		{
			cancellationToken.ThrowIfCancellationRequested();
			var document = BamlReader.ReadDocument(stream, cancellationToken);
			var xaml = new XamlDecompiler().Decompile(new BamlDecompilerTypeSystem(module, assemblyResolver), document, cancellationToken, new BamlDecompilerOptions(), assemblyReferences);
			return xaml;
		}
```
