### ISSUE TITLE
How does ilspy use terminal to control the exported C# version

### ISSUE THREAD

**Issue by zajanmy** [icsharpcode/ILSpy#2057]
How does ilspy use terminal to control the exported C# version

**Comment by siegfriedpammer** [comment]
Sorry, I don't understand. What are you asking?

**Comment by dgrunwald** [comment]
ILSpy passes the `LanguageVersion` enum to the `DecompilerSettings` constructor.

If by "terminal" you refer to ICSharpCode.Decompiler.Console (which ILSpy isn't using!); there's a `--languageversion` option.
