### ISSUE TITLE
NullReferenceException when running transforms on ILFunction

### ISSUE THREAD

**Issue by tgjones** [icsharpcode/ILSpy#2058]
### Steps to reproduce

1. Use this C# code, compile it to `MyDll.dll`:

``` csharp
public class MyClass
{
    public struct BoundingBox2D
    {
        public Float2 Min;
        public Float2 Max;
    }

    public struct Float2
    {
        public float X;
        public float Y;
    }

    public static float SimpleStruct()
    {
        var boundingBox = new BoundingBox2D
        {
            Min = new Float2 { X = 1, Y = 2 },
            Max = new Float2 { X = 3, Y = 4 }
        };
        return boundingBox.Min.Y + boundingBox.Max.X;
    }
}
```

2. Use this ILSpy code.

``` csharp
public void DoStuff(string inputDllFilePath)
{
    using var peFile = new PEFile(inputDllFilePath);

    var assemblyResolver = new UniversalAssemblyResolver(inputDllFilePath, true, ".NETCoreApp,Version=v3.1.0");
    var typeSystem = new DecompilerTypeSystem(peFile, assemblyResolver);

    var method = typeSystem.MainModule.TypeDefinitions
        .First(x => x.Name == "MyClass")
        .Methods
        .First(x => x.Name == "SimpleStruct");

    var methodDefinition = peFile.Metadata.GetMethodDefinition((MethodDefinitionHandle)method.MetadataToken);

    var methodBody = peFile.Reader.GetMethodBody(methodDefinition.RelativeVirtualAddress);
    var reader = new ILReader((MetadataModule)method.ParentModule);
    var ilFunction = reader.ReadIL(
        (MethodDefinitionHandle)method.MetadataToken,
        methodBody);

    var transforms = CSharpDecompiler.GetILTransforms();
    var transformContext = new ILTransformContext(ilFunction, typeSystem, null);

    ilFunction.RunTransforms(transforms, transformContext);
}
```

### Error message shown

```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    ILTransformContext.get_UsingScope()
    TransformCollectionAndObjectInitializers.IsPartOfInitializer(InstructionCollection`1 instructions, Int32 pos, ILVariable target, IType rootType, BlockKind& blockKind)
    TransformCollectionAndObjectInitializers.DoTransform(Block body, Int32 pos)
    IStatementTransform.Run(Block block, Int32 pos, StatementTransformContext context)
    StatementTransform.Run(Block block, BlockTransformContext context)
    Block.RunTransforms(IEnumerable`1 transforms, BlockTransformContext context)
    BlockILTransform.VisitBlock(ControlFlowNode cfgNode, BlockTransformContext context)
    BlockILTransform.Run(ILFunction function, ILTransformContext context)
    ILFunction.RunTransforms(IEnumerable`1 transforms, ILTransformContext context)
    Test.DoStuff()
```

### Details

* Product in use: ICSharpCode.Decompiler nuget package
* Version in use: 6.0.0.5836
* Any other relevant information to the issue: I'm probably using `ILFunction` and IL transforms in an unusual way. But with other input code it's worked fine until now. I've found it really helpful to use ILSpy's loop detection, condition detection, etc. on IL without having to write all that analysis code from scratch. The exception [happens here](https://github.com/icsharpcode/ILSpy/blob/004ea1bfc391f040b4830bc80a722ed6a1eb0225/ICSharpCode.Decompiler/IL/Transforms/IILTransform.cs#L53) because in my usage, `DecompileRun` is `null`. Am I too far off the beaten path, or is this fixable? I'm happy to work on a fix if someone could point me in the right direction.

**Comment by dgrunwald** [comment]
Using only this portion of the decompiler should be possible; that's why the ILReader and ILAst is public in the first place.
I guess that means we'll also need to expose the `DecompileRun` stuff for completeness; though in this case it would be good enough to fix the NullReferenceException and just not perform the collection initializer transform.

Background: some ILAst transforms for high-level C# constructs are sensitive to the presence of extension methods. But those depend on the usings we will end up generating. We won't know for sure which usings we will generate until after the decompiler is done; but some ILAst transforms require knowledge of a superset of all usings that might end up being generated.

As far as I can tell, this only affects object/collection initializers and the `?.` null propagation operator.
You may be able to work around this bug by disabling those two features in the `DecompilerSettings` passed to the `ILTransformContext`.

In general if you're processing the ILAst yourself instead of decompiling it to C#, you might want to disable all features (e.g. by using LanguageVersion.CSharp1 to create the `DecompilerSettings`) and then only enabling the features you need.
This way you avoid transforms introducing ILAst constructs that your code can't handle.

**Comment by tgjones** [comment]
Thank you for the great explanation and very quick bug fix! I tried using `new DecompilerSettings(LanguageVersion.CSharp1)` and indeed that does workaround the bug. And that's going to be useful in general, so I can more explicitly control the ILAst tree.

Also, thank you for ILSpy, and for making this part of the decompiler public. I'm prototyping an IL-to-WebAssembly compiler (yes, probably pointless, but I really want something lightweight with no runtime, and such a thing doesn't currently exist). WebAssembly requires structured control flow among other things, and using ILSpy's decompiler with its control flow detection and explicitly-typed IL tree has saved me a lot of time I would otherwise have spent writing that code.

**Comment by dgrunwald** [comment]
For a target as low-level as WebAssembly you might want to disable some more options in the `DecompilerSettings` that are still included with C# 1.0: `AutomaticEvents`, `UsingStatement`, `ForEachStatement`, `LockStatement`, `SwitchStatementOnString`, `MakeAssignmentExpressions`, `IntroduceIncrementAndDecrement`.

Or maybe you could even avoid `CSharpDecompiler.GetILTransforms()` altogether and build your own pipeline out of the individual transforms.

**Comment by siegfriedpammer** [comment]
> Or maybe you could even avoid `CSharpDecompiler.GetILTransforms()` altogether and build your own pipeline out of the individual transforms.

I don't think that all transforms are declared public. Should we change this?

**Comment by dgrunwald** [comment]
> I don't think that all transforms are declared public. Should we change this?

It's maybe not necessary for a low-level target like WebAssembly. But other high-level targets (e.g. a hypothetical VB decompiler) might want to use a mixture of their own transforms and our transforms. So I think all transforms that aren't strictly C#-specific should be public.

Back on the topic of `DecompileRun`: I think we don't need to make this public; the stuff sensitive to `using` declarations/extension methods is all highly C#-specific.
