### ISSUE TITLE
It seems that there is no switch for out variable declaration

### ISSUE THREAD

**Issue by zajanmy** [icsharpcode/ILSpy#2059]
![image](https://user-images.githubusercontent.com/8474367/86872913-daef2f80-c10f-11ea-88c1-90f9795e0547.png)
out int KHBGIONFHLJ is C# 7.0 syntax, I chose C#6.0 output, there is still such syntactic sugar

It seems that there is no switch for out variable declaration,  I don’t want a statement like out int a, there is no such switch in C# 7.X

**Comment by zajanmy** [comment]
It seems that there is no switch for out variable declaration, for example, I don’t want a statement like out int a, there is no such switch in C# 7.0

**Comment by siegfriedpammer** [comment]
![image](https://user-images.githubusercontent.com/344204/86880993-d6b21a80-c0ed-11ea-9d7a-93c3b4ff7c90.png)

There is an option in ILSpy for that. However from your screenshot I see you are not using ILSpy. Which product are you using?

**Comment by zajanmy** [comment]
> ![图片](https://user-images.githubusercontent.com/344204/86880993-d6b21a80-c0ed-11ea-9d7a-93c3b4ff7c90.png)
> 
> 在ILSpy中有一个选项。但是，从您的屏幕截图中，我看到您没有使用ILSpy。您正在使用哪种产品？

Thank you for your reply
I am using ilspy
I did not check "Use out variable declarations"

**Comment by siegfriedpammer** [comment]
![image](https://user-images.githubusercontent.com/344204/86883136-bf752c00-c0f1-11ea-8507-ca7631cdf8c2.png)

It works on my machine.

> I am using ilspy

Are you sure, I didn't know about  the dark theme support.

Can you send the assembly for inspection?

**Comment by zajanmy** [comment]
Hi, sorry, I was wrong
But I have another question
![image](https://user-images.githubusercontent.com/8474367/86884413-18f74e00-c126-11ea-994b-36aebf3a6555.png)
Which switch is this grammar

**Comment by siegfriedpammer** [comment]
There is no setting for ref locals, please see https://github.com/icsharpcode/ILSpy/issues/1292#issuecomment-477383331:

> We can't magically make ref locals disappear, just like we can't magically erase generics just because you might select C# 1.0.
