### ISSUE TITLE
Redundant code emitted when original code uses pattern matching

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2061]
### Input code
redundant goto
redundant local var

Token: 0x060002F5
public static CorLibTypeSig GetCorLibTypeSig(this ICorLibTypes self, ITypeDefOrRef type)

Token: 0x0600032A
public static TypeSig RemoveModifiers(this TypeSig a)

Token: 0x0600037A
public AssemblyNameInfo(AssemblyName asmName)

And more

[dnlib.x.dll.zip](https://github.com/icsharpcode/ILSpy/files/4902886/dnlib.x.dll.zip)

### Erroneous output
```c#
public static CorLibTypeSig GetCorLibTypeSig(this ICorLibTypes self, ITypeDefOrRef type)
{
        TypeDef typeDef = type as TypeDef;
        CorLibTypeSig corLibTypeSig = default(CorLibTypeSig);
        int num;
        if (typeDef != null)
        {
                TypeDef declaringType = typeDef.DeclaringType;
                if (declaringType == null)
                {
                        CorLibTypeSig corLibTypeSig2 = corLibTypeSig = self.GetCorLibTypeSig(typeDef.Namespace, typeDef.Name, typeDef.DefinitionAssembly);
                        num = ((corLibTypeSig2 != null) ? 1 : 0);
                        goto IL_0072;
                }
        }
        num = 0;
        goto IL_0072;
        IL_0072:
        if (num != 0)
        {
                return corLibTypeSig;
        }
        TypeRef typeRef = type as TypeRef;
        int num2;
        if (typeRef != null && !(typeRef.ResolutionScope is TypeRef))
        {
                CorLibTypeSig corLibTypeSig3 = corLibTypeSig = self.GetCorLibTypeSig(typeRef.Namespace, typeRef.Name, typeRef.DefinitionAssembly);
                num2 = ((corLibTypeSig3 != null) ? 1 : 0);
        }
        else
        {
                num2 = 0;
        }
        if (num2 != 0)
        {
                return corLibTypeSig;
        }
        return null;
}

public static TypeSig RemoveModifiers(this TypeSig a)
{
	if (a == null)
	{
		return null;
	}
	while (true)
	{
		bool flag = true;
		ModifierSig modifierSig = a as ModifierSig;
		if (modifierSig != null)
		{
			a = a.Next;
			continue;
		}
		break;
	}
	return a;
}
```

### Details
* Product in use: ILSpy
* Version in use: 6.0.0.5839

**Comment by dgrunwald** [comment]
GetCorLibTypeSig original code is here: https://github.com/0xd4d/dnlib/blob/ce7a762916805721639c2ce1a2629ebd221df3ba/src/DotNet/ICorLibTypes.cs#L122-L132
It uses pattern matching with `is Type t` and `is null`.
Apparently, unlike `== null`, pattern matching introduces an extra local variable in the generated IL code.
ILSpy doesn't implement pattern matching yet (#2048); so it doesn't know to remove these variable.

But when the initialization and the null check are in separate code statements, it's no longer possible to use `&&`. This then makes `goto` statements unavoidable (without duplicating other code or introducing temporary variables not present in the IL).

I think the other methods are the same problem: the original code uses pattern matching.

**Comment by dgrunwald** [comment]
I added an option "Always inline local variables if possible" (in the Decompiler>Other options) that helps keeping this style of code a good bit cleaner without requiring pattern matching to be implemented.

**Comment by siegfriedpammer** [comment]
We now support pattern matching.
