### ISSUE TITLE
ILSpy 6.0.0.5836 creates invalid csproj file

### ISSUE THREAD

**Issue by Saguntar** [icsharpcode/ILSpy#2065]
### Steps to reproduce
1. Open any Dotnet library built with Visual Studio 2015 against DotNet 4 Client Framework or DotNet 4.6
2. Save C#-Project
3. The source files and AssemblyInfo.cs are exported correctly, but the created csproj file is invalid: It contains no reference to any source code file nor an xmlns entry in the root node, but only some general settings and the DotNet references.

### Error message shown
-- none --

### Content of generated project file is attached
[MyProjectName.csproj.txt](https://github.com/icsharpcode/ILSpy/files/4917271/MyProjectName.csproj.txt)

```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```

### Details
Used ILSpy V 6.0.0.5836

**Comment by christophwille** [comment]
There is a new default for exporting projects - we are generating modern SDK-style projects:

![sdkstyleprojects](https://user-images.githubusercontent.com/344208/87399565-d4513400-c5b7-11ea-9034-742898cb6195.png)
