### ISSUE TITLE
Add a option to sort switch cases

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2071]
If the order of basic blocks is changed, the decompilation result of the switch statement will change (e.g. de4dot cflow)
``` cs
after de4dot cflow:
switch (osType)
{
default:
	throw new InvalidOperationException("Shouldn't be here");
case OSType.Unix:
	Unix.Dispose(intPtr, origDataLength);
	break;
case OSType.Windows:
	Windows.Dispose(intPtr);
	break;
}

before de4dot cflow (original):
switch (osType)
{
case OSType.Windows:
	Windows.Dispose(intPtr);
	break;
case OSType.Unix:
	Unix.Dispose(intPtr, origDataLength);
	break;
default:
	throw new InvalidOperationException("Shouldn't be here");
}
```
So sorting cases by some rules may help, such as sorting by number value for byte short int long and sorting by string value for string

**Comment by dgrunwald** [comment]
We intentionally sort by IL offset.

With non-obfuscated code, the C# compiler emits IL in the same order as the original source code; so we try to preserve that order.
