### ISSUE TITLE
Add support for displaying module initializer constructors in ILSpy

### ISSUE THREAD

**Issue by philiplaureano** [icsharpcode/ILSpy#2083]
**Is your feature request related to a problem? Please describe.**
I'm currently emitting my own IL to generate a module initializer/constructor, and since module constructors are not supported in C# 8 and below, it is impossible to show even the IL view of that module constructor, using ILSpy.

The approach that I've taken to generating that constructor is similar to the one in this blog post: https://einaregilsson.com/module-initializers-in-csharp/

Note: It appears that the special module constructor named '.cctor' can be displayed in ILDASM.exe, but it cannot be displayed in ILSpy. 

**Describe the solution you'd like**
I'm just looking for the ability to do an IL dump of what is in that special static '.cctor' module constructor/initializer, and optionally, what would it look like it its C# form, all without having to leave ILSpy.

**Additional context**
I'm aware that it's a corner case, but it would be nice to get full parity between ILSpy and ILDASM so that I don't have to switch between the two tools just to fill in any missing information.

**Comment by dgrunwald** [comment]
You should be able to see the special `<Module>` class in the unnamed namespace (labeled `-` in the UI).
Unless you maybe have "Show only public types and members" enabled?

**Comment by christophwille** [comment]
@philiplaureano does the existing feature work for you scenario?

**Comment by christophwille** [comment]
No feedback provided, closing.
