### ISSUE TITLE
if statement c# code erroneously negate

### ISSUE THREAD

**Issue by trivalik** [icsharpcode/ILSpy#2084]
ILSpy Version 6.1

At decompile `Dispose(bool)` from `System.Drawing.Image` it looks like that the C# code is negate the `if` but the IL code not, see both here:
```
	// if (!(nativeImage != IntPtr.Zero))
	IL_0000: ldarg.0
	IL_0001: ldfld native int System.Drawing.Image::nativeImage
	IL_0006: ldsfld native int [mscorlib]System.IntPtr::Zero
	IL_000b: call bool [mscorlib]System.IntPtr::op_Inequality(native int, native int)
	IL_0010: brfalse.s IL_003f
```

**Comment by dgrunwald** [comment]
That `brfalse.s` skips over the whole method if `op_Inequality` returns false.

ILSpy decompiles this to:
```
	if (!(nativeImage != IntPtr.Zero))
	{
		return;
	}
```
which effectively does the same thing.

**Comment by dgrunwald** [comment]
Note that the decompiler will always rearrange things to use early returns where possible.
This keeps code more readable if there are lot of early-exit-conditions -- with the alternative, we'd end up creating highly-nested code.
See [ReduceNestingTransform](https://github.com/icsharpcode/ILSpy/blob/417a2c3391e1540a69c167081af62d5041204f86/ICSharpCode.Decompiler/IL/Transforms/ReduceNestingTransform.cs#L29).

**Comment by trivalik** [comment]
Sure, but then if statement should be `if (nativeImage != IntPtr.Zero)` to work correctly, free a `Zero` would not be good.
