### ISSUE TITLE
Translations not currently included in VSIX

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2085]
We discussed that during the first weekend of #1933 but chose to not fix it, but with the new translations in #2066 we definitely should reconsider fixing the missing inclusion of translations.

See https://github.com/icsharpcode/ILSpy/blob/master/ILSpy.AddIn/ILSpy.AddIn.csproj#L117

**Comment by maikebing** [comment]
Hi , @christophwille  , now , it fix by   #2066

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/88932879-3e085800-d2b1-11ea-8920-71d9e74f4c74.png)

**Comment by maikebing** [comment]
![image](https://user-images.githubusercontent.com/3445167/88933014-6a23d900-d2b1-11ea-892f-eafa164fa976.png)

**Comment by siegfriedpammer** [comment]
@maikebing can you confirm that this is fixed now?

**Comment by maikebing** [comment]
The vsix translation has been completed and is all displayed as Chinese.

**Comment by maikebing** [comment]
If you want, the next step can start supporting other languages, not just Chinese. 
Click on the link below to see how to manage localization.
https://crowdin.com/page/open-source-project-setup-request  
Of course, if you don't have time to deal with it, I can help.

**Comment by maikebing** [comment]
I have experience with CodeMaid and GitHub for Visual Studio.

**Comment by christophwille** [comment]
Issue resolved, created discussion https://github.com/icsharpcode/ILSpy/discussions/2099
