### ISSUE TITLE
Incorrect transformation of IL to Unsafe.ByteOffset call

### ISSUE THREAD

**Issue by jonathan-vermeiren** [icsharpcode/ILSpy#2094]
### Input code
```
.method public hidebysig static 
	native int ByteOffset<T> (
		!!T& origin,
		!!T& target
	) cil managed aggressiveinlining 
{
	// Code size 4 (0x4)
	.maxstack 2

	IL_0000: ldarg.1
	IL_0001: ldarg.0
	IL_0002: sub
	IL_0003: ret
}
```
See also the original source code for the ByteOffset<T> method in System.Runtime.CompilerServices.Unsafe: https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Runtime.CompilerServices.Unsafe/src/System.Runtime.CompilerServices.Unsafe.il#L422 to verify that this instruction sequence is indeed that of the ByteOffset<T> method.

### Erroneous output
```c#
using System;
using System.Runtime.CompilerServices;

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static IntPtr ByteOffset<T>(ref T origin, ref T target)
{
	return Unsafe.ByteOffset(ref target, ref origin);
}
```
The IL is correctly transformed to use the proper Unsafe method, but the transformation has the parameters in the wrong order.
To perform the computation the second parameter is the first one to be loaded onto the evaluation stack.

### Expected output
Therefore the correct decompilation should reverse them when transforming it to a Unsafe.ByteOffset call:
```c#
using System;
using System.Runtime.CompilerServices;

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static IntPtr ByteOffset<T>(ref T origin, ref T target)
{
	return Unsafe.ByteOffset(ref origin, ref target);
}
```

### Details
Product in use: ILSpy 6.1.0.5902

**Comment by dgrunwald** [comment]
Oh interesting. I assumed that `SubtractByteOffset` and `ByteOffset` did the same thing just with different types (ref-I=ref vs. ref-ref=I), but apparently `ByteOffset` has the parameters in the opposite order of `SubtractByteOffset`.
I guess we'll need to use named arguments as this happens too late in the decompiler to reorder expressions that might have side-effects.
