### ISSUE TITLE
Prefix:PropertyName is invalid syntax

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2097]
``` IsChecked="{TemplateBinding prefix:IsExpanded}" ```

Should use `PropertyName` or `TypeName.ProppertyName` or `Prefix:TypeName.PropertyName`

**Comment by siegfriedpammer** [comment]
Please provide the assembly that triggers this behavior. Thank you very much!

**Comment by CreateAndInject** [comment]
[file.zip](https://github.com/icsharpcode/ILSpy/files/5045849/file.zip)

uicommon/themes/alirpawindowbasestyle.baml:
 ```<Border Name="ShadowRectangle" BorderThickness="0" Background="#00FFFFFF" CornerRadius="{TemplateBinding themes:WindowCornerRadius}">```

**Comment by CreateAndInject** [comment]
attendedrobot/usercontrols/appstoredatacontrol.baml‎ : 
```<GridViewRowPresenter Columns="{TemplateBinding ColumnCollection}" Margin="{TemplateBinding Padding}" />```
But `GridViewRowPresenter` and its base types don't have a  `ColumnCollection` property, should it:
```<GridViewRowPresenter Columns="{TemplateBinding GridView.ColumnCollection}" Margin="{TemplateBinding Padding}" />``` ??

**Comment by CreateAndInject** [comment]
```
				if (parent == null || (parent.GetDefaultNamespace() != typeName.Namespace
					                && parent.Name.Namespace != typeName.Namespace))
					name = typeName.Namespace + name.LocalName;
```

This logic seems incorrect, see:
```<materialGglDesign:MaterialTabControl MinWidth="250" TabControlHelper.HeaderPanelBorderThickness="0" Padding="0">```

Must add prefix for `TabControlHelper.HeaderPanelBorderThickness`, it should be:
```<materialGglDesign:MaterialTabControl MinWidth="250" materialGglDesign:TabControlHelper.HeaderPanelBorderThickness="0" Padding="0">```

**Comment by siegfriedpammer** [comment]
Can you please tell me the location of these examples? I am having a hard time finding `MaterialTabControl` in any of the BAML files of the provided assembly.

**Comment by CreateAndInject** [comment]
It's another files
[2.zip](https://github.com/icsharpcode/ILSpy/files/5048011/2.zip)

common/controls/customcontrols/basestatsrangeview/basestatsrangeview.baml‎ : 
```<materialGglDesign:ImageIcon Margin="0,0,8,0" Source="pack://application:,,,/Hand2NoteCore;component/Resources/Icons/AntonTulenev/infinity_16.png" Padding="0" VerticalAlignment="Bottom" Command="{Binding SetLeftInfinityCommand}" Visibility="{Binding IsLeftInfinityPossible, Converter={BoolToVisibilityConverter}}">```

`Converter={BoolToVisibilityConverter}` should be => `Converter={materialGglDesign:BoolToVisibilityConverter}` 

<br/><br/>

```<common:ClickSelectTextBox Grid.Column="1" Padding="0" MinWidth="20" HorizontalContentAlignment="Right" DoubleTextBoxBehavior.Enable="True" VerticalAlignment="Center" Style="{StaticResource MaterialTextBox}" DoubleTextBoxBehavior.Value="{Binding Left, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" materialGglDesign:DefaultValueManager.CurrentValue="{Binding Left}" materialGglDesign:DefaultValueManager.DefaultValueSource="{Binding DefaultValue.Left}" />```

`DoubleTextBoxBehavior.Enable="True` should be => `common:DoubleTextBoxBehavior.Enable="True`

**Comment by CreateAndInject** [comment]
@siegfriedpammer I can reproduce it in an easy simple:
```
<Window x:Class="BamlTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:BamlTest"
        Title="{x:Static local:My.Test}" Height="350" Width="525">
    <Grid>
        <TextBlock Text="{x:Static local:My.Test}"/>
    </Grid>
</Window>

namespace BamlTest
{
	public partial class MainWindow : Window
	{
		public MainWindow()
		{
			InitializeComponent();
		}
	}

	class My
	{
		public static string Test = "Hello";
	}
}
```

ILSpy output:
```
<Window x:Class="BamlTest.MainWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="clr-namespace:BamlTest" Title="{x:Static My.Test}" Height="350" Width="525">
  <Grid>
    <TextBlock Text="{x:Static local:My.Test}" />
  </Grid>
</Window>
```
See:
` Title="{x:Static My.Test}" ` Wrong, should be =>` Title="{x:Static local:My.Test}" `
`<TextBlock Text="{x:Static local:My.Test}" />` Right

**Comment by siegfriedpammer** [comment]
Thank you for providing so many examples and a test case!
