### ISSUE TITLE
wrong string switch

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2101]
``` cs
private string DeleteFileOrDirectory(string type1, string type2, string wj)
{
	string text = Directory.GetCurrentDirectory() + wj;
	if (type1 == "QQ目录下")
	{
		text = Directory.GetCurrentDirectory() + "\\QQ\\" + ((Plugin)this).get_Client().get_QQ() + wj;
	}
	reply = $"删除失败，路径指向的文件{type2}不存在！\n详细路径：{text}";
	string text2;
	switch (text2)
	{
	default:
		if (text2.Length == 0 && File.Exists(text))
		{
			File.Delete(text);
			reply = "删除成功！";
		}
		break;
	case "夹":
		if (Directory.Exists(text))
		{
			Directory.Delete(text, recursive: true);
			reply = "删除成功！";
		}
		break;
	case null:
	case null:
		break;
	}
	return reply;
}
```

it is obviously not a string switch, even local var "text2" does not get assigned and there are duplicated cases.

i don't have source code, it is bin file and i deleted other not related code.
[1.zip](https://github.com/icsharpcode/ILSpy/files/5057862/1.zip)

ilspy version: 6.1.0.5969

**Comment by dgrunwald** [comment]
ILSpy will turn a sufficiently-long chain of `if-else if` string comparisons into a switch.

I see two problems here:
 * The switch transform has a bug that causes it to sometimes delete a necessary variable initialization (this leaves `text2` uninitialized)
 * The switch transform needs to check for duplicate strings (here: duplicate null) and combine these (or abort the transform if these jump to different instructions)

In this case if the de-duplication was implemented that would reduce the number of case labels from 3 to 2; which would disable the decompilation into a switch.
