### ISSUE TITLE
[Analyzer] Async usage not detected correctly

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#2105]
### Steps to reproduce
1. Download the sample from https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases or [HearthstoneDeckTracker.zip](https://github.com/icsharpcode/ILSpy/files/5066194/HearthstoneDeckTracker.zip)
2. Navigate to `Hearthstone_Deck_Tracker.Core.Initialize()`
3. Right click on the `UpdateOverlayAsync();`, select `Analyze`
4. `<Initialize>d__45.MoveNext()` was shown in `Used by`, but itself was not used by anything (should be used by `Initialize()`)

### Error message shown
![image](https://user-images.githubusercontent.com/9637711/90074717-a3484a00-dcb0-11ea-9b8a-cd4d747a73ee.png)

### Details
* Product in use: ILSpy
* Version in use: 6.1.0.5967

**Comment by siegfriedpammer** [comment]
The `MoveNext` method is not directly used anywhere. It implements `System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext`, which is called by `System.Runtime.CompilerServices.Async*MethodBuilder.Start`. The "used by" analyzer only looks for direct usages, not interface uses. However, it might be a good idea to add uses inferred by our CodeMapping analysis. Thanks for the feedback!
