### ISSUE TITLE
Can't open saved solution in VS

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2112]
### Steps to reproduce
1.  Save as solution  (VS2017.7 selected in combobox)
2.  Try to open up in VS 2017  (ver 15.9.24)
3. 

### Error message shown

![image](https://user-images.githubusercontent.com/765343/90663775-c0ea5600-e252-11ea-87a8-3c066e88a43c.png)

Project not loaded at all!

### Details
* Version in use: ILSpy version 6.1.0.5902

Would be nice to print more info and/or fix the issue

the error is not clear...

**Comment by dgrunwald** [comment]
What type of project did you try to decompile? .NET Core/Standard/Framework?

**Comment by christophwille** [comment]
We can't do much about the VS dialog (obviously). Although it shouldn't be an issue for VS2017, you could try in Options/Decompiler/Other (last one in the listbox) to turn off the second-last option to generate SDK style projects.

**Comment by greenozon** [comment]
.net standard (4.0)

.csproj starts as follows:

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>testtest</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWPF>True</UseWPF>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>

.... here is list of ref dlls

```


No any .cs source added!

**Comment by greenozon** [comment]
> try in Options/Decompiler/Other (last one in the listbox) to turn off the second-last option to generate SDK style projects.

WOW!
this option helped

COuld you confirm that new "sdk style project" is not OK for VS2017?
maybe its OK only for 2019+?

**Comment by christophwille** [comment]
The new format was introduced with .NET Core, and we (ILSpy) have been using the SDK-style format for a very long time (pre-2019). However, we weren't using the latest format (eg your Windows Desktop target is newer), so that's why it worked even back then.

Defaulting to SDK-style projects is new in ILSpy 6.0.

**Comment by greenozon** [comment]
OK, thanks for explanation
Closing it as there is a workaround to use old project style
