### ISSUE TITLE
Improving csproj Export (Save Code)

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2121]
√ 1. if reference assembly is in GAC, <HintPath> shouldn't be generated. sometimes it will cause compilation errors.
√ 2. app.config and app.manifest can't be exported to decompilation directory.
√ 3. ico file can't be exported to decompilation directory.
√ 4. add \<RootNamespace /\> to csproj, for some merged assembly, csproj without <RootNamespace /> will cause output file resource in wrong namespace
√ 5. add \<EmbeddedResource\> for embedded resource, ilspy currently just copies embeded resource to decompilation directory but does't add <EmbeddedResource> for it in csproj

**Comment by wwh1004** [comment]
4. add <RootNamespace /> to csproj, for some merged assembly, csproj without <RootNamespace /> will cause output file resource in wrong namespace
5. add <EmbeddedResource> for embedded resource, ilspy currently just copies embeded resource to decompilation directory but does't add <EmbeddedResource> for it in csproj

**Comment by zrlw** [comment]
dnSpy  could export  app.config and app.manifest automatically while exporting project,  so i think  ISSpy may be do it also in the furture.

**Comment by christophwille** [comment]
We welcome contributions in this area because it is low on our priority list (we focus on decompilation quality).

**Comment by wwh1004** [comment]
√  6. app.manifest
