### ISSUE TITLE
Don't generate  InitializeComponent, IComponentConnector.Connect and member variables  which are alreay defined in xaml

### ISSUE THREAD

**Issue by zrlw** [icsharpcode/ILSpy#2122]
**Describe the solution you'd like**
If having xaml, don't generate InitializeComponent, IComponentConnector.Connect  and member variables just like dnSpy did.

**Comment by Neznakomec** [comment]
Also for successful compilation of exported project, it should add a **partial** keyword to class like
`public **partial** class App : Application`
`public **partial** class MainWindow : ThemedWindow, IComponentConnector`

**Comment by riQQ** [comment]
Related to #2253

**Comment by siegfriedpammer** [comment]
> Also for successful compilation of exported project, it should add a **partial** keyword to class like `public partial class App : Application` `public partial class MainWindow : ThemedWindow, IComponentConnector`
> 
> and
> 
> 1. rename this App.cs and MainWindow.cs files with extensions *.xaml.cs
> 2. place `App.xaml.cs, MainWindows.xaml.cs` **in the same directory** with `App.xaml, MainWindow.xaml`

This is already implemented in 5046e4cf6038735d1202194d5d96d281cfdbac4b
