### ISSUE TITLE
Unable to decompile async function with capture in new version of roslyn

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2129]
### Input code
```cs
        public void Test(int i)
        {
            _ = Test1();

            async Task Test1()
            {
                await Task.Yield();
                Console.WriteLine(i);
            }
        }
```

### Erroneous output
```c#
	public void Test(int i)
	{
		object <>4__this;
		Test1();
		[AsyncStateMachine(typeof(<>c__DisplayClass0_0.<<Test>g__Test1|0>d))]
		Task Test1()
		{
			<>c__DisplayClass0_0.<<Test>g__Test1|0>d stateMachine = default(<>c__DisplayClass0_0.<<Test>g__Test1|0>d);
			stateMachine.<>t__builder = AsyncTaskMethodBuilder.Create();
			stateMachine.<>4__this = (<>c__DisplayClass0_0)<>4__this;
			stateMachine.<>1__state = -1;
			stateMachine.<>t__builder.Start(ref stateMachine);
			return stateMachine.<>t__builder.Task;
		}
	}
```

### Details
* Product in use: `ILSpy`
* Version in use: `6.1.0.5902`, `6.2.0.6035-preview1`(master)

**Comment by siegfriedpammer** [comment]
Sorry, could not reproduce...

![image](https://user-images.githubusercontent.com/344204/91538099-90bc4a80-e917-11ea-9661-7f62956de80e.png)

Assembly generated using Visual Studio 16.7.2 / Roslyn 3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878 / .NET 5.0 / Debug Build

**Comment by yyjdelete** [comment]
Attached dlls compiled with dotnet-sdk 5.0.100-preview.8.20417.9(roslyn 3.8.0-2.20413.3 (71ffb700))/vs16.8.0-preview2(3.8.0-2.20418.7 (0276b9b7))
[2129.zip](https://github.com/icsharpcode/ILSpy/files/5141248/2129.zip)

**Comment by yyjdelete** [comment]
Seems also for normal async functions with capture `this`;
```cs
public class X
{
        int j;
        async Task Test1()
        {
            Console.WriteLine(this.j);
        }
}
```
