### ISSUE TITLE
GUI - Unaligned second column in search pad

### ISSUE THREAD

**Issue by dsrbecky** [icsharpcode/ILSpy#213]
The search pad results seem to have two columns - the name of the result and the parent node of the result (declaring type or namespace).  The second column seems to unaligned for some reason - the X position of the is completely wrong.

I guess we should also add the column headers and a little bit of margin.  At the moment the first impression is that the search results are acutally in a combobox-like popup rather then in Pad.

**Comment by siegfriedpammer** [comment]
The ListBox was replaced by a ListView in 1ba2c0537a2946d08345623c14c0ee05e2f9ff36. I consider this fixed.
