### ISSUE TITLE
Could not decompile dll from apk of Xamarin.Android 

### ISSUE THREAD

**Issue by jingliancui** [icsharpcode/ILSpy#2137]
Steps:
1.Visual studio create the xamarin.forms project
2.Change debug mode to release
3.Rebuild the Android Project.
4.ILSPY Open the dll from bin/Release folder can decompile 
5.Archive the project to publish the apk
6.Unzip the apk and got the dll
7.ILSPY Open the dll from apk could not decompile

dll which could not be decompiled here:
[SampleApp.zip](https://github.com/icsharpcode/ILSpy/files/5155015/SampleApp.zip)

other info:
Visual Studio 2019 Community

```
// C:\Users\ericc\Desktop\com.companyname.sampleapp\assemblies\SampleApp.dll
// This file does not contain a managed assembly.

System.BadImageFormatException: Image is too small.
   在 System.Reflection.Throw.ImageTooSmall()
   在 System.Reflection.PortableExecutable.SectionHeader..ctor(PEBinaryReader& reader)
   在 System.Reflection.PortableExecutable.PEHeaders.ReadSectionHeaders(PEBinaryReader& reader)
   在 System.Reflection.PortableExecutable.PEHeaders..ctor(Stream peStream, Int32 size, Boolean isLoadedImage)
   在 System.Reflection.PortableExecutable.PEReader.InitializePEHeaders()
   在 ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader, MetadataReaderOptions metadataOptions)
   在 ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
```

**Comment by greenozon** [comment]
Looks like your dll, SampleApp.dll,  is a kind of packed file, thus not loadable out of the box:

![image](https://user-images.githubusercontent.com/765343/91829283-f119f780-ec49-11ea-9716-2255b45bcf0d.png)

**Comment by jingliancui** [comment]
What is the packed file 😂

**Comment by greenozon** [comment]
It means file is not ready to be eaten by any external tool like ILSpy, etc

someone has to unpack it before - most probably thats up to Xamarin runtime I guess...

packed file info - https://en.wikipedia.org/wiki/Executable_compression

**Comment by dgrunwald** [comment]
The first 14 bytes in your hex dump seem to be some extra header. The bytes after that (`MZ`) are normally at the start of the file.
The PE header seems to start at 0x6a.
Normally offset 0x3c holds the address of the PE header, but here it's the word "This". Removing the first 14 bytes also doesn't work, 0x3c will still be inside the text.
This means ILSpy (and other tools) are unable to find the PE header.

If I replace the first 0x6a bytes of your file with the first 0x80 bytes of a normal .NET assembly I can get the start of the PE header to decode in CFF explorer. However most of the fields in the optional header seem to be garbage -- so there's probably also some differences in the file format there. The garbage prevents CFF explorer from finding the .NET headers (if there even are any).

Going by the visible text in the DLL there might be uncompressed .NET metadata in there; but finding it will require figuring out what file format this is -- portions of it look like normal PE files but those portions are not arranged in the way they should be.

**Comment by dgrunwald** [comment]
This seems to be the PR adding the decompression support to the mono runtime: https://github.com/xamarin/xamarin-android/pull/4686
The whole assembly is in fact compressed with LZ4 (including the clearly visible "This program cannot be run in DOS mode") -- LZ4 doesn't use entropy coding so readable fragments of uncompressed data can remain.

**Comment by jingliancui** [comment]
@dgrunwald So is this mean that ilspy and other decompile apps can not decompile the dll which used LZ4 to compress ?😂

**Comment by jingliancui** [comment]
It's seem like this PR had written the format to compress the dll , so I know decompile tools will decompile the dll finished someday future.

**Comment by siegfriedpammer** [comment]
> @dgrunwald So is this mean that ilspy and other decompile apps can not decompile the dll which used LZ4 to compress ?😂

Not entirely sure why this is funny, but yes, just like word processors, image editors or other tools want you to unpack your zip file before you can edit the files contained within, you will have to preprocess compressed DLLs before ILSpy can open them. Each tool focuses on one particular job: there are unpackers, deobfuscators, disassemblers, decompilers, etc. The job of decompilation is complex enough and we only want to support a limited range of "vanilla" file formats.

Unless support for these is contributed, it won't happen. Thank you for your understanding.

**Comment by jingliancui** [comment]
@siegfriedpammer Thanks your explain. Discuss of this issue is helpful for my development work.

**Comment by Techbrunch** [comment]
I ran into this issue today and someone actually solved it.

You can run a smally [python script](https://github.com/x41sec/tools/blob/master/Mobile/Xamarin/Xamarin_XALZ_decompress.py) to decompress the DLL.

Source: [Decompressing Xamarin DLLs](https://www.x41-dsec.de/security/news/working/research/2020/09/22/xamarin-dll-decompression/)

**Comment by Falco20019** [comment]
I appreciate #2471. If it would not get merged, it would still be great to at least detect the file starting with XALZ and hinting the user to why it's failing. This would be minimal and not add any dependency to LZ4 decompression.

**Comment by Falco20019** [comment]
Wasn't trying to pressure you at all :) Sorry if it felt like that.

Only wanted to mention an alternative in case you want to refrain from adding it in favor of keeping the application simpler/focused on it's main concern.
