### ISSUE TITLE
Add flag values to both "Characteristics" lists in Metadata Explorer

### ISSUE THREAD

**Issue by srutzky** [icsharpcode/ILSpy#2138]
Having the "Characteristics" lists in Metadata Explorer is great, but it would be even more helpful to see the individual values for each item in both lists. Doing so would make the relationship between the bitmasked value and the individual items that make up that value much clearer. I want to add the specific flag values to each of the individual options for both the "Characteristics" list (in "COFF Header") and the "DLL Characteristics" list (in "Optional Header"). The end-result being that we would see:

```
☑️  | <0x0002> File is executable
🟦  | <0x0004> Line numbers stripped from file
🟦  | <0x0008> Local symbols stripped from file
...
🟦  | <0x0080> Bytes of machine words are reversed (Low)
```
Or, it could be:
```
☑️  | <0002> File is executable
🟦  | <0004> Line numbers stripped from file
🟦  | <0008> Local symbols stripped from file
...
🟦  | <0080> Bytes of machine words are reversed (Low)
```
Or, it could be something else entirely.

Is there a preferred style? I'm using `<` and `>` to keep them visually separate from the existing parenthetical values used at the end of the line in a few places: `(Low)`, `(High)`, and `(SEH)`.

I'm willing to make the change, but I first want to make sure that the format is acceptable.

Thanks, Solomon..

**Comment by siegfriedpammer** [comment]
Looks good to me.

**Comment by srutzky** [comment]
@siegfriedpammer Great. But, is there a preference between with `0x` or without? As in:

`<0x0080>`  vs  `<0080>`

_With_ `0x` is clearer that the value is hex instead of decimal, but at least to me it doesn't look as nice as without. So far I am leaning towards _without_, but there are a few places in Metadata Explorer where I kinda wish it were a little clearer that the value is hex or decimal. Of course, after checking again, I don't see any place that has `0x`, so probably best to leave that off for the sake of consistency.

**Comment by siegfriedpammer** [comment]
> Of course, after checking again, I don't see any place that has `0x`, so probably best to leave that off for the sake of consistency.

The values look like flags anyway, so I think you can omit the 0x. 

> but there are a few places in Metadata Explorer where I kinda wish it were a little clearer that the value is hex or decimal.

If I recall correctly, all values are hexadecimal with one single exception: the RID column.

Your proposed change would also follow the current display of attributes/flags in tooltips.

![image](https://user-images.githubusercontent.com/344204/92024639-b9e93a80-ed5e-11ea-9850-d8d71cdb9a19.png)

**Comment by srutzky** [comment]
> The values look like flags anyway, so I think you can omit the 0x.

Done via #2145.

&nbsp;

> If I recall correctly, all values are hexadecimal with one single exception: the RID column.

The "Value" column in the "DOS Header" tab / section is in decimal / integer format. Which is fine, at least for now. It would be nice to have both because I use some values to find something in the assembly, and I use other values to find the value itself. I'm not exactly sure what the real solution should be, especially because there are some "Meaning" entries that should be updated to include the value. And, I don't do this type of analysis frequently enough to make it a priority. If I ever have the time, I will open a separate issue for that.
