### ISSUE TITLE
ILSpy 6.2p1 no longer respects "use discards" setting

### ISSUE THREAD

**Issue by lbmaian** [icsharpcode/ILSpy#2140]
### Input code
Decompiler settings reset to default, which includes enabling "Use discards" under C# 7.0.

Source as entered in LINQPad 5:
```cs
void Main()
{
	Foo(out var _);
}

void Foo(out bool x)
{
	x = true;
}
```
Assembly: [query_xskhct.zip](https://github.com/icsharpcode/ILSpy/files/5160945/query_xskhct.zip)

### Erroneous output
Actual output:
```cs
private void Main()
{
	Foo(out bool x);
}

private void Foo(out bool x)
{
	x = true;
}
```

Expected output:
```cs
private void Main()
{
	Foo(out bool _);
}

private void Foo(out bool x)
{
	x = true;
}
```

### Details
* Product in use: e.g. ILSpy
* Version in use: 6.2.0.6062-preview1

**Comment by siegfriedpammer** [comment]
Yes, this feature was removed, as it was not correctly implemented. `out var _` is not actually a discard, but an out variable declaration named `_`. In order to properly support discards, we will have to adapt some  parts of the decompiler, e.g., overload resolution, to support the new language rules.

**Comment by lbmaian** [comment]
Are you sure?

The following
```cs
Foo(out bool _);
Foo(out bool _);
```
works fine for me.

If it were an actual out variable declaration, I'd get a CS0128 syntax error.

You can't even access this `_` afterwards (results in CS0103 name '_' does not exist in the current context), unless `_` is explicitly defined elsewhere (a local var not defined via out var declaration, an argument, or a field).

**Comment by lbmaian** [comment]
Thanks for fixing this!

I think some of the prior confusion may be that `out` `var`-less discards in the form of `Foo(out _)` aren't safe to do, since if `_` is defined elsewhere and is in scope, the `_` in `Foo(out _)` would refer to it (or attempt to). But AFAIK, `out` variable declarations like `Foo(out var _)` and `Foo(out bool _)` should be safe.

**Comment by siegfriedpammer** [comment]
See https://github.com/icsharpcode/ILSpy/commit/04f9603768bfb282fdc762c3c00c57d1054a6523#diff-77df99bb43b3cc69be9a5f6beca55c78R599-R602

once that is added, we might use the `out _` shortcut as well...
