### ISSUE TITLE
Decompile Xamarin compressed assemblies

### ISSUE THREAD

**Issue by bitk0der** [icsharpcode/ILSpy#2142]
Hello, is it possible to decompile compressed Xamarin Assemblies (".dll", NOT ".dll.so")? DLL now can be compressed LZ4 algo, described here: https://github.com/xamarin/xamarin-android/pull/4686

**Comment by dgrunwald** [comment]
Duplicate of #2137.

We currently don't plan to work on this feature; but we're happy to accept contributions.

**Comment by christophwille** [comment]
Closing duplicate.
