### ISSUE TITLE
Internal event implementation not removed

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2154]
ILSpy version 6.2.0.6088-preview1

For some reason I see the internal event implementation code instead of having just += as well as -= short syntax

I guess this is very similar to issue #2098

### Erroneous output
```c#
public static event PageDescriptor StopRepository
{
	add
	{
		PageDescriptor pageDescriptor = paramDescriptor;
		PageDescriptor pageDescriptor2;
		do
		{
			pageDescriptor2 = pageDescriptor;
			PageDescriptor value2 = (PageDescriptor)Delegate.Combine(pageDescriptor2, value);
			pageDescriptor = Interlocked.CompareExchange(ref paramDescriptor, value2, pageDescriptor2);
		}
		while ((object)pageDescriptor != pageDescriptor2);
	}
	remove
	{
		PageDescriptor pageDescriptor = paramDescriptor;
		PageDescriptor pageDescriptor2;
		do
		{
			pageDescriptor2 = pageDescriptor;
			PageDescriptor value2 = (PageDescriptor)Delegate.Remove(pageDescriptor2, value);
			pageDescriptor = Interlocked.CompareExchange(ref paramDescriptor, value2, pageDescriptor2);
		}
		while ((object)pageDescriptor != pageDescriptor2);
	}
}
```

### Expectations
```c#
		public static event PageDescriptor StopRepository
		{
			add { paramDescriptor += value; }
			remove { paramDescriptor -= value; }
		}
```

**Comment by dgrunwald** [comment]
Your expectation is wrong: the code with `+=` on a field of delegate type is not thread-safe, but the original code is.

The compiler-generated event pattern can only be turned into:
`public static event PageDescriptor StopRepository;`
but then that loses the relation to the field `paramDescriptor`. So this transform is only enabled if both the field and the event have the same name.

**Comment by siegfriedpammer** [comment]
See https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAIU4AbOAcwnguwBYKAFCeuAETigBjBAEsADjAD2CABQB5YACs4gmBShwAdtWQUAogDctMAIIJ6UCnCObT5qAEoA3CRLkWuCgGEKAbxIUgSz4AGyc3HwCwuJSCBRiEAgQYPxCohLSLsRBFAFB7tihVjZqXDyp0RlxAMpSYgBKcGKSUCKxAJ4kAJBd/sQ9XRAoKH7xickV6bEU6AC8FAYQNACucE4UAL7dPQhwYJJGowlJKVFT0hQAtPOLK2ub21vZQXmBr7nPgQXsALIyDn53k8NkA===

**Comment by greenozon** [comment]
Thanks for details on this case!
as well as sharplab live visualizer
Closing issue.
