### ISSUE TITLE
IL sample of "default:" case placed first in switch

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#2155]
As requested, sample of IL making ILSpy move "default:" first in switch. As I stripped out the unimportant stuff, I dubt ilasm accepts this as-is, but it's enough to display what goes on.

```
Orig IL. "default:" placed where expected.

.method ... int32 Blah () cil managed 
{
	IL_0000: ldarg.0
	IL_0001: call blahBlah
	IL_0006: ldfld blah2
	IL_000b: stloc.0
	IL_000c: ldloc.0
	IL_000d: switch (IL_0028, IL_002a, IL_002c, IL_002e, IL_0030)

	IL_0026: br.s IL_0032  <-- This explicit jump makes ILSpy place "default:" last.

	IL_0028: ldc.i4.0
	IL_0029: ret

	IL_002a: ldc.i4.1
	IL_002b: ret

	IL_002c: ldc.i4.2
	IL_002d: ret

	IL_002e: ldc.i4.3
	IL_002f: ret

	IL_0030: ldc.i4.4
	IL_0031: ret

	IL_0032: ldc.i4.2
	IL_0033: ret
}


IL transformed by 3rd party tool. "default:" case placed first in switch, on decompilation.

.method ... int32 Blah () cil managed 
{
	IL_0000: ldarg.0
	IL_0001: call blahBlah
	IL_0006: ldfld blah2
	IL_000b: stloc.0
	IL_000c: ldloc.0
	IL_000d: switch (IL_0028, IL_002a, IL_002c, IL_002e, IL_0030)

	// this reordered (simply optimized, one might argue) version places "default:" first.

	IL_0026: ldc.i4.2
	IL_0027: ret

	IL_0028: ldc.i4.0
	IL_0029: ret

	IL_002a: ldc.i4.1
	IL_002b: ret

	IL_002c: ldc.i4.2
	IL_002d: ret

	IL_002e: ldc.i4.3
	IL_002f: ret

	IL_0030: ldc.i4.4
	IL_0031: ret
}
```

Cheers.

**Comment by siegfriedpammer** [comment]
Well, sorry to "only" give an explanation why it doesn't work as you would expect, but here is my explanation:

I'll assume that you know how the IL switch instruction works, in short: if none of the values match, continue with the next instruction and exactly there is the difference:

In the working case, the next instruction is a `br.s`. The decompiler combines switch + br.s into a single switch and uses the `br.s` as default case.

```
Block IL_0000 (incoming: 1) {
	// ...
	switch (ldloc S_0) {
		case [0..1): br IL_001c
		case [1..2): br IL_001e
		case [2..3): br IL_0020
		case [3..4): br IL_0022
		case [4..5): br IL_0024
		case [long.MinValue..0),[5..long.MaxValue]: br IL_001a
	}
}

Block IL_001a (incoming: 1) {
	br IL_0026
}
```

Is simplified to:

```
switch (ldloc S_0) {
	case [long.MinValue..0),[5..long.MaxValue]: br IL_0026
	case [0..1): br IL_001c
	case [1..2): br IL_001e
	case [2..3): br IL_0020
	case [3..4): br IL_0022
	case [4..5): br IL_0024
}
```

(later the cases are sorted by branch offset...)

In the modified version the ILAst looks like this:

```
Block IL_0000 (incoming: 1) {
	stloc S_0(ldloc i)
	switch (ldloc S_0) {
		case [0..1): br IL_001c
		case [1..2): br IL_001e
		case [2..3): br IL_0020
		case [3..4): br IL_0022
		case [4..5): br IL_0024
		case [long.MinValue..0),[5..long.MaxValue]: br IL_001a
	}
}

Block IL_001a (incoming: 1) {
	stloc S_1(ldc.i4 2)
	leave IL_0000 (ldloc S_1)
}
```

There is no special branch, so the default case actually comes first.

What could we do about this? We could set a flag on the switch instruction to differentiate between simple IL switch -- in that case force the default case last -- and other switches created from branch sequences or string dictionaries... However, I don't think it's worth the effort.

**Comment by dgrunwald** [comment]
ILSpy works exactly as designed here: the C# code we generate is intentionally ordered the same way as the IL code was.
If you run a tool that moves the `default` case up to the beginning of the switch in IL; the exact same will happen in the decompiled C# code.

**Comment by tamlin-mike** [comment]
No worries.

I was thinking about it the other way around, that the switch fallthrough instruction is the default case, and the (non-optimizing, by design) Microsoft compiler always generates a redundant br, even that such a br can make it impossible (if all explicit cases terminate with a `ret`) to know if the identified default case is really part of the switch or is supposed to come after it. An IL optimizer removed the redundant br, and inlined the br target, but otherwise kept everything the same.

Since I myself have never seen a `default` case first in a switch in real code, ever, I would likely have added a super-simple TransformSwitchDefaultLast following TransformSwitch, to keep `default` BB last in decompiled code (provided 1 entry and 1 exit to the BB, whether that entry is an explicit or implicit br after the switch IL statement). (mentioning it now, I wonder why I don't simly do just that locally :-) ).

Again, no worries. It's not something to lose any sleep over. :-) I just provided a sample of it since you wanted to see some IL of how it looked and came to be. Feel free to close this issue.

**Comment by siegfriedpammer** [comment]
Close reason: works as designed.
