### ISSUE TITLE
Suggestion: Mark preview releases as 'pre-releases'

### ISSUE THREAD

**Issue by Nicceboy** [icsharpcode/ILSpy#2170]
**Is your feature request related to a problem? Please describe.**

With current release method, it is hard to track latest "stable" release through GitHub API. This is useful for third-party package providers. 
For example:
```
curl https://api.github.com/repos/icsharpcode/ilspy/releases/latest
```
Returns the latest preview release. If these would be marked as `pre-release`, then GitHub API would return the latest real release instead.

**Describe the solution you'd like**
Mark preview releases as `pre-release`

**Comment by christophwille** [comment]
The 6.1+ series of releases is considered to be stable even with preview labels applied (yes, this release train is considered special). It is a simple tradeoff with the new GH user interface: if a release isn't featured on the homepage (only latest stable is), the newer versions won't enough testing (who clicks through to the entire list of releases?) and thus stability will be lower on RTM... so kind of a catch-22.

**Comment by Nicceboy** [comment]
Thank you for clarification. Did not think about the impact of GH UI change, and how it would affect on release process. Maybe this would be worthy feedback to give for GitHub developers.

**Comment by christophwille** [comment]
We are releasing v6.2 final today. So I am going to close this (fyi: 6.3 will follow a similar approach as 6.2, with a preview release being promoted to stable within a week of release, barring showstopper bugs obviously).
