### ISSUE TITLE
Constructors having a type passed in as parameter shown in that type's Exposed By list

### ISSUE THREAD

**Issue by cateyes99** [icsharpcode/ILSpy#2172]
### Steps to reproduce
1. Create a simple **.NET Core** or **.NET Framework** program (both have the issue) as below
``` C#
namespace ConsoleApp_ILSpyExposeBug
{
    class Program
    {
        static void Main(string[] args)
        {
            B b = new B(new A());
            Console.WriteLine("Hello World!");
        }
    }

    class A
    {
    }

    class B
    {
        A _a;

        public B(A a)
        {
            _a = a;
        }
    }

    class C
    {
        public C()
        {
            A a = new A();
        }
    }
}
```
2. As you can see, `class B`'s **constructor** accepts `class A` as a parameter, while `class C`'s **constructor** uses `class A` inside it instead.
3. By Analyzing `class A`, we can see that `class B` is mistakenly shown in `class A`'s `Exposed By` list! But `class A` for sure won't be exposed by `class B`'s **constructor** of course.
![image](https://user-images.githubusercontent.com/19678455/94230631-7d23f400-ff56-11ea-9ab8-df48b944e961.png)
4. Meanwhile,  `class B`'s **constructor** & `class C`'s **constructor** are correctly shown in `class A`'s `Used By` list.
### Details
* Product in use: _ILSpy_
* Version in use: _6.2.0.6124_

**Comment by dgrunwald** [comment]
The constructor of class B has a parameter of type A, so type A is exposed there.
"exposed by" currently means the type appears in non-private API.

**Comment by cateyes99** [comment]
ic. thanks for the explanation. I didn't think it in that way. I thought **A** `Exposed by` **X** means that others can consume **A** through **X**. I then just close this issue.
