### ISSUE TITLE
How to get a member from MemberReferenceExpression?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2181]
Such as an instance of `MethodDeclaration`, so I can check some infomation, such as: Parameters, ReturnType, etc....

`GetSymbol` return null.

**Comment by dgrunwald** [comment]
`GetSymbol` should work on `MemberReferenceExpression`, do you have any more details?

**Comment by CreateAndInject** [comment]
@dgrunwald Add flowing code in `EscapeInvalidIdentifiers.Run`, you can see: It can be null or not null

```
		public void Run(AstNode rootNode, TransformContext context)
		{
			foreach (var mre in rootNode.Descendants.OfType<MemberReferenceExpression>())
			{
				var symbol = mre.GetSymbol();
				if (symbol != null)
					System.Console.WriteLine(symbol);
				else
					System.Console.WriteLine("<null>");
			}
...
```

**Comment by dgrunwald** [comment]
For method invocations `a.M()` the symbol is on the `InvocationExpression`, not on the `MemberReferenceExpression`.

**Comment by CreateAndInject** [comment]
Thanks!
