### ISSUE TITLE
Variable should be declared inside the loop

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2184]
Transferred from #2182: 
> Hello, can you just help me how to remove this default (int) when decompiler out? When the decompiler has a default (int), when running multi-thread, there will be a lack of data to be run. The way to fix is to declare a variable when running as in the image I edit below. How can I auto-edit the way I do? Thank you very much.
> ![Fix Loi default int](https://user-images.githubusercontent.com/17797687/95274987-760fb680-0871-11eb-918e-b8cf53466c67.PNG)
> ![Loi default int](https://user-images.githubusercontent.com/17797687/95274988-76a84d00-0871-11eb-8a69-688482607b5a.PNG)

**Comment by siegfriedpammer** [comment]
@xuan2261 Can we please continue the discussion here?

My first question would be: Is it possible for you to provide the binary? It is difficult to fully assess the problem just from the screenshots you provided. Thanks!

**Comment by xuan2261** [comment]
> @xuan2261 Can we please continue the discussion here?
> 
> My first question would be: Is it possible for you to provide the binary? It is difficult to fully assess the problem just from the screenshots you provided. Thanks!

We can continue to discuss here. Do you mean provide the program's executable .exe file?

**Comment by siegfriedpammer** [comment]
> Do you mean provide the program's executable .exe file?

Yes, please either the .exe or .dll file you tried to decompile.

**Comment by siegfriedpammer** [comment]
Any update?

**Comment by siegfriedpammer** [comment]
@xuan2261 any update?

**Comment by siegfriedpammer** [comment]
@xuan2261 any update?

**Comment by siegfriedpammer** [comment]
Closing because no response.
