### ISSUE TITLE
Strange cast

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2187]
[Test.zip](https://github.com/icsharpcode/ILSpy/files/5390632/Test.zip)

1.exe
```C#
internal class MyForm : Office2007Form
{
	public void Test()
	{
		((Control)(object)this).Text = "";
	}
}
```

I delete other types and save as 2.exe:
```C#
internal class MyForm : Office2007Form
{
	public void Test()
	{
		Text = "";
	}
}
```

Why?

**Comment by CreateAndInject** [comment]
By the way:
```
public interface _Application
{
	override void _VtblGap1_15();
}
```

Old ILSpy is right:
```
public interface _Application
{
	void _VtblGap1_15();
}
```

**Comment by dgrunwald** [comment]
ILSpy inserts casts like `((Control)(object)this)` when it isn't sure that `MyForm` is derived from `Control`. Usually because some assembly references could not be resolved.

**Comment by CreateAndInject** [comment]
@dgrunwald 
1. Base type `Office2007Form` is defined in `DevComponents.DotNetBar2.dll`, which I have already attach it.
2. When I delete other types, ILSpy can decompile it correctly, so it's not `because some assembly references could not be resolved`

**Comment by CreateAndInject** [comment]
@siegfriedpammer Can you check it? The assembly reference exists in the folder.

**Comment by CreateAndInject** [comment]
@dgrunwald @siegfriedpammer I found the reason : Remove the duplicate assembly references(such as remove System.Windows.Forms(2.0.0.0) as keep System.Windows.Forms(4.0.0.0)), then ILSpy can decompile it corrently.

It's not necessary to fix it for me now.

Can you see the second issue:
New ILSpy:
```C#
public interface _Application
{
	override void _VtblGap1_15();
}
```

Old ILSpy is right:
```C#
public interface _Application
{
	void _VtblGap1_15();
}
```

**Comment by CreateAndInject** [comment]
I can add a transform or modify VtableLayout to resolve it by myself.
