### ISSUE TITLE
TDCU fails to transform display-classes that are copied

### ISSUE THREAD

**Issue by bzmework** [icsharpcode/ILSpy#2188]
ILSpy_binaries_6.2.1.6137 Error:
_003C_003Ec__DisplayClass35_0 CS_0024_003C_003E8__locals0 = new _003C_003Ec__DisplayClass35_0();

ILSpy_binaries_5.0.2.5153 Ok:
IReadOnlyList<Permission> readOnlyList = await GetGrantedPermissionsAsync(role);

**Comment by siegfriedpammer** [comment]
Would it be possible for you to provide the binary / assembly?

**Comment by bzmework** [comment]
Please see the attachment
Change the file suffix to RAR


[dllrar.log](https://github.com/icsharpcode/ILSpy/files/5397496/dllrar.log)

**Comment by siegfriedpammer** [comment]
Thank you for providing the assembly.

This particular problem can be solved by activating aggressive inlining of locals (Options > Decompiler > Other > Always inline local variables if possible).

I will have to take a look whether we can improve the decompiler so it's not necessary to use aggressive inlining.
