### ISSUE TITLE
Provide a .vsconfig

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2200]
Basically "codify" what we have in our README/How to build. See https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

**Comment by joshuacookdev** [comment]
I built the .vsconfig, but feel like the documentation in the readme (if not other places as well) should be updated to reflect the change - is that something you would like to update in this thread also?

**Comment by christophwille** [comment]
Sorry for taking a bit to get back to you - yes, the README should reflect that too.

**Comment by joshuacookdev** [comment]
No worries at all on timing - I know how stressful it can be to wear all of these hats. I appreciate the feedback at all!

And sounds good to me - I'll update the readme on the PR branch after work today.

**Comment by joshuacookdev** [comment]
Update to say that I received some feedback on the vsconfig from other devs, and am spending some time paring it down to absolute bare requirements. Been uninstalling/reinstalling in Sandbox to make sure everything lines up. I marked the PR as a draft until the list of components is minimized and the readme is updated.
