### ISSUE TITLE
Error causing build to fail

### ISSUE THREAD

**Issue by hippolippo** [icsharpcode/ILSpy#2209]
After struggling to get dotnet to work, I installed it using snap and was able to run the `dotnet build Frontends.sln` command but (this is with ubuntu 18.04) It gave red errors and the build failed.
![image](https://user-images.githubusercontent.com/15696741/98265757-7924c200-1f57-11eb-8461-7890448220bc.png)

**Comment by christophwille** [comment]
Are you building Release or Debug? You have the latest code checked out?

**Comment by siegfriedpammer** [comment]
Thanks for reporting this!

**Comment by hippolippo** [comment]
> Thanks for reporting this!

What do I have to do to fix it

**Comment by christophwille** [comment]
For Debug builds, it works right away. The Release build needs a new NuGet package.
