### ISSUE TITLE
fixed statements and arrays of pointers

### ISSUE THREAD

**Issue by LADSoft** [icsharpcode/ILSpy#2215]
so I got rid of extraneous conv.u statements.   But if I have an array of pointers to some structure, the code my compiler compiler compiles is now decompiled the way I expect, however, CSC doesn't like it because it doesn't like unsafe.as where the second argument to the as is a pointer.    Find attached an example...   I'm wondering if this is something you can/will fix, or if I need to find a way to generate code that is happily interpreted by ilspy.   If the latter can you advise me?

[t1.zip](https://github.com/icsharpcode/ILSpy/files/5520283/t1.zip)

**Comment by dgrunwald** [comment]
Fixed in ILSpy master.

New output:
```
public unsafe static int main(int argc, void* argv)
{
	for (int i = 0; i < 10; i++)
	{
		((s*)System.Runtime.CompilerServices.Unsafe.As<void_ptr_array_40, IntPtr>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref q.vv, (nint)i * (nint)sizeof(s*))))->b = 0;
	}
	s s = default(s);
	q.aa = &s;
	for (int j = 0; j < 10; j++)
	{
		System.Runtime.CompilerServices.Unsafe.As<s_array_120, s>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref q.vv1, (nint)j * (nint)sizeof(s))).b = 0;
	}
	return 0;
}
```
