### ISSUE TITLE
issue 2076 marked as resolved but actually not.

### ISSUE THREAD

**Issue by DingMingyu** [icsharpcode/ILSpy#2225]
![Capture](https://user-images.githubusercontent.com/2093398/99505400-c1160100-29bb-11eb-9ada-727662007158.PNG)
![Capture2](https://user-images.githubusercontent.com/2093398/99505500-dee36600-29bb-11eb-9e12-629af0f2055f.PNG)

**Comment by siegfriedpammer** [comment]
Can you provide a concrete example/binary?

**Comment by siegfriedpammer** [comment]
Any update @DingMingyu ?

**Comment by siegfriedpammer** [comment]
Closing due to missing feedback.
