### ISSUE TITLE
can't run on win10

### ISSUE THREAD

**Issue by guohaitk** [icsharpcode/ILSpy#2236]
### Steps to reproduce
1. download and unzip 
2. click ILSpy.exe ,no response
3. in event viewer -- windows log -- application ,this are tow error .one called event 1000,application error.another is event 1026 .net runtime.
I had setup .net Farmework version 4.7.2,hope you can resolve it.
thank for you share
### Error message shown
1000
错误应用程序名称: ILSpy.exe，版本: 7.0.0.6225，时间戳: 0xb1d492cc
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.207，时间戳: 0x746c1866
异常代码: 0xe0434352
错误偏移量: 0x0000000000023e49
错误进程 ID: 0x16b8
错误应用程序启动时间: 0x01d6c889a61c4a80
错误应用程序路径: D:\Download\ILSpy_binaries_7.0.0.6225-preview1\ILSpy.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 02a8e76a-5f11-47f8-b832-81834c56f049
错误程序包全名: 
错误程序包相对应用程序 ID: 
1026 
应用程序: ILSpy.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.IO.FileNotFoundException
   在 ICSharpCode.ILSpy.App..ctor()
   在 ICSharpCode.ILSpy.App.Main()

**Comment by christophwille** [comment]
We are all developing on Windows 10, and have never seen that error - is there anyting special about your setup? (virus scanner, policies, ...)

**Comment by guohaitk** [comment]
> We are all developing on Windows 10, and have never seen that error - is there anyting special about your setup? (virus scanner, policies, ...) And... Win10 should have netfw4.8 by default installed.
> 
> 
thank for your reply
I setup .net farmework because I think it maybe work，on my system nothing special，just download and unzip,then run.
I had try ILSpy v 7.0.0.6225-preview1 、6.1.0.5902、5.0.2.5153。
and try close virus scanner,the problem is still。
even  have a bath，you know it‘s helpful for goodluck，๑乛◡乛๑

**Comment by siegfriedpammer** [comment]
Maybe the tip I gave a while back might help you: https://github.com/icsharpcode/ILSpy/issues/798#issuecomment-351256927

**Comment by guohaitk** [comment]
> Maybe the tip I gave a while back might help you: [#798 (comment)](https://github.com/icsharpcode/ILSpy/issues/798#issuecomment-351256927)

I user tools to unblock folder,tips unnecessary.
according to the errors，I think it's caused by KERNELBASE.dll or ILSpy application.
so I try to fix dll file，I use DirectX Repair to repair dll files。
then run in system safe model ,the problem still exists。
so I think the error message about ICSharpCode.ILSpy.App..ctor() and ICSharpCode.ILSpy.App.Main() maybe help
I copy the zip to anthor compute ,it's win7,run application ,it tips need .net farmework v4.0.
I download .net farmework v4.8 runtime. it works well.
thank you (　＾∀＾)
