### ISSUE TITLE
Automatically deploy ilspycmd in nuget at each new version

### ISSUE THREAD

**Issue by GreyXor** [icsharpcode/ILSpy#2245]
**Is your feature request related to a problem? Please describe.**
While the version of https://www.nuget.org/packages/ilspycmd/ is not up to date on NuGet, it would be useful to offer automatic deployment to get the latest version. 
The packet ICSharpCode.Decompiler is automatically sent to Nuget. I propose to do the same thing with ilspycmd to avoid having a late version.

**Describe the solution you'd like**
This https://www.nuget.org/packages/ilspycmd/ package should reflect the actual latest version

**Comment by christophwille** [comment]
There is no deployment automation - ilspycmd v7p1 was intentionally not published.

**Comment by GreyXor** [comment]
> 
> 
> There is no deployment automation - ilspycmd v7p1 was intentionally not published.

Hello @christophwille,
ilspycmd 6.2.1 was intentionally not published too ?

I am well aware that there is currently no automatic deployment. This is precisely the subject of my issue. For those who use ilspycmd (like me) it would be very convenient.

We would have to follow the same pattern as ICSharpCode.Decompiler. just publish each version. this would give us the possibility to choose easily with the dotnet tool.

**Comment by christophwille** [comment]
There is no deployment automation. For none of the artefacts.

**Comment by GreyXor** [comment]
OK,
So you may consider a Github action for that. it would be useful. It would save you time, automatic and we would have all the versions available.

**ilspycmd 6.2.1 was intentionally not published too ?**

**Comment by christophwille** [comment]
The signing of the executable happens locally, and that currently is the state of things. Given our release cadence investing in automation won't pay off.

**Comment by GreyXor** [comment]
ok, apart from the fact that you refused to answer the question as to **why ilspycmd 6.2.1 is not on nuget**. i thank you for the time spent answering me. I will automate this on my side on a reflective fork. We can close this feature request.
