### ISSUE TITLE
UI icon themes support and non-flat theme for Windows 7

### ISSUE THREAD

**Issue by FallenPhoenix** [icsharpcode/ILSpy#2246]
New UI icon theme may looks not bad on Windows 10. But icons which was in ILSpy 5.x and earlier versions looks much better on Windows 7. So add please feature to select icons theme between flat and non-flat.

Here screenshots of ILSpy 5.x and 6.x. look on Windows 7:

ILSpy 5.x
![ILSpy 5](https://user-images.githubusercontent.com/1318291/102626058-60631b00-4157-11eb-8970-179d8d3ebe59.png)

ILSpy 6.x
![ILSpy 6](https://user-images.githubusercontent.com/1318291/102626065-622cde80-4157-11eb-8458-ad89723ba28c.png)

**Comment by christophwille** [comment]
That's a no. We do not support out of support operating systems.

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
