### ISSUE TITLE
When namespace is same with type name, should not add namespace

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2257]
input:
``` cs
using System;

namespace ILSpyBugs {
    class ILSpyBugs {
    }
    class Class1 {
        Type Method1() {
            return typeof(ILSpyBugs);
        }
    }
}
```

ilspy output:
``` cs
internal class Class1
{
	private Type Method1()
	{
		return typeof(ILSpyBugs.ILSpyBugs);
	}
}
```

ilspy version:  7.0.0.6275-preview2

**Comment by wwh1004** [comment]
maybe adding gloabl:: is also an available way. it should be easier to implement. like "global::ILSpyBugs.ILSpyBugs"

**Comment by siegfriedpammer** [comment]
Currently, if something is not unambiguous we fully-qualify it in order to avoid any bugs. Not sure how adding the `global` prefix would help...

**Comment by wwh1004** [comment]
but vs can't compile
``` cs
internal class Class1
{
	private Type Method1()
	{
		return typeof(ILSpyBugs.ILSpyBugs);
	}
}
```
Error CS0426 The type name 'ILSpyBugs' does not exist in the type 'ILSpyBugs'

**Comment by siegfriedpammer** [comment]
ah, sorry, I was wrong, now I understand, yes, adding global:: would fix this...
