### ISSUE TITLE
[Output] Syntax error for nested using () {}

### ISSUE THREAD

**Issue by quangkieu** [icsharpcode/ILSpy#2265]
So the output code by ILSpy is not able to compile as nested **using** syntax is wrong in the output

### Erroneous output
```c#
		XmlDocument inputXml = new XmlDocument();
		inputXml.load(@"C:\input.xml");
        string text = $"{path}{Guid.NewGuid().NullSafeToString()}.htm";
        XsltSettings xsltSettings = new XsltSettings();
        xsltSettings.EnableScript = true;
        xsltSettings.EnableDocumentFunction = true;
        XslCompiledTransform xslCompiledTransform = new XslCompiledTransform();
        using (StringReader input = new StringReader(htmlConverterXsl))
        {
            using XmlTextReader stylesheet = new XmlTextReader(input);
            xslCompiledTransform.Load(stylesheet, xsltSettings, null);
        }
        using (Stream stream = new MemoryStream())
        {
            xslCompiledTransform.Transform(inputXml, null, stream);
            stream.Position = 0L;
            using StreamReader streamReader = new StreamReader(stream);
            using StreamWriter streamWriter = new StreamWriter(text);
            streamWriter.Write("<meta http-equiv='Content-Type' content='text/html;charset=utf-8'>" + streamReader.ReadToEnd());
        }
```
### Expected 
```c#
		using (var a = new aa()){
			using (var b = new bb()){
				...
			}
		}
```
And I am not sure .NullSafeToString() needed as NewGuid() already return safe string
### Details
* Product in use: ILSpy 6.2.1.6137
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by siegfriedpammer** [comment]
Looks perfectly fine to me... can you please provide the binary?

> So the output code by ILSpy is not able to compile as nested using syntax is wrong in the output

What makes you think any of these using statements need to be nested?

> And I am not sure .NullSafeToString() needed as NewGuid() already return safe string

Take a look at the IL code, if the method call is there, ILSpy will preserve it. ILSpy is not an optimizer, but a decompiler that tries to reconstruct the original code as closely as possible. Also, neither the compiler nor a decompiler could possibly know that `NullSafeToString` is unnecessary, because it is not a special method known to the compiler.

**Comment by dgrunwald** [comment]
The syntax `using XmlTextReader stylesheet = new XmlTextReader(input);` is new in C# 8: [Enhanced using](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/using.md)
If you don't want it, you can disable it in the ILSpy options.

**Comment by quangkieu** [comment]
Oh that why. The dll is target 4.6.2 i think. Would check back

**Comment by quangkieu** [comment]
I also did not know about this syntax

**Comment by dgrunwald** [comment]
.NET 4.6.2 shouldn't be an issue; the `.csproj` file written by ILSpy should contain the `<LangVersion>` tag to enable the newer language version even on older frameworks.
But to recompile the code, you will need to use a Visual Studio version that supports the selected C# version (check the dropdown in ILSpy's toolbar, it lists the minimum required versions).

**Comment by quangkieu** [comment]
Thanks. I think I am good now
