### ISSUE TITLE
Must assign a local var for linq expression

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2267]
input:
``` cs
void Method1() {
	var list = new List<string>();
	var query = from s in list
				from c in s
				where c > 1
				select new {
					a = c + 1,
					c
				};
}
```

output:
``` cs
private void Method1()
{
		from s in new List<string>()
		from c in s
		where c > '\u0001'
		select new
		{
			a = c + 1,
			c = c
		};
}
```

compiler error:
Error CS0201 Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement

**Comment by siegfriedpammer** [comment]
Triage: This is due to the "Remove dead variables" setting being used.

**Comment by siegfriedpammer** [comment]
Problem: The `DeclareVariables` step runs before extension methods and further LINQ expressions are introduced. I see three options here:
1) We teach DeclareVariables.IsValidInStatementExpression about expressions that will be transformed further and declare the variable as required.
2) We disable LINQ expression transformation in expressions that are not part of the right side of an assignment.
3) Leave the error as is, the "Remove dead stores" setting has "use with caution!" added for a reason...

Option 1 would be better/nice, however this would mean a lot of work.
Options 2 and 3 are little to no work...

**Comment by dgrunwald** [comment]
I think easiest is option 2: avoid using LINQ if the direct parent is an `ExpressionStatement`.

**Comment by wwh1004** [comment]
but sometimes can only use linq expression to decompile. see https://github.com/icsharpcode/ILSpy/issues/2264

**Comment by siegfriedpammer** [comment]
> I think easiest is option 2: avoid using LINQ if the direct parent is an `ExpressionStatement`.

Come to think of it... we could insert a "discard-assignment" in those cases after the LINQ transformation...
