### ISSUE TITLE
Make a simple DMG for Mac.

### ISSUE THREAD

**Issue by StupidRepo** [icsharpcode/ILSpy#2271]
**Is your feature request related to a problem? Please describe.**
Just make a compiled version of it for Mac because I am having so much trouble with .net sdk's and building this stupid application on Mac.

Make a DMG version for us Mac users >:(

**Describe the solution you'd like**

**Additional context**

**Comment by christophwille** [comment]
This is the wrong repo for this request. Has to go here: https://github.com/icsharpcode/AvaloniaILSpy/issues
