### ISSUE TITLE
Add precompiled Linux and MacOS build

### ISSUE THREAD

**Issue by iMonZ** [icsharpcode/ILSpy#2274]
Title is self explained

**Comment by christophwille** [comment]
ilspycmd is shipped via https://www.nuget.org/packages/ilspycmd/ (runs anywhere .NET Core is available). If, however, you refer to a UI version, you have to go to https://github.com/icsharpcode/AvaloniaILSpy/

**Comment by iMonZ** [comment]
Oh okay

And there is no merge possible?

**Comment by christophwille** [comment]
You mean one UI codebase for win/linux/mac? No, the main UI is WPF and the other project is Avalonia.

**Comment by iMonZ** [comment]
> You mean one UI codebase for win/linux/mac? No, the main UI is WPF and the other project is Avalonia. (Note: the debug build UI on Windows has way more options than the release builds)

An there are no plans for switching?
Or Maybe another cross platform ui?

**Comment by christophwille** [comment]
There is no plan for that (and we have the download numbers for AvaloniaILSpy - and quite frankly, there is no user base)
