### ISSUE TITLE
Exception when assembly doesn't contain `TargetFrameworkId` data

### ISSUE THREAD

**Issue by jaredpar** [icsharpcode/ILSpy#2275]
### Steps to reproduce

Created a C# file called `example.cs` with the following content:

```c#
interface I1 { }
```

Then run the following command: 

```cmd
> dotnet exe "C:\Program Files\dotnet\sdk\5.0.101\Roslyn\bincore\csc.dll" example.cs /t:library /noconfig
```

### Error message shown

Open the resulting `example.dll` file in ILSpy and you will get the following error message:

```
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ICSharpCode.Decompiler.Metadata.DotNetCorePathFinderExtensions.DetectTargetFrameworkId(PEReader assembly, String assemblyPath)
   at ICSharpCode.ILSpy.LoadedAssembly.<GetTargetFrameworkIdAsync>d__6.MoveNext()
```

### Details
* Product in use:ILSpy 6.2.1.6137

**Comment by siegfriedpammer** [comment]
So your quiz from twitter made ILSpy crash 😄

**Comment by jaredpar** [comment]
> So your quiz on twitter made ILSpy crash 

Indeed it did :smile:

**Comment by siegfriedpammer** [comment]
I've fixed the bug by assuming MetadataVersion "4.0" (used as framework version) if it's empty... however, it might be more reasonable to assume framework version 5.0 instead?

**Comment by jaredpar** [comment]
Think `4.0` is probably better. This can work effectively well in pretty much any framework .

**Comment by siegfriedpammer** [comment]
Makes sense, thanks!
