### ISSUE TITLE
Unnecessary temporary variables introduced when dup'ing float/double/long constants

### ISSUE THREAD

**Issue by jfd16** [icsharpcode/ILSpy#2277]
### Steps to reproduce
Decompile a method with the following IL:
```
ldc.i4.1
conv.r8
dup
dup
dup
call void [A]A.MyClass::foo(float64, float64, float64, float64)
ret
```
### Expected output
```csharp
MyClass.foo(1.0, 1.0, 1.0, 1.0);
```
### Actual output
```csharp
double num = 1.0;
MyClass.foo(num, num, num, num);
```
A similar issue exists with `long` constants (replace `conv.r8` with `conv.i8`).

### Details
* Product in use: e.g. ILSpy
* Version in use: 6.0.0.5836

**Comment by dgrunwald** [comment]
The C# compiler doesn't turn `foo(1.0, 1.0, 1.0, 1.0);` into a bunch of dup instructions; so I'm not sure why you think ILSpy should perform the reverse transformation.

On the other hand, if you recompile
```
double num = 1.0;
MyClass.foo(num, num, num, num);
```
in release mode, you'll find that the C# compiler replaces the local variables with a stack slot (thus using a bunch of `dup` instructions).

So I think the current ILSpy output is more accurate to the original code than your suggestion.
