### ISSUE TITLE
Having same var at class level and inside function leads to error

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2280]
### Input code
orig code:
![image](https://user-images.githubusercontent.com/765343/105379134-36e55580-5c15-11eb-91a0-a704ef5499d5.png)

ILSpy code:
![image](https://user-images.githubusercontent.com/765343/105379209-48c6f880-5c15-11eb-9eac-8bdc2dd972bf.png)

as you see 2nd (rightmost) part is missing this.

### Details
* Product in use: ILSpy version 7.0.0.6297-preview2

**Comment by siegfriedpammer** [comment]
Can you provide the assembly? I could not reproduce this using a minimal sample. Thanks!

**Comment by greenozon** [comment]
sent

**Comment by siegfriedpammer** [comment]
This is related to #2267. If you decompile the project using at least C# 7.0, discard assignments are used and the code is compilable. There is one more bug in the `DeclareVariables` logic, which makes it generate a simple name without all the additional checks present in `AssignVariableNames`.

**Comment by greenozon** [comment]
Thank you for you time/analsys and reply!
For some reason older C#5.0 is a must for that kind of stuff..
anyway, this is easy nut, so no big worries
Feel free to close this issue
