### ISSUE TITLE
Enable server garbage collection for ILSpy and ilspycmd

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#2286]
Enabling server garbage collection can let ILSpy decompile large project 3x\~4x and small project 2x\~3x faster than before.
It is easy to enable it:
```
<configuration>
  <runtime>
    <gcServer enabled="true" />
  </runtime>
</configuration>
```

**Comment by wwh1004** [comment]
Decompile mscorlib in my computer:

no server gc:
Decompilation complete in 16.2 seconds.
server gc:
Decompilation complete in 6.4 seconds.

Decompile default assembly list (mscorlib, System, System.Core, System.Xml, System.Xaml, WindowsBase, PresentationCore, PresentationFramework) as solution in my computer:

no server gc:
Elapsed time: 80.3 seconds.
server gc:
Elapsed time: 21.5 seconds.

**Comment by dgrunwald** [comment]
Thanks for the hint!

My run times:
mscorlib without server gc: Decompilation complete in 12,2 seconds.
mscorlib with server gc: Decompilation complete in 5,8 seconds.
default assembly list without server gc: Elapsed time: 58,1 seconds.
default assembly list with server gc: Elapsed time: 29,4 seconds.

**Comment by dgrunwald** [comment]
I'm not quite sure how this applies to ilspycmd, given that that is using .NET Core.

**Comment by siegfriedpammer** [comment]
https://stackoverflow.com/questions/52525205/setting-gcserver-true-when-running-on-linux-in-net-core-project
