### ISSUE TITLE
Ensure that all labels generated by StatementBuilder are unique.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2291]
[test.zip](https://github.com/icsharpcode/ILSpy/files/5905070/test.zip)
There're two `end_IL_0014` definitions in `Main`.

**Comment by CreateAndInject** [comment]
@siegfriedpammer There're some more places should call `EnsureUniqueLabel`, such as:
https://github.com/icsharpcode/ILSpy/blob/a01c63dc62ba118d9fdfed91c12b6b5fd35012a4/ICSharpCode.Decompiler/CSharp/StatementBuilder.cs#L390-L394

**Comment by CreateAndInject** [comment]
@siegfriedpammer Why don't call `EnsureUniqueLabel` directly?
```C#
			if (!endContainerLabels.TryGetValue(inst.TargetContainer, out string label))
			{
				label = "end_" + EnsureUniqueLabel(inst.TargetContainer.EntryPoint);
				endContainerLabels.Add(inst.TargetContainer, label);
			}
```

**Comment by siegfriedpammer** [comment]
I wanted to number the "end container" labels independently from the block labels. Not sure if it makes a significant difference.
