### ISSUE TITLE
ILSpy crash when searching for a method

### ISSUE THREAD

**Issue by Oberndorfer** [icsharpcode/ILSpy#2293]
### Steps to reproduce
1. Open Search Pane
2. Choose "Search for: Method"
3. Enter 3 or more characters

### Error message shown
Sorry we crashed.
NullReferenceException...

![ILSpy Crash](https://user-images.githubusercontent.com/40287684/106871267-5c249a00-66d2-11eb-845c-8df535d87764.png)

### Details
ILSpy version 6.2.1.6137

**Comment by siegfriedpammer** [comment]
Possible duplicate of #2241. Could you try one of the 7.0 previews?

**Comment by Oberndorfer** [comment]
Yes, it is resolved with ILSpy version 7.0.0.6291-preview2

**Comment by siegfriedpammer** [comment]
Duplicate of #2241
