### ISSUE TITLE
Found some issues in code after performing static analysis

### ISSUE THREAD

**Issue by IlyaGainulin** [icsharpcode/ILSpy#2294]
Hello. Recently checked ILSpy project with static code analyzer - PVS-Studio. Guess, it's found some issues and possible errors in the project's code. If you are interested in results, please, [check this article](https://habr.com/ru/company/pvs-studio/blog/540934/).

**Comment by siegfriedpammer** [comment]
note: already fixed 1) in 899214c658e07d15cdb755830b02d40cf720f504
