### ISSUE TITLE
Null reference exception on search of any type or member

### ISSUE THREAD

**Issue by AndrewAdov** [icsharpcode/ILSpy#2296]
### Steps to reproduce
1. Include in the list all of assemblies from the Microsoft Visual Studio Professional 2019 Version 16.8.4 installation folder
2. Try to search of any type or member

### Error message shown

![image](https://user-images.githubusercontent.com/60420606/107216242-8bfad700-6a1d-11eb-9722-aabd7805ffc7.png)

### Details
* ILSpy version 6.2.1.6137 (binaries)

**Comment by siegfriedpammer** [comment]
Duplicate of #2241 
Duplicate of #2293

Please try using the most recent 7.0 preview, thanks!

**Comment by AndrewAdov** [comment]
> Please try using the most recent 7.0 preview, thanks!

The preview version looks good and much faster. Thanks!
