### ISSUE TITLE
Change Font Size Through Mouse Scrolling

### ISSUE THREAD

**Issue by JasonBock** [icsharpcode/ILSpy#2298]
**Is your feature request related to a problem? Please describe.**
Not a problem per-se.

**Describe the solution you'd like**
In tools like Visual Studio and Notepad++, you can hold down the Control key and scroll with the mouse wheel, which will change the font size in the text editor. It would be nice if ILSpy would have that option in its code viewer as well. I know you can change the font via _View -> Options -> Display_, but having that scrolling option is a bit quicker.

Also, if this feature is added, it would also be nice to have a percentage somewhere in the code viewer that tells you what size the font is currently at. Visual Studio has this, but Notepad++ doesn't, and I like being able to see how I can get back to 100%. It's also editable in Visual Studio which is a nice-to-have.

**Additional context**
Just showing what Visual Studio has for this in terms of the font size as a percentage:
![image](https://user-images.githubusercontent.com/904213/107374109-dd05dc00-6aac-11eb-854c-2055e6d99eb5.png)

**Comment by steamos** [comment]
I've started looking at this the text scaling part works but requires some tidying and also I need to add the percentage box.

Code changes here: https://github.com/steamos/ILSpy/tree/text_scaling
