### ISSUE TITLE
Must Create DependencySource on same Thread

### ISSUE THREAD

**Issue by AfshinZavvar** [icsharpcode/ILSpy#2299]
after few days of using ILSpy version 7.0.0.6291-preview2 I'm getting error and I need to remove  ILSpy.xml and re create whole list again and again

![image](https://user-images.githubusercontent.com/21095394/107589284-c5b82180-6c59-11eb-98a9-d41ff1afedc0.png)

**Comment by siegfriedpammer** [comment]
This will be difficult to analyze because it depends on the assemblies you have loaded. Would you be able to help us investigate, by testing whether it only happens once a specific assembly is added to the list? Thank you!

**Comment by siegfriedpammer** [comment]
Seems this is fixed. If the problem still occurs, please open a new issue. Thanks!
