### ISSUE TITLE
NuGet: Unable to load the service index

### ISSUE THREAD

**Issue by d3rpym00** [icsharpcode/ILSpy#2300]
Trying to compile ILSpy for the first time, I keep getting an error that says Unable to load the service index for the source https://dotnet.myget.org/F/symreader-converter/api/v3/index.json. Sure enough, when I go to that website and check there, it says Feed does not exist.

**Comment by christophwille** [comment]
This has long been fixed on master.

**Comment by d3rpym00** [comment]
So then did I download the wrong version?
