### ISSUE TITLE
Decompile Reflection.Emit generated assembly from memory

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [icsharpcode/ILSpy#2304]
**Is your feature request related to a problem? Please describe.**
Does the ILSpy API or the ICSharpCode.Decompiler API allow decompiling a dynamically generated assembly (e.g. Reflection.Emit)? It appears all entry APIs require a `PEFile`.

**Describe the solution you'd like**
I would like to be able to pass an `Assembly` instance and decompile the C# for that assembly.

**Additional context**
I found https://github.com/icsharpcode/ILSpy/issues/356 but the issue is vague and it isn't entirely clear if this is supported.

**Comment by dgrunwald** [comment]
If you have a full in-memory assembly, you can use the `PEFile` constructors taking a `Stream` or `PEReader` as input.

While these also take a `string fileName` parameter, this is only used to initialize the `PEFile.FileName` property; it doesn't have to be a valid filename on disk. ILSpy uses this when loading assemblies from NuGet packages without having to unpack them on disk.

But I'm not sure if Reflection.Emit dynamic assemblies are actually full assemblies. Is there some way to fill a System.Reflection.Metadata.MetadataReader with the information from a dynamic assembly?

**Comment by christophwille** [comment]
@AaronRobinsonMSFT is this resolved?

**Comment by AaronRobinsonMSFT** [comment]
@christophwille I don't think so actually. I fell back to using https://github.com/Lokad/ILPack, but that also had issues. The big issue is the following:

> Is there some way to fill a System.Reflection.Metadata.MetadataReader with the information from a dynamic assembly?

Which I think that ILPack attempts to do but is difficult to perform correctly. This issue can be closed as I've moved onto another approach though.
