### ISSUE TITLE
Cant Reflect with ILSpy

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2317]
Originally posted at #2316 by @balangi

---

### Problem
Hi there,
I have an Assembly when I try to reflect with ILSpy return some error.I sent this file to your team may you can help me.notice to utils folder in assembly there are most of error
with best regards 

balangi

https://drive.google.com/file/d/1wPbeoV1lMK_HCg-cP1MDeZJ7PvogujP0/view?usp=sharing

**Comment by siegfriedpammer** [comment]
@balangi

Could you please specify, which problem you would want us to fix?

Looking at the assembly, it will be hard to fix all the issues because
1) the assembly is obfuscated,
2) the original source code was written in F#, thus it is very unlikely for ILSpy to be able to produce compilable code. F# and C# are very different and the result will be very ugly code.

**Comment by balangi** [comment]
hi,
you're right, I have two problem and to this reason I first try with
SmartAssembly for fix Obfuscation
but after that I try with ILSpy for reflect assembly that I get some error
like below:

System.InvalidCastException: Unable to cast object of type
'ICSharpCode.Decompiler.TypeSystem.SpecialType' to type
'ICSharpCode.Decompiler.TypeSystem.Implementation.TypeWithElementType'.

may you help me?

I also tried with another reflector called 'dnSpy' and result was very
different
dnSpy reflector return a lot of files that are attached to assembly and
reflect better code but there is also some problem and exceptions


with best regards
balangi

**Comment by siegfriedpammer** [comment]
Triage: the InvalidCastException occurs in `@06004914 ns73.Stream9.method_0`.
