### ISSUE TITLE
Add conditional sub directory support

### ISSUE THREAD

**Issue by caviyacht** [icsharpcode/ILSpy#2330]
**Is your feature request related to a problem? Please describe.**
A commit added last year https://github.com/icsharpcode/ILSpy/commit/9742a7cfae4e50df6dabf6200382dcfdaebb4ff3 has started creating sub directories based on the namespace. This has caused some pain as the projects I am decompiling have a very long default namespace (ex: Company.Project.Plugin.PluginName). 

This causes the code to be very nested when saved as a project.

**Describe the solution you'd like**
I would like a way to have the previous behavior be togglable and/or allow the use of a default namespace when generating the folder structure (ex, default would be Company.Project.Plugin.PluginName and everything under that could have the sub directories as the commit solves).

**Additional context**
An example from v6 would product something like this:

```
Company.Project.Plugin.PluginName
Company.Project.Plugin.PluginName.Models
Company.Project.Plugin.PluginName.Views
```

v7 now does this:

```
Company
  Project
    Plugin
      PluginName
        Models
        Views
```

Ideal output would be this:

```
Company.Project.Plugin.PluginName
  Models
  Views
```

**Comment by Nikkelmann** [comment]
I fell into the same problem today - had not specified a version on "dotnet tool update", so it just took the latest and ran with it.
Lesson learned, always specify a version...
