### ISSUE TITLE
BAML Decompiler public API design

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2337]
For ILSpy 7.1 we are planning to expose a reusable API to the BAML decompiler. This is a brain storming issue to develop a minimal API that covers most immediate known use-cases.

@CreateAndInject since you asked for this in the first place. What is necessary to get the BAML decompiler into shape for public use?

**Comment by CreateAndInject** [comment]
![image](https://user-images.githubusercontent.com/2529999/111162134-d6e8ab00-85d6-11eb-9de6-be79ea4313ec.png)


I want to convert my plugin from dnSpy to ILSpy, dnSpy can get assemblyReferences.

**Comment by siegfriedpammer** [comment]
I would really like to understand why you need assembly references as a return value from a method called "Decompile". Doesn't make much sense to me. Is the plugin you are developing somewhere publicly available so I can take a look at the source code to understand your use case better? Thanks!

**Comment by CreateAndInject** [comment]
Not every dependency assembly appear in the `AssemblyRef Table` of `Metadata`, so I want to analyze xaml to get all dependencies.

**Comment by siegfriedpammer** [comment]
So, is this the only piece of information you would want from the decompiler? Do you need the fully processed/decompiled `XDocument` as well? Because, if not, it would be better to design an API that does not actually do the full processing, but rather parses the BAML stream and returns all records or the part you are interested in. Are there other parts of the BAML stream you might be interested in? Thanks!

**Comment by CreateAndInject** [comment]
I only need this information currently.

**Comment by CreateAndInject** [comment]
Of course, I need the xaml text and asmRefs, what I need is dnSpy do.
