### ISSUE TITLE
KERNELBASE.DLL crash

### ISSUE THREAD

**Issue by ParzivalWolfram** [icsharpcode/ILSpy#2348]
### Steps to reproduce
1. Start ILSpy

### Error message shown

```
APPCRASH with faulting DLL: KERNELBASE.DLL
```
![Screenshot_2021-03-21_17-13-21](https://user-images.githubusercontent.com/30007617/111922813-0a5d8680-8a6a-11eb-8235-386f5a27feb0.png)
### Details
- ILSpy [ver. 7.0.0.6372-preview3](https://github.com/icsharpcode/ILSpy/releases/tag/v7.0-preview3)
- OS: Win7 SP1 or Win10 20H2
- Tried all solutions mentioned in #2236, nothing helped

**Comment by siegfriedpammer** [comment]
As this is not an exception which can be reproduced, I will try my best to help you.

* Do you have all Windows Updates installed?
* Did you try SFC scan?
* Did you make sure at least .NET framework 4.7.2 is installed on your computer? Uninstall? Reinstall?

You could also try to create a crash dump using task manager (as soon as this dialog is displayed, do not click anything, go to task manager > details > create dump file). If you provide the dump file debugging the issue remotely might be possible.

**Comment by ParzivalWolfram** [comment]
Windows Updates all applied, aside from a rare one or two that has issues with Virtualbox. SFC reports no issues. Using .NET 4.8, should've specified that in the original issue, sorry. I did notice that, in ProcMon, ILSpy can't find a LARGE number of DLLs, [some of them being looked for in the wrong places](https://imgur.com/a/DYuFcFj) or... [being Direct3D](https://i.imgur.com/LxYotLY.png), the latter striking me as especially strange.
Dump located [here](https://anonfiles.com/WeA5ofm5u4/ILSpy.DMP_zip) (can't upload to GitHub because >10MB)

**Comment by siegfriedpammer** [comment]
Sorry for taking longer to get back to you...

> I did notice that, in ProcMon, ILSpy can't find [...] Direct3D, the latter striking me as especially strange.

This is not at all a strange thing, as ILSpy uses WPF (Windows Presentation Foundation) for its UI, which is based on DirectX. I would suggest installing/repairing your DirectX/Direct3D install.

The other missing DLLs look like they're resources DLLs which are located in a sub-directory called <isolangcode-countrycode> (e.g. "en-US" or "en-GB") relative to the DLL .NET is trying to load the resources for. If these resources DLLs are missing, it's generally not a problem as the runtime will try to fallback to default resources. Also, you would get a proper .NET exception in that case.

If installing/repairing DirectX doesn't solve your problem, I will take a look at the dump and try to find the problem.

Thank you! Hope this helps!

**Comment by ParzivalWolfram** [comment]
I'll test to see if that's the issue once I can get my machine running
again. Flaky motherboards are a pain...

**Comment by siegfriedpammer** [comment]
Any updates on this?

**Comment by ParzivalWolfram** [comment]
The new motherboard required wiping my secondary Win10 install, and it works fine there. I'm still not sure what was happening, but it doesn't much matter, now. Sorry for the trouble.
