### ISSUE TITLE
ContextSwitchDeadlock was detected

### ISSUE THREAD

**Issue by KrisVandermotten** [icsharpcode/ILSpy#235]
- open ILSpy,
- select File/Open from GAC...
- use ctrl-A to select all
- press enter
- while the "decompiling..." prompt appears, try invoking some commands

ContextSwitchDeadlock was detected
Message: The CLR has been unable to transition from COM context 0x4148b0 to COM context 0x414660 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.

for more information, see http://msdn.microsoft.com/en-us/library/ms172233.aspx

**Comment by siegfriedpammer** [comment]
After fixing some threading issues in ILSpy's UI I tried to reproduce this a few times, but could not trigger the context switch deadlock MDA nor was I seeing any performance problems while loading and/or decompiling the whole GAC. Can we close this?
