### ISSUE TITLE
Decompiled projects with nested namespaces are broken on Linux

### ISSUE THREAD

**Issue by meiomorphism** [icsharpcode/ILSpy#2358]
Under 7.0-preview2 and 7.0-preview3, directory names corresponding to nested namespaces are created with backslashes rather than dots.

On Linux (and, presumably, Mac), this is _not_ an elliptical way of saying that a subdirectory tree is created. Rather, the names of created directories contain literal backslashes. This breaks `dotnet build` entirely. (And somewhat mysteriously, due to https://github.com/dotnet/sdk/issues/10172.)

This is a regression from 6.2. I haven't actually done the bisection to check, but I assume this is due to #2201.

Any Unity game's `Assembly-CSharp.dll` should work as a test case.

**Comment by tanmng** [comment]
👍  

I noticed that the container that I usually use to decompile some DLL was upgraded to release `7.0.0` today and ran into this issue.

In prior release, when decompiling project that has `.` in their name (eg. `foo.bar.dll`) the output directory correctly use `.` (eg. `foo.bar/BundleConfig.cs`, now it's replaced by `\\` (eg. `foo\\bar/BundleConfig.cs`).

If anyone ran into the same issue, please install prior release of the tool to avoid this strange behaviour (couldn't find a flag that help change this):

```sh
dotnet tool install ilspycmd -g --version 6.2.0.6124
```
