### ISSUE TITLE
UI and theming issues

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2359]
This issue is to track all the remaining questions/issues regarding UI and theming:

/cc @tom-englert fyi

* [x] When hovering over the scrollbars the cursor changes in an unexpected way. It should display the default cursor, however, currently the used cursor is the one for vertical/horizontal resize.
![scrollbar_cursor](https://user-images.githubusercontent.com/344204/112747585-9ca7e200-8fb6-11eb-8d14-6e127674ac36.gif)
~~Will have to investigate where the alternate cursors for the scrollbar thumb are defined.~~ found it:
https://github.com/tom-englert/TomsToolbox/blob/master/src/TomsToolbox.Wpf.Styles/Themes/ScrollViewerStyle.xaml#L55-L117

**Comment by siegfriedpammer** [comment]
* [ ] For me it's a bit irritating that the currently hovered menu item does not change its background color - the slight change in the text color is not enough visual feedback in my opinion.
* [ ] Another problem is that the shortcuts are no longer visible in the menu
![image](https://user-images.githubusercontent.com/344204/113197807-6f349000-9265-11eb-81c8-7b7d09c05fc8.png)

**Comment by christophwille** [comment]
Showing the shortcuts is definitely necessary (how would you learn about the shortcut otherwise?). And yes, similarity to VS is a good thing.

**Comment by tom-englert** [comment]
https://github.com/icsharpcode/ILSpy/commit/6840adb2fd08cc2f876f4b3bea303b17a71e6e27 fixes the menu style

**Comment by christophwille** [comment]
![image](https://user-images.githubusercontent.com/344208/115513635-90e0d000-a283-11eb-9d99-7738d5c6cc78.png)

@tom-englert would we happen to have radio buttons too? (because it is a radio and not checkbox scenario)

**Comment by tom-englert** [comment]
Not out of the box - there is no such design in the standard...

**Comment by tom-englert** [comment]
We would need to have a special style for this

**Comment by christophwille** [comment]
It is only irritating because check boxes indicate multi-selection (well-aware that this is menu default, but a checkmark doesn't look as distracting as a checkbox).

**Comment by tom-englert** [comment]
I'll have a look

**Comment by tom-englert** [comment]
Got it - that should be only a check-mark, without the border making it look like a check-box

**Comment by tom-englert** [comment]
@christophwille checkmark is fixed

**Comment by christophwille** [comment]
One thing that I noticed already way back - Notepad focused:

![image](https://user-images.githubusercontent.com/344208/117539487-311c5000-b00b-11eb-89f0-fe3bbf0bb009.png)

ILSpy focused:

![image](https://user-images.githubusercontent.com/344208/117539496-3b3e4e80-b00b-11eb-8b68-32a5beef662e.png)

At least on my machine with the light theme ILSpy is the only app that has this "dark-ish" blue border around it. Is that a theming glitch or supposed to be like that?

**Comment by tom-englert** [comment]
![image](https://user-images.githubusercontent.com/10229954/117540355-47c4a600-b00f-11eb-9597-2f083f9f7eb7.png)
It was inspired by the Visual Studio style, but it seems that in VS this outer border is less prominent. It should be more like the background of the highlighted menu.
I'll gonna fix this.

**Comment by tom-englert** [comment]
![image](https://user-images.githubusercontent.com/10229954/117617004-393fd100-b16c-11eb-8ce4-6983cc78b163.png)
@christophwille On the other hand Outlook looks the same as ILSpy now

**Comment by christophwille** [comment]
Difference being that the title bar in Outlook is blue and thus doesn't stand out compared to the light grey

**Comment by christophwille** [comment]
I am closing this in favor of new, targeted issues (if they come up).
