### ISSUE TITLE
Failed to reopen Search tab

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2367]
Tested with 7.0.0.6473-rc1

### Steps to reproduce
1. Open `Search tab` with `Ctrl+Shift+F` or button in toolbar or etc.
2. Close it with the right-top `X`.
3. Try to reopen `Search tab`.

### Error message shown
None, but it won't be shown again without restart ILSpy or click `Window/Reset layout`

### Details
* Product in use: ILSpy
* Version in use: 7.0.0.6473-rc1

**Comment by siegfriedpammer** [comment]
@Dirkster99 would you be able to help us with this issue? I don't know in enough detail what AvalonDock expects us to do to properly restore a closed ToolPane. Your help would be greatly appreciated, thank you!

The current behavior is that a tool pane is not removed from the collection but only hidden, then when trying to show it again, the `IsActive`/`IsVisible` properties are set to true. I would expect the pane to just be made visible again. If you want to debug the problem yourself, I have linked some of the classes that contain points of interest. If you need more information, do not hesitate to ask.

References:
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/ViewModels/SearchPaneModel.cs#L37
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/ViewModels/ToolPaneModel.cs
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/ViewModels/PaneModel.cs
https://github.com/icsharpcode/ILSpy/blob/master/ILSpy/Docking/DockWorkspace.cs
