### ISSUE TITLE
Search window crash when file deleted

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#2370]
### Steps to reproduce
1. Add a random assembly to the Assemblies tree
2. Delete the added file but keep it in the tree
3. Type anything in the search textbox
![image](https://user-images.githubusercontent.com/9637711/115128159-a5c21880-9f90-11eb-80c1-05e28067eef8.png)
4. Click OK. The progress bar keeps moving in the search window but nothing shows up.
5. Change the dropdown "Search for:" in the search window
![image](https://user-images.githubusercontent.com/9637711/115128209-ff2a4780-9f90-11eb-851b-4533d3f7c548.png)
6. Click OK.
![image](https://user-images.githubusercontent.com/9637711/115128225-19642580-9f91-11eb-9655-3713ecac8001.png)

It might be better to silently skip the files that failed to open.

### Details
* Product in use: e.g. ILSpy version 7.0.0.6373-preview3

**Comment by siegfriedpammer** [comment]
possible duplicate of #2340. Can you please test again with the latest master build? Thank you very much!

**Comment by sgkoishi** [comment]
> 
> 
> possible duplicate of #2340. Can you please test again with the latest master build? Thank you very much!

Yes, it's duplicated, and already fixed in the latest build 7.0.0.6483-rc1.
