### ISSUE TITLE
Decompiled code vs. compile error output CS1525, CS1073, CS2046, see figure

### ISSUE THREAD

**Issue by xintiandi** [icsharpcode/ILSpy#2382]
When decompiling a dll file of a netcore platform, there are many errors in the figure. After saving the project code, errors will occur in the generation, all of which are ref and typeof errors. I don't know if it is a bug?

![BUG](https://user-images.githubusercontent.com/22853635/116552588-c93f7880-a92b-11eb-98a5-99150f291eeb.png)

**Comment by dgrunwald** [comment]
Probably related to the "Unknown result type" warning.

Make sure you load the necessary reference assemblies into ILSpy, some decompiler features (like async methods) won't work if references are missing.

**Comment by xintiandi** [comment]
> 可能与“未知结果类型”警告有关。
> 
> 确保将必要的引用程序集加载到ILSpy中，如果缺少引用，某些反编译器功能（例如异步方法）将无法使用。

All assembly references are loaded, there is no problem, it can run with dnspy or NET.Reflector loading, but the code is basically the same, I don’t know where the problem is, I guess it may be the same as netcore3.1 and 5.0 asp. Net analysis is related.

**Comment by christophwille** [comment]
"reference assemblies" != "assembly references". Go to "Manage assembly lists" (button next to the drop-down in the toolbar), and choose the right version from the "Add preconfigured list..." button/list.

**Comment by xintiandi** [comment]
> "reference assemblies" != "assembly references". Go to "Manage assembly lists" (button next to the drop-down in the toolbar), and choose the right version from the "Add preconfigured list..." button/list.

The previous picture is my compilation situation in vs2019. The picture below shows the situation when I opened it directly with ILSpy_binaries_7.0.0.6488. When the mouse hovers over <ExecuteAsync>d__27, it will turn into a gripper icon. It will jump to the corresponding reference place, and it feels like this place is wrong; after the other parts of the code become a grasper, left-click will jump to the corresponding reference or assembly.

![2021-04-30_14-13-42](https://user-images.githubusercontent.com/22853635/116656045-9abead80-a9be-11eb-90a8-bd095943066e.png)

**Comment by christophwille** [comment]
Would you mind creating a assembly reference list for the target framework, activating it, and then trying?

**Comment by xintiandi** [comment]
> Would you mind creating a assembly reference list for the target framework, activating it, and then trying?

//IL_0002: Unknown result type (might be due to invalid IL or missing references)
//IL_0007: Unknown result type (might be due to invalid IL or missing references)

Thank you for your reply. From these 2 lines of hints, I feel that there may be a lack of quotes. Then I think about what caused the problem. Maybe my understanding of .net needs to be improved and I am studying hard.

**Comment by xintiandi** [comment]
> "reference assemblies" != "assembly references". Go to "Manage assembly lists" (button next to the drop-down in the toolbar), and choose the right version from the "Add preconfigured list..." button/list.

According to the method you said, hover and click the function to jump to the corresponding reference. It's just that after "Add preconfigured list", I have to re-run ILSpy to take effect, but the error is still causing vs. compiling, maybe I still don't understand.

**Comment by siegfriedpammer** [comment]
I do not speak Chinese, but I am trying to help!

![explanation](https://user-images.githubusercontent.com/344204/116660402-43571800-a993-11eb-828b-1cd829f62e3c.gif)

I hope you can understand.

**Comment by xintiandi** [comment]
> I do not speak Chinese, but I am trying to help!
> 
> ![explanation](https://user-images.githubusercontent.com/344204/116660402-43571800-a993-11eb-828b-1cd829f62e3c.gif)
> 
> I hope you can understand.

Thank you for your reply, I don’t understand, it’s because the knowledge of decompiling .NET is still lacking. According to the previous friend’s reply, I already do that to load the assembly. After loading, hover the mouse and click on the function to jump. Go to the corresponding reference point. What I want to express is that although the assembly is loaded. However, the source code file saved by ILSpy is compiled in vs2019, but it always prompts that the reference is missing, which is the error in the above figure. In vs2019, I checked that the reference and dependent assemblies have been loaded, and there is no lack of assemblies. I don’t know. Why is there still an error in the picture? This is the reason I don't understand.

**Comment by dgrunwald** [comment]
The "unknown type" ILSpy is having trouble with is the type `AsyncTaskMethodBuilder`.
That type is not a hyperlink because ILSpy cannot find its definition.

You'll need to help ILSpy find that type by loading the appropriate version of the assembly defining `AsyncTaskMethodBuilder`.

For .NET Core projects that's `System.Private.CoreLib.dll`; for classic .NET Framework projects it's `mscorlib.dll`.
It's possible that you have an incorrect version of these .dlls loaded, causing ILSpy to look for the type in the wrong place.
That's why @siegfriedpammer suggested you start with a fresh assembly list.

**Comment by xintiandi** [comment]
> The "unknown type" ILSpy is having trouble with is the type `AsyncTaskMethodBuilder`.
> That type is not a hyperlink because ILSpy cannot find its definition.
> 
> You'll need to help ILSpy find that type by loading the appropriate version of the assembly defining `AsyncTaskMethodBuilder`.
> 
> For .NET Core projects that's `System.Private.CoreLib.dll`; for classic .NET Framework projects it's `mscorlib.dll`.
> It's possible that you have an incorrect version of these .dlls loaded, causing ILSpy to look for the type in the wrong place.
> That's why @siegfriedpammer suggested you start with a fresh assembly list.

Thank you very much, I am looking at the reason。
