### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by nwikechisom** [icsharpcode/ILSpy#2383]
### Steps to reproduce
1. Check out the repository using git.
2. Execute `git submodule update --init --recursive` to download the ILSpy-Tests submodule (used by some test cases).
3. Use `dotnet build Frontends.sln` to build the non-Windows flavors of ILSpy (.NET Core Global Tool and PowerShell Core).

### Error message shown
/Users/sherocoder/ilspy/ILSpy/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj(667,5): error MSB3073: The command "pwsh -NoProfile -ExecutionPolicy Bypass -File BuildTools/update-assemblyinfo.ps1 Debug" exited with code 127.
```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* Version in use: e.g. 6.0.0 or a commit hash (use Help>About to see which ILSpy version you are using)
* Any other relevant information to the issue, or your interest in contributing a fix.
* macOS Big Sur - terminal

**Comment by christophwille** [comment]
See section "How to build" in the README.

**Comment by nwikechisom** [comment]
I followed the instructions and got to that bug on macOS

**Comment by christophwille** [comment]
So you do have PowerShell installed and can run it interactively by executing pwsh?

**Comment by nwikechisom** [comment]
Yes I do

**Comment by christophwille** [comment]
Works on my Mac

**Comment by nwikechisom** [comment]
Apologies. I was running in bash terminal instead of pwsh terminal

**Comment by siegfriedpammer** [comment]
It seems like pwsh is not in your PATH, as the pwsh script should actually be executed by dotnet build even when executing from bash.

**Comment by christophwille** [comment]
I have pwsh installed via Homebrew (and that adds it to the path automatically)
