### ISSUE TITLE
Missing ``extern`` keyword

### ISSUE THREAD

**Issue by marwie** [icsharpcode/ILSpy#2389]
Decompiling UnityEditor.dll, Unity Version 2020.3.6f1

### Input code
Zip containing UnityEditor.dll
[UnityEditor.zip](https://github.com/icsharpcode/ILSpy/files/6425741/UnityEditor.zip)

### Erroneous output
It looks like properties are not handled correctly. For example ``ConnectTimeout`` is missing extern
``UnityEngine.Networking.ConnectionConfigInternal.ConnectTimeout {set;}``
whereas ``InternalCreate()`` in the same type is correct.

**Missing extern**
```csharp
[NativeProperty("m_ProtocolRequired.m_ConnectTimeout", TargetType.Field)]
private uint ConnectTimeout
{
   [MethodImpl(MethodImplOptions.InternalCall)]
   set;
}
```

**Correct**:
```csharp
[MethodImpl(MethodImplOptions.InternalCall)]
private static extern IntPtr InternalCreate();
```

### Details
* Product in use: ILSpy
* Version in use: fork based off of dfd82de1afdb7d897d1c0084856a84197ac8fd20, https://github.com/needle-tools/ILSpy. 
* Merged with master (f7460a041ea8fb8b0abf8527b97a5b890eb94eea) but issue still exists
* I only ~~hacked~~ added solution output to the cli in my fork. No additional changes
* I can provide you with the output solution or repo (currently private) if it helps
* Here is the relevant example from the official Unity CSReference https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Modules/UNET/ScriptBindings/UNETTransportConfig.bindings.cs#L116
* CSReference is not updated anymore hence the effort to provide an unofficial but up-to-date reference again on our Unity mirror org needle-mirror https://github.com/needle-mirror

![image](https://user-images.githubusercontent.com/5083203/117112572-8cd7a680-ad89-11eb-8604-997dbad83921.png)

**Comment by dgrunwald** [comment]
The UnityEditor.dll you uploaded does not contain the `ConnectionConfigInternal` class.

**Comment by marwie** [comment]
Ah I'm sorry, ``ConnectionConfigInternal`` and ``NavMeshQuery`` are both in UnityEngine

[UnityEngine.zip](https://github.com/icsharpcode/ILSpy/files/6430423/UnityEngine.zip)
