### ISSUE TITLE
Cannot cast expression of type 'conditional expression' to type ``void*``

### ISSUE THREAD

**Issue by marwie** [icsharpcode/ILSpy#2392]
### Input code
Please refer to https://github.com/icsharpcode/ILSpy/issues/2389

The relevant section is in ``UnityEngine.Experimental.AI.NavMeshQuery`` for example ``NavMeshQuery.Raycast``

https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Modules/AI/NavMeshExperimental.bindings.cs#L394

### Erroneous output
It produces four methods with ``Cannot cast expression of type 'conditional expression' to type 'void*'`` in NavMeshQuery

For example
```csharp
public unsafe PathQueryStatus Raycast(out NavMeshHit hit, NavMeshLocation start, Vector3 targetPosition, int areaMask = -1, NativeArray<float> costs = default(NativeArray<float>))
{
	AtomicSafetyHandle.CheckReadAndThrow(m_Safety);
	if (costs.Length != 0 && costs.Length != 32)
	{
		throw new ArgumentException($"The number of costs ({costs.Length}) must be exactly {32}, one for each possible area type.", "costs");
	}
	void* costs2 = (void*)((costs.Length == 32) ? ((IntPtr)(nint)costs.GetUnsafePtr()) : ((IntPtr)(nint)0));
	int pathCount;
	PathQueryStatus pathQueryStatus = Raycast(m_NavMeshQuery, start, targetPosition, areaMask, costs2, out hit, null, out pathCount, 0);
	return pathQueryStatus & ~PathQueryStatus.BufferTooSmall;
}
```
![image](https://user-images.githubusercontent.com/5083203/117117175-864c2d80-ad8f-11eb-96e4-4edc4372e37b.png)

Broken methods:
``
public unsafe PathQueryStatus BeginFindPath(NavMeshLocation start, NavMeshLocation end, int areaMask = -1, NativeArray<float> costs = default(NativeArray<float>))
``
``
public unsafe PathQueryStatus Raycast(out NavMeshHit hit, NavMeshLocation start, Vector3 targetPosition, int areaMask = -1, NativeArray<float> costs = default(NativeArray<float>))
``
``
public unsafe PathQueryStatus Raycast(out NavMeshHit hit, NativeSlice<PolygonId> path, out int pathCount, NavMeshLocation start, Vector3 targetPosition, int areaMask = -1, NativeArray<float> costs = default(NativeArray<float>))
``
``
public unsafe PathQueryStatus GetEdgesAndNeighbors(PolygonId node, NativeSlice<Vector3> edgeVertices, NativeSlice<PolygonId> neighbors, NativeSlice<byte> edgeIndices, out int verticesCount, out int neighborsCount)
``

### Details
Please see https://github.com/icsharpcode/ILSpy/issues/2389

**Comment by dgrunwald** [comment]
I'm not sure what's up with that.
The code shown in your screenshot should be valid C# code.

This one actually seems to be a C# compiler bug? The conditional expression clearly should have type `IntPtr`.
I can't reproduce the compiler error either, [similar code](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYYCuAdgM4CGAZgKaYAsAVOgLIAUARgPa8AbdNQA06AJbkALmwAOUgE4BKfIWLqordADd0AXnSdNLJZ2roA/Ic4BJaQAVFp8pKlL5y9CGt2pj5Zwu0koADEpKANxq6kRQAOw6UUjqAL7IKUA) compiles fine for me.

But I guess we can try to clean up the redundant casts here to produce something more like the original code.

**Comment by marwie** [comment]
Weird. Yeah the same code produces an error in this project

![image](https://user-images.githubusercontent.com/5083203/117200194-77936400-adeb-11eb-9cab-dd676fadc745.png)

**Comment by dgrunwald** [comment]
`NavMeshQuery` is also missing from the DLL you uploaded; but I think the commit I just pushed should help to avoid the casts.

**Comment by marwie** [comment]
Great. This seems to have fixed it. Thank you!

Output looks now like this:

```csharp
public unsafe PathQueryStatus Raycast(out NavMeshHit hit, NavMeshLocation start, Vector3 targetPosition, int areaMask = -1, NativeArray<float> costs = default(NativeArray<float>))
{
	AtomicSafetyHandle.CheckReadAndThrow(m_Safety);
	if (costs.Length != 0 && costs.Length != 32)
	{
		throw new ArgumentException($"The number of costs ({costs.Length}) must be exactly {32}, one for each possible area type.", "costs");
	}
	void* costs2 = ((costs.Length == 32) ? costs.GetUnsafePtr() : null);
	int pathCount;
	PathQueryStatus pathQueryStatus = Raycast(m_NavMeshQuery, start, targetPosition, areaMask, costs2, out hit, null, out pathCount, 0);
	return pathQueryStatus & ~PathQueryStatus.BufferTooSmall;
}
```

![image](https://user-images.githubusercontent.com/5083203/117216564-45d8c800-ae00-11eb-8f4c-8588481cc921.png)
