### ISSUE TITLE
Optional parameters must appear after all required parameters

### ISSUE THREAD

**Issue by marwie** [icsharpcode/ILSpy#2393]
### Input code
Please refer to https://github.com/icsharpcode/ILSpy/issues/2389

Relevant section in CSReference https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Modules/AI/NavMeshExperimental.bindings.cs#L298

### Erroneous output
``  <UnityEngine>\UnityEngine\Experimental\AI\NavMeshQuery.cs:22549 Optional parameters must appear after all required parameters`` 
```csharp
[MethodImpl(MethodImplOptions.InternalCall)]
private static extern void MapLocation_Injected(IntPtr navMeshQuery, ref Vector3 position, ref Vector3 extents, int agentTypeID, int areaMask = -1, out NavMeshLocation ret);
```

![image](https://user-images.githubusercontent.com/5083203/117117984-797c0980-ad90-11eb-8b72-adc6cea92ab4.png)

### Details
Please see https://github.com/icsharpcode/ILSpy/issues/2389

**Comment by dgrunwald** [comment]
There's not much we can do here -- that function really has a non-optional parameter following an optional parameter.

Something must be re-writing the method (appending an `out` parameter and replacing the return type with `void`). But I don't think that's being done by the C# compiler; so it wouldn't be appropriate for ILSpy to undo it.
