### ISSUE TITLE
The type parameter 'TQueryType' cannot be used with the 'as' operator because it does not have a class type constraint nor a 'class' constraint

### ISSUE THREAD

**Issue by marwie** [icsharpcode/ILSpy#2396]
### Input code
Please see https://github.com/icsharpcode/ILSpy/issues/2389

Relevant section in official CSReference
https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Modules/Subsystems/SubsystemManager.cs#L35

### Erroneous output
``  <UnityEngine>\UnityEngine\SubsystemManager.cs:3536 The type parameter 'TQueryType' cannot be used with the 'as' operator because it does not have a class type constraint nor a 'class' constraint``

```csharp
private static void AddSubsystemSubset<TBaseTypeInList, TQueryType>(List<TBaseTypeInList> copyFrom, List<TQueryType> copyTo) where TBaseTypeInList : ISubsystem where TQueryType : ISubsystem
{
	TQueryType item = default(TQueryType);
	foreach (TBaseTypeInList item2 in copyFrom)
	{
		int num;
		if (item2 is TQueryType)
		{
			object obj = item2;
			item = (TQueryType)(obj as TQueryType);
			num = 1;
		}
		else
		{
			num = 0;
		}
		if (num != 0)
		{
			copyTo.Add(item);
		}
	}
}
```

![image](https://user-images.githubusercontent.com/5083203/117119026-cf04e600-ad91-11eb-9b66-bc4bccbb6655.png)

Same issue for ``AddDescriptorSubset`` https://github.com/Unity-Technologies/UnityCsReference/blob/61f92bd79ae862c4465d35270f9d1d57befd1761/Modules/Subsystems/SubsystemDescriptorStore.cs#L29

![image](https://user-images.githubusercontent.com/5083203/117119340-302cb980-ad92-11eb-979d-43785429312d.png)

### Details
Please see https://github.com/icsharpcode/ILSpy/issues/2389

**Comment by dgrunwald** [comment]
The IL code is weird here.
It uses this sequence for the actual cast:
```
			IL_0021: ldloc.1
			IL_0022: box !!TBaseTypeInList
			IL_0027: isinst !!TQueryType
			IL_002c: unbox.any !!TQueryType
			IL_0031: stloc.2
```

The `isinst` in there seems to be completely redundant given that `item2 is TQueryType` was already checked by the if-condition above.
But ILSpy is translating this snippet locally, so it doesn't know that the type is guaranteed to match.
And if the type does not match, the weird `isinst` changes the semantics: instead of the `InvalidCastException` that you'd typically get, you would get a `NullReferenceException` because the `isinst` replaces non-matching types with a null reference.

So I don't think we can easily fix this :(

**Comment by dgrunwald** [comment]
I can reproduce the weird IL sequence with:
```
        public void Generic<T1, T2>(T1 x) where T2 : IDisposable
        {
            if (x is T2 y)
            {
                y.Dispose();
            }
        }
```

I think we would first need to implement support for pattern matching, as it's only in the context of the whole pattern that we could detect that the second `isinst` is redundant.

**Comment by marwie** [comment]
Oh nice, thanks for the info and fix. I'll try the next few days again!
