### ISSUE TITLE
ILSpy's titlebar does not differentiate between focused/active and inactive

### ISSUE THREAD

**Issue by Jehoel** [icsharpcode/ILSpy#2409]
## Steps to reproduce
1. Open ILSpy 7+ as a maximized window on one monitor.
2. Open Notepad on another monitor.
3. In ILSpy, click around on things
4. Alt-tab to notepad
5. Observe that the Notepad titlebar changed color when Notepad gained focus (or at least its text color did with default Windows 10 settings), but ILSpy's titlebar, nor _any_ part of its window, changed appearance when ILSpy lost focus.
    * It's even worse than that: the current document-tab in ILSpy retains the "active" color even when the window doesn't have focus, which is misleading.
      * Many other programs will use a different color for the active document tab, such as a slightly desaturated version of the active color, but not grey either. 

(After I wrote this, I realized that ILSpy7 _does_ very subtly change the opacity of its custom window drop-shadow, but this is almost invisible on a high-DPI display or if you have a dark desktop wallpaper that doesn't have sufficient contrast to make drop-shadows visible).

## Expected results

* ILSpy's titlebar should still respect the user's color and theming settings to indicate if it has focus or not.

## Actual results:

* **It is currently almost impossible to tell visually if ILSpy has focus or not** (and it may as well be fully impossible if you have impaired vision). This is a pain if I start typing when I think that ILSpy has focus when it doesn't - or vice-versa - and my keystrokes end-up in the wrong program.

### Preferred solution

* Bring back the Windows default rendering of the nonclient area of the ILSpy application window.
  * I'm not saying to go ditch the current WPF application-wide skin that ILSpy has started using - I just don't think it's a good idea to skin or customize the nonclient area as right now it not only adds zero value, but takes away useful visual hints for the user.

### Alternative solution

* Set the WPF skin's nonclient area's customized titlebar's background color to use the user's system color for active and inactive windows as per the user's settings.

**Comment by christophwille** [comment]
@tom-englert can you please comment?

**Comment by tom-englert** [comment]
It follows the Visual Studio styling, this doesn't change the title bar, and it does not follow the accent color, either (Office apps don't do that, too).

VS only changes the border and the icon color. I agree that we should dim the title text like in other windows when the window is not active.

Also @christophwille complaint in #2359 that the border change of the active window is too prominent, while @Jehoel complains that it is too subtle - that's a hard to solve conflict.

**Comment by tom-englert** [comment]
An option would be to not style the non-client at all like @Jehoel suggested - so dark mode in default windows settings would look just not fully like in Visual Studio.

@christophwille you could just remove L17 to try how that looks:
https://github.com/icsharpcode/ILSpy/blob/46e9f633ca5e9bc06feb21421439b00a127ee440/ILSpy/MainWindow.xaml#L16-L18

**Comment by Jehoel** [comment]
As a preface, I'm very aware that everyone has strong opinions about UX, and _especially_ colour schemes :)

@tom-englert 

> so dark mode in default windows settings would look just not fully like in Visual Studio.

ILSpy doesn't look a thing like Visual Studio, honestly - the visual similarities are minor at-best. If ILSpy _was_ using the exact same WPF control and style libraries that WPF was using then it might be worthwhile, but as it isn't - and as VS vNext / Dev17 is around the corner and will doubtless tweak its own visual appearance again I don't see anything worthwhile in trying to stay on the visual-design copycat treadmill.

**Comment by YellowAfterlife** [comment]
Visual Studio does indicate focus, although subtly - VS icon, project name, and window control buttons are dimmed when out of focus:
![image](https://user-images.githubusercontent.com/731492/118372506-9b5c6400-b5ba-11eb-8c35-8f12ee9fe619.png)

If it's not too much work, offering a choice between native and custom frame (like VS Code has it) could be good - since ILSpy doesn't nest any custom controls in the title bar like VS does, using a native border only costs the user a handful of pixels.

**Comment by christophwille** [comment]
Office has a very elaborate custom styling (I would even go so far to call it design language), so we definitely should not be taking that as a comparison.

In general, my preference for the NCA is leaning towards Windows instead of highly customized apps.

**Comment by tom-englert** [comment]
So I made this optional, to accomplish everyone's taste.
