### ISSUE TITLE
Trojaner in Setup DLL

### ISSUE THREAD

**Issue by szeski** [icsharpcode/ILSpy#2414]
ILSpy_binaries_7.0.0.6488.zip
Trojaner in ICSharpCode.AvalonEdit.dll erkannt durch VirusTotal.com

https://www.virustotal.com/gui/file/86ff97015da0c2802b1c1c35d4e9c3c21cb024258557eff9cade16a9d58bd34b/detection

**Comment by christophwille** [comment]
Duplicate of https://github.com/icsharpcode/AvalonEdit/issues/283

**Comment by christophwille** [comment]
So in total we have two companies (AVG is owned by Avast) that have a screwy reputation system.

**Comment by christophwille** [comment]
I am closing this issue in favor of the one in AE - because it is not us, it is the anti-virus vendors.
