### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by Pinox** [icsharpcode/ILSpy#2437]
please add VS 2022 support , extension currently not listed for VS 2022

Writing Visual Studio Extensions with Mads - 64bit extensions for Visual Studio 2022
https://www.youtube.com/watch?v=L8b3kFriwCs&ab_channel=MicrosoftVisualStudio

thanks in advance.

**Comment by christophwille** [comment]
Yes, we know that the addin needs changes for 2022. Do not hold your breath us doing this.

**Comment by christophwille** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022 

plus

https://www.youtube.com/watch?v=-PKIPTW6km0

**Comment by christophwille** [comment]
Adding another resource that might come in handy: https://github.com/VsixCommunity/Community.VisualStudio.Toolkit

**Comment by christophwille** [comment]
Can you give https://github.com/icsharpcode/ILSpy/suites/3162894633/artifacts/72790275 a shot to see if it works in your scenarios? (I admit to not having tested every single possible combination that might make the addin keel over)

**Comment by RobertvanderHulst** [comment]
Christoph,
This VSIX installs IlSpy in VS2020 and you can start it from the tools menu.
Also right clicking on a reference in a .Net Framework app opens that reference in ILSpy.
So it seems to be working.
Right clicking a .Net Core or .Net 5/6 assembly in the Dependencies\Frameworks\Microsoft.NETCore.App branch in the solution explorer does not show ILSpy in the context menu, but I suspect that also does not work in VS 2019.

What other functionality should there be ?

**Comment by christophwille** [comment]
I had a chat with @Rpinski earlier this week about available features to validate the extension's code paths. Works:

* Open output in ILSpy on the project node
* Pre-SDK projects: Open in ILSpy on a reference node
* Editor window: right-click on a symbol, Open in ILSpy
* Tools main menu, Open in ILSpy

Newer dependencies (PackageReference) do not work (this is now tracked via #2446)

**Comment by RobertvanderHulst** [comment]
Thanks, 
One more question:
Your extension seems to depend on the Roslyn API. That means that it does not work for Non-Roslyn projects.
Have you considered to use the 'normal' VS Project System API  to allow ILSpy to work for custom languages as well, such as:
- Open project output
- Open on a Reference Node

Background:
We have developed our own .Net language (X#) with our own project system. 
My colleague Fabrice Foray has added ILSpy support for our language (for ILSpy 5 and ILSpy 6. We cannot get ILSpy 7 to work right now)
I would love to be able to open the output of our product in ILSpy from the context menu inside VS.
For now I am using the option inside VS to open the project folder in Explorer and then navigate to the output folder and double click the DLL file to open it in ILSpy (I have associated the DLL extension with IlSpy) . Saving a few clicks would be helpful.

**Comment by christophwille** [comment]
No, we only support Roslyn (that is why 15.0 and newer is supported only).

**Comment by RobertvanderHulst** [comment]
Are you accepting pull requests for this?
Then I will try to implement this myself.

**Comment by christophwille** [comment]
To be very much honest, we barely have the cycles to keep the existing addin afloat, much less supporting (because after all long-term it will be on us) additional functionality that is an edge case these days.

**Comment by lastlink** [comment]
@christophwille your artifact build worked for me in visual studio 2022
