### ISSUE TITLE
functions cannot be preceded by "ref" modifiers

### ISSUE THREAD

**Issue by zgfflc** [icsharpcode/ILSpy#2438]
Sometimes a decompiled function will have "ref" modifiers in front of the function, causing the code to fail to compile.Like :
		public ref Dictionary<string, string> fun
		{
                }
The same goes for assignment code like:
	a= ref b;
**Describe the solution you'd like**
I want to decompile the code to make sure it compiles properly.

**Additional context**

**Comment by zgfflc** [comment]
[check.zip](https://github.com/icsharpcode/ILSpy/files/6698781/check.zip)

**Comment by dgrunwald** [comment]
Functions/properties can use `ref` modifiers starting with C# 7.0. (reference return and locals)
If the IL code has by-reference returns, there's no way to express the code in older C# versions.

**Comment by dgrunwald** [comment]
Not a bug.
Assemblies using this feature will need to be recompiled as C# 7 or later, then recompilation will be successful.
