### ISSUE TITLE
Ambiguous implicit conversions from null literals in decompiled code

### ISSUE THREAD

**Issue by jfd16** [icsharpcode/ILSpy#2444]
### Input code
```csharp
public class X {}
public class Y {}

public struct Z {
    public static implicit operator Z(X x) => new Z();
    public static implicit operator Z(Y y) => new Z();
    public static void M1(Z z) { }
    public static void M2() => M1((X)null);
}
```
### Erroneous output
`M1((X)null)` decompiles to `M1(null)`, which is an ambiguous implicit conversion.

### Details
* Version in use: 7.0.0.6488

**Comment by sgkoishi** [comment]
At the same time `M3() M1((Y)null);` decompiles correctly - and if you switch the order of operator (move the YZ to the first) and the XZ cast will be preserved and YZ will be omitted.
[SharpLab](https://sharplab.io/#v2:D4AQzABCBMEBoQN4F8CwAocVYE0lvQywGcAXAJwFcBjUiALSQwhakhAEYA2CASwFsADgBte1XnQD2ggKbkAhqUnkGACgQAPAJQQAvAD4IAOxkB3NVoDczVlk48BIsRIjS5i5WrwBPHQeNmFtborGxQ3FAALBAAshyqjABeOogQBKF2ESDRMdCqfoZxqupaRpTCwlY2LJk82bFg+XqF8ao4peWVwchAA=)
