### ISSUE TITLE
Decompiler shows some enum values as hexdecimal instead of decimal

### ISSUE THREAD

**Issue by Symbai** [icsharpcode/ILSpy#2448]
For some reason the decompiler shows enum values sometimes in hexdecimal. I prefer it shows the integer value which it does most of the time but for some values it does not. See image below

![image](https://user-images.githubusercontent.com/14368203/124586169-6b14a180-de56-11eb-8c22-f2ecc1f1d344.png)

### Details
* Product in use: e.g. ILSpy & ICSharpCode.Decompiler nuget package
* Version in use: 7.1.0.6543

**Comment by dgrunwald** [comment]
There's a heuristic that prefers hex for numbers that are powers of 2 or close to them, e.g. masks in bit manipulation.
This heuristic currently only looks at the number itself without considering the context.
We would improve this for enums so that we use a consistent strategy for all enum members.

**Comment by siegfriedpammer** [comment]
I think an acceptable solution is to only use hex for flags enums.

**Comment by Symbai** [comment]
> I think an acceptable solution is to only use hex for flags enums.

Why? Cannot it be just a preference of the user and customizable via setting? I prefer decimal values especially on large enums like in the screenshot. I hate if I always have to think what for example 0x3F is in decimal.

**Comment by siegfriedpammer** [comment]
Flags enums usually use powers of two which are easier to understand in hex notation as it is just 0, 1, 2, 4 and 8 with an increasing number of zeros at the end. E. g. 0, 1, 2, 4, 8, 0x10, 0x20, ...

**Comment by siegfriedpammer** [comment]
Flags are about bit positions rather than the actual values.
