### ISSUE TITLE
Framework Microsoft.NETCore.App version 3.1.0 not found

### ISSUE THREAD

**Issue by testentry** [icsharpcode/ILSpy#2450]
I was able to run 
```dotnet build Frontend.sln```
Going to ICSharpCode.Decompiler.Console/bin/Debug/netcoreapp3.1 and running ilspycmd gave me the following
```It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64
 ```
I don't know what to do from here
I am running
```Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by christophwille** [comment]
I can see where the confusion comes from: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler.Console/ICSharpCode.Decompiler.Console.csproj#L5 targets only LTS releases, however, our build system https://github.com/icsharpcode/ILSpy/blob/master/global.json#L3 recently moved to 5.0 (not the targets per se, but the newer compilers were the reason to move)

So, yes, you'd need to also install the .NET Core 3.1 Runtime.

**Comment by testentry** [comment]
Going to the official website said that Version 3.0 is unsupported and couldn't find anything I did find a site that lets me download it, but just sends me back to same website ¯\_(ツ)_/¯

**Comment by christophwille** [comment]
https://dotnet.microsoft.com/download/dotnet/3.1

**Comment by siegfriedpammer** [comment]
Also note that 3.0 is unsupported, but 3.1, used by ILSpy, is LTS and thus still supported.

**Comment by testentry** [comment]
You were right, I had to install the binaries directly move them to the corresponding folders. Works good now thanks.
