### ISSUE TITLE
 引发异常的上一位置中堆栈跟踪的末尾

### ISSUE THREAD

**Issue by kkkkkkkk4** [icsharpcode/ILSpy#2452]
报错内容：
// PE file does not contain any managed metadata.

ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
   在 ICSharpCode.ILSpy.LoadedAssembly.<LoadAsync>d__50.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)

无法反编译exe文件

**Comment by kkkkkkkk4** [comment]
![捕获](https://user-images.githubusercontent.com/85882798/125573255-35877266-db12-429b-88ba-8e8f8528b969.JPG)

**Comment by siegfriedpammer** [comment]
The file you are trying to decompile is not a .NET assembly, so we cannot do anything about it. This is not a bug.
