### ISSUE TITLE
Make editor editable (i.e. make syntactic highlighting shift with typed text)

### ISSUE THREAD

**Issue by Niko-O** [icsharpcode/ILSpy#2456]
**Is your feature request related to a problem? Please describe.**
Sometimes it's really nice to do small code adjustments right there in the editor before copying code somewhere that doesn't have so great editing capabilities (think Telegram or MS Word) or to just break up some complex lins to get a better understanding.
Back in 2014 I forked the repository and simply changed `<ae:TextEditor ... IsReadOnly="True"` to False in DecompilerTextView.xaml. Back then, times were simpler. I forked the repository in its current state and tried to apply my modifications again (merging/rebasing was too much work) and it's going OK, but the syntax highlighting is acting up.

Simply setting `IsReadOnly="False"` will allow me to type, but it messes with the syntax highlighting. The offset of the highlighted substrings is not shifted along as you type. Simply setting `textEditor.SyntaxHighlighting` to null and back to its original value in `textEditor.TextChanged` does not work. (It was worth a shot.)

**Describe the solution you'd like**
Ideally the editor should be just writable in general, possibly a CheckBox in the options window.
But if this is not a feature you deem fitting for ILSpy, I would appreciate some pointers to what I could try to fix it myself. I am very unfamiliar with the workings of Avalon and ILSpy.
If I manage to fix it I could pull-request that back here because I think it would be useful for others who just want to set ReadOnly

**Additional context**
Here's a video of the current behavior. Note how the highlighting isn't updated at first when adding text after the method header, but then snaps to the "correct" location when adding text further down. This might make things more complicated to fix.
https://user-images.githubusercontent.com/4943909/126402796-02c9fc5a-77f1-4c70-bca9-3eaa0b3ffdf5.mp4

**Comment by dgrunwald** [comment]
C# gained a lot of context-sensitive keywords in the last few language versions.
The old regex-based syntax highlighting built into AvalonEdit can't handle those; so ILSpy instead remembers what's supposed to be a keyword when it generates the source code, and then uses this lookup table during highlighting. If you modify the text, the lookup table no longer fits.
You'd need to implement new code to adjust the lookup table in the `TextChanged` event. That gets tricky if you don't want to introduce performance problems for large methods; and we're unlikely to accept such a PR -- the current design is simple and sufficient for ILSpy as the text is not meant to be editable.
