### ISSUE TITLE
ILSpy starts slowly if many assembles loaded

### ISSUE THREAD

**Issue by KevinCathcart** [icsharpcode/ILSpy#247]
ILSpy has no problem loading a large number of assemblies simultaneously, since it does all the work in the background.

However, if ILSpy is closed with many assemblies open, then when it is run again, it appears to wait until it has loaded all assemblies before the UI appears and is ready. This seems highly suboptimal.

It would be better to load them all in the background, showing the UI immediately, except perhaps the one assembly last browsed, since the member or class last browsed is displayed by default.

**Comment by siegfriedpammer** [comment]
Is this still a problem in 2017 with SSDs and faster processors?

On my system (Windows 10 Pro x64, notebook with SSD, 16 GB memory), starting ILSpy loading a list of all assemblies in my GAC only takes approx. 3 seconds in debug mode.

**Comment by siegfriedpammer** [comment]
I implemented some performance improvements in 12dc70e05a1362f34af5491faccb2acc97d06704 and subsequent commits. I think this is no longer an issue. If you still face any performance problems, feel free to open a new issue.
