### ISSUE TITLE
Visual Studio 2017 does not show Editor's context menu to open ILSpy and no assembly is opened using the main menu

### ISSUE THREAD

**Issue by Ordisoftware** [icsharpcode/ILSpy#2472]
**Since v6**

Visual Studio 2017 does not show Editor's context menu to open ILSpy and no assembly is opened using the main menu (need to load manually from system file and browse artifact).

![image](https://user-images.githubusercontent.com/22332878/128301125-f01c8afa-151f-4db6-b573-0b07ea564607.png)

![image](https://user-images.githubusercontent.com/22332878/128301156-67875e61-e047-4d21-8b11-d3a14035d6d8.png)

**Up to ILSpy.AddIn_5.0.0.5124**

All is automatic from the source code.

![image](https://user-images.githubusercontent.com/22332878/128301528-c0e7ae22-5e25-4f76-9a5b-47802053167b.png)

![image](https://user-images.githubusercontent.com/22332878/128301553-a85d5b5c-ccac-4ef6-880d-ed4c8c4d90dd.png)

**Comment by Rpinski** [comment]
Hello @Ordisoftware,

Some questions:

1.  Does it happen on any project you open or only on some specific sorts of projects?
2. Does it happen on any code of the project or only at some specific places or files?
3. Which .NET version does the project use?

**Comment by Ordisoftware** [comment]
Dear,

It happens on any project.
It happens on any code of the project, anywhere I click in the Code Editor.
I use .NET Framework 4.7.2 and C# 7.3.

Windows 10-x64 and last Visual Studio 2017.

I sometimes try some v6.x month after month but it's always the same problem.

Thus I return every time to the last v5 and disable auto-update.

It is not really a problem for me and I plan, perhaps, to switch to VS2022 when ready.

**Comment by Rpinski** [comment]
Sorry, it took a while, but finally it seems I found the reason. From 6.0 up to latest 7.1 release of the add-in we have used a "bad" version of VS SDK (15.9.3), which referenced some VS 16 (= 2019) core libs not available in VS 2017. When used in VS 2017, an exception was thrown at some point, but silently catched by VS. This prevented the menu item from appearing in code editor.

The good message: This issue has been already fixed after 7.1 release with d1678d1547caf88cf841bb693254a9d6ce060e6f. You could give the [latest dev build](https://github.com/icsharpcode/ILSpy/actions/runs/1108485301) a try. It worked correctly for me (in VS 2017).

@christophwille We might consider a bugfix release of the add-in through marketplace - based on latest master.

**Comment by Ordisoftware** [comment]
This is strange, because it was after trying v7.1 that I decided to create this issue and the images are of this version which does not work on my machine. The last to work is v5.0.0.5124 and it suits me with no issues, I just raised the issue just in case. I had to try 3 or 4 versions from 6.0 to 7.1 and none worked, except using the stand-alone in manual load and browse, but nothing in VS.

**Comment by Rpinski** [comment]
My explanation might have been confusing, I meant that the bug fix came **after** v7.1 was released. So it still doesn't work in v7.1 and you are right.

We will publish a fixed add-in through marketplace ASAP, in the meantime you can try the mentioned development build from master branch, if you want.

**Comment by Ordisoftware** [comment]
Oh yes, sorry, I misunderstood the English words used at the same time: "_already_ fixed _after_"...

Thus I will try the next release.

Thanks!

**Comment by christophwille** [comment]
@siegfriedpammer wouldn't it be best to cherry pick (see https://github.com/icsharpcode/ILSpy/issues/2472#issuecomment-902140066) for a 7.1.1 branch?

**Comment by siegfriedpammer** [comment]
done

**Comment by christophwille** [comment]
7.1.0.6543 was the old version, 7.1.0.6544 is now the re-released version based on https://github.com/icsharpcode/ILSpy/commits/release/7.1 (one commit cherry-picked). 

Bonus: https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy now also works with 2022 already.

**Comment by Ordisoftware** [comment]
It works very well, thanks!
