### ISSUE TITLE
System.IO.Compression 4.2.0.0 cannot be resolved

### ISSUE THREAD

**Issue by Droppers** [icsharpcode/ILSpy#2473]
System.IO.Compression 4.2.0.0 should be resolved to System.IO.Compression 4.0.0.0, see the explanation from a Microsoft employee.

> There were some out of band packages for System.IO.Compression released with a higher versions reference assemblies. When supported netstandard 2.0 we had to support such reference versions and that is why VS ship with such higher version number in the ref assemblies. The .NET assembly loader internally handle such higher reference assembly version and map it to the implementation assembly 4.0.0.0.

https://developercommunity.visualstudio.com/t/systemiocompression-in-net-48-version-number-diffe/995459

### Steps to reproduce
1.  Open an assembly with a reference to System.IO.Compression 4.2.0.0 (ShareX is an example)
2.  Expand it in the tree view on the left.
3.  System.IO.Compression 4.2.0.0 could not be found error will be shown

### Error message shown

```
// System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
	// Assembly reference loading information:
	// There were some problems during assembly reference load, see below for more information!
	// Error: Could not find reference: System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

```

### Details
* Product in use: ILSpy
* Version in use: 7.1.0.6543
* Example application: ShareX

**Comment by greenozon** [comment]
Maybe dup?
#2080

**Comment by Droppers** [comment]
@greenozon yes, Microsoft does some magic mapping, at least I was able to find an answer to the mystery, do you want me to reply to existing issue and close this issue?

**Comment by greenozon** [comment]
Well, I"d like to receive some feedback on the case from ILSpy authors..
and yeah - thanks for good piece of info!
