### ISSUE TITLE
Make SearchTermMatches virtual for possible class extensions

### ISSUE THREAD

**Issue by beaverden** [icsharpcode/ILSpy#2493]
https://github.com/icsharpcode/ILSpy/blob/7716f9ccd82e0da0f82b7f4550da462d19ac1131/ILSpy/FilterSettings.cs#L76

Use case:

If nodes need to be filtered by something else than the exact term or maybe if we want to show only some of the methods, FilterSettings can be extended further to apply regex or preferential matching according to some internal rules.

**Comment by siegfriedpammer** [comment]
Well, currently that logic is not used anywhere in ILSpy and it is not planned to add a filter textbox for the tree view anytime soon. The filtering logic in `ILSpyTreeNode` is effectively dead code.

**Comment by beaverden** [comment]
It seemed to work though the last time I tried to filter something directly from the tree. I was left with only a few nodes. I created a FilterSettings object and passed in down to the AssemblyTreeNode as far as I remember (don't have the code anywhere). 

It is this really not usable or just not currently used?

**Comment by beaverden** [comment]
@siegfriedpammer Hello, are there any updates on this matter? It would be great to have any sort of resolution

**Comment by dgrunwald** [comment]
This functionality isn't likely to survive the next UI refactoring as it's dead code for us.
But we haven't touched this part of the UI in a long time, and aren't really likely to do so soon, as we're focusing on the decompiler engine itself. So I've just gone ahead and merged your PR.

I'm not exactly sure what the status on treeview filtering is / why we got rid of the text box for entering the search term. So it's possible you could run into tree view bugs here.
