### ISSUE TITLE
Missing cast

### ISSUE THREAD

**Issue by RKlier** [icsharpcode/ILSpy#250]
Having the following code

``` csharp
    static void Main(string[] args)
    {
      testFct((Int16)5);
      testFct(7);
    }

    static void testFct(object o)
    {
    }
```

the decompiled code is missing the cast/boxing in the first call to testFct:

``` csharp
    private static void Main(string[] args)
    {
      Program.testFct(5);
      Program.testFct(7);
    }
```

The generated IL code contains the boxing as `box [mscorlib]System.Int16`

**Comment by dgrunwald** [comment]
This is fixed on the newdecompiler branch.
