### ISSUE TITLE
Add .NET core versions and runtimes versions

### ISSUE THREAD

**Issue by jmroyb** [icsharpcode/ILSpy#2507]
**Is your feature request related to a problem? Please describe.**
When I need to know .NET Core versions and runtimes versions installed in a computer I have to run commands explaned here:

https://docs.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-windows

Can you add these information in main page? This is special helpful after PC referesh.

**Describe the solution you'd like**
Add .NET core versions and runtimes versions here:

![image](https://user-images.githubusercontent.com/4932314/134478957-e9db05f5-d290-4045-8ad4-515730a768c2.png)

**Additional context**
N/A

Thank you

**Comment by christophwille** [comment]
The intent of this information in About is for proper bug report (version of ILSpy, version of .NET it is running on) - not generic information about your computer.
