### ISSUE TITLE
Switch solutions to solution filters

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#2516]
There are signs that our ILSpy.AddIn for VS needs separate projects for 2017, 2019 and 2022. Also we want to split some logic from ILSpy.exe into an x-plat ILSpy.Core.dll, so that it can be used with ILSpyCmd. And, lastly there is the ILSpy.WithPackage.sln and Frontends.sln.

My proposal would be the following:
ILSpy.sln: (aka "ILSpy complete edition")
- ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.PowerShell.csproj
- ICSharpCode.Decompiler.PdbProvider.Cecil.csproj
- ICSharpCode.Decompiler.Tests.csproj
- ILSpy.csproj
- ILSpy.Core.csproj
- ILSpy.Tests.csproj
- ILSpy.BamlDecompiler.csproj
- ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.ReadyToRun.csproj
- TestPlugin.csproj
- ILSpy.Package.csproj
- ILSpy.AddIn.2017.csproj
- ILSpy.AddIn.2019.csproj
- ILSpy.AddIn.csproj

ILSpy.XPlat.slnf:
- ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler.Console.csproj
- ICSharpCode.Decompiler.PowerShell.csproj

ILSpy.Wpf.slnf:
- ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler.PdbProvider.Cecil.csproj
- ICSharpCode.Decompiler.Tests.csproj
- ILSpy.csproj
- ILSpy.Core.csproj
- ILSpy.Tests.csproj
- ILSpy.BamlDecompiler.csproj
- ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.ReadyToRun.csproj
- TestPlugin.csproj

ILSpy.AddIn.slnf:
- ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler.PdbProvider.Cecil.csproj
- ICSharpCode.Decompiler.Tests.csproj
- ILSpy.csproj
- ILSpy.Core.csproj
- ILSpy.Tests.csproj
- ILSpy.BamlDecompiler.csproj
- ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.ReadyToRun.csproj
- TestPlugin.csproj
- ILSpy.AddIn.2017.csproj
- ILSpy.AddIn.2019.csproj
- ILSpy.AddIn.csproj

ILSpy.Package.slnf:
- ICSharpCode.Decompiler.csproj
- ICSharpCode.Decompiler.PdbProvider.Cecil.csproj
- ICSharpCode.Decompiler.Tests.csproj
- ILSpy.csproj
- ILSpy.Core.csproj
- ILSpy.Tests.csproj
- ILSpy.BamlDecompiler.csproj
- ILSpy.BamlDecompiler.Tests.csproj
- ILSpy.ReadyToRun.csproj
- TestPlugin.csproj
- ILSpy.Package.csproj

The build server would continue using ILSpy.sln as-is.

**Comment by dgrunwald** [comment]
Sounds good to me.

**Comment by christophwille** [comment]
How about we keep the separate packages solution around? This makes the builds stay the same until we move.

**Comment by christophwille** [comment]
This is complete, the wapproj is tracked by #2490 and #2558
