### ISSUE TITLE
[UI] `ICSharpCode.ILSpy.TreeNodes.ResourcesFileTreeNode+SerializedObjectRepresentation` can't be properly shown

### ISSUE THREAD

**Issue by yyjdelete** [icsharpcode/ILSpy#2518]
### Steps to reproduce
1. Open `System.Windows.Forms` (netframework4.x) from GAC 
2. Switch to `Resources/System.Security.Policy.TrustManagerMoreInformation.resources`

### Error message shown
![image](https://user-images.githubusercontent.com/1819074/136814621-f0c646a3-2495-4575-8471-bf35069d2b68.png)

### Details
* Product in use: ILSpy
* Version in use: 7.2.0.6651-preview1 (since 7.0.0.6472-rc1)

**Comment by siegfriedpammer** [comment]
Thank you for pointing out this regression! @yyjdelete
