### ISSUE TITLE
code in winmd does not display

### ISSUE THREAD

**Issue by talenth** [icsharpcode/ILSpy#2524]
### Details
https://docs.microsoft.com/en-us/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript

According to the above url, operate until the sentence "Using the Windows Runtime from JavaScript and managed code", the compiled "SampleComponent.winmd" file, according to the text, the file contains the managed code and the Windows describing the code Metadata, but using "7.2.0.6651-preview1" does not show the implementation code of the "GetAnswer" function

**Comment by siegfriedpammer** [comment]
Yes, looking at a random winmd file on my computer, these are essentially like reference assemblies. All methods are declared `extern`.

**Comment by talenth** [comment]
I am learning this file format recently, can you tell me where to find the function implementation in this file ? ^_^

**Comment by siegfriedpammer** [comment]
I suspect that there is a `SampleComponent.dll` next to the `SampleCompnent.winmd` which contains the executable code. But, I am not sure, as I didn't try it myself.
