### ISSUE TITLE
Crash when opening ILSpy

### ISSUE THREAD

**Issue by tranthanhbinh2603** [icsharpcode/ILSpy#2537]
I got an error when I ran the latest ILSpy.exe, ILSpy 7.2 Preview 1, and even when I downgraded to 7.1 everything was the same:
![image](https://user-images.githubusercontent.com/65013334/140631819-f2a15784-a66f-4a17-ab58-621fc29ba1a5.png)
Does anyone have a solution for me?

**Comment by siegfriedpammer** [comment]
Looks like your download of ILSpy is broken... the ILSpy.exe.config file seems to be missing.
