### ISSUE TITLE
Open .ndll Files?

### ISSUE THREAD

**Issue by krigeta** [icsharpcode/ILSpy#2543]
Hello, is it possible to decompile the .ndll files using ILSpy?

**Comment by siegfriedpammer** [comment]
Could you share an example? Thanks!

**Comment by krigeta** [comment]
Yes I am glad to share it

[HULKv3.zip](https://github.com/icsharpcode/ILSpy/files/7503879/HULKv3.zip)
.

**Comment by dgrunwald** [comment]
What is `.ndll`? Is it related to .NET in any way?

**Comment by greenozon** [comment]
This is a reguarl .net assembly (heavily obfuscated BTW)
.NET Framework 4.5.2

as far as I see it is some part or addon of GTA V game

**Comment by krigeta** [comment]
@greenozon Yes, you are right, and I want to learn modding so I am trying to get the scripts out of it. so that's why I want to open it. is there any way to do that?

**Comment by christophwille** [comment]
Heavily obfuscated assemblies is usually an area where we don't fare well, and given that in a decade+ this is the first time this "file format" came up, we won't invest time in special-casing it.
