### ISSUE TITLE
Decompilation fails to escape closing brace ("}") properly within an interpolated string.

### ISSUE THREAD

**Issue by nedsociety** [icsharpcode/ILSpy#2544]
### Input code
The code in question is from a proprietary software that I'm not affiliated with so I believe I have no right to upload it. It might fall under fair use if used for this specific bug report, but making it publicly accessible would be definitely nay. If there's a channel to privately share it, please instruct the process.

### Erroneous output
```c#
                public void UpdateIsAwaitingConnectCallbacksOfEntity(List<ChannelEntity> channelEntity, bool isAwaitingConnectCallback)
		{
                //...
					PubNubInstance.PNLog.WriteToLog($"UpdateIsAwaitingConnectCallbacksOfEntity not found key/val1 {item.ChannelID.ChannelOrChannelGroupName} {item.ChannelID.IsChannelGroup.ToString()}}", PNLoggingMethod.LevelInfo);
		//...
                }
```
`error CS8086: A '}' character must be escaped (by doubling) in an interpolated string.`

### Details
* Product in use: e.g. ILSpy
* Version in use: 7.2.0.6702-preview2

The extra brace at the end of the string seems to be an errata originated from the input binary. It just seems like ILSpy fails to escape it. Unfortunately I've failed to reduce it into a minimal-complete-reproducible example as it seems to escape them properly on simpler cases.

**Comment by siegfriedpammer** [comment]
To make things easy, send the binary to siegfried.pammer@gmail.com, thanks!
