### ISSUE TITLE
How to remove some of references from assembly?

### ISSUE THREAD

**Issue by SirDeveloperOrg** [icsharpcode/ILSpy#2556]
Hi, How can I remove some of references from assembly?
![image](https://user-images.githubusercontent.com/93499598/142670756-c6b34323-f0e8-4980-bfc3-9ebebf963f1f.png)

**Comment by siegfriedpammer** [comment]
You can't. ILSpy cannot edit assemblies out of the box. You might be able to do so using [Reflexil](http://reflexil.net/).

**Comment by greenozon** [comment]
@SirDeveloperOrg 
take a look on another tool(s)
e.g.:

![image](https://user-images.githubusercontent.com/765343/142680764-de44df33-a2ad-4716-a4af-dc61b4331f1b.png)

**Comment by greenozon** [comment]
Checked Reflexil for .NET Reflector - as mentioned by @siegfriedpammer  - could delete referenced assemblies as well, e.g.:

![image](https://user-images.githubusercontent.com/765343/142682593-37243975-61ce-49d8-8243-970220ce108a.png)

**Comment by siegfriedpammer** [comment]
@greenozon Reflexil is also available for ILSpy... no need to use other tools ;-)

**Comment by greenozon** [comment]
@siegfriedpammer  shame on me! you are very right!
PS Never know it supports that old good plugin!
