### ISSUE TITLE
Can i use it for .NET Core 3.1  assemblies / applications?

### ISSUE THREAD

**Issue by jayjupdhig** [icsharpcode/ILSpy#2559]
Hi there

As the title says - can i use it for .NET Core 3.1 libraries / assemblies?

So i think, the "usual" .NET Framwork (currently in V 5.x) is not Byte-Code (MSIL-Code?) compatible with the new ".NET core" framework version - right? (So, e.g., we can't mix assemblies / appss in different frameworks, e.g. a core 3.1 assembly in a 5.x app or vice versa... in that case, a decompiler for the "usual" (non-core) framework will not work with core compilations?

Because of that my question regarding your decompiler...

Thank you very much for your feedbacks.

**Comment by christophwille** [comment]
.NET Framework 4.x is the "legacy" .NET Framework, anything 1-5 .NET Core and .NET 6 are the "new" .NET Framework, so the progression is .NET Core 3.1 -> 5.0 -> 6.0 (here the "Core" was dropped).

Yes, you can use ILSpy for all .NET Frameworks plus Mono, plus Silverlight plus Unity.

**Comment by jayjupdhig** [comment]
Thank you very much for your fast feedback!! :-)

**Comment by jayjupdhig** [comment]
After downloading and installing i see it in the plugins list on my vs 2019...

But when i right-click an assembly dll, then select "open with", i get that dialog here. And there is not ilspy entry:

![image](https://user-images.githubusercontent.com/42765391/142857222-6e7251c4-7f92-4023-9c12-a5fa77f86f72.png)

**Comment by christophwille** [comment]
The VS addin is enabled on the References (NuGet, asm refs) node and project node (Output). Not on any file that happens to float around in the project. That indeed is not working.

**Comment by jayjupdhig** [comment]
Thank you very much. I need to compare 2 files with same name and same classes (but not 100% same source)... so then i need to add both of them as a reference. Don't know this will work. Will look on it...

![image](https://user-images.githubusercontent.com/42765391/142858290-b2cadf29-fd96-4b71-80e0-b2ed341392df.png)

**Comment by jayjupdhig** [comment]
May there is a version / fork that runs as a windows .exe application instead as a VS plugin...?

**Comment by christophwille** [comment]
Yes, check out the repo main page for all the various frontends to our decompilation engine.

**Comment by jayjupdhig** [comment]
Thank you very much!! :-)
