### ISSUE TITLE
ilspycmd help text

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#2563]
Output from `ilspycmd --help` starts with
`Usage: ilspycmd [arguments] [options]`

This is obviously wrong. Maybe it does _also_ accept that kind of input, but it empirically allows for the more normal form, where the syntax would be displayed as
`Usage: ilspycmd [options] [arguments]`

Additionally, it only allows a single assembly as input, why the trailing `s` in `arguments` and `Arguments` should be dropped.

**Comment by christophwille** [comment]
Sorry, I don't get what you are getting at. Sample call:

`ilspycmd some.dll -o c:\`

Yes, there is only arg0 at the moment, however, the options (with or without parameters) do follow that. What is your "more normal form" meant to change/do better?

**Comment by tamlin-mike** [comment]
It's not _my_ normal form, it's universal.

The normal order for any command line program input is to first take options, followed by zero or more arguments in form of filenames et c. The only two I know of specifying this opposite order are zpaq and ilspycmd, and I find both equally confusing every time I use them.

What it's meant to change should be obvious; swap the order in the synopsis to match the gazillions of command line programs preceeding it.

Besides the obvious of familiarity, what it does better is to allow command line completion on Microsoft platforms without eradicating already written options (completion on Windows clobbers/destroys/erases everything after the completion).

The fact that ilspycmd accepts the "strange" order _in addition_ to the normal order (since `ilspycmd -o z:\tst some.dll` also works), I have no opinion about.

**Comment by christophwille** [comment]
Neither the help text generation https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler.Console/IlspyCmdProgram.cs#L30 nor the command line parsing is done by us - that's what libraries are for.

Now, I know and use:

`npm update -g`

`az account show -o table`

`choco upgrade all -y`

`dotnet new mvc –name MVCWebApplication`

So, those are all wrong?

**Comment by siegfriedpammer** [comment]
I think he has a point. All those examples you are listened use "commands", "subcommands" or "verbs" in front of the options, which are then followed by arguments. There's even been a bug raised with the library we use https://github.com/natemcmaster/CommandLineUtils/issues/303 and a fix was already contributed.

**Comment by siegfriedpammer** [comment]
Fixed in 2e5411732af7a61b14a1a198e686f76faa6c1499
