### ISSUE TITLE
Installer: Additional UI

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2574]
Something along the lines of 

* "Do you want to install" (with hint where it will go)
* "Installation complete" (with hint where it is)

No feedback at all is bad. (or does VSCode per-user show no UI either?)

**Comment by Rpinski** [comment]
Added a dialog step before installation start, where user can see the target directory.

**Comment by christophwille** [comment]
Thanks, exactly what I would have expected - Welcome, Install, Done. Thanks!
