### ISSUE TITLE
2022 Extension does not decompile async correctly

### ISSUE THREAD

**Issue by jetuser** [icsharpcode/ILSpy#2575]
Installed the 2022 ilspy extension and decompiled a reference which resulted in the async state machine code that happens when it can't figure out the pattern. However on the standalone client, it was able to decompile correctly.

**Comment by christophwille** [comment]
Just to make sure - you used the context menu "Open in ILSpy" and *not* F12?

**Comment by christophwille** [comment]
No feedback, closing.
