### ISSUE TITLE
Support for readonly struct members

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2576]
### Input code
Please provide the input that failed to decompile.

```c#
        struct TestStruct2
        {
            public readonly int Property => 123;

            public int Property_ReadonlyGet { readonly get; set; }
            public int Property_ReadonlySet { get { return 0; } readonly set { int a = 1; } }
            
            public readonly int Method() => 123;
            public readonly int this[int indexerKey] => 123;
        }
```

### Erroneous output
```c#
private struct TestStruct2
{
	public readonly int Property => 123;

	public int Property_ReadonlyGet { get; set; }

	public int Property_ReadonlySet
	{
		get
		{
			return 0;
		}
		readonly set
		{
			int a = 1;
		}
	}

	public readonly int this[int indexerKey] => 123;

	public readonly int Method()
	{
		return 123;
	}
}
```
Please pay attention to Property_ReadonlyGet 
it is missing readonly modifier

### Details
ILSpy version 7.2.0.6792-preview4
.NET version 4.8.3928.0

**Comment by siegfriedpammer** [comment]
This is not a bug, at least not in the decompiler. Could be a compiler bug 😄. If you look at [sharplab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLTJrAlgY1QGygFtgATKZAHwwThxgAIAVFGAZRlvoCYBYAKADeAhqIYABAMwMsAO0YAFBAHsADhAQwAngH0A4hEaCGAc0MBuBsgsMAviLFSZ8hkrUbtOgErRSy2fhaBkYMSFB+AVqmNtYwlvb8tkA=) you can see that the generated attributes and IL are the same for both properties.

The compiler emits `[IsReadOnly]` for both properties. For simplicity we decided to remove `readonly` completely, as it is implicitly emitted by the compiler anyway.

**Comment by greenozon** [comment]
Agree, closing
