### ISSUE TITLE
How to export code for only public types and members

### ISSUE THREAD

**Issue by laicasaane** [icsharpcode/ILSpy#2584]
**Is your feature request related to a problem? Please describe.**
I mainly work with Unity engine and need a custom code generation workflow that can be developed inside Unity itself. To do that, I need to import `Microsoft.CodeAnalysis.dll` and `Microsoft.CodeAnalysis.CSharp.dll` into a Unity project so my generator plugins can be integrated into an external generation process. However, Unity will complain from time to time, like this

```
Unloading broken assembly Assets/Plugins/Microsoft.CodeAnalysis.dll, this assembly can cause crashes in the runtime
Unloading broken assembly Assets/Plugins/Microsoft.CodeAnalysis.CSharp.dll, this assembly can cause crashes in the runtime
```

It's very annoying but there is no way to stop it. So I imagine I can decompile these 2 dlls into 2 projects which contain only public API (with the method body throws NotImplementedExceptiom). These projects will allow me to develop in Unity with peace.

I found the function to export code in ILSpy. But sadly it will export everything. There are tons of files generated for `Microsoft.CodeAnalysis.dll` and I have to manually delete internal or private types and methods. This is quite frustrating and time consuming.

So I hope we can have a feature to export only public code. And maybe another feature to export lightweight public code (i.e. public methods that throw NotImplementedException).

**Comment by christophwille** [comment]
Exporting only public code would mean incomplete and non-compilable code. I don't think that is something we'd consider.

**Comment by laicasaane** [comment]
> Exporting only public code would mean incomplete and non-compilable code.
Actually I don't need them to be compilable. They won't actually run inside Unity, but they are there just for compatibility reasons. Because I want to be able to develop the tools that rely on `Microsoft.CodeAnalysis` namespace inside Unity, but ultimately those tools will run outside Unity and grab the real `Microsoft.CodeAnalysis.dll` on the way.

Btw, I'm in the process of develop another tool to serve my needs.

**Comment by siegfriedpammer** [comment]
> Btw, I'm in the process of develop another tool to serve my needs.

I was going to suggest the same, as your use-case seems quite specific and would not fit into a general purpose tool like our decompiler, however, I can provide you with a partial solution to get you started (using our type system and syntax tree implementation).

Example:

```csharp
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.Syntax;
using ICSharpCode.Decompiler.CSharp.Transforms;
using ICSharpCode.Decompiler.Metadata;
using ICSharpCode.Decompiler.TypeSystem;
using System.Reflection.PortableExecutable;

Console.WriteLine("Hello, World!");

string fileName = typeof(PEFile).Assembly.Location;
string path = Path.Combine(Path.GetDirectoryName(fileName), "output");
Directory.CreateDirectory(path);
PEFile inputFile = new PEFile(fileName, PEStreamOptions.PrefetchEntireImage);

var resolver = new UniversalAssemblyResolver(fileName, throwOnError: false, ".NETStandard, Version=v2.0");

DecompilerTypeSystem typeSystem = new DecompilerTypeSystem(inputFile, resolver);
var settings = new DecompilerSettings(ICSharpCode.Decompiler.CSharp.LanguageVersion.Latest)
{
    DecompileMemberBodies = false,
};

var decompiler = new CSharpDecompiler(typeSystem, settings);
decompiler.AstTransforms.Add(new RemovePrivateItemsVisitor());

foreach (var type in typeSystem.MainModule.TopLevelTypeDefinitions)
{
    if (type.EffectiveAccessibility() != Accessibility.Public)
        continue;
    File.WriteAllText(Path.Combine(path, type.FullName + ".cs"), decompiler.DecompileAsString(type.MetadataToken));
}

internal class RemovePrivateItemsVisitor : DepthFirstAstVisitor, IAstTransform
{
    void IAstTransform.Run(AstNode rootNode, TransformContext context)
    {
        rootNode.AcceptVisitor(this);
    }

    public override void VisitMethodDeclaration(MethodDeclaration methodDeclaration)
    {
        base.VisitMethodDeclaration(methodDeclaration);

        var symbol = methodDeclaration.GetSymbol() as IMethod;

        if (symbol.EffectiveAccessibility() != Accessibility.Public)
        {
            methodDeclaration.Remove();
            return;
        }

        // TODO check if member needs a body
        // replace body with throw null;
        methodDeclaration.Body = new BlockStatement { Statements = { new ThrowStatement(new NullReferenceExpression()) } };
    }

    // TODO other members
}
```

**Comment by laicasaane** [comment]
Thanks! This is indeed helpful.
