### ISSUE TITLE
Cannot decompile "using" correctly?

### ISSUE THREAD

**Issue by Suceru** [icsharpcode/ILSpy#2588]
### Steps to reproduce
1. Decompile
2. Check the code

### Error message shown
This is  the ILSpy
```
public static string SaveXmlToString(XElement node, bool throwOnError)
        {
            using StringWriter stringWriter = new StringWriter();
            SaveXmlToTextWriter(node, stringWriter, throwOnError);
            return stringWriter.ToString();
        }
```
This is the right
```
public static void SaveXmlToStream(XElement node, Stream stream, Encoding encoding, bool throwOnError)
        {
            using (TextWriter textWriter = (encoding != null) ? new StreamWriter(stream, encoding) : new StreamWriter(stream))
            {
                SaveXmlToTextWriter(node, textWriter, throwOnError);
            }
        }
```
All the using(){} that appear during decompilation do not decompile correctly, they are all lines ending with a semicolon.  

### Details
* Product in use: ILSpy.AddIn.VS2022_7.2.0.6791-preview3.vsix

**Comment by siegfriedpammer** [comment]
The methods listed above are not the same. They have different names and parameters, so there is no "right" or "wrong".

**Comment by siegfriedpammer** [comment]
> All the using(){} that appear during decompilation do not decompile correctly, they are all lines ending with a semicolon.

This is a recent C# 8.0 language feature, see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using#using-declaration. If you don't like it, you can either lower the language version used for decompilation using the language version dropdown or uncheck the setting in the settings dialog:

![image](https://user-images.githubusercontent.com/344204/147506738-007bb41a-3d0c-4912-83b6-b1f51f78786a.png)

Hope this helps!
