### ISSUE TITLE
Shows wrong DLL version

### ISSUE THREAD

**Issue by onefreddy** [icsharpcode/ILSpy#2599]
ILSpy 7.2 Preview 3
link for testing https://www.nuget.org/packages/Xamarin.AndroidX.Core/
Instead of version 1.6.0.3, it shows 1.0.0.0

screens:
![image](https://user-images.githubusercontent.com/73015418/148088669-a68624b6-74e7-4da2-b8e6-9af6e65e7416.png)
![image](https://user-images.githubusercontent.com/73015418/148088738-14ca8008-5163-4886-9461-51da1c1e604f.png)

**Comment by siegfriedpammer** [comment]
Assembly version and package version are two different things and thus they do not have to be identical. (Which is something I consider a flaw in the nuget ecosystem, but I guess that ship has sailed.)

Most people expect them to be the same, but sadly they are not always the same.

**Comment by onefreddy** [comment]
@siegfriedpammer ok, but this package is official from Microsoft xamarin team. Are you hoping to say that the people there are so stupid that the reason is that they do not know how to fill in the assembly version?

**Comment by dgrunwald** [comment]
Or they intentionally don't embed the correct version number in the assembly. Using fixed version numbers in strong-named assemblies can sidestep the need for `<bindingRedirect>`s.
In any case, ILSpy is displaying the information that the DLL actually contains. There's no need for that to match the information in the .nuspec file.

**Comment by siegfriedpammer** [comment]
> @siegfriedpammer ok, but this package is official from Microsoft xamarin team. Are you hoping to say that the people there are so stupid that the reason is that they do not know how to fill in the assembly version?

I never used the word "stupid" or attacked anyone personally (at least not knowingly) and thus I can answer your question: **NO**, I am not saying that anyone is stupid - why would you assume I do?

I just explained what ILSpy is doing and that ILSpy is not wrong. Your expectation that the package version and the assembly version should be the same is **reasonable**, but does not always hold. As @dgrunwald pointed out, there might be a variety of reasons to not use the same version number for the assembly and the package.

**Comment by onefreddy** [comment]
@dgrunwald @siegfriedpammer thanks, keep making ILSpy, we appreciate it 🧡
