### ISSUE TITLE
BAML decompiler missing required class prefix on static fields in binding?

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#2610]
Tested with ILSpy 65792dfa5.

Looking at Microsoft.VisualStudio.Editor.Implementation.dll 16.11.31.23313
(it's in Common7\IDE\CommonExtensions\Microsoft\Editor\),
inside _Microsoft.VisualStudio.Editor.Implementation.g.resources_
baml _codelens/common/controls/sharedresource.baml_

At the very bottom of this file in
`<Style x:Key="{x:Static controls:CodeSenseResources.TreeViewStyleKey}" TargetType="{x:Type TreeView}">`
we can find
` <ScrollViewer [...] HorizontalScrollBarVisibility="{TemplateBinding HorizontalScrollBarVisibility}"`

The `HorizontalScrollBarVisibility` in the `TemplateBinding` seems to not exist in `TreeView`. If we look a little earlier in that Style we find
`<Setter Property="ScrollViewer.HorizontalScrollBarVisibility" Value="Disabled" />`
suggesting the value it was intended to refer to was, indeed, `ScrollViewer.HorizontalScrollBarVisibility`. Same goes for `VerticalScrollBarVisibility`.

There are however a number of unknowns here:
Is the BAML decompiler really mis-decompiling this binding, have Microsoft simply shipped broken XAML, is there a missing Style-wide typename-introducer for `ScrollViewer` (I don't know XAML enough to know if this is even possible), or maybe something I haven't even thought of?

Still, I judged it important enough to document the issue, just in case it's indeed a BAML decompiler problem.

**Comment by siegfriedpammer** [comment]
You are right. The easiest fix would be to always emit fully-qualified names in template bindings. Would this be an acceptable solution? The reason is, that we actually do not know the target type of the style at that point in the decompilation process.

**Comment by tamlin-mike** [comment]
Sorry for the late reply. Provided always emitting FQN doesn't mess something else up, I don't see a problem with that fix. One could even argue that spelling out the FQN could make it easier to understand. Removing reduncy (from decompiled code) is easy (if boring); adding unknowns is... less obvious. :-)
