### ISSUE TITLE
How can I specify a dependency when ILSpy resolve failed?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2614]
Is there an event like `AppDomain.AssemblyResolve` or `BaseAssemblyResolver.ResolveFailure`?

**Comment by dgrunwald** [comment]
Not an event, but you can write your own `IAssemblyResolver` implementation wrapping the `UniversalAssemblyResolver` to detect when one of the `Resolve*` methods returns `null`.

**Comment by CreateAndInject** [comment]
Seems I can only support `IAssemblyResolver` for such as `DecompilerTypeSystem` or `XamlDecompiler`, but can not for `LoadedAssembly`, so ILSpy doesn't load my dependency to the UI AssemblyList.
Can ILSpy add an event?

**Comment by CreateAndInject** [comment]
I can add to AssemblyList myself, thanks!
