### ISSUE TITLE
程序集窗口标题栏出现错误

### ISSUE THREAD

**Issue by OfflineJudge** [icsharpcode/ILSpy#2619]
### 步骤
1. 将程序集拖拽出窗口使之成为独立窗口。
2. 将程序集窗口拖至右边框，使之隐藏一部分。
3. 缓缓将窗口拖回，标题栏样式改变。
### 图片

![image](https://user-images.githubusercontent.com/66544162/152280881-4cdfb444-af69-449d-91be-d6c0be74af59.png)

**Comment by maikebing** [comment]
建议你想办法翻译为英文。

**Comment by siegfriedpammer** [comment]
I think this issue should be reported at https://github.com/Dirkster99/AvalonDock
