### ISSUE TITLE
Wrong decompilation

### ISSUE THREAD

**Issue by RumitKmphitech** [icsharpcode/ILSpy#2621]
I am use A ILSPY Latest and v5.2 and i also use a c# language version 8.0/2019 but after run this code in my unity v2019 show the error as like ({,},>,<) etc... and I attach  the screenshot Please Help me Thank You...
![Screenshot 2022-02-04 144204](https://user-images.githubusercontent.com/92717553/152503567-5a2bf1b2-17dc-4628-bc36-b3c6e7a3604e.png)

**Comment by siegfriedpammer** [comment]
Could you please provide an example snippet of the code that does not compile? Also, I think it will be necessary for you to share the assembly in question with us. Otherwise we might not be able investigate the issue properly. Thanks!

**Comment by christophwille** [comment]
No feedback, closing.
