### ISSUE TITLE
Installed ILSpy AddIn VS2022 7.2.0.6839-preview4 but cannot find it from menu

### ISSUE THREAD

**Issue by huanlin** [icsharpcode/ILSpy#2628]
### Steps to reproduce
1. Install [ILSpy.AddIn.VS2022_7.2.0.6839-preview4.vsix](https://github.com/icsharpcode/ILSpy/releases/download/v7.2-preview4/ILSpy.AddIn.VS2022_7.2.0.6839-preview4.vsix)
2. Start Visual Studio 2022 Preview version 17.1.0 Preview 5.0
3. Cannot find ILSpy from editor's context menu, nor can I find it from Tools menu.

**Comment by christophwille** [comment]
I installed in p6 via https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy2022 - works for me

![image](https://user-images.githubusercontent.com/344208/153367342-c0679d59-a115-4324-893d-dd8aa13f36df.png)

**Comment by huanlin** [comment]
> I installed in p6 via https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.ILSpy2022 - works for me

So I upgrade my Visual Studio 2022 from Preview 5 to Preview 6, and ILSpy context menu still doesn't show. However, the I noticed that my shortcut of VS2022 has extra arguments: `/rootSuffix Exp`. So I remove this argument and ILSpy worked!

Close this issue now. Thanks for your information!
