### ISSUE TITLE
What is the option to make by default all objects expandable?

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2632]
Pardon this stupid question, what is the option to make by default all objects expandable?
instead of seeing these "..." all around

IL used: 
ILSpy version 7.2.0.6843-rc
.NET version 4.8.3928.0

![image](https://user-images.githubusercontent.com/765343/154239346-b5baee54-644e-46d2-a9ec-dddbe0ef35a5.png)

**Comment by dgrunwald** [comment]
View > Options > Display > Expand member definitions after decompilation

**Comment by greenozon** [comment]
Great answer! thanks a lot

but I"ve got another one while I was testing your hint

so, if for example I'm having the "..." state and then I click the  "Expand member definitions after decompilation" checkbox 
then click OK - nothing happens!

Expected result - collapsed funtions should get be expanded right after OK

Why I' thinking this way? cause for example if you click the "Show line numbers" then OK - it is applied right after OK click..

Maybe it worth to do immediate action for all the checkboxes in Display section of Options?
