### ISSUE TITLE
Add nested-directories flag to ilspycmd

### ISSUE THREAD

**Issue by GreyXor** [icsharpcode/ILSpy#2635]
Hello,
GUI allows us to generate an output where each folder is correctly in a subfolder according to the namespace.

It will be useful to have this setting available in ilspycmd.

![image](https://user-images.githubusercontent.com/79602273/156595666-8b35a8d4-921b-483e-b070-214929531492.png)

**Comment by siegfriedpammer** [comment]
Fixed in #2636
