### ISSUE TITLE
v7.2 NuGet misses one dependency

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2637]
https://github.com/icsharpcode/ILSpy/blob/104407a3ef1d6307cef7a84df9ccba88abe35482/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs#L553

We started using Microsoft.Win32.Registry in 7.2 - but missed to add it to the nuspec too. Being used only in WholeProjectDecompiler, and that comes with a catch clause so the exception won't surface. Fix: fix the nuspec.

Edit: ilspycmd not affected because it uses project reference.

**Comment by siegfriedpammer** [comment]
https://github.com/icsharpcode/ILSpy/releases/tag/v7.2.1 contains a fix for this. `master` no longer uses a handwritten nuspec.
