### ISSUE TITLE
AwaitInFinallyTransform: ILAst must form a tree

### ISSUE THREAD

**Issue by LuisPerez89** [icsharpcode/ILSpy#2652]
nuget package: Microsoft.Azure.Cosmos - 3.23.0
dll: \lib\netstandard2.0\Microsoft.Azure.Cosmos.Client.dll

![Capture](https://user-images.githubusercontent.com/92027653/158551227-0edf51d7-4b5f-458e-bdf3-9fe2320e4283.PNG)

![Capture2](https://user-images.githubusercontent.com/92027653/158551276-355a02f4-7226-45d7-8278-a1419c1436a4.PNG)

I only get this error if I point directly to the ICSharpCode.Decompiler project, because, if instead I use the ICSharpCode.Decompiler nuget package, I dont receive any error at all, the library just get stuck.

**Comment by dgrunwald** [comment]
That's a debug-only assertion that the ` AwaitInFinallyTransform` introduced a cycle in what's supposed to be a tree data structure.
In release builds that cycle goes undiagnosed; but it's likely that this causes an infinite loop.
