### ISSUE TITLE
Silent crash on latest CI build (8.0.0.6933-alpha1) start

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2659]
### Steps to reproduce
1. Download latest CI build from here https://github.com/icsharpcode/ILSpy/actions/runs/2018900654   (debug build)
2. Run it
3. 

### Error message shown
silent crash
head lines from Report.wer file:
```
Version=1 EventType=APPCRASH EventTime=132924536682286110 ReportType=2 Consent=1 ReportIdentifier=ac7ff5a3-aa1c-11ec-a5a5-5cf9dd47c047 IntegratorReportIdentifier=ac7ff5a2-aa1c-11ec-a5a5-5cf9dd47c047 Response.type=4 Sig[0].Name=Application Name Sig[0].Value=ILSpy.exe Sig[1].Name=Application Version Sig[1].Value=8.0.0.6933 Sig[2].Name=Application Timestamp Sig[2].Value=6216d2c0 Sig[3].Name=Fault Module Name Sig[3].Value=KERNELBASE.dll Sig[4].Name=Fault Module Version Sig[4].Value=6.1.7601.24408 Sig[5].Name=Fault Module Timestamp Sig[5].Value=5c92f34f Sig[6].Name=Exception Code Sig[6].Value=e0434352 Sig[7].Name=Exception Offset Sig[7].Value=000000000000be0d DynamicSig[1].Name=OS Version DynamicSig[1].Value=6.1.7601.2.1.0.256.1 DynamicSig[2].Name=Locale ID DynamicSig[2].Value=1058 DynamicSig[22].Name=Additional Information 1 DynamicSig[22].Value=8ff5 DynamicSig[23].Name=Additional Information 2 DynamicSig[23].Value=8ff57a46ef6fc6dec66d4c16418e541a DynamicSig[24].Name=Additional Information 3 DynamicSig[24].Value=da19 DynamicSig[25].Name=Additional Information 4 DynamicSig[25].Value=da1907f3a88e6c70410a00070a88f036 
.......
```

### Details
* Product in use: [ILSpy 8.0.0.6933-alpha1 (Debug)](https://github.com/icsharpcode/ILSpy/suites/5744847862/artifacts/190599610)
* Windows 7 SP1 x64
*

PS latest release - ILSpy version 7.2.0.6844  runs OK

**Comment by siegfriedpammer** [comment]
ILSpy 8.0 uses .NET 6.0 and according to https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md Windows 7 is only supported, if you have access to "extended security updates", which (I guess?) you get via a support contract with MS.

**Comment by greenozon** [comment]
Yeah, that might be a potential reason, but I did try to investigate more
so I've opened up .hdmp from ILSpy and inside VS I've found this:

![image](https://user-images.githubusercontent.com/765343/159802611-2f54cebf-a2f7-40e8-8844-d9d049264190.png)

the quesiton is: why the basic issue like on pic leads to silent crash?

**Comment by greenozon** [comment]
Is it possible to catch these exceptions @ ILSpy level and be more user friendly to end user?

**Comment by greenozon** [comment]
Issue tracked down and fixed

the bug was somehow inside the very 1st GA release of .NET6 - version 6.0.100,
after I"ve removed it ILSpy 8 alpha started up successfully! but complained I need to install .NET6,
so after installing this - 
.NET 6.0 Desktop Runtime (v6.0.3) - Windows x64 Installer!
the IL8 successfully booted up @Win7 x64!!!

![image](https://user-images.githubusercontent.com/765343/159815644-8bfc2cc7-0aa4-49af-bdaa-1e1f686329cf.png)


BTW, why IL8 shows > 1 About tab? :)
proposing to show just 1

**Comment by yyjdelete** [comment]
For WPF, it's an known issue 
https://github.com/dotnet/core/issues/7176
And seems it will never be fixed(build with newer version and run with 6.0.0/6.0.1) without the workaround in 7176
https://github.com/dotnet/wpf/pull/6101#issuecomment-1039089267

**Comment by christophwille** [comment]
No, old plugins won't run. Simply because we are also rearchitecting a few things (major version number).

**Comment by siegfriedpammer** [comment]
Yes, we are moving a lot of stuff around simply to make code-sharing (or feature-sharing) a lot easier for ILSpy, ilspycmd, ILSpyAvalonia and other flavors of ILSpy. The decompiler engine will probably not see as many breaking changes, but the ILSpy APIs get a much needed makeover after many years of almost no refactorings/clean-up. In its core ILSpy is still the same as it was 11 years ago, when we quickly threw together something to get the decompiler shipped after Red Gate's famous statement concerning Reflector.
