### ISSUE TITLE
Customize Syntax Highlighting

### ISSUE THREAD

**Issue by SirDeveloperOrg** [icsharpcode/ILSpy#2661]
Hi, I want to customize syntax highlighting, I have been trying for several days to do that but since I don't have much information's about how ILSpy works I couldn't do much things.
Here it is the my modified version of CSharpHighlightingTokenWriter.cs file:
[CSharpHighlightingTokenWriter.txt](https://github.com/icsharpcode/ILSpy/files/8346044/CSharpHighlightingTokenWriter.txt)
 It's working a little bit but it's have so many problems for example in bellow image it's highlighted "enum" as "class" but when I go to definition of it it's show the actual color of it. 

![image](https://user-images.githubusercontent.com/93499598/160018895-772658cd-7963-4080-997e-977d35233797.png)

![image](https://user-images.githubusercontent.com/93499598/160018742-17c12fb1-c206-49ed-82e1-e842aff173f7.png)

I think the way I try to get the type of Identifier is wrong, Is there any common method to get the type of Identifier?
I will be very grateful if anyone could guide me, I want to highlight class, method, field, method parameter, namespace, enum, struct, event & etc...
Regards.

**Comment by christophwille** [comment]
See #534 - we have that feature on the back log for a long time, but never got around to it (and it is still low-pri). Contributions welcome along the lines of the implementation suggestion.
