### ISSUE TITLE
Crash right clicking on not loaded reference

### ISSUE THREAD

**Issue by Hefaistos68** [icsharpcode/ILSpy#2664]
### Steps to reproduce
1.  Get the Custom Document Well Extension for VS2017, (MS DevLabs)
2. open the extension DLL in ILSpy
3. locate the RegexColorManager
4. go to the ApplyRegexColors() method
5. at the end of the method right click on RaiseEvent

### Error message shown
![image](https://user-images.githubusercontent.com/8855055/161385884-c4d6b1bf-0d3f-4924-a764-550e88fc05d9.png)
(Sorry, couldnt get the text from Win7 dialog box)
```

```

### Details
* ILSpy latest version as of writing (7.2.0.6844)
* Win7

**Comment by xMunduSCodEx** [comment]
Same, it crash whenever I move the mouse pointer

**Comment by siegfriedpammer** [comment]
https://github.com/icsharpcode/ILSpy/releases/tag/v7.2.1 contains a fix for this. Thanks for reporting!
