### ISSUE TITLE
[Feature Request] Namespace Nesting in the Tree View

### ISSUE THREAD

**Issue by ds5678** [icsharpcode/ILSpy#2666]
Currently, ILSpy always flattens namespaces in the tree view like this:
```
{} Top.Middle
{} Top.Middle.Bottom1
{} Top.Middle.Bottom2.EvenLower
{} Top.Middle.Bottom3
```
It would be more intuitive and less cluttering if there was an option to organize it like this:
```
{} Top.Middle
    {} Bottom1
    {} Bottom2.EvenLower
    {} Bottom3
```
Where `Bottom1`, `Bottom2.EvenLower`, and `Bottom3` are child nodes that can be collapsed into `Top.Middle`.

**Comment by siegfriedpammer** [comment]
As the namespaces in metadata are just strings, how exactly would you separate "Top.Middle" from "Buttom2.EvenLower"? What are the rules?

A simple rule would be: new level after every dot, and would look like this:

```
{} Top
    {} Middle
        {} Bottom1
        {} Bottom2
            {} EvenLower
        {} Bottom3
```

But that is not exactly what you want, right?

**Comment by ds5678** [comment]
I chose my example like that because it's more vertically concise, but dividing by dots is also also okay.

**Comment by ds5678** [comment]
Thank you
