### ISSUE TITLE
什么时候可以集成EXE调试功能？早期2.0版本时是有这个功能的，之后没有了。

### ISSUE THREAD

**Issue by chinapsu** [icsharpcode/ILSpy#2671]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is and why it's important to you. Ex. I'm always frustrated when [...]
Any (even unsuccessful) ways in which you've tried to workaround the problem currently

**Describe the solution you'd like**

**Additional context**

**Comment by christophwille** [comment]
"When can the EXE debugging function be integrated? This function was available in the early 2.0 version, but not after that." That was the title.

**Comment by christophwille** [comment]
No, there are no plans to bring back the debugger.
