### ISSUE TITLE
Feature Request: Scan for MEF assemblies in a user controlled directory.

### ISSUE THREAD

**Issue by InKahootz** [icsharpcode/ILSpy#2672]
**Is your feature request related to a problem? Please describe.**
It's particularly painful to add plugins when ILSpy is installed via the Windows Store since the directory it's installed in (for me currently: `C:\Program Files\WindowsApps\17310ICSharpCodeTeam.ILSpy_7.2.6856.0_neutral__jpqg2ewkdrg54`) is heavily permission restricted. I cannot copy my plugin dlls to the current install directly without modifying lots of folder permissions. Not to mention, this directory will change when the version is updated.

**Describe the solution you'd like**
I would like a user controlled directory to be scanned for MEF plugins. 
Something like `%APPDATA%\ICSharpCode\ILSpy` or even the package storage area `%LOCALAPPDATA%\Packages\17310ICSharpCodeTeam.ILSpy_jpqg2ewkdrg54\LocalCache\Roaming\ICSharpCode`.

It would have to be compatible with both the portable and Windows Store version so I doubt the latter would be the best solution.

**Additional Details**

I _will_ do the PR myself as long as it's decided that this is a worthwhile idea to pursue!

**Comment by christophwille** [comment]
We had a discussion around this here https://github.com/icsharpcode/ILSpy/discussions/2601

At the point of writing, the MSIX is now history, and we have the installer only. This installer will replace at RTM of v8 the existing MSIX-based Microsoft Store ILSpy version. I don't know for sure, but I think this will install to a more deterministic location.

**Comment by InKahootz** [comment]
I did search the issues and missed that since it was in discussions. 

I will close this since v8 seems to install to `%LOCALAPPDATA%\Programs\ILSpy` which is acceptable to write to!
