### ISSUE TITLE
[Feature Request]: .NET 6 Target with Trimming

### ISSUE THREAD

**Issue by ds5678** [icsharpcode/ILSpy#2673]
A .NET 6 target for the decompiler project with [trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming) would allow this to be used in [NativeAOT](https://github.com/dotnet/runtime/issues/61231) apps.

Issues to be dealt with:
* A bunch of Linq substitutes need excluded on .NET 6 with preprocessor directives.
* `ResXResourceWriter.cs` uses `TypeDescriptor.GetConverter` and [`BinaryFormatter.Serialize`](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete).
* `UniversalAssemblyResolver.cs` calls `Type.GetType("Mono.Runtime")` which I think can be safely excluded with a preprocessor directive on .NET 6.
* 6a6e82c3722d7adde7b7f93da25455b8e792000f added [ReferenceAssemblyAnnotator](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator) which breaks when targeting multiple frameworks tunnelvisionlabs/ReferenceAssemblyAnnotator#92

**Comment by christophwille** [comment]
What sort of app using a decompiler would be using NativeAOT?

**Comment by siegfriedpammer** [comment]
ReferenceAssemblyAnnotator is not going to be removed unless Microsoft adds nullable attributes to netstandard2.0 out of the box. Too many customers depend on netstandard2.0, so we cannot upgrade and of course adding NRT to the decompiler is also a must at this point.

Thank you for your understanding!

**Comment by ds5678** [comment]
> What sort of app using a decompiler would be using NativeAOT?

I have a [game recovery project](https://github.com/AssetRipper/AssetRipper) where performance is very important. NativeAOT would help with that.

**Comment by ds5678** [comment]
> ReferenceAssemblyAnnotator is not going to be removed unless Microsoft adds nullable attributes to netstandard2.0 out of the box. Too many customers depend on netstandard2.0, so we cannot upgrade and of course adding NRT to the decompiler is also a must at this point.
> 
> Thank you for your understanding!

I'm not suggesting you remove ReferenceAssemblyAnnotator or netstandard 2.0 support. The former just needs fixed so that it doesn't break when targeting multiple framework versions.

**Comment by christophwille** [comment]
@ds5678 please open a new issue if ever the ReferenceAssemblyAnnotator bug gets fixed and we can thus support trimming.
