### ISSUE TITLE
C# decompiled source for [ComImport] fails to retain vtbl ordering

### ISSUE THREAD

**Issue by smaillet** [icsharpcode/ILSpy#2688]
ILSPY is sorting and re-ordering methods/properties of an interface marked with the [ComImport] attribute. This is broken as that attribute is used for COM interface with strict ABI vtbl slot ordering. AFAIK there is no setting to control this (and for ComImport any setting for ordering should be ingored anyway to ensure proper slot ordering)

### Details
ILSpy version 7.2.1.6856
.NET version 4.8.9032.0
Package Name: 17310ICSharpCodeTeam.ILSpy_7.2.6856.0_neutral__jpqg2ewkdrg54

**Comment by siegfriedpammer** [comment]
Should already be fixed in recent builds of ILSpy 8.0 by #2639
