### ISSUE TITLE
This e doesn't know which object is referenced

### ISSUE THREAD

**Issue by zgfflc** [icsharpcode/ILSpy#2694]
Hi ,The decompiled code is correct, but there will be conflict problems when compiling.
		public void ComBox_OnClick(object sender, EventArgs e)
		{
			try
			{
				//......................................A lot of code is omitted here

				user_Dialog.SetListView_CheckBox(Strs, delegate(object sender, AdapterView.ItemClickEventArgs e)
				{
					try
					{
                                                  //The problem arises here. This e doesn't know which object is referenced
						Combox_EditText.Text = Strs[e.Position].ToString();
					}
					catch
					{
					}
				});
				user_Dialog.Show();
			}
			catch
			{
			}
		}

**Comment by dgrunwald** [comment]
Note that C# 8 started allowing shadowing of lambda parameters.
So if we start renaming parameters to avoid this issue, we should restrict that to C# <= 7.3.
