### ISSUE TITLE
IL with C# shows no C#

### ISSUE THREAD

**Issue by trivalik** [icsharpcode/ILSpy#2701]
### Steps to reproduce
1. get [PcapDotNet.Binaries.1.0.4.zip](https://github.com/PcapDotNet/Pcap.Net/releases/download/v1.0.4/PcapDotNet.Binaries.1.0.4.zip) of https://github.com/PcapDotNet/Pcap.Net/releases/tag/v1.0.4
2. open PcapDotNet.Core.Extensions.dll
3. navigate to function PcapDotNet.Core.Extensions.PacketCommunicatorExtensions.ReceivePackets(this PacketCommunicator communicator, **int count**)
4. of course have select "IL to C# option"

### Details
* tested with 7.2.1.6856 and 8.0.0.7007-preview1

**Comment by siegfriedpammer** [comment]
The method in question is implemented as a yield return state machine... the state machine initialization code does not really correspond to any C# code that is visible in the C# view.

What is the output that you would expect?
