### ISSUE TITLE
Wrong decompilation of using statement

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2710]
### Input code
Decompilation by dnSpy (see the { } usage in using statements

![image](https://user-images.githubusercontent.com/765343/173226146-ab9b7761-7734-4e60-a2ad-2e3d51d1f147.png)

### Erroneous output
![image](https://user-images.githubusercontent.com/765343/173226088-08595197-c272-4a2a-b2c9-f463f67a3aad.png)

2nd using statement is erroneous

as from VS2019:

![image](https://user-images.githubusercontent.com/765343/173226647-5d797e90-7d1f-45b7-95ec-af2b21a35d60.png)

### Details
* ILSpy version 8.0.0.7046-preview1
.NET version 6.0.3-servicing.22123.9+c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
[err121.zip](https://github.com/icsharpcode/ILSpy/files/8885547/err121.zip)

**Comment by dgrunwald** [comment]
It's a C# 8 using declaration.
The problem is that the outer using statement doesn't have any braces -- ILSpy omits braces for nested using statements; but it shouldn't omit them for a using declaration nested within a using statement.
