### ISSUE TITLE
Ctor decompilation issue

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2714]
### Input code
Please see one ctor under analysis

### Erroneous output
Getting this code on some ctor from time to time, eg:
![image](https://user-images.githubusercontent.com/765343/173762837-08301977-8482-4e9e-ad16-8a7ddd50cdf6.png)

### Details
* ILSpy version 8.0.0.7053-preview1
.NET version 6.0.3-servicing.22123.9+c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663
[webs.zip](https://github.com/icsharpcode/ILSpy/files/8906607/webs.zip)

**Comment by siegfriedpammer** [comment]
This is an inlining issue... I am surprised that we don't yet handle this case correctly. Apparently `ILInlining` doesn't like casts as struct call-targets.

Original source code: https://github.com/sta/websocket-sharp/blob/ed7e0498266d26c297f0d706bdcc6d379929b745/websocket-sharp/HttpResponse.cs#L71-L80
