### ISSUE TITLE
Bug: "Implicit nullable conversions" don't work so well

### ISSUE THREAD

**Issue by OmerRaviv** [icsharpcode/ILSpy#272]
Decompiling the C# code with ILSpy  2.0.0.1391:

``` C#
    int? nully = 3;
    float? nullyFloat = 5;
    nullyFloat = nully;
```

Yields the following decompiled code:

``` C#
    int? nully = new int?(3);
    float? nullyFloat = new float?(5f);
    int? num = nully;
    nullyFloat = (num.HasValue ? new float?((float)num.GetValueOrDefault()) : null);
```

I think this could possibly be simplified - see CSharp 4 Language Spec "1.40.4 Implicit nullable conversions"

**Comment by dgrunwald** [comment]
Output of ILSpy 3.0-preview2:
```
	int? nully = new int?(3);
	float? nullyFloat = new float?(5f);
	nullyFloat = (float?)nully;
```

There's still a problem with redundant casts, but the core problem with lifted conversion operators is fixed.
