### ISSUE TITLE
CodeQL Action bump

### ISSUE THREAD

**Issue by clin1234** [icsharpcode/ILSpy#2724]
**Is your feature request related to a problem? Please describe.**
v1 of the CodeQL Action will be deprecated in December 2022

**Describe the solution you'd like**
Bump CodeQL Action to v2 in codeql-analysis.yml

**Comment by christophwille** [comment]
Deprecation information from a current run (for documentation): https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

**Comment by christophwille** [comment]
Thank you for bringing this to our attention!
