### ISSUE TITLE
Can't browse assembly types

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#2733]
### Steps to reproduce
1. Try to browse assembly types

### Error message shown

![image](https://user-images.githubusercontent.com/765343/177037578-1acb6b68-633a-4575-9841-5c44e03379a2.png)

dnSpy opens up this assembly as no error at all
one could easily browse types tree, etc

### Details
* ILSpy version 8.0.0.7061-preview1
* .NET version 6.0.6-servicing.22267.7+7cca709db2944a09b4db6ca7b20c457ff260fb5a

Idea:  paint somehow those tables which have potentioal issues, eg:

![image](https://user-images.githubusercontent.com/765343/177037642-01b1ce0c-14ff-4fd1-9cef-d9e2fb7d3a99.png)
[err123.zip](https://github.com/icsharpcode/ILSpy/files/9034641/err123.zip)

**Comment by siegfriedpammer** [comment]
The crash doesn't occur when looking at the metadata tables, but right when we try to construct the type system for decompilation. The metadata tables view displays the broken ResolutionScope reference just fine.
