### ISSUE TITLE
Write Tests for ref fields in ref structs feature

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2748]
For https://github.com/icsharpcode/ILSpy/commit/5f324de10bcc9f9ad3144b4030a1a0a27615a8dc and https://github.com/icsharpcode/ILSpy/commit/2ed9ad6b51110acfa5430a50f34b985c9c4eb1ac

We manually tested during the #2722 dev meeting because only 4.3.0-2.final of Microsoft.Net.Compilers.Toolset was available at that time - that didn't yet support the feature. (we used VS Preview 3 17.3 to generate test assemblies). 

To do: turn the manual sample into unit tests.

**Comment by dgrunwald** [comment]
PR #2992
