### ISSUE TITLE
Search panel always show `Assembly` Icon

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2751]
![image](https://user-images.githubusercontent.com/2529999/179372561-2cef0e61-33ba-4d0a-b9a5-0a874358dcc9.png)

**Comment by zshameel** [comment]
Please include build info, language and steps to reproduce.

**Comment by CreateAndInject** [comment]
[latest CI build (master)]

**Comment by zshameel** [comment]
I could not reproduce the issue. I'm using English. Is this specific to Chinese?
