### ISSUE TITLE
Nullable Attributes No Longer Decompiling Right

### ISSUE THREAD

**Issue by ds5678** [icsharpcode/ILSpy#2753]
### Input code

```c#
using System.Diagnostics.CodeAnalysis;

namespace Project.Extensions
{
	internal static class ArrayExtensions
	{
		public static bool IsNullOrEmpty<T>([NotNullWhen(false)] this T[]? array) => array is null || array.Length == 0;
	}
}
```

### Erroneous output
```c#
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Project.Extensions
{
	internal static class ArrayExtensions
	{
		[System.Runtime.CompilerServices.NullableContext(2)]
		public static bool IsNullOrEmpty<T>([System.Runtime.CompilerServices.Nullable(new byte[] { 2, 1 })][NotNullWhen(false)] this T[] array)
		{
			return array == null || array.Length == 0;
		}
	}
}
```
#### If the output fails to re-compile, provide the compiler error message.
```
CS0234	The type or namespace name 'NullableContextAttribute' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)
CS0234	The type or namespace name 'NullableContext' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)
CS0234	The type or namespace name 'NullableAttribute' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)
CS0234	The type or namespace name 'Nullable' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)
```
#### If the output has the wrong behavior, explain how it differs from the expected behavior.

Previously, it would hide those attributes and generate the correct nullable annotations inside the code.

### Details
* Product in use: ILSpy
* Version in use: 06039f24efec4682b7979e33b1bd42b12628079c, but I was also able to reproduce on 7.2.1 and 8.0 Preview 1. It decompiled correctly on these versions in the past.
* As far as I can tell, this started on the day Microsoft released a new version of [.NET 6](https://devblogs.microsoft.com/dotnet/july-2022-updates/) and [Visual Studio](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview).

**Comment by christophwille** [comment]
Mind to tell us why you no longer consider this to be a problem?

**Comment by ds5678** [comment]
> Mind to tell us why you no longer consider this to be a problem? 

User error. It was on a lower C# version, and I didn't notice.

**Comment by christophwille** [comment]
Thanks for providing the feedback.
