### ISSUE TITLE
Improve enum

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2763]
Original : 
```csharp
public static void Test(int value)
{
    var color = (KnownColor)value;
    switch (color)
    {
        case KnownColor.DarkBlue:
            Console.WriteLine();
            break;
        case KnownColor.DarkCyan:
            Console.WriteLine();
            break;
        case KnownColor.DarkGoldenrod:
            Console.WriteLine();
            break;
        case KnownColor.DarkGray:
            Console.WriteLine();
            break;
        case KnownColor.DarkGreen:
            Console.WriteLine();
            break;
        case KnownColor.DarkKhaki:
            Console.WriteLine();
            break;
    }
}
```

ILSpy : 
```csharp
public static void Test(int value)
{
	switch (value)
	{
	case 49:
		Console.WriteLine();
		break;
	case 50:
		Console.WriteLine();
		break;
	case 51:
		Console.WriteLine();
		break;
	case 52:
		Console.WriteLine();
		break;
	case 53:
		Console.WriteLine();
		break;
	case 54:
		Console.WriteLine();
		break;
	}
}
```

**Comment by mpMelnikov** [comment]
Hi @siegfriedpammer,

I have investigated the issue. The replacement of enum with int happens somewhere inside StatementTransform. I can catch the moment when this replacement happens. In this stack trace, there is such a comment: "
			// TODO: inlining of small integer types might be semantically incorrect,
			// but we can't avoid it this easily without breaking lots of tests.
Can it be related? Does it make sense to try to fix it or does it look like a potentially major change?

**Comment by mpMelnikov** [comment]
@dgrunwald 
I have created a [pull request](https://github.com/icsharpcode/ILSpy/pull/2785). It is my first attempt to contribute to ILSpy, so I understand that the solution can be totally incorrect. At least it gives some insight where the issue is, and I hope it can be a starting point.

Also, I found another bug.
This method
```csharp
    public static void EnumReplacedWithIntIncorrectly_AndIncorrectConditionGenerated_AndUnusedVariables(int intValue)
    {
        var color = (KnownColor)intValue;
        var color2 = (KnownColor)intValue;
        var color3 = (KnownColor)intValue;
        if (color == KnownColor.DarkBlue)
        {

        }

        if (color2 == KnownColor.DarkBlue)
        {

        }
    }
```
is generated like this:
```csharp
	public static void EnumReplacedWithIntIncorrectly_AndIncorrectConditionGenerated_AndUnusedVariables(int intValue)
	{
		KnownColor color = (KnownColor)intValue;
		KnownColor color2 = (KnownColor)intValue;
		if (color == KnownColor.DarkBlue)
		{
		}
		if (color2 != KnownColor.DarkBlue)// '!=' instead of '==' here
		{
		}
	}
```

Do you remember if it was already registered?

One more question. I tried to use as pre-commit script as required, but I constantly get an error even though no spaces were introduced (only tabs). Is pre-commit script supported and working correctly now?

**Comment by siegfriedpammer** [comment]
> // '!=' instead of '==' here

Empty blocks cannot be distinguished, so the code is effectively semantically equivalent, and the conditions entirely depend on the generated IL code.

If you add statements to the bodies, the code is decompiled exactly as expected:

https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAIFMYBXMAAgGkYB7AdxgGFaAbWgJwoG8KARCBwDWAIVakicfoKEBxDkRJSAmkVbt6UgEpEEU+YvgUxEigF8CBdAGYKWCkx4EKLu7fTYAbHYAsFAKJkYDoADqwQAMa6AOpQAC4AFgCSMHEpEZwKEXGsAJ4A+gCCMAjpmUTZLCXxULQwsiREHBBxukUlAKpkAM66AGqCUBDArETdABSwcRRTA+JEAJTOrtzLrq4AboIUGexcALwU4zQMzGycC7MQ8wDca+sUW1y7nJgUh8d0jCx7l6lzEju+Aem22Lw4tg+J2+5w4fziAKIQJBLigADMjuD3odoWc9gA6ATCEyLe7rVbAlHrDwATnGACIiaJ5vSFsiURZCJSQejMbC3vscV88ZxCTISUtuQ8KVTqdg6YzxSy2ZYpetOeqCGYgA=
