### ISSUE TITLE
`new DecompilerTypeSystem(...)` is very slow sometimes

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2772]
```
public DecompilerTypeSystem(PEFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions)
{
	if (mainModule == null)
		throw new ArgumentNullException(nameof(mainModule));
	if (assemblyResolver == null)
		throw new ArgumentNullException(nameof(assemblyResolver));
	InitializeAsync(mainModule, assemblyResolver, typeSystemOptions).GetAwaiter().GetResult();
}
```

I added a context menu command, when I call `new DecompilerTypeSystem(...)`, ILSpy may hang in `InitializeAsync(mainModule, assemblyResolver, typeSystemOptions).GetAwaiter().GetResult();` a long time (more than 10 seconds, but not every time)

**Comment by siegfriedpammer** [comment]
Depending on your `IAssemblyResolver` implementation resolving references may involve a lot of disk IO at least the default implementation `UniversalAssemblyResolver` performs a lot of filesystem accesses, which may take a long time. I don't think this is a bug, but rather something that could be improved.

In ILSpy (see Please also see https://github.com/icsharpcode/ILSpy/issues/2594#issuecomment-1030705028) we have added `AssemblyListSnapshot` which allows us to cache successful assembly searches, however, we still have no caching for assemblies that cannot be resolved at all.

**Comment by CreateAndInject** [comment]
But for the same assembly, why sometimes more than 10 seconds, sometimes immediately?

**Comment by christophwille** [comment]
Would you have a way to attach a profiler on your machine (where you seemingly sometimes can repro this)?

**Comment by CreateAndInject** [comment]
I can't repo now, I'll check if it's because of my `IAssemblyResolver` when it happen next.

**Comment by christophwille** [comment]
Can we close this?

**Comment by CreateAndInject** [comment]
OK, close it.
