### ISSUE TITLE
Readonly property in xaml

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2773]
`<ObjectDataProvider x:Key="DBEnumKey" MethodName="GetValues" ObjectType="{x:Type core:Enum}" MethodParameters="{x:Type TypeName=local:DBEnum}" />`

`MethodParameters` is readonly, and cannot be assigned

**Comment by siegfriedpammer** [comment]
Do you have a suggestion what code we could emit in such a case?

**Comment by CreateAndInject** [comment]
@siegfriedpammer 
```
            <ObjectDataProvider x:Key="DBEnumKey" MethodName="GetValues" ObjectType="{x:Type core:Enum}">
                <ObjectDataProvider.MethodParameters>
                    <x:Type TypeName="local:DBEnum"></x:Type>
                </ObjectDataProvider.MethodParameters>
            </ObjectDataProvider>
```
