### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by modz2014** [icsharpcode/ILSpy#2782]
### Steps to reproduce
1. The context menu isnt working at all in the latest version
2. 
3. 

### Error message shown

```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* Version in use: e.g. 6.0.0 or a commit hash (use Help>About to see which ILSpy version you are using)
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by siegfriedpammer** [comment]
Works on my machine... can you post an example for me to try to reproduce? Thanks!

**Comment by modz2014** [comment]
Is there a menu to select it because I looked everywhere for it

**Comment by siegfriedpammer** [comment]
What's "it"?

**Comment by modz2014** [comment]
to add it to content menu how to add it there there was a option to do on the older version

**Comment by dgrunwald** [comment]
We don't understand what you're referring to.
Please try to describe fully: what are you clicking on, what are you seeing + what were you expecting instead.

If you are missing a specific menu command that existed in an earlier version: what exactly was the name of that command?

**Comment by siegfriedpammer** [comment]
If you are referring to the "Open in ILSpy" shell extension, you may have to remove it and add it again using the button in the ILSpy options:

![image](https://user-images.githubusercontent.com/344208/151211981-288f5bd2-48a1-4bbd-901d-28b48786de84.png)

yes, click the button once to remove and once more to add it again. This will refresh the used command-line and will probably fix your problem.

If this does not help, please write down step by step what you are doing, if possible add images and describe what you are expecting and what's not working for you. Thanks!

**Comment by modz2014** [comment]
ok i fixed seem it there was a bug on my end for some reason ill close this now thank you for your time also can you put to the code in ILSpy where it says the add shell integration please

**Comment by siegfriedpammer** [comment]
>  can you put to the code in ILSpy where it says the add shell integration please

The code is already there... I don't understand what you are referring to.

**Comment by modz2014** [comment]
where is the code does it say about the context
