### ISSUE TITLE
Preview .NET runtimes do not appear in the "Add preconfigured list…" button

### ISSUE THREAD

**Issue by teo-tsirpanis** [icsharpcode/ILSpy#2783]
### Steps to reproduce
1. Install .NET 7.
2. View the preconfigured assembly lists.

### Error message shown

![image](https://user-images.githubusercontent.com/12659251/190261712-269766b4-a3bd-4c08-aa3d-21e5cbcfc273.png)

.NET Core 3.1 and .NET 6 are there, but nowhere is 7. The same happened when .NET 6 was in preview.

### Details
* Product in use: ILSpy
* Version in use: 7.2.1.6856

**Comment by siegfriedpammer** [comment]
I excluded the preview runtimes from that list on purpose, as I am not sure, how "deduplication" should happen with previews... For released versions I always take the latest version of each major.minor version pair. If I did the same for previews, would that be enough? e.g. if you have net7 p3 and p4 installed, only p4 will show up in that list? Let me know what you think...

**Comment by teo-tsirpanis** [comment]
Yeah, that's enough, thanks. People don't usually have many preview versions installed.
