### ISSUE TITLE
Display Linker Timestamp for Assembly

### ISSUE THREAD

**Issue by WolfgangHG** [icsharpcode/ILSpy#2793]
To explain my requirement: I just had an issue that a change of mine was not contained in the DLL that a colleague had published (though the publishing process should ensure that the latest code version is pulled from source control). So I don't know whether the DLL was not compiled because of an unknown reason or whether he did not pull the correct code. Unfortunately I could not check the modification date, because during publish, the DLL is signed and thus the last write time is not the compilation timestamp.

I could verify that the old code was compiled by checking the decompiled code in ILSpy.

But it would have helped me if the Linker Timestamp header was displayed in ILSpy.

See e.g. here: [https://blog.codinghorror.com/determining-build-date-the-hard-way/](https://blog.codinghorror.com/determining-build-date-the-hard-way/).

Here is a C# version of the code from the link (assembly location is in variable "filePath")

```
      const int c_PeHeaderOffset = 60;
      const int c_LinkerTimestampOffset = 8;
      byte[] b = new byte[2048];
      System.IO.Stream s = null;

      try
      {
        s = new System.IO.FileStream(filePath, System.IO.FileMode.Open, System.IO.FileAccess.Read);
        s.Read(b, 0, 2048);
      }
      finally
      {
        if (s != null)
        {
          s.Close();
        }
      }

      int i = System.BitConverter.ToInt32(b, c_PeHeaderOffset);
      int secondsSince1970 = System.BitConverter.ToInt32(b, i + c_LinkerTimestampOffset);
      DateTime dt = new DateTime(1970, 1, 1, 0, 0, 0);
      dt = dt.AddSeconds(secondsSince1970);
      //in .NETCore "TimeZone" is obsolete.
      //dt = dt.AddHours(TimeZone.CurrentTimeZone.GetUtcOffset(dt).Hours);
      dt = dt.AddHours(TimeZoneInfo.Local.GetUtcOffset(dt).Hours);
      return dt;
```

Note that the Linker Timestamp is only valid if deterministic build is disabled in the project settings:

`    <Deterministic>False</Deterministic>`

**Comment by siegfriedpammer** [comment]
This should be the information you are looking for:

![image](https://user-images.githubusercontent.com/344204/193425433-622f1cf1-6832-47dc-ac14-7f7da217cd83.png)

**Comment by siegfriedpammer** [comment]
I have added more info to that field in fc1e9eb5bcfd9e36e2a3d3270883a00480c36eb2.

**Comment by WolfgangHG** [comment]
Thanks! Sorry, I would have never searched this information at this place ;-). Closing this issue.
