### ISSUE TITLE
Proposal: Better progress reporting and cancellation for PortablePdbWriter

### ISSUE THREAD

**Issue by andrewcrawley** [icsharpcode/ILSpy#2801]
I'm continuing to work on improving the integration between the decompiler and the Visual Studio debugger.  We've found that a surprisingly high number of customers who try the decompiler end up attempting to cancel the decompilation operation, and our current hypothesis is that the lack of progress feedback leads them to think that the operation is "hung", or otherwise unresponsive.  Since the decompiler doesn't really support cancellation, this leads to an undesirable situation where the user attempts to cancel the operation in VS, and we're forced to wait for it to complete (probably successfully!) before discarding the results and informing the user that the "cancellation" succeeded.

To improve things, I'm looking at implementing better support for cancellation and progress reporting in `PortablePdbWriter`, the entry point used by the VS debugger.

I've prototyped the following API, which I believe addresses both of the pain points I mentioned above - better progress reporting so users hopefully won't cancel as often, and better cancellation so they won't have to wait as long when they do cancel.

```C#
public static void WritePdb(
    PEFile file,
    CSharpDecompiler decompiler,
    DecompilerSettings settings,
    Stream targetStream,
    bool noLogo = false,
    BlobContentId? pdbId = null,
    CancellationToken cancellationToken = default(CancellationToken), // New!
    IProgress<WritePortablePdbProgress> progress = null)              // New!

public struct WritePortablePdbProgress
{
    int TotalTypes { get; }
    int TypesWritten { get; }
}
```

The implementation merely updates the loop over types in `WritePdb` to check the CancellationToken and send a progress update per iteration.

If you're satisfied with this design, I'd be happy to clean up my prototype and send a PR.  We're hoping to be able to get this into the 8.0 release.

**Comment by dgrunwald** [comment]
Cancellation is already supported via the `CSharpDecompiler.CancellationToken` property.
Adding support for `IProgress` makes sense.

**Comment by siegfriedpammer** [comment]
For now, I will only add this to WholeProjectDecompiler / PortablePdbWriter on a per-file basis...

**Comment by andrewcrawley** [comment]
@dgrunwald - Thanks for the info on cancellation, I just submitted changes to the debugger to get that hooked up.

I'll follow up with a PR for the progress reporting, thanks!
