### ISSUE TITLE
ITypeDefinition returning false for IsRecord on record struct

### ISSUE THREAD

**Issue by daningalla** [icsharpcode/ILSpy#2803]
tl;dr: Should `ITypeDefinition.IsRecord` return `true` for record struct?

### Steps to reproduce
Decompile any assembly with `record struct`
Get type definition from type system

### Error message shown
No error, but the unexpected behavior is the resulting `ITypeDefinition` returns `false`  for `IsRecord`. Is this only true for reference type records?

### Details
ICSharpCode.Decompiler, version=8.0.0.7106-preview2

**Comment by siegfriedpammer** [comment]
Would you be able to provide some more information on how you create your type system? Also, an example of a record struct that is not decompiled properly, would be appreciated. As you can see, we have lots of record structs test cases already working: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler.Tests/TestCases/Pretty/Records.cs#L132

Thank you!

**Comment by daningalla** [comment]
Sorry for wasting your time, I was using an older version of the library in my unit test project. Thank you for the prompt response, this library is fantastic.
