### ISSUE TITLE
Permit source generation for the `<Module>` from the project decompile

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [icsharpcode/ILSpy#2807]
**Is your feature request related to a problem? Please describe.**

I am looking at generating C# from a C++/CLI binary compiled with `/clr:pure`. A lot of code is pinned on `<Module>` and not emitting this is annoying because now I must go to each node in the module. Would it be possible to permit this? I can submit a PR if this seems helpful.

**Describe the solution you'd like**
I've removed the `"<Module>"` check in the below path and it works as expected.

https://github.com/icsharpcode/ILSpy/blob/6e70db7dd3f02aa230be8d6c938b2f76005a14eb/ICSharpCode.Decompiler/CSharp/ProjectDecompiler/WholeProjectDecompiler.cs#L172-L173

**Comment by dgrunwald** [comment]
We don't want to output `<Module>` when decompiling a C# assembly; so you'd somehow need to detect C++/CLI.

**Comment by AaronRobinsonMSFT** [comment]
@dgrunwald Thoughts on making it an opt-in setting?

**Comment by AaronRobinsonMSFT** [comment]
Perhaps adding a new checkbox under **Other**, off by default, to emit `<Module>`?

![image](https://user-images.githubusercontent.com/30635565/197062005-7653cf79-564d-4fcd-844b-bc8d1ff97f71.png)

**Comment by siegfriedpammer** [comment]
> We don't want to output `<Module>` when decompiling a C# assembly; so you'd somehow need to detect C++/CLI.

Couldn't we detect whether code from <Module> is referenced elsewhere and include it in those cases?

**Comment by AaronRobinsonMSFT** [comment]
> Couldn't we detect whether code from <Module> is referenced elsewhere and include it in those cases?

That would also solve it. I've figured out how to add a new option and plumb that through I can submit a PR for that approach. Detecting a reference is beyond my level of understanding in this system so I'd need some pointers if that is the preferred option.

**Comment by AaronRobinsonMSFT** [comment]
I've submitted a possible solution for this issue - https://github.com/icsharpcode/ILSpy/pull/2815.

**Comment by siegfriedpammer** [comment]
I have implemented my proposed solution, i.e., automatic detection of missing types... https://github.com/icsharpcode/ILSpy/tree/fix/2807

What do you think? @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
> What do you think? @AaronRobinsonMSFT

Works as advertised. Thanks! This meets my needs for sure. I will close my PR.
