### ISSUE TITLE
Cast to interface from 'dynamic'

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#2808]
This is more of a heads-up on something I just encountered.

While the resulting decompiled code is syntactically valid, it produces massively different code than the original.

Consider a method returning a C# interface reference by `dynamic`, like
```
 dynamic GetIFace();
```
The use of this could decompile into e.g.
```
  IFace r = (IFace)GetIFace();
```
At first glance that looks fine, right?

What you might not realize is that the compiler has generated a _ton_ of code for that cast, and introduced a reference to Microsoft.CSharp that you now have to add to the project.

The solution might not be obvious, but ILSpy should be made aware of this:
```
  IFace r = (IFace)(object)GetIFace();
```

With that seemingly redundant cast to `object` the code once again works as expected.

Just thought it could be good to share this, since I myself got bitten by it.

**Comment by siegfriedpammer** [comment]
Test code here: https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAPQGYACWAFwFMAnAMwgGMrSBJUgbwF8CiytSAYU4FSY0ggCeMCGCiNSAcSoVWACgCUpALwA+UjACuAG2MBuUeMtiSbUgBUqAZwqbrI/OK+l0AdiUq6hoWnuI8oWLutuyOLthuER7e4n6kaqwayqqaIV7hXlFkMc4UmAleHO5eqekaagD2wABWVIwUmYE57uFcQA==
