### ISSUE TITLE
Unity Asset Metadata Export

### ISSUE THREAD

**Issue by UserIdklol** [icsharpcode/ILSpy#2814]
Please add meta-export

**Comment by dgrunwald** [comment]
I don't know what that's supposed to be. Can you explain?

**Comment by UserIdklol** [comment]
> I don't know what that's supposed to be. Can you explain?
generating meta files for the unity project

**Comment by UserIdklol** [comment]
> I don't know what that's supposed to be. Can you explain?

https://docs.unity3d.com/Manual/AssetMetadata.html

**Comment by christophwille** [comment]
Isn't that what https://github.com/Perfare/AssetStudio does?

**Comment by UserIdklol** [comment]
> Isn't that what https://github.com/Perfare/AssetStudio does?

no

**Comment by christophwille** [comment]
Given that we have no experience in this area it is unlikely that we will add this feature (contributions welcome).

**Comment by christophwille** [comment]
Closing as not planned.
