### ISSUE TITLE
Can't search for constants, starting by @

### ISSUE THREAD

**Issue by AfshinZavvar** [icsharpcode/ILSpy#2827]
### Steps to reproduce
1. Change search type to be constant 
2. Search for @
3. Crashes

### Error message shown
![image](https://user-images.githubusercontent.com/21095394/199656825-0142b99f-5cfa-4405-a2c4-82ed4d5424ff.png)

```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* Version in use: e.g. 6.0.0 or a commit hash (use Help>About to see which ILSpy version you are using)
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by siegfriedpammer** [comment]
Which version of ILSpy are you currently using? Have you tried the latest version? This doesn't crash for me using the latest development build.

In the latest version it does not find anything, but this can be worked around by using `c:@`. Then "@" is no longer interpreted as prefix by our "query language" parser.
