### ISSUE TITLE
Enhance ReflectionDisassembler to support filtering/sorting

### ISSUE THREAD

**Issue by tom-englert** [icsharpcode/ILSpy#2834]
**Is your feature request related to a problem? Please describe.**
When using IL disassembling to verify the outcome of some IL modification, it frequently happens that tests break just because the IL layout has slightly changed, but only by the ordering of classes or members, while the IL is still the same.
Another use case is to validate IL changes by before/after comparison, which is impossible when not only a few IL statements, but the complete layout has changed.

**Describe the solution you'd like**
ReflectionDisassembler should support an extension point to enable sorting or filtering. By sorting classes or members, the generated IL would be identical if only the ordering of members has changed.
Filtering could be helpful to reduce the output just to the points of interest.

**Additional context**
See implementation and tests in #2835

**Comment by siegfriedpammer** [comment]
Fixed by https://github.com/icsharpcode/ILSpy/pull/2835
