### ISSUE TITLE
Parse variable names from debug info using ILReader

### ISSUE THREAD

**Issue by PascalHonegger** [icsharpcode/ILSpy#2865]
**Is your feature request related to a problem? Please describe.**
I want to read variables from IL and extract their original variable name from the debug information, if they're available.
Using the ILSpy executable, I can see that my DLL contains all the required debug metadata, as the decompiled code contains the original names.

I've looked at the ILSpy source and found utilities for getting the debug info, but I'm bound to supporting .NET 4.6.2 and seemingly cannot use the ILSpyX namespace.

**Describe the solution you'd like**
```csharp
var ilReader = new ICSharpCode.Decompiler.IL.ILReader(module) {
	UseDebugSymbols = true,
	DebugInfo = /* I need this */
};
```

**Additional context**

**Comment by siegfriedpammer** [comment]
If you cannot use the latest version of ILSpy, then the only solution is to simply copy the relevant parts of these files from the last 7.x release: https://github.com/icsharpcode/ILSpy/tree/v7.2.1/ILSpy/DebugInfo

If you need anything else, do not hesitate to ask.

**Comment by mjossdev** [comment]
Out of curiosity, why are these classes not in the NuGet package?

**Comment by dgrunwald** [comment]
DebugInfoUtils uses additional dependencies (Mono.Cecil) that we don't want to add as required dependencies to the NuGet package.
But I'm not sure about PortableDebugInfoProvider, maybe we could move that.

**Comment by christophwille** [comment]
Yes, but how much use will it be without DebugInfoUtils? Eg https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.ILSpyX/PdbProvider/DebugInfoUtils.cs#L64
