### ISSUE TITLE
It says I need to install .NET, despite the fact that I did.

### ISSUE THREAD

**Issue by SpookLad** [icsharpcode/ILSpy#2870]
### Steps to reproduce
1. Download and install ILSpy 8.0.0.7246 preview 3
2. Download and install .NET 6.0.12
3. Attempt to open ILSpy

### Error message shown
```
To run this application, you must install missing frameworks for .NET.

Would you like to download it now?
```

(Clicking yes brings you to the download for .NET 6.0.12)
```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```
![pain_ilirl](https://user-images.githubusercontent.com/83087893/208358060-be5b7f99-8c02-4b1a-9145-e9a60ee03898.png)

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* Version in use: e.g. 6.0.0 or a commit hash (use Help>About to see which ILSpy version you are using)
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by christophwille** [comment]
When you execute `dotnet --list-runtimes` on the command prompt, what gets listed? (btw, which Windows version are you on?)

**Comment by SpookLad** [comment]
The reason the version listed above isn't listed there is because I uninstalled it and tried to install the latest version instead.

**Comment by christophwille** [comment]
ILSpy will run only with .NET 6.0, 7.0 won't do anything for you.

**Comment by SpookLad** [comment]
Do I specifically need 6.0? 6.0.12 doesn't work.

**Comment by christophwille** [comment]
No, latest works fine (the runtime is updated by Windows Update anyways). Also, please try the self-contained download (although the framework-dependent download should absolutely work with .NET 6.0 installed).

**Comment by greenozon** [comment]
Works like a charm on old good and supercool Win7!
![image](https://user-images.githubusercontent.com/765343/208621837-35423f0d-6f1d-409b-82ec-8d9cfb682459.png)

**Comment by christophwille** [comment]
@SpookLad got any updates for us?
