### ISSUE TITLE
To run this application, you must install missing frameworks

### ISSUE THREAD

**Issue by architelos** [icsharpcode/ILSpy#2880]
### Steps to reproduce
1.  Install ILSpy on a fresh install of Windows
2.  Open ILSpy
3.  Follow the link shown in the original error message, install the provided runtime
4.  Reopen ILSpy

### Error message shown
"To run this application, you must install missing frameworks for .NET"

![image](https://user-images.githubusercontent.com/108888162/210794272-e6694135-cd69-40e1-bcb9-140dfc26cb5d.png)

### Details
* Product in use: e.g. ILSpy executable
* Version in use: Newest release

**Comment by architelos** [comment]
`dotnet --info` output:

```
global.json file:
  Not found

Host:
  Version:      6.0.12
  Architecture: x64
  Commit:       02e45a41b7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

Tried reinstalling both the provided runtime and ILSpy, enabling all .NET framework related settings in Control Panel, and restarting

**Comment by christophwille** [comment]
![image](https://user-images.githubusercontent.com/344208/210795892-647feac7-e87b-4128-8ce1-556f15c183c5.png)

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Which of those did you install? To me this looks like the latter from the screenshot "**The .NET Runtime contains just the components needed to run a console app**. Typically, you'd also install either the ASP.NET Core Runtime or .NET Desktop Runtime."

**Comment by architelos** [comment]
Ahhh! I installed the one which popped up after clicking "Yes" on the dialog box shown, I'll try downloading the Desktop Runtime and report back!

**Comment by riQQ** [comment]
So the .NET dialog still doesn't forward to the correct download link for desktop apps :(

**Comment by architelos** [comment]
Thank you! ILSpy is working now!
