### ISSUE TITLE
Anthor Decompiler bug

### ISSUE THREAD

**Issue by admintony** [icsharpcode/ILSpy#2881]
In the latest version of the code, you can see the variable and function name when decompiling, but the specific content of the function is shown as the following error

```
		//Discarded unreachable code: IL_0006, IL_03a4
		//IL_0006: Unknown result type (might be due to invalid IL or missing references)
		//IL_0456: Incompatible stack heights: 0 vs 1
		/*Error near IL_0001: Metadata token must be either a methoddef, memberref or methodspec*/;
```

**Comment by dgrunwald** [comment]
What are you trying to decompile?
These errors usually indicate you are trying to decompile invalid code that .NET would refuse to load. Obfuscators sometimes put such code in places where the .NET runtime would never load it (e.g. unused methods or skipped-over control flow blocks).

**Comment by christophwille** [comment]
No further information provided, closing.
