### ISSUE TITLE
[Feature Request]: .NET 6 Target with Trimming

### ISSUE THREAD

**Issue by ds5678** [icsharpcode/ILSpy#2882]
## Context

> This is a repost of #2673.

A .NET 6 target for the decompiler project with [trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming) would allow this to be used in trimmed or NativeAOT-compiled applications. This allows for applications to be smaller, faster, and more independent of user software installations.

## Issues to be handled

* A bunch of `Linq` polyfills need excluded on .NET 6 with preprocessor directives.
* `ResXResourceWriter.cs` uses `TypeDescriptor.GetConverter` and [`BinaryFormatter.Serialize`](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete).
* `UniversalAssemblyResolver.cs` calls `Type.GetType("Mono.Runtime")` which I think can be safely excluded with a preprocessor directive on .NET 6.
* https://github.com/icsharpcode/ILSpy/commit/6a6e82c3722d7adde7b7f93da25455b8e792000f added [ReferenceAssemblyAnnotator](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator) which breaks when targeting multiple frameworks https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/issues/92

## Nullable Attributes

The [issue](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/issues/92) mentioned in the last bullet point still hasn't been resolved. However, I have some alternatives:

* [Nullable](https://github.com/manuelroemer/Nullable) is a polyfill for nullable attributes.
* [PolySharp](https://github.com/Sergio0694/PolySharp) is a polyfill for many classes, including nullable attributes. This would allow ILSpy to use [additional C# language features](https://github.com/Sergio0694/PolySharp#documentation-) in its codebase.

Both of these are more actively maintained, and neither of them exhibit the [issue](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/issues/92) that prevents multi-targeting.

On a more practical note, PolySharp has support for `MemberNotNullAttribute` and `MemberNotNullWhenAttribute`, which [ReferenceAssemblyAnnotator does not](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/issues/84).

**Comment by ds5678** [comment]
> MEF

Is this referring to the [Managed Extensibility Framework](https://learn.microsoft.com/en-us/dotnet/framework/mef/)?

**Comment by ds5678** [comment]
> MEF and NativeAot? Don't know if that will work.

Even if trimming isn't feasible, do you mind if I do a pull request for PolySharp and .NET 6?

**Comment by dgrunwald** [comment]
I don't see a need to introduce PolySharp here. We should be able to use ReferenceAssemblyAnnotator for .NET Core 2; and we shouldn't need anything extra at all for .NET 6?

**Comment by ds5678** [comment]
> I don't see a need to introduce PolySharp here.

If nothing else, you'll be able to use `MemberNotNullAttribute` and `MemberNotNullWhenAttribute` which are not available from ReferenceAssemblyAnnotator.

However, PolySharp also inserts [numerous other classes](https://github.com/Sergio0694/PolySharp#documentation-), such as `[UnscopedRef]`, which could potentially benefit your customers if used in ILSpy.

**Comment by christophwille** [comment]
Unless a customer specifically asks for that we won't do it. Just because is not a valid justification.

**Comment by ds5678** [comment]
It sounds like I am not welcome here.
