### ISSUE TITLE
System.ArgumentException: Number of type arguments must match the type definition's number of type parameters

### ISSUE THREAD

**Issue by Examnes** [icsharpcode/ILSpy#2885]
### Steps to reproduce
ilspycmd -p -o ./decomp/ Assembly-CSharp.dll
### Error message shown
[code.log](https://github.com/icsharpcode/ILSpy/files/10420137/code.log)
### Details
* Product in use: ilspycmd
* Version in use: ilspycmd: 7.2.1.0 ICSharpCode.Decompiler: 7.2.1.6856
* As far as i know the method that causes the problen is Process(ze): void of ClusterMapUI class
[Assembly-CSharp.zip](https://github.com/icsharpcode/ILSpy/files/10420134/Assembly-CSharp.zip)

**Comment by dgrunwald** [comment]
This seems to be already fixed in version 8.1. (4fc8f4e66e506e798e6be8c83fd6f1bfbc5a7fdf)
