### ISSUE TITLE
How to Decompile String, Bool etc...

### ISSUE THREAD

**Issue by AsutoraGG** [icsharpcode/ILSpy#2886]
![image](https://user-images.githubusercontent.com/76235964/212548302-5bdec6b4-97d5-412b-9ec9-34ac6526df14.png)
How to show String, Boolean

**Comment by dgrunwald** [comment]
That's obfuscated code -- an obfuscator has renamed all the fields to these unicode characters. The code you show is a correct representation of that.
This is not a bug in ILSpy: there isn't anything else left that a decompiler could show.
