### ISSUE TITLE
decompiled c# 7.3 code has recursive patterns from 8.0

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [icsharpcode/ILSpy#2888]
### Steps to reproduce
1. Decompile this: https://edit-sm.art/download/SMART.1.19.8261.19946.zip and decompress the .compressed files from custora
2. Try to compile it

### Error message shown

Feature 'recursive patterns' is not available in C# 7.3. Please use language version 8.0 or later.

### Details
ILSpy version 8.0.0.7106

**Comment by siegfriedpammer** [comment]
Can you tell us WHICH of the 13 compressed costura files we need to look at? Please also mention the full namespace, class and name of the member that contains the error.

Also, we haven't yet implemented support for recursive patterns in ILSpy, I would love to see the code that produces this compiler error. Thanks!

**Comment by H-A-M-G-E-R** [comment]
line 3141 in BtnPasteMapData_Click in MapEditor.cs and line 1982 in AllocateRooms in ProjectBody.cs
also decompressed and added all of the 13 compressed costura files

**Comment by H-A-M-G-E-R** [comment]
it's trying to put the 'is' operator on a tuple type

**Comment by H-A-M-G-E-R** [comment]
after i fixed it, the compiler gave CS8050 errors

**Comment by H-A-M-G-E-R** [comment]
and after i removed all compiler-generated code it still gives errors
