### ISSUE TITLE
Is this expected? (UniversalAssemblyResolver fallback)

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#2891]
https://github.com/icsharpcode/ILSpy/blob/cbaf05529d90304c34e65c9f45bafcd953b38de2/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs#L430-L442

Prior to 4.0 will fall back to .NET 6 rather than 4.0 as the comment indicate.

**Comment by siegfriedpammer** [comment]
Can you provide an example please?

**Comment by CreateAndInject** [comment]
[dotnet1.1test.zip](https://github.com/icsharpcode/ILSpy/files/11130741/dotnet1.1test.zip)

**Comment by christophwille** [comment]
Related #3011
