### ISSUE TITLE
ILSpy and compiler-generated code doesn't go well

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [icsharpcode/ILSpy#2907]
part 2 of #2888
same ILSpy version

**Comment by H-A-M-G-E-R** [comment]
The name 'LoadIntervalsAny' does not exist in the current context

**Comment by dgrunwald** [comment]
Please mention the assembly, class and method name that we should look at.
We don't want to waste a bunch of time trying to re-discover what you've already found.

**Comment by christophwille** [comment]
Closing because of no feedback. Feel free to open a new issue at a later time.
