### ISSUE TITLE
Please add an "Export to Project" menuitem, just like dnSpy and dotPeek have. (But ILSpy is just better)

### ISSUE THREAD

**Issue by TERIHAX** [icsharpcode/ILSpy#2916]
# *This is not an issue or bug report, this is a feature request*

# *Comment*
One thing I'd like to say is how phenomenal ILSpy is, I've used it from time to time but I've never expected it to have many things that other decompilers like dnSpy and JetBrains dotPeek don't have, one example is that both fail to decompile dynamic code but for ILSpy, it's just too great.

# *Feature Request*
I would like to request for an "Export to Project" menu item or button somewhere on the UI that will export the current selected decompiled project in the TreeView.

# Examples from other Decompilers:
# *dnSpy*
![image](https://user-images.githubusercontent.com/69073505/221667855-fd7bcdbf-88a1-4e98-8fce-f1da61fc70a5.png)
# *JetBrains dotPeek*
![image](https://user-images.githubusercontent.com/69073505/221668819-f93124b6-947e-4e12-8a84-931128a55659.png)

**Comment by christophwille** [comment]
This is what "Save code" does on the tree node of an assembly.

**Comment by TERIHAX** [comment]
> This is what "Save code" does on the tree node of an assembly.

I had no idea I could do that because I think I selected a class instead and it tried to save the class.

However, I tried it and it creates a .csproj file, but it doesn't create a .sln file along with the folder/directory that contains the .csproj file, this shouldn't really be a problem but it's a tiny that could be added
