### ISSUE TITLE
Optional ref parameters are not legal in C#

### ISSUE THREAD

**Issue by Peperud** [icsharpcode/ILSpy#2920]
VB.NET allows ```Optional ByRef``` parameters. 

When decompiling such code, ILSpy generates ```ref <type>=<default>``` parameter. Optional ```ref``` and ```out``` parameters are not allowed in C# and the code does not compile.

ILSpy version 7.2.1.6856

**Comment by dgrunwald** [comment]
That sounds more like a problem with C# than with ILSpy.

If there's no valid C# that results in the desired semantics (and externally-observable aspects of the method signature certainly count here), ILSpy will invent new syntax to accurately represent the IL anyways. We did that with `ref` locals long ago before C# had that feature; still do it for certain cases of `calli` not representable with C# function pointer syntax; I think this is just one more case.

**Comment by siegfriedpammer** [comment]
Such a parameter can be represented in C# by using the OptionalAttribute and DefaultParameterValueAttribute.

**Comment by daiplusplus** [comment]
IMO, ILSpy should emit a C# comment whenever it encounters known incompatible/illegal code so when people do copy-and-paste from ILSpy into VS they'll know the error isn't a bug or shortcoming in ILSpy.
