### ISSUE TITLE
Theme Selection UI Affordances

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2929]
We want the selection of themes to look and work like Visual Studio. Thus:
* have a "Theme" menu item above "UI Language" in the View menu (same section). Items in flyout are options from current toolbar dropdown.
* have a "Theme:" + dropdown in the Display tab of the Options dialog. Located on top above "Font:" separator (no additional separator to be added above)
* remove dropdown from toolbar

**Comment by christophwille** [comment]
@ltrzesniewski would that be something you'd be willing to do?

**Comment by ltrzesniewski** [comment]
Sure, no problem 🙂
