### ISSUE TITLE
Hope Don't limit the filename length

### ISSUE THREAD

**Issue by cozil** [icsharpcode/ILSpy#2941]
It seems that file name has a limitation of 30 chars. Could you please don't truncate the file name ? Or at least supply an option whether truncate the file name.

**Comment by greenozon** [comment]
Search through closed issues, this is a recurruring quesiton and there were very "hot" battles around it...

**Comment by cozil** [comment]
Thank you for telling me this solution!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2023年3月30日(星期四) 下午5:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [icsharpcode/ILSpy] Hope Don&#39;t limit the filename length (Issue #2941)





 
Not truncating the filename leads to crash reports if the filename exceeds Windows limits.
 Yeah, the battles are over; we won't be changing this now.
 
ILSpy uses a low limit if your system does not support long paths; and will use a higher limit if you enable the support for long paths in the registry: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
