### ISSUE TITLE
Show a dark title bar when a dark theme in ILSpy is selected

### ISSUE THREAD

**Issue by tom-englert** [icsharpcode/ILSpy#2950]
As of Windows 11 there is a possibility to change the color of the windows title bar.

"DWMWA_USE_IMMERSIVE_DARK_MODE" is supported starting with Windows 11 Build 22000.
[learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute)

This could be used to let the title bar color follow the ILSpy color theme.

Also maybe an option could be using DWMWA_CAPTION_COLOR and  DWMWA_TEXT_COLOR to set the colors explicit according to ILSpy them.

**Comment by christophwille** [comment]
I have read the various comments in the PR #2947. Let's look at this from the user's point of view: if I switch a theme in ILSpy, I expect consistent behavior regardless of the OS's settings regarding light/dark. So, me being light in Win11, selecting dark in ILSpy, I would expect the title bar to follow - and not like in the PR be a no-op ("Style the window title bar" is hitting that expectation).

**Comment by tom-englert** [comment]
Also just tried a simple sample app, using DWMWA_USE_IMMERSIVE_DARK_MODE.
It will do what is expected, despite the confusing documentation: https://learn.microsoft.com/en-us/answers/questions/966330/dwmwa-use-immersive-dark-mode-confusion

However I only managed to get a pitch-black title bar, no matter what my windows settings are:
![image](https://user-images.githubusercontent.com/10229954/230293724-5c8f412a-3650-48be-a9ff-ec0376fc4c17.png)

So if we anyhow ignore the windows theme settings, it would look better if we set the color individually.

**Comment by christophwille** [comment]
> So if we anyhow ignore the windows theme settings, it would look better if we set the color individually.

Simply floating a few ideas: Can we query the OS light/dark colors? What I am getting at is for a theme to say "Give me the system-default dark look for the chrome" vs additionally "Hey, this is the color to use" (think VS blue theme).

**Comment by SlimeNull** [comment]
> Also just tried a simple sample app, using DWMWA_USE_IMMERSIVE_DARK_MODE. It will do what is expected, despite the confusing documentation: https://learn.microsoft.com/en-us/answers/questions/966330/dwmwa-use-immersive-dark-mode-confusion
> 
> However I only managed to get a pitch-black title bar, no matter what my windows settings are: ![image](https://user-images.githubusercontent.com/10229954/230293724-5c8f412a-3650-48be-a9ff-ec0376fc4c17.png)
> 
> So if we anyhow ignore the windows theme settings, it would look better if we set the color individually.

![image](https://user-images.githubusercontent.com/69663231/230317928-124454d2-9d65-407d-afaf-5ee31702ee7c.png)
If you enable this option in the settings, then the Mica effect will not be applied to your title bar.

**Comment by SlimeNull** [comment]
And I noticed that your window border is not rounded, is there no problem with the graphics card driver? Or are rounded borders disabled or some visual effects?

**Comment by SlimeNull** [comment]
> > So if we anyhow ignore the windows theme settings, it would look better if we set the color individually.
> 
> Simply floating a few ideas: Can we query the OS light/dark colors? What I am getting at is for a theme to say "Give me the system-default dark look for the chrome" (even if light is current) vs additionally "Hey, this is the color to use" (think VS blue theme).

I am also curious. Visual Studio customized the title bar, but its "layout options" are still available.

**Comment by SlimeNull** [comment]
In addition, I have a suggestion. Currently, ILSpy has two themes, Light and Dark. Can we introduce an "Auto" mode? When the system theme changes, it automatically switches to the target mode. In WPF, we only need to subscribe to the SystemEvents.UserPreferenceChanged event.

**Comment by tom-englert** [comment]
> And I noticed that your window border is not rounded, is there no problem with the graphics card driver? Or are rounded borders disabled or some visual effects?

Yes, that's probably because its a VM, not a real machine, so my investigations here might not be fully valid.

**Comment by tom-englert** [comment]
> I am also curious. Visual Studio customized the title bar, but its "layout options" are still available.

If someone can find out how to enable this, I'll definitely would add this to the default styles!

**Comment by tom-englert** [comment]
> In addition, I have a suggestion. Currently, ILSpy has two themes, Light and Dark. Can we introduce an "Auto" mode? When the system theme changes, it automatically switches to the target mode. In WPF, we only need to subscribe to the SystemEvents.UserPreferenceChanged event.

Good point, but this would be a different issue.
