### ISSUE TITLE
Remove the possibility to have a custom styled title bar on any windows version.

### ISSUE THREAD

**Issue by tom-englert** [icsharpcode/ILSpy#2951]
With #2950 the windows title bar would follow the ILSpy theme automatically, without side effects, at least for Win11 users.

The feature to use a custom styled title bar (#2409 / #2412) is them maybe optional and could be removed.

**Comment by tom-englert** [comment]
Since #2950 only applies to Win11, and #2954 can be fixed via #2955, this issue should may be postponed

**Comment by christophwille** [comment]
Closing as per comment https://github.com/icsharpcode/ILSpy/pull/2955#issuecomment-1501913068
