### ISSUE TITLE
Large memory usage during decompilation when ILSpy is used within VS (through Roslyn).

### ISSUE THREAD

**Issue by CyrusNajmabadi** [icsharpcode/ILSpy#2965]
Hey ILSpy, 

We (Roslyn) are seeing extremely high memory spikes in the wild with people navigating to decompiled source.  Internal report:  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1801010

has the following info:

> “navigate to external source” (vs/ide/vbcs/navigatetoexternalsources) triggers decompilation, and sometimes consumes a lot of memory and other impacts as well. In 17.5, this memory issue ranks ninth, with 90th percentile size attributed to this being 2GB. 

> This session ([VS Session Explorer (vsdata.io)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fexplore.vsdata.io%2fvs%2fsession%2f55b90ddf-b6ac-4dad-96f7-7c5944a7af6d%2fevents&data=05%7c01%7cashokka%40microsoft.com%7c5364a6189cfa47f81fe308db3bc048c8%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638169469296915840%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=Go7rK2wtxt3STHUmwsrX%2BoUdmK%2f%2f%2BGoySA2xfO9EvGw%3D&reserved=0)) shows navigate to external sources triggering high CPU, high GC, high memory, threadpool starvation and eventually user terminates the process. 

The memory allocations in general are in:

```
[MemWatson] memory: Mgd_.NET_mscorlib!System.ValueTuple<ICSharpCode.Decompiler.IL.ILInstruction[], ICSharpCode.Decompiler.IL.ILInstruction>[]
```

Could this be looked into to see about if whatever is going on there can be optimized to use less memory?  Thanks!

**Comment by dgrunwald** [comment]
What decompiler version are you on?
That type makes me think of #2612 but that fix is old enough that it's already in v7.2.0.

**Comment by christophwille** [comment]
https://github.com/dotnet/roslyn/blob/e784dac5521faafa4d536113bc1e64821f7f0eee/eng/Versions.props#L64 7.1.0.6543

**Comment by CyrusNajmabadi** [comment]
Good to know. I'll update us!

**Comment by christophwille** [comment]
Just an fyi regarding one specific dependency of 7.2.1 (we forgot it previously) - Microsoft.Win32.Registry is only used by the class WholeProjectDecompiler which isn't used in the Roslyn integration at all. So it can be safely omitted (and it is gone in the 8 series again).

**Comment by christophwille** [comment]
For reference https://github.com/dotnet/roslyn/pull/67875 - closing this issue.

**Comment by christophwille** [comment]
Additional reference https://github.com/dotnet/roslyn/pull/67919 (change reverted because of VS Debugger also depending on ILSpy)
