### ISSUE TITLE
Searching resource tables

### ISSUE THREAD

**Issue by miloush** [icsharpcode/ILSpy#2967]
Trying to look for particular resources in a string/object table of .resources files. Ctrl+F in the decompiled .resources file does not work, as it is an embedded user control.

A workaround is to select all rows in the listview, copy them, paste into notepad and search there.

I would like to have the ability to search either by resource key or value in a decompiled .resources file. I am not expecting a search provider to look through these.

**Comment by christophwille** [comment]
PR merged, closing (wasn't linked to the PR so it slipped through).
