### ISSUE TITLE
Debugger Added back

### ISSUE THREAD

**Issue by modz2014** [icsharpcode/ILSpy#2968]
Hi any chance of adding debugger option back in i can keep it updated once added back in

**Comment by christophwille** [comment]
https://github.com/icsharpcode/ILSpy/pull/2966#issuecomment-1514565904 => No.

**Comment by modz2014** [comment]
it seems it can not be added back have to rewrite the hole project for getting debugger back im guessing

**Comment by modz2014** [comment]
instead of what

**Comment by modz2014** [comment]
what you talking about
