### ISSUE TITLE
Can't create pdb from assembly, doesn't contain PE Debug Directory Entry

### ISSUE THREAD

**Issue by Meister1593** [icsharpcode/ILSpy#2973]
Not sure if i understand what this means, or why it wouldn't create it, maybe i'm not understanding something obvious?
In general, my overall idea is to attach debugger (rider in my case) and have a debug symbols for the attached application assemblies to see code. The first part of attaching game i already completed, but without symbols it's not very useful, and rider doesn't generate them by itself. I tried using dotpeek, but it doesn't really want to run under wine, so while looking at solutions, ilspy seemed most promising for that purpose.

### Steps to reproduce
It seems quite random, but it happens for some Dll's, but not for others. In my case, i tried to generate pdb for game files (NeosVR)
and some assemblies works and they generate pdb files (CodeX.dll from Managed folder), but some don't (FrooxEngine.dll for instance)
Since this is a someone's product, i probably can't really redistribute dlls, but they are stored with it and it's free. There is also a link for a standalone version with same links outside steam, but not sure if it would be needed.

### Error message shown
![image](https://user-images.githubusercontent.com/7141787/233800214-ac29e89a-1272-4165-922b-3e0d757cdd5d.png)

### Details
* Product in use: e.g. ILSpy under wine, AvaloniaILSpy native on linux (same errors)
* Version in use: ILSpy version 7.2.1.6856 .NET version 4.7.3062.0 under wine and ILSpy version 7.2.0.0.rc (AvaloniaILSpy on linux native)

**Comment by trivalik** [comment]
The pdb create is blocked, the question is why: see https://github.com/icsharpcode/ILSpy/blob/fa900be124cf2997e9d60d3bf0a5735cad572625/ILSpy/Commands/GeneratePdbContextMenuEntry.cs#L62

**Comment by trivalik** [comment]
As we found out in the PR that for assemblies built without an pdb it is not possible to load a pdb in Visual Studio. This makes this bug report no sense and should be closed.
