### ISSUE TITLE
Switching Microsoft Store submission from MSIX to MSI

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2984]
For v7, we had a MSIX (Desktop Bridge) project. For v8, we switched to a vanilla installer MSI. Now, to submit an MSI the docs look rather simple https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/upload-app-packages?pivots=store-installer-msi-exe but it seems that after deleting the MSIX we are stuck in MSIX land:

![image](https://github.com/icsharpcode/ILSpy/assets/344208/bde4597a-20ce-44f8-99d8-a35faac46c79)

https://learn.microsoft.com/en-us/answers/questions/1244248/windows-store-change-existing-msix-or-pwa-app-to-e seems to confirm that changing isn't possible.

**Comment by christophwille** [comment]
I tried to get support from https://developer.microsoft.com/en-us/windows/support/?tabs=Contact-us (second one).
![image](https://github.com/icsharpcode/ILSpy/assets/344208/f0530da0-c129-412a-9e7b-805262fddaff)
Reply I got:
"Thank you for contacting Windows Developer Support, I understand that you would like to switch from MSIX to MSI your app ILSpy. It is out of my team scope you should contact App technical support  https://developer.microsoft.com/en-us/windows/support/ >  Contac us > UWP Development > Submit An Incident.
 
I am sorry for any inconvenience and appreciate your understanding.
 
I will proceed to close the ticket."

Aside from the fact what else than a portal issue that would be, it requires a support contract:
![image](https://github.com/icsharpcode/ILSpy/assets/344208/70adf9e6-0812-47c4-bbb9-eb7ca1eeee68)
 
I am in a good mood to close this and remove ILSpy from the Microsoft Store.

**Comment by christophwille** [comment]
ok, all my expectations came true re:a new app registration

we loose
* the url to the Store
* the reputation (reviews & ratings)
* all download history and statistics
* 
Additionally, existing users won't get an automatic update, but have to uninstall old and get a new one for the new registration.

**Comment by ltrzesniewski** [comment]
Out of curiosity, may I ask why you're switching from MSIX to MSI? I'm not familiar with the installer technologies.

**Comment by christophwille** [comment]
> Out of curiosity, may I ask why you're switching from MSIX to MSI? I'm not familiar with the installer technologies.

MSI is more general than the specialized MSIX format - and more importantly, the MSIX gave a few headaches in the past.

**Comment by driver1998** [comment]
Hosting MSI on Microsoft Store is just a glorfied download page, even automatic updates are not supported. I think it is going backwards from MSIX to MSI.

**Comment by christophwille** [comment]
[ms-windows-store://pdp/?productid=XP8C26VDWLP4T4](ms-windows-store://pdp/?productid=XP8C26VDWLP4T4) or Web store https://apps.microsoft.com/store/detail/ilspy-fresh/XP8C26VDWLP4T4

**Comment by christophwille** [comment]
The MSIX project gave us multi-targeting trouble and in general was not useful outside the store.

**Comment by christophwille** [comment]
* Verified: installs properly on Surface X (ARM64) from Store
* Verified: does not auto-update. We need to add something like NetsparkleUpdater (useful for everyone, not only a Store-version gimmick; kind of evergreen support like VSCode)

**Comment by driver1998** [comment]
Speaking of Surface X, can you release an ARM64 native version? I tried `dotnet ilspy.dll` to force ILSpy to run as ARM64, it works just fine. So it is mostly a packaging and releasing thing.

**Comment by christophwille** [comment]
The package is neutral.

**Comment by driver1998** [comment]
Modern .NET is not as "AnyCPU" as .NET Framework. The EXE file is a native C++ launcher (or app host), which will be tied to a specific architecture.

The current MSI ships an x64 app host, and will run ILSpy with the x64 .NET Runtime.

For the true "AnyCPU" experience, IIRC you would have to load the DLL directly with the `dotnet` command.

**Comment by christophwille** [comment]
@driver1998  please give "ILSpy arm64 8.0.0.7354 (Release) " a try at https://github.com/icsharpcode/ILSpy/actions/runs/5104246556#artifacts

That is an arm64-published binaries zip https://github.com/icsharpcode/ILSpy/commit/10129eaf0793c01074e3100f6de383c71494c63e

**Comment by driver1998** [comment]
Runs as native just fine, startup time is also good.
![image](https://github.com/icsharpcode/ILSpy/assets/22699485/f49e4367-e103-430e-a3cc-61f3d6554052)

**Comment by christophwille** [comment]
#2997 is the follow-up to this here (yes, not having an arm64 msi is a known minor issue at the moment).

**Comment by christophwille** [comment]
One more note: as of now, we are building arm64 msi installers.
