### ISSUE TITLE
Switch to System.Reflection.Metadata 7+ 

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#2989]
https://github.com/dotnet/runtime/pull/72561 this will allow support for generic attributes. 

This would be a breaking change in ics.d that hasn't had dependency changes for quite some time. And it might affect downstream consumers of the ics.d NuGet package.

**Comment by christophwille** [comment]
Additional note: we might even go to 8 of https://www.nuget.org/packages/System.Reflection.Metadata/

**Comment by christophwille** [comment]
@filipw would such a version upgrade be a problem for Omnisharp?

**Comment by filipw** [comment]
OmniSharp's dependency on SRM (aside from ICSharpCode.Decompiler of course) is via Microsoft.CodeAnalysis.Common, where it's defined as >= 7.0.0, so it should not be a problem.

**Comment by christophwille** [comment]
#3120 uses the SRM 7 approach again for SRM 8.
