### ISSUE TITLE
System.TypeLoadException: Could not load type 'ICSharpCode.ILSpy.LoadedAssembly'ILSpy, Version=8.0.0.7345

### ISSUE THREAD

**Issue by mohramzi** [icsharpcode/ILSpy#2995]
### Steps to reproduce
1. Select an exe file
2. Drag it to the ILSpy.exe to open
3. Once it opens, a popup error is showing

### Error message shown
System.TypeLoadException: Could not load type 'ICSharpCode.ILSpy.LoadedAssembly'ILSpy, Version=8.0.0.7345

### Details
*  ILSpy installer & ILSpy binaries
* Version 8.0.0.7345
* Reflexil is copied to ILSpy folder. **No errors when not using Reflexil**

###Screenshot
![2023-06-04 10 03 16](https://github.com/icsharpcode/ILSpy/assets/98305792/d69a1955-4296-4452-8e3d-3c640a7c8d85)

**Comment by christophwille** [comment]
Please see https://github.com/sailro/Reflexil - it has been discontinued.
