### ISSUE TITLE
Some redundant results

### ISSUE THREAD

**Issue by ahdung** [icsharpcode/ILSpy#2996]
LEFT: 7.2.1.6856
RIGHT: 8.0.0.7345-220b4cbd

I prefer LEFT.
If you need `dll` please email me, ahdung[you know]qq.com

![微信截图_20230607140233](https://github.com/icsharpcode/ILSpy/assets/12094247/0bbfa8b2-046e-45ae-942b-ec1004769671)
![微信截图_20230607140335](https://github.com/icsharpcode/ILSpy/assets/12094247/cc820d1a-6ddb-41bc-81de-5ef16b19cf96)

**Comment by dgrunwald** [comment]
This was an intentional change: ILSpy is now a bit closer to the original C# from which the DLL was generated.
See #2972.
