### ISSUE TITLE
ILSpy generate wrong .resx file for .NET Core

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#3001]
[ResourceTest.zip](https://github.com/icsharpcode/ILSpy/files/11697099/ResourceTest.zip)

Original .resx in VS :
![image](https://github.com/icsharpcode/ILSpy/assets/2529999/06714fd7-3095-4d10-99f3-0e61f045f59b)

Saved project in VS :
![image](https://github.com/icsharpcode/ILSpy/assets/2529999/34e3569b-90c4-45a0-990a-f5cbcd8653cf)

**Comment by CreateAndInject** [comment]
@dgrunwald @siegfriedpammer Branch resx-fix/Refactor ResXResourceWriter is merged, is it finished? But it can't fix this issue

**Comment by siegfriedpammer** [comment]
Can you share the project you used to create this? The data stored in the resources stream does not resemble anything that looks like an icon. Thanks!

**Comment by CreateAndInject** [comment]
[ResTest.zip](https://github.com/icsharpcode/ILSpy/files/11859477/ResTest.zip)

**Comment by ElektroKill** [comment]
> Can you share the project you used to create this? The data stored in the resources stream does not resemble anything that looks like an icon. Thanks!

The reason why ILSpy fails to decode this resource properly is that the underlying ResourceReader class is different. The file uses a different variation of ResourceReader which uses a slightly different format for serialized objects. You can take a look at the different behavior here: https://github.com/dotnet/dotnet/blob/95703b57cf3dfaa79f054d277551a809d4f7696a/src/runtime/src/libraries/System.Resources.Extensions/src/System/Resources/Extensions/DeserializingResourceReader.cs#L108

**Comment by CreateAndInject** [comment]
A year has passed, any news?
