### ISSUE TITLE
TypeSystem custom attribute API design question

### ISSUE THREAD

**Issue by ElektroKill** [icsharpcode/ILSpy#3002]
Hello,

I have a question regarding the way the TypeSystem explores CustomAttributes to the decompiler/end-user. I find it quite strange that the 3 methods relating to custom attributes (`GetAttributes`, `HasAttribute`, `GetAttribute`) will almost always rebuild the TypeSystem representation of the custom attributes when called. Is there any reason for this reconstruction? It seems to me that the TypeSystem model is read-only meaning that the data could be constructed once and stored for reuse to avoid constantly rebuilding it.

If such a caching approach is deemed appropriate I would be interested in contributing it :D

**Comment by dgrunwald** [comment]
The decompiler only uses these methods rarely (and mostly only on the methods being decompiled), so I don't think it makes much sense to spend a bunch of memory caching them (but I haven't actually measured this).
Also, `HasAttribute` has an optimized implementation that doesn't require creating a bunch of IAttribute instance.
