### ISSUE TITLE
The outer class of a nested class is not clickable

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#3025]
As the title said, the outer class is not clickable and no specific colour just like namespace in all built-in theme, plain black and white depends on light/dark theme. The hover tooltip is coloured as expected.
![image](https://github.com/icsharpcode/ILSpy/assets/9637711/a6d85146-ad12-4b63-a2d9-e81d02d2d8f4)

```csharp
namespace Namespace;
public class Layer1
{
    public class Layer2
    {
        public class Layer3
        {
            public class Layer4
            {
                public static void Method()
                {
                }
            }

            public static void Method()
            {
            }
        }

        public static void Method()
        {
        }
    }

    public static void Method()
    {
        Layer2.Method();
        Layer2.Layer3.Method();
        Layer2.Layer3.Layer4.Method();
    }
}
```
Perhaps this should be posted to [AvalonEdit](https://github.com/icsharpcode/AvalonEdit/)?

**Comment by ltrzesniewski** [comment]
> Perhaps this should be posted to [AvalonEdit](https://github.com/icsharpcode/AvalonEdit/)?

No, the hlighlighting code is in ILSpy itself (in `CSharpHighlightingTokenWriter` to be more precise)
