### ISSUE TITLE
How to handle (future) Depdenabot updates?

### ISSUE THREAD

**Issue by clin1234** [icsharpcode/ILSpy#3028]
I've just opened a pull request #3027 to bump a few dependencies. Far as I can tell, the GitHub Actions pass on both my fork and will soon do so upstream.

So, what's the policy from now on? Let upstream bump them automatically, or request manual merges from forks?

**Comment by christophwille** [comment]
Those deps were manually updated quite some time ago - and the "policy" regarding GH actions is more or less: we own them, we update them.
