### ISSUE TITLE
doc: Why does ICSharpCode.Decompiler lag in Roslyn?

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#3033]
This is only a "for your information" issue for documentation purposes.

The last update we started was https://github.com/dotnet/roslyn/pull/53304. If you look at the history, it took a super-long time until it landed. That was the point in time where we decided to no longer bother to provide update PRs.

Recently, @CyrusNajmabadi started PR https://github.com/dotnet/roslyn/pull/67875 (after opening issue #2965 with us), which was merged but almost immediately reverted in https://github.com/dotnet/roslyn/pull/67919. I asked in comment https://github.com/dotnet/roslyn/pull/67919#issuecomment-1522805463 what/if the future process could/would be to update the decompiler, but got no answer.

So we have no insight if/when updates to our decompilation engine will land in Roslyn / VS Debugger in the future going forward (fyi @jacdavis).

**Comment by CyrusNajmabadi** [comment]
We're happy to merge updates in ASAP.  Just give us a ping over at roslyn (ideally a new issue) when you want it to happen :-)

**Comment by christophwille** [comment]
@CyrusNajmabadi your upgrade PR got reverted because of whatever "dual insertion" or "concord" is. Is that sorted?

**Comment by CyrusNajmabadi** [comment]
oh no!  it did?  I was not aware that that had happened.  I'll look into it after the holidays.  Thanks!

**Comment by christophwille** [comment]
I didn't realize you weren't aware of that (otherwise would have pointed it out earlier). Btw, 8 is now out, and it is stable (ie we haven't received any dealbreaker bug reports)

**Comment by christophwille** [comment]
@CyrusNajmabadi did you get a chance to get the conversation going on how Roslyn & the debugger team can upgrade the Decompiler in lockstep in the future?

**Comment by CyrusNajmabadi** [comment]
@christophwille nope. I just got back. I'll check on this ASAP!

**Comment by christophwille** [comment]
For visibility to others - https://github.com/dotnet/roslyn/pull/69065 is the current PR of upgrading to 7.2.1

**Comment by christophwille** [comment]
@CyrusNajmabadi your comment "Just give us a ping over at roslyn (ideally a new issue) when you want it to happen" - we just released https://github.com/icsharpcode/ILSpy/releases/tag/v8.1 - obviously I'd wait at least a month before I'd open an issue at Roslyn. Would "Update Roslyn to ics.d version x" be an appropriate title? (Of course I'd list out new C# language features and also have a separate pdb generation section - the Debugger team will be interested I am sure.)

**Comment by CyrusNajmabadi** [comment]
Yup yup. That would be reasonable. Thanks!

**Comment by christophwille** [comment]
https://github.com/dotnet/roslyn/issues/69982 opened
