### ISSUE TITLE
A JetBrains Rider plugin

### ISSUE THREAD

**Issue by aldelaro5** [icsharpcode/ILSpy#3034]
**Is your feature request related to a problem? Please describe.**
I want to have a more integrated experience in my IDE for decompilation, but I don't like to use visual studio and I have a Rider license. Rider does come with its own decompiler called dotpeek, but in my experience, it is significantly worse than ILSpy. I would like to be able to have a similar integrated experience, but using ILSpy rather than dotpeek.

**Describe the solution you'd like**
A plugin that would replace dotpeek with ILSpy or implement similar features than its integration.

**Additional context**
This could help with linux usage because while there are options to use ILSpy there, I found them lacking in one way or another:
- Avalonia GUI: currently lacks maintenance and has many problems
- CLI: works perfectly, but lacks configuration of all the settings
- Using the wpf version with wine: I tried this, it refuses to work well

It also seems logical to me: Rider while not free, is used quite a lot and I think ILSpy could be well integrated into this IDE just like visual studio.

**Comment by christophwille** [comment]
This is not something we plan on doing - for precisely the reason that there is an integration between Rider and dotPeek (their products).
