### ISSUE TITLE
Windows 11 context menu 

### ISSUE THREAD

**Issue by modz2014** [icsharpcode/ILSpy#3043]
Looking creating the context menu for windows 11 i have created Contextmenu in C++  this can only be achieved by using msix package whcih is how explorer is sued to identiy the programs

**Comment by christophwille** [comment]
As discussed in #3042 we won't add that to the main project. Feel free to create that as an "add on" for ILSpy (to be separately downloaded, obviously), we'll happily point users towards such a project.

**Comment by modz2014** [comment]
yer was told to open something here so i did umm i see that microsoft will be removing the old context menu if future updates according to the sider programmer

**Comment by christophwille** [comment]
My comment was only intended to summarize and surface the discussion we already had in your previous pull request.

**Comment by modz2014** [comment]
here the link the uploaded project if anything needs to be changed let me know https://github.com/modz2014/ILSpyContextMenu/

**Comment by modz2014** [comment]
also i can not get installer to compile as well not to sure why

**Comment by christophwille** [comment]
Please see https://github.com/icsharpcode/ILSpy/blob/master/ILSpy.Installer/README.md

**Comment by modz2014** [comment]
yer already done this i just figured it out the installer needs to be set to release for it to build

**Comment by christophwille** [comment]
Yes, you are right, those projects are only configured for Release.

**Comment by modz2014** [comment]
ok since you don't link C I have made some adjustments for windows 11 as well but still working out why .exe does not show up yet it does for .dll 

`public ICommand AddRemoveShellIntegrationCommand { get; }

		const string rootPathExe = @"Software\Classes\exefile\shell\Open With ILSpy";
		const string rootPathDll = @"Software\Classes\dllfile\shell\Open With ILSpy";

		private void AddRemoveShellIntegration(object obj)
		{
			string commandLine = NativeMethods.ArgumentArrayToCommandLine(Path.ChangeExtension(Assembly.GetEntryAssembly().Location, ".exe")) + " \"%L\"";
			if (RegistryEntriesExist())
			{
				if (MessageBox.Show(string.Format(Properties.Resources.RemoveShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes)
				{
					Registry.CurrentUser.DeleteSubKeyTree(rootPathDll);
					Registry.CurrentUser.DeleteSubKeyTree(rootPathExe);
				}
			}
			else
			{
				if (MessageBox.Show(string.Format(Properties.Resources.AddShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes)
				{
					RegisterContextMenuForFileType(".dll", commandLine);
					RegisterContextMenuForFileType(".exe", commandLine);
				}
			}
			OnPropertyChanged(nameof(AddRemoveShellIntegrationText));
		}

		private static void RegisterContextMenuForFileType(string fileType, string commandLine)
		{
			string rootPath = fileType == ".dll" ? rootPathDll : rootPathExe;

			var rootKey = Registry.CurrentUser.CreateSubKey(rootPath);
			rootKey?.SetValue("", "Open With ILSpy");

			var commandKey = rootKey?.CreateSubKey("command");
			commandKey?.SetValue("", commandLine);
		}

		private static bool RegistryEntriesExist()
		{
			return Registry.CurrentUser.OpenSubKey(rootPathDll + @"\command") != null
				&& Registry.CurrentUser.OpenSubKey(rootPathExe + @"\command") != null;
		}

		public string AddRemoveShellIntegrationText {
			get {
				return RegistryEntriesExist() ? Properties.Resources.RemoveShellIntegration : Properties.Resources.AddShellIntegration;
			}
		}`

**Comment by modz2014** [comment]
ok i found soemthing you can use the key called extract and will show to open ILSpy in windows 11 context menu but thats really a good way i tried creating a shell context menu and still does the same thing not to sure why here is an exmaple 

`[HKEY_CLASSES_ROOT\exefile\shell\extarct\command]
@="\"C:\\Users\\UserName\\Desktop\\Path to ILSpy\\ILSpy.exe\" \"%1\"" `

**Comment by christophwille** [comment]
No, that won't work. The installer is non-admin, writing to local machine thus not possible.

**Comment by christophwille** [comment]
The installer is non-admin and will remain that way. It was very much intentional for it to behave exactly like vscode.

**Comment by modz2014** [comment]
ok so then the installer doe not add registery keys then

**Comment by modz2014** [comment]
ok i added the registerying part for my contextmenu you can add the context menu to the install just if you use just change the location to the same area where your installing ILSpy by defualt and then run the custom command to register the context menu once the package has been built  you can run the installer 

To do 
Create the package for ILSpy 
run the custom command when install ILSpy is installing

**Comment by modz2014** [comment]
i added a few changes to ILSpy for the context menu it check the OS version your on windows 10 or windows 11 if windows 11 it install the context menu i created else if on windows 10 use the one you use created if you wanna see the example

**Comment by modz2014** [comment]
here is what i have for windows 11 ILSpy check the OS version either windows 10 or windows 11 and install my contextMenu hopefully this can be added in as well i will update the contextmenu again later on so it be found in the current director as ILSpy ect 

`using System;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows;
using System.Windows.Input;

using ICSharpCode.ILSpy.Commands;
using ICSharpCode.ILSpyX.Settings;

using Microsoft.Win32;



using static System.Windows.Forms.VisualStyles.VisualStyleElement;

namespace ICSharpCode.ILSpy.Options
{



	public class MiscSettingsViewModel : IMiscSettings, INotifyPropertyChanged
	{
		


		bool allowMultipleInstances;
		bool loadPreviousAssemblies = true;

		public MiscSettingsViewModel(MiscSettings s)
		{
			AllowMultipleInstances = s.AllowMultipleInstances;
			LoadPreviousAssemblies = s.LoadPreviousAssemblies;

			AddRemoveShellIntegrationCommand = new DelegateCommand<object>(AddRemoveShellIntegration);
		}

		/// <summary>
		/// Allow multiple instances.
		/// </summary>
		public bool AllowMultipleInstances {
			get { return allowMultipleInstances; }
			set {
				if (allowMultipleInstances != value)
				{
					allowMultipleInstances = value;
					OnPropertyChanged();
				}
			}
		}

		/// <summary>
		/// Load assemblies that were loaded in the previous instance
		/// </summary>
		public bool LoadPreviousAssemblies {
			get { return loadPreviousAssemblies; }
			set {
				if (loadPreviousAssemblies != value)
				{
					loadPreviousAssemblies = value;
					OnPropertyChanged();
				}
			}
		}

		public ICommand AddRemoveShellIntegrationCommand { get; }

		const string rootPath = @"Software\Classes\{0}\shell";
		const string fullPath = @"Software\Classes\{0}\shell\Open with ILSpy\command";

		private void AddRemoveShellIntegration(object obj)
		{
			string commandLine = NativeMethods.ArgumentArrayToCommandLine(Path.ChangeExtension(Assembly.GetEntryAssembly().Location, ".exe")) + " \"%L\"";


			if (IsWindows10())
			{
				// Windows 10 logic
				if (RegistryEntriesExist())
				{
					if (MessageBox.Show(string.Format(Properties.Resources.RemoveShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes)
					{
						Registry.CurrentUser.CreateSubKey(string.Format(rootPath, "dllfile")).DeleteSubKeyTree("Open with ILSpy");
						Registry.CurrentUser.CreateSubKey(string.Format(rootPath, "exefile")).DeleteSubKeyTree("Open with ILSpy");
					}
				}
				else
				{
					if (MessageBox.Show(string.Format(Properties.Resources.AddShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes)
					{
						Registry.CurrentUser.CreateSubKey(string.Format(fullPath, "dllfile"))?
							.SetValue("", commandLine);
						Registry.CurrentUser.CreateSubKey(string.Format(fullPath, "exefile"))?
							.SetValue("", commandLine);
					}

					OnPropertyChanged(nameof(AddRemoveShellIntegrationText));
				}
			}
			else if (IsWindows11())
			{
				if (RegistryEntriesExist())
				{
					if (MessageBox.Show(string.Format(Properties.Resources.RemoveShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes)
					{
						// Execute PowerShell commands to remove the package on Windows 11
						string packageName = "ContextMenuRegistration_1.0.0.0_neutral__h91ms92gdsmmt";
						string removeCommand = $"Remove-AppxPackage -Package {packageName}";

						ProcessStartInfo startInfo = new ProcessStartInfo("powershell.exe") {
							Arguments = $"-NoProfile -ExecutionPolicy Bypass -Command \"{removeCommand}\"",
							RedirectStandardOutput = true,
							UseShellExecute = false,
							CreateNoWindow = true
						};

						Process process = new Process();
						process.StartInfo = startInfo;
						process.Start();
						process.WaitForExit();
					}
				}
				else
				{
					// Add Windows 11-specific logic for adding the integration if needed
				}
			}

			OnPropertyChanged(nameof(AddRemoveShellIntegrationText));
		}


		private static bool IsWindows10()
		{
			return Environment.OSVersion.Platform == PlatformID.Win32NT && !IsWindows11();
		}
		[StructLayout(LayoutKind.Sequential)]
		public struct OSVERSIONINFOEX
		{
			public int dwOSVersionInfoSize;
			public int dwMajorVersion;
			public int dwMinorVersion;
			public int dwBuildNumber;
			public int dwPlatformId;
			[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
			public string szCSDVersion;
		}

		[DllImport("ntdll.dll", SetLastError = true)]
		public static extern int RtlGetVersion(ref OSVERSIONINFOEX lpVersionInformation);
		private static bool IsWindows11()
		{

			OSVERSIONINFOEX osVersionInfo = new OSVERSIONINFOEX();
			osVersionInfo.dwOSVersionInfoSize = Marshal.SizeOf(typeof(OSVERSIONINFOEX));

			if (RtlGetVersion(ref osVersionInfo) == 0)
			{
				return (osVersionInfo.dwMajorVersion == 10 && osVersionInfo.dwMinorVersion == 0 && osVersionInfo.dwBuildNumber >= 22000);
			}

			return false;
		}


		private static bool RegistryEntriesExist()
		{
			string packageName = "ContextMenuRegistration_1.0.0.0_neutral__h91ms92gdsmmt";
			string packagePath = @"Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages";

			if (IsWindows10())
			{
				return (Registry.CurrentUser.OpenSubKey(string.Format(fullPath, "dllfile")) != null &&
						Registry.CurrentUser.OpenSubKey(string.Format(fullPath, "exefile")) != null);
			}
			else if (IsWindows11())
			{
				using (RegistryKey key = Registry.CurrentUser.OpenSubKey(packagePath))
				{
					if (key != null)
					{
						return key.OpenSubKey(packageName) != null;
					}
				}
			}

			return false;
		}



		public string AddRemoveShellIntegrationText {
			get {
				if (IsWindows10())
				{
					return RegistryEntriesExist() ? Properties.Resources.RemoveShellIntegration : Properties.Resources.AddShellIntegration;
				}
				else if (IsWindows11())
				{
					// Return appropriate text for Windows 11
					return RegistryEntriesExist() ? Properties.Resources.RemoveShellIntegration : Properties.Resources.AddShellIntegration;
				}
			
				else
				{
					return "Unsupported Windows version.";
				}
			}
		}


		#region INotifyPropertyChanged Implementation

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			PropertyChanged?.Invoke(this, e);
		}

		protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}

		#endregion
	}
}
`

**Comment by greenozon** [comment]
>return "Unsupported Windows version.";

Please add other OS support
there are lots of people still using win7/8

**Comment by modz2014** [comment]
yes i can do that as well

**Comment by modz2014** [comment]
@greenozon i added the other OS as well but i have not tested them as i dont use those OS anymore

**Comment by greenozon** [comment]
No problemo
please leave me the luxury to test Windows7 support

**Comment by modz2014** [comment]
we dont need to check OS version only needs to be checl for windows 11 to use the new contextmenu others all other OS work the same with change that later i was using for testing other thing i have on there as well

**Comment by modz2014** [comment]
@greenozon i have fixed it up properly now it should work regardless if your not on windows 11

**Comment by modz2014** [comment]
here is the new code with windows 11 context menu for windows 11 

`public ICommand AddRemoveShellIntegrationCommand { get; }

		const string rootPath = @"Software\Classes\{0}\shell";
		const string fullPath = @"Software\Classes\{0}\shell\Open with ILSpy\command";

		private void AddRemoveShellIntegration(object obj)
		{
			string commandLine = NativeMethods.ArgumentArrayToCommandLine(Path.ChangeExtension(Assembly.GetEntryAssembly().Location, ".exe")) + " \"%L\"";

			if (IsWindows11())
			{
				if (RegistryEntriesExist())
				{
					if (System.Windows.MessageBox.Show(string.Format(Properties.Resources.RemoveShellIntegrationMessageWindows11, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question) == MessageBoxResult.Yes)
					{
						// Execute PowerShell commands to remove the package on Windows 11
						string packageName = "ContextMenuRegistration_1.0.0.0_neutral__h91ms92gdsmmt";
						string removeCommand = $"Remove-AppxPackage -Package {packageName}";

						ProcessStartInfo startInfo = new ProcessStartInfo("powershell.exe") {
							Arguments = $"-NoProfile -ExecutionPolicy Bypass -Command \"{removeCommand}\"",
							RedirectStandardOutput = true,
							UseShellExecute = false,
							CreateNoWindow = true
						};

						Process process = new Process();
						process.StartInfo = startInfo;
						process.Start();
						process.WaitForExit();
					}
				}
				else
				{
					//MessageBox.Show("Entering Windows 11 logic", "Debug Info", MessageBoxButton.OK, MessageBoxImage.Information);
					var result = System.Windows.MessageBox.Show(string.Format(Properties.Resources.AddShellIntegrationMessageWindows11, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question);
					if (result == MessageBoxResult.Yes)
					{
						
						//MessageBox.Show("User clicked Yes for Windows 11 integration", "Debug Info", MessageBoxButton.OK, MessageBoxImage.Information);
						ProcessStartInfo startInfo = new ProcessStartInfo("ContextReg.exe") 
						{
							RedirectStandardOutput = true,
							RedirectStandardError = true,
							UseShellExecute = false,
							CreateNoWindow = true
						};

						using (Process process = new Process())
						{
							process.StartInfo = startInfo;
							process.Start();
							process.WaitForExit();
						}

						OnPropertyChanged(nameof(AddRemoveShellIntegrationText));


					}
				}
				OnPropertyChanged(nameof(AddRemoveShellIntegrationText));

			}

			else
			{


				//Other OS Systems 
				if (RegistryEntriesExist())
				{
					var result = System.Windows.MessageBox.Show(string.Format(Properties.Resources.RemoveShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question);
					if (result == MessageBoxResult.Yes)
					{
						Registry.CurrentUser.CreateSubKey(string.Format(rootPath, "dllfile")).DeleteSubKeyTree("Open with ILSpy");
						Registry.CurrentUser.CreateSubKey(string.Format(rootPath, "exefile")).DeleteSubKeyTree("Open with ILSpy");
					}
					OnPropertyChanged(nameof(AddRemoveShellIntegrationText));
				}
				else
				{
					var result = System.Windows.MessageBox.Show(string.Format(Properties.Resources.AddShellIntegrationMessage, commandLine), "ILSpy", MessageBoxButton.YesNo, MessageBoxImage.Question);
					if (result == MessageBoxResult.Yes)
					{
						Registry.CurrentUser.CreateSubKey(string.Format(fullPath, "dllfile"))?
							.SetValue("", commandLine);
						Registry.CurrentUser.CreateSubKey(string.Format(fullPath, "exefile"))?
							.SetValue("", commandLine);
					}

					OnPropertyChanged(nameof(AddRemoveShellIntegrationText));
				}



			}

		}





		private static bool RegistryEntriesExist()
		{
			string packageName = "ContextMenuRegistration_1.0.0.0_neutral__h91ms92gdsmmt";
			string packagePath = @"Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages";

			if (IsWindows11())
			{
				using (RegistryKey key = Registry.CurrentUser.OpenSubKey(packagePath))
				{
					if (key != null)
					{
						return key.OpenSubKey(packageName) != null;
					}
				}
			}
			else
			{
				return (Registry.CurrentUser.OpenSubKey(string.Format(fullPath, "dllfile")) != null &&
						Registry.CurrentUser.OpenSubKey(string.Format(fullPath, "exefile")) != null);
			}

			return false;
		}

		public string AddRemoveShellIntegrationText {
			get {
				if (IsWindows11())
				{
					return RegistryEntriesExist() ? Properties.Resources.RemoveShellIntegration : Properties.Resources.AddShellIntegration;
				}
				else
				{
					return RegistryEntriesExist() ? Properties.Resources.RemoveShellIntegration : Properties.Resources.AddShellIntegration;
				}
			}
		}`

**Comment by modz2014** [comment]
hey should i create something seperate for msix package for ILSpy or no i have added the contextmenu to it as well

**Comment by christophwille** [comment]
Sorry, I don't follow - what do you want to do & where?

**Comment by modz2014** [comment]
i was asking i have created a msix package with my contextmenu for windows 11 to use the new context menu i also have added some code up to you guys above to help with implementy the context menu on windows 11 in above post

**Comment by christophwille** [comment]
You want the code in https://github.com/icsharpcode/ILSpy/issues/3043#issuecomment-1666548891 be merged into ILSpy - basically an install / uninstall of a Store app that is not provided by us, or is the install part separate and will fail if the msix is not on the machine already? (because ContextReg.exe must come from somewhere I suppose)

Given how complicated Explorer context menu integration in Windows 11 seems to be we are more inclined to drop it altogether and only have drag & drop support.

**Comment by modz2014** [comment]
ContextReg.exe is from my project https://github.com/modz2014/ILSpyContextMenu/tree/main/RegApp here is the source code i can create the msix package by itself as well if you want it to be part of ILSpy just let me know

**Comment by christophwille** [comment]
@siegfriedpammer @dgrunwald https://github.com/icsharpcode/ILSpy/issues/3043#issuecomment-1681940226 do we want the Explorer integration to get that complicated & convoluted? Or keep as is and "risk" that at some point MS will kill off the old integration?

**Comment by modz2014** [comment]
well in the context menu you can use the location of where ILSpy is installed when installin it but when running portable is a different story i will be keeping the ocntextmenu up to date all the time and the msi install as well if needed

**Comment by modz2014** [comment]
i have updated the contextmenu again can be installed and be used where ever ILSpy is located as long as remove shell context and add shell context again at new location same way as it was before

**Comment by christophwille** [comment]
How about this approach:
* we keep the legacy Explorer integration in ILSpy as-is (even if the user activates it, it will be sort-of-hidden behind "Show more options")
* you provide the addon for the first-class Windows 11 Explorer integration

For that approach to work, you'd need to allow a user to specific the path to ilspy.exe - that way your contextmenu could work with any of the installation options of ILSpy.

**Comment by modz2014** [comment]
i just update it to work in any location when ILSpy is installed/ being anywhere on the system its implemented in the context menu this will also work on windows 10 as well as windows 11 so no need to check if the system is on windows 11 or not

**Comment by modz2014** [comment]
this code shows a messagebox where ILSpy is located @christophwille [MessageBox(nullptr, ilspyPath, L"ILSpy Path", MB_OK);](https://github.com/modz2014/ILSpyContextMenu/blob/84b78c7ad89a6c00bd48877882fcbc8278721f78/ContextMenuImplementation/dllmain.cpp#L223)

**Comment by christophwille** [comment]
There might be a misunderstanding here (either on my part or your part, don't know for sure): your context menu has to know where ilspy.exe is located. If our distribution of ILSpy does not include any of your code for enabling/disabling your context menu, your context menu has to have some means for the user to specify the location of ilspy.exe. A C++ MessageBox is not a means of input if I am not mistaken.

**Comment by modz2014** [comment]
My context menu requires 'ilspy.exe' location for proper functioning. If not bundled with our code, users can conveniently specify its location via a user-friendly interface, ensuring smooth functionality independent of 'ilspy.exe' distribution.

Moreover, my context menu seamlessly locates 'ilspy.exe' on its own, eliminating the need for user input

**Comment by modz2014** [comment]
My context menu requires 'ilspy.exe' location for proper functioning. If not bundled with our code, users can conveniently specify its location via a user-friendly interface, ensuring smooth functionality independent of 'ilspy.exe' distribution.

Moreover, my context menu seamlessly locates 'ilspy.exe' on its own, eliminating the need for user input @christophwille

**Comment by modz2014** [comment]
My context menu requires 'ilspy.exe' location for proper functioning. If not bundled with our code, users can conveniently specify its location via a user-friendly interface, ensuring smooth functionality independent of 'ilspy.exe' distribution.

Moreover, my context menu seamlessly locates 'ilspy.exe' on its own, eliminating the need for user input @christophwille

**Comment by siegfriedpammer** [comment]
I did not read everything in this thread as it is getting longer and longer, however, as far as we, the maintainers, are concerned, I'd like to clearly state that:

1. No, we will never incorporate any code into ILSpy that requires an elevated process ("administrator" permissions) to work - portability and speed are key characteristics of ILSpy.
2. Extending the Windows 11 context menu seems to add no significant value, the pre-Win11 way of doing things is easy, requires no elevation and is portable. *Personal opinion: Microsoft decided to change things again in Windows 11 for the sake of change it seems. The Shift+F10 nonsense only adds to the list of things making me want to stay away from Windows 11 as long as possible.*
3. You (or anyone interested in the topic) are free to re-package ILSpy to make it more Windows 11 compatible (just like https://github.com/M2Team/NanaZip does for 7zip) and we will gladly link to you in our wiki and/or readme. However, *personal opinion: I think compared to 7zip (which has a lot of commands in its explorer integration), doing the same for one single ILSpy command is too much work.*

Thanks!

**Comment by christophwille** [comment]
Added to https://github.com/icsharpcode/ILSpy/wiki/Plugins#current-plugins

**Comment by modz2014** [comment]
This does not need administration rights i have changed the code multiple
times its just package as a seperate msix app identifier which is what is
needed for windows 11 context menu it can also run on windows 10 and below
as well contextmenu knows where ILSpy.exe is regardless of locations its
the same way you intergrated it now  if you move ilspy you need to remove
shell and then add it again in the new location same way context menu is
done

Keep in mind if you package ilspy and my contextmenu as msix it will get
registered

Registery the shell context menu without msix package would work but wont
show up in the new windows 11 context menu

Since microsoft have announced they will stop supporting windows 10 in 3
years times

**Comment by christophwille** [comment]
Closing the issue as the addon is now listed for anyone who wants tight Windows 11 Explorer integration.
