### ISSUE TITLE
Add multitab support

### ISSUE THREAD

**Issue by pryvyd9** [icsharpcode/ILSpy#3044]
**Is your feature request related to a problem? Please describe.**
It's currently impossible to open multilple tabs and pin them. There's no option to pin a tab and they switch whenever I go to other types so I have to write down the types and use search to find them again. It's inconvenient.

**Describe the solution you'd like**
I need an ability to open multilple tabs and pin them.

**Additional context**
![зображення](https://github.com/icsharpcode/ILSpy/assets/26070759/b6490887-1f72-4318-bc0d-d3e40bd76981)

**Comment by christophwille** [comment]
![image](https://github.com/icsharpcode/ILSpy/assets/344208/9e3c06a7-ae2c-4ada-a313-1eba7a36a11f)
Isn't that what you are looking for? (yes, pinning a tab to the left would be a different thing, but I am talking multi-tab)

**Comment by pryvyd9** [comment]
oh, I didn't notice that. Thanks, that'll do for me
