### ISSUE TITLE
IL Code Question

### ISSUE THREAD

**Issue by modz2014** [icsharpcode/ILSpy#3059]
Hey i notice something im not to sure if its ILSpy but when looking thiorught the code of a exe file using IL it shows a few different ones then if i was to use Simple assembly explorer ones not sure if there is an issue but it seems to be confusing when using IL in Ilspy it might be me having to learn how ILspy is using it not sure
<img width="1074" alt="Screenshot 2023-08-18 131021" src="https://github.com/icsharpcode/ILSpy/assets/25472227/7d57c9a8-061a-4039-a422-9ad9fcc4d6cb">

**Comment by siegfriedpammer** [comment]
Can you please provide the assembly in question, so I can take a closer look? Thanks!

**Comment by modz2014** [comment]
fix it
