### ISSUE TITLE
Improper IL Decompilation of try/filter/catch statements

### ISSUE THREAD

**Issue by AV-IO** [icsharpcode/ILSpy#3061]
### Steps to reproduce
1. Decompile MobileConcepts45.dll (obtained from [CyberGhost download](https://www.cyberghostvpn.com/en_US/apps/windows-vpn) and installation) to [IL](https://gist.github.com/AV-IO/77612990e3473bd0034c52ff70217eab)
2. Fail to compile to DLL target with `ilasm.exe .\MobileConcepts45.il /DLL /noautoinherit`
3. Modify `MobileConcepts45.il` file to match [ECMA-335 (6th edition)](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf) §11.19.4 by removing `catch` keyword
4. All applicable (try/filter/catch) statements should now read as follows:
```cs
.try {
// ...
}
filter {
// ...
}
{
// ...
}
```
5. Successfully compile to DLL target with `ilasm.exe .\MobileConcepts45.il /DLL /noautoinherit`

### Error message shown
```
.\MobileConcepts45.il(62976) : error : syntax error at token 'catch' in:               catch
```

### Details
* ILSpy 8.1.0.7455
* ilasm v. 4.8.9105.0 (Included in Visual Studio 2022 v. 17.6.3)
* Windows 11 development environment ([provided by Microsoft](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/))

### Resolution
I believe to resolve this for the future, ILSpy should no longer output the `catch` keyword when preceded directly by a `filter` statement in order to comply with ECMA-335.

**Comment by siegfriedpammer** [comment]
Thanks for reporting! Next time, please upload the binary in question directly, so I don't have to go and download + install software in order to reproduce the bug. Thank you for your understanding!
