### ISSUE TITLE
Win store version is outdated

### ISSUE THREAD

**Issue by heartacker** [icsharpcode/ILSpy#3062]
ILSpy 版本 7.2.1.6856
.Net 版本4.8.9172.0
Package Name: 17310ICSharpCodeTeam.ILSpy_7.2.6856.0_neutral__jpqg2ewkdrg54

![image](https://github.com/icsharpcode/ILSpy/assets/1876302/b3da2ea7-0fc2-43fe-9472-1f9523f6c621)

**Comment by christophwille** [comment]
Yes, that is the net472 version, you are looking for ILSpy Fresh.

**Comment by heartacker** [comment]
https://github.com/icsharpcode/ILSpy/releases now is  8.xx

**Comment by christophwille** [comment]
The homepage links to the current store version https://apps.microsoft.com/store/detail/ilspy-fresh/XP8C26VDWLP4T4

**Comment by heartacker** [comment]
ALL RIGHT, THAT , AND I get used to my installed version(NOT FRESH) so we do not notice the new app
