### ISSUE TITLE
[Bug?]: `ScopeSearchToAssembly` includes assemblies which also start with the same assembly name

### ISSUE THREAD

**Issue by just-ero** [icsharpcode/ILSpy#3064]
## Steps to reproduce
1. Load two assemblies where one begins with the same name as the other; i.e. `FooAssembly.dll` and `FooAssembly-Other.dll`
2. Search for a type or member name which matches in both assemblies.
3. Scope the search to `FooAssembly.dll` via `inassembly:FooAssembly`.

## Expected Behavior
Only results from `FooAssembly.dll` are be displayed.

## Actual Behavior
Results from `FooAssembly-Other.dll` are also displayed.  
This is relevant for example when decompiling a Unity game's `Assembly-CSharp.dll` where results from `Assembly-CSharp-firstpass.dll` are also displayed.

## Details
* Product in use: ILSpy
* Version in use: 8.1.0.7455

**Comment by siegfriedpammer** [comment]
While I can see your point, I think this is by design, since everything uses sub-string matching by default. Maybe we would need something like `inassembly:=FooAssembly` to denote whole-string matching?

**Comment by dgrunwald** [comment]
I don't think new syntax is the solution; personally I can't even remember our existing syntax.

Different idea: adjust the sorting of search results, so that exact matches are preferred.
