### ISSUE TITLE
Remove packaged ILSpy from MS Store

### ISSUE THREAD

**Issue by dongle-the-gadget** [icsharpcode/ILSpy#3066]
**Is your feature request related to a problem? Please describe.**
Currently there are two product pages, both visible, for ILSpy in the Microsoft Store: ILSpy and ILSpy Fresh (the former is packaged, the latter is not). Packaged ILSpy has been discontinued since version 8.0, and leaving both product pages visible causes confusion when users search for "ILSpy" in the Microsoft Store.

**Describe the solution you'd like**
Set discoverability for the packaged ILSpy version to private and modify description to say that it's outdated. Possibly, in addition, provide an exclusive update to add a notification saying that the packaged version is no longer updated (right now, there are no clear indication of deprecation other than the lack of updates).

**Comment by modz2014** [comment]
they do not use msix packages anymore so it wont get updated apparently

**Comment by christophwille** [comment]
The legacy package has been set to

![image](https://github.com/icsharpcode/ILSpy/assets/344208/e2662a3d-b24b-47a6-8ae9-f56d5cd862ed)

**Comment by christophwille** [comment]
Made unavailable.
