### ISSUE TITLE
Support for .NET 8

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3084]
what are the ideas/plans/etc for upcoming .NET 8 ?

it was just [released ](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)(RC1)

**Comment by christophwille** [comment]
We have a branch for that https://github.com/icsharpcode/ILSpy/tree/net8 - but the current plan is to release 8.2 on .NET 6.0 first.

**Comment by greenozon** [comment]
RC2 was just released
looks like there is a rule of thumb to release once a month some delivery?.. or so

**Comment by christophwille** [comment]
Just to give some guidance - that branch won't be touched again before net80 rtm and ILSpy 8.2 shipping.

**Comment by greenozon** [comment]
Hurrey!
8.0 RTM was just released!  any plans for next steps?

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by christophwille** [comment]
Implemented by #3119
