### ISSUE TITLE
ILSpy doesn't respect the NUGET_PACKAGES environment variable

### ISSUE THREAD

**Issue by geeknoid** [icsharpcode/ILSpy#3090]
I just installed a fresh machine, and I used the latest .NET 8 rc2 SDK. Doing so, my nuget package cache ended up in c:\.tools\.nuget instead of the prior ~/.nuget which was previously customary. The environment contains a NUGET_PACKAGES environment variable that points to this new location and is respected by the .NET tooling.

ILSpy however hardcodes its lookup to ~/.nuget as seen here: https://github.com/icsharpcode/ILSpy/blob/d2d1c3326f4362f5853916e5e65daf2a458f35b9/ICSharpCode.Decompiler/Metadata/DotNetCorePathFinder.cs#L63

Would it be possible to add support for the NUGET_PACKAGES environment variable?

Thanks.

**Comment by christophwille** [comment]
Relevant docs: https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-environment-variables "Specified as absolute path."

**Comment by geeknoid** [comment]
FYI, as a workaround, I created an NTFS junction from ~/.nuget to c:\.tools\.nuget and that made ILSpy happy.
