### ISSUE TITLE
Wrong Collection initializer

### ISSUE THREAD

**Issue by Solaestas** [icsharpcode/ILSpy#3091]
### Input code
```c#
public class Test
{
	public static Test Create()
	{
		var ins = new Test();
		ins.Add(2);
		ins.Add(2);
		return ins;
	}
}

public static class TestExtension
{
	public static void Add(this Test obj, int value) { }
}
```

### Erroneous output
```c#
public class Test
{
	public static Test Create()
	{
		return new Test { 2, 2 };
	}
}

public static class TestExtension
{
	public static void Add(this Test obj, int value)
	{
	}
}
```
Language version is C# 10.0 / VS2022
Collection initializer requires its type 'type' to implement System.Collections.IEnumerable.

### Details
* Product in use: VS extension
* Version in use: 8.1.1.7464

**Comment by siegfriedpammer** [comment]
This is one is funny, because we already check for exactly that:

https://github.com/icsharpcode/ILSpy/blob/d2d1c3326f4362f5853916e5e65daf2a458f35b9/ICSharpCode.Decompiler/IL/Transforms/TransformCollectionAndObjectInitializers.cs#L447-L448

**Comment by siegfriedpammer** [comment]
Cannot reproduce

![image](https://github.com/icsharpcode/ILSpy/assets/344204/af8aa4e8-95a5-4df8-8b3a-c04cbe30da76)

**Comment by Solaestas** [comment]
I just found that it only happens on Release

**Comment by Solaestas** [comment]
![image](https://github.com/icsharpcode/ILSpy/assets/49426220/a0534120-d0af-46f5-8550-3e682ac5f8d5)
