### ISSUE TITLE
Incorrect "You are not using the latest version of the tool" message.

### ISSUE THREAD

**Issue by Cazra** [icsharpcode/ILSpy#3101]
### Steps to reproduce
1. Install the current version of ilspycmd.
2. Decompile a sample with it.
3. It will successfully decompile it, but at the end of the output, it gives an erroneous message saying that I'm not using the latest version, even though I am using the latest version.

### Error message shown

```
You are not using the latest version of the tool, please update.
Latest version is '8.1.1.7464'
```

The command `ilspycmd --version` yields the output
```
ilspycmd: 8.1.1.7464
ICSharpCode.Decompiler: 8.1.1.7464
```

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* Version in use: e.g. 6.0.0 or a commit hash (use Help>About to see which ILSpy version you are using)
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by christophwille** [comment]
tbh, I don't know why that would fail. However, I switched the comparison to an explicit call to CompareTo with comparison option.
