### ISSUE TITLE
ERROR: "The system cannot find the file specified."

### ISSUE THREAD

**Issue by wally96334** [icsharpcode/ILSpy#3105]
### Steps to reproduce
1. Downloaded ILSpy
2. click Tools > ILSpy
3. ERROR: "The system cannot find the file specified."

### Error message shown
ERROR: "The system cannot find the file specified."
```
Copy and paste any error messages / relevant text and/or screenshot the incorrect behaviour.
```

### Details
* Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension
* Version in use: e.g. 6.0.0 or a commit hash (use Help>About to see which ILSpy version you are using)
* Any other relevant information to the issue, or your interest in contributing a fix.

I downloaded ILSpy for Visual Studio 2017 Community on Win 10 Pro system a moment ago. I click Tools > ILSpy, and get the following error message.

"The system cannot find the file specified."

This is a WPF application.

**Comment by wiz0u** [comment]
I had this issue on my VS2019 install.
It was trying to launch
"%APPLOCALDATA%\Microsoft\VisualStudio\16.0_35831ab1\Extensions\vnjuvjez.kyc\x64\ILSpy\ILSpy.exe"
but the x64 folder does not exist.

I duplicated the extension files into a new x64 folder and it solved the issue.

Something must be wrong with ILSpy AddIn install and x64 systems.

**Comment by christophwille** [comment]
That was the hint I needed:

https://github.com/icsharpcode/ILSpy/blob/c12187277cace22f6d919ea879360ccd981e9fea/ILSpy.AddIn.Shared/ILSpyInstance.cs#L36

Only in VS2022 we copy to the subfolder

https://github.com/icsharpcode/ILSpy/blob/c12187277cace22f6d919ea879360ccd981e9fea/ILSpy.AddIn.VS2022/ILSpy.AddIn.VS2022.csproj#L84

but not for the old extension:

https://github.com/icsharpcode/ILSpy/blob/c12187277cace22f6d919ea879360ccd981e9fea/ILSpy.AddIn/ILSpy.AddIn.csproj#L89

**Comment by christophwille** [comment]
Once the actions run https://github.com/icsharpcode/ILSpy/actions/runs/6598796525 completes (roughly half an hour) please grab the VS2017-2019 vsix artifact and give it a try. Thanks!

**Comment by wiz0u** [comment]
Tested. It works.
