### ISSUE TITLE
README.md does not explain how to checkout to the release

### ISSUE THREAD

**Issue by jasursadikov** [icsharpcode/ILSpy#3129]
I tried to build ILSpy on my Linux machine and I found out that global.json file for the latest commit does require .NET 8.0.100.
Unfortunately, checking out to the release commit has not being mentioned in the README.md neither the requirement of .NET 8.

**Comment by christophwille** [comment]
Fixed in https://github.com/icsharpcode/ILSpy/commit/bba2d26944b643451dedc929ce830eeb4b030c0d
