### ISSUE TITLE
Methods with params keyword omit the keyword on C# export

### ISSUE THREAD

**Issue by jmucchiello** [icsharpcode/ILSpy#3143]
### Steps to reproduce
1. Decompile a program with a method containing a `params` keyword
2. Export the C# to a directory
3. The method doesn't say `params` where it should

### Error message shown
None

### Details
* Product in use: ILSpy on Windows 11 Pro
* Version in use: ILSpy version 8.1.0.7455

I'm making mods for a game with Mod support. They even have a class within the game called Mod with this code emitted by ILSpy:
```
	public virtual object Call(object[] args)
	{
		return null;
	}
```
According to the developers, the method should have the params keyword:
```
	public virtual object Call(params object[] args)
	{
		return null;
	}
```

**Comment by siegfriedpammer** [comment]
Can you please share the binary? The modifier might be missing in the metadata.

**Comment by jmucchiello** [comment]
I can't share the binary. It's part of a commercially released game.

Where in ILSpy would I look for that text? And if the field you are looking for isn't there, what might cause it to be missing?

This is the IL with C# view of the method:
```
.method public hidebysig newslot virtual 
	instance object Call (
		object[] args
	) cil managed 
{
	// Method begins at RVA 0x3e10d
	// Header size: 1
	// Code size: 2 (0x2)
	.maxstack 8

	// return null;
	IL_0000: ldnull
	IL_0001: ret
} // end of method Mod::Call
```

**Comment by siegfriedpammer** [comment]
The parameter attribute should be right above the `// Method begins at` comment.

So ILSpy is displaying exactly what is there in the binary. This is not a bug, it's working as intended.

**Comment by jmucchiello** [comment]
Thanks. I'll be pointing the devs to this post.
