### ISSUE TITLE
Upload-artifact GH action v4 breaks the build

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#3145]
See https://github.com/icsharpcode/ILSpy/pull/3114#issuecomment-1868520369

We currently have more than 10 artifacts in our build. v4 of the action limits the number of artifacts to 10 and breaks our build.

Solution is probably to bundle the artifacts only used for releases into an archive.

**Comment by christophwille** [comment]
https://github.com/actions/upload-artifact/issues/470#issuecomment-1885881535 let's see if #3146 works

**Comment by christophwille** [comment]
Build is working again, merging.
