### ISSUE TITLE
Public Key Token calculation is incorrect

### ISSUE THREAD

**Issue by marklio** [icsharpcode/ILSpy#3153]
### Steps to reproduce
1. Inspect the code at https://github.com/icsharpcode/ILSpy/blob/1370b999fe4e7e6cd00f54833608a8a3a2d6254e/ICSharpCode.Decompiler/Metadata/MetadataExtensions.cs#L24-L54

### Error message shown
The implementation uses the assembly's hash algorithm id to choose which hash algorithm to use when hashing the public key. This is incorrect. public key tokens are always calculated using a SHA1 hash of the public key.

### Details
Since SHA1 is the default, and it is pretty difficult to successfully create a non-SHA1 assembly, the current implementation almost always works.

Here's a straightforward implementation from .NET itself: https://github.com/dotnet/runtime/blob/cc5f1df48e5e39a6fa5ab94ca4664aac3cc36898/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyNameHelpers.StrongName.cs#L11C1-L33C10

You can see that SHA1 is always used. Recall that assembly references can capture a public key without the ability to capture a hash algorithm, so it must be calculatable without that. Also, publishers must be able to change the hash algorithm in future releases without changing an assembly's identity.

**Comment by siegfriedpammer** [comment]
Thank you for reporting this inconsistency. Note that there are two separate APIs that calculate hashes. The other API was always using SHA1. I just misinterpreted the assembly metadata fields when implementing the System.Reflection.Metadata-based API.
