### ISSUE TITLE
Nullable string doesn't display as nullable

### ISSUE THREAD

**Issue by IamIC** [icsharpcode/ILSpy#3158]
### Steps to reproduce

public string? Test(string value)
{
	if (value.Length == 0) return null;

	string? newVal = value + "!";

	if (newVal == null) return null;

	return (newVal.Length < 10) ? newVal : null;
}

### Error message shown
None. `string? newVal` decompiles to `string newVal` even though the [Use C# 8.0 nullable reference types syntax option] is set.

### Details
ILSpy version 8.2.0.7535
.NET version 6.0.26-servicing.23605.8+dc45e96840243b203b13e61952230e225d2aac52

**Comment by siegfriedpammer** [comment]
This is expected, because the nullability annotations for local variables are not preserved in the metadata.

ILSpy tries to reconstruct them from how a variable is used. However in your case, the variable `value` is already non-null, so we can assume `value` is not null as well.
