### ISSUE TITLE
ILSpy incorrectly disassembles System.Buffers.Binary.BinaryPrimitives to empty branches

### ISSUE THREAD

**Issue by daiplusplus** [icsharpcode/ILSpy#3166]
### Input code

> Please provide the input that failed to decompile.

* Assembly: `System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e` (.NET 7 SDK 7.0.13)
    * Filesystem location: `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.13\System.Private.CoreLib.dll`
* Type: `System.Buffers.Binary.BinaryPrimitives`
* Method: `ReadInt32BigEndian`
* IL below
* [Raw C# source on GitHub](https://github.com/dotnet/runtime/blob/3f73a2f186e08c905aba441ea5545295ca261730/src/libraries/System.Private.CoreLib/src/System/Buffers/Binary/ReaderBigEndian.cs#L60) (link points to the 7.0.13 snapshot tag)

```
.method public hidebysig static 
	int32 ReadInt32BigEndian (
		valuetype System.ReadOnlySpan`1<uint8> source
	) cil managed aggressiveinlining 
{
	// Method begins at RVA 0x64c4fc
	// Header size: 1
	// Code size: 19 (0x13)
	.maxstack 8

	IL_0000: ldsfld bool System.BitConverter::IsLittleEndian
	IL_0005: brtrue.s IL_0007

	IL_0007: ldarg.0
	IL_0008: call !!0 System.Runtime.InteropServices.MemoryMarshal::Read<int32>(valuetype System.ReadOnlySpan`1<uint8>)
	IL_000d: call int32 System.Buffers.Binary.BinaryPrimitives::ReverseEndianness(int32)
	IL_0012: ret
} // end of method BinaryPrimitives::ReadInt32BigEndian
```

The instruction at `IL_0005: brtrue.s IL_0007` doesn't seem right to me... but I'm a bit rusty on my IL right now.

ILSpy disassembles this to:

```
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int ReadInt32BigEndian(ReadOnlySpan<byte> source)
{
	if (!BitConverter.IsLittleEndian)
	{
	}
	return BinaryPrimitives.ReverseEndianness(MemoryMarshal.Read<int>(source));
}
```

[The actual C# source is](https://github.com/dotnet/runtime/blob/3f73a2f186e08c905aba441ea5545295ca261730/src/libraries/System.Private.CoreLib/src/System/Buffers/Binary/ReaderBigEndian.cs#L60):

```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int ReadInt32BigEndian(ReadOnlySpan<byte> source)
        {
            return BitConverter.IsLittleEndian ?
                ReverseEndianness(MemoryMarshal.Read<int>(source)) :
                MemoryMarshal.Read<int>(source);
        }
```

### Details
> Product in use: e.g. ILSpy / ICSharpCode.Decompiler nuget package / VS extension

* ILSpy version 8.2.0.7535
* .NET version 6.0.27-servicing.24069.12+80de56dadb3864aec7e8edd3ae32a23aeda08285

**Comment by siegfriedpammer** [comment]
If you add the instruction bytes to the IL output, (The setting can be found in Settings > Display > Decompilation view options > last checkbox). You will see that the bytes of the instruction are 0xD200, where 0xD2 is the opcode for `brtrue.s`:

![image](https://github.com/icsharpcode/ILSpy/assets/344204/fa2fe8bc-cd7d-469e-b859-0f3411f61dfa)
Taken from ECMA-335, 6th edition, June 2012, page 297

and 0x00 is the **relative** offset to jump to, which basically is "don't jump at all".

Not sure what the C# compiler is trying to do, but it seems pointless. I don't think ILSpy is at fault here. Probably some branch optimization gone wrong in the compiler.

**Comment by siegfriedpammer** [comment]
`Converter.IsLittleEndian` is marked with an `IntrinsicAttribute`, so it seems there is some special going on. May I ask you to open a discussion on the dotnet/runtime repo?

**Comment by siegfriedpammer** [comment]
Opened a discussion in the Roslyn repo: https://github.com/dotnet/roslyn/discussions/74892

**Comment by daiplusplus** [comment]
> May I ask you to open a discussion on the dotnet/runtime repo?

Hey, sorry I didn't follow-up on this - I'll admit it's because I wasn't sure what I should have even asked them about - and then I simply forgot about this thread entirely, sorry 😔

**Comment by siegfriedpammer** [comment]
No problem, I am just curious myself and I figured that roslyn might be the better place to ask, since it's probably csc that produces the weird code.

**Comment by huoyaoyuan** [comment]
I believe it's caused by ILLink.

The System.Private.CoreLib assembly is post-processed by ILLink for default. There is a descriptor for endianness:

https://github.com/dotnet/runtime/blob/5fd3f22b98cb0d126e4f6328f5a0bf922a532f69/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.LittleEndian.xml#L4

Then ILLink removes the code for big endian, but doesn't remove the endianness check and left an empty branch.
