### ISSUE TITLE
Debugger + Environment.CommandLine

### ISSUE THREAD

**Issue by boombuler** [icsharpcode/ILSpy#317]
If you use Environment.CommandLine within the debugged application, the executable path is missing.
This can be fixed by including filename in the lpCommandLine parameter at Debugger.Process.CreateProcess.
Sorry for not providing a pull request but i have no time to fork now.

**Comment by siegfriedpammer** [comment]
The debugger feature is no longer part of ILSpy and likely will not come back like this.
