### ISSUE TITLE
Can't open the .NET bundle file.

### ISSUE THREAD

**Issue by wwh1004** [icsharpcode/ILSpy#3197]
### Steps to reproduce
1. Open a .NET bundle
2. Fails

### Details
LoadedAssembly.LoadAsync doesn't catch exceptions when thrown in "result = await loader.Load(fileName, stream, settings).ConfigureAwait(false);". If open an entry in bundled file, FileNotFoundException will be thrown and breaks logic of LoadAsync.

![image](https://github.com/icsharpcode/ILSpy/assets/27536652/1fd4f93b-b3c1-4e95-9eb3-97a9ffa3e64c)
![image](https://github.com/icsharpcode/ILSpy/assets/27536652/547dc8f7-8f19-4928-831c-4df489b14e6b)

**Comment by wwh1004** [comment]
It seems that a logic to prioritize bundled entries should be added. If a file with the same name exists in the ILSpy directory, this file will be loaded first instead of loading the bundled entry.

**Comment by workgroupengineering** [comment]
The same issue exists for nuget packages

**Comment by workgroupengineering** [comment]
If i revert pr #3191 commit id 65e30c0 work

**Comment by wwh1004** [comment]
@siegfriedpammer My github account was suspended two weeks ago, and has been reinstated now.
