### ISSUE TITLE
hi i have problem with gameaasembly.dll

### ISSUE THREAD

**Issue by nemiskr** [icsharpcode/ILSpy#3210]
example script

private static void addAchievement(string key, bool generateToken)
{
if (!generateToken)
{
SaveManager.AddInt(key, 1);
}
int num = 0;
int num2 = UnityEngine.Random.Range(0, generateToken ? 1 : 0);
string str;
string text = "" + str;
num++;
AchievementManager achievementManager = AchievementManager.instance;
int <>int v = 1__; state;
AchievementManager.d__22 d__ = new AchievementManager.d__22(<>1__state);
<>1__state = 0;
d__.key = key;
d__.token = text;
Coroutine coroutine = achievementManager.StartCoroutine(d__);
SaveManager.AddString(key, text);
SaveManager.SaveFileAsync();
}

have this error

error CS1519: Invalid token '<' in class, struct, or interface member declaration

what do you mean?

**Comment by siegfriedpammer** [comment]
Can you please provide the binary/assembly in question? Thanks!

**Comment by christophwille** [comment]
No feedback, closing.
