### ISSUE TITLE
Program Compatibility Assistant

### ISSUE THREAD

**Issue by modz2014** [icsharpcode/ILSpy#3224]
![image](https://github.com/icsharpcode/ILSpy/assets/25472227/f315d486-52aa-450e-a67a-fbc049772a95)
this keeps poping up every time i open and close on windows 11

**Comment by christophwille** [comment]
Which version of ILSpy?

**Comment by modz2014** [comment]
@christophwille i just downloaded the latest one  ILSpy version 9.0.0.7660-preview2

**Comment by christophwille** [comment]
That is strange - I am developing on Windows 11 and have never seen this.

**Comment by modz2014** [comment]
@christophwille ok I'm not sure either but it always happens

**Comment by christophwille** [comment]
Closing until someone has the same problem (and we have a chance for a repro)
