### ISSUE TITLE
Load assemblies that were loaded in the last instance doesnt work

### ISSUE THREAD

**Issue by GazziFX** [icsharpcode/ILSpy#3241]
### Steps to reproduce
1. Load some assemblies
2. Exit ILSpy
3. Open it again

Instead of previous assembly list it loads default NET8 assemblies

### Details
* Product in use: ILSpy
* Version in use: 9.0.0.7660-preview2

**Comment by christophwille** [comment]
You mean you are selecting an assembly list from the dropdown in the toolbar, and on close/reopen, it reverts to something else? Or do you mean that changes to the currently selected assembly list are not persisted on close/reopen? 

Given that the Avalonia folks just released an XPF build for MacOS, we are talking here about our Windows version?

**Comment by christophwille** [comment]
No feedback, closing.
