### ISSUE TITLE
Choppy scrolling when scrolling fast after smooth scrolling introduction

### ISSUE THREAD

**Issue by ElektroKill** [icsharpcode/ILSpy#3246]
### Steps to reproduce
1. Open ILSpy compiled from master (https://github.com/icsharpcode/ILSpy/commit/d1c7a51a1d823983afe93bae1d0c70a6912cf3da)
2. Decopile a large class like `System.Array` from `System.Private.CoreLib`
3. Scroll fast on the scroll wheel
4. Observe weird choppiness and snapping when scrolling

See video below which demonstrates the behavior:
https://www.youtube.com/watch?v=py0OHKgWccw

**Comment by christophwille** [comment]
@tom-englert @ltrzesniewski ideas?

**Comment by ltrzesniewski** [comment]
I can take a look later, unless @tom-englert or @SlimeNull would like to have a go at this first.

**Comment by tom-englert** [comment]
I'll have a look, I guess it's the easing function:
  `  private static readonly IEasingFunction _scrollingAnimationEase = new CubicEase { EasingMode = EasingMode.EaseOut };`
