### ISSUE TITLE
Weird cast

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#3253]
Is the same issue as https://github.com/icsharpcode/ILSpy/issues/3011?

![image](https://github.com/user-attachments/assets/cb1e09b4-b4b2-4e73-aef2-481255975c55)

**Comment by siegfriedpammer** [comment]
Hard to say without taking a look at the IL...

**Comment by CreateAndInject** [comment]
> Hard to say without taking a look at the IL...

@siegfriedpammer Check it : [test.zip](https://github.com/user-attachments/files/16488479/test.zip)

**Comment by siegfriedpammer** [comment]
![image](https://github.com/user-attachments/assets/3a35b624-d3c4-4b84-8e90-0a5416840e8f)

Yes, in this assembly the code is trying to assign an array of type System.Byte from mscorlib v2 to a variable of type array of type System.Byte from mscorlib v4. This causes these weird casts.

**Comment by CreateAndInject** [comment]
![image](https://github.com/user-attachments/assets/8f2ac6b4-bd00-49e3-a2ff-b2abbad94096)
![image](https://github.com/user-attachments/assets/f7feffcf-b7aa-45a2-ab07-af5c3205d41f)

How about those `Unsafe.As`? Is also the same issue?

**Comment by siegfriedpammer** [comment]
@dgrunwald do you think it would make sense to do "unification" of well-known/special types in the type-system?

**Comment by dgrunwald** [comment]
I think this makes more sense as a job for the assembly resolver -- there shouldn't be multiple mscorlibs in the same compilation.
If we let both assemblyrefs resolve to the newer mscorlib version, then the typerefs will also resolve to the same type and the casts are avoided.
