### ISSUE TITLE
Quicksearch box font cut below

### ISSUE THREAD

**Issue by AGlezB** [icsharpcode/ILSpy#3256]
### Steps to reproduce
1. Open a text/code window.
2. Open quick search (CRTL+F).
3. Type a text.

### Issue
The vertical space in the TextBox is insufficient so text is cut below:

![image](https://github.com/user-attachments/assets/8406fcad-9d8f-46fc-a8ff-eaee6f7eac35)

This is what it looks like at different zoom levels changed using CTRL+MScrollWheel:

![image](https://github.com/user-attachments/assets/be0bddf7-2c5e-4d68-901e-b083372c93c4)

The text in the images is `AAAbbbppp` and as you can see it isn't completely readable with characters like `g`, `j` and `p` to the point where `p` looks more like `n` at some zoom levels. `gggjjjpppnnn` looks like this:

![image](https://github.com/user-attachments/assets/c7b22179-b634-46dc-8c6b-8ae85b17fa2b)

### Details
Tested in Windows 10 at 100% UI scaling.
Tested in latest release and preview versions.

ILSpy version 8.2.0.7535
.NET version 6.0.32-servicing.24314.7+e77011b31a3e5c47d931248a64b47f9b2d47853d

ILSpy version 9.0.0.7660-preview2
.NET version 8.0.6+3b8b000a0e115700b18265d8ec8c6307056dc94d

**Comment by christophwille** [comment]
Doesn't seem to happen on my 125% Windows 11 machine.

**Comment by siegfriedpammer** [comment]
![image](https://github.com/user-attachments/assets/5b9a5b0d-80f9-4f08-b34e-1b8de02efce4)

Windows 10, 2560x1440 @ 100%, tested both light and dark mode... no difference

**Comment by AGlezB** [comment]
Might be something with the font settings
![image](https://github.com/user-attachments/assets/75367c8a-ca94-4aad-bf1c-3a2db70b68d6)

**Comment by christophwille** [comment]
Yes, that textbox seems to be optimized for 10pt. Can confirm with testing 15pt.

**Comment by AGlezB** [comment]
It can be fixed the easy by leaving the font fixed at 10 for the quicksearch and ignoring the settings. The size/font of the search box doesn't change with zoom levels so both would behave in the same way. Fixing it the hard way would involve more complex size calculations.

I'd prefer the easy way because nobody noticed or reported this issue before and that means they are either not using quicksearch or not changing the font size in the settings.

**Comment by AGlezB** [comment]
@siegfriedpammer +1
