### ISSUE TITLE
It is not possible to use NRT attributes in the ILSpy project

### ISSUE THREAD

**Issue by tom-englert** [icsharpcode/ILSpy#3258]
### Steps to reproduce
Try to use e.g. `[NotNullWhen(true)]` attribute in ILSpy source code

### Error message shown
```
CS0433	The type 'NotNullWhenAttribute' exists in both 'ICSharpCode.Decompiler, Version=9.0.0.7716, Culture=neutral, PublicKeyToken=d4bfe873e7598c49' and 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

### Details
The attributes are introduced by `TunnelVisionLabs.ReferenceAssemblyAnnotator`, which is generally fine. 
However the `ICSharpCode.Decompiler` project exposes it's internals to the `ILSpy `project, so `ILSpy` now can see two versions of the attributes:
```
#if DEBUG
[assembly: InternalsVisibleTo("ILSpy, PublicKey=00240000048000009400000006020000002400005253413100040000010001004dcf3979c4e902efa4dd2163a039701ed5822e6f1134d77737296abbb97bf0803083cfb2117b4f5446a217782f5c7c634f9fe1fc60b4c11d62c5b3d33545036706296d31903ddcf750875db38a8ac379512f51620bb948c94d0831125fbc5fe63707cbb93f48c1459c4d1749eb7ac5e681a2f0d6d7c60fa527a3c0b8f92b02bf")]
#endif
```

**Comment by tom-englert** [comment]
A simple fix would be to move the code that requires the access to decompiler internals to the test plugin

**Comment by siegfriedpammer** [comment]
One example would be `ShowCFGContextMenuEntry` and I am a bit reluctant to move utilities that are actively used to debug algorithms in the decompiler engine to something called "TestPlugin"... but I guess there is no better alternative...

**Comment by tom-englert** [comment]
If you're concerned about the naming "TestPlugin", maybe just introduce a "Debug.Plugin"?

**Comment by siegfriedpammer** [comment]
tbh I would really like to get rid of the conditional DEBUG-only IVT attribute completely, because that leads to surprises when you change something and only the release build fails in CI (which I usually do not test locally)

I guess we could move `GraphVizGraph` and ControlFlowNode.ExportGraph to ILSpy? @dgrunwald
