### ISSUE TITLE
FR: IL view on the GUI

### ISSUE THREAD

**Issue by RedStoneMatt** [icsharpcode/ILSpy#3259]
**Is your feature request related to a problem? Please describe.**

I am trying to decompile a heavily obfuscated program, which leads to some functions not being able to be decompiled properly.

For this reason, I would like to directly look at the IL of those functions, but there seemingly is no way to do this on the ILSpy GUI tool.

**Describe the solution you'd like**

When right clicking a decompiled function (no matter if the decompilation failed or not), it'd be good to have a "Show IL" options to see the IL behind the function.

If the decompilation succeeded, it'd be nice to be able to link the cursor from IL to the decomp so putting your cursor on a statement of the decompilation view would place it at the equivalent instructions in the IL view, and vice versa.

**Comment by ltrzesniewski** [comment]
There's a language option in the toolbar:

![image](https://github.com/user-attachments/assets/fed228be-8788-4de7-b23f-d72b808f0e33)

**Comment by siegfriedpammer** [comment]
I think your second feature request is already covered by the "IL with C#" language option.
