### ISSUE TITLE
Incorrect type inference for ternary operators

### ISSUE THREAD

**Issue by kg** [icsharpcode/ILSpy#326]
With the following test case:

``` csharp
using System;

class Base {
}

class A : Base {
}

class B : Base {
}

public static class Program {
    public static void Main (string[] args) {
        var flag = true;
        var a = new A();
        var b = new B();
        Console.WriteLine(flag ? a as Base : b as Base);
        Console.WriteLine(!flag ? a as Base : b as Base);
    }
}
```

The inferred and expected types in the ILAst for the nodes within the ternary operator are wrong. The ternary node generated for it looks like this:

```
ternaryop:A[exp:object](ldloc:bool(flag), ldloc:A(a), ldloc:B[exp:A](b))
```

As you can see, the inferred type for the ternary operation is wrong, and the expected type for the second bit (ldloc b) is wrong.

**Comment by dgrunwald** [comment]
newdecompiler now generates:

    Console.WriteLine(flag ? ((object)new A()) : ((object)new B()));

If the target method expects type `Base`, the operands are still cast to `object`, and then the whole ternary expression is cast back to `Base`. Which is not wrong, but also not pretty, so I'm keeping this bug open.
