### ISSUE TITLE
Help -> About is broken

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#3281]
### Steps to reproduce
1.  menu Help -> about
2. 
3. 

### Error message shown

```
opens up empty tab named as  "New Tab"
```

### Details
* ILSpy version 9.0.0.7777-preview2+bf2cf936e143384221d3277ac2a2960c7e2f0005
* .NET version 8.0.8+08338fcaa5c9b9a8190abb99222fed12aaba956c

**Comment by christophwille** [comment]
@tom-englert related to recent WPF changes?

**Comment by greenozon** [comment]
This is also new issue introduced recently I guess - just clicking in the left-hand tree view on different items

![image](https://github.com/user-attachments/assets/28ba7ae6-a0af-4754-9779-b7c8a6d5891f)

**Comment by greenozon** [comment]
once this issue raises, it literally happens on EVERY single click in the left tree

**Comment by tom-englert** [comment]
I'll have a look later

**Comment by siegfriedpammer** [comment]
> the commit hash changes for about page?

I highly doubt that changing the length of a compile-time string constant has such an impact.

**Comment by tom-englert** [comment]
The about box is fixed, however the described crash is not reproducible

**Comment by greenozon** [comment]
Thanks! then that's another thing worth a separate issue

**Comment by christophwille** [comment]
@greenozon please keep putting the new UI through its paces!
