### ISSUE TITLE
Focus always moving to the assembly tree view when changing tabs

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#3284]
Using the latest released version the focus behavior was as shown in the following gif:

![focus1](https://github.com/user-attachments/assets/38d2a2f9-49f9-46df-ae82-455378dbb607)

Using latest master the behavior is as follows:

![focus2](https://github.com/user-attachments/assets/44de26db-7e1d-46e1-8535-9b3e69213d0d)

I have yet to determine the change that causes this deviation. For me this is only a minor distraction, because switching between tabs and tree nodes makes the screen flicker a bit more than usual. However, as [we have seen previously](https://github.com/icsharpcode/ILSpy/issues/2577), there are people who depend on accessibility software to use ILSpy, and I can image that this change causes some frustration, because the focus move is unanticipated.

While creating the above screen recordings, I noticed that the label of the assembly tree view content (previously labelled `Assemblies`) is now labelled `ILSpy <version> - <assembly list name>`, which was previously in the window title, not sure if this has some negative impact on accessibility...

/cc @tom-englert

**Comment by siegfriedpammer** [comment]
Note: looking at the recordings, it seems to me that the new behavior is that switching between tabs triggers a refresh/decompilation run.

**Comment by tom-englert** [comment]
I'll have a look on this
