### ISSUE TITLE
Navigation failed because the target is hidden even when show all types and members

### ISSUE THREAD

**Issue by sgkoishi** [icsharpcode/ILSpy#3289]
### Steps to reproduce
Search for a constant string in the analyzer and double click to open the method.

### Error message shown
```
Navigation failed because the target is hidden or a
compiler-generated class. \n
Please disable all filters that might hide the items (i.e. activate "View >
Show internal types and members") and try again.
```
The settings doesn't got applied until `Reload all assemblies`, and public members are not shown no matter which option selected, even after reload. Same for the `Assemblies` window.

### Details
* ILSpy nightly
* version 9.0.0.7780-preview2+f10514743887122266bfecb3d168a4b40c0d6e06

The release (9.0.0.7660-preview2) works fine. The 7756 (58e993d71) partially works: it doesn't respect the settings globally, but able to show the members after I click `Show all types and members` again, per assembly. The 7780 (f10514743) is not following this setting completely and refuse to show even public members.

**Comment by christophwille** [comment]
@tom-englert @siegfriedpammer partially related to WPF changes?

**Comment by sgkoishi** [comment]
The problem is that even public members are not shown, without switching language from C# to IL (and from IL to C#). There's no `ICSharpCode` in ILSpy 🤔 
![ilspy#3289](https://github.com/user-attachments/assets/b5186b0a-fa60-424e-96e8-f07d6f076bf8)
