### ISSUE TITLE
feature request: edit method

### ISSUE THREAD

**Issue by nes-girl** [icsharpcode/ILSpy#3306]
**Is your feature request related to a problem? Please describe.**
There exists dnSpy which can directly edit methods
https://github.com/dnSpy/dnSpy

**Describe the solution you'd like**
I would like this feature in ILSpy because dnSpy is abandoned.
The code could be used from dnSpy github

**Additional context**
Screenshot: right click a method to see these (and more) options

![afbeelding](https://github.com/user-attachments/assets/447f28ec-a1fb-4edc-a803-a0d8489efe39)

**Comment by christophwille** [comment]
There is https://github.com/dnSpyEx/dnSpy/

And no, Editing won't come to ILSpy.

**Comment by nes-girl** [comment]
Why not?
