### ISSUE TITLE
VS 2022 Add-In Reusing Existing ILSpy Processes instead of spawning a new one

### ISSUE THREAD

**Issue by tinmanjk** [icsharpcode/ILSpy#3311]
### Steps to reproduce - [Latest 8.2 release]
1. Have ILSpy using multiple instances in the options
2. Have a separate ILSpy (portable) open and inspecting DLL X
3. Right click in *.cs file in VS 2022 and clicking Open in ILSpy
4. The AddIn will open a new ILSpy instance but reuse the existing one for displaying the *.cs code and have the new one be just blank

It would be better to not touch existing running processes for the VS 2022 AddIn.

**Comment by christophwille** [comment]
Does the 9.x also expose that behavior? (resolving running instances has been changed entirely)
