### ISSUE TITLE
Clicking does not select in Assemblies pane when it doesn't have focus

### ISSUE THREAD

**Issue by carlreinke** [icsharpcode/ILSpy#3333]
### Steps to reproduce
1. Select an item in the Assemblies pane.
2. Click on the code pane.
3. Click on another item in the Assemblies pane.

### Expected behavior
The item that was clicked in step 3 is selected.  (This is how it used to work, and it's how the Analyze pane still does work.)

### Actual behavior
The Assemblies pane gets focus, but the selection does not change.  You have to click on the item again to select it.

### Details
* Product in use: ILSpy
* Version in use: 9.0.0.7833-preview3+3746337d376584ac6dec7d8672dbdd034046d8c9
* OS: Windows 10.0.19045 Build 19045

**Comment by siegfriedpammer** [comment]
I was able to reproduce this /cc @tom-englert can you please take a look? Thanks!
