### ISSUE TITLE
Cannot open a DLL produced with .NET 10 Alpha using ILSpy 8.2.0.7535

### ISSUE THREAD

**Issue by carlossanlop** [icsharpcode/ILSpy#3349]
I created a simple console app that targets .NET 10 alpha ([latest available nightly](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md)) It compiled without issues. (I shared the csproj and cs code at the end for a repro).

If I try to open the produced assembly, I get an error using this ILSpy version:
```
ILSpy version 8.2.0.7535
.NET version 6.0.36-servicing.24514.21+f1dd57165bfd91875761329ac3a8b17f6606ad18
        ✅You are using the latest release.
```

Note that the sidebar is able to show the API tree, but if I try to expand a type, I get this callstack:

![Image](https://github.com/user-attachments/assets/f7620c62-4134-4a89-8d39-8dfec6ec8ee6)

If I change the language to IL, it shows a bunch of System.Reflection attributes for the assembly:
![Image](https://github.com/user-attachments/assets/1570f661-9360-468e-8f48-f607325f4ecd)

But a couple seconds later this dialog showed up:
![Image](https://github.com/user-attachments/assets/c671990b-2633-49e9-ac58-01904abee9bb)

Project code:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

```cs
using System;

namespace MyNamespace.MySubNamespace;

[AttributeUsage(AttributeTargets.Class)]
public class MyUnchangedAttribute : Attribute
{
    public MyUnchangedAttribute() { }
}
```

**Comment by carlossanlop** [comment]
My colleague @ericstj found the root cause:

https://github.com/icsharpcode/ILSpy/blob/e652490cce4a3f5ec54b9c858807418f02e39ae0/ICSharpCode.Decompiler/Metadata/UniversalAssemblyResolver.cs#L196-L197

**Comment by siegfriedpammer** [comment]
Sorry for the bug, who would've thought that .NET reaches version 10 😉... this is so embarrassing. Thanks for reporting!

**Comment by carlossanlop** [comment]
No worries! We caught it early, fortunately. .NET has grown so fast!

**Comment by ericstj** [comment]
You might consider replacing this parsing with https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.frameworkname?view=net-9.0 or if you keep the parsing, just create a new version if it doesn't have enough parts. That way you don't muck with the string.

**Comment by ericstj** [comment]
Thank you for the quick fix!
