### ISSUE TITLE
Incorrect generic parameter for invocation of constructor on generic type

### ISSUE THREAD

**Issue by kg** [icsharpcode/ILSpy#343]
Hi,

It seems like ILAst is generating incorrect generic parameters for invocations of constructors on generic types. This doesn't seem to negatively affect the generated C# from decompilation but it seems to be semantically wrong - the MethodReference for the constructor uses generic method parameter references (like !!0) instead of type parameter references (T).

For example, this function:

``` csharp
    public static List<string> MyToList1(IEnumerable<string> source)
    {
        return new List<string>(source);
    }
```

Produces this IL:

``` msil
.method public hidebysig static 
    class [mscorlib]System.Collections.Generic.List`1<string> MyToList1 (
        class [mscorlib]System.Collections.Generic.IEnumerable`1<string> source
    ) cil managed 
{
    // Method begins at RVA 0x2050
    // Code size 12 (0xc)
    .maxstack 2
    .locals init (
        [0] class [mscorlib]System.Collections.Generic.List`1<string> CS$1$0000
    )

    IL_0000: nop
    IL_0001: ldarg.0
    IL_0002: newobj instance void class [mscorlib]System.Collections.Generic.List`1<string>::.ctor(class [mscorlib]System.Collections.Generic.IEnumerable`1<!0>)
    IL_0007: stloc.0
    IL_0008: br.s IL_000a

    IL_000a: ldloc.0
    IL_000b: ret
} // end of method Program::MyToList1
```

However, if you inspect the actual newobj ILExpression, the Operand is:

``` msil
{System.Void System.Collections.Generic.List`1<System.String>::.ctor(System.Collections.Generic.IEnumerable`1<!0>)}
```

For comparison, the actual signature of that constructor according to ILSpy is:

``` msil
.method public hidebysig specialname rtspecialname 
    instance void .ctor (
        class System.Collections.Generic.IEnumerable`1<!T> collection
    ) cil managed 
{
```

As I understand it, the !0 form of a generic parameter refers to a generic method's generic parameters - in this case, neither the calling method or the constructor are generic, so they cannot have any generic method parameters. I would expect the parameter to be !T or T here.

Is this a bug in ILSpy or am I just missing a detail about how MSIL works? In my case, I'm using the Operand from the newobj to identify which particular constructor overload is being invoked, and this discrepancy makes it impossible for me to locate the actual overload at work here. Is !0 a positional reference to something else in the expression?

**Comment by dgrunwald** [comment]
I don't think this is still a problem with the NR-based type system; all type references should be resolved in a context where the true type parameter is available.
