### ISSUE TITLE
decompile bug

### ISSUE THREAD

**Issue by yunfei9731** [icsharpcode/ILSpy#349]
on de decompiled code :

```
        foreach (FieldBuilder fieldBuilder in list)
        {
            FieldBuilder fieldBuilder;
            if (fieldBuilder.FieldType == typeof(string))
            {
                iLGenerator3.Emit(OpCodes.Ldarg_0);
                iLGenerator3.Emit(OpCodes.Ldstr, "");
                iLGenerator3.Emit(OpCodes.Stfld, fieldBuilder);
            }
        }
```

the vs error message:
Error   21  A local variable named 'fieldBuilder' cannot be declared in this scope because it would give a different meaning to 'fieldBuilder', which is already used in a 'parent or current' scope to denote something else   E:\aaa.cs   68

**Comment by siegfriedpammer** [comment]
Closing due to missing feedback after 5 years. Also, this is likely fixed in the upcoming new decompiler.
