### ISSUE TITLE
Add support for decompiling coalesce operator

### ISSUE THREAD

**Issue by litera** [icsharpcode/ILSpy#352]
When you do something like:

```
return somevar ?? (somevar = get());
```

then ILSpy decompiles this as a series of statements (this is semi-pseudo code because types aren't provided):

```
[typeofsomevar] arg_0;
if ((arg_0 = somevar) == null)
{
    arg_0 = (somevar = get());
}
return arg_0;
```

Would be nice if ILSpy decompiled this back to coalesce and since it's smart enough to decompile lambda expressions I don't see any particular reasons why `coalesce` couldn't be decompiled as well.

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
