### ISSUE TITLE
Odd tooltip for volatile fields (and other tooltip bugs)

### ISSUE THREAD

**Issue by Allon-Guralnek** [icsharpcode/ILSpy#355]
I'm looking at the decompilation of the `Value` property of `Lazy<T>`, and when I hover the mouse over the m_boxed field in the code area, I get the following tooltip:

> System.Object modreq(System.Runtime.CompilerServices.IsVolatile) System.Lazy`1<T>::m_boxed

The obvious bug is the `modreq(...)`, where it should simply say `volatile`, but there are other bugs visible:
- `System.Object` should simply be `object` like in the decompiled code.
- `volatile` should come before `object` like in the decompiled code.
- `System.Lazy`1<T>` shouldn't have the ``1` notation.

The correct tooltip should therefore be:

> volatile object System.Lazy<T>::m_boxed

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
