### ISSUE TITLE
Separate automatically-loaded assemblies from manually loaded assemblies

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/ILSpy#358]
ILSpy should not store automatically loaded assemblies in the assembly list, so that they do not get loaded immediately on the next start of ILSpy (they'll be loaded on demand instead).

The assemblies should be shown in a different color in the tree view, and should be sorted to the bottom (any manually loaded assembly should be inserted above the automatically loaded ones).

**Comment by EdHarvey** [comment]
I've implemented a minimal solution for this feature.

There probably needs to be a discussion on the visual/operational aspects of this feature...
For example, 
* I'm not 100% happy with the blue highlighting of AutoLoaded assembles (but it was the best I could come up with at the time!)
* Is the *'Add To Main List'* context menu command useful? Should it be renamed?

At present, the list does not automatically enforce the manual/auto-load divide - I will investigate how to do that, but at first glace it looks like it will be messy/painful to implement given the current internal design :worried:

**Comment by whut** [comment]
Looks like this is implemented now in ILSpy version 2.3.1.1855!

I believe this behavior should be optional (IMO opt-in, not opt-out), as I initially considered it a bug: "why does ILSpy forgets to load some assemblies after restart"  :confused: 

I also believed that the blue highlight is just a indicator of newly loaded assembly, not of "this assembly will disappear after ILSpy close". Also the "Add to Main List" does not convey any meaning - before finding this issue I had no clue what it does.
