### ISSUE TITLE
Cannot navigate to field type on click

### ISSUE THREAD

**Issue by 3-1415926** [icsharpcode/ILSpy#361]
For example, go to System.Threading.Tasks.Task.t_stackGuard and try to navigate to StackGuard by clicking it in the disassembly (С#) window. Non-static and non-thread-static fields have this issue as well, e.g. System.Threading.Tasks.ParallelForReplicaTask.m_handedOverChildReplica

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler (which just landed on the master branch).
