### ISSUE TITLE
No Horizontal ScrollBar in non-Maximized Mode

### ISSUE THREAD

**Issue by DJDoena** [icsharpcode/ILSpy#370]
When running ILSpy in normal window mode, there's no horizontal scrollbar, even when the text is longer, see:

http://imageshack.us/a/img707/261/normala.png

http://imageshack.us/a/img233/1875/maximized.png

ILSpy version 2.1.0.1603

**Comment by siegfriedpammer** [comment]
Cannot reproduce this.
