### ISSUE TITLE
ArgumentException: an item with the same key has already been added

### ISSUE THREAD

**Issue by mausch** [icsharpcode/ILSpy#372]
1. Download https://nuget.org/packages/QuartzNetWebConsole/0.2.0
2. Open QuartzNetWebConsole.dll contained in that package with ILSpy 2.1.0.1603
3. Navigate to the QuartzNetWebConsole.Views namespace
4. Open the Views class. When doing this, it throws an "ArgumentException: an item with the same key has already been added"

![Screenshot](http://s12.postimage.org/vbxrccqvh/ilspy_crash.png)

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
