### ISSUE TITLE
Unexpected character '$' while trying to rebuild decompiled code

### ISSUE THREAD

**Issue by senglory** [icsharpcode/ILSpy#376]
ILSpy version 2.1.0.1603, trying to decompile U2U.SharePoint.CAML.DLL from www.u2u.be/res/tools/camlquerybuilder.aspx. Decompilation completes successfully, but when I try to rebuild the code in VS 2010 it throws the following error:

DECOMPILATION\U2U\U2U-Decompiled\U2U.SharePoint.CAML\Builder.cs(1447,81): error CS1056: Unexpected character '$'

Here's the shit it complains about:

if (<PrivateImplementationDetails>{1B743747-93B8-4A24-8F3F-07245468540B}.$$method0x60000c6-1 == null)

**Comment by siegfriedpammer** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
