### ISSUE TITLE
Need Assistance to alter Getter Setter output

### ISSUE THREAD

**Issue by JLarue** [icsharpcode/ILSpy#380]
ILSpy is amazing! I am hoping this is not a big deal but I am hoping someone can point me to the area in code that I can change so I generate a different accessor output from the default.  The current output decompile generates the following.

var x = SomeType.get_SomeProperty();

... I would like to change that to be the following;

var x = SomeType.SomeProperty;

as well the current setter generates like so ...

SomeType.set_SomeProperty(valueToSet);

and I would like to change output to be this ...

SomeType.SomeProperty = valueToSet;

Currently I am looking at literally 1000's of property modifications that I have to make manually and its killing me! 

Any help is greatly appreciated!

Cheers

**Comment by siegfriedpammer** [comment]
See #849
