### ISSUE TITLE
Weird expected type in ILAst for equality comparisons

### ISSUE THREAD

**Issue by kg** [icsharpcode/ILSpy#381]
Certain equality comparisons seem to produce incorrect expected type information. Somehow this doesn't affect the C# generated by the decompiler, but everything I know about ILAST's data model suggests that this is wrong.

``` csharp
using System;

public interface I {}

public class A : I {}

public class B : I {
  public void X(I i) {
    if (this == i) 
      Console.WriteLine("equal");
    else
      Console.WriteLine("not equal");
  }
}

public static class Program {

  public static void Main () {
    var b = new B();
    b.X(new A());
  } 
}
```

Decompiles fine, but the method X produces this ilast:

``` ilast
if (logicnot:bool(cne:bool(ldloc:B(this), ldloc:I[exp:B](i)))) {
    call:void(Console::WriteLine, ldstr:string("equal"))
} else {
    call:void(Console::WriteLine, ldstr:string("not equal"))
}
```

The expected type of 'B' for 'i' seems totally spurious in this case: Actually honoring that expected type would produce broken code, because it would involve a cast to B when in this case what we actually want is an ordinary reference comparison. It seems like this would be okay in most cases but it is specifically problematic for comparison operators - it looks like ILSpy believes that 'bool operator == (B lhs, B rhs)' is being called, when 'bool operator == (I lhs, I rhs)' is actually being called.

At present whenever I see an expected type that does not match an inferred type, I treat it as a cast, because in most cases that is what it seems to mean in ILAST. In this case, however, I have to detect this weird pattern and ignore it.

Am I misunderstanding expected and inferred types?

**Comment by dgrunwald** [comment]
The newdecompiler branch no longer has expected types (or any C# types at all) in the ILAst, so I'm closing this issue.

If you are still maintaining JSIL, you should take a look at that branch. We've made significant progress in decompiler correctness, to the point where we can decompile libraries like Mono.Cecil or NRefactory.CSharp, recompile them from the decompiled project, and have them pass their original test suites.
The downside is that the newdecompiler does not yet support all detecting all the high-level C# constructs that were previously supported.

**Comment by kg** [comment]
Thanks, that's great to hear! I'll look into the new branch at some point, and it sounds like since it's simpler it should be easier to contribute fixes for.
