### ISSUE TITLE
Non-alphanumeric characters in identifiers

### ISSUE THREAD

**Issue by DiEvAl** [icsharpcode/ILSpy#385]
I have an partially obfuscated dll in which all private members and some classes are called like `\u0019\u0006` (`EM``ACK`), `\u000A\u0009` (`LF``TAB`), etc. But of course compiler doesn't allow such identifiers.

I think when decompiler encounters invalid identifier, it should replace it with a different, but valid one. For example for fields it might do `newName = "field_" + oldName.GetHashCode()`.

![](https://f.cloud.github.com/assets/1624998/150034/8c63de54-7542-11e2-88d2-93dee0b5095d.png)

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
