### ISSUE TITLE
Non-compilable code was produced by ILSpy

### ISSUE THREAD

**Issue by senglory** [icsharpcode/ILSpy#389]
In decompiled sources I saw something weird:

if (<  PrivateImplementationDetails >{1B743747-93B8-4A24-8F3F-07245468540B}.$$method0x60000c6-1 == null)

C# compiler (v 4.0 and 4.5) refuses to compile it.

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch) -- at least because we know escape invalid identifiers.
