### ISSUE TITLE
Non-compilable code - properties setter

### ISSUE THREAD

**Issue by senglory** [icsharpcode/ILSpy#390]
For that code:

SPQuery sPQuery = new SPQuery();

```
        if (xmlNode == null)
        {
            sPQuery.set_Query(this._camlDocument.InnerXml);
        }
```

it produces wrong assignment line (set_Query). Instead of explicit set_Query(XXX) it should write .Query = XXX

**Comment by siegfriedpammer** [comment]
See #849
