### ISSUE TITLE
clicking the class of a variable doesn't move over to that class

### ISSUE THREAD

**Issue by BloodyRain2k** [icsharpcode/ILSpy#391]
A good example is mscorlib -> System.Activator
There's a "private const BindingFlags" (System.Reflection.BindingFlags) and when I click that "BindingFlags" nothing happens aside the cursor giving off a small shockwave or pulsing effect, or something like that.

I found this bug while going through another dll looking at public variables, so I first thought it might be only these but it looks like it doesn't work for all class variables.

The version of ILSpy that I'm using is 2.1.0.1603 and my OS is Win7 Home Premium 64bit.

**Comment by siegfriedpammer** [comment]
Cannot be reproduced with current master branch => closing.
