### ISSUE TITLE
yield return x bug

### ISSUE THREAD

**Issue by Warstone** [icsharpcode/ILSpy#395]
Trying to disassemble bsgo.com unity3d C# lib...

There is bogus disassembled code (ActorLevel):

``` C#
private IEnumerator WaitForPrefab(AssetRequest request)
    {
        AvatarLevel.<WaitForPrefab>c__Iterator7 <WaitForPrefab>c__Iterator = new AvatarLevel.<WaitForPrefab>c__Iterator7();
        <WaitForPrefab>c__Iterator.request = request;
        <WaitForPrefab>c__Iterator.<$>request = request;
        <WaitForPrefab>c__Iterator.<>f__this = this;
        return <WaitForPrefab>c__Iterator;
    }
```

It's called from

``` C#
base.StartCoroutine(this.WaitForPrefab(request));
```

Description of StartCoroutine is here: http://docs.unity3d.com/Documentation/ScriptReference/MonoBehaviour.StartCoroutine.html

You can get library from unity3d file with Unity3D Obfuscator http://unity3d.netobf.com/unity3dobfuscator (free version is fine)

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
