### ISSUE TITLE
Implicit conversion from Nullable<T> to T (used in VB.NET) results in typecast to type "!0" in C#

### ISSUE THREAD

**Issue by MartinMulderTurien** [icsharpcode/ILSpy#407]
If my VB.NET code uses implicit conversions from nullable types to non-nullable types, the generated C#-code will use a cast. The cast is not the type we want, but always to the type "!0".

So this:

decimal arg_24F_2 = new decimal?(new decimal(123));
arg_24F_3 = (!0)arg_24F_2;

should be:

decimal arg_24F_2 = new decimal?(new decimal(123));
arg_24F_3 = (decimal)arg_24F_2;

**Comment by dgrunwald** [comment]
This is fixed in the new implementation of nullables in ILSpy 3.0.
