### ISSUE TITLE
If compiler generated code is converted by ILSpy into C#, these (.NET) names are invalid in C#

### ISSUE THREAD

**Issue by MartinMulderTurien** [icsharpcode/ILSpy#408]
If the compiler generates code, like anonymous methods, the methods created by the compiler use characters like '$'. When ILSpy converts these functions into C#, the names remain, cause illegal names in C#.

**Comment by siegfriedpammer** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
