### ISSUE TITLE
Error during decompilation of the System.Uri::ParseSchemeCheckImplicitFile in the 

### ISSUE THREAD

**Issue by kant2002** [icsharpcode/ILSpy#412]
During decompilation of the method

System.UInt16 System.Uri::ParseSchemeCheckImplicitFile(System.Char*,System.UInt16,System.UriExceptionHelper/ParsingError&,System.Uri/Flags&,System.UriParser&)

from the system.dll assembly which is shipped with Silverlight,
the NullReferenceException thrown.

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
