### ISSUE TITLE
switch decompilation issue

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#414]
Latest build of ILSpy  (ILSpy version 2.1.0.1645) has some issues with switch decompilation

example:

private void frmMain_FormClosing(object sender, FormClosingEventArgs e)
{
    int num;
    int num3;
    try
    {
        IL_00:
        ProjectData.ClearProjectError();
        num = -2;
        IL_08:
        int num2 = 2;
        if (modGlobal.m_bForceRestartApp)
        {
            goto IL_35;
        }
        IL_11:
        num2 = 3;
        if (Interaction.MsgBox("Exit application?", MsgBoxStyle.YesNo | MsgBoxStyle.Information, modGlobal.m_szAppProductName) != MsgBoxResult.No)
        {
            goto IL_35;
        }
        IL_27:
        num2 = 4;
        e.Cancel = true;
        IL_30:
        goto IL_114;
        IL_35:
        num2 = 8;
        if (modGlobal.m_eProxyOption != modGlobal.EProxyOption.ProxyList)
        {
            goto IL_56;
        }
        IL_3F:
        num2 = 9;
        if (!File.Exists(modGlobal.m_szProxyListPath))
        {
            goto IL_56;
        }
        IL_4E:
        num2 = 10;
        modGlobal.UpdateProxyListFileStatus();
        IL_56:
        num2 = 13;
        this.class1_0.method_4();
        IL_65:
        num2 = 14;
        this.class2_0.method_1();
        IL_74:
        num2 = 15;
        modGlobal.DeleteYPCache(false);
        IL_7D:
        goto IL_114;
        IL_82:
        int arg_87_0 = num3 + 1;
        num3 = 0;
        @switch(ICSharpCode.Decompiler.ILAst.ILLabel[], arg_87_0);
        IL_D0:
        goto IL_109;
        num3 = num2;
        if (num <= -2)
        {
            goto IL_82;
        }
        @switch(ICSharpCode.Decompiler.ILAst.ILLabel[], num);
        IL_E7:
        goto IL_109;
    }
    object arg_E9_0;
    endfilter(arg_E9_0 is Exception & num > 0 & num3 == 0);
    IL_109:
    throw ProjectData.CreateProjectError(-2146828237);
    IL_114:
    if (num3 != 0)
    {
        ProjectData.ClearProjectError();
    }
}

here is how latest Reflector decompiles it:

private void frmMain_FormClosing(object sender, FormClosingEventArgs e)
{
    int num2;
    try
    {
        int num3;
    Label_0000:
        ProjectData.ClearProjectError();
        int num = -2;
    Label_0008:
        num3 = 2;
        if (modGlobal.m_bForceRestartApp)
        {
            goto Label_0035;
        }
    Label_0011:
        num3 = 3;
        if (Interaction.MsgBox("Exit application?", MsgBoxStyle.Information | MsgBoxStyle.YesNo, modGlobal.m_szAppProductName) != MsgBoxResult.No)
        {
            goto Label_0035;
        }
    Label_0027:
        num3 = 4;
        e.Cancel = true;
        goto Label_0114;
    Label_0035:
        num3 = 8;
        if (modGlobal.m_eProxyOption != modGlobal.EProxyOption.ProxyList)
        {
            goto Label_0056;
        }
    Label_003F:
        num3 = 9;
        if (!File.Exists(modGlobal.m_szProxyListPath))
        {
            goto Label_0056;
        }
    Label_004E:
        num3 = 10;
        modGlobal.UpdateProxyListFileStatus();
    Label_0056:
        num3 = 13;
        this.class1_0.method_4();
    Label_0065:
        num3 = 14;
        this.class2_0.method_1();
    Label_0074:
        num3 = 15;
        modGlobal.DeleteYPCache(false);
        goto Label_0114;
    Label_0082:
        num2 = 0;
        switch ((num2 + 1))
        {
            case 1:
                goto Label_0000;

```
        case 2:
            goto Label_0008;

        case 3:
            goto Label_0011;

        case 4:
            goto Label_0027;

        case 5:
        case 0x10:
            goto Label_0114;

        case 6:
        case 7:
        case 8:
            goto Label_0035;

        case 9:
            goto Label_003F;

        case 10:
            goto Label_004E;

        case 11:
        case 12:
        case 13:
            goto Label_0056;

        case 14:
            goto Label_0065;

        case 15:
            goto Label_0074;

        default:
            goto Label_0109;
    }
Label_00D2:
    num2 = num3;
    if (num <= -2)
    {
        goto Label_0082;
    }
    switch (num)
    {
        case 0:
            goto Label_0109;

        case 1:
            goto Label_0082;
    }
}
catch (object obj1) when (?)
{
    ProjectData.SetProjectError((Exception) obj1);
    goto Label_00D2;
}
```

Label_0109:
    throw ProjectData.CreateProjectError(-2146828237);
Label_0114:
    if (num2 != 0)
    {
        ProjectData.ClearProjectError();
    }
}

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
