### ISSUE TITLE
use ILSpy on linux with Mono

### ISSUE THREAD

**Issue by hajdbo** [icsharpcode/ILSpy#416]
I'd like to use ILSpy on Linux, if it could be run by Mono.

Mono does not support WPF and I guess it's how ILSpy GUI is built.

**Comment by andreif** [comment]
Could you recommend a strategy to make a cli application if there is no such already for OS X?

**Comment by andreif** [comment]
From what I see, one would need to exclude AvalonEdit and run `DecompileNodes` with proper arguments. Am I on the right track?

**Comment by dgrunwald** [comment]
Those "nodes" are still WPF tree nodes. Pretty much all the code in ILSpy is WPF-dependent UI code.
The decompiler logic itself is already in a separate assembly: ICSharpCode.Decompiler.

MonoDevelop already uses ICSharpCode.Decompiler on OS X and Linux.

**Comment by andreif** [comment]
I have not found a sane way to decompile a large library to source files in MonoDevelop/Xamarin. If you know how, please tell. Otherwise it's just infinite manual copy-pasting from GUI to text files.

**Comment by andreif** [comment]
What about `CSharpLanguage.DecompileAssembly`?

**Comment by andreif** [comment]
Well, I am slowly getting further. There is no `fusion.dll` on OS X, so the libs has to be collected manually as I see. Not sure if I have enought time and interest to get it done though. I'll keep posting here for now.

**Comment by andreif** [comment]
Ok, so I got it to decompile a library without references (it fails for `mscorlib.dll` though). I'll try to find some way to include the refs as well whenever I can dedicate more time for it.

**Comment by andreif** [comment]
It seems to work well now. I have modified few source files to get it through and now curious if I can avoid modifying the original sources. I'll try to find some time for testing it.

**Comment by andreif** [comment]
I made a quick-n-dirty project to build for OS X but I guess it should work for Linut too, see https://github.com/andreif/ILSpyMono

**Comment by minexew** [comment]
@andreif This has been very helpful, thanks.

**Comment by christophwille** [comment]
@mkrueger prepared a [demo project](https://github.com/mkrueger/ILSpy/tree/xwt) for our SharpDevelop Developer Days in November outlining how a multi-targetting project could look like.

We are leaning towards WPF for Windows, and having one head for Mac/Linux. But note that the core team is working on vNext of the underlying decompiler architecture, so it is a good time to chime in if you have xplat chops especially with xwt.

**Comment by andreif** [comment]
Just found one more CLI project https://github.com/aerror2/ILSpy-For-MacOSX
Did anyone try it?

**Comment by sbrl** [comment]
Isn't that for Mac? On 19 Feb 2017 5:42 pm, Andrei Fokau <notifications@github.com> wrote:Just found one more CLI project https://github.com/aerror2/ILSpy-For-MacOSX
Did anyone try it?

**Comment by andreif** [comment]
It's called `ILSpy for Mac OS X ,Linux and any mono supported platform`

**Comment by sbrl** [comment]
Hrm. While that project compiles, I get nasty errors about an incorrect
directory.
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb"
> ,"name":"GitHub"},"entity":{"external_key":"github/icsharpcode/ILSpy","title":
> "icsharpcode/ILSpy","subtitle":"GitHub repository","main_image_url":"https://c
> loud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/asse
> ts/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/icsharpcode/ILSpy"}},"updates":{"snippets":[
> {"icon":"PERSON","message":"@andreif in #416: It's called `ILSpy for Mac OS X
> ,Linux and any mono supported platform`"}],"action":{"name":"View
> Issue","url":"https://github.com/icsharpcode/ILSpy/issues/416#issuecomment-
> 280940238"}}}

**Comment by PoroCYon** [comment]
[This fork](https://github.com/0xd4d/dnSpy) exists, and the CLI version seems to work just fine on mono. (I'm running Parabola (99% the same as Arch) myself, and it works for me.)

**Comment by TiberiumN** [comment]
@PoroCYon sorry for necro-post, but this is not a fork, it's a completely different code (it's just based on some ilspy code)

**Comment by tthiery** [comment]
Has anyone spent a thought on using VS Code as the UI platform?

**Comment by jleclanche** [comment]
That'd be nice.

**Comment by christophwille** [comment]
So far, even /newdecompiler isn't netstandard2 (might work though). When/if that lands, xplat UI should be a lot easier to pull off - re:VSCode, haven't ever looked into what it would take to implement a rather complex UI (in terms of interaction between JS and .NET, think memory). If anyone has infos (eg a "similar" existing extension), that would be welcome.

**Comment by sbrl** [comment]
I'd prefer not having to install Visual Studio Code in order to use it.

**Comment by asd-and-Rizzo** [comment]
[I was able to run on Wine.](https://stackoverflow.com/a/27940964/173073)

**Comment by jeremymeng** [comment]
I am working on a prototype of VSCode extension.  The basic idea is to have an omnisharp-roslyn like backend, which takes requests then responds using stdio, and to use some utilities from omnisharp-vscode to handle the request handling in the extension.  The back end (in C#) uses ILSpy support to decompile and sends nodes and decompiled code to VS Code extension for display using the TreeDataProvider and the editor.

![image](https://user-images.githubusercontent.com/7583839/29846868-8af1b6ca-8ccd-11e7-8965-dd1b3f3cec7f.png)

I haven't added support for Linux/OSX.  I imagine it should be easy and similar to what omnisharp-vscode is doing: running them using Mono.

**Comment by christophwille** [comment]
We are working hard on netstandard 2.0 (/newdecompiler branch) and it should land very, very soon. That should allow .NET Core and make this a lot more streamlined across platforms (haven't checked what mssql extension is doing - Mono too?).

**Comment by lextm** [comment]
@jeremymeng at least JetBrains Rider runs ReSharper code on Mono on non-Windows platforms. So if your case, your VSCode extension can run some ILSpy code on Mono.

**Comment by jeremymeng** [comment]
@lextm I know it's workable, just haven't got time to get to that part.  Also with ILSpy netstandard 2.0 work coming, Mono route might become unnecessary. Last time I checked, the biggest obstacle is CodeDOM, which I don't see in the newdecompiler any more.

**Comment by PoroCYon** [comment]
@Yardanico Oops, sorry

@sbrl Indeed, my machine can't handle much load, so I don't want to have VS Code running... (Same for Wine, really, so what @asd-and-Rizzo managed is still of no use for me.)

-----

I tried to compile the `newdecompiler` codebase, but `xbuild` couldn't parse the `.csproj` files. Does anyone have pointers on getting it to compile? (Preferably without installing `dotnet`, as I have some [bad experiences](https://gitlab.com/PoroCYon/PokeApi.NET/issues/16#note_37101638) with it...)

**Comment by Yardanico** [comment]
@PoroCYon also dnSpy works great with Wine + .net runtime

**Comment by PoroCYon** [comment]
I currently use dnSpy in the terminal, running on mono, and it works just fine. (I'm not really a UI person, so maybe some of you mightn't agree.)

**Comment by christophwille** [comment]
@PoroCYon we are definitely not targeting low-end machines, neither on Windows (net461 will be the future min fw) nor for any other platform we might support (.NET Core itself has some requirements).

**Comment by sbrl** [comment]
@christophwille I do have a pretty good laptop (running Ubuntu 17.04), but I'm not about to install wine or VS Code just to decompile C# programs.

**Comment by christophwille** [comment]
Like I said, ILSpy is not a one-size-fits-all app. However, there is no reason why multiple frontends couldn't be built, including a command line version (also interesting for automation scenarios btw).

**Comment by PoroCYon** [comment]
@christophwille Same, it's a laptop, but not the best ever (it's 6 years old), so I'd rather avoid as much bloat as possible. FYI, I'm running Parabola (rolling release).

**Comment by christophwille** [comment]
Please read https://github.com/icsharpcode/ILSpy/issues/831#issuecomment-326868618 Again, the package is intended for those that want to get started with xplat netcoreapp support. @jeremymeng please test, and @andreif if you want to test for console, that would be great.

**Comment by jeremymeng** [comment]
@christophwille my project uses a copy of `CSharpLanguage` which depends on `ICSharpCode.NRefactory`.  Are there any alternatives? It would be great if non-UI-related code is extract out of `ILSpy` into a .netsandard library so it can be consumed easily by other projects.

**Comment by dgrunwald** [comment]
@jeremymeng: The non-UI-related code is already extracted into `ICSharpCode.Decompiler.dll`. The main class you're supposed to use is `CSharpDecompiler` or `WholeProjectDecompiler`.

`CSharpLanguage` was never meant to be the entry point for using the decompiler API, it's just the class that corresponds to the "C#" choice in ILSpy's language dropdown.

**Comment by jeremymeng** [comment]
> it's just the class that corresponds to the "C#" choice in ILSpy's language dropdown.

Yeah, but there are handy helper methods for decompiling methods, fields, etc. into various languages (C#, VB, IL).  They are not tied to the WPF UI, but unfortunately within the same project.

**Comment by siegfriedpammer** [comment]
Soon we'll prepare a small demo command-line application that uses the CSharpDecompiler class.

**Comment by christophwille** [comment]
We have updated https://github.com/christophwille/ilspy-console-netcoreapp/ to "wean everyone off of CSharpLanguage". As you can see in the animated GIF, it can run as a self-contained executable on Mac + it decompiles itself (being a netcoreapp this is new, something that wasn't possible last week)

**Comment by PoroCYon** [comment]
@christophwille Is there any way to get it to work without having to install `dotnet-cli`? I don't really want to install something that requires itself to compile, as I don't like binary packages (especially Microsoft's).

**Comment by christophwille** [comment]
Self-contained deployment (scd) is the farthest we will go at the moment (remember: the cmd line uses the -alpha2 package and we haven't yet reached the functionality level of the decompiler for master merge) - there are bigger fish to fry. Having said that: the future might be https://github.com/dotnet/corert

**Comment by christophwille** [comment]
Please note that the ilspycmd project is now officially supported in our main repo:

https://github.com/icsharpcode/ILSpy/tree/master/ICSharpCode.Decompiler.Console

@jeremymeng Command line and VS "proper" addin are already part of our main repo - definitely something we'd like for a VS Code addin too.

**Comment by jeremymeng** [comment]
@christophwille I planned to publish my projects to github after some cleanup.  If any ideas/architecture can be reused by ILSpy team I am happy to continue contributing.

**Comment by christophwille** [comment]
@jeremymeng thanks. (side note: ILSpy core devs will meet for the weekend of October 12th in Bad Ischl at our annual developer days)
