### ISSUE TITLE
if unable to reflect one class it stops dumping the source

### ISSUE THREAD

**Issue by KOLANICH** [icsharpcode/ILSpy#424]
I started decompilation using File->Save Code...
Sometimes decompilation of one class had failed, and this had cancelled dumping the code of the rest of them.
It should continue dumping the source skipping classes which cannot be dumped.

**Comment by dgrunwald** [comment]
If you're running into decompiler crashes, please report them so that we can fix them.

We won't add a mode that ignores errors.
