### ISSUE TITLE
Problem with decompilation

### ISSUE THREAD

**Issue by KOLANICH** [icsharpcode/ILSpy#425]
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Boolean project.Class41::Method6(System.Windows.Forms.Form,System.Windows.Forms.ListView,System.Collections.Generic.Dictionary`2<System.String,System.Collections.Generic.List`1<project.Class39>>,System.Collections.Generic.Dictionary`2<System.String,System.String>)
 ---> System.Exception: Inconsistent stack size at IL_4B
   в ICSharpCode.Decompiler.ILAst.ILAstBuilder.StackAnalysis(MethodDefinition methodDef)
   в ICSharpCode.Decompiler.ILAst.ILAstBuilder.Build(MethodDefinition methodDef, Boolean optimize, DecompilerContext context)
   в ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   в ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- Конец трассировки внутреннего стека исключений ---
   в ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   в ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef)
   в ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef)
   в ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
   в ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef)
   в ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   в ICSharpCode.ILSpy.TreeNodes.TypeTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   в ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   в ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass17.<DecompileAsync>b__16()

PS I firstly used  [pv logicels deobfuscator](http://www.pvlog.com/Tools.aspx)

**Comment by siegfriedpammer** [comment]
This was probably fixed in the new decompiler engine (which just landed on the master branch).
