### ISSUE TITLE
This code should be improved

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#427]
source code:
static void Main(string[] args)
{
    IEnumerable<string> col = null;
    foreach (var ele in col)
        Console.WriteLine(ele);
    {
        string ele = "7";
        Console.WriteLine(ele);
    }
}

decompile code:
private static void Main(string[] args)
{
    IEnumerable<string> enumerable = null;
    string value;
    using (IEnumerator<string> enumerator = enumerable.GetEnumerator())
    {
        while (enumerator.MoveNext())
        {
            value = enumerator.Current;
            Console.WriteLine(value);
        }
    }
    value = "7";
    Console.WriteLine(value);
}

If I rename any "ele", ILSpy can work normally.

**Comment by siegfriedpammer** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
