### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#430]
Source:
private static void Main(string[] args)
        {
            Console.WriteLine(0xffffeeeeL);
            Console.ReadKey();
        }

Output is 4294962926

Decompile:
private static void Main(string[] args)
{
    Console.WriteLine((long)((ulong)-4370));
    Console.ReadKey();
}

This code contains an error, edit it:
private static void Main(string[] args)
{
   unchecked
{
    Console.WriteLine((long)((ulong)-4370));
    Console.ReadKey();
}
}

Output is -4370, not 4294962926

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
