### ISSUE TITLE
Freezes on very long if else... statements

### ISSUE THREAD

**Issue by Shockah** [icsharpcode/ILSpy#434]
ILSpy hangs while trying to decompile very long if else... statements. At least I think it's what happens. Basically, it turns if elses into if {} else {if {}...}, which with 1500 or so statements is too much for it.

I don't know what's the actual code that makes it do that, but if you ever heard of a game called Terraria, then you can test it yourself - the class Item doesn't decompile at all because of that. It's pretty annoying for us, the tAPI dev team (we're bringing mod support to Terraria), as we have to decompile it manually class-by-class, and then use dotPeek for the Item.cs.

**Comment by dgrunwald** [comment]
Can you try with the new decompiler engine (which just landed on the master branch)?

**Comment by dgrunwald** [comment]
I'll assume that this was something similar to #631, so the performance issue is likely fixed with the new decompiler.
