### ISSUE TITLE
Deassemble  is wrong.

### ISSUE THREAD

**Issue by xieyubo** [icsharpcode/ILSpy#439]
list.AddRange(BitConverter.GetBytes((ushort) 2));
list.AddRange(BitConverter.GetBytes(2));

The first line is the result of .Net Reflector. The second line is the result of ILySpy 2.1.0.1603. (ushort) is missed in ILySpy result. .Net Reflector is right.

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
