### ISSUE TITLE
Cannot decompile Roslyn-compiled async methods

### ISSUE THREAD

**Issue by weltkante** [icsharpcode/ILSpy#457]
When an assembly was compiled with the recently released Roslyn compiler (http://roslyn.codeplex.com) then ILSpy fails to decompile async methods, it displays code like this instead:

```
private void Form1_Load(object sender, EventArgs e)
{
    Form1.<Form1_Load>d__1 <Form1_Load>d__;
    <Form1_Load>d__.<>t__builder = AsyncVoidMethodBuilder.Create();
    <Form1_Load>d__.<>1__state = -1;
    AsyncVoidMethodBuilder <>t__builder = <Form1_Load>d__.<>t__builder;
    <>t__builder.Start<Form1.<Form1_Load>d__1>(ref <Form1_Load>d__);
}
```

However the inner class `<Form1_Load>d__` is not accessible in ILSpy so I cannot browse the state machine either, which makes ILSpy useless for these assemblies. (The inner class becomes visible when switching from C# to IL mode, but thats not very useful.)

So this really is two issues:
- analysis of async methods fails for Roslyn-based assemblies
- when async method analysis fails you cannot examine the state machine because the inner class is hidden

Fixing either one would help a lot.

To reproduce you can reference the nuget package `Microsoft.Net.ToolsetCompilers` in Visual Studio to build a project with Roslyn instead of the normal compiler. Alternatively you could of course setup your own Roslyn build environment.

**Comment by dolkensp** [comment]
Looks to be broken again when compiling in VS2015 - possibly same issue again?

**Comment by weltkante** [comment]
@dolkensp this issue was with the prerelease roslyn compiler, so its unlikely to be the same issue since back then.

If I remember right Roslyn had changed the generated IL bytecode patterns sometime between codeplex prerelease and VS2015 release. There are plenty of other open issues around with ILSpy unable to handle current Roslyn/VS2015 IL, so no point reopening this specific issue.

**Comment by dolkensp** [comment]
@weltkante  not a problem - this was the first issue I came across and it perfectly matched what I was seeing. Sounds like you're already on top of it.

I was just being lazy anyways - decompiling the exe on one machine, to check something, instead of walking across the room to get my laptop to view the source ;)
