### ISSUE TITLE
Invalid Decompiled VB Code for Event Handler Assignments

### ISSUE THREAD

**Issue by AdorianDoran** [icsharpcode/ILSpy#465]
Instead of:

```vb.net
AddHandler ObjectName.EventName, AddressOf MethodName
```

The following C# flavored syntax is generated, which is invalid in VB:

```vb.net
ObjectName.EventName += New EventHandler(MethodName)
```

**Comment by siegfriedpammer** [comment]
if type information is missing ILSpy cannot detect the event and thus does not produce an AddHandler/RemoveHandler expression. If there's a specific case, please post a real world example.
