### ISSUE TITLE
Full namespace search

### ISSUE THREAD

**Issue by Z1oG1aZ** [icsharpcode/ILSpy#473]
Please add possibility to search class or methods name with full namespace e.g.  System.Web.UI.UserControl

In addition, please add an option to search for the exact match since currently it will search for all names that contains the "search" word:
![searchimporvement](https://cloud.githubusercontent.com/assets/7161197/3482064/80191cd6-037b-11e4-96dc-79905d6756cd.png)

**Comment by Zvirja** [comment]
Hope, that will help somebody.

That is actually implemented. Check https://github.com/icsharpcode/ILSpy/blob/a2cbd6d3456d1e4e37daec7edebb1982c8ec6042/ILSpy/SearchStrategies.cs#L20.

It appears that search supports regular expressions.
Also, you can put modifiers to specify term presence:

`=` - should equal (e.g. `=UserControl`).
`+` - should be present
`-` - should not be present

**Comment by Z1oG1aZ** [comment]
Thanks!
