### ISSUE TITLE
Search in a specific namespace

### ISSUE THREAD

**Issue by Brampage** [icsharpcode/ILSpy#475]

**Comment by Zvirja** [comment]
Could you clarify what exact behavior should be?
I imagine that custom prefix could be added to run that "namespace" search. The only question is whether you need specify the fully-qualified namespace name or "string.Contains()" should be used?

**Comment by dgrunwald** [comment]
You can already search in a specific namespace by including the namespace in the search term, e.g. `generic.list`.
