### ISSUE TITLE
XmlException with microsoft.bcl.immutable

### ISSUE THREAD

**Issue by LaurentDardenne** [icsharpcode/ILSpy#485]
Hi,
when i use C# or VB i get this exception :

System.Xml.XmlException: '.', valeur hexadécimale 0x00, est un caractère non valide. Ligne 2, position 1.
   à System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   à System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Xml.XmlReader.MoveToContent()
   à ICSharpCode.NRefactory.Documentation.XmlDocumentationProvider..ctor(String fileName)
   à ICSharpCode.ILSpy.XmlDoc.XmlDocLoader.LoadDocumentation(ModuleDefinition module)
   à ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   à ICSharpCode.ILSpy.XmlDoc.AddXmlDocTransform.Run(AstNode node)
   à ICSharpCode.ILSpy.CSharpLanguage.RunTransformsAndGenerateCode(AstBuilder astBuilder, ITextOutput output, DecompilationOptions options, IAstTransform additionalTransform)
   à ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options)
   à ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   à ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15()

Windows Seven x64 Fr

ILSpy version 2.2.0.1706

https://www.nuget.org/packages/microsoft.bcl.immutable

[assembly: AssemblyVersion("1.0.34.0")]
[assembly: AssemblyProduct("System.Collections.Immutable")]

**Comment by siegfriedpammer** [comment]
I am closing this issue. I have implemented a workaround for your problem. The underlying problem is that `System.Collections.Immutable.xml` is not a valid XML file.

**Comment by LaurentDardenne** [comment]
Thank you :-)
