### ISSUE TITLE
Add support for switch statement pattern using Hashtable

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#489]
Here is how ILSpy 2.2 decompiles some switch blocks:

public static BitArray getBoolArrayOfPermissions(ArrayList permissions)
{
   if (<PrivateImplementationDetails>.$$method0x600024f-1 == null)
   {
       <PrivateImplementationDetails>.$$method0x600024f-1 = new Hashtable(188, 0.5f)
       {

```
       {
           "AgEdtRecord",
           0
       },

       {
           "AgDelRecord",
           1
       },
```

...........
       object obj;
       if ((obj = text) != null && (obj = <PrivateImplementationDetails>.$$method0x600024f-1[obj]) != null)
       {
           switch ((int)obj)
           {
           case 0:
.................

and here is how old .Net Refletor 7.0 handles it:

public static BitArray getBoolArrayOfPermissions(ArrayList permissions)
{
   BitArray array = new BitArray(permCount);
   array.SetAll(false);
   for (int i = 0; i < permissions.Count; i++)
   {
       switch (((string) permissions[i]))
       {
           case "AgEdtRecord":
               array[iAgEdtRecord] = true;
               break;
....................

The question is:

it is possible to elaborate on this issue and make it more user-friendly like Reflector handles it?
Thanks

**Comment by siegfriedpammer** [comment]
Sorry for taking so long to work on this. With the rewrite of the decompiler engine we now reimplemented `switch-on-string` in the ILAst. We currently can only correctly handle C# switch-string patterns that either use `Dictionary<string, int>` (legacy C#) or a special hash function (Roslyn).

Could you provide a binary containing an example that uses `Hashtable`?
