### ISSUE TITLE
Refreshing a .dll should try to expand the tree view in the same matter as it was opened before

### ISSUE THREAD

**Issue by Meai1** [icsharpcode/ILSpy#493]
Just ignore tree nodes that dont exist anymore, but it's quite annoying to constantly have to expand all these items again every time I update the assembly.

**Comment by imor** [comment]
In the latest build, whenever I rebuild an assembly and press F5, the last selected node remain selected. If that node is no longer available (e.g. the selected method was deleted) then its parent is selected. Can you confirm?

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler (which just landed on the master branch).
