### ISSUE TITLE
Wpf's Application.Dispatcher.Invoke not correct.

### ISSUE THREAD

**Issue by kissstudio** [icsharpcode/ILSpy#496]
the output is Application.Dispatcher.Invoke(delegate{//code})
but the vs complier requires code like Application.Dispatcher.Invoke(new Action(()=>{//code});
and the output code always contains a empty object array param like this 
the output is Application.Dispatcher.Invoke(delegate{//code},new object[0])
i don't need that param i think.

**Comment by siegfriedpammer** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
