### ISSUE TITLE
Will support finding assembly reference in config file?

### ISSUE THREAD

**Issue by kissstudio** [icsharpcode/ILSpy#497]
the config file like this, and the reference path is a relative path.
ilspy can not find the reference file automatic.
![qq 20141016104646](https://cloud.githubusercontent.com/assets/2771647/4656843/ac3d3536-54de-11e4-9806-ff47f5e2b384.png)
Will ilspy support finding the reference of assemblies in config file?

**Comment by dgrunwald** [comment]
I don't think we'll ever support this special case.
