### ISSUE TITLE
Add 2.2 to chocolatey

### ISSUE THREAD

**Issue by asd-and-Rizzo** [icsharpcode/ILSpy#499]
Please add it to chocolatey.org
Integrate into Program Start Menu to be able to search app by name and into command line (ilspy.exe my.dll)
See how https://chocolatey.org/packages?q=git splits several packages (install, commandline and git combination).

Please automate creation of chocolatey packages for newer versions.

I will donate another few bucks to icsharpcode after this made.

**Comment by christophwille** [comment]
https://chocolatey.org/packages/ilspy - we are not the package maintainers.

**Comment by batzen** [comment]
If you are not the maintainers you could ask the current maintainer or the chocolatey team to add you.

I think this issue should be closed because the package is already updated or should be renamed to "Get admin access to chocolatey package" or "Automate creation of chocolatey package".

**Comment by siegfriedpammer** [comment]
This is already on our list.
