### ISSUE TITLE
ILSpy doesn't handle non-trivial language features from Roslyn compilers

### ISSUE THREAD

**Issue by SLaks** [icsharpcode/ILSpy#502]
Existing features like `switch` blocks, lambdas, iterators, and especially async are compiled differently by the Roslyn compiler, and ILSpy generates very ugly code for them (sometimes failing entirely).

These issues are especially evident when trying to decompile Dev14 itself, which is all compiled with Roslyn.

I will change the decompiler test cases to run each test with both the Roslyn compiler and the legacy compiler, and fix as many of the breakages as I can.

**Comment by rraallvv** [comment]
I'm seeing this on the Xamarin Studio's Assembly browser too:

```
[CompilerGenerated]
[Serializable]
private sealed class <>c
{
	public static readonly Parser.<>c <>9 = new Parser.<>c ();

	public static Converter<TypeNode, string> <>9__77_0;

	public static Converter<TypeNode, string> <>9__75_0;

	public static Converter<TypeNode, string> <>9__74_0;

	public static Converter<TypeNode, string> <>9__73_0;
 
```

Is there a way to make ILSpy to correctly decompile the assemblies that generated that?

**Comment by dgrunwald** [comment]
The new decompiler engine (which just landed on the master branch) adds Roslyn support for all language features supported so far (see #829 details).
