### ISSUE TITLE
Collapse group in Visual Studio context menu

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#504]
For the context menu which appears when you right click an assembly under a **References** node in the **Solution Explorer** pane.

Currently the **Open in ILSpy** command is placed in its own group below **View in Object Browser**. I believe a better placement would be *within* the same group as **View in Object Browser**, but still placed below it.

**Comment by vincpa** [comment]
Can I suggest putting suggestions on UserVoice ? :)
