### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#506]
(ALT+)F12 Go to definition

Navigate to a temporary tab _inside_ VS (opening ILSpy.exe is not a good idea here).
Make sure to support scenarios where people have tools on their box that rewrite F12 too (think Resharper)

**Comment by yoyobbi** [comment]
Note that "Go to definition" is similar to the "Open code in ILSpy" feature I'm working on. See #696 and friends. However I am **not** working on support for display inside Visual Studio (along the lines of the standard "Peek Definition"), just for launching ILSpy externally and navigating to the selected code.

**Comment by sharwell** [comment]
@SLaks For a feature inside Visual Studio, I think the Roslyn custom workspace approach is the one to go with. "Only works with dev14" will quickly turn to "works with dev14 and newer"... plus you would still have the external viewer for other cases.

**Comment by bbi-yoyo** [comment]
For the record, in case anyone on this thread is interested, pull request #706 (not yet merged as of May 4th) resolves the final issues I am aware of with my new "Open code in ILSpy" feature. Would appreciate feedback from anyone who has time to try it out.

**Comment by bbi-yggy** [comment]
I did test constructors extensively, including a wide variety of generic constructors, see ILSpy.AddIn/Samples/ILSpyAddInSamples.cs for my test cases. How can I determine the state of the code in version 2.4.0.1963? Does it match the current v2.4 tag?

If it's not working with my latest changes (which aren't recent, it was back in May) then I will investigate why and the fixes should be straightforward. Unfortunately I won't have time to investigate until the middle of next week, August 3rd or so. If you can provide a test case that doesn't work that could be helpful.

For what it's worth, I just retested with the ILSpy add-in I built locally while working on the feature, and navigate to constructor is working fine.

**Comment by ayushkovsky** [comment]
> Does it match the current v2.4 tag?
Yes, unfortunately the current full version I built (version 2.4.0.1972, matched v2.4 tag, built on July 31) has this bug. 

> Unfortunately I won't have time to investigate until the middle of next week
I don't think this is a high-level bug, just a little inconvinience :)

**Comment by bbi-yggy** [comment]
Hmm, OK. Please attach sample code -- my testing of constructors is working fine.

**Comment by siegfriedpammer** [comment]
Closing as ILSpy is now part of Visual Studio.
