### ISSUE TITLE
VSIX only includes dependencies for a full rebuild

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#511]
This is a complicated issue. For a full rebuild, all of the assemblies above are included transitively through the **ILSpy** reference with the exception of **ILSpy.BamlDecompiler.csproj** (see #510). However, for incremental builds after that, all transitive dependencies of **ILSpy** are removed from the output package.

A question about this [remains unanswered](http://stackoverflow.com/q/12110135/138304) on StackOverflow.

One solution is to always include all references to projects in the **ILSpy.AddIn** project, rather than rely on inherited dependencies. However, I'm hesitant to use this solution without understanding the details because it would be too easy for a future change to one of the inherited dependencies to not be included in the VSIX (any added transitive dependency must then be manually added to the VSIX project).

**Comment by siegfriedpammer** [comment]
I think this can be closed, because we are manually including referenced assemblies via the following msbuild script: https://github.com/icsharpcode/ILSpy/blob/56c2f200d04aa7a6c6c538f2b5c7d8a60be050c0/ILSpy.AddIn/ILSpy.AddIn.csproj#L94-L126
