### ISSUE TITLE
Naming of well known constants in C#, VB code (Math.PI instead of 3.1415926535897931)

### ISSUE THREAD

**Issue by KvanTTT** [icsharpcode/ILSpy#517]
It would be good to convert double numbers to well know constants (such as Math.PI, Math.E) and their combinations (Math.PI \* 2).

I mean decompile IL to:

``` csharp
if (x > Math.PI)
    x -= Math.PI * 2;
```

instead of:

``` csharp
if (x > 3.1415926535897931)
    x -= 6.2831853071795862;
```

**Comment by interdrift** [comment]
Why is this needed for the decompilator, it looks like a functinality that works fine?
