### ISSUE TITLE
Ternary order is reversed in decompiled code

### ISSUE THREAD

**Issue by MattRix** [icsharpcode/ILSpy#518]
I feel like I might be missing some option somewhere to switch this, but it sure feels like a bug to me. I'm using 2.2.0.1706

If my original code has:

```
answer = myBool ? "yes" : "no";
```

It will be decompiled as:

```
answer = (!myBool) ? "no" : "yes";
```

Technically it still works the same, but it take a lot more mental energy to read through code when all the ternary operators are arranged like that.

**Comment by dgrunwald** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
