### ISSUE TITLE
Could the core decompiler library be separated into its own repository?

### ISSUE THREAD

**Issue by alexrp** [icsharpcode/ILSpy#527]
(I am not sure if this has been brought up before, so if there is an existing issue, please point me in the right direction and close this!)

I would like to use `ICSharpCode.Decompiler` for decompilation support in Mono's `sdb` [0]. Doing so today is rather impractical as it would require pulling in the entirety of ILSpy as a submodule, which is quite large and only one library is actually relevant to `sdb`. It seems that MonoDevelop has had to import a copy of the source code [1] which is not really great either as that opens the door to local changes that people forget to submit upstream, and the local copy tends to get updated rarely because it's not as convenient as updating a Git submodule.

Perhaps `ICSharpCode.Decompiler` could be split into its own repository with a similar structure to Mono's `debugger-libs`, where `cecil` and `nrefactory` must be cloned side-by-side with the `debugger-libs` directory [2].

[0] https://github.com/mono/sdb/issues/7
[1] https://github.com/mono/monodevelop/tree/master/main/contrib
[2] https://github.com/mono/debugger-libs

**Comment by siegfriedpammer** [comment]
How about using the nuget package?
