### ISSUE TITLE
Support regular expressions in the Search box

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#530]
Currently the Search box is difficult to use for certain operations. It would be helpful if the search supported Regular Expressions.

In a past extension for Visual Studio, I found that this was convenient to implement by the following pair of rules. If you use the same rules, then you will not need to provide any additional UI updates (checkboxes, etc.) for this feature.

1. If the search string starts with `/`, remove the `/` character and treat the remaining search expression as a regular expression. For example, the search string `/^Directory$` would search for items using the regular expression `^Directory$`.

2. If the search string does not start with `\`, perform the same operation you are currently using.

**Comment by siegfriedpammer** [comment]
was implemented by pull request #481

**Comment by sharwell** [comment]
:sunglasses: :sparkles: :dancers:
