### ISSUE TITLE
Line numbers in decompiled code

### ISSUE THREAD

**Issue by ebrouen** [icsharpcode/ILSpy#536]
When the PDB file of a assembly is available, the variables names can be retrieved.
Why, in this situation, the true line numbers (instead of lines starting at 1 for each type) and source file name cannot be associated?
This would be a very great improvement for version debugging:  a project has been delivered to a customer, some modifications have been made, and an error occurs in the past version... It is not always possible to keep all versions of source code when evolution rhythm is high...

**Comment by SLaks** [comment]
You should use source control (with branches for customer modifications) instead.

**Comment by ebrouen** [comment]
Thank you for your answer but it is not the goal. The debugger is not necessary the programmer...

**Comment by SLaks** [comment]
Yes, but the debugger should still have access to source control history.

**Comment by ebrouen** [comment]
Let's say that there is one office (more merely one developer) that add functions to the project, deliver them to (some) customers, and continues like that all the time. 
On the other hand, some people in another branch, are the receiver of bug alerts (by mail, with full dump and access to the assemblies and pdb of the customer).
They don't have access to the source code, and it is not necessary because each error report gives the line number and file where the error occurred. 
If ILSpy show the real line number of source code, they can link it with the error report and give a better support, and most important, they can dialog with the developer with a good base ground...

Example:
The error is (in fact an exception) :
```
Ending VT12 at 12/02/2015 13:06:40
IP Address = 192.168.1.70:0


MySQL .Net Connector must be at least of version 6.7.5
   à VT12.DAL.DataAccessLayer.ServerConnect() dans C:\Users\Eric\Documents\Visual Studio 2010\Projects\VT12\VT12DLL\VT12.DAL.cs:ligne 949
   à VT12.DAL.DataAccessLayer.ServerConnect(String pServerType, String pServerURIName, String pServerUser, String pServerPassword, String pServerDatabaseName) dans C:\Users\Eric\Documents\Visual Studio 2010\Projects\VT12\VT12DLL\VT12.DAL.cs:ligne 798
   à VT12.Core.Configuration.DataBaseConnect(DataAccessLayer oDal) dans C:\Users\Eric\Documents\Visual Studio 2010\Projects\VT12\VT12DLL\VT12.Core.cs:ligne 3699
   à VT12.Program.Main() dans C:\Users\Eric\Documents\Visual Studio 2010\Projects\VT12\VT12\Program.cs:ligne 228
   à System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   à System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   à Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()
```

and ILSpy give me the following code

```
	case DataAccessLayer.DataBaseProvider.MySQL:
	{
		Version version = AssemblyName.GetAssemblyName("MySQL.Data.dll").Version;
		if (version.CompareTo(new Version("6.7.5.0")) < 0)
		{
			throw new PDSException("MySQL .Net Connector must be at least of version 6.7.5")
			{
				DontRestartApplication = true
			};
		}
```
with lines between 84 and 93.

In this example, I have only one case with this exception, but sometimes, because the exception is not handled, I can have more possibilities of errors.
With the real line number, I could debug the solution starting from the dump, till the source code. 
I hope that my explanation is clear enough....

**Comment by molnargab** [comment]
I have to use `ildasm` when I need to check line numbers for an assembly. It would be nice to have this feature in ILSpy as well.

**Comment by linquize** [comment]
How this relates to ILSpy?

**Comment by molnargab** [comment]
I use both tools to decompile assemblies. ILSpy is great for me, if I want to check what IL code is compiled, though when I want to track that back to the C# source, I need to open up `ildasm` to display line numbers from the PDB.

So in my case, if ILSpy displayed the line numbers, I wouldn't need to use `ildasm` at all.

**Comment by dgrunwald** [comment]
ILSpy 3 now has an option "Show info from debug symbols, if avaiable". If this is checked, the IL view (and the "IL with C#" view) will show sequence points from the .pdb.

**Comment by dgrunwald** [comment]
I think the ILSpy sequence points solve this issue.
