### ISSUE TITLE
ILSpy can't find any "Overridden By" methods

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#537]
1. View the System.Windows.Markup.Primitives.MarkupObject class in the WindowsBase assembly.
2. Right click on the "GetProperties(bool)" method
3. Click on Analyze
4. Try to expand "Overridden By"

No methods will appear.

If you go to all the derived types of MarkupObject (make sure ILSpy is configured to show internal types), you will see that they all override that method.

**Comment by EdHarvey** [comment]
Overriding methods were not shown because the base method was marked
'internal' and so would normally only be visible within its own
assembly.
However the assembly had a InternalsVisibleToAttribute specified which
allowed access from the assembly containing the derived types....
