### ISSUE TITLE
Support event fields better in the UI

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#540]
- e.g. `System.Windows.Interop.HwndSource`'s `PublicHooksFilterMessage` method in the "PresentationCore.dll" assembly there is a line:

``` C#
if (this._hooks != null)
```

I expect left clicking on the `_hooks` in the editor to take you to the event handler field:

``` C#
// System.Windows.Interop.HwndSource
private event HwndSourceHook _hooks;
```

Instead ILSpy does nothing.
- if you right click on the `_hooks` in the editor, and click on "Analyze", it will show "Read By" and "Assigned By" of the internal delegate that backs the event field, rather than the "add", "remove", "Raised By" of the event itself.
- ILSpy should add "Assigned By" and "Read By" to event fields which track places in the code that use the `foo.SomeEvent.SomeDelegateMethod()`, `==`, `!=`, `=` operators, etc. on the internal backing delegate (the `+=` and `-=` operators and `add_SomeEvent`/`remove_SomeEvent` should be filtered out of that list).

**Comment by siegfriedpammer** [comment]
I am not sure what you want us to implement in your last paragraph. Could you please give an example of how it should look like... Do you want us to add "Assigned By" and "Read By" as analyzers for auto events?

**Comment by EdHarvey** [comment]
I've been working on a solution to the event<->delegate mapping as part of some general enhancements to the analysis functions.
I should have "Assigned By" and "Read By" finished within the next couple of days....

**Comment by DerpMcDerp** [comment]
> Do you want us to add "Assigned By" and "Read By" as analyzers for auto events?

Yes. It should detect all places (except for the compiler generated foo.add_SomeEvent and foo.remove_SomeEvent methods) where constructs like the following appear:

foo.SomeEvent != null
foo.SomeEvent = whatever
foo.SomeEvent.SomedDlegateMethod()

but not:

foo.SomeEvent += whatever
foo.SomeEvent -= whatever
foo.SomeEvent(whatever)

since those are already handled by the "add", "remove", "Raised By" analyzers.

**Comment by siegfriedpammer** [comment]
@EdHarvey we are planning to release 2.3 by Monday next week. Any chance you might get this finished by then?

**Comment by EdHarvey** [comment]
Doubtful... I'm a bit pressed on available time over the next week, and I have some higher priority stuff that I'd like to get finished before 2.3

**Comment by siegfriedpammer** [comment]
OK... are there any open issues, you are working on? I'd like to add them to the 2.3 Milestone so we have some documentation on what's been done in this release. I will remove this one from the 2.3 milestone.

**Comment by siegfriedpammer** [comment]
@EdHarvey did you make any progress with this?

**Comment by dgrunwald** [comment]
Related issue for the event analyzers: #199

**Comment by siegfriedpammer** [comment]
See comment https://github.com/icsharpcode/ILSpy/issues/199#issuecomment-405378919

I consider this fixed.
