### ISSUE TITLE
int vs uint enum decompiling confusion

### ISSUE THREAD

**Issue by MWisBest** [icsharpcode/ILSpy#541]
There appears to be some confusion in decompiling an enum specified as uint, e.x.
```c#
public enum SomeEnum : uint
```

Specifically, this code:
```c#
public enum b2 : uint
{
	b = 3418120847,
	c = 1586957500,
	d = 2383490743
}
```
Will be decompiled to:
```c#
public enum b2 : uint
{
	b = -876846449,
	c = 1586957500,
	d = -1911476553
}
```
Adding 2147483648 (INT_MAX + 1) gets the proper value back of the negative numbers. It would appear that ILSpy decompiles the numbers to what their value would be if they were int, and not their uint values?

**Comment by siegfriedpammer** [comment]
I cannot reproduce this using the most recent version compiled from source.

The enum is decompiled as

```csharp
public enum b2 : uint
{
    b = 3418120847u,
    c = 1586957500u,
    d = 2383490743u
}
```
which seems to be correct.

**Comment by MWisBest** [comment]
The sample was pulled from a larger program, so maybe it's something else in there causing the mix-up; I'll double-check and get back to you when time permits. Thanks!

**Comment by 0xd4d** [comment]
This is the relevant line: https://github.com/icsharpcode/ILSpy/blob/master/ICSharpCode.Decompiler/Ast/AstBuilder.cs#L336

The constant is an Int32 even though it's an enum derived from UInt32. The file has been obfuscated with Dotfuscator.
