### ISSUE TITLE
Find text should search again when editor's text is changed

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#544]
e.g.

1. Go to `System.RuntimeType`'s `Assembly` member
2. Push ctrl+F and search for the string "assembly"
3. Go to the `AssemblyQualifiedName` member

I expect ILSpy to re-search the found text but instead ILSpy uses the old found text positions from the `Assembly` buffer.

A similar thing happens, when you navigate through history with the "Back" and "Forward" buttons.

(Also, I don't want to open a new bug for this but all the grid splitters and the close button on the ctrl+F panel should have Focusable = false).

**Comment by siegfriedpammer** [comment]
I think the first issue you mention was fixed in the most recent nightly release. Can you please check a nightly build from http://build.sharpdevelop.net/BuildArtefacts/#ILSpyMaster?

**Comment by DerpMcDerp** [comment]
The latest nightly does fix this issue. However I found one problem:

If you search for something and use the "back" and "forward" buttons on the mouse to navigate through history (I guess Mouse.XButton1 and Mouse.XButton2) and the text cannot be found, ILSpy will display a "No matches found!" tooltip which seems to steal focus from the mouse preventing you from using those mouse buttons to navigate until you dismiss the tooltip.

As an easy workaround, you can make the background of edit field of the find dialog turn red similar to how firefox does it if nothing is found instead of displaying a tooltip.

**Comment by siegfriedpammer** [comment]
Not sure if this will happen for the next release. The tooltip is implemented in AvalonEdit, which currently doesn't support other means of notification. Sadly I don't own a mouse with fancy buttons, so it won't be easy to reproduce the issue...

**Comment by DerpMcDerp** [comment]
I've written a PowerShell script which injects a hardware XButton1 (i.e. the mouse's "back" button) click every ~3 seconds which may help you reproduce it:

```PowerShell
# first, add the P/Invoke to your PowerShell session
Add-Type -TypeDefinition @'
public class user32 {
[System.Runtime.InteropServices.DllImport("user32.dll")]
public static extern void mouse_event(uint flags, uint dx, uint dy, uint data, System.IntPtr extra);
}
'@
```

Then just run this infinite loop (push ctrl+c to break it)

```PowerShell
for(;;){ sleep -m 2700 ; 0x80,0x100 |%{ [user32]::mouse_event($_, 0,0,1,0) ; sleep -m 150 }}
```

**Comment by siegfriedpammer** [comment]
Thanks for providing the necessary steps. I was able to fix the issue.
