### ISSUE TITLE
ILSpy's linking behavior needs a little tweaking for attributes

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#545]
e.g. view `System.ModuleHandle`'s `_ContainsPropertyMatchingHash` method:

``` C#
// System.ModuleHandle
[SecurityCritical, SuppressUnmanagedCodeSecurity]
[DllImport("QCall", CharSet = CharSet.Unicode)]
private static extern bool _ContainsPropertyMatchingHash(RuntimeModule module, int propertyToken, uint hash);
```

I expect:
- `CharSet` on the lhs to link to the `CharSet` attribute of DllImport
- `CharSet` on the rhs to link to the `CharSet` enum
- `Unicode` to link to the `Unicode` field
- `(` and `)` on `DllImport` to link to the appropriate DllImportAttribute constructor

**Comment by dgrunwald** [comment]
Triage: `newdecompiler` added the `CharSet` enum link on the rhs; all the other links are still missing.
