### ISSUE TITLE
"Instantiated By" doesn't appear on System.Text.RegularExpressions.RegexParser

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#548]
It has a `.ctor` which "Used By" displays 3 places.

**Comment by EdHarvey** [comment]
Interesting case: The class has no public constructor, but is instantiated by its static members...

The original test for the "Instantiated By" node visibility excluded any class without a public constructor because this was the code pattern used for 'static' classes in Net v1.
