### ISSUE TITLE
various minor UI annoyances

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#553]
- [x] the close button on the AvalonEdit's Ctrl+F find panel should have Focusable = false
- [x] the grid splitters should have Focusable = false
- [x] clicking on a variable in the AvalonEdit control highlights all instances of that variable. There should be a way to unhighlight by clicking on something else
- [ ] identifier links in the AvalonEdit control use left mouse down rather than left mouse click to navigate. This makes it difficult to select certain text using the mouse. What AvalonEdit should do is on left mouse down, begin selecting text and keep track of the position the mouse cursor was on, on left mouse up, if the cursor position is the same, navigate you to the link, otherwise do nothing.
- [x] there should be a "Copy" menu item in the AvalonEdit's popup menu among the "Toggle Folding" menu items
- [ ] there should be a "Select All" menu item in the AvalonEdit's popup menu below the "Copy" menu item
- [x] right clicking on an item in the search for types list should display an "Analyze" popup menu
- [x] the search for types hotkey should be ~~Ctrl+K~~ `Ctrl+Shift+F` rather than `F3` since it conflicts with the AvalonEdit's "find next" (this is similar to what the Thunderbird and Firefox do because they has multiple find panels)
- [x] pushing ~~Ctrl+K~~ `Ctrl+Shift+F` while the focus is anywhere should open the search for types panel. Ditto for the `Ctrl+F` find panel
- [x] ~~if the search for types edit field is focused and all its text is selected, pushing Ctrl+K should close the search panel (in other words,Ctrl+K `Ctrl+Shift+F` should act like a toggle). Ditto for the `Ctrl+F` find panel~~
- [ ] the margins on the grid splitters should be tweaked. They overflow onto the treeview's scrollbar and AvalonEdit window and interfere with scrolling and mouse selection sometimes.
- [ ] there should be a setting to format the source using K&R C brace style to minimize vertical space

**Comment by siegfriedpammer** [comment]
Why don't you want to close button to be focusable?

**Comment by DerpMcDerp** [comment]
OCD. Seeing the focus ring whenever the close button is clicked is jarring to me.

**Comment by weltkante** [comment]
@DerpMcDerp What? Mouse input shouldn't trigger focus rectangles, you only get these when using keyboard (tab) to navigate. And when I use the keyboard I expect to tab into the close button.

**Comment by siegfriedpammer** [comment]
I guess the focus rectangle is not much of a problem. I will not implement your suggestion...

**Comment by DerpMcDerp** [comment]
@weltkante Go to "Control Panel > Ease of Access Center > Change how your keyboard works" and then turn on the "Underline keyboard shortcuts and access keys" option. When that setting is enabled, clicking on buttons that have Focusable = true will display a focus ring.

Why would you expect tab to navigate to the close button? No other program with a find panel UI does that, they all use ESC to close (some also have Ctrl+F to toggle) and not let you keyboard navigate to the close button.

**Comment by siegfriedpammer** [comment]
Why `Ctrl+K`? I'd prefer `Ctrl+F` for text search and `Ctrl+Shift+F` for the types/members search.

**Comment by siegfriedpammer** [comment]
As for the idea of toggling: I'd prefer `Ctrl+F` to reactivate the search panel, if it's already open, that is, keep the current behavior, which matches Firefox.

**Comment by weltkante** [comment]
@DerpMcDerp when I turn that setting on I'd expect a focus rectangle on the close button. Thats what it does after all with almost everything else, and fixing it here would (IMHO) introduce nonstandard behavior. About why I'd expect to tab into the close button? well the programs *I* use are allowing that so I'm used to it, but meh, escape or ctrl+F toggle would probably work just as well.

I don't really care that much as long as its easily closable by keyboard, just found it odd to work around standard framework behavior without giving any justifications. Smells like adjusting the program to your personal tastes instead of keeping it in line with common behavior of other applications people might be used to, like VS or browsers.

**Comment by DerpMcDerp** [comment]
> As for the idea of toggling: I'd prefer Ctrl+F to reactivate the search panel, if it's already open

Toggling should only toggle if the search panel's edit control is focused and all its text is selected. Otherwise it should behave exactly as it does now.

**Comment by whut** [comment]
I used F3 shortcut to search long before ILSpy was created, in the days of free Reflector. Probably not only for me it is a surprise to see it is not working in v2.3.But after reading this issue, I finally understand why F3 sometimes didn't work before 2.3, so big thanks for fixing it by introducing a different shortcut.

BTW: "Find" could also use Ctrl + , (comma) like Visual Studio "find symbol".

**Comment by siegfriedpammer** [comment]
I am closing this, if you really think you need the other items from your list, please open separate issues.
