### ISSUE TITLE
ILSpy misses "fixed" statements in a few cases

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#566]
ILSpy doesn't recognize the `fixed (char* ptr = chars)` pattern in `System.Text.ASCIIEncoding`'s methods:

`GetByteCount(string chars)`
`GetBytes(string chars, int charIndex, int charCount, byte[] bytes, int byteIndex)`

**Comment by dgrunwald** [comment]
Seems to be fixed on the newdecompiler branch.
