### ISSUE TITLE
Improve the display of namespaces and nested classes

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#577]
- [ ] It's difficult to tell what's a namespace and what's an outer class in certain places. ILSpy should help out by using "+" instead of "." to separate nested classes there.
- [ ] There are places where the namespace and/or outer class should be stripped off to minimize horizontal space.

![nested_and_ns2](https://cloud.githubusercontent.com/assets/8602394/6764211/fe747a7c-cf62-11e4-80e3-56fca9acf046.png)

**Comment by siegfriedpammer** [comment]
I don't think it's a good idea to use `+` as separator for type names in C#.

The namespaces in the name of explicit interface implementations are generated by the compiler. Without doing expensive analysis while loading the assembly, we cannot remove the namespace.
