### ISSUE TITLE
Collapse All button for the assemblies list

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#582]
It would be nice to have a **Collapse All** command for the list of assemblies. I think a perfect place for this would be a toolbar at the top of the list of assemblies (not the main toolbar), but if that's not possible it would work as a menu command or other button.

**Comment by siegfriedpammer** [comment]
@sharwell 
> I think a perfect place for this would be a toolbar at the top of the list of assemblies (not the main toolbar)

I think adding a second toolbar directly below the main toolbar does not make sense. It would not look nice:
![grafik](https://user-images.githubusercontent.com/344204/30469812-79fee108-99f2-11e7-86b2-54f5a129a34b.png)

Unless we add something like a header to the tree view (to separate it from the main toolbar), I think adding the command to the main tool is just fine. Any more thoughts?
