### ISSUE TITLE
Formatting for attributes

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#584]
Currently the decompiled output lists outputs in the following form:

``` csharp
[Attribute1, Attribute2, ...]
```

It would be nice, either by default or as an option, to support this form instead:

``` csharp
[Attribute1]
[Attribute2]
...
```

This is particularly noticable for things like this. VSPackage implementations are even worse with their registration attributes.

```
[MarginContainer("LeftSelection"), TextViewRole("INTERACTIVE"), ContentType("text"), Name("Coverage Margin"), Order(Before = "LineNumber"), Export(typeof(IWpfTextViewMarginProvider))]
```

**Comment by siegfriedpammer** [comment]
This is the default behavior of the new decompiler (which just landed on the master branch).
