### ISSUE TITLE
Analyze doesn't seem to work across assemblies

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#585]
e.g. in the `System.Windows.Controls.Toolbar.cctor()` method there are two lines:

``` C#
UIElement.FocusableProperty.OverrideMetadata(typeof(ToolBar), new FrameworkPropertyMetadata(BooleanBoxes.FalseBox));
...
FocusManager.IsFocusScopeProperty.OverrideMetadata(typeof(ToolBar), new FrameworkPropertyMetadata(BooleanBoxes.TrueBox));
```

If you right click on `FocusableProperty` or `IsFocusScopeProperty` and click on "Analyze", ILSpy does nothing. It seems like ILSpy doesn't work across assembly boundaries since:
- `System.Windows.Controls.Toolbar` is in the `PresentationFramework.dll` assembly
- `UIElement.FocusableProperty` and `FocusManager.IsFocusScopeProperty` are in the `PresentationCore.dll` assembly

Also, the tooltips for those properties are strange:

`FocusableProperty`'s tooltip displays:
`System.Windows.DependencyProperty System.Windows.UIElement::FocusableProperty`
rather than the expected:
`public static readonly DependencyProperty FocusableProperty`.

`IsFocusScopeProperty`'s tooltip displays:
`System.Windows.DependencyProperty System.Windows.Input.FocusManager::IsFocusScopeProperty`
rather than the expected:
`public static readonly DependencyProperty IsFocusScopeProperty`.

**Comment by EdHarvey** [comment]
reverse Github auto-close

**Comment by EdHarvey** [comment]
Analyze should now be ok.

I'll leave the tooltip issue to someone more qualified :smiley:

**Comment by siegfriedpammer** [comment]
The tooltip issue seems to be fixed long ago.
