### ISSUE TITLE
how to make c# result have better format?

### ISSUE THREAD

**Issue by gnemoug** [icsharpcode/ILSpy#589]
ILspy is a amazing tool, but when I use it decompile dll, I have result like this:
```
this.lastOrientation = base.get_Orientation();
```
but what it should be is like this:
```
this.lastOrientation = base.Orientation;
```

how can I get the better result?

**Comment by dgrunwald** [comment]
Ensure that the assembly that containing 'Orientation' property is also loaded in ILSpy.

**Comment by gnemoug** [comment]
It should be a property like 
```
        private void InitializeUI()
        {
            this.OnOffBattery.Source = this.batteryOffImage;
            this.OnOffImage.Source = this.offImage;
            this.SosImage.Source = this.sosOffImage;
            this.BtnMenu.Source = this.MenuOffImage;
            this.lastOrientation = base.Orientation;
        }
```
but  the decompile result is like this
```
		private void InitializeUI()
		{
			this.OnOffBattery.set_Source(this.batteryOffImage);
			this.OnOffImage.set_Source(this.offImage);
			this.SosImage.set_Source(this.sosOffImage);
			this.BtnMenu.set_Source(this.MenuOffImage);
			this.lastOrientation = base.get_Orientation();
		}
```

**Comment by dgrunwald** [comment]
ILSpy will correctly decompile the usage of properties *if it can find the property definition*. If the property definition is unavailable because the assembly defining the property cannot be found, it is impossible to tell the difference between property setters and normal methods.
