### ISSUE TITLE
Idle time usage CPU

### ISSUE THREAD

**Issue by bprg** [icsharpcode/ILSpy#593]
ILSpy Idle time usage CPU. OS Win8.1 x64

**Comment by linquize** [comment]
What is your problem? Do you mean high CPU usage during idle time?

**Comment by bprg** [comment]
Yes.

**Comment by pista7** [comment]
It is especially visible running inside a VM, at least with VMWare Fusion - without ILSpy, the vmware-vmx (host) process idles at around 10%, with ILSpy running it rarely goes under 80% (note that on OS X 100% means one core, not the entire CPU running at full load). This is on an i7-4870HQ (MBP 15" Mid 2014)

**Comment by linquize** [comment]
Which ILSpy version?
How many, what assemblies did you visit?
What else did you do in ILSpy?

**Comment by pista7** [comment]
ILSpy version 2.3.1.1855 (should be the latest)

It happens even with the assembly list completely empty, immediately after launching. Please note that the process on the windows side uses only around 2% (I have four cores assigned, so it corresponds to roughly 10% of one CPU). However, I believe there is some background process that wakes the CPU very often for extremely short periods, which causes it to consume disproportionately more CPU power as it appears on the VM host side.

**Comment by linquize** [comment]
Is it doing network operation?

**Comment by pista7** [comment]
None at all.

However, I've tried attaching a profiler to the process and it seems to be WPF related - the entire call tree is WPF-internal pumping of messages. Looking through Spy++, there are hundreds of "MilChannelNotify" and "DispatcherProcessQueue" messages processed per second. Have you ever seen such a problem?

**Comment by linquize** [comment]
How do you attach the profiler?

**Comment by pista7** [comment]
I've ran it from the command line with COMPLUS_ZapDisable=1 to avoid using NGen-ed native images (prevents successful symbol loading), then attach VS2015 profiler (Debug > Profiler > Performance Explorer > Attach/Detach...)

**Comment by weltkante** [comment]
MilChannelNotify is a window message to communicate with the WPF render thread. Normally WPF should stop rendering if the UI is not dirty and there are no animations requiring continuous rendering.

Unfortunately a profiler will not help you figuring out what WPF and the rendering thread are communicating. There are ETW events defined for WPF, maybe listening to them would shed some light into this, but I never done this myself yet.

Unless ILSpy is animating controls or something like that, I don't think this is an ILSpy issue.

**Comment by 0xd4d** [comment]
This is a problem with the texteditor's progressbar. You can set its IsIndeterminate property to false when it's hidden or remove it completely. IsEnabled=false might also work.

**Comment by dgrunwald** [comment]
Whoa, good find @0xd4d.
A control in a container with `Visibility=Collapsed` still gets animated? I'd call that a WPF bug.

Setting `IsEnabled=false` doesn't help, the progress bar still causes WPF to render at 60 FPS. Setting `IsIndeterminate = false` while the progress bar is invisible solves the problem: the frame rate goes down to 2 FPS (if the caret is blinking) or 0 FPS if the editor doesn't have the focus.

**Comment by dgrunwald** [comment]
By the way, the "WPF Performance Suite" (wpfperf.exe, part of the Windows SDK I think) can be used to debug this kind of issue -- the option "Show dirty-region update overlay" clearly shows the progress bar as culprit.

**Comment by pista7** [comment]
Wow guys, that was quick! Thanks a lot!

As for the WPF Performance Suite - I've tried to get ahold of it for quite some time today but couldn't find any other way than installing the Windows 7 SDK which unfortunately installs only on W7 and I don't have a W7 VM handy. I there a direct download or something? Sorry if this is way off-topic.

**Comment by weltkante** [comment]
@dgrunwald That tool only works up to Win7 and is no longer supported. The application timeline in the VS 2015 profiler provides a partial replacement. You have to add missing ProjectTypeGuids to the project file to be able to use it though (see [the last comment in this post](https://blogs.msdn.microsoft.com/wpf/2015/01/16/new-ui-performance-analysis-tool-for-wpf-applications/))

> A control in a container with Visibility=Collapsed still gets animated? I'd call that a WPF bug.

This actually looks like a really nasty bug, not limited to Visibility=Collapsed. I made a test application with just a panel and a progress bar, once the progress bar starts animating WPF will never drop back out of 60 fps rendering, *even if I remove the progress bar from the visual tree and have it garbage collected* (I verified that the objects are gone via heap snapshots). It will stop invalidating the visual tree but it still renders at 60 fps. The only way to get out of 60 fps rendering is by explicitely turning the animation on the progress bar off by setting IsIndeterminate=false.

So if you ever have an animated object garbage collected WPF could be stuck in 60 fps mode. At least my test application seems to do.
