### ISSUE TITLE
Browse to type in Visual Studio

### ISSUE THREAD

**Issue by migig** [icsharpcode/ILSpy#599]
The latest additions to the VS addin are great, but the one obvious missing feature is:

right click a type in the editor,
context menu should show "Browse in ILSpy",
after click, takes you to the decompiled source for that type

**Comment by yoyobbi** [comment]
And not just types, but members too. Including overloaded methods and those with generic type parameters. For example, given this class:
`class MyClass
{
    void MyMethod<T>(T arg)
    {
        ...
    }
}`

This command line works great:
`ILSpy.exe MyAssembly.dll /navigateTo:M:MyClass.MyMethod``1(``0)`

I would love the equivalent capability in the Visual Studio context menu. Basically anywhere I can right-click and "Go To Definition" I want to be able to "Go To IlSpy".

**Comment by MarekPokornyOva** [comment]
Maybe you would like to try:
https://marketplace.visualstudio.com/items?itemName=MarekPokornyOVA.GoToILSpyforVS2015
https://gotoilspy.codeplex.com/

**Comment by siegfriedpammer** [comment]
@MarekPokornyOva you are aware of the ILSpy extension provided by ILSpy? Would you mind sharing/integrating your code into the official VS Extension?

**Comment by MarekPokornyOva** [comment]
Hi Siegfried,
I'd be honored if you include the extension into your official code/package. But please understand, this version is first beta and there're still places to be improved.
If you don't mind about these non-final points, feel free and include the extension.

Also, don't hesitate to contact me if you find some topic to discuss.
  ----- Original Message -----

**Comment by exyi** [comment]
Btw I just found a Roslyn interface that generates source from metadata http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/MetadataAsSource/IMetadataAsSourceService.cs,ee8ba724e4557ada , it would be cool to have a ILSpy powered implementation. I can look at it if you also think that it's good idea.

**Comment by siegfriedpammer** [comment]
I would like to include your code directly into the extension (i.e. merge), not just distribute your executable alongside ILSpy, if that's OK with you.

**Comment by MarekPokornyOva** [comment]
Siegfried,
I allow/grant you to copy/merge/use/whatever any piece or all the content of GoToILSpy extension and include/build-in it to your ILSpy tool/extension.

I'll (but maybe I won't) decide if to remove the separated GoToILSpy extension distribution pack/pages.

**Comment by bbi-yggy** [comment]
Note that #706 is the final PR in a series of changes that implements the ability to browse to any code in ILSpy. So for types of your own implementation, you can "Go to definition" and then "Open in ILSpy".

**Comment by siegfriedpammer** [comment]
With the recent fixes to the VS AddIn and our integration into Roslyn, I believe this can be closed.
