### ISSUE TITLE
CodeDOM tree from an assembly

### ISSUE THREAD

**Issue by deostroll** [icsharpcode/ILSpy#602]
Is it possible to get a System.CodeDOM.CodeCompileUnit from an assembly using ilspy?

My goal is in modifying the assembly for instrumentation purposes...which is a bit of overkill I know...but...anyway...would like to have one such feature...

**Comment by dgrunwald** [comment]
System.CodeDOM cannot represent many C# constructs; it's not really usable for anything except simple code generators.

`ICSharpCode.Decompiler` can give you an `ICSharpCode.NRefactory.CSharp.SyntaxTree` for the decompiled code. But note that ILSpy's decompiler isn't perfect, and sometimes produces invalid C# or C# with slightly different semantics. For instrumentation, it's probably best to directly modify the IL code (e.g. using `Mono.Cecil`).

**Comment by linquize** [comment]
System.CodeDOM is OK for 2.0 syntax, but fails to evolve to newer C# versions.
