### ISSUE TITLE
Suggestion: Display public key used for signing assembly.

### ISSUE THREAD

**Issue by DumboJet** [icsharpcode/ILSpy#610]
I think it would be handy if you could provide a way to display the public key used for signing each assembly.
From a first look, you don't do that yet.
I think this is possible using this command line:

```
sn -Tp YourAssembly.dll
```

..but having it in ILSpy would be good. :)

Thanks for the great free tool. :)

**Comment by junderhill** [comment]
@DumboJet  Are you refering to the public key token or the entire public key? If it's just the token it is displayed when hovering over an assembly. See here..
![2015-06-11_14-14-59](https://cloud.githubusercontent.com/assets/838529/8107849/61e2e338-1044-11e5-82aa-0a1fcbc7f6cd.png)

If it is the entire key you are refering to I can't see it being difficult to make available..

**Comment by DumboJet** [comment]
I mean the entire public key.
It would be handy to have, I think. :)

**Comment by junderhill** [comment]
OK, I'll have a look at this

**Comment by junderhill** [comment]
Something like this perhaps?
![2015-06-11_15-15-04](https://cloud.githubusercontent.com/assets/838529/8109083/d6a046fe-104c-11e5-89b6-76c483aa3e06.png)

**Comment by DumboJet** [comment]
Yes, that seems the correct info.
This can be verified with SN.exe, if I am not mistaken:

```
sn –T myDLL.dll
```

If there was a way to copy it too, it might be even more cooler. :)

**Comment by junderhill** [comment]
That's the other thing I was thinking of. It verifies correctly so I'm happy it is displaying the correct data but the ability to copy would definitely be useful. Leave it with me.

**Comment by junderhill** [comment]
Ok I've implemented this on the right click context menu for assemblys as follows:
![2015-06-11_17-11-45](https://cloud.githubusercontent.com/assets/838529/8112045/3e0c8c7a-105d-11e5-88e4-fe4e10669925.png)

**Comment by DumboJet** [comment]
Cool ! :)
Thanks a lot ! :)
