### ISSUE TITLE
Feature some way to organize assembly list

### ISSUE THREAD

**Issue by jho1965us** [icsharpcode/ILSpy#611]
e.g. 
one should be able to group assemblies in folders (like solution folders)
one should be able to save/load the list of assemblies

**Comment by siegfriedpammer** [comment]
ILSpy already has a way to manage assembly lists - see `File > Open List...`
I have to think about grouping assemblies - I don't know if they are useful enough to justify all the work.

**Comment by siegfriedpammer** [comment]
Assembly Lists are now much easier to use. Closing this.
