### ISSUE TITLE
Bug in decompiling try/catch + async/await (VS 2015)

### ISSUE THREAD

**Issue by weltkante** [icsharpcode/ILSpy#612]
Following code produces nonsense results when decompiled with ILSpy. (using VS 2015 RC, release build, targetting .NET 4.6 -- in case it matters)
```csharp
async Task InvokeAsync(List<Func<object, Task>> handlers, object data)
{
    List<Exception> exceptions = null;

    for (int i = 0; i < handlers.Count; i++)
    {
        var handler = handlers[i];

        try
        {
            await handler(data);
        }
        catch (Exception exception)
        {
            if (exceptions == null)
                exceptions = new List<Exception>();

            exceptions.Add(exception);
        }
    }

    if (exceptions != null)
        throw new AggregateException(exceptions);
}
```
The analyzer for the async/await state machine gets confused by the try/catch block and loses track of the state variable. This causes fragments of the state machine not being erased and showing up in the decompiled output. I'll submit a proposed fix.

**Comment by dgrunwald** [comment]
Nice catch!

Thanks for the patch.
