### ISSUE TITLE
enumeration missing EnumMember data contract attributes in decompiled C#

### ISSUE THREAD

**Issue by mikofski** [icsharpcode/ILSpy#619]
decompiled code is ...

    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.Serialization;
    namespace SunPower.MatlabDataService
    {
        [GeneratedCode("System.Runtime.Serialization", "4.0.0.0"), DataContract(Name = "EOperationStatus", Namespace = "")]
        public enum EOperationStatus
        {
            Success,
            Fail
        }
    }

... but should be ...

    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.Serialization;
    namespace SunPower.MatlabDataService
    {
        [GeneratedCode("System.Runtime.Serialization", "4.0.0.0"), DataContract(Name = "EOperationStatus", Namespace = "")]
        public enum EOperationStatus
        {
            [EnumMember]
            Success,
            [EnumMember]
            Fail
        }
    }

### references
* https://msdn.microsoft.com/en-us/library/system.runtime.serialization.enummemberattribute(v=vs.110).aspx
* https://msdn.microsoft.com/en-us/library/aa347875(v=vs.110).aspx
* https://msdn.microsoft.com/en-us/library/system.runtime.serialization.enummemberattribute.value(v=vs.110).aspx

**Comment by mikofski** [comment]
the attributes _are_ shown correctly in the view for each enumeration member

![enum member](https://cloud.githubusercontent.com/assets/1385621/8440962/6aebf2a4-1f2a-11e5-98c4-ddfff4ca830d.PNG)

it's just in the generated code for the enumeration where the attributes are missing

![enumeration](https://cloud.githubusercontent.com/assets/1385621/8441057/cbc8000e-1f2a-11e5-9677-b464a2eb8810.PNG)

**Comment by LordJZ** [comment]
Any attribute actually.
