### ISSUE TITLE
Crash when saving XML resources : System.ObjectDisposedException: Cannot access a closed Stream

### ISSUE THREAD

**Issue by rustyx** [icsharpcode/ILSpy#622]
I'm unable to save (Ctrl-S) any XML resources like a StringTable, ILSpy (any version, including 2.3.0.1827) crashes with:

    System.ObjectDisposedException: Cannot access a closed Stream.
    ...
    at ILSpy.ResourceEntryNode.Save
    ...

**Comment by siegfriedpammer** [comment]
Cannot reproduce the exception using the most recent version. Seems it's already fixed. The shortened stacktrace you provided is not of much help, unfortunately.
