### ISSUE TITLE
Feature Request: Make analyzer window types public

### ISSUE THREAD

**Issue by abk-x** [icsharpcode/ILSpy#623]
Hello,

Designing a plugin that wants to send some analysis results to the 'analyze' window, however the types that are used to add to the analyzer window require some types that are 'internal' e.g. 'AnalyzedMethodTreeNode' in the following file  https://github.com/icsharpcode/ILSpy/blob/fc6387934df91c99129980158b08d353b1bccb9e/ILSpy/TreeNodes/Analyzer/AnalyzedMethodTreeNode.cs

I tested by changing this to public, and I can now access this type.

Edit: however, when I now add a method to the analyzer window using my plugin, it seems I can expand the children of this method, but I cannot double click on the method to make it scope to the disassembly (???), I guess my hack of changing stuff to public doesn't immediately solve the issue (there is probably some dependency not being loaded first), so I suggest that instead of changing the visibility of the types, that a supported way to add to the analyzer window is investigated.. (maybe there is already!)

Edit2: worked it out, it seems you cant just use any Cecil type, you need to use the type that is in the TreeNode:

```
            var nodes = context.SelectedTreeNodes;
            foreach (AssemblyTreeNode node in nodes) 
            {
                var binaryPathFull = node.LoadedAssembly.AssemblyDefinition.MainModule.FullyQualifiedName;
                var classMethodMap = XX.csharpILSpyInteropGetX(binaryPathFull);

                if (classMethodMap.Length != 0)
                {
                    // we had something that matched

                    foreach (MethodBase mb in classMethodMap)
                    {

                        var types = node.LoadedAssembly.ModuleDefinition.Types;
                        foreach (TypeDefinition type in node.LoadedAssembly.ModuleDefinition.Types)
                        {
                            if (type.Name == mb.DeclaringType.Name)
                                Analyze(type);
                        }

                    }
                }
            }

        }
```

**Comment by dgrunwald** [comment]
See also: #274

**Comment by siegfriedpammer** [comment]
An IAnalyzer API was added in 4.0.
