### ISSUE TITLE
Add option to display metadata token in 10-based or hex format

### ISSUE THREAD

**Issue by Lakmus85** [icsharpcode/ILSpy#628]
Proposition to improve existing feature of displaying the metadata tokens near the members.
Now this functionality works only in one format, while it sometimes useful to be able to switch between decimal and hexadecimal display of that values.

**Comment by fenugrec** [comment]
I would add, on this topic, that it would be nice to have an option (maybe Preferences->Display ?) to select hex or decimal format for literal constants !
