### ISSUE TITLE
StackOverflowException in TypeAnalysis when decompiling System.Web.Configuration.BrowserCapabilitiesFactory.UpProcess()

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/ILSpy#629]
In System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Occurs only when running ILSpy as 64-bit process, not as 32-bit process. Looks like the default stack is simply too small; the ILAst in this method has a nesting level >200.

**Comment by siegfriedpammer** [comment]
This no longer happens with newdecompiler now on master.
