### ISSUE TITLE
VSIX - Support VS2015 (Community Edition)

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/ILSpy#630]
Currently, the vsixmanifest only supports Pro, not Community.

**Comment by sharwell** [comment]
In Visual Studio 2013, Community Edition recognizes "Pro" extensions automatically. Was this behavior changed for Visual Studio 2015?

**Comment by christophwille** [comment]
If this is the default behavior, we're good - but I think we have never actually tested it.

**Comment by siegfriedpammer** [comment]
Seems this is fixed now.
