### ISSUE TITLE
occur OverflowException when save code from dll file

### ISSUE THREAD

**Issue by doodoori2** [icsharpcode/ILSpy#634]
I tried decompile unityengine.dll (version 5.1.2f) for project https://github.com/MattRix/UnityDecompiled
ILSpy(version 2.3.1.1855) success to decompile but failed to save code. 
Here is OverflowException stack information.
https://gist.github.com/doodoori2/3f0a8d075ab4c5368d0a
and you can download unityengine.dll from unity 5.1.2 here (http://unity3d.com/get-unity/download?ref=personal)

**Comment by PLYoung** [comment]
Get this same error. The source files are created but the UnityEngine.csproj file is empty (0 bytes).  I assume that is because of the mentioned error. This was for the UnityEngine.dll in Unity 5.3 x64.

**Comment by siegfriedpammer** [comment]
fixed by a6ae2e4b24241ad8a4430f3aa55f99ca934f69b3
