### ISSUE TITLE
Decompiling error

### ISSUE THREAD

**Issue by salucci** [icsharpcode/ILSpy#641]
I want to open an .exe, tryed a couple of stuff around and other decompiling tools but seems to be that file is locked

on other tools I'm getting access denied error, on ILspy I'm getting this:

System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em Mono.Cecil.PE.ByteBuffer.ReadByte()
   em Mono.Cecil.PE.ByteBuffer.ReadCompressedUInt32()
   em Mono.Cecil.SignatureReader..ctor(UInt32 blob, MetadataReader reader)
   em Mono.Cecil.MetadataReader.ReadMethod(UInt32 method_rid, Collection`1 methods)
   em Mono.Cecil.MetadataReader.ReadMethods(TypeDefinition type)
   em Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   em Mono.Cecil.TypeDefinition.get_Methods()
   em Mono.Cecil.MetadataReader.LookupMethod(UInt32 rid)
   em Mono.Cecil.MetadataReader.ReadEntryPoint()
   em Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   em Mono.Cecil.ModuleDefinition.get_EntryPoint()
   em ICSharpCode.ILSpy.CSharpLanguage.DecompileAssembly(LoadedAssembly assembly, ITextOutput output, DecompilationOptions options)
   em ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
   em ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   em ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15()

any Idea? I can upload .exe if needed
[]'s

**Comment by weltkante** [comment]
Thats odd, it doesn't crash in ILSpy decompiling, but when loading the file. Basically it either means you found a bug in the Mono file loader (unlikely) or the file is corrupted.

Or it might be "obfuscated" and contain intentionally corrupted methods which are never executed but the decompiler fails because when you click on a class it loads all methods of that class, including the corrupt ones.

**Comment by salucci** [comment]
hm, I think it's the second option, cause the .exe is usable, and deObsfucation algothims are already know, like de4dot deObfsucator(the .exe is c# vs made), anyway your tip about intentionally corrupted methods was very helpfull, thx

**Comment by weltkante** [comment]
If it's indeed obfuscation you are probably on your own here. If you really need to look into that file you could try to preprocess it, for example removing the corrupted methods, and see what you can make from the remaining data.

**Comment by salucci** [comment]
IDA hex rays can load, reCompile and then the file is funtional and brand new, but the assembly code when loaded is so much weird, 99% of instructions are things like:
seg000:00022022                 db  10h
seg000:00022023                 db  6Ch ; l
seg000:00022024                 db 0BDh ; ¢
seg000:00022025                 db    9
seg000:00022026                 db  53h ; S

I just meet stuff like jz, cjne, R0,ACC and etc, like on this:
http://www.8052.com/set8051.phtml
I'll try to find something around
anyway, thx a lot

**Comment by siegfriedpammer** [comment]
Closing, because there's nothing we could fix here.
