### ISSUE TITLE
(are you missing a cast?)

### ISSUE THREAD

**Issue by Dashdemir** [icsharpcode/ILSpy#644]
A fragment of the IL code:
    ldloc.0
    ldloc.1
    ldarg.1
    ldloc.2
    ldc.i4.1
    add
    ldelem.u1
    ldc.i4.s 64
    add
    conv.u1
    stelem.i1
decompilers as:
    array[num] = buffer[i + 1] + 64;
but should be:
    array[num] = (byte) (buffer[i + 1] + 64);
otherwise the compiler SharpDevelop4.4 returns an error:
Error CS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)

**Comment by dgrunwald** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
