### ISSUE TITLE
Int64 divides decompiled incorrectly

### ISSUE THREAD

**Issue by kg** [icsharpcode/ILSpy#645]
ILSpy decompiles an int64 div, i.e.

```csharp
long x = ...;
long y = x / 65536;
```

into a float64 div, where the lhs and rhs are casted to float64, divided as float64, then cast back to int64. I can't even figure out why it does this.

**Comment by LordJZ** [comment]
For me, this code:

    public long Issue645(long v)
    {
        return v / 65536;
    }

Decompiles into this:

    public long Issue645(long v)
    {
        return v / 65536L;
    }

Which looks correct.

**Comment by kg** [comment]
The output C# doesn't necessarily look wrong, but the ILAst is wrong.

**Comment by LordJZ** [comment]
Still, that's what I get:

    ret(div:int64(ldloc:int64(v), ldc.i8:int64(65536)))

No float64 in intermediate steps as well.

**Comment by kg** [comment]
Looks like it works here on Windows; I'll get you a binary from mcs next time I'm at work.

**Comment by kg** [comment]
Didn't stash the dll anywhere on this machine and I can't reproduce it anymore since I put in a workaround. :/

For reference, the problem seemed to be in type inference. I checked the dll with mono's disassembler and it was using the proper types, but the ILAst had float expected types. Not sure how it happened; can't see any code in ILSpy that would do this either.
