### ISSUE TITLE
VB-compilers 'For Each In' is not recognized as foreach during decompilation

### ISSUE THREAD

**Issue by donid** [icsharpcode/ILSpy#646]
When you compile this VB code:

```
    Dim list As List(Of String) = New List(Of String)()
    For Each current As String In list
        Debug.WriteLine(current)
    Next
```

and then decompile the resulting assembly with ILSpy to VB or C# it will be displayed as "while"-loop that uses an iterator.

**Comment by weltkante** [comment]
If you are using VS 2015 then this is expected, ILSpy is currently not capable of fully decompiling Roslyn based code.

**Comment by donid** [comment]
I have just checked this with a VS2012 compiled assembly: ILSpy shows the same "while"-loop...

BTW: When I compile a c# foreach with VS2015/Roslyn it is correctly decompiled as foreach.

**Comment by weltkante** [comment]
> I have just checked this with a VS2012 compiled assembly: ILSpy shows the same "while"-loop...

No idea then, sorry.

> BTW: When I compile a c# foreach with VS2015/Roslyn it is correctly decompiled as foreach.

That may depend on the surrounding code and build mode, I had seen cases where it didn't work.
