### ISSUE TITLE
hard-coded path dependency

### ISSUE THREAD

**Issue by srajaratnam** [icsharpcode/ILSpy#647]
Version 2.3.1.1855
Zip binaries when extracted and launched, The below listed dll's are coming up with error

ICSharpCode.TreeView 
Mono.Cecil
ICSharpCpde.AvalonEdit
ICSharpCode.Decompiler

Could not find a part of the path 'C:\Utils\ILSpy\ICSharpCode.TreeView.dll'.

rename the extracted folder to ILSpy and they are good to go.

![ilspy](https://cloud.githubusercontent.com/assets/14903341/10187872/7fdc50d4-676c-11e5-87eb-6daecb3dbe99.JPG)

**Comment by dgrunwald** [comment]
There are no hard-coded paths in ILSpy (certainly not "C:\Utils").

My guess is that you opened an assembly list created by a previous version of ILSpy that was installed in that path.

**Comment by srajaratnam** [comment]
The hardcoded path is the name of the folder ILSpy, the working directory
of the executable. Please see the screen shot attached

**Comment by siegfriedpammer** [comment]
I guess you are confused by the error message. It basically says that the DLL you had opened previously was located at 'C:\Utils\ILSpy'. It seems you had opened ILSpy in itself and the version at 'C:\Utils\ILSpy' got deleted/moved, thus the error message.

You can remove the missing DLLs from the assembly list and load them again from the new location. There are no hard-coded paths in ILSpy. You are welcome to do a full text search through the source code, if you disagree ;-)
