### ISSUE TITLE
Incorrect disassembling for ble.un.s?

### ISSUE THREAD

**Issue by eikesauer** [icsharpcode/ILSpy#649]
I'm not an expert and I totally might be wrong... but I met the following.

For this original code:

[code]
    if((aPath != nullptr)&&(aPath->Length>0))
    {
        const Char firstChar = aPath[0];
        return !(firstChar >= 'a' && firstChar <= 'z' || firstChar >= 'A' && firstChar <= 'Z');
    }
    return false;
[/code]

... I get this from ILSpy:

[code]
    if (aPath != null && aPath.Length > 0)
    {
        char c = aPath[0];
        int num;
        if ((c >= 97 && c == 122) || c + 65471 <= 25)
        {
            num = 0;
        }
        else
        {
            num = 1;
        }
        return (byte)num != 0;
    }
    return false;
[/code]

ildasm says:

[code]
  IL_0007:  brfalse.s  IL_0039
  IL_0009:  ldarg.0
  IL_000a:  call       instance int32 [mscorlib]System.String::get_Length()
  IL_000f:  ldc.i4.0
  IL_0010:  ble.s      IL_0039
  IL_0012:  ldarg.0
  IL_0013:  ldc.i4.0
  IL_0014:  call       instance char [mscorlib]System.String::get_Chars(int32)
  IL_0019:  stloc.0
  IL_001a:  ldloc.0
  IL_001b:  ldc.i4.s   97
  IL_001d:  blt.un.s   IL_0024
  IL_001f:  ldloc.0
  IL_0020:  ldc.i4.s   122
  IL_0022:  ble.un.s   IL_0030
  IL_0024:  ldloc.0
  IL_0025:  ldc.i4     0xffbf
  IL_002a:  add
  IL_002b:  conv.u2
  IL_002c:  ldc.i4.s   25
  IL_002e:  bgt.un.s   IL_0034
  IL_0030:  ldc.i4.0
  IL_0031:  stloc.1
  IL_0032:  br.s       IL_0036
  IL_0034:  ldc.i4.1
  IL_0035:  stloc.1
  IL_0036:  ldloc.1
  IL_0037:  conv.u1
  IL_0038:  ret
  IL_0039:  ldc.i4.0
  IL_003a:  ret
[/code]

So, isn't the "==122" from ILSpy wrong?
I'm using ILSpy version 2.3.1.1855, Visual Studio 2005 and C++/CLI.

**Comment by weltkante** [comment]
Just to clarify for other readers what you mean: "BLE" being "branch less equal" should be "<=" and not "=="

**Comment by dgrunwald** [comment]
This seems fixed in ILSpy 3, I'm getting `if ((uint)c >= 97u && (uint)c <= 122u)`.
