### ISSUE TITLE
BIG Set of enhancements

### ISSUE THREAD

**Issue by hhblaze** [icsharpcode/ILSpy#664]
Thank you for the beautiful product. Here are some enhancements.

```C#
//MADE
Dictionary<string, object> dictionary;
if (!ResourceUtility.cache.TryGetValue(typeof(TResourceClass), ref dictionary))
//MUST
Dictionary<string, object> dictionary;
if (!ResourceUtility.cache.TryGetValue(typeof(TResourceClass), out dictionary))

//MADE 
//cache is Dictionary
ResourceUtility.cache.set_Item(typeof(TResourceClass), dictionary);
//MUST
ResourceUtility.cache[typeof(TResourceClass)] =  dictionary;

//MADE 
CultureInfo cultureInfo;
cultureInfo.get_Name();
//MUST
cultureInfo.Name;

//MADE
string.Compare(cultureName, cultureInfo.Name, 5)
//MUST
string.Compare(cultureName, cultureInfo.Name, StringComparison.OrdinalIgnoreCase)

//MADE
public event EventHandler<CollectionItemPropertyChangedEventArgs> CollectionItemPropertyChanged
		{
			[MethodImpl(32)]
			add
			{
				this.CollectionItemPropertyChanged = (EventHandler<CollectionItemPropertyChangedEventArgs>)Delegate.Combine(this.CollectionItemPropertyChanged, value);
			}
			[MethodImpl(32)]
			remove
			{
				this.CollectionItemPropertyChanged = (EventHandler<CollectionItemPropertyChangedEventArgs>)Delegate.Remove(this.CollectionItemPropertyChanged, value);
			}
		}
//MUST (may be also with empty subscription inside of the class, who declares this event)
public event EventHandler<CollectionItemPropertyChangedEventArgs> CollectionItemPropertyChanged;


//MADE
base.add_CollectionChanged(new NotifyCollectionChangedEventHandler(this.WaySourceCollection_CollectionChanged));
//MUST
base.CollectionChanged += this.WaySourceCollection_CollectionChanged;


//MADE
property.set_CookieContainer(value);
//MUST
property.CookieContainer = value;

//MADE
this.contentLayer.remove_MouseMove(new MouseEventHandler(this.ContentLayer_MouseMoveForLabels));
//MUST
this.contentLayer.MouseMove -= this.ContentLayer_MouseMoveForLabels;

//MADE
string a="dsfsd";
a.get_Chars(i);
//MUST
a[i];

//MADE (again enums)
typeof(MyObj).GetField(text, 25);
//MUST
typeof(MyObj).GetField(text, BindingFlags.IgnoreCase | BindingFlags.Static | BindingFlags.Public);

```

**Comment by hhblaze** [comment]
ILSpy version 2.3.1.1855

**Comment by exyi** [comment]
Maybe you have not loaded the assembly where are these properties defined.

**Comment by hhblaze** [comment]
All are standard librairies, I can see them listed in ILSpy tree from the left.

**Comment by weltkante** [comment]
The decompiled results you are getting are not normal, but they are typical for cases where ILSpy cannot find a referenced assembly and tries a "best effort" decompilation with incomplete information. It is really odd though that core libraries and types like String and Type cannot be found.

Simple being listed on the left side isn't enough if its the wrong version of the assembly. Is this a standard .NET framework library you are decompiling, or some of the newer runtimes like WinRT or UWP? In the latter case ILSpy may not know where to find the runtime libraries and you may have to help it by manually loading them. (I'm not sure, never decompiled WinRT/UWP assemblies, its just a guess.)

**Comment by hhblaze** [comment]
Here are assemblies...Silverlight assemblies. Rename from .png to .dll


![microsoft maps mapcontrol common](https://cloud.githubusercontent.com/assets/486781/11876382/c20859a2-a4e9-11e5-87fd-735d92cde374.png)
![microsoft maps mapcontrol](https://cloud.githubusercontent.com/assets/486781/11876383/c20a80e2-a4e9-11e5-8ab7-81fb7973e1b1.png)

**Comment by hhblaze** [comment]
Original names:
Microsoft.Maps.MapControl.Common.dll
Microsoft.Maps.MapControl.dll

**Comment by weltkante** [comment]
It references the silveright runtime (mscorlib version 2.0.5.0) and you probably have the standard framework runtime loaded on the left side. If ILSpy can't find the right version automatically (it cannot for me, but I don't know if I have that version of silverlight installed) then you need to help it out by manually loading mscorlib 2.0.5.0

**Comment by hhblaze** [comment]
Very well!
