### ISSUE TITLE
[Feature Request] Generate PDB from Assembly

### ISSUE THREAD

**Issue by 0x53A** [icsharpcode/ILSpy#669]
I would love the ability to generate a PDB from an existing Assembly.
It should be possible to generate a PDB for any Language, e.g. C#, VB and also just raw IL.

This would be useful not only if you want to debug third-party code, but also if you want to debug your own code at the IL-Level.

The easiest way would probably be to skip the old format and start with the new portable pdb format (spec: https://github.com/dotnet/roslyn/blob/master/docs/specs/PortablePdb-Metadata.md) which ships with Roslyn.

**Comment by MarekPokornyOva** [comment]
Maybe you would like to try http://pdbrestorer.codeplex.com/ until ILSpy guys develop the requested feature. It's built on top of ILSpy's older version but can be modified to use the latest one.

**Comment by siegfriedpammer** [comment]
Closing this, because basic PDB gen support is present in ILSpy 4.
