### ISSUE TITLE
[Feature Request] Detect F# using patterns when decompiling to C#

### ISSUE THREAD

**Issue by 0x53A** [icsharpcode/ILSpy#670]
I have a few F# projects. Since there is no F# decompiler in ILSpy, I often just decompile it to C#.
This works, but is often not pretty.

I have an example of how it decompiles a using block here: https://gist.github.com/0x53A/5c8dedc0be448a299386

Not sure why the compiler generates these superfluous instructions in the finally block, I was compiling in release mode.

**Comment by 0x53A** [comment]
Adding the F# pattern was actually relatively straightforward: 
https://github.com/0x53A/ILSpy/tree/fsharp-using-pattern
https://gist.github.com/0x53A/5c8dedc0be448a299386#file-c-with-my-changes

**Comment by 0x53A** [comment]
This specific issue was fixed with https://github.com/icsharpcode/ILSpy/pull/671, but there are a few other instances of F# code being decompiled .. unsatisfactory .., so if you don't mind, I'll keep this open for now (or should I create separate issues?).

**Comment by dgrunwald** [comment]
F# using is broken once again, @siegfriedpammer: please re-enable the F# test case.

If there are any other problems, please create new issues.
