### ISSUE TITLE
https://ci.appveyor.com/project/icsharpcode/ILSpy/build/artifacts

### ISSUE THREAD

**Issue by Karaulov** [icsharpcode/ILSpy#673]
https://ci.appveyor.com/project/icsharpcode/ILSpy/build/artifacts

how to download latest build?

**Comment by greenozon** [comment]
I'm always getting latest bits from here
http://build.sharpdevelop.net/BuildArtefacts#ILSpyMaster
for the moment it is ILSpy_Master_2.3.1.1875_Binaries.zip

**Comment by siegfriedpammer** [comment]
information has been added to README.md
