### ISSUE TITLE
Missing required cast for overloaded method arg type.

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#682]
Imagine: 
class foo { void m(int); void m(byte); };
foo f; // init however
f.m((byte)42);

Before type inference (typing from memory, so pardon inconsistencies):
  ldc_4(u8(42));
invoke the 'byte' version of 'm'

ILSpy incorrectly drops the 'byte' cast, producing a call to the int method, due to a problem in... I think the type inference code. It sets both ExpectedType and InferredType to System.Byte, even that the expression clearly generates 'int' due to type promotion.

I tried the q'n'd "obvious" quick fix in the ldc_4 case, but while it works for the function/method arg case, I fear it would mess up f.ex. chained arithmetic operations.

Could perhaps the infer method(s) require more info? In this case, the method signature clearly dominates the expression type and should force a cast. The same applies to all (smaller-than-int) overloads from int (short, ushort, ...).

**Comment by sphereinabox** [comment]
I hit a simpler test case for this:
        static void demo(BinaryWriter bw)
        {
            bw.Write((short)5);
        }

decompiles to code without the (short) cast or number-suffix, which would then compile to calling the int overload. If you hover over the bw.Write() call the tooltip shows the correct overload .Write(short value)

**Comment by dgrunwald** [comment]
This was fixed a short while ago: ILSpy master branch will introduce casts as necessary for picking the correct overload.
