### ISSUE TITLE
Pointer make crash always !!

### ISSUE THREAD

**Issue by chrisgotboost** [icsharpcode/ILSpy#683]
à ICSharpCode.Decompiler.ILAst.ILAstOptimizer.HandlePointerArithmetic(ILNode method)
   à ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep)
   à ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters)
   à ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   --- Fin de la trace de la pile d'exception interne ---
   à ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDefinition methodDef, DecompilerContext context, IEnumerable`1 parameters)
   à ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethod(MethodDefinition methodDef)
   à ICSharpCode.Decompiler.Ast.AstBuilder.AddTypeMembers(TypeDeclaration astType, TypeDefinition typeDef)
   à ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
   à ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef)
   à ICSharpCode.ILSpy.CSharpLanguage.DecompileType(TypeDefinition type, ITextOutput output, DecompilationOptions options)
   à ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)
   à ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass16.<DecompileAsync>b__15()

**Comment by chrisgotboost** [comment]
Can someone patch this ? i can contribute in money :)

**Comment by lextm** [comment]
You could simply debug into the `HandlePointerArithmetic` method to see what's wrong,

https://github.com/icsharpcode/ILSpy/blob/b33b5ca9bfce4e211b765a07f36d8ea218eddfdb/ICSharpCode.Decompiler/ILAst/ILAstOptimizer.cs#L671

Without your asemblies, it would be difficult for others to reproduce the crash.

**Comment by chrisgotboost** [comment]
i can give the assembly !! i have try to debug but it crash the ilspy :) tank you very much !!!

**Comment by siegfriedpammer** [comment]
Can you please post the assemblies causing the crash somewhere?

**Comment by dgrunwald** [comment]
It's hard to tell without a reproducer; but given that all the code in `ILAstOptimizer.HandlePointerArithmetic` no longer exists in the new decompiler engine, this is likely fixed.
