### ISSUE TITLE
"dup, br*, pop" construct with boolean value confuses ILSpy

### ISSUE THREAD

**Issue by poizan42** [icsharpcode/ILSpy#684]
While working on a compiler for a custom language I encountered some interesting behaviour in ILSpy. I have implemented short circuiting of `expr1 || expr2` by emitting:   

```
(code for expr1)
dup // we want to keep the result if we are branching
brtrue after_test
pop // pop the copy of the first result off the stack
(code for expr2)
after_test:
(code using the test)
```

Logical and is implemented analogous with a brfalse instead. This code seems to confuse ILSpy tremendously, possibly because it's the original boolean value that is returned. The fact that two booleans of the same value are indistinguishable seems to be lost (or more likely never thought into the design).

E.g. I have an expression that basically says `(num >= 1000) || (num < 2)`. This is decompiled into `(num >= 1000) ?? (num < 2)`. This is not even valid C# code since the lhs is a boolean expression...

Another place I have a loop that in C# could be written as

``` CSharp
while ((i <= c) && (A[i] != 0))
    i := i + 1;
```

When I use the short-circuiting construct described above, ILSpy decompiles the generated IL into this abomination:

``` CSharp
while (true)
{
    bool arg_A9_0;
    if (arg_A9_0 = (num2 <= num))
    {
        arg_A9_0 = (array2[num2] != 0);
    }
    if (!arg_A9_0)
    {
        break;
    }
    num2++;
}
```

The whole example including the code in the custom language, the generated il and the decompiled code can be seen here: https://gist.github.com/poizan42/e553cb76d12aad28c0fb

**Comment by dgrunwald** [comment]
The new decompiler (ILSpy 3) should emit correct code in these cases... (no more strange `??`).
However, it certainly doesn't produce readable code... it tends to introduce an integer variable for the stack slot, leading to code like this:

```
	int num = int.Parse(Console.ReadLine());
	int num2 = (num >= 1000) ? 1 : 0;
	if (num2 == 0)
	{
		num2 = ((num < 2) ? 1 : 0);
	}
```

I'm not sure if we want to add a pattern to detect this type of code as `&&` or `||` operator; but at least we should figure out that the newly introduced variable should have type `bool`.
