### ISSUE TITLE
Can't install your extension in new VS"15"Preview

### ISSUE THREAD

**Issue by jakubsuchybio** [icsharpcode/ILSpy#688]
Hi,
### Installed product versions
- Visual Studio: [15 Preview]

### Description
At build 2016 Microsoft released Visual Studio 15 Preview.
There are some extensions that work there, but some that are not even searchable in "Extensions and Updates". Yours is one of those that are not searchable and not installable.

### Steps to recreate
1. Install Visual Studio 15 Preview: https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx (Visual Studio "15" Preview with new installer)
2. Open VS15Preview
3. Open Extensions and Updates
4. Click on Online in the menu
5. Search for ILSpy
6. Your extension doesn't pop up

### Current behavior
Your extension is not searchable in new Visual Studio 15 Preview

### Expected behavior
Your extension should or could be also in VS15Preview :)

### Steps to fix
As I am writing this, one of other extension makers already fixed this issue for his extension here:
https://github.com/cpmcgrath/codealignment/issues/43

You only need to add these:
```xml
<VisualStudio Version="15.0">
    <Edition>Pro</Edition>
    <Edition>Community</Edition>
</VisualStudio>
```
into your ```.vsixmanifest``` file into section ```<SupportedProducts>``` and it should work. :)

Regards.

**Comment by christophwille** [comment]
The new version is uploaded to the gallery, please give it a try (and thanks for digging up the necessary changes)

**Comment by jakubsuchybio** [comment]
ILSpy installed in VS15, works like a charm. Thank you!
