### ISSUE TITLE
C# function crashes

### ISSUE THREAD

**Issue by damh0503** [icsharpcode/ILSpy#690]
When I decompile dll file bools and functions are crashes like ࣁ...

**Comment by linquize** [comment]
ILSpy version?
Could you give example code?

**Comment by damh0503** [comment]
Latest version of ILSpy,
And example code, if you talking about crashing code,
`using System;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class BulletPool : MonoBehaviour
{
	public GameObject genericBullet;

	public List<GameObject> bullets;

	public int poolenAmount;

	public BulletPool()
	{
		this.poolenAmount = 150;
	}

	public override void ࢬ()
	{
		this.bullets = new List<GameObject>();
		for (int i = 0; i < this.poolenAmount; i++)
		{
			GameObject gameObject = Object.Instantiate<GameObject>(this.genericBullet);
			gameObject.SetActive(false);
			gameObject.get_transform().set_parent(this.get_transform());
			this.bullets.Add(gameObject);
		}
	}

	public override void Main()
	{
	}

	public override void Start()
	{
		this.ࢬ();
	}
}
`
Here.

**Comment by siegfriedpammer** [comment]
Can you be a bit more specific on the crash? Stacktrace or any more information available? Would be nice, if you could provide us the assembly ILSpy crashes on. Thank you very much!

**Comment by damh0503** [comment]
Looks like private one is crashing, public one looks correctly.

**Comment by siegfriedpammer** [comment]
Yes, but what is the crash? Do you have any stacktrace?

**Comment by siegfriedpammer** [comment]
Closed due to inactivity.
