### ISSUE TITLE
Decompiling events as C#

### ISSUE THREAD

**Issue by andreif** [icsharpcode/ILSpy#698]
ILSpy produces event definition as e.g.

``` cs
public event BooleanPreference.ValueChangedHandler ValueChanged
{
    add
    {
        BooleanPreference.ValueChangedHandler valueChangedHandler = this.ValueChanged;
        BooleanPreference.ValueChangedHandler valueChangedHandler2;
        do
        {
            valueChangedHandler2 = valueChangedHandler;
            valueChangedHandler = Interlocked.CompareExchange<BooleanPreference.ValueChangedHandler>(ref this.ValueChanged, (BooleanPreference.ValueChangedHandler)Delegate.Combine(valueChangedHandler2, value), valueChangedHandler);
        }
        while (valueChangedHandler != valueChangedHandler2);
    }
    remove
    {
        BooleanPreference.ValueChangedHandler valueChangedHandler = this.ValueChanged;
        BooleanPreference.ValueChangedHandler valueChangedHandler2;
        do
        {
            valueChangedHandler2 = valueChangedHandler;
            valueChangedHandler = Interlocked.CompareExchange<BooleanPreference.ValueChangedHandler>(ref this.ValueChanged, (BooleanPreference.ValueChangedHandler)Delegate.Remove(valueChangedHandler2, value), valueChangedHandler);
        }
        while (valueChangedHandler != valueChangedHandler2);
    }
}
```

and for the code to compile again, I have to remove everything except the first line. 

Is there something I can do to generate the simple event definition line or I have to modify the ILSpy source (or post-process exported source) to skip the `add`/`remove` code?

**Comment by siegfriedpammer** [comment]
Removing the everything except the first line will make it compile, but it will change the semantics, which is not what we want. Can you post the C# code that results in this output when decompiled by ILSpy? If not, can you post the IL code or assembly you decompiled?

**Comment by andreif** [comment]
Hm, not sure if you could decompile it without other libs, but an example of such events is at https://github.com/RimWorldMods/EdB-ColonistBar/blob/master/Assemblies/EdBColonistBar.dll

**Comment by andreif** [comment]
@siegfriedpammer I'll push ILSpy output from the lib in a few minutes. There is some code I've got via Xamarin Assembly Browser which I heard uses your decompiler, but I think we need output of ILSpy here.

**Comment by andreif** [comment]
@siegfriedpammer so here it is decompiled and one of the events at https://github.com/RimWorldMods/EdB-ColonistBar-Sources/blob/ilspy/EdB.Interface/BooleanPreference.cs#L24 (beware non-master branch)

**Comment by siegfriedpammer** [comment]
decompiling the mentioned event definition with ILSpy built from the recent master-branch results in

	// EdB.Interface.BooleanPreference
	public event BooleanPreference.ValueChangedHandler ValueChanged
	{
		[MethodImpl(MethodImplOptions.Synchronized)]
		add
		{
			this.ValueChanged = (BooleanPreference.ValueChangedHandler)Delegate.Combine(this.ValueChanged, value);
		}
		[MethodImpl(MethodImplOptions.Synchronized)]
		remove
		{
			this.ValueChanged = (BooleanPreference.ValueChangedHandler)Delegate.Remove(this.ValueChanged, value);
		}
	}

Note that the usages of `this.ValueChanged` actually refer to `.field private class EdB.Interface.BooleanPreference/ValueChangedHandler ValueChanged` as defined in IL. IL allows the field to have the same name as the event, because the field is loaded with a different instruction.

Actually this code should be decompiled as:

	// EdB.Interface.BooleanPreference
	public event BooleanPreference.ValueChangedHandler ValueChanged;

Normally auto events have a `System.Runtime.CompilerServices.CompilerGeneratedAttribute` attached and use a different pattern:

	public event EventHandler MyEvent
	{
		[CompilerGenerated]
		add
		{
			EventHandler eventHandler;
			EventHandler eventHandler2;
			EventHandler value2;
			eventHandler = this.MyEvent;
			while (true)
			{
				eventHandler2 = eventHandler;
				value2 = (EventHandler)Delegate.Combine(eventHandler2, value);
				eventHandler = Interlocked.CompareExchange<EventHandler>(ref this.MyEvent, value2, eventHandler2);
				if (eventHandler == eventHandler2)
				{
					break;
				}
			}
		}
		[CompilerGenerated]
		remove
		{
			EventHandler eventHandler;
			EventHandler eventHandler2;
			EventHandler value2;
			eventHandler = this.MyEvent;
			while (true)
			{
				eventHandler2 = eventHandler;
				value2 = (EventHandler)Delegate.Remove(eventHandler2, value);
				eventHandler = Interlocked.CompareExchange<EventHandler>(ref this.MyEvent, value2, eventHandler2);
				if (eventHandler == eventHandler2)
				{
					break;
				}
			}
		}
	}

The ValueChanged event does use neither the `CompilerGenerated` nor the above pattern. Which compiler was used to compile the DLL? We might have to add another pattern to the decompiler in order to solve this issue.

**Comment by andreif** [comment]
@siegfriedpammer I am trying to reach the author to find out about the compiler. The only reply I got so far is that they use `MonoDevelop/Xamarin`, so it may be `xbuild` related.

**Comment by sv1eia** [comment]
The bug still persists, "The event can only appear on the left hand side of += or -="
Used ILSpy v3.01-preview1 and its still there. Any chance to iron this out?
I'm using VS2013.

**Comment by siegfriedpammer** [comment]
Can you provide a sample?

**Comment by sv1eia** [comment]
Just tried this one and given the error
svn.tapr.org/repos_sdr_hpsdr/trunk/W5WC/PowerSDR_HPSDR_2/bin/Release/FlexCW.dll

**Comment by siegfriedpammer** [comment]
@andreif Can you confirm this is fixed?

**Comment by sv1eia** [comment]
Took the latest artifact binaries and yep, it is solved.
Thanks!
