### ISSUE TITLE
OverflowException when decompile the attached file

### ISSUE THREAD

**Issue by kenforgh** [icsharpcode/ILSpy#702]
System.OverflowException: 
 System.UInt64.System.IConvertible.ToInt64(IFormatProvider provider)
 ICSharpCode.Decompiler.Ast.AstBuilder.ConvertArgumentValue(CustomAttributeArgument argument)
 ICSharpCode.Decompiler.Ast.AstBuilder.ConvertArgumentValue(CustomAttributeArgument argument)
 ICSharpCode.Decompiler.Ast.AstBuilder.ConvertCustomAttributes(AstNode attributedNode, ICustomAttributeProvider customAttributeProvider, String attributeTarget)
 ICSharpCode.Decompiler.Ast.AstBuilder.ConvertAttributes(EntityDeclaration attributedNode, TypeDefinition typeDefinition)
 ICSharpCode.Decompiler.Ast.AstBuilder.CreateType(TypeDefinition typeDef)
 ICSharpCode.Decompiler.Ast.AstBuilder.AddType(TypeDefinition typeDef)
 ICSharpCode.ILSpy.CSharpLanguage.<>c__DisplayClass26_0.b__2(IGrouping2 file) 在 System.Threading.Tasks.Parallel.<>c__DisplayClassf1.b__c()
 System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
 System.Threading.Tasks.Task.<>c__DisplayClass11.b__10(Object param0)

**Comment by siegfriedpammer** [comment]
duplicate of #699

**Comment by kenforgh** [comment]
[test.zip](https://github.com/icsharpcode/ILSpy/files/238159/test.zip)

**Comment by kenforgh** [comment]
[test.zip](https://github.com/icsharpcode/ILSpy/files/238172/test.zip)

**Comment by siegfriedpammer** [comment]
fixed by a6ae2e4b24241ad8a4430f3aa55f99ca934f69b3
