### ISSUE TITLE
Splitter grid hitbox interferes with mouse clicks

### ISSUE THREAD

**Issue by DerpMcDerp** [icsharpcode/ILSpy#705]
The splitter grid has a weird hitbox that sometimes trigger grid resizing instead of selecting text or scrollbar scrolling when using the mouse (the red pixels in the picture are inclusive of the hitbox):

![grid_hitbox](https://cloud.githubusercontent.com/assets/8602394/14898304/ec013eae-0d3a-11e6-8f5a-9c2032568ab5.png)

**Comment by dgrunwald** [comment]
It would be incredibly hard to hit the splitter if it the hitbox was as small as it is visually.

**Comment by DerpMcDerp** [comment]
If you're reluctant to adjust the hitbox sizes, how about at least shifting the hitbox between the search results and the editor 3 pixels up?
