### ISSUE TITLE
Retargetting to framework v4.5 +

### ISSUE THREAD

**Issue by EdHarvey** [icsharpcode/ILSpy#709]
Starting January 2016 Microsoft will no longer provide security updates, technical support or hotfixes for .NET 4, 4.5, and 4.5.1 frameworks, so it is likely that most installations will be swiftly installing version 4.5.2 (or later) if they have not already done so. Post version 4 frameworks are an 'in-place' update replacing the existing version rather than existing side-by-side. 

I believe this is an opportune time for us to retarget ILSpy from 4 to a more recent version. 

This would allow us to use the rather substantial enhancements to MEF that were introduced in 4.5.

**Comment by EdHarvey** [comment]
I am currently working on a major restructuring/upgrade of the Analyzer to
* Reduce dependencies between the Analyzer and ILSpy/Decompiler
* Make it easier to enhance/maintain the Analyzer in the future.
* Allow third-party use of Analyser functionality (for example, add-ins)
* Allow add-in extensions to the Analyzer.

*The final two items will probably require functionality from "MEF2", introduced in .Net 4.5*

**Comment by christophwille** [comment]
I for one have no problem going 4.5+ @siegfriedpammer @dgrunwald  any objections from you?

**Comment by AraHaan** [comment]
tbh I perfer 4.6 just to be safe.

**Comment by dgrunwald** [comment]
Every increase of the required .NET version will cause problems for some of our users who don't have the latest .NET version installed. Going to 4.5 also means giving up support for Windows XP. (which shouldn't be a problem in 2016...)

I don't have any objections going to .NET 4.5 since that does offer us major advantages (async/await, MEF2, other portable libraries), but I wouldn't increase the .NET requirement further without a compelling reason.

**Comment by EdHarvey** [comment]
> I don't have any objections going to .NET 4.5 since that does offer us major advantages (async/await, MEF2, other portable libraries), but I wouldn't increase the .NET requirement further without a compelling reason.

I agree, but 4.5.2 seems to be the best candidate to me, as it's the earliest version still supported by Microsoft...

I would, however, be *very* amenable to allowing C# 6 features into the codebase. 
It's been nearly a year since it was released, and I **really** want to be able to use the 'null conditional' operator (it's become second nature now, and I hate having to shift mental gears to go back and rewrite code to be C#5 compliant :unamused:)

**Comment by siegfriedpammer** [comment]
I am already using C# 6 features in the code base. The language version is not connected to the framework version used. Of course, in order to compile ILSpy you have to install the framework version with the C# 6 compiler included.

**Comment by AraHaan** [comment]
Do you not forget that users can install 4.5+ on windows XP too I did so with a few hacks to make it think that it is a Windows 7.

**Comment by christophwille** [comment]
XP definitely should not be part of our considerations any more. It is dead security-wise.

**Comment by AraHaan** [comment]
Yep security wise yes but sadly the last OS that uses a bitmap format theme the newer ones use PNG on their resources and no ini config.

**Comment by christophwille** [comment]
Related https://github.com/icsharpcode/ILSpy/issues/831

**Comment by siegfriedpammer** [comment]
Now targeting v4.6.1.
