### ISSUE TITLE
Saving Project does not Convert *.resources to *.resx for use in Visual Studio 2015 on C# & VB Projects.

### ISSUE THREAD

**Issue by AraHaan** [icsharpcode/ILSpy#712]
It would be nice if it would allow converting of the *.resources files to *.resx so I do not have to Open SharpDevelop for that. It would be much more convient for those who do not have SharpDevelop either.

**Comment by lbx1979** [comment]
ILSpy version 3.0.1.3459 still have this issue, the generated project file did not include ".resource" files. I rename  those files to ".resx" extension and include them in the project , then works fine.
