### ISSUE TITLE
Issue when Decompiling parts of a Compiled EXE who's Namespace has a ton of controls.

### ISSUE THREAD

**Issue by AraHaan** [icsharpcode/ILSpy#713]
There is a probplem with a namespace named ``PmdForm`` in Assemply ``PMDEditor``. And I have a image of it as well.

![fd01b9d54a57354330c72347e02dc256](https://cloud.githubusercontent.com/assets/15173749/15451872/51e15afe-1f9e-11e6-8afe-6614865fe297.png)

As you guys can see things like this causes a ``System.NullReferenceException: Object reference not set to an instance of an object.`` on it. And therefore saving the project generates the file for this to be ``0 kb`` which does not help because then the ``*.csproj`` file becomes ``0 kb`` as well.

**Comment by siegfriedpammer** [comment]
Would you be able to provide the `PMDEditor` assembly? Any download links I found are blocked by the South Korean Government. (I am currently in South Korea and will stay here for the next couple of months.) Thank you!

**Comment by AraHaan** [comment]
Ah ok I can.
Here it is:
[PMDEditor_0139.zip](https://github.com/icsharpcode/ILSpy/files/287458/PMDEditor_0139.zip)

**Comment by AraHaan** [comment]
ah it seems to be that the "Decompile anonymous methods/lambda" in Options causes this if enabled.

**Comment by siegfriedpammer** [comment]
I found the problem a few days ago. I will publish a fix very soon. It's just that I am very busy with other things at the moment.

**Comment by AraHaan** [comment]
oh and what is with random ``get_[varname]()`` on these assemblies as C# does not like it and does not want to let me compile with those present.

**Comment by siegfriedpammer** [comment]
That's an entirely different issue, but I guess it's because some references or types are missing. `Pmx` for example, thus ILSpy cannot detect whether the method is a getter or not.

**Comment by siegfriedpammer** [comment]
a nightly build with the fix included can be found here: http://build.sharpdevelop.net/BuildArtefacts/#ILSpyMaster
