### ISSUE TITLE
Exception thrown when converting System.Enum To System.Int64 in CustomAttribute

### ISSUE THREAD

**Issue by JasonAtGithub** [icsharpcode/ILSpy#716]
if (type != null && type.IsEnum) {
         return MakePrimitive(Convert.ToInt64(argument.Value), type);
}
In file AstBuilder.cs[line:1524].

My Type definition:
    public enum AppID
    {
        Invalid = 18446744073709551615,
    }

The value is overflow, since Its type is System.UInt64.

**Comment by siegfriedpammer** [comment]
Hi, I just tried to reproduce this with the most recent [nightly build](http://build.sharpdevelop.net/BuildArtefacts/#ILSpyMaster) but was unable to do so. I used your code as example for testing, but it seems ILSpy produces the correct code:

```
using System;

namespace Bug716
{
	public enum AppID : ulong
	{
		Invalid = 18446744073709551615uL
	}
}
```

**Comment by JasonAtGithub** [comment]
Sorry for your time, I have tested the code above, It works well. I just change my code and add system attribute _System.ComponentModel.DefaultValue_ to it, it throw an exception mentioned above.
Code:
`   
    [System.ComponentModel.DefaultValue(AppID.Invalid)]
    public enum AppID : ulong
    {
        Invalid = 0xFFFFFFFFFFFFFFFFul,
    }
` 
@siegfriedpammer

**Comment by JasonAtGithub** [comment]
`Hello`
