### ISSUE TITLE
How to multi instance

### ISSUE THREAD

**Issue by danmosemsft** [icsharpcode/ILSpy#718]
ILSpy prefers to be single instance which is usually what I want (I associate .dll extension with it, and I can double click to open in my existing instance)

However I sometimes want multi instance: I have several groups of assemblies, that are distinct but have many types in common. It would be great if I could force a new instance of ILSpy.

**Comment by siegfriedpammer** [comment]
There's a command line switch: /separate

**Comment by danmosemsft** [comment]
awesome. for future reference:
https://github.com/icsharpcode/ILSpy/blob/master/doc/Command%20Line.txt

It's a little wacky because
ilspy /separate foo.dll
ilspy /separate bar.dll

opens one with foo.dll and another with both foo and bar. but it gets the job done, thanks!

**Comment by siegfriedpammer** [comment]
Will add a page in the wiki to document the command line and make it easily discoverable.

**Comment by danmosemsft** [comment]
You could also potentially make "ilspy.exe /?" show a dialog with the flags. thx!
