### ISSUE TITLE
FeatureRequest: Constructor calling into another overload should have a link

### ISSUE THREAD

**Issue by dlstucki** [icsharpcode/ILSpy#721]
When inspecting a .ctor which invokes another overload why isn't the text "this" a hyperlink to that overload?

```
public UniqueId(Guid guid) : this(guid.ToByteArray()) { }
```

**Comment by AraHaan** [comment]
not to mention parts with ``this..ctor`` cannot compile so I do not know what function it should call. I think the ``this..ctor`` stuff is wrong somewhere.

**Comment by dstuckims** [comment]
http://stackoverflow.com/questions/4614099/what-is-the-meaning-of-ctor
________________________________

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
