### ISSUE TITLE
Failure to load assemblies with a portable pdb

### ISSUE THREAD

**Issue by AustinWise** [icsharpcode/ILSpy#723]
If you compile hello world using the new .NET Core CLI:
````
dotnet new
dotnet restore
dotnet build
````
and try to open the resulting DLL using IlSpy, the DLL fails to load with this exception:
````
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& tokenToSourceMapping, String& sourceServerData, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadSymbols(ModuleDefinition module)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
````

The root cause is the cecil class [PdbFileHeader](https://github.com/jbevain/cecil/blob/042bdd2432705ae4c682743ff9740550dee3bead/symbols/pdb/Microsoft.Cci.Pdb/PdbFileHeader.cs) does some not check the header of the PDB file.

This could worked around in IlSpy by [catching more exceptions](https://github.com/icsharpcode/ILSpy/blob/e2e952a9be85c57eed8c70d7315281a6724b7049/ILSpy/LoadedAssembly.cs#L134) during symbol loading.

**Comment by AraHaan** [comment]
You know you can make a Pull Request right?

**Comment by tyrotoxin** [comment]
FYI: this is still the issue for .NET Standard assemblies

**Comment by valhristov** [comment]
I workarounded this by adding `<DebugType>Full</DebugType>` to my projects. It also helps with collecting code coverage, see https://github.com/Microsoft/vstest/issues/800...

**Comment by pkruk2** [comment]
Could we reopen this? Mono.Cecil supports Portable PDBs now, maybe ILSpy could update it's Mono.Cecil version?

**Comment by siegfriedpammer** [comment]
No, because we are moving away from Mono.Cecil altogether... see #1030

**Comment by pkruk2** [comment]
Thanks, makes sense. Is there an ETA for #1030 ?

**Comment by siegfriedpammer** [comment]
ILSpy 4.0 will enter alpha quality in late summer.

**Comment by AraHaan** [comment]
Oh btw @siegfriedpammer is it possible that on the ILSpy VS extension that you can make an code analysis extension that checks c# code for things like:

    bool something = false;
    string somethingelse = string.Empty;
    // do something that can change the above variable.
    if (something)
    {
        somethingelse = "some value";
    }
    else
    {
        somethingelse = "some other value";
    }
To:

    bool something = false;
    string somethingelse = string.Empty;
    // do something that can change the above variable.
    somethingelse = something ? "some value" : "some other value";

Which I find more readable and a lot eaiser to maintain. Something that even I sometimes struggle to do at times. It would be nice however if ILSpy was to warn on this saying this if it decides that the IL code/ metadata ends up being the above case. I wish the actual compiler had an option for checks like this though to warn on and produce errors when warn as error is enabled. That would ensure everyone gets used to the ways of doing the same thing with far less typing and more readability.

**Comment by siegfriedpammer** [comment]
@AraHaan I think this is totally out of the scope of a decompiler. In this case it is easy to see, but would require a lot of semantic analysis, which is better done using a Roslyn analyzer. Thank you for your understanding.

Also, please stop hijacking other issues that have nothing to do with your problems or suggestions. Even more so, if they were already closed a while back. You can always open new issues. Thank you very much!
