### ISSUE TITLE
Weird decompilation of `return` inside `switch case` statement

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [icsharpcode/ILSpy#729]
Have a look at screenshot. All `return`s inside `switch case` statement are decompiled into `goto IL_2C7;`

I don't know whether this is compiler-based problem or ILSpy's bug but all `goto IL_2C7;` could be replaced by `return;`

![image](https://cloud.githubusercontent.com/assets/15037839/16709259/46b4144c-461c-11e6-86bb-04d69d82690b.png)

**Comment by dgrunwald** [comment]
The newdecompiler branch does a better job introducing a `default:` case, which should fix this problem.
