### ISSUE TITLE
[UI] Thinking of Adding a AutoUpdate feature.

### ISSUE THREAD

**Issue by AraHaan** [icsharpcode/ILSpy#730]
Roadmap in no Particular Order.
- [x] Create a exe that should extract the updates that the DLL downloads in case a update was detected.
- [ ] Add option to automatically download updates (someone else has to do this part).
- [x] Create a DLL that does the downloading of the updates.(Will need to Download updates to Application.StartupPath)(would need a constant link that will always update for release and a different one for nightly builds)(eg link never changes but content does)

Note: in event that the Release happens the places where it downloads the updates would have to not include the updater exe that extracts them.

Also Ionic.Zip does support Relative Paths as far as I tested so this should be fine.

**Comment by christophwille** [comment]
You happen to be aware of (just as an example btw) https://github.com/synhershko/NAppUpdate?

Auto-updating is not as easy as you might think.

**Comment by lextm** [comment]
There are also other approaches, such as [Squirrel for Windows](https://github.com/Squirrel/Squirrel.Windows).

**Comment by AraHaan** [comment]
ah I cant use ``System.IO.Comrpession`` for the Progress bar stuff I need ``Ionic.Zip`` Well at least I know now.

**Comment by AraHaan** [comment]
``Ionic.Zip`` fixes the issue with having to Delete the files before extracting as long as they are not in use. So, I do not have to delete them first.

**Comment by dgrunwald** [comment]
It's very hard to write an auto updater that isn't a huge security vulnerability. Your PR seems to tick the usual boxes:
[X] no authentication that the update isn't provided by a random MitM
[X] no verification that the .zip doesn't overwrite files other than intended (possibly even outside the intended target directory, if Ionic.Zip isn't forbidding relative paths)

The current 'update process' is already vulnerable enough even with a human user in the loop. It needs to be secured before there's any point in creating an auto updater.

**Comment by jsakamoto** [comment]
@AraHaan  I forked ILSpy original repository, and create "ClickOnce" edition.

And, I published the ILSpy "ClickOnce" edition at my responsibility on the website below.

https://clickonceget.azurewebsites.net/app/ILSpy/detail
