### ISSUE TITLE
Add sorting feature for search results

### ISSUE THREAD

**Issue by zvirja** [icsharpcode/ILSpy#736]
It strange a bit that I wasn't able to find an issue for that.
It would be great to have a button to sort search results. I'd like to have the following features
- sort by name
- sort by enclosing container and than by name.

I could implement that. Let's discuss how it's better to do that. I could add one more icon button after "Search for..." control:

![image](https://cloud.githubusercontent.com/assets/1074182/16985357/7b7a6f2c-4e88-11e6-8903-44302477ba4c.png)

That could be `AZ` icon that we currently use for the assembly sorting - we'll just add one more there.
Also, I'd suggest the following behavior:   
- Left click on button sorts by names
- Right click on button shows menu:
  - Sort by name (default)
  - Sort by enclosing name -- to discuss name.

Your thoughts?

**Comment by siegfriedpammer** [comment]
I think "sort by enclosing name" is the same as "sort by FQN", which is a better name imho.

**Comment by siegfriedpammer** [comment]
I am working on this...

**Comment by Zvirja** [comment]
Have you already started to work on it or just assigned the task to yourself?  

I could help with this one. However, if you already started to implement the feature - let's just wait for your implementation :)

**Comment by Zvirja** [comment]
@siegfriedpammer Do you have updates on this one? Is there something I can help you with?

**Comment by Zvirja** [comment]
It seems that you haven't started to work on it. I'll try to implement this if I have a free time :) 

#783 should be also considered.

**Comment by siegfriedpammer** [comment]
@zvirja I am closing this, because we do not feel special sorting UI is necessary. We now have search result sorting by length as implemented by #668. If you think it is insufficient, feel free to make a pull request.

**Comment by zvirja** [comment]
OK, let's see how it goes after the update. If I feel that I still need this feature - I'll fire a PR.

Thank you for the update.
