### ISSUE TITLE
E_INVALIDARG when "Open output in ILSpy" for CLI/C++ project

### ISSUE THREAD

**Issue by mediawolf** [icsharpcode/ILSpy#737]
Opening such project using VS extension produces: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
While opening output binary inside ILSpy works fine.

**Comment by AraHaan** [comment]
I get that when Trying to View Project Settings when the Solution file has no Actual Project's just solution folders with files.

**Comment by Rpinski** [comment]
Should be fixed with 84758dca5ec0ca35f9fe672e0a55d7f380591edb.
