### ISSUE TITLE
[UI] Add "Save Code" Option to Right Click menus when selected a 'base' node on a Assembly.

### ISSUE THREAD

**Issue by AraHaan** [icsharpcode/ILSpy#744]
I wonder if it is possible where if it is the 'base' Node on Any Assembly that is managed to add the 'Save Code' Option. Also Could you guys add some sort of Detection for if it was made in Managed C++ to Disable 'Save Code' For that specific Assembly as well?

Why? Because Managed C++ is by way different than C# (with `#include`'s all over them.)

**Comment by dgrunwald** [comment]
What do you mean by «'base' Node on Any Assembly» ???

**Comment by christophwille** [comment]
Closing because no feedback was provided.

**Comment by AraHaan** [comment]
ye, on any assembly, sorry for no reply I just found this issue.

**Comment by siegfriedpammer** [comment]
A "Save Code" context menu entry will be added in #1550
