### ISSUE TITLE
Parameter Overload

### ISSUE THREAD

**Issue by FlorianGrimm** [icsharpcode/ILSpy#746]
If a Method exist with Overload with type and base type wrong code is generated
`
using System;
namespace TestParameter {
    public class Program  {
        public static void Main(string[] args)   {
            var b = new B();
/**/
            System.Console.Out.WriteLine(b.M(b) + b.M((A)b) + b.M((object)b));
/**/
        }
    }
    public class A    {
        public virtual int M(Object a) { return 1; }
        public virtual int M(A a) { return 2; }
    }
    public class B : A    {        public virtual int M(B b) { return 4; }    }
}
`

will be decompiled to
`Console.Out.WriteLine(b.M(b) + b.M(b) + b.M(b));`

I'll tried to fix it within ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs convert return expr.CastTo(AstBuilder.ConvertType(reqType)); but that's too much.. and I'll don't know enough about IL and the process of decompiling..

**Comment by riQQ** [comment]
Fixed the formatting of your code:

```csharp
using System;
namespace TestParameter
{
  public class Program
  {
    public static void Main(string[] args)
    {
      var b = new B(); /**/
      System.Console.Out.WriteLine(b.M(b) + b.M((A) b) + b.M((object) b)); /**/
    }
  }
  
  public class A 
  {
    public virtual int M(Object a)
    {
      return 1;
    }

    public virtual int M(A a)
    {
      return 2;
    }
 }
 
  public class B : A 
  {
    public virtual int M(B b)
    {
      return 4;
    }
  }
}
```

**Comment by dgrunwald** [comment]
This is fixed on the newdecompiler branch -- there we always make casts explicit. In the future we'll likely use NRefactory to check whether the casts are necessary in order to select the correct overload.

**Comment by dgrunwald** [comment]
The newdecompiler branch just got merged to master.
