### ISSUE TITLE
Show getters/setters

### ISSUE THREAD

**Issue by LennyPenny** [icsharpcode/ILSpy#747]
Would be awesome if you added an option to show getter/setter methods without having to switch to the IL view

**Comment by Zvirja** [comment]
Could you please clarify in more detail what you want to see? Add some screenshots and highlight exact places where you want to see them. 

Thanks.

**Comment by dgrunwald** [comment]
We should probably have an option to show all members in C# view, the same way we do in IL view.
This would then also include the compiler-generated members.

**Comment by LennyPenny** [comment]
Yea that's exactly what I was looking for
