### ISSUE TITLE
SharpTreeView usage

### ISSUE THREAD

**Issue by ygoe** [icsharpcode/ILSpy#748]
I'd like to use SharpTreeView for a tree with columns and lazy loading in my project but can't figure out how to use it. I can place it in my window, but no nodes are ever displayed, the control remains empty. Is there any example available?

**Comment by lextm** [comment]
SharpTreeView was developed as part of SharpDevelop, so you should go to that repo to check its demo project,

https://github.com/icsharpcode/SharpDevelop/tree/master/src/Libraries/SharpTreeView/ICSharpCode.TreeView.Demo
