### ISSUE TITLE
Getting error when starting the exe?

### ISSUE THREAD

**Issue by SeppPenner** [icsharpcode/ILSpy#751]
I'm getting the following error when I start the executable:

"---------------------------
## Sorry, we crashed

System.Windows.Markup.XamlParseException: Durch den Aufruf des Konstruktors für Typ "ICSharpCode.ILSpy.MainWindow", der den angegebenen Bindungseinschränkungen entspricht, wurde eine Ausnahme ausgelöst. ---> System.ComponentModel.Composition.ChangeRejectedException: Die Komposition bleibt unverändert. Die Änderungen wurden aufgrund der folgenden Fehler zurückgewiesen: Bei der Komposition ist ein Kompositionsfehler aufgetreten. Die Ursache wird unten angegeben. Die CompositionException.Errors-Eigenschaft liefert genauere Informationen.

1) Es wurden keine Exporte gefunden, die der Einschränkung entsprechen: 
    ContractName    ICSharpCode.ILSpy.TextView.DecompilerTextView
    RequiredTypeIdentity    ICSharpCode.ILSpy.TextView.DecompilerTextView

Ergebnis: Import "ICSharpCode.ILSpy.MainWindow.decompilerTextView (ContractName="ICSharpCode.ILSpy.TextView.DecompilerTextView")" kann nicht für Teil "ICSharpCode.ILSpy.MainWindow" festgelegt werden.

Element: ICSharpCode.ILSpy.MainWindow.decompilerTextView (ContractName="ICSharpCode.ILSpy.TextView.DecompilerTextView") -->  ICSharpCode.ILSpy.MainWindow

   bei System.ComponentModel.Composition.CompositionResult.ThrowOnErrors(AtomicComposition atomicComposition)

   bei System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)

   bei System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)

   bei System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)

   bei ICSharpCode.ILSpy.MainWindow..ctor()

   --- Ende der internen Ausnahmestapelüberwachung ---

   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   bei System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   bei System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)

   bei System.Windows.Application.DoStartup()

   bei System.Windows.Application.<.ctor>b__1_0(Object unused)

   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
![ilspy-debugger_crash](https://cloud.githubusercontent.com/assets/9639361/18000251/7267a9a6-6b7d-11e6-94cb-0907b0f6cd0f.PNG)
"

**Comment by siegfriedpammer** [comment]
Seems like your ILSpy install is broken, have you tried downloading a fresh copy?
