### ISSUE TITLE
missing assignment on decompile

### ISSUE THREAD

**Issue by trivalik** [icsharpcode/ILSpy#752]
In class System.Windows.Forms.Design.TabControlDesigner in assembly System.Design.dll in method OnAdd is ILSpy not showing the assignment to SelectedIndex.

The code line which ILSpy shows is:

tabControl.TabCount--;

but it should be:

tabControl.SelectedIndex = tabControl.TabCount - 1;

**Comment by siegfriedpammer** [comment]
This was fixed in the new decompiler engine (which just landed on the master branch).
