### ISSUE TITLE
nightly build

### ISSUE THREAD

**Issue by bprg** [icsharpcode/ILSpy#760]
How can download nightly build? I can't find download link from [here ](http://build.sharpdevelop.net/BuildArtefacts/#ILSpyMaster)

**Comment by dgrunwald** [comment]
I think the build server deletes old builds, even if there is no newer build available due to a period of inactivity.
@christophwille: can we get this fixed? this happens quite frequently...

**Comment by christophwille** [comment]
This is the default behavior implemented via a dead-simple (and extremely old) batch script

c:\tools\fileremover.exe 5 ILSpy*.* c:\BuildArtefacts

Would need to write an entirely new one to account for "leave at least one set of build artefacts behind" (currently does not care how many exe/msi/zip comprise one "build")

**Comment by christophwille** [comment]
Get-ChildItem ILSpy_*.* | sort LastWriteTime -Descending | select -skip 3 | Remove-Item

That's a PS script that would the job specifically for ILSpy build artefacts.

**Comment by siegfriedpammer** [comment]
Our old build server no longer exists. Nightly builds are now provided at https://ci.appveyor.com/project/icsharpcode/ilspy. The artifacts should stay around as long as there are no more recent builds.
