### ISSUE TITLE
Eliminate dead, unreachable code

### ISSUE THREAD

**Issue by ChlorideCull** [icsharpcode/ILSpy#766]
It would be great if an additional "simple" dead code elimination step could be enabled. Certain obfuscators tend to like inserting blocks of code which will break compilation as-is, like

```
if (!true)
{
    RuntimeMethodHandle arg_43_0 = methodof(CP.V(int)).MethodHandle;
}
```

Obviously, `!true` will never be `true`, but the presence of the code is enough to throw off Microsoft's C# compiler, since `methodof` doesn't exist.

Slightly harder, but still doable, is something like

```
while (true)
{
    switch (2)
    {
    case 0:
        continue;
    }
    break;
}
```

As the switch will never hit a case (no default, only case is not the same as the constant), it can be completely removed, only leaving a `while (true) { break; }`, which could also be removed.

**Comment by akyryz** [comment]
What about a plugin for this kind of stuff?

**Comment by dgrunwald** [comment]
I don't think it's a good idea for us to start an arms race with obfuscators. But I'm open to the possibility of allowing plugins to add passes to the decompiler pipeline.

**Comment by siegfriedpammer** [comment]
If anyone is interested in contributing such a feature, we'll be glad to help providing an plugin interface. But for now we are closing this.
