### ISSUE TITLE
Protected Net Programs

### ISSUE THREAD

**Issue by highattack30** [icsharpcode/ILSpy#768]
ILSpy not reading the files currently seems he can't handle with protected programs this feature can be implanted ?

**Comment by SlowLogicBoy** [comment]
It's a limitation of https://github.com/jbevain/cecil library which aims for ECMA CIL generation, so it will not be possible, at least for now. And if .Net file is protected it means they (creators of that file) don't want you to look in their code.

**Comment by lextm** [comment]
You might use [dnEditor](https://github.com/ViRb3/dnEditor) which is based on ILSpy and dnlib. It can work for obfuscated assemblies.

As the other comment indicates, Cecil and ILSpy's goal is not to support such assemblies.
