### ISSUE TITLE
Feature request: grouping assemblies

### ISSUE THREAD

**Issue by FallenPhoenix** [icsharpcode/ILSpy#770]
Hello. I want to ask developers to make ways to group assemblies in the ILSpy list (left panel), to make able, for example, put standard .NET libraries in one group (or even separate .NET 2.x and 4.x) and custom user binaries into another one. It can be top-level folders, separators or something like that.

**Comment by siegfriedpammer** [comment]
With the changes to assembly lists in v6.0 we think this is no longer an issue. If you or anybody still thinks, we should add something like folders to the assembly list tree view, please create a new issue.
