### ISSUE TITLE
.NET Core compatibility

### ISSUE THREAD

**Issue by Piedone** [icsharpcode/ILSpy#771]
It would be great to have the ILSpy assemblies compatible with .NET Core, or to formulate otherwise, be able to access .NET Core-compatible versions of the ILSpy assemblies (with the point of using them form .NET Core programs).

If I'm not mistaken the current versions of Mono.Cecil and ICSharpCode.NRefactory required by ICSharpCode.Decompiler v2.3.1 (which is the released version on NuGet) aren't .NET Core-compatible either.

If the upstream source is already compatible, just not yet released, then please tell me.

**Comment by dgrunwald** [comment]
I just updated the newdecompiler branch to the current Mono.Cecil version; and no longer needs ICSharpCode.NRefactory (the necessary portions of NRefactory are now part of the ICSharpCode.Decompiler project).

**Comment by Piedone** [comment]
Great!

**Comment by JosephWoodward** [comment]
Any idea when these changes will be available via NuGet?

**Comment by christophwille** [comment]
Related https://github.com/icsharpcode/ILSpy/issues/831

**Comment by christophwille** [comment]
The 3.x nugets (alpha packages) are now available.
