### ISSUE TITLE
Where is the debug plug-in?

### ISSUE THREAD

**Issue by AdamAndersonFalafelSoftware** [icsharpcode/ILSpy#774]
There are mentions of it on the main wiki page that link to a blog (from 2011) that advertise its existence, but no links to download it. Is it still available or what's the story? Thanks!

**Comment by lextm** [comment]
https://github.com/icsharpcode/ILSpy/pull/608

Clearly it has been abandoned.

**Comment by AdamAndersonFalafelSoftware** [comment]
Thanks for the reference; the title of the linked issue was not very descriptive!
