### ISSUE TITLE
Errors about decompiling local variables and default for switch-cases

### ISSUE THREAD

**Issue by gyrodrill** [icsharpcode/ILSpy#778]
```
switch (k)
{
	case 0:
	{
		IL_3D:
		bool flag2 = false;
		int maxValue = num3;
		break;
	}
	case 1:
	{
		bool flag2 = true;
		int maxValue = num;
		break;
	}
	case 2:
	{
		bool flag2 = false;
		int maxValue = num3;
		break;
	}
}
goto IL_3D;
IL_77:

A few lines of code...

int maxValue;
bool flag2;
```

It seems that the first label IL_3D should be default for this switch-case, and the local variable maxValue and flag2 are decleared many times.
Is it possible to automatically move the declear statment to the place where it is before all other using of this value, and turn the goto label into switch() { default: }?

**Comment by dgrunwald** [comment]
The newdecompiler branch should have better detection of switch statements. And even if it gets it wrong and produces unnecessary gotos, those should now always be valid (never jump into blocks).

**Comment by gyrodrill** [comment]
When i compile the code in commit 681641948b0fa1315a266382044f5e13f4c72155 from newdecompiler branch (2016 Dec 4), the ILSpy brokes with the stack trace below, and did not show any decompiled code.

ICSharpCode.ILSpy.AssertionFailedException
    ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message, String detailMessage)  \ILSpy\ILSpyTraceListener.cs:Lines 74
    ICSharpCode.ILSpy.ILSpyTraceListener.Fail(String message)  \ILSpy\ILSpyTraceListener.cs:Lines 46
    System.Diagnostics.TraceInternal.Fail(String message)
    ICSharpCode.Decompiler.IL.StLoc.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.IfInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.Block.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.BlockContainer.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.IL.ILInstruction.CheckInvariant(ILPhase phase)
    ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DecompileBody(MethodDefinition methodDefinition, IMethod method, EntityDeclaration entityDecl, ITypeResolveContext decompilationContext)
    ICSharpCode.Decompiler.CSharp.CSharpDecompiler.DoDecompile(MethodDefinition methodDefinition, IMethod method, ITypeResolveContext decompilationContext)
    ICSharpCode.Decompiler.CSharp.CSharpDecompiler.Decompile(IMemberDefinition[] definitions)
    ICSharpCode.ILSpy.CSharpLanguage.DecompileMethod(MethodDefinition method, ITextOutput output, DecompilationOptions options)  \ILSpy\Languages\CSharpLanguage.cs:Lines 107
    ICSharpCode.ILSpy.TreeNodes.MethodTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)  \ILSpy\TreeNodes\MethodTreeNode.cs:Lines 133
    ICSharpCode.ILSpy.TextView.DecompilerTextView.DecompileNodes(DecompilationContext context, ITextOutput textOutput)  \ILSpy\TextView\DecompilerTextView.cs:Lines 502
    ICSharpCode.ILSpy.TextView.DecompilerTextView.<>c__DisplayClass31_0.<DecompileAsync>b__0()  \ILSpy\TextView\DecompilerTextView.cs:Lines 481

**Comment by gyrodrill** [comment]
Will it help if i post the il code here?

**Comment by siegfriedpammer** [comment]
It would help, if you could provide a minimal example of what is failing.

**Comment by gyrodrill** [comment]
I am not sure where the problem is, because the version i compiled will give wierd code even for helloworld programs: all local variables become v_(number) and they have declarations. It happens in Sample of items.zip/Program.exe.

Another problem happen that when it could NOT decompile Ionic.Zip.CF.dll, totally not. It is in Sample of items.zip too, and ILSpy breaks in most classes. Screenshots are provided in file.


Finally, the code i give in this issue is in Terraria, type name WorldGen and method name generateWorld.
It only happens when the checkbox View - Options - Decompile anonymous methods/lambdas is true. When it is false, it would not breaks, but the code is full of $<> (Compiler generated things).
[Samples_and_screenshots.zip](https://github.com/icsharpcode/ILSpy/files/670370/Samples_and_screenshots.zip)

**Comment by siegfriedpammer** [comment]
Thank you very much for posting the samples, we'll take a look soon! :)

**Comment by siegfriedpammer** [comment]
I am no longer able to reproduce any of the problems with switch, but I will take a look at the problem with delegate construction in `generateWorld`.
