### ISSUE TITLE
Property getter/setter decompiled incorrectly for .Net 1.1 code

### ISSUE THREAD

**Issue by paulhickman** [icsharpcode/ILSpy#780]
If you have .Net code of the following pattern in a .Net 1.1 assembly:

    object1.Property1 = object2.Property2;

ILSpy version 2.4.0.1963 will decompile this to:

    object1.set_Property1(object2.get_Property2());

So, for example the code:

    DateTime t = DateTime.Now;

Becomes:

    DateTime t = DateTime.get_Now();

**Comment by dgrunwald** [comment]
ILSpy cannot tell whether the method `get_Property1` belongs to a property unless the assembly defining that property is loaded.

**Comment by dgrunwald** [comment]
The decompiler should probably complain about missing assembly references more visibly (e.g. as comment in decompiled code?). Missing information affects not only properties, but also enum literals and some other constructs.

For properties, we could possibly also use the typical naming schema (get_* and set_*) to make a guess when there's no accurate information available.

**Comment by siegfriedpammer** [comment]
see #849
