### ISSUE TITLE
Feature request: show exact matches first; provide ways to sort results; lift result limit

### ISSUE THREAD

**Issue by qwertie** [icsharpcode/ILSpy#783]
For example, when I search for `Thread`, I'm not (necessarily) looking for `CrossThreadDependencyNotification` or `SafeThreadHandle` and I'm certainly not looking for all those classes in `System.Threading` that don't have `Thread` in their name. I just want `Thread`.

It would also help if I could sort the results by name. Right now I'm trying to use ILSpy to investigate PCLs.: I'd like to know which versions of mscorlib.dll contain a `Thread` class in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.0\Profile. But there's no column headers so I cannot sort the results to group all instances of class `Thread` together.

Finally, some results are presumably missing because at the bottom of the list it says "Search aborted, more than 1000 results found" - that gives me a sad face, since the irrelevant results presumably prevent me from finding all the classes that are named `Thread`. There should be a way to increase the result limit, or have a separate limit for exact matches.

**Edit:** I just noticed there is a Regex search, but `^System.Threading.Thread$` and `^Thread$` give zero results.
**Edit 2**: Oooh, you have write `/^System.Threading.Thread$/`. Excellent!

Now if only I could more easily see which assemblies contain an instance of `Thread`...

**Comment by siegfriedpammer** [comment]
I just merged #668 which should fix the problem you are seeing. Also you could use `=Thread` to find exact matches.

**Comment by dgrunwald** [comment]
Note that #668 added a new option Display > Sort results by fitness, which needs to be enabled.
We'll enable it by default after it got some more testing.

**Comment by qwertie** [comment]
Thank you!
