### ISSUE TITLE
System.NotSupportedException: ICSharpCode.Decompiler.ILAst.ILFixedStatement

### ISSUE THREAD

**Issue by kissstudio** [icsharpcode/ILSpy#784]
meet the error when spy a method.

I added a if statement there, is it right?.

![qq 20161206225114](https://cloud.githubusercontent.com/assets/2771647/20929946/bc9609e4-bc06-11e6-9a02-b1bc0eb49a7f.png)

**Comment by dgrunwald** [comment]
This should be fixed in the new decompiler engine (which just landed on the master branch).
