### ISSUE TITLE
astbuilde.MakePrimitive should add cast while target type is not int

### ISSUE THREAD

**Issue by loobins** [icsharpcode/ILSpy#785]
IL_004f: ldc.i4 165
		IL_0054: callvirt instance void [mscorlib]System.IO.BinaryWriter::Write(uint8)

should be  decompiled to Write((byte)165) rather than Write((byte)165) .

//astbuilder.cs  Line:1612
 if(type.MetadataType == MetadataType.Char  || type.MetadataType == MetadataType.SByte  || type.MetadataType == MetadataType.Byte)
            {
                    return new Ast.PrimitiveExpression(CSharpPrimitiveCast.Cast(code, val, false)).CastTo(ConvertType(type));
                    
            }
            return new Ast.PrimitiveExpression(CSharpPrimitiveCast.Cast(code, val, false));

**Comment by siegfriedpammer** [comment]
Fixed on the newdecompiler branch.
