### ISSUE TITLE
decompiler produces source code with syntax errors for System.Xaml assembly

### ISSUE THREAD

**Issue by matthargett** [icsharpcode/ILSpy#788]
They all come down to not translating some generic types correctly:
```
BuiltInValueConverter.cs(36,24,36,25): error CS1001: Identifier expected
System.Xaml\XamlLanguage.cs(18,24,18,25): error CS1001: Identifier expected
```

The same line is the culprit in both cases: 
```
		private sealed class <>c
```

**Comment by siegfriedpammer** [comment]
This is not about translation of generic types but rather incomplete translation of compiler-generated code. This should be fixed in the new decompiler.
