### ISSUE TITLE
Dead loop in AsyncDecompiler when decompiling an async method 

### ISSUE THREAD

**Issue by kissstudio** [icsharpcode/ILSpy#790]
[xcontrol.core-cleaned.zip](https://github.com/icsharpcode/ILSpy/files/707182/xcontrol.core-cleaned.zip)

target class: xcontrol.core.Controls.MyScreen

snapshot:
![snapshot](https://cloud.githubusercontent.com/assets/2771647/21970034/d6583dec-dbdd-11e6-8177-c5acc88c9ed0.png)

**Comment by wtyvvv** [comment]
你好 你这个反混淆出来了吗  他是通过什么混淆的呢

**Comment by wtyvvv** [comment]
有qq吗 一起研究  我研究到最后一步了

**Comment by kissstudio** [comment]
没几个死循环，跳过就行了。可以得到99%的源码。

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
