### ISSUE TITLE
Question about the new decompiler

### ISSUE THREAD

**Issue by xoofx** [icsharpcode/ILSpy#792]
Hi there,
I saw that there is an on-going branch [newdecompiler](https://github.com/icsharpcode/ILSpy/commits/newdecompiler). Without going too much into the dirty details, I'm just curious where this branch is heading, what is its status and do you expect to merge it back to master later this year? (don't want an ETA but an overall feeling! 😅 )
Thanks!

**Comment by siegfriedpammer** [comment]
[newdecompiler](https://github.com/icsharpcode/ILSpy/commits/newdecompiler) is a rewrite of the ICSharpCode.Decompiler library. The reasons and goals for it are detailed on this page: [newdecompiler wiki](https://github.com/icsharpcode/ILSpy/wiki/newdecompiler).

The ground work is mostly done, of course there are a lot of features missing (mostly high level constructs such as foreach, using, yield and async), but we were planning to merge it back into master, hopefully in the next two to three months. After that we will work to prepare a 3.0 release with the new decompiler.

**Comment by xoofx** [comment]
Thanks a lot for the fast response, looking forward to try this new version. 👍
