### ISSUE TITLE
Call to an explicit interface implementation misses a cast in decompiled source (C# and VB)

### ISSUE THREAD

**Issue by jmairboeck** [icsharpcode/ILSpy#793]
Suppose you have the following interfaces:

```c#
interface IBase {
 int Property { get; }
}
interface IDerived : IBase {
 new int Property { get; } // this hides IBase.Property
}
```

A possible implementation of IDerived can have two implementations of the Property getter (via explicit implementation).

If you have some instance of IDerived and want to to call IBase's Property getter, you need a cast on the call site. However, ILSpy doesn't generate a cast.

```c#
IDerived instance = ...;
int x = ((IBase)instance).Property; //ILSpy doesn't generate this cast, calling the wrong property
```

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
