### ISSUE TITLE
NuGet ICSharpCode.Decompiler package update?

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [icsharpcode/ILSpy#796]
The ICSharpCode.Decompiler package on NuGet has seen no update in 1.5 years. Is it abandoned? Version 2.3.1 works fine for my needs, but it would be nice to use latest version of the decompiler.

**Comment by christophwille** [comment]
Related: https://github.com/icsharpcode/ILSpy/issues/831

**Comment by ZimM-LostPolygon** [comment]
@christophwille Why is the issue closed?

**Comment by christophwille** [comment]
Oh, you didn't follow #831 - it states that we have updated Nuget packages, plus a sample (now even as part of the main repository, ics.d.console)

**Comment by ZimM-LostPolygon** [comment]
Oh, cool! Thanks.
