### ISSUE TITLE
While loop with break shows as 'Exit for'

### ISSUE THREAD

**Issue by TheBarret** [icsharpcode/ILSpy#797]
I might be wrong but does it suppose to display "Exit For" in a while loop?

Screenshot:
![jiv5th8](https://cloud.githubusercontent.com/assets/25234371/23769618/4cbb0482-0510-11e7-9381-f2b5ac998c58.png)

Opcodes:
[opcode.txt](https://github.com/icsharpcode/ILSpy/files/832237/opcode.txt)

This project is from a script engine that compiles to IL called Delta

**Comment by dgrunwald** [comment]
We just landed a new decompiler engine, which does not support VB at the moment.
If we add back VB support in the future, it'll likely be a completely new implementation, so closing all VB-related issues.
