### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by yaakov-h** [icsharpcode/ILSpy#798]
On a handful of machines at my workplace, ILSpy often takes a significant amount of time to start up.

I've monitored it with Sysinternals Process Monitor and found that there are multi-second gaps in operations.

Most of these appear to be `QueryEAFile` operations. I have no idea what this is, but it appears to be happening within the CLR and Windows Kernel.

Do you have any idea what ILSpy may be doing to cause this? It is the only process that exhibits this behaviour, all other programs on these PCs launch in a reasonably expected amount of time.

![ilspy_qea_2](https://cloud.githubusercontent.com/assets/426009/24126601/05769fde-0e23-11e7-8000-e8dc9560a48f.PNG)
![ilspy_qea_3](https://cloud.githubusercontent.com/assets/426009/24126600/0575d720-0e23-11e7-907e-97ca8230c260.PNG)
![ilspy_qea_1](https://cloud.githubusercontent.com/assets/426009/24126599/0573f0f4-0e23-11e7-8a60-9badf3548428.PNG)
![ilspy_1](https://cloud.githubusercontent.com/assets/426009/24126602/078c3de2-0e23-11e7-9f3f-1ca7254e915f.PNG)

**Comment by tamlin-mike** [comment]
Only thing that comes to mind is a misbehaving anti-virus filesystem filter.

**Comment by siegfriedpammer** [comment]
On my system (Windows 10 Pro x64, notebook with SSD, 16 GB memory), starting ILSpy loading a list of all assemblies in my GAC only takes approx. 3 seconds in debug mode. This seems to be an AV problem...

**Comment by yaakov-h** [comment]
Hmmm. I see this in a lot of machines, but the only AV running on any of them is Windows Defender.

My machine in particular:

Windows 10 Enterprise x64 FCU
i9-7900X CPU, not overlocked
64GB RAM
SSD (Samsung 960 EVO)

The strange pauses above only happen on the first launch of ILSpy. Subsequent launches are fine.

ILSpy is also the only application affected.

😕

**Comment by tamlin-mike** [comment]
I came to think of three more things to check.

1. Switch procmon to display both "advanced" I/O (i.e. IRP's) and network activity (attempts).
2. As admin, delete %windir%\Prefetch\ILSpy*.pf
3. Check disk activity at the time this happens.

While it seems unlikely to me it would affect multiple machines, theoretically it could be an attempt to access an unavailable network (or other kind of unavailable, e.g. USB storage, unmounted volume, ...) resource.

Also to check could be the time-to-complete of the operation preceeding the gap.

Please note that this is by me now pure brainstorming, since I have never seen similar delays myself.

**Comment by yaakov-h** [comment]
This seems to be caused by Windows Defender. After adding ILSpy's folder to the exclusions list, it starts up quickly.

😕

**Comment by siegfriedpammer** [comment]
That's strange... Windows Defender is well-behaved on my system it seems. :(

**Comment by siegfriedpammer** [comment]
I just had an idea: did you already "unblock" all assemblies that are part of ILSpy?

![grafik](https://user-images.githubusercontent.com/344204/33917895-fc968342-dfb0-11e7-8f36-aa151122f7f7.png)

Maybe this helps to fix this issue. Also, when I tried to launch ILSpy as downloaded from the build server, Windows Defender started to show some scary prompts about ILSpy not being signed and so on, but I could not see any performance problems.

**Comment by yaakov-h** [comment]
Hmm, thanks. I'll try it.

**Comment by christophwille** [comment]
As this is no longer an issue of "ILSpy-slowness" (ie our code), I am closing this issue.
