### ISSUE TITLE
Incorrect paths with ASP.NET Core projects

### ISSUE THREAD

**Issue by grokky1** [icsharpcode/ILSpy#799]
Details [from this PR](https://github.com/icsharpcode/ILSpy/pull/706#issuecomment-289882270)

Environment is VS2015, and ASP.NET Core.

When right clicking a type in the code editor, and choosing the "open-with" command, it shows an error box with

>"could not find assembly, `c:\foo\bar\projectname.\bin', please ensure the project and references were built correctly!"

PS the "GoToILSpy for VS2015" extension works for me, so it's probably not my environment, but rather what is mentioned in the error message.

**Comment by bbi-yggy** [comment]
Thanks @grokky1.

It seems that the way the output assembly path name is determined is specific to project type. I only tested the "Open code in ILSpy" feature with regular C# projects. Will investigate, time permitting.

**Comment by grokky1** [comment]
@bbi-yggy FYI the bin paths for an ASP.NET Core project look like this:

    MySolution\src\MyProject\bin\Debug\netcoreapp1.1
    MySolution\src\MyProject\bin\Release\netcoreapp1.1

**Comment by siegfriedpammer** [comment]
Fixed by 3bfc1fc3c27fb13bb7c8be0b688e31a1639af258
