### ISSUE TITLE
Doesn't show StateMachine for async/await in C# mode

### ISSUE THREAD

**Issue by egorikas** [icsharpcode/ILSpy#801]
I have problems with decompiling a console application which is using .net 4.6 and async/await. My ILSpy version is 2.4.0.1963.

I have a simple class
```csharp
    public class Example
    {
        public async Task ShowStateMachine()
        {
            FirstSync();
            await Task.Delay(500);
            SecondSync();
        }

        public void FirstSync()
        {
            Console.WriteLine("First");
        }

        public void SecondSync()
        {
            Console.WriteLine("Second");
        }
    }
```
But when I open ILSPy in C#-mode, I can't go to the statemachine

![c mode](https://cloud.githubusercontent.com/assets/6932844/24837233/125c696c-1d38-11e7-8cb0-796b1f7b2982.png)

But it exists in IL-mode

![il mode](https://cloud.githubusercontent.com/assets/6932844/24837241/3355a336-1d38-11e7-93a5-d67d55f71474.png)

**Comment by lextm** [comment]
There is already a new decompiler engine, so you might try that, https://github.com/icsharpcode/ILSpy/tree/newdecompiler

**Comment by egorikas** [comment]
@lextm ok. I'll try it.

**Comment by egorikas** [comment]
The problem was in the decompiler options. I'd turned off everyone and saw the statemachine. Thank you
