### ISSUE TITLE
bugs about IntPtr

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#803]
class Program
{
    static void Main(string[] args)
    {
        IntPtr ip = new IntPtr();
        ip.ToInt32();
        ip.ToString();
        Test(new IntPtr());
    }
    public static void Test(IntPtr ip)
    {
    }
}
Decompiled by ILSpy:

private static void Main(string[] args)
{
IntPtr ip = 0;//error
ip.ToInt32();
ip.ToString();
Program.Test(0);//error
}

/* 0x0000025C 00           */ IL_0000: nop
/* 0x0000025D 1200         */ IL_0001: ldloca.s  ip
/* 0x0000025F FE1513000001 */ IL_0003: initobj   [mscorlib]System.IntPtr
/* 0x00000265 1200         */ IL_0009: ldloca.s  ip
/* 0x00000267 281100000A   */ IL_000B: call      instance int32 [mscorlib]System.IntPtr::ToInt32()
/* 0x0000026C 26           */ IL_0010: pop
/* 0x0000026D 1200         */ IL_0011: ldloca.s  ip
/* 0x0000026F FE1613000001 */ IL_0013: constrained. [mscorlib]System.IntPtr
/* 0x00000275 6F1200000A   */ IL_0019: callvirt  instance string [mscorlib]System.Object::ToString()
/* 0x0000027A 26           */ IL_001E: pop
/* 0x0000027B 1201         */ IL_001F: ldloca.s  CS$0$0000
/* 0x0000027D FE1513000001 */ IL_0021: initobj   [mscorlib]System.IntPtr
/* 0x00000283 07           */ IL_0027: ldloc.1
/* 0x00000284 2802000006   */ IL_0028: call      void ConsoleApplication94.Program::Test(native int)
/* 0x00000289 00           */ IL_002D: nop
/* 0x0000028A 2A           */ IL_002E: ret
The IL is new IntPtr(), but ILSpy convert it to 0.

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
