### ISSUE TITLE
TLS 1.2 Handshake failure while connecting with Super Web Socket.

### ISSUE THREAD

**Issue by sandipbramhankar** [icsharpcode/ILSpy#804]
Hi,

This is regarding the issue we are facing using TLS 1.2. We have installed the server on windows 2012 R2, enabling TLS 1.2 protocol (along with TLS 1.0,TLS 1.1 which we disabled later on).

As we could see even after the TLS 1.0, TLS 1.1 was disabled, in the TLS exchange we found TLS 1.0 still was sent. We saw in the websocket "ServerConfig" having the value "tls" for Security attribute  which didn't help us in changing to any other value (Tls11,Tls12).

As we just want to be sure if the protocol is supported in SuperWebSocket so that we might rule out the issue with the socket and look around the issue on the system.

We are using the nuget package version 0.9.0.2 and binary version as 0.9.0.0.

I hope to receive the response quick as we are just stuck up and unable to proceed.

PS- The connection was successful using Tls 1.0.

Thanks  & Regards,
Sandip

**Comment by lextm** [comment]
SuperWebSocket? That's clearly another project.
