### ISSUE TITLE
Incorrect code generated that attempts to negate an unsigned value.

### ISSUE THREAD

**Issue by mjmckp** [icsharpcode/ILSpy#807]
(Issue copied from https://github.com/0xd4d/dnSpy/issues/431)

The following bit of IL:
```
	IL_0033: ldloc.1
	IL_0034: ldc.i4.1
	IL_0035: shr.un
	IL_0036: ldloc.1
	IL_0037: ldc.i4.1
	IL_0038: conv.i8
	IL_0039: and
	IL_003a: neg
	IL_003b: xor
	IL_003c: stloc.1
	IL_003d: ldloc.1
	IL_003e: ret
```
Decompiles with dnSpy to the following invalid C# code:
```
return (long)((ulong)num >> 1 ^ (ulong)(-(ulong)(num & 1L)));
```
(where `num` is of type `long`).  This is invalid since it's not possible to negate a `ulong` value.

The correct code that should be generated is:
```
return (long)((ulong)num >> 1 ^ (ulong)(-(num & 1L)));
```

**Comment by Piedone** [comment]
Related (or possible duplicates): https://github.com/icsharpcode/ILSpy/issues/373, https://github.com/icsharpcode/ILSpy/issues/430, https://github.com/icsharpcode/NRefactory/issues/353

**Comment by dgrunwald** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).

**Comment by Piedone** [comment]
@dgrunwald do you mean this was tested somehow, is there some specific fix for this or any other change that would make this likely fixed?

**Comment by dgrunwald** [comment]
The whole logic for inserting casts was completely rewritten; and tested on various randomly-generated IL fragments.
I didn't test your specific case, but I think it's very likely fixed. Feel free to reopen if it isn't.

**Comment by Piedone** [comment]
I see, thank you. We had a similar issues with some code of ours, so once the new version is out on NuGet we'll check whether that specifically was also fixed.
