### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by adamralph** [icsharpcode/ILSpy#809]
Sometimes I want to compare one version of an assembly to another. It would be great if I could have two instances of ILSpy open next to each other.

I believe this would be best as a config option, switched off by default.

**Comment by siegfriedpammer** [comment]
You can use the command line argument `/separate`.
See also https://github.com/icsharpcode/ILSpy/wiki/Command-Line-Arguments

**Comment by adamralph** [comment]
👍 thanks for the info. That solves my immediate need.

I'll withdraw this issue and replace it with #810.
