### ISSUE TITLE
Global config switch for separate instances

### ISSUE THREAD

**Issue by adamralph** [icsharpcode/ILSpy#810]
While it's possible to force a separate instance using the `/separate` CLI switch, it would be nice to be able to set this globally in the GUI options.

**Comment by Radon222** [comment]
Resolved in Pull Request Allow Multiple Instance Option and Dialog #818
`https://github.com/icsharpcode/ILSpy/pull/818`

**Comment by siegfriedpammer** [comment]
#818 was merged. Therefore closing this.

**Comment by adamralph** [comment]
Fantastic. Thanks!
