### ISSUE TITLE
"Open output in ILSpy" not working for MSBuild 15 projects in VS2017

### ISSUE THREAD

**Issue by Zastai** [icsharpcode/ILSpy#815]
In VS2017, using "Open output in ILSpy" after a successful build gives an error, saying "Could not find assembly" but then pointing to the output directory without the assembly name. This is with both single- and multi-target projects.

**Comment by arthurborisow** [comment]
same problem for me with .net core project

**Comment by screig** [comment]
Seems to be a net core problem rather than VS 2017, try with a net framework project. I think the issue could be that when you try to open it from VS that is expecting an exe rather that a dll. For a console app (created in VS2017 in this case) a Net Core project produces a dll, where as under the Net Framework it produces an exe? Just an idea....

**Comment by Zastai** [comment]
If you create a NET desktop project, the csproj you get is still the "old" format (MSBuild 14), with almost everything spelled out. This only supports targeting a single framework at a time, and output goes in a $(Configuration) subdirectory.

The "new" format (MSBuild 15) is much leaner (in fact, you will often just specify the project type and target framework(s)); Visual Studio only generates such projects for .NET Core/Standard templates, but they can target the desktop framework too.
Because these support targeting multiple frameworks in one project, the output structure has changed, without output being under $(Configuration)\$(TargetFramework).
There is indeed the additional "fun" that a build core console app is a .dll and you only get a .exe when publishing (which adds additional subdirectories per target runtime); but that shouldn't affect ILSpy much, as long as it picks up the .dll.

It would be a start when the plugin is able to find the output for single-target new-format projects; however, for multi-target projects, it may have to pop up UI to select the specific assembly to open.

**Comment by screig** [comment]
Would agree with that, essentially I think it can read all the formats, its just looks like it is not finding the correct dir,

**Comment by sharwell** [comment]
:memo: This specifically impacts projects using the new project system, and is unrelated to the target framework used by the project.

**Comment by KostaVlev** [comment]
I am still getting the same error. Using -> Open code in ILSpy in netcoreapp2.0 project I get error message "Could not find assembly".

**Comment by christophwille** [comment]
You are using the VSIX available via the Releases tab? Because on the marketplace, it is still the old version (we push only release versions to the marketplace)

**Comment by bakhodirk** [comment]
ILSpy crashes on opening assembly which compiled under new debug information "portable". Use others instead portable, ILSpy will open well.
