### ISSUE TITLE
Problem with decompiling

### ISSUE THREAD

**Issue by Crumbler** [icsharpcode/ILSpy#827]
I'm trying to inject an assembly reference to a .exe file but no matter what I do I can't inject the assembly reference. How do you inject an assembly reference in the first place? Do you have to type the name with our without .ndll?

**Comment by siegfriedpammer** [comment]
You are trying to inject an assembly reference? ILSpy is not capable of doing that. Are you using any plugins? I would ask you to directly ask the maintainer of the plugin.

**Comment by siegfriedpammer** [comment]
Closing - no response.
