### ISSUE TITLE
Allow scoping search and analysis to a specific assembly or namespace

### ISSUE THREAD

**Issue by AGlezB** [icsharpcode/ILSpy#828]
As of version 2.4.0.1963 ILSpy looks at every single loaded assembly. This is very inconvenient when you are trying to locate elements with common words like _string_ or _char_.

What I'd really like is to be able to right-click on one assembly/namespace in the tree and select _**Scope to this**_ so search and analysis do not show hits from any class/namespace/assembly outside the selected scope.

This is not intended for clases and below. Only at assembly or namespace level.

**Comment by miloush** [comment]
@AGlezB I tried to implement search that let's you scope results to class/namespace/assembly, freel free to do some testing: https://github.com/miloush/ILSpy/tree/scoped-search (instructions in #1175)

Doesn't alter the analysis behaviour.

**Comment by AGlezB** [comment]
@miloush Nice. I'll do some testing and let you know.

**Comment by AGlezB** [comment]
Not working for Unity common namespace:
![image](https://user-images.githubusercontent.com/12277525/65926235-9ee1ae00-e3ca-11e9-8d7c-4bc5b71dd29a.png)

Other than that it works great but it is kind of hard to remember all the letters. My suggestions so far:

1. Allow both short an long forms:
```
e:pin in: t:serial
event:pin in: type:serial
```
2. Add some form of quick help for the search or a link to the relevant docs.
3. Add "Search here" context menus to assemblies and namespaces, and maybe other places, that open the search panel and autofill the `in: ` terms or just replace them if the search was already open.

**Comment by miloush** [comment]
Yeah, that's a fake name for display purposes, the namespace is actually not a hyphen, it's empty. Root namespaces are currently not included in the search strategy, but that's easy to fix. It should probably return results of empty namespaces as hyphens consistently with the tree, however the matching should probably work for empty namespaces too. `/^$/` would work but it does not meet the minimum length criteria for regex search. 

Some documentation is here: https://github.com/icsharpcode/ILSpy/wiki/Search-Options and also in the placeholder of the search box, which you can see if it is not focused, but I agree some more visible help would be useful, for example when there are no results.

I like the idea of autofilling in: from context menus, I will have a look into that.

**Comment by AGlezB** [comment]
Thanks for pointing out the docs. I'd just assumed there wasn't any.
I guess using the fake namespace is fine, regex is kind of overkill for that.
I noticed the placeholder help... a feature fit for enterprise software. :wink:

**Comment by AGlezB** [comment]
Done and done. Thanks.
