### ISSUE TITLE
typeof(T) is not fully decompiled

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#837]
Currently `typeof(T)` is being decompiled to the following:

```
Type.GetTypeFromHandle(typeof(T).TypeHandle)
```

:memo: Observed in the newdecompiler branch for `System.Collections.ObjectModel.Collection<T>`, method `ICollection.CopyTo`.

**Comment by sharwell** [comment]
💭 The problem seems to arise in the following two lines:

https://github.com/icsharpcode/ILSpy/blob/4bdd7f48b1f56f9f72e04bd9e61705862f36a033/ICSharpCode.Decompiler/CSharp/Transforms/ReplaceMethodCallsWithOperators.cs#L69-L70

When I tested this, `method.FullName` was returning `System.Type.GetTypeFromHandle` instead of the complete signature.

**Comment by siegfriedpammer** [comment]
Good catch, seems this was never properly ported from Cecil objects to the NR type system.
