### ISSUE TITLE
Searching for a metadata token

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#841]
Currently it is possible to show metadata tokens in the source tree, but it is not possible to search for them. It would be helpful if the search window supported searching for metadata tokens.

Options include:

1. Allowing a metadata token to be specified instead of a name while using another filter, e.g. `t:@0200029e` instead of `t:SomeTypeName`
2. Simply allowing the `@` as a new prefix for searching

**Comment by siegfriedpammer** [comment]
Not sure what the benefit of the first option is... `02` at the beginning already indicates, that this is row 670 of the TypeDef table... I've added the second option, but it would need some tweaking to show the containing file (instead of namespace), as the tokens are unique only per PE file.

**Comment by siegfriedpammer** [comment]
In #1263 we've added a tooltip showing the filename for each search result. I think this fixed the last thing that was missing and this can be closed.
