### ISSUE TITLE
Support netcore/netstandard "runtime" references

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#845]
The following places need to be updated to support the new netcore/netstandard IL/attribute format:

* https://github.com/icsharpcode/ILSpy/blob/newdecompiler/ICSharpCode.Decompiler/IL/ILReader.cs
* https://github.com/icsharpcode/ILSpy/blob/newdecompiler/ICSharpCode.Decompiler/TypeSystem/Implementation/BlobReader.cs

Is there any specification/documentation on the format changes?

Update: Seems like the IL format is the same, but we need to find a way to resolve netcore/netstandard runtimes.

netcore: "bcl" references should be located at `%ProgramFiles%\dotnet\shared\Microsoft.NETCore.App2.0\<version>`
netstandard: ?

**Comment by dgrunwald** [comment]
I don't think there is a format change to attributes. It's just that the constructor parameter types must be available in order to correctly decode attribute blobs.

**Comment by siegfriedpammer** [comment]
See #848
