### ISSUE TITLE
how to generate namespace definition

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#852]
I write a plugin for ILSpy, some code like this:
        public static void Test(TypeDefinition td)
        {
            DecompilationOptions option = new DecompilationOptions();
            CSharpLanguage cs = new CSharpLanguage();
            var output = new PlainTextOutput();
            cs.DecompileType(td, output, option);
            Debug.Fail(output.ToString());
        }
but the output don't contains namespace definition:

using ...
**namespace xxx**   // lose
{ //lose
   class xxx
   {
   }
} //lose

How to generate namespace definition?

**Comment by dgrunwald** [comment]
That's not possible through the `CSharpLanguage` API; you'll have to use the decompiler API directly (now that newdecompiler landed on the master branch: `ICSharpCode.Decompiler.CSharp.CSharpDecompiler`).

There, `DecompileTypes()` will give you namespace definitions, while `Decompile()` will just decompile the type/member itself.

**Comment by CreateAndInject** [comment]
Thanks!
