### ISSUE TITLE
Inconsistent annotations: ILVariable vs. ILVariableResolveResult

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#854]
public static class AnnotationExtensions
{
public static ILVariable GetILVariable(this VariableInitializer vi)
{
    `return vi.Annotation<ILVariable>();`  ==> `return vi.Annotation<ILVariableResolveResult>().Variable;`
}
}

**Comment by siegfriedpammer** [comment]
Actually I would prefer to use `ILVariableResolveResult` everywhere to be consistent. Then we could add an extra overload that performs ResolveResult unpacking as you suggested.

**Comment by CreateAndInject** [comment]
both  ILVariableResolveResult  and ResolveResult  are correct.
`vi.Annotation<ILVariable>()` allways is `null`

**Comment by dgrunwald** [comment]
Yes this is a bug, we should consistently use `ILVariableResolveResult`.

(`vi.Annotation<ILVariable>()` is currently non-null in only two special cases: `fixed` and `using` statements)
