### ISSUE TITLE
Failure to decompile foreach in some cases

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#860]
```cs
class ForeachTest
{
    class Disposable : IDisposable
    {
        public void Dispose() { }
    }

    void Test()
    {
        using (new Disposable())
        {
            foreach (var item in new System.Collections.Generic.List<string>())
            {
                Console.Write(item);
            }
        }
    }
}
```
Produces this:
```cs
internal class ForeachTest
{
	private class Disposable : IDisposable
	{
		public void Dispose()
		{
		}
	}

	private void Test()
	{
		using (new Disposable())
		{
			using (List<string>.Enumerator enumerator = new List<string>().GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					Console.Write(enumerator.Current);
				}
			}
		}
	}
}
```

**Comment by siegfriedpammer** [comment]
This is because Roslyn is emitting an optimized foreach pattern (in release build), which does not use an extra local variable for `enumerator.Current`.

**Comment by mmusu3** [comment]
I have found other cases that aren't due to `Current` optimizations

```cs
void Test2(Dictionary<int, int> pairs)
{
    int num = 0;

    foreach (KeyValuePair<int, int> pair in pairs)
    {
        if (pair.Key > pair.Value)
            num += 1;
    }
}
```
Produces this:
```cs
private void Test2(Dictionary<int, int> pairs)
{
	int num = 0;
	using (Dictionary<int, int>.Enumerator enumerator = pairs.GetEnumerator())
	{
		while (enumerator.MoveNext())
		{
			KeyValuePair<int, int> pair = enumerator.Current;
			if (pair.Key > pair.Value)
			{
				num++;
			}
		}
	}
}
```

**Comment by mmusu3** [comment]
It seems that recent commits have fixed most cases including those above. However I have found another. Compiled in release.
```cs
string Test3(string str)
{
	string result = str;

	foreach (var obj in GetObjects())
	{
		if (obj.Str1 == str)
		{
			result = obj.Str2;
			break;
		}
	}

	return result;
}

struct Data
{
	public string Str1;
	public string Str2;
}

List<Data> GetObjects() => new List<Data>();
```
Produces:
```cs
private string Test3(string str)
{
	using (List<Data>.Enumerator enumerator = this.GetObjects().GetEnumerator())
	{
		Data obj;
		while (true)
		{
			if (enumerator.MoveNext())
			{
				obj = enumerator.Current;
				if (obj.Str1 == str)
					break;
				continue;
			}
			return str;
		}
		return obj.Str2;
	}
}

private List<Data> GetObjects()
{
	return new List<Data>();
}
```

**Comment by siegfriedpammer** [comment]
The last failing test case is the same as #861

**Comment by dgrunwald** [comment]
The first two test cases were fixed in @siegfriedpammer's foreach update.

In the third test case, the code generated by Roslyn in release is similar to what non-Roslyn would generate if you had an early return within the loop. The decompiler eliminates what it believes to be a compiler-generated return variable, thus turning the program into one with an early return within the loop (which is affected by #861).
But I think we could tell that this isn't a true return variable (because there are stores not immediately followed by a return statement) and avoid replacing the "break;" with an early return.

**Comment by mmusu3** [comment]
Hi, sorry to continue with this but the previous test case seems to have been fixed however I have found another simpler test case that is still incorrect.
```cs
object Test4(List<object> objects)
{
    foreach (var obj in objects)
        return obj;

    return null;
}
```
Produces:
```cs
private object Test4(List<object> objects)
{
	using (List<object>.Enumerator enumerator = objects.GetEnumerator())
	{
		if (enumerator.MoveNext())
		{
			return enumerator.Current;
		}
	}
	return null;
}
```
I hope my test isn't *too* simple.

**Comment by dgrunwald** [comment]
That test is indeed too simple: after compilation, it no longer contains any loop at all! (the loop backedge was unreachable due to the return, and got optimized out by the C# compiler)

We could add a whole new special transform for the "foreach that doesn't actually loop" case, but I doubt that's worth the effort.

**Comment by siegfriedpammer** [comment]
See #824 as well... earlier we've decided to not fix this issue, because it's not worth the effort.

**Comment by mmusu3** [comment]
Whoops! I should have noticed there was no while loop output in that last example. Sorry. I guess I reduced the test case too much. I think the problem I was seeing may still be present though so I will try to get a better example. Thanks for all the work you've done so far!

**Comment by siegfriedpammer** [comment]
I am closing this as the `using-if (enumerator.MoveNext())` pattern is expected.
