### ISSUE TITLE
Invalid assignment to returned value

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#882]
The output from decompiling this code cannot be recompiled due to referencing the unassigned local variable `item`.
```cs
class Item
{
    public Item Self;
}

static void Test()
{
    var item = GetItem(null);
    item.Self = item;
}

static Item GetItem(object obj) => null;
```
Produces:
```cs
private class Item
{
    public Item Self;
}

private static void Test()
{
    object obj = ((Item)obj).Self = GetItem(null);
}

private static Item GetItem(object obj)
{
    return null;
}
```

**Comment by siegfriedpammer** [comment]
Thanks for reporting this! I think we need more test cases in this area. If you could provide some, this would be very nice.

**Comment by mmusu3** [comment]
I think this is the first I've seen but if I come across any more I'll be sure to report them.

**Comment by mmusu3** [comment]
I have another test case for this issue. Tested at commit 17d19cd04a9f6c8419772dcd88dce8d01f17e2d6

Source:
```cs
struct Data
{
    public bool Condition { get; set; }
}

static Data GetData()
{
    throw new NotImplementedException();
}

static void Test()
{
    Data data = GetData();
    data.Condition = false;
}
```

Output:
```cs
struct Data
{
    public bool Condition
    {
        get;
        set;
    }
}

static Data GetData()
{
    throw new NotImplementedException();
}

static void Test()
{
    GetData().Condition = false;
}
```

**Comment by siegfriedpammer** [comment]
Please do not revive closed issues. You can open a new issue for each problem you discover. Thank you!

**Comment by dgrunwald** [comment]
I don't see a problem there. The semantics of `Data data = GetData(); data.Condition = false;` and `GetData().Condition = false;` are identical if the `data` variable is not used elsewhere.
The C# compiler tends to optimize out such local variables in release builds, so we can't tell what the original code looked like.

**Comment by mmusu3** [comment]
In this case the compiler does generate a local variable even in release. `GetData().Condition = false;` is invalid since it produces an error: `Error CS1612 Cannot modify the return value of 'GetData()' because it is not a variable`.

I though that this example might be a bit too simple to be representative. Here is another that is more like the original problem I encountered where the struct is a wrapper for unmanaged data (still simplified). I hope it gives a better idea of the issue.

Source:
```cs
unsafe struct Data
{
    byte* ptr;

    public bool Condition
    {
        get { return *(bool*)ptr; }
        set { *(bool*)ptr = value; }
    }
}

static Data GetData()
{
    throw new NotImplementedException();
}

static void Test()
{
    Data data = GetData();
    data.Condition = false;
}
```

Output:
```cs
private struct Data
{
    public unsafe bool Condition
    {
        get
        {
            return *ptr != 0;
        }
        set
        {
            *ptr = (value ? ((byte)1) : ((byte)0));
        }
    }

    private unsafe byte* ptr;
}

private static Data GetData()
{
    throw new NotImplementedException();
}

private static void Test()
{
    GetData().Condition = false;
}
```
