### ISSUE TITLE
ILSpy show add/remove in event

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#884]
public event EventHandler VerifySettings
{
	[MethodImpl(MethodImplOptions.Synchronized)]
	add
	{
		this.VerifySettings = (EventHandler)Delegate.Combine(this.VerifySettings, value);
	}
	[MethodImpl(MethodImplOptions.Synchronized)]
	remove
	{
		this.VerifySettings = (EventHandler)Delegate.Remove(this.VerifySettings, value);
	}
}

Reflector & dnSpy just show:
public event EventHandler VerifySettings;

**Comment by siegfriedpammer** [comment]
See #698 

I fixed this in af6935a46f0822e4196dac24b8ecf2fe3afa3606
