### ISSUE TITLE
Unessesary default(T) assignments

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#890]
Local variables that are not assigned at definition but are fully assigned before use are unnecessarily given a `default` initial value.
```cs
void Test()
{
    int i;
    int.TryParse("1", out i);
}

struct Data
{
    public int i;
    public float f;
}

void Test2()
{
    Data data;
    data.i = 1;
    data.f = 6f;
}
```
Output:
```cs
private struct Data
{
    public int i;
    public float f;
}

private void Test()
{
    int i = default(int);
    int.TryParse("1", out i);
}

private void Test2()
{
    Data data = default(Data);
    data.i = 1;
    data.f = 6f;
}
```

**Comment by CreateAndInject** [comment]
Maybe it's hard to determine whether it are fully assigned before using.
ILSpy 2.x doesn't give a default initial value, and allways occurs compiler errors.
So, maybe it's unessesary, but it's safe and no side-effect.

**Comment by dgrunwald** [comment]
We currently use an IL-level analysis for definite assignment. This doesn't distinguish between `ref` and `out` parameters, so it creates the default value just to be safe.
For your first example, we'll probably end up generating `out int i` once that feature is implemented.

For the second example, this requires the full C# definite assignment analysis including structs. This probably won't happen, except maybe if somehow can re-use the existing analysis from Roslyn.

**Comment by mmusu3** [comment]
This isn't a breaking issue for me just something I would prefer to see done. If there are no plans to implement this you can close the issue.
