### ISSUE TITLE
Documentation XML is collapsed if no "using"s

### ISSUE THREAD

**Issue by mindless2112** [icsharpcode/ILSpy#891]
Normally the initial state of the code view is that the "using"s are collapsed and the documentation XML on the type/member is not collapsed.  If there are no "using"s then the documentation XML is collapsed.  This is unexpected.

ILSpy version 3.0.0.2787

**Comment by siegfriedpammer** [comment]
Can you provide an example from a publicly available DLL? So far, I could not reproduce it. Hunting for such a rare case is wasting my time.

**Comment by dgrunwald** [comment]
This is probably due to icsharpcode/AvalonEdit#87

**Comment by mindless2112** [comment]
[Example](https://github.com/icsharpcode/ILSpy/files/1347274/Example.zip) attached.

**Comment by siegfriedpammer** [comment]
This was fixed by the AvalonEdit upgrade in c202b9145bbf2d348594ff570733ae4c5666f400
