### ISSUE TITLE
Local variable name highlighter sometimes only finds subset of usages

### ISSUE THREAD

**Issue by mindless2112** [icsharpcode/ILSpy#893]
When highlighting a variable name, the highlighter sometimes only highlights a subset of usages.  Which subset it highlights depends on which usage is under the cursor.  See the screenshots for an example.

![screenshot1](https://user-images.githubusercontent.com/676569/31065379-02b422c6-a702-11e7-8771-bd3e577167c5.png)
![screenshot2](https://user-images.githubusercontent.com/676569/31065380-048149e4-a702-11e7-9fa6-6fe160ac939c.png)

ILSpy version 3.0.0.2787

**Comment by siegfriedpammer** [comment]
This is due to two different `ILVariable`s being used. Probably we'll have to unify the `ILVariableResolveResult` annotations as we unify `ILVariable`s in `AssignVariableNames`?
