### ISSUE TITLE
Support by-ref types

### ISSUE THREAD

**Issue by sharwell** [icsharpcode/ILSpy#894]
The new `ref struct` feature in C# 7.2 results in several attributes applying to the compiled code. ILSpy should be updated to recognize these attributes and decompile the code to a `ref struct` instead.

As seen in dotnet/roslyn#22453, these attributes are:

* `IsByRefLikeAttribute` (applies for all `ref struct`)
* `IsReadOnlyAttribute` (applies for `readonly ref struct`)
* `ObsoleteAttribute` (emitted with the specific message hard-coded)

Let me know if you have any questions about this :smile:

**Comment by siegfriedpammer** [comment]
Closing this, because support for the attributes was added long ago. #829 will be updated accordingly as soon as we've achieved test coverage and support for most use-cases.
