### ISSUE TITLE
Minor flaws in 'checked' generation

### ISSUE THREAD

**Issue by KevinCathcart** [icsharpcode/ILSpy#90]
`System.Linq.Enumerable.Average(this IEnumerable<int> source)`.
The decompiled code is:

```
public static double Average(this IEnumerable<int> source)
{
    checked
    {
        if (source == null)
        {
            throw Error.ArgumentNull("source");
        }
        long num = 0L;
        long num2 = 0L;
        foreach (int current in source)
        {
            num += unchecked((long)current);
            num2 += 1L;
        }
        if (num2 > 0L)
        {
            return (double)num / (double)num2;
        }
        throw Error.NoElements();
    }
}
```

The unchecked expression and cast is unnecessary. There is no way that the int to long conversion could overflow. The compiler knows this, which is why it does not use the overflow form of the conversion operator.

I actually checked the original source of this function to be sure of that. The other differences from the original source are mostly stylistic, such as size of the checked block, using a post-increment rather than `+= 1L`, and only one cast to double on the return statement.

`System.Linq.EnumerableAverage(this IEnumerable<double> source)`

This function has an indisputable bug. The decompiled code contains a statement of the form `checked(num2 += 1L);`, which does not compile. Also there is a pattern match failure here. The while inside the using should actually be a foreach loop.

**Comment by siegfriedpammer** [comment]
This was likely fixed in the new decompiler engine (which just landed on the master branch).
