### ISSUE TITLE
System.InvalidOperationException: Could not find block for branch target

### ISSUE THREAD

**Issue by bprg** [icsharpcode/ILSpy#902]
I wanted to decompile a project but return this error, I tried latest version.

![error](https://user-images.githubusercontent.com/706507/31314316-f873f7f4-abb2-11e7-856e-771cf406c69c.png)

**Comment by siegfriedpammer** [comment]
Can you please post either the assembly or a file containing the output from ildasm? You will have to try to decompile each class/method individually to find the offender. Otherwise this will be difficult to solve. Thank you for your support!

**Comment by bprg** [comment]
This project is private, I send privately, What's your e-mail? Thank you for your support!

**Comment by bprg** [comment]
It seems this _Method_ is obfuscated So it can not decompile.
