### ISSUE TITLE
Incorrect decompilation of foreach over 'Array'

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#905]
Test case:
```cs
enum Values { }

void Test(string name, ref Values value)
{
    foreach (Values v in Enum.GetValues(typeof(Values)))
    {
        if (v.ToString() == name)
        {
            value = v;
            break;
        }
    }
}
```
Output:
```cs
private enum Values
{
}

private void Test(string name, ref Values value)
{
    IEnumerator enumerator = Enum.GetValues(typeof(Values)).GetEnumerator();
    try
    {
        Values v;
        while (true)
        {
            if (enumerator.MoveNext())
            {
                v = (Values)enumerator.Current;
                if (v.ToString() == name)
                    break;
                continue;
            }
            return;
        }
        value = v;
    }
    finally
    {
        IDisposable disposable = enumerator as IDisposable;
        if (disposable != null)
            disposable.Dispose();
    }
}
```

**Comment by tamlin-mike** [comment]
I generated a similar boiled down example, and while the following doesn't exhibit the manual Dispose (it's using `using`), interestingly it displayed another decompilation bug.

```
using System;
using System.Collections.Generic;
class foo {
	List<object> coll = new List<object>(2);
	object o;
	void Works() { foreach (var v in coll) { o=v; } }
	void Fails() { foreach (var v in coll) { o=v; break; } }
}
```

That is, the only difference between the loop bodies is the addition of the `break`.

Not only does it fail to grok the foreach pattern in the failing case, the `break` is missing from decompiler output.

Provided I read the ILAst correctly, even at the last step it's having the `break` (now converted to `leave`), but at C# with no transforms the result is as follows, and the vital `break`is missing.

	private void Works()
	{
		foreach (object item in this.coll)
		{
			obj = (this.o = item);
		}
	}

	private void Fails()
	{
		using (Enumerator enumerator = this.coll.GetEnumerator())
		{
			if (enumerator.MoveNext())
			{
				obj = (this.o = enumerator.Current);
			}
		}
	}

**Comment by dgrunwald** [comment]
@tamlin-mike: Your example got boiled too much: it no longer contains any loop. There's no bug there, unless you want us to convert loop-free IL code into "foreach".

**Comment by tamlin-mike** [comment]
/me slaps forehead

Thanks, you're right. :-)

**Comment by tamlin-mike** [comment]
Adding `if (v==null)` before the break, or even `if (v==null) continue;` at head of both loop bodies fixes my short circuit (both brain and code).

So it seems it's the addition of jumps, to both loop-start (`continue`) and after-loop-end (`break`) making the foreach detection fail.

I tested my revised example with dnSpy, and it got it right (although "chattier" with a redundant local `bool` introduced). Perhaps ideas could be borrowed?

**Comment by siegfriedpammer** [comment]
Afaik dnSpy uses our old decompiler engine with a few modifications, not sure if we can borrow easily from them, as we did a complete rewrite of the engine.

**Comment by dgrunwald** [comment]
Let's keep this issue for the problem in the original post: foreach transform fails due the try-block containing not just the `while`, but also another statement that would better be placed within the loop.

Which has an obvious fix: use the try-block's exit point as loop exit point if the loop looks like it might be a foreach loop.
