### ISSUE TITLE
Multiple unnecessary casts

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#907]
Test cases:
```cs
string Test1()
{
    string s = null;
    NoOp(s);
    return null;
}

void NoOp(string s) { }

void Test2(Action action)
{
    if (action != null)
        NoOp();
}

void NoOp() { }

void Test3(string text)
{
    NoOp(new Dictionary<string, object> { { "", text } });
}

void NoOp(Dictionary<string, object> d) { }
```
Output:
```cs
private string Test1()
{
    string s = (string)null;
    this.NoOp(s);
    return (string)null;
}

private void Test2(Action action)
{
    if ((object)action != null)
    {
        this.NoOp();
    }
}

private void Test3(string text)
{
    this.NoOp(new Dictionary<string, object>
    {
        {
            "",
            (object)text
        }
    });
}
```

**Comment by tamlin-mike** [comment]
Sometimes the cast to `object` is required when comparing to (even) `null`. Example (reduced to display the issue):

    public static bool operator ==(Foo a, Foo b)
    {
        return ((object)a != null && (object)b != null && a.Equals(b));
    }
    public static bool operator !=(Foo a, Foo b)
    {
        return !(a == b);
    }

With the casts, the two comparisons to `null` correctly produces the IL
`    ldarg.0`
`    brfalse somewhere`

Without the casts, it generates call(s) to `operator!=`, which obviously results in infinite recursion.

This probably depends on the referred type implementing the referred operator(s). If they are not accessible, the casts could probably be left out, but I feel it's better to err on the side of caution (and generate source that behaves correctly when re-compiled) than a re-compilation of the code generating unexpected crashes.

**Comment by dgrunwald** [comment]
Test 1: unnecessary casts on constants were fixed recently.
Test 2: Here the decompiler is casting to object to avoid picking up `Delegate.op_Equality()` instead of a reference comparison. We'll need a special case for delegates here.
Test 3: Collection initializers currently cast to the exact target type to make sure we'll call the correct overload of the `Add` method. We should run overload resolution to test whether the cast is necessary.

**Comment by mmusu3** [comment]
Test 1 does appear to be resolved now, thanks.
I am ok with how Test 2 is.
I have found other issues though.

This one doesn't seem to be quite the same as test 2.
The equality test is using Type.op_Equality however the null is not implicitly cast.
```cs
void Test4(Type type)
{
    if (type == null)
        NoOp();
}
```
Output:
```cs
private void Test4(Type type)
{
    if (type == (Type)null)
    {
        this.NoOp();
    }
}
```

Here Type is cast to MemberInfo as that is what GetCustomAttribute requires however the cast should be implicit.
```cs
Attribute Test5(Type type)
{
    return System.Reflection.CustomAttributeExtensions.GetCustomAttribute<AttributeUsageAttribute>(type);
}
```
Output:
```cs
private Attribute Test5(Type type)
{
    return ((MemberInfo)type).GetCustomAttribute<AttributeUsageAttribute>();
}
```
Another similar case:
```cs
static float Test6(string value, float defaultValue)
{
    float result;
    if (float.TryParse(value, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out result))
        return result;

    return defaultValue;
}
```
Output:
```cs
private static float Test6(string value, float defaultValue)
{
    float result = default(float);
    if (float.TryParse(value, NumberStyles.Float, (IFormatProvider)CultureInfo.InvariantCulture, out result))
    {
        return result;
    }
    return defaultValue;
}
```
Lastly returning a valuetype enumerator as an IEnumerable causes two casts, one being a box
```cs
class EnumerableClass<T> : IEnumerable<T>
{
    List<T> list;

    public IEnumerator<T> GetEnumerator() => list.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => list.GetEnumerator();
}
```
Output:
```cs
private class EnumerableClass<T> : IEnumerable<T>, IEnumerable
{
    private List<T> list;

    public IEnumerator<T> GetEnumerator()
    {
        return (IEnumerator<T>)(object)this.list.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return (IEnumerator)(object)this.list.GetEnumerator();
    }
}
```
These cover most of the casting issues I have found so far.

**Comment by siegfriedpammer** [comment]
As of d04155132affcc36ede6f98b9c18a7676bedc1b0 only `Test4` and `Test5` use unnecessary casts.

**Comment by dgrunwald** [comment]
I believe all problems here are fixed now.
Please open a new issue for additional casting issues, this one is getting hard to follow.
