### ISSUE TITLE
Loop detection picks exit point which was already included in nested loop

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/ILSpy#915]
Try decompiling `System.Diagnostics.Tracing.EventSource::SendManifest(System.Byte[])`, there will be a debug assertion.
Looks like we're mishandling loops within fixed blocks.

**Comment by tamlin-mike** [comment]
The problem comes from ExtendLoop, specifically its call to ExtendLoopHeuristic. If commenting that out that call, invariants hold true.

Seems the node triggering it (a `br`) is outside the BB that should be parent.

**Comment by dgrunwald** [comment]
Here's a reduced test case (using a try-finally block instead of fixed block):
```
private void LoopWithGotoRepeat()
{
	try {
		REPEAT:
		Console.WriteLine("after repeat label");
		while (GetBool("Loop condition")) {
			if (GetBool("if1")) {
				if (GetBool("if3")) {
					goto REPEAT;
				}
				break;
			}
		}
		Console.WriteLine("after loop");
	} finally {
		Console.WriteLine("finally");
	}
	Console.WriteLine("after finally");
}
```

ILAst of the try-block after the first loop has been detected:
```
BlockContainer {
	Block IL_0001 (incoming: 1) {
		br IL_0002
	}

	Block IL_0002 (incoming: 2) {
		call WriteLine(ldstr "after repeat label")
		br IL_0036
	}

	Block IL_0036 (incoming: 1) {
		BlockContainer (loop) {
			Block IL_0036 (incoming: 2) {
				if (call GetBool(ldloc this, ldstr "Loop condition")) br IL_0010
				br IL_0045
			}

			Block IL_0010 (incoming: 1) {
				if (logic.not(call GetBool(ldloc this, ldstr "if1"))) br IL_0036
				br IL_0020
			}

			Block IL_0020 (incoming: 1) {
				if (logic.not(call GetBool(ldloc this, ldstr "if3"))) br IL_0045
				br IL_0002
			}

			Block IL_0045 (incoming: 2) {
				call WriteLine(ldstr "after loop")
				leave IL_0001 (nop)
			}

		}
	}
}
```

Control flow graph of the try-block: (black edges are control flow, green edges are dominance)
![cfg](https://user-images.githubusercontent.com/243140/32417127-00983b8a-c255-11e7-89fe-bc016b51d1ae.png)

There's two natural loops: { IL_0036, IL_0010 } and { IL_0002, IL_0036, IL_0010, IL_0020 }.

Now what happens is that when the first loop is detected, it has no clear unique exit point (there's an exit out of the try-block via IL_0045, and the exit back to IL_0002), so we fall back to the heuristic, which decides to also include IL_0020 and IL_0045 in the loop.
Then when the second (outer) loop is detected, we discover (via post-dominance) the exit point IL_0045. So everything but IL_0045 is included into the outer loop.
But that puts IL_0045 both within the inner loop and outside the outer loop, which is a contradiction.

**Comment by dgrunwald** [comment]
As for solutions: the obvious fix is to just force all blocks that are already within nested loops to be also within the outer loop. This fixes the correctness issue no matter what decisions are made by `ExtendLoop()`.

But it's unfortunate that a clear obvious decision (IL_0045 is the exit point of the outer loop) is made difficult based on the decisions a heuristic made prior to that. I guess we could remove `ExtendLoopHeuristic` from the loop detection, and instead run something like it in a second pass, so that it can take the decisions of loop detection for outer loops into account.

**Comment by dgrunwald** [comment]
Decompiled result with the fix:

```
private void LoopWithGotoRepeat()
{
	Console.WriteLine("LoopWithGotoRepeat:");
	try
	{
		while (true)
		{
			Console.WriteLine("after repeat label");
			while (true)
			{
				if (Loops.GetBool("Loop condition"))
				{
					if (!Loops.GetBool("if1"))
					{
						continue;
					}
					if (Loops.GetBool("if3"))
						break;
				}
				Console.WriteLine("after loop");
				goto end_IL_000c;
			}
		}
		end_IL_000c:;
	}
	finally
	{
		Console.WriteLine("finally");
	}
	Console.WriteLine("after finally");
}
```
That's not pretty (IL_0045="after loop" shouldn't be within the loops); but it's correct, and I think this problem can only occur if the original code was already using goto.

**Comment by tamlin-mike** [comment]
"I guess we could remove `ExtendLoopHeuristic` from the loop detection, and instead run something like it in a second pass"

Taking a step back, I think you may be on to something.

My line of thought is: First and foremost correctness is the most important. Only after a *fully formed* and valid IL AST (no matter how ugly and full of `goto`'s etc) is created would higher-level transformations and construct identification (such as loop finders in this case) kick in, then finally optimization steps (which in turn might f.ex. short-circuit logical operations to the point further high-level loop constructs could be identified).
It feels like that would provide a natural separation of tasks and responsibilities.

At first glance it seems ... logical, but there are probably a gazillion border-cases I haven't though of.

Comments?

Another idea that just struck me, could *generating* terminals in some specific cases actually help/simplify CFA? I'm thinking of cases with f.ex. nested loops, and compiler has optimized to the point it jumps out of multiple loops. When there is an "obvious" exit point, but that's the target of multiple BB's, or would simply be outside the current BB (in this case, an inner loop), could CFA's job be made easier by introducing a *virtual* (-ish) terminal, that is only a jump to exit point, and then keeping that around until a later cleanup pass?

I probably made a mess of trying to explain this thought, and I don't know if it has any merit whatsoever, but felt it could potentially have some use.

"I think this problem can only occur if the original code was already using goto"
After some searching I found the actual source code, and indeed there's the label and at 3243 we find the goto.

https://github.com/dotnet/coreclr/blob/4be1b4b90f17418e5784a269cc5214efe24a5afa/src/mscorlib/shared/System/Diagnostics/Tracing/EventSource.cs#L3226

Sidenote: braces inconsistency in decompiled code. "if1" have braces, "if3" not.

**Comment by dgrunwald** [comment]
I don't think extra blocks would make things easier. If anything they cause problems (hence why we remove them in an early transform if the original IL contains such redundant branches).

All loops in C# have exactly one entry-point (because `goto` can't jump into blocks), and usually also one exit-point (the block being jumped to when the loop condition is false / when a "break;" is executed -- we're not counting return/throw as exit point).
When we're detecting natural loops, we get the entry-point (=loop head) for free.
We also get both lower bounds and upper bounds on the loop content (lower bound: the natural loop, i.e. the set of blocks from which a back-edge is reachable; upper bound: set of blocks dominated by the loop).
If there's a single exit-point, that's also easy to find: it's the common post-dominator of all blocks in the loop.

So the only cases where the loop contents are ambiguous are:
a) There are zero exits out of the set of blocks dominated by the loop head. Correctness-wise, we could include all the code in the loop. But we could also pick one of the self-contained subtrees and use it as exit point.
Including all code in the loop makes the code more nested than necessary, so we use a heuristic (`PickExitPoint`) to pick a subtree that gets excluded from the loop.
b) There is no common post-dominator, and set of blocks dominated by the loop head can be left via multiple different branches. In this case, there must be multiple different branches leaving the loop, hence the code must use `goto` (or additional variables) to be represented in C#. We use a different heuristic (`ExtendLoopHeuristic`) to try and reduce the number of `goto`s.

If I see this correctly, only the `ExtendLoopHeuristic` has the potential of preventing an outer loop from picking its preferred single exit-point. But given that this should only be called in cases that require `goto` anyway, it's probably not worth the effort to move this part into a later pass.

**Comment by dgrunwald** [comment]
Actually now that I've written it out, I think there's a bug in the implementation:
We currently don't distinguish between
b) There is no common post-dominator, and set of blocks dominated by the loop head can be left via multiple different branches.
and
c) There is no common post-dominator, because the set of blocks dominated by the loop head is left via a branch to a block outside the container that we ran dominance analysis on.

Case c) has an obvious exit point (the block outside the container), but we currently fall back to the heuristic, which might or might find the correct loop body.

**Comment by tamlin-mike** [comment]
Thanks for the explanation. I was originally (once I slept on it and got my thoughts sorted) thinking of some kind of explicit BBexit field for Block, that would reference the BB-exit but not have it explicitly be part of initial analysis, in hope it could simplify block nesting and/or reordering, but after digesting your explanation I realize it would probably add very little (at this point in time), or even just make it messier.

Case c) sounds to me very much like a `goto`, provided that "external" (in the loosest sense) block has multiple entry references. If it had only one entry (the one from inside the loop), it would already have been inlined or at least been found by CFA to have only one entry, and therefore it would have been part of dominance analysis, no?

**Comment by dgrunwald** [comment]
Case c) is code like this:
```
try {
   while (GetBool("condition")) { }
} finally {
}
Console.WriteLine("outside exit point");
```
Dominance analysis is per-BlockContainer, so the code outside the try-block is not considered for dominance analysis within the try-block.

So this code snippet currently triggers the `ExtendLoopHeuristic` even though there's no `goto`. Of course, the snippet is also simple enough the heuristic doesn't cause any problems.

**Comment by tamlin-mike** [comment]
Thanks for the example. It made it crystal clear.
