### ISSUE TITLE
Is there any difference between "Lastest CI Build" and "Lastest build in AppVeyor"?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#916]
Both Debug & Release is normal in the lastest build of AppVeyor.
But there's an error in "Lastest CI Build" when clicking the code panel:
![error](https://user-images.githubusercontent.com/2529999/31582579-22bfaab4-b1ba-11e7-9d8d-4a95f26eba3d.png)

**Comment by dgrunwald** [comment]
AppVeyor has builds for multiple branches and PRs, so the "latest build" over all branches can be different from the "Latest CI build" link = latest build of the master branch.

We recently updated AvalonEdit to make use of this new property, looks like there's something wrong and AppVeyor continues to package the old AvalonEdit version.
