### ISSUE TITLE
Conversion of bool literals to bool? not pretty

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#918]
The following pretty test fails (see commented test case in `Pretty/Switch.cs`):

	  56   39   		public static bool? SwitchOverNullableEnum(State? state)
	  57   40   		{
	  58   41   			switch (state) {
	  59   42   				case State.False:
	  60      (-) 					return false;
		   43 (+) 					return new bool?(false);
	  61   44   				case State.True:
	  62      (-) 					return true;
		   45 (+) 					return new bool?(true);
	  63   46   				case State.Null:
	  64      (-) 					return null;
		   47 (+) 					return default(bool?);
	  65   48   				default:
	  66   49   					throw new InvalidOperationException();
	  67   50   			}
	  68   51   		}

Seems there is something wrong in `NullableLiftingTransform`.

**Comment by dgrunwald** [comment]
`NullableLiftingTransform` is not involved here: there's no operator that could be lifted.

We need to handle these as redundant casts; probably in the same way we handle `new EventHandler(this.OnClick)`

**Comment by siegfriedpammer** [comment]
A possible fix would be:

	case InvocationResolveResult invocation: {
		if (Expression is ObjectCreateExpression oce && oce.Arguments.Count == 1 && invocation.Type.IsKnownType(KnownTypeCode.NullableOfT)) {
			return this.UnwrapChild(oce.Arguments.Single());
		}
		break;
	}


In `TranslatedExpression.ConvertTo` next to the special cases boxing conversion and method group conversion.

However this only solves the first two cases. We'll have to decide on how to handle default value expressions in general:
* Is it preferable to use `null` instead of `default(possibleReferenceType)` everywhere?
* Should `Nullable<T>` be a special case or should we treat generic type arguments the same? E. g. `where T : class`, should we use `null` instead of `default(T)`?

**Comment by dgrunwald** [comment]
Yes, I think we should prefer `null` over `default` if the type is nullable or a reference type.
