### ISSUE TITLE
[Request] /quit option to coincide with /saveDir

### ISSUE THREAD

**Issue by BenWoodford** [icsharpcode/ILSpy#919]
Given that ILSpy will stay open when using `/saveDir`, a `/quit` command line argument would be nice so that it can be used during automated tasks. When run from say, AppVeyor, ILSpy will block the running of the rest of a script due to staying open past the decompilation stage.

**Comment by dgrunwald** [comment]
ILSpy.exe is not meant to be used in a non-interactive context.
Use the command-line decompiler (ICSharpCode.Decompiler.Console) instead.
