### ISSUE TITLE
Gen:Variant.Johnnie.37124

### ISSUE THREAD

**Issue by tkrasinger** [icsharpcode/ILSpy#922]
Hi, 

Last week F-Secure stated on all my local user-accounts using VS that a virus has been deleted:
C:\users\<user>\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\<somecode>\ILSpy.exe

Saying that the virus is: Gen:Variant.Johnnie.37124

Any ideas?

**Comment by christophwille** [comment]
Was the VSIX installed from the VS Gallery / Marketplace or the build server?

**Comment by siegfriedpammer** [comment]
See https://www.f-secure.com/v-descs/false_positive.shtml

**Comment by tkrasinger** [comment]
installed via vs gallery. I now installed version 1.6 instead of 1.5, rescanned and got no virus warnings.
