### ISSUE TITLE
Null literal white space formatting issue

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#928]
Looks like there should be a `isAfterSpace = false` in `CSharpOutputVisitor.VisitNullReferenceExpression`

**Comment by siegfriedpammer** [comment]
Do you have some test case that reproduces this issue?

**Comment by mmusu3** [comment]
When decompiled the space after the first null is missing
```cs
void Test(object a, object b)
{
    if (a != null && b != null)
        Console.WriteLine();
}
```
