### ISSUE TITLE
Mixed mode assembly: duplicate members

### ISSUE THREAD

**Issue by greenozon** [icsharpcode/ILSpy#935]
Example:  http://prntscr.com/h1277m
comments: there are 2 symbols defined in different modules, but having same name
ILSpy (v3 latest) instead of decoding one line shows duplicate (right panel)
most probably it does not take into account address (module)

2) feature for real men: 
is it possible to do such a sweet magic like SAE (competitor tool) could do:
http://prntscr.com/h12c2z

ideally would be nice to see the string as comment in decompiled panel!

3) what about other native types like arrays of ints/other types...... - any chance to visualize that as well?

thanks

**Comment by siegfriedpammer** [comment]
ad 1) Yes, this is a bug, but we currently do not support mixed mode assemblies officially.

ad 2) As far as I can see, `Simple Assembly Explorer` already uses ILSpy under the hood. You see, we have limited resources and many people use our decompiler engine but hardly ever contribute back.

As this is a feature I personally wouldn't ever need, it'll probably never be implemented without contribution. You are welcome to contribute, or just keep using the "competitor tools" like `Simple Assembly Explorer` or `dnSpy`.

ad 3) Can you please clarify?

**Comment by siegfriedpammer** [comment]
I am closing this, because without the binary it is hard to check if the problem still exists and how we could improve the situation.
If there are similar problems in future, please open a new issue. Thank you!
