### ISSUE TITLE
Crash in CSharp.StatementBuilder.TranslateSwitch (due to empty sequence)

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#959]
CI binary 3.0.0.3209-beta1 (2017-10-31):

```System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.TranslateSwitch(BlockContainer switchContainer, SwitchInstruction inst)
   at ICSharpCode.Decompiler.CSharp.StatementBuilder.Convert(ILInstruction inst)
<snip>
```

I have not yet been able to find the IL provoking this (hint: if possible, emitting class+function it tried to decompile at the time could be good), but I wanted this to be known ASAP. I'll follow up once source is identified.

**Comment by tamlin-mike** [comment]
Found the culprit.
```
	IL_0000: ldarg.1
	IL_0001: brfalse IL_000b
	IL_0006: br IL_0011
	IL_000b: ldarg.1
	IL_000c: brtrue IL_0011
	IL_0011: ret
```
That's the whole function.

**Comment by siegfriedpammer** [comment]
Could you please post the full signature of the IL method? This would make it a lot easier to identify the problem.

**Comment by tamlin-mike** [comment]
```
.method private hidebysig 
	instance void Methodname (
		bool arg
	) cil managed 
{
	// Code size 18 (0x12)
	.maxstack 8
```

**Comment by tamlin-mike** [comment]
Part of the problem narrowing it down (to see what transform is converting that code into a switch), seems to be ILSpy no longer honors the drop-down setting for what transform to run up to (in debug builds), so all transforms are always performed. At least that's what I get from my understanding of `CSharpDecompiler.DecompileBody`.
Is my understanding correct?

Anyway, the problem seems to be `SwitchDetection.UseCSharpSwitch` mis-detecting this as a switch.

Based on the IL provoking this, I'd guesstimate that's something like remnants of `#if`'d-out code - since it's clearly nonsense (the rest of the assembly seems non-obfuscated, at least at first glance, so I have no reason to believe this is obfuscation).

**Comment by dgrunwald** [comment]
ILSpy does honor that drop-down setting, it's just that this crash happens in the ILAst->"C# no transforms" step. The ILAst itself has so many substeps that we removed those from the dropdown -- instead the ILAst view has a "Show Steps" button.

Currently we're using switch (on integers) instead of a series of ifs when:
 * switch replaces more than just one 'if'
 * no single section needs more than 50 case labels

I guess we should add "there's more than 1 section" to that list.
Still, a switch with only a "default" section is valid in the ILAst and in C#, so the translation to C# shouldn't crash.

**Comment by tamlin-mike** [comment]
A "fix" I locally employed was in `StatementBuilder.TranslateSwitch`, 191:
```
- if (switchContainer != null) {
+ if (switchContainer != null && stmt.SwitchSections.Count > 0) {
```

I don't know if it's just hiding the underlying problem, but at least ILSpy doesn't crash on this construct anymore. It generates a completely empty switch, which I'm not sure is valid C#, but it's (for me, for now) better than nothing.

**Comment by siegfriedpammer** [comment]
I will push a fix for this in a few minutes.

**Comment by tamlin-mike** [comment]
@dgrunwald I totally missed that "Show Steps" button! Thanks for pointing it out. Yeah, that makes sense - the drop list would otherwise indeed have grown to unmanageable proportions.
