### ISSUE TITLE
Decompile methods now include using statements?

### ISSUE THREAD

**Issue by jeremymeng** [icsharpcode/ILSpy#961]
This is using the 3.0.03206-beta1 package

```csharp
using System;
using System.Linq;
using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.TypeSystem;

namespace ConsoleApp8
{
    class Program
    {
        static void Main(string[] args)
        {
            var decompiler = new CSharpDecompiler(@"C:\vso\yumeng\msil-decompiler-vscode\bin\msildecompiler\Mono.Cecil.dll", new DecompilerSettings());
            var name = new FullTypeName("Mono.Cecil.Cil.ILProcessor");
            var typeInfo = decompiler.TypeSystem.Compilation.FindType(name).GetDefinition();
            var member = typeInfo.Methods.Single(p => p.Name.Equals("Replace"));
            var cecilMethod = decompiler.TypeSystem.GetCecil(member).Resolve();
            Console.WriteLine(decompiler.DecompileAsString(cecilMethod));
        }
    }
}
```

Expected:
Output doesn't include using statements

Actual:
Output has using statements

```csharp
using System;

public void Replace(Instruction target, Instruction instruction)
{
        if (target == null)
        {
                throw new ArgumentNullException("target");
        }
        if (instruction == null)
        {
                throw new ArgumentNullException("instruction");
        }
        this.InsertAfter(target, instruction);
        this.Remove(target);
}
```

**Comment by dgrunwald** [comment]
Why would you expect using statements to be missing?
If you copied the method into a C# interactive window, you'd need the using statements.

**Comment by jeremymeng** [comment]
I didn't know they are intended for script usage. It just looked weird without the containing type.  And the implicit namespace of for example `Instruction` isn't imported by a using (so I'd need to fully qualify them I guess).

**Comment by dgrunwald** [comment]
Yeah, for script usage we'd also need an explicit import for the namespace.
You're not the first who finds the usings on method-level strange. But I don't really see the harm in having this extra information available (especially given that they are collapsed by default).

Note that the usings at class level are really the same thing -- they're also out of context, as it's just the class itself without the namespace.

Note that `DecompilerSettings` has `bool UsingDeclarations` and `bool FullyQualifyAmbiguousTypeNames` if you need to customize this behavior.

**Comment by jeremymeng** [comment]
Makes sense.

**Comment by jeremymeng** [comment]
`FullyQualifyAmbiguousTypeNames=true` doesn't fully qualify `Instruction` for me in this example.  Are there any other settings that make it work, like what ILSpy Gui is showing?
![image](https://user-images.githubusercontent.com/7583839/32294633-f0228e6c-bf03-11e7-9049-ddca272e56e5.png)

**Comment by dgrunwald** [comment]
That might be an old version of the ILSpy GUI where the "current namespace" wasn't set correctly when decompiling a single method.
There isn't really any way to enforce the use of fully-qualified names everywhere.

What do you need these full types names for? Maybe your usecase is better served by inspecting the annotations on the syntax tree (similar to what ILSpy uses for showing tooltips).

**Comment by jeremymeng** [comment]
I am playing with the new decompiler in my VS Code extension (mentioned in https://github.com/icsharpcode/ILSpy/issues/941).  So I'd like to match whatever ILSpy GUI has as much as I can.  I don't have any particular use cases.
