### ISSUE TITLE
Why can't compile it?

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#965]
I get ILSpy source by clone "https://github.com/icsharpcode/ILSpy.git" in Visual Studio 2017
But I get these errors:

Error	MSB3249	Application Configuration file "app.config" is invalid. Could not find file '...\ILSpy\ILSpy\app.config'.
[Failure] Could not find file '...\ILSpy\ICSharpCode.Decompiler\Properties\AssemblyInfo.cs'.
[Failure] Could not find file '...\ILSpy\ILSpy\Properties\AssemblyInfo.cs'.
[Failure] Could not find file '...\ILSpy\ICSharpCode.Decompiler\Properties\AssemblyInfo.cs'.

**Comment by tamlin-mike** [comment]
1. I think you need VS15.3 (a.k.a. 2017.3) or later.
2. You need to install .NET Core SDK 2 I grabbed it from https://www.microsoft.com/net/download/visual-studio-sdks
3. You need to have git in PATH for the devenv process (it only uses it in .ps1 script to generate revision). If you don't want to install more stuff into VS, you can open a developer command prompt, add git to your PATH env. var. and start devenv.exe from it (since it inherits the env.).

After that I got it compiling. Hope it works for you.
++luck;

**Comment by CreateAndInject** [comment]
Do you mean I must install git?
I don't install git, because Visual Studio 2017 can do it.

**Comment by christophwille** [comment]
Yes. We are relying on the command line version of git for our build tasks (we have a base commit hash for ..1 and we calculate the current revision based on the delta of commit numbers)

**Comment by siegfriedpammer** [comment]
Git is no longer required. We'll use dummy versions if git is not found.

> I don't install git, because Visual Studio 2017 can do it.
Please see https://developercommunity.visualstudio.com/content/problem/26539/vs2017-deployed-gitexe-not-usable.html ... it's stated that VS uses a stripped down version of git, which might not be working in all cases.

**Comment by CreateAndInject** [comment]
All the same, I can't compile with the same errors.

**Comment by siegfriedpammer** [comment]
1) Did you follow the steps in the README?
2) Can you please post your PATH variable? (You could send me a PM on gitter)

**Comment by CreateAndInject** [comment]
I only download the lastest Visual Studio 2017(15.4.2), and install .net core 1.1&2.0, and clone dnSpy in vs2017, don't do anything else.
My  PATH variable is:
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\

**Comment by siegfriedpammer** [comment]
> and clone dnSpy in vs2017, don't do anything else.

I think you are talking about ILSpy, but how can I clone a repository in VS2017... didn't even know that you could do that... I guess you are missing the submodules as well...

Your path looks fine...

**Comment by siegfriedpammer** [comment]
Does it work with the latest fix?

**Comment by CreateAndInject** [comment]
No, all the same.

**Comment by siegfriedpammer** [comment]
Does it work for you when you comment out the content of find-git in updateassemblyinfo.ps1 except for the return false?

**Comment by CreateAndInject** [comment]
Do you mean "\BuildTools\update-assemblyinfo.ps1"?
Both
function Find-Git() {
return $false;
}
and 
function Find-Git() {
return $true;
}
don't work

**Comment by siegfriedpammer** [comment]
Could you please post the build output with
function Find-Git() {
return $false;
}

Thank you!

**Comment by CreateAndInject** [comment]
$PSScriptRoot is null

**Comment by CreateAndInject** [comment]
This time it works!
But I have two questions:
1. Does it mean those commits about this issue before the lastest commit are unnecessary？
2. There's an error:
 System.Threading.Mutex doesn't contains method "Dispose".

**Comment by siegfriedpammer** [comment]
1. I don't think they are unnecessary.
2. How is this possible? Do you have .NET 4.0 installed?

**Comment by CreateAndInject** [comment]
There are 2.0, 3.0, 3.5, 4.0, 4.5, 4.5.1, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7 on my OS.

Maybe the compiler run on .net 2.0 ?

**Comment by CreateAndInject** [comment]
I add "[System.Environment]::Version", it shows 2.0

**Comment by siegfriedpammer** [comment]
I have no idea... It works on our machines including the build server without any extra configuration. But, as it seems it's only a minor problem. You can either force powershell to load .NET 4.0 by editing powershell.exe.config or try other solutions found online.

As the original problem is fixed, I will close this. Good luck!
