### ISSUE TITLE
MiniJSON as test

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#966]
As I recalled this having generated problems in the past when decompiling it, I grabbed a copy of
  https://github.com/Jackyjjc/MiniJSON.cs
and found it to be a nice test for a few issues.

A non-optimized command-line build (with csc.exe 2.4.0.62122) displayed it indeed displays a few problem areas for ILSpy.

* Nested switch in NextToken.get (inner on string, so maybe it's just general string-switching?).
* A bunch of "dead"/unused locals.
* Unneeded `default`initialization of  `out` variables (I know there's a separate issue for this, but since the `out` keyword is properly used, maybe the `default(blah)` could be found in scope and dropped?).
* Unneeded casts to `object` (possibly only for return values?).

Just thought it would be nice to have a repro with source available for some issues.

**Comment by siegfriedpammer** [comment]
* The code in `NextToken.get` looks quite good. But `ParseString` is not quite right... not sure if we can get rid of the gotos...
* Did not closely look for anything, but at first glance it seems quite OK...
* Yes, out variables are still not done and there are some issues to resolve:
  * remove default initialization
  * infer name from out parameter
* I don't see any casts to object anymore... looks like we nailed that ;)

If you find any other issues, please report them :)

**Comment by siegfriedpammer** [comment]
Just tested MiniJSON.cs again... there are no more gotos and no extra variables as we now support out vars.

Not sure if we should make this a pretty test, because it would need some work to make it conform to the usual decompiler output format.

**Comment by siegfriedpammer** [comment]
I think, a correctness test is sufficient in this case.
