### ISSUE TITLE
The lastest commit[ed0ed8f] can not make everyone happy.

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#969]
It seems ILSpy always has build errers.
Yesterday, I can build it.
Tody, I delete it, and clone twice.
So there are two ILSpy directoies on my OS, $PWD is null in one, but is not null in another, but both can not build.

**Comment by CreateAndInject** [comment]
Now, one can build, and another can't.
But I find a prolbem:
If I copy and past the root direcotry, so build it, it will fail
for example:
C:\ILSpy can build
Copy it as:
C:\ILSpy2, build it ,it seem say: C:\ILSpy exist, it seems it use the old path.

**Comment by CreateAndInject** [comment]
I get it, if the path contains some char, it will fail
such as:
C:\My ILSpy (space)
C:\[ILspy]   ([])

**Comment by CreateAndInject** [comment]
If the .ps1 file is in **E:\abc\[Tools]** Get-Location will return "C:\"
If the .ps1 file is in **E:\abc\[Tools** Get-Location will occur exception

**Comment by dgrunwald** [comment]
It seems that powershell has massive problems with paths containing `[`. I don't think there's any sane way we can fix this; you'll have to use a different directory name.

**Comment by CreateAndInject** [comment]
Can't build also if the path contains space.

**Comment by dgrunwald** [comment]
I just added some quotes to the post-build command. Please post the error message if there's still any problem with spaces.

**Comment by CreateAndInject** [comment]
That's ok with space now!
It seems it's powershell bug about "[", so it can not resolve except migrating to CMD.
