### ISSUE TITLE
how do use ILspy i download it on the ILspy.net and theres only a bunch of files in the winrar

### ISSUE THREAD

**Issue by vorticus** [icsharpcode/ILSpy#973]
there is no executable or anything to open or use ILSpy

**Comment by christophwille** [comment]
The ilspy.net Homepage points to https://github.com/icsharpcode/ILSpy/releases/download/v2.4/ILSpy_Master_2.4.0.1963_Binaries.zip for the "binaries" download link - it contains all the files that are supposed to be in this zip archive.
