### ISSUE TITLE
null comparisons simplification

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#974]
Instead of worrying about casting to `object` and using `==` to compare to `null`, to avoid e.g. infinite recursion, we could use `is null` and forget about the casting.

```
bool IsNullTest1(String s) { return (object)s == null; }
bool IsNullTest2(String s) { return s is null; }
```
At least the compiler I tested with is generating the exactly same code.

Comments?

**Comment by dgrunwald** [comment]
The `is` syntax tends to get ugly if you need negation, especially if `s` is a more complex expression.
```
bool IsNullTest1(SomeType s) { return (object)s != null; }
bool IsNullTest2(SomeType s) { return !(s is null); }
bool IsNullTest3(object obj) { return obj != null; }
bool IsNullTest4(object obj) { return !(obj is null); } // clearly worse than IsNullTest3
```

Also, in the special case of `string`s being compared with a `null` literal, we shouldn't introduce a cast. The C# compiler normally calls `System.String.op_Equality` when using `operator ==` on `string`, but in the special case of `s == null` it emits a reference comparison instead.

**Comment by dgrunwald** [comment]
I don't think we'll ever use `is` for simple null comparisons. If there's an overloaded operator we have to avoid, we'll just keep the cast around.
For the special case of strings (and delegates), current ILSpy no longer generates redundant casts, so I'm considering this issue fixed.

**Comment by tamlin-mike** [comment]
Gotcha. I consider the rationale sane.
