### ISSUE TITLE
turn off lambda decompliation

### ISSUE THREAD

**Issue by delapiero** [icsharpcode/ILSpy#978]
Which option should I use to get something like:

`IEnumerable<FilterInfo> featuresFiltersValues = this.Filters.Select<IFilter, FilterInfo>((Func<IFilter, FilterInfo>) (x => x.GetFilterInfo()));`

instead of:
```
IEnumerable<IFilter> arg_25_0 = this.Filters;
Func<IFilter, FilterInfo> arg_25_1;
if ((arg_25_1 = ProductsListViewModel.<>c.<>9__134_0) == null)
{
	arg_25_1 = (ProductsListViewModel.<>c.<>9__134_0 = new Func<IFilter, FilterInfo>(ProductsListViewModel.<>c.<>9.<GetLotRows>b__134_0));
}
IEnumerable<FilterInfo> featuresFiltersValues = arg_25_0.Select(arg_25_1);
```

Sorry if it is inappropriate place to ask a question

**Comment by siegfriedpammer** [comment]
Actually the behavior you expect should be the default. Could you please try the (latest version)[https://ci.appveyor.com/api/projects/icsharpcode/ilspy/artifacts/ILSpy_binaries.zip?branch=master&job=Configuration%3A+Release]?

If it doesn't work properly, please post the IL code of the method (including the signature/header). Thank you for your help!

**Comment by delapiero** [comment]
Works fine on ILSpy version 3.0.0.3332-beta2, 
I've been using ILSpy version 2.4.0.1963, which "Check for updates" reports as lastest release
Thank you for such quick response and for help
