### ISSUE TITLE
Invariant check triggers for (esoteric) fixed var conditional initialization

### ISSUE THREAD

**Issue by tamlin-mike** [icsharpcode/ILSpy#981]
I have not been able to reproduce this from source code, and it's unknown what compiler managed to produce it, but it displays a DFA PHI problem in ILSPy.

The problem should be obvious:
From 00d5 the decompiler deduces this is 'Ref', but coming down to d7/d8 it thinks it's trying to assign an integer to it, triggering the following invariant check:

```
IL.StLoc.CheckInvariant(ILPhase) Line 36
IL.ILInstruction.CheckInvariant(ILPhase) Line 78
IL.Block.CheckInvariant(ILPhase) Line 105
IL.ILInstruction.CheckInvariant(ILPhase) Line 78
IL.BlockContainer.CheckInvariant(ILPhase) Line 181
IL.ILInstruction.CheckInvariant(ILPhase) Line 78
IL.ILFunction.CheckInvariant(ILPhase) Line 78
CSharp.CSharpDecompiler.DecompileBody
```
At the failing assert, value.ResultType is `I`, but variable.StackType is `Ref`.

The source code producing the problematic IL seems it should be something like
```
fixed (byte* ptr = (byteArray != null && byteArray.Length != 0) ? &byteArray[0] : null) {}
```
but all attempts to repro with Microsoft csc.exe fails, complaining that about `&byteArray[0]`
`You can only take the address of an unfixed expression inside of a fixed statement initializer`

Well DUH, compiler, what do you think I'm trying to do?
	

```
.method public hidebysig 
	instance void MethodName (
		<args omitted>
	) cil managed 
{
	.locals init (
		[3] uint8* pinned,
		[4] int16*,
	)
		<snip>
		// if (this.byteArray != null && this.byteArray.Length != 0)
		IL_00b7: ldarg.0
		IL_00b8: ldfld uint8[] ClassName::byteArray
		// (no C# code)
		IL_00bd: brfalse.s IL_00d7

		IL_00bf: ldarg.0
		IL_00c0: ldfld uint8[] ClassName::byteArray
		IL_00c5: ldlen
		IL_00c6: conv.i4
		IL_00c7: brfalse.s IL_00d7

		// val = (?)ref this.byteArray[0];
		IL_00c9: ldarg.0
		IL_00ca: ldfld uint8[] ClassName::byteArray
		IL_00cf: ldc.i4.0
		IL_00d0: ldelema [mscorlib]System.Byte
		// (no C# code)
		IL_00d5: br.s IL_00d9

		// intPtr = (IntPtr)(void*)null;
		IL_00d7: ldc.i4.0
		// val = (?)(long)intPtr;
		IL_00d8: conv.u

		// (no C# code)
		IL_00d9: stloc.3   // Invariant triggers here
		
		// short* ptr2 = (short*)ptr;
		IL_00da: ldloc.3
		IL_00db: stloc.s 4
```

I'm not sure how to proceed with this, since I can't create a src repro for it, but figured it prudent to still document the issue.

**Comment by dgrunwald** [comment]
Is this even valid IL?

Trying a similar method myself, I'm getting a peverify error:
```
[offset 0x0000000D] Non-compatible types on stack depending on path.
```

I've now fixed this under the assumption that the non-`ref` branch is implicitly converted to `ref` when the branches meet. I believe this should fix the assertion you're seeing.
