### ISSUE TITLE
Add keyboard shortcut for "analyze"

### ISSUE THREAD

**Issue by CreateAndInject** [icsharpcode/ILSpy#984]
1. add a keyboard shortcut "Ctrl+R" for "Analyze" like Reflector.
2. When we viewing decompiltion code, we allways view the method, so I think ILSpy should sort the members as:
`NestedType, cctor, ctor, method, property, event, field`
Now, ILSpy places fields before methods, so we must scroll to find method.

**Comment by siegfriedpammer** [comment]
As for the second suggestion: We're not planning to change the order of items in the near future.
