### ISSUE TITLE
open assemblies for compact framework lead to crash

### ISSUE THREAD

**Issue by trivalik** [icsharpcode/ILSpy#985]
Just try to open C:\Program Files (x86)\Microsoft Visual Studio 8\SmartDevices\SDK\CompactFramework\2.0\v2.0\WindowsCE\System.Windows.Forms.dll

and expand then the tree, immediately a crash will ocure with stacktrace. I could not grab because it get immediately frozen.

**Comment by siegfriedpammer** [comment]
I just tried to reproduce this, but I could get it to crash only once: in `SharpTreeNodeView.CalculateIndent` `Node` was null. Guess this is the same as #857...

**Comment by dgrunwald** [comment]
Hopefully fixed in 930ed379730efadff51e3302ea5739fb143332f3.
