### ISSUE TITLE
Missing variable type for string concat statement

### ISSUE THREAD

**Issue by mmusu3** [icsharpcode/ILSpy#995]
Test case:
```cs
void Test(string str1, string str2)
{
    var a = str1 + " ";
}
```
Output:
```cs
private void Test(string str1, string str2)
{
	? val = str1 + " ";
}
```

**Comment by siegfriedpammer** [comment]
I cannot reproduce this... I suspect you are missing a reference to mscorlib, which normally should be loaded automatically. Could you please post the binary, you tried to decompile?

**Comment by mmusu3** [comment]
Seems to only happen in release mode.
[ILSpyTests.zip](https://github.com/icsharpcode/ILSpy/files/1513725/ILSpyTests.zip)

**Comment by mmusu3** [comment]
Looks like I accidentally left a second string parameter in the tests, however the problem still exists without it.

**Comment by siegfriedpammer** [comment]
Thanks for the report!
